src_old/objects/Account.object
<CustomObject>
    <fields>
        <fullName>IsApproved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Approved</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src_old/objects/Location__c.object
<CustomObject>
    <description>Location defines a location and its type, address, and the Retailer is it associated with. Location is related to Retailer, Job, and Project Location.</description>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OneHubRetailerId__c</fullName>
        <label>OneHub Retailer ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Retailer__c</fullName>
        <label>Retailer</label>
        <referenceTo>Retailer__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <fields>
        <fullName>ApprovalDate__c</fullName>
        <description>A field that indicates the date and time that the Project was approved.</description>
        <inlineHelpText>The date and time that the project was approved.</inlineHelpText>
        <label>Approval Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ApprovalRequestDate__c</fullName>
        <description>A field that indicates the date and time the Project was last submitted for approval.</description>
        <inlineHelpText>Date and time the project was last submitted for approval.</inlineHelpText>
        <label>Approval Request Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>BudgetedLocationsCount__c</fullName>
        <description>An entry field that indicates the number of budgeted locations for the Project.</description>
        <inlineHelpText>Expected number of locations</inlineHelpText>
        <label>Budgeted Locations Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>An entry field that indicates the end date of the Project.</description>
        <inlineHelpText>The last date available to complete execution</inlineHelpText>
        <label>Project End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IsJobManualRegenReqd__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The check box will be set when a the Job Manual has to be generated.</description>
        <inlineHelpText>The check box will be set when a the Job Manual has to be generated.</inlineHelpText>
        <label>Regenerate Job Manual</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsLocked__c</fullName>
        <defaultValue>false</defaultValue>
        <description>A checkbox that indicates that the Project is locked</description>
        <inlineHelpText>If selected, the project is locked.</inlineHelpText>
        <label>Is Locked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsSplit__c</fullName>
        <defaultValue>false</defaultValue>
        <description>A checkbox that indicates if the project is split among the accounts.</description>
        <inlineHelpText>If selected, the project is split among accounts.</inlineHelpText>
        <label>Is Split</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MaxServiceCount__c</fullName>
        <description>A field that indicates the maximum number of services for the Project.</description>
        <inlineHelpText>The maximum number of services for the project.</inlineHelpText>
        <label>Max Service Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MinServiceCount__c</fullName>
        <description>A field that indicates the  minimum number of services for the Project.</description>
        <inlineHelpText>The minimum number of services for the project.</inlineHelpText>
        <label>Min Service Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OneHubRetailerId__c</fullName>
        <description>A field that indicates the ID number of the OneHub retailer.</description>
        <inlineHelpText>The ID number of the OneHub retailer.</inlineHelpText>
        <label>OneHub Retailer Id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProjectLaunchDate__c</fullName>
        <description>A field that indicates the launch date for the Project</description>
        <inlineHelpText>The date the project becomes visible on execution platforms and fulfillment entities.</inlineHelpText>
        <label>Project Launch Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ProjectScheduleOption__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Determines soft-dated or hard-dated scheduling of work</inlineHelpText>
        <label>Project Schedule Option</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>ScheduleOption__c.IsActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ScheduleOption__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Type</label>
        <referenceTo>ProjectType__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Retailer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Retailer</label>
        <referenceTo>Retailer__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SplitType__c</fullName>
        <description>A picklist that indicates if the project is to be a solo or split across multiple accounts.</description>
        <inlineHelpText>Select the split type for the project.</inlineHelpText>
        <label>Project Split Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Solo</fullName>
                </value>
                <value>
                    <fullName>Percentage (%)</fullName>
                </value>
                <value>
                    <fullName>Amount ($)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>An entry field that indicates the start date of the Project.</description>
        <inlineHelpText>The date available to start execution</inlineHelpText>
        <label>Project Start Date</label>
        <type>Date</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ProjectAccount__c.object
<CustomObject>
    <description>Project Account maps an Account to a Project and defines how the Account will be billed. Project Account is related to Project, Account, and Account Address.</description>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Project_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Account</label>
    <nameField>
        <displayFormat>PA-{0000000}</displayFormat>
        <label>Project Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectLocation__c.object
<CustomObject>
    <description>Project Location relates a Location to a Project. Project Location is related Project, Job, and Location.</description>
    <fields>
        <fullName>OneHubRetailerId__c</fullName>
        <label>OneHub Retailer Id</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProjectType__c</fullName>
        <formula>Project__r.ProjectType__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>ProjectLocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Retailer__c</fullName>
        <formula>Project__r.Retailer__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Retailer</label>
        <type>Text</type>
    </fields>
    <label>Project Location</label>
    <nameField>
        <displayFormat>PL-{0000}</displayFormat>
        <label>Location ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectService__c.object
<CustomObject>
    <description>Project Service relates a Service to a Project and is a container used to define the instance of a Service for a specific Project. Project Service is related to Project, Job, Project Service Attribute, Project Service Certification, Project Service Equipment, Project Service Material, Project Service Question, Project Service Target, and Service.</description>
    <fields>
        <fullName>OneHubRetailerId__c</fullName>
        <label>One Hub Retailer ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProjectType__c</fullName>
        <formula>Project__r.ProjectType__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>ProjectServices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Retailer__c</fullName>
        <formula>Project__r.Retailer__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Retailer</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>Project Services</relationshipLabel>
        <relationshipName>ProjectServices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Service</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectType__c.object
<CustomObject>
    <description>Project Type defines a collection of Services and sets configuration options for a Project. Project Type is related to Project, Project Type Execution Company, Project Type Service, and Location Assignment.</description>
    <fields>
        <fullName>LaunchLeadTime__c</fullName>
        <label>Launch Lead Time</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MaxServiceCount__c</fullName>
        <label>Max Service Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MinServiceCount__c</fullName>
        <label>Min Service Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ScheduleOption__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Schedule Option</label>
        <referenceTo>ScheduleOption__c</referenceTo>
        <relationshipLabel>Project Types</relationshipLabel>
        <relationshipName>Project_Types</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Types</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/Retailer__c.object
<CustomObject>
    <description>Retailer stores the retailers for the system. Retailer is related to Location, Retailer Service, Retailer Service Certification, and Retailer Service Equipment.</description>
    <fields>
        <fullName>OneHubRetailerId__c</fullName>
        <label>One Hub Retailer ID</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Retailer</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Retailers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ScheduleOption__c.object
<CustomObject>
    <description>Schedule Option defines the schedule options that are available when building a Project. Schedule Option is related to Project and Job.</description>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates that the Schedule Option is available at the org level to set visibility when building a Project.</description>
        <inlineHelpText>Indicates that the Schedule Option is available at the org level to set visibility when building a Project.</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Schedule Option</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/classes/TestDataSetupExt.cls
public with sharing class TestDataSetupExt {
    public integer projCount{get;set;}
    public integer projServCount{get;set;}
    public integer projLocCount{get;set;}
    public string LocNumber{get;set;}
    public List<SelectOption> AllServicesList{get;set;}
    public List<SelectOption> SelectedServicesList{get;set;} 
    public Project__c project{get;set;}
    public List<SelectOption> AllStatus{get;set;}
     public string selectedStatus{get;set;}   
    public TestDataSetupExt(ApexPages.StandardController controller) {
        //projCount=1;
        //projServcount=2;
        //projLocCount=2;      
        String message = '' + ApexPages.CurrentPage().GetParameters().Get('message');
        if(message != 'null')
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Info,message));
        }
            
        this.project = (Project__c) controller.getRecord();
        
        AllServicesList= new List<SelectOption>();
        for(service__c svc : [select id,name from service__c])
        {
          AllServicesList.add(new SelectOption (svc.name, svc.name));
        }
        SelectedServicesList = new List<SelectOption>(); 
        
        AllStatus= new List<SelectOption>(); 
        
        AllStatus.add(new SelectOption (CONSTANTS.PROJECT_STATUS_PLANNING, CONSTANTS.PROJECT_STATUS_PLANNING));
        AllStatus.add(new SelectOption (CONSTANTS.PROJECT_STATUS_BOOKED, CONSTANTS.PROJECT_STATUS_BOOKED));
    }
    

    
    public PageReference Save()
    {       
        try{ 
            //create proj
            /*project__c proj = new project__c();
            proj.name = this.project.name;
            proj.projecttype__c = [select id from projecttype__c limit 1].id;
            proj.retailer__c = [select id from retailer__c limit 1].id;
            proj.ProjectScheduleOption__c = this.project.ProjectScheduleOption__c ;*/
            TriggerUtil.SkipAllTriggers();
            ProjectType__c projectType = [SELECT name,maxservicecount__c,minservicecount__c, LaunchLeadTime__c FROM ProjectType__c limit 1 ];
            retailer__c retailer = [select id,OneHubRetailerId__c from retailer__c limit 1];
            account acct = [select id from account where IsApproved__c =true limit 1];
            
            list<project__c> projList = new list<project__c>();
            project__c proj= new project__c();
            
            ScheduleOption__c scopt = [select id from ScheduleOption__c where isactive__c=true limit 1];
            
            for(integer i=1;i<=projCount;i++)
            {
                proj= new project__c();
                proj.projecttype__c = projectType.id;
                proj.retailer__c = retailer.id;
                proj.IsSplit__c = true;
                proj.BudgetedLocationsCount__c = (projLocCount!=0)?projLocCount:(LocNumber.split(',')).size();
                proj.OneHubRetailerId__c = retailer.OneHubRetailerId__c;
                proj.SplitType__c='Solo';
                proj.maxservicecount__c = projectType.maxservicecount__c;
                proj.minservicecount__c = projectType.minservicecount__c;
                proj.startdate__c=this.project.startdate__c;
                proj.enddate__C =this.project.enddate__C;
                proj.ProjectScheduleOption__c=scopt.id;
                proj.islocked__c=this.project.islocked__c;
                if(this.project.ProjectLaunchDate__c!=null)
                    proj.ProjectLaunchDate__c=this.project.ProjectLaunchDate__c;
                else
                    proj.ProjectLaunchDate__c = this.project.StartDate__c.addDays(projectType.LaunchLeadTime__c.intValue() * -1);
                
                proj.IsJobManualRegenReqd__c = true;
                proj.name = this.project.name ;
                
                system.debug('~~~~~selectedStatus  ~~~~'+selectedStatus);
                if(selectedStatus==CONSTANTS.PROJECT_STATUS_BOOKED)
                {
                    system.debug('~~~~ CONSTANTS.PROJECT_STATUS_BOOKED ~~~');
                    proj.ApprovalRequestDate__c  = System.Now();
                    proj.ApprovalDate__c = System.Now();
                    proj.BookedProjectStartDate__c = project.StartDate__c;
                    proj.BookedProjectEndDate__c = project.EndDate__c;
                    proj.Status__c = CONSTANTS.PROJECT_STATUS_BOOKED;      
                }
                else
                    proj.status__C=CONSTANTS.PROJECT_STATUS_PLANNING;
            
                if(projCount> 1)
                    proj.name = this.project.name +'  -  '+i;
                
                
                projList.add(proj);
            }
            insert projList;
            //this.project.ProjectLaunchDate__c = this.project.StartDate__c.addDays(projectType.LaunchLeadTime__c.intValue() * -1);
            
            system.debug('~~~'+projList+'~~~'+projList.size());
            list<Id> listOfProjIds = new list<Id>();
            //list<Database.Saveresult> insertResults =Database.insert(projList, false);
            //for (Database.SaveResult sr : insertResults) {
            for(project__c p:projList){
                //if (sr.isSuccess()) {
                    system.debug('~~~~~~'+p.Id);
                    listOfProjIds.add(p.id);
                //}
            }
            
            string ServNames='';
            if(projServCount==0)
               {
                   SelectedServicesList = new List<SelectOption>();         
                   SelectedServicesList.add(new SelectOption ('test', 'test'));
                   
                   for(SelectOption so: SelectedServicesList){
                       ServNames= ServNames + so.getValue()  + ',';
                   }
               }
               
            if(projLocCount>0)
               LocNumber  = '';   
            
            id[] param = listOfProjIds;
            system.debug('listOfProjIds~~~'+listOfProjIds+'~~~'+ integer.valueof(projLocCount) +'~~~'+ LocNumber  +'~~~'+ integer.valueof(projServCount)  +'~~~'+SelectedServicesList);
            
            Database.executeBatch(new BatchTestDataSetup(param,projLocCount,LocNumber,projServCount,ServNames,selectedStatus), 1);
            
            //Database.executeBatch(new BatchTestDataSetup(listOfProjIds,integer.valueof(projLocCount),LocNumber,integer.valueof(projServCount),SelectedServicesList), 200);
            
            
            /*
                       
            ProjectAccount__c updatedPA = new ProjectAccount__c();
            updatedPA.Account__c = acct.id;
            updatedPA.IsPrimary__c = true;
            updatedPA.Project__c = this.project.id;
            updatedPA.SplitValue__c = 100;
            insert updatedPA;
            

            //location
            list<projectlocation__c> plocList = new list<projectlocation__c>();
            list<location__c> plocVal = new list<location__c>();
            projectlocation__c ploc;
            string LocationQry;
            if(projLocCount!=0)
            {
                LocationQry='select id from location__c limit ' + projLocCount;
                plocVal = Database.query(LocationQry);
            }
            else{
                plocVal =[select id from location__c where  locationnumber__c IN : LocNumber.Split(',')]; 
            }
            system.debug('~~~~123~~~'+LocationQry+'    '+plocVal );
            
            for(location__c loc: plocVal )
            {
                ploc = new projectlocation__c();
                ploc.project__C = this.project.id;
                ploc.location__c = loc.id;
                plocList.add(ploc);              
            }
            insert plocList;
            
            //service
            projectService__c pserv;
            list<projectService__c> pserList = new list<projectService__c>();
            list<Service__c> svcL= new list<Service__c>();
            if(projServCount!=0){
                string ServiceQry='select id from service__c limit ' + projServcount;
                svcL = Database.query(ServiceQry);
            }
            else{
                set<string> setObj = new set<string>();
                for (SelectOption so : SelectedServicesList)
                {
                    setObj.add(so.getValue());
                }
                svcL=[select id from service__c where  name IN : setObj];
            }

            for(Service__c serv: svcL)
            {
                pserv = new projectService__c();
                pserv.project__C = this.project.id;
                pserv.Service__c = serv.id;
                pserv.ResponsibleForExecution__c = 'Execution Company';
                pserv.OneHubRetailerId__c = retailer.OneHubRetailerId__c;
                pserv.JobManualFileName__c = ''; 
                pserv.IncludeAutoGenManual__c = false;
                pserv.JobManualTemplate__c  = 'Standard';
                pserList.add(pserv);              
            }
            insert pserList ;
            
           
            system.debug('~~~~ schedulingStrategyObject ~~~');
             SchedulingStrategy schedulingStrategyObject = SchedulingStrategyFactory.getSchedulingStrategy(projectType.Name);
             List<ProjectLocation__c> scope = Database.query(schedulingStrategyObject.getSchedulableLocationsQuery(this.project));
             system.debug('~~~~~scope'+scope);
             SchedulingStrategyObject.ScheduleLocations(scope, String.valueof(this.project.ID));
            
            
            if(selectedStatus==CONSTANTS.PROJECT_STATUS_BOOKED)
            {
                system.debug('~~~~ CONSTANTS.PROJECT_STATUS_BOOKED ~~~');
                this.project.ApprovalRequestDate__c  = System.Now();
                this.project.ApprovalDate__c = System.Now();
                this.project.BookedProjectStartDate__c = project.StartDate__c;
                this.project.BookedProjectEndDate__c = project.EndDate__c;
                this.project.Status__c = CONSTANTS.PROJECT_STATUS_BOOKED;           
                update this.project;
            }
             
             */
             
             
                    
            system.debug('~~~~ the end ~~~');
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.info,'Successfully inserted !!!' ));
            PageReference pr = new PageReference('/apex/TestDataSetup');
             pr.setRedirect(true);
            pr.GetParameters().Put('message', 'Successfully inserted !!!');
            return pr;
   
        }
        catch(exception ex){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,ex.getmessage()));
        }  
                     
             return null;
    }
}