src_old/objects/AccountBudget__c.object
<CustomObject>
    <description>AccountBudget</description>
    <fields>
        <fullName>ExecutedAgainstBudget__c</fullName>
        <label>Executed Against Budget</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planning</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Ended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Account Budget</label>
    <nameField>
        <label>Budget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Budgets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/objects/ProjectAccount__c.object
<CustomObject>
    <description>Project Account maps an Account to a Project and defines how the Account will be billed. Project Account is related to Project, Account, and Account Address.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Project Accounts</relationshipLabel>
        <relationshipName>Project_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Account</label>
    <nameField>
        <displayFormat>PA-{0000000}</displayFormat>
        <label>Project Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectInvoice__c.object
<CustomObject>
    <fields>
        <fullName>ProjectAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Account</label>
        <referenceTo>ProjectAccount__c</referenceTo>
        <relationshipLabel>Project Invoices</relationshipLabel>
        <relationshipName>Project_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Invoiced</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Grouped</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TotalProjectInvoiceAmountCalculated__c</fullName>
        <label>Total Invoice Amount Calculated</label>
        <summarizedField>ProjectInvoiceLineItem__c.TotalLineItemAmount__c</summarizedField>
        <summaryForeignKey>ProjectInvoiceLineItem__c.ProjectInvoice__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Project Invoice</label>
    <nameField>
        <displayFormat>INV-{000000000}</displayFormat>
        <label>Project Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/ProjectInvoiceTriggerHandler.cls
public class ProjectInvoiceTriggerHandler extends TriggerHandler {
    
    public override void afterInsert(){
       if (TriggerUtil.skipProjectInvoiceTrigger) return;
       
        Set<String> projectInvoiceIds = new Set<String>();
                
        for(ProjectInvoice__c pi :(List<ProjectInvoice__c> )Trigger.new){
           
            if (pi.Status__c == Constants.PROJECT_INVOICE_STATUS_INVOICED ){
                projectInvoiceIds.add(pi.Id);
            }            
        } 
        
        updateReleatedAccountBudget(projectInvoiceIds);
    }
    
    public override void afterUpdate(){
                
        if (TriggerUtil.skipProjectInvoiceTrigger) return;
        
        Set<String> projectInvoiceIds = new Set<String>();
                
        for(ProjectInvoice__c pi :(List<ProjectInvoice__c> )Trigger.new){
            ProjectInvoice__c oldPi = (ProjectInvoice__c) System.Trigger.oldMap.get(pi.Id);
            
            if (oldPi.Status__c != pi.Status__c && pi.Status__c == Constants.PROJECT_INVOICE_STATUS_INVOICED ){
                projectInvoiceIds.add(pi.Id);
            }
            
        } 
        
        updateReleatedAccountBudget(projectInvoiceIds);
    }
    
    private void updateReleatedAccountBudget(Set<String> projectInvoiceIds){

		Set<String> accountBudgetIds = new Set<String>();
        
        List<ProjectInvoice__c> projectInvoiceList = [Select id,Status__c, TotalProjectInvoiceAmountCalculated__c,ProjectAccount__r.Opportunity__r.AccountBudget__c 
                                                      From ProjectInvoice__c 
                                                      Where ID IN :projectInvoiceIds 
                                                      And ProjectAccount__r.Opportunity__r.AccountBudget__c != null];
        
        //To get all associated Account Budget
        for(ProjectInvoice__c pi : projectInvoiceList){
            accountBudgetIds.add(pi.ProjectAccount__r.Opportunity__r.AccountBudget__c);
        }
        
        Map<String, AccountBudget__c> accountBudgetMap = new Map<String, AccountBudget__c>(
            [select id, ExecutedAgainstBudget__c 
             from AccountBudget__c 
             Where ID IN :accountBudgetIds]);
        
        List<AccountBudget__c> accountBudgetListToUpdate =  new List<AccountBudget__c>();
        
        //To update ExecutedAgainstBudget__c field of associated Account Budget object 
        for(ProjectInvoice__c pi : projectInvoiceList){
            
            AccountBudget__c ab = accountBudgetMap.get(pi.ProjectAccount__r.Opportunity__r.AccountBudget__c);
            ab.ExecutedAgainstBudget__c = ab.ExecutedAgainstBudget__c != null ? ab.ExecutedAgainstBudget__c + pi.TotalProjectInvoiceAmountCalculated__c : pi.TotalProjectInvoiceAmountCalculated__c;
            accountBudgetListToUpdate.add(ab);
        }
        
        // To update all account budget
        update accountBudgetListToUpdate;

    }

}