src_old/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CMKOneHubAccountID__c</fullName>
        <label>Lawson Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <fields>
        <fullName>ProjectNumber__c</fullName>
        <displayFormat>{YY}{MM}{DD}{000000}</displayFormat>
        <inlineHelpText>this is help text in design</inlineHelpText>
        <label>Project Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planning</fullName>
                    <default>true</default>
                    <label>Planning</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Launched</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ended</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ProjectAccount__c.object
<CustomObject>
    <description>Project Account maps an Account to a Project and defines how the Account will be billed. Project Account is related to Project, Account, and Account Address.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please make sure this account&apos;s &apos;Can Request Project&apos; setting is enabled.</errorMessage>
            <filterItems>
                <field>Account.CanRequestProjects__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Project Accounts</relationshipLabel>
        <relationshipName>Project_Accounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsPrimary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsPrimary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Project_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Account</label>
    <nameField>
        <displayFormat>PA-{0000000}</displayFormat>
        <label>Project Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/classes/ProjAcctWrapper.cls
public class ProjAcctWrapper {
        @AuraEnabled
        public string StreetAddress{get; set;}
        @AuraEnabled
        public string CityAddress{get; set;}
        @AuraEnabled
        public string StateAddress{get; set;}
        @AuraEnabled
        public string PostalCodeAddress{get; set;}
        @AuraEnabled
        public string ContactName{get; set;}
        @AuraEnabled
        public string ContactPhone{get; set;}
		@AuraEnabled
        public string AccountName{get; set;}
        @AuraEnabled
        public string ProjectNum{get; set;}
    	@AuraEnabled
        public string ProjectName{get; set;}
    	@AuraEnabled
        public string Id{get; set;}
    	@AuraEnabled
        public string AccountId{get; set;}
    	@AuraEnabled
        public string LawsonId{get; set;}
    	
        @AuraEnabled
        public string ProjectStatus{get; set;}
       
       @AuraEnabled 
       public Boolean CanSetPrimary{get;set;}
        @AuraEnabled 
       public Boolean canDelete{get;set;}
    	
        @AuraEnabled
        public string IsPrimary{get; set;}
    
    
    Public ProjAcctWrapper(){}
        
    	public ProjAcctWrapper(projectAccount__c PA){
            
            ProjectName = PA.Name;
            ProjectNum = string.valueOf(PA.Project__r.projectnumber__c);
            StreetAddress = PA.Account__r.BillingStreet;
            CityAddress = PA.Account__r.BillingCity;
            StateAddress = PA.Account__r.BillingState;
            PostalCodeAddress = PA.Account__r.BillingPostalCode;
            ContactName = PA.Account__r.Owner.Name;
            AccountName = PA.Account__r.Name;
            AccountId = PA.Account__r.Id;
            Id = PA.Id;
            LawsonId = PA.Account__r.CMKOneHubAccountID__c;
            ProjectStatus = PA.Project__r.Status__c;
            IsPrimary = string.valueOf(PA.IsPrimary__c);
            CanSetPrimary = !UIConfig.checkFieldHidden(PA.Project__r.Status__c, 'ProjectAccount__c.SetPrimary');
            canDelete= !UIConfig.checkFieldHidden(PA.Project__r.Status__c, 'ProjectAccount__c.Delete');
        }        
}