src_old/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CanRequestProjects__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Can Request Projects</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsApproved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OneHubAccountType__c</fullName>
        <label>OneHubAccountType</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Execution Company</fullName>
                </value>
                <value>
                    <fullName>Retailer</fullName>
                </value>
                <value>
                    <fullName>Manufacturer</fullName>
                </value>
                <value>
                    <fullName>Client</fullName>
                </value>
                <value>
                    <fullName>Retail Category</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>3PL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ProjectAccount__c.object
<CustomObject>
    <description>Project Account maps an Account to a Project and defines how the Account will be billed. Project Account is related to Project, Account, and Account Address.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please make sure this account&apos;s &apos;Can Request Project&apos; setting is enabled.</errorMessage>
            <filterItems>
                <field>Account.CanRequestProjects__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Project Accounts</relationshipLabel>
        <relationshipName>Project_Accounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsPrimary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsPrimary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Project_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Account</label>
    <nameField>
        <displayFormat>PA-{0000000}</displayFormat>
        <label>Project Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectService__c.object
<CustomObject>
    <description>Project Service relates a Service to a Project and is a container used to define the instance of a Service for a specific Project. Project Service is related to Project, Job, Project Service Attribute, Project Service Certification, Project Service Equipment, Project Service Material, Project Service Question, Project Service Target, and Service.</description>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>ProjectServices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>Project Services</relationshipLabel>
        <relationshipName>ProjectServices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Service</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectServiceTarget__c.object
<CustomObject>
    <description>Relates a Target to a Project Service. Targets are manually added when building a Project. Project Service Target related to Project Service, Target, and Account.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Project Service Target</relationshipLabel>
        <relationshipName>Project_Service_Target</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Account</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>ProjectAccount__c.Project__c</field>
                <operation>equals</operation>
                <valueField>$Source.Project__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>ProjectAccount__c</referenceTo>
        <relationshipLabel>Project Service Target</relationshipLabel>
        <relationshipName>Project_Service_Target</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectService__c</fullName>
        <label>Project Service</label>
        <referenceTo>ProjectService__c</referenceTo>
        <relationshipLabel>Project Service Target</relationshipLabel>
        <relationshipName>ProjectServiceTargets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Service Target</relationshipLabel>
        <relationshipName>Project_Service_Target</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Service Target</label>
    <nameField>
        <displayFormat>SC-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Service Target</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/Service__c.object
<CustomObject>
    <description>Service contains the definition of a service. Service is related to Service Attribute, Service Exception, Service Question, Service Question Defined Response, Retailer Service, Retailer Service Equipment, and Project Service.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account specific service</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/classes/LightningProjectAccountsController.cls
public with sharing class LightningProjectAccountsController {
    
    @AuraEnabled
    public static list<Object> GetProjectAccount(String projectId) {
        checkProjectId(projectId);
        try{
            return  ProjectAccountModel.create(projectId).getList();
        }
        catch(CustomException cust){
            throw new AuraHandledException(cust.getStackTraceString());
        }
        catch(Exception ex){
            throw new AuraHandledException(ex.getStackTraceString());
        }
        
    }
    
    static void checkProjectId(String projectId){
        if (String.isBlank(projectId)){
            throw new AuraHandledException('The project Id is required.');
        }
    }
    
    @AuraEnabled
    public static list<Object> GetAccounts(String searchText, String projectid, Boolean getAll) {
        
        String accountQuery = '';
        
        if (getAll) {
            accountQuery = 'SELECT Name, Id, Owner.name, Phone, IsApproved__c, OneHubAccountType__c ' 
                + ' FROM Account '
                + 'WHERE CanRequestProjects__c = true';
        } else {
            accountQuery = 'SELECT Name, Id, Owner.name, Phone, IsApproved__c, OneHubAccountType__c ' 
                + ' FROM Account '
                + 'WHERE CanRequestProjects__c = true and name like \'%' + searchText + '%\'';
        }        
        
        if (projectid != null && projectid != '')
        {
            accountQuery = accountQuery + ' AND Id not in ( Select Account__c from ProjectAccount__c WHERE Project__c = \'' + projectid + '\')';
            
        }
        
        accountQuery = accountQuery + ' LIMIT 20';
        
        list<Account> accounts = Database.query(accountQuery); 
        
        list<AccountWrapper> awList = new list<AccountWrapper>();
        AccountWrapper ac;
        for(Account acct : accounts)
        {            
            awList.add(new AccountWrapper(acct));
        }
        
        Return awList;
    }
    
    @AuraEnabled
    public static string AddAccount(List<string> accounts, String projectId) {
        
        ResponseWrapper rw;
        List<ProjectAccount__c> ProjectAccounts = new List<ProjectAccount__c>();
        boolean isPrimarySet = false;
        
        Integer temp = [select count() from ProjectAccount__c where project__c =: projectId and IsPrimary__c=true];
        isPrimarySet = temp>0;
        
        for(string account : accounts)
        {
            ProjectAccount__c newProjectAccount = new ProjectAccount__c(Account__c = account, project__c = projectId);
            if(!isPrimarySet){
                newProjectAccount.IsPrimary__c=true;
                isPrimarySet=true;
            }
            
            ProjectAccounts.add(newProjectAccount);     
        }      
        try{
            insert ProjectAccounts;  
            rw = ResponseWrapper.getInstance(CONSTANTS.RESPONSE_STATE_SUCCESS, 'Successfully added account to project', 'SUCCESS');
        }
        catch(System.DmlException e) {
            String dmlMessage = e.getDmlMessage(0);
            if(e.getDmlType(0) == StatusCode.FIELD_FILTER_VALIDATION_EXCEPTION){
                dmlMessage = 'The selected account does not have approval to be added to a project. ';
                
            }
            throw new System.AuraHandledException(e.getDmlMessage(0)); 
        }
        
        catch(Exception ex) {
            throw new System.AuraHandledException(ex.getMessage()); 
        }
        
        return JSON.serialize(rw);
        
    }  
        
    @AuraEnabled
    public static string RemoveAccountsFromProject(string ProjectAccountId) {
        ResponseWrapper rw;
        system.debug(ProjectAccountId);
        ProjectAccount__c ProjectAccount = [Select Id, Project__c, Account__c from ProjectAccount__c where id =: ProjectAccountId ];
        
        system.debug(ProjectAccount.Id);
        //oh-2961
        ValidateBeforeRemoveAccount(ProjectAccount.Project__c, ProjectAccount.Account__c);
        id projID = ProjectAccount.Project__c;
        try{  
            delete ProjectAccount;
            //check if only one account exist
            list<ProjectAccount__c> ProjAcctList = getAccountList(projID);
            system.debug('~~ProjAcctList.size()~~'+ProjAcctList.size());
            if(ProjAcctList.size()==1){                
                list<ProjectServiceTarget__c> PSTList = [Select Id, ProjectAccount__c From ProjectServiceTarget__c where ProjectService__r.Project__c =: projID And ProjectAccount__c = null];
                system.debug('~~PSTList.size()~~'+PSTList.size());
                for(ProjectServiceTarget__c obj:PSTList){
                    obj.ProjectAccount__c = ProjAcctList[0].id;
                }
                update PSTList;
                
            }
 
            rw = ResponseWrapper.getInstance(CONSTANTS.RESPONSE_STATE_SUCCESS, 'Successfully deleted account from project', 'SUCCESS');
        }
        catch(Exception ex){
           
            throw new AuraHandledException(ex.getMessage());
            
        }
        
        return JSON.serialize(rw);
        
    } 
    
    //oh-2961:  Verify that Account cannot be removed if Service tied to account is not removed.
    static void ValidateBeforeRemoveAccount(Id project, Id account){
        AggregateResult[] results = [SELECT count(Id) cnt 
                                     FROM ProjectService__c 
                                     WHERE Project__c=:project 
                                     AND Service__r.Account__c=:account];
        if(results.size() > 0 && Integer.valueOf(results[0].get('cnt')) > 0) {
            throw new AuraHandledException('The account can\'t be deleted. There are still some services associated to this account.');
        }
    }
    
    static list<ProjectAccount__c> getAccountList(Id project){
        return [SELECT id FROM ProjectAccount__c WHERE Project__c=:project];
    }
    
    @AuraEnabled
    public static string makeAcctPrimary(string ProjectAccountId) {
        ResponseWrapper rw;
        system.debug(ProjectAccountId);
        
        ProjectAccount__c ProjectAccount = [Select Id,IsPrimary__c,project__c from ProjectAccount__c where id =: ProjectAccountId ];
        ProjectAccount.IsPrimary__c=true;
        
        
        ProjectAccount__c OldProjectAccount = [Select Id,IsPrimary__c from ProjectAccount__c where IsPrimary__c=true and project__c =:ProjectAccount.Project__c  ];
        OldProjectAccount.IsPrimary__c=false;
        update OldProjectAccount;
        
        update ProjectAccount;
        
        
        system.debug('+--+'+ProjectAccount.Id);
        
        try{
            rw = ResponseWrapper.getInstance(CONSTANTS.RESPONSE_STATE_SUCCESS, 'Successfully changed primary account', 'SUCCESS');
        }
        catch(Exception ex){
            rw = ResponseWrapper.getInstance(CONSTANTS.RESPONSE_STATE_ERROR, 'Unable to change primary account. Details: ' + ex.getMessage(), 'ERROR'); 
        }
        
        return JSON.serialize(rw);
        
    } 
    
    @AuraEnabled
    public static list<ProjectServiceTarget__c> getProjectServiceTarget(String projectId) {  
        return LightningProjectServiceTargetsController.getProjectServiceTarget(projectId);
    }
    
    @AuraEnabled
    public static String getNamespaceApex() {
        return CONSTANTS.CURRENTNAMESPACEPREFIX;
    }        
    
}