src_old/objects/Account.object
<CustomObject>
    <fields>
        <fullName>UniqueKey__c</fullName>
        <label>Unique Key</label>
        <length>250</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <fields>
        <fullName>SplitType__c</fullName>
        <description>A picklist that indicates if the project is to be a solo or split across multiple accounts.</description>
        <inlineHelpText>Select the split type for the project.</inlineHelpText>
        <label>Project Split Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Solo</fullName>
                </value>
                <value>
                    <fullName>Percentage (%)</fullName>
                </value>
                <value>
                    <fullName>Amount ($)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ProjectAccount__c.object
<CustomObject>
    <description>Project Account maps an Account to a Project and defines how the Account will be billed. Project Account is related to Project, Account, and Account Address.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please make sure this account&apos;s &apos;Can Request Project&apos; setting is enabled.</errorMessage>
            <filterItems>
                <field>Account.CanRequestProjects__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Project Accounts</relationshipLabel>
        <relationshipName>Project_Accounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BillToAddress__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill To Address</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Account__c</field>
                <operation>equals</operation>
                <valueField>AccountAddress__c.Account__c</valueField>
            </filterItems>
            <filterItems>
                <field>AccountAddress__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Billing Address</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>AccountAddress__c</referenceTo>
        <relationshipLabel>Project Accounts</relationshipLabel>
        <relationshipName>ProjectAccounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Project_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SplitValue__c</fullName>
        <label>% / $</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UniqueKey__c</fullName>
        <label>UniqueKey</label>
        <length>250</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Project Account</label>
    <nameField>
        <displayFormat>PA-{0000000}</displayFormat>
        <label>Project Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/classes/AddEditProjectAccountExt.cls
public with sharing class AddEditProjectAccountExt {

     
     
     public boolean ShowSplitAmount {get; set;}
     public void addMessage(ApexPages.Severity severity, String message){
     Apexpages.addMessage(new ApexPages.Message(severity, message));} 
     public Project__c project{get; set;}
     
    ApexPages.StandardController con;
    public AddEditProjectAccountExt(ApexPages.StandardController controller) {
           con= controller;
           
           ProjectAccount__c pa = (ProjectAccount__c) con.getRecord();
           Project= [SELECT Id,Name,SplitType__c FROM Project__c where id =: pa.project__c];
           if(Project.SplitType__c == 'Solo')
           {
               ShowSplitAmount = false;
           }
           else
           {
               ShowSplitAmount = true;
           }
           
           
    }


    public PageReference save()
     {        
        try
        {
            ProjectAccount__c pa = (ProjectAccount__c) con.getRecord();
            string tmp = pa.Project__c +'_'+  pa.Account__c +'_'+ pa.BillToAddress__c;//should be same as unique key
            integer cnt  = [select count() from projectaccount__c where UniqueKey__c =: tmp and project__c =: pa.project__c];
            
            system.debug('~~~~~pa.id~~~');
            
            if(cnt>0){
              addMessage(ApexPages.Severity.ERROR, 'The Account/Bill To Address selected has already been added to the project. Please select another Bill To Address for the selected Account.'); 
              return null; 
            }
            
            Project__c Project= [SELECT SplitType__c FROM Project__c where id =: pa.project__c];
            if(Project.SplitType__c == 'Solo')
            {
               pa.SplitValue__c = 100;
            }
            pa.UniqueKey__c = pa.Project__c +'_'+  pa.Account__c +'_'+ pa.BillToAddress__c;  //please update tmp variable before updating unique key
            con.save();
            
            pa = (ProjectAccount__c) con.getRecord();
            
            system.debug('~~~~~pa.id~~~'+pa.id);
            if(pa.id <> null)
            {
              return new PageReference(ApexPages.currentPage().getParameters().get('retURL'));
            }
            else
            {
              return null;
            }
        }         
        catch(Exception ex){
            system.debug('~~~inside ex'+ex.getMessage());        
            if (ex.getMessage().Contains('duplicate'))
            {
                addMessage(ApexPages.Severity.ERROR, 'Account already added. Please check and try again.');
            }
            else if(ex.getMessage().Contains('UniqueKey__c duplicates value')){
                addMessage(ApexPages.Severity.ERROR, 'Account already added. Please check and try again.');
            }
            else
            {
                addMessage(ApexPages.Severity.ERROR, ex.getMessage());
            }            
        }
        return null;
    }
}