src_old/objects/Account.object
<CustomObject>
    <fields>
        <fullName>OneHubAccountType__c</fullName>
        <label>OneHubAccountType</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Execution Company</fullName>
                </value>
                <value>
                    <fullName>Retailer</fullName>
                </value>
                <value>
                    <fullName>Manufacturer</fullName>
                </value>
                <value>
                    <fullName>Client</fullName>
                </value>
                <value>
                    <fullName>Retail Category</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>3PL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ThirdPartyApprover__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Third Party Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src_old/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ContactId__c</fullName>
        <externalId>true</externalId>
        <label>Contact Id</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Is3PLReq__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is 3PL Req</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src_old/objects/Job__c.object
<CustomObject>
    <description>Job defines the body of work to be performed at a Location and all of the dates related to the Job performance. A Job is related to a Project, Project Service, Project Location, Job Material, Contact, Exception, and Job Attempt.</description>
    <fields>
        <fullName>AssignedContactId__c</fullName>
        <description>The field that indicates the ID number of the Assigned Contact.</description>
        <formula>ActiveJobAttempt__r.AssignedContactId__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The ID number of the assigned contact</inlineHelpText>
        <label>Assigned Contact ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProjectLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field that indicates the Location of a Project.</description>
        <inlineHelpText>The location of the project</inlineHelpText>
        <label>Project Location</label>
        <referenceTo>ProjectLocation__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field that indicates the name of the Project to which a Job belongs.</description>
        <inlineHelpText>The name of the project for this job</inlineHelpText>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Job</label>
    <nameField>
        <displayFormat>JOB-{000000000}</displayFormat>
        <label>Job ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/JobAttempt__c.object
<CustomObject>
    <description>Job Attempt is an attempt of a Job performed at a location. Job Attempt is related to an Exception.</description>
    <fields>
        <fullName>AssignedContactId__c</fullName>
        <label>Assigned Contact ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AssignedContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Job Attempts</relationshipLabel>
        <relationshipName>Job_Attempts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AttemptStatus__c</fullName>
        <label>Attempt Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Started</fullName>
                </value>
                <value>
                    <fullName>Reported</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DateAssigned__c</fullName>
        <label>Date Assigned</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Job__c</fullName>
        <label>Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Job Attempts</relationshipLabel>
        <relationshipName>Job_Attempts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ProjectLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Location</label>
        <referenceTo>ProjectLocation__c</referenceTo>
        <relationshipLabel>Job Attempts</relationshipLabel>
        <relationshipName>Job_Attempts_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Job Attempt</label>
    <nameField>
        <displayFormat>JA-{000000000}</displayFormat>
        <label>Job Attempt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Attempts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/JobAttemptWorker__c.object
<CustomObject>
    <fields>
        <fullName>ContactEmail__c</fullName>
        <label>Contact Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>ContactId__c</fullName>
        <label>Contact Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Job_Workers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DateAssigned__c</fullName>
        <label>Date Assigned</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ECWorkerTime__c</fullName>
        <label>EC Worker Time</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FirstName__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>JobAttempt__c</fullName>
        <label>Job Attempt</label>
        <referenceTo>JobAttempt__c</referenceTo>
        <relationshipLabel>Job Attempt Workers</relationshipLabel>
        <relationshipName>Job_Attempt_Workers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>My3PLWork__c</fullName>
        <formula>if( $User.ThirdPartyAgency__c = ThirdPartyAgency__r.Name, True, false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>My3PLWork</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Checked In</fullName>
                </value>
                <value>
                    <fullName>Checked Out</fullName>
                </value>
                <value>
                    <fullName>No Show</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SupervisorEmail__c</fullName>
        <label>Supervisor Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>SupervisorFirstName__c</fullName>
        <label>Supervisor First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SupervisorLastName__c</fullName>
        <label>Supervisor Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SupervisorPhone__c</fullName>
        <label>Supervisor Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>ThirdPartyAgencyStatus__c</fullName>
        <label>3PL Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Requested</fullName>
                </value>
                <value>
                    <fullName>Canceled - Reassigned to CMK</fullName>
                </value>
                <value>
                    <fullName>Committed</fullName>
                </value>
                <value>
                    <fullName>Executed</fullName>
                </value>
                <value>
                    <fullName>Invoiced</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Agency Declined</fullName>
                </value>
                <value>
                    <fullName>Pending 3PL Agency Approval</fullName>
                </value>
                <value>
                    <fullName>CMK Rejected</fullName>
                </value>
                <value>
                    <fullName>Filled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ThirdPartyAgency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>3PL Agency</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Job Attempt Workers (3PL Agency)</relationshipLabel>
        <relationshipName>Job_Attempt_Workers1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ThirdPartyApprover__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>3PL Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Job_Attempt_Workers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WorkerType__c</fullName>
        <label>Worker Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Team Lead</fullName>
                </value>
                <value>
                    <fullName>Team Member</fullName>
                    <default>true</default>
                    <label>Team Member</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Job Attempt Worker</label>
    <nameField>
        <displayFormat>JAW-{000000000}</displayFormat>
        <label>Job Attempt Worker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Attempt Workers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectLocation__c.object
<CustomObject>
    <description>Project Location relates a Location to a Project. Project Location is related Project, Job, and Location.</description>
    <fields>
        <fullName>ProjectType__c</fullName>
        <formula>Project__r.ProjectType__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>ProjectLocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Job Created</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ThirdPartyAgencyContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>3PL Agency Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Project Locations</relationshipLabel>
        <relationshipName>Project_Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Location</label>
    <nameField>
        <displayFormat>PL-{0000}</displayFormat>
        <label>Location ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/JobAttemptWorkerTriggerHandler.cls
public class JobAttemptWorkerTriggerHandler extends TriggerHandler {
    
    public override void beforeUpdate() {
        
        if (TriggerUtil.skipJobAttemptWorkerTrigger) return;
        TriggerUtil.skipJobAttemptWorkerTrigger = true;

        //we put it here because we do not enforce contact ID must assigned logic below.
        handle3PLImportLogic();

        List<contact> defaultContacts;        
        
        Map<String, JobAttemptWorker__c> leadJobAttemptWorkerMap = new Map<String, JobAttemptWorker__c>();
        Map<String, JobAttemptWorker__c> unassignedleadJobAttemptWorkerMap = new Map<String, JobAttemptWorker__c>();        
        Map<String, JobAttemptWorker__c> thirdPartyAgencyContactChangeMap = new Map<String, JobAttemptWorker__c>();
        
        
        set<String> contactIds = new set<String>();
        
        set<String> jawIds = new set<string>();
        List<String> unAssigned3PLAgencyList = new List<String>();
        
        for (JobAttemptWorker__c jaw: (List < JobAttemptWorker__c>) Trigger.new) {
            
            JobAttemptWorker__c oldjw = (JobAttemptWorker__c) System.Trigger.oldMap.get(jaw.Id);
            if (oldjw.ContactId__c != null)
                contactIds.add(oldjw.ContactId__c); 
            if (jaw.ContactId__c != null)
                contactIds.add(jaw.ContactId__c); 
            
            jawIds.add(jaw.Id);                       
        }
        
        
        if (contactIds.size() == 0) {return;}
        
        //Gets contact object for contact id's
        Map<String,CONTACT> contactsMap = getContacts(contactIds);
        
        if(jawIds.size() == 0) {return;}
        Map<String,JobAttemptWorker__c> plAssignmentMap = get3plAssignments(jawIds);
        
        
        for (JobAttemptWorker__c jw: (List < JobAttemptWorker__c>) Trigger.new) {
            JobAttemptWorker__c oldjw = (JobAttemptWorker__c) System.Trigger.oldMap.get(jw.Id);            
            
            //Assignment Logic
            if(oldjw.ContactId__c !=jw.ContactId__c && jw.ContactId__c != null)
            {
                AssignWorker(oldjw, jw, contactsMap, leadJobAttemptWorkerMap);                
            }
            
            //Unassignment Logic
            if(oldjw.Status__c == CONSTANTS.JOB_ATTEMPT_WORKER_STATUS_ASSIGNED  && 
               jw.Status__c == CONSTANTS.JOB_ATTEMPT_WORKER_STATUS_OPEN)
            {
                UnassignWorker(oldjw, jw, contactsMap, unassignedleadJobAttemptWorkerMap);                
            }
            
            //OH-5488 -             
            if (oldjw.ContactId__c != jw.ContactId__c && oldjw.ContactId__c != null)
            {
                Contact oldContact = contactsMap.get(oldjw.ContactId__c);
                Contact newContact = contactsMap.get(jw.ContactId__c);                

                
                if (newContact == null){
                    jw.ThirdPartyAgencyStatus__c = constants.JOB_ATTEMPT_WORKER_3PL_STATUS_NONE;
                    jw.ThirdPartyAgency__c = null;
                    jw.Contact__c = null;
                    jw.ThirdPartyApprover__c = null;
                }
                else
                {
                    if ((contactsMap.get(oldjw.ContactId__c).Is3PLReq__c == true || oldContact.Account.OneHubAccountType__c == constants.ACCOUNT_TYPE_3PL )){
                                                
                        //if(jw.ContactId__c != AppUtil.ThirdPartyAgencyDeniedContactId && newContact.Account.OneHubAccountType__c != constants.ACCOUNT_TYPE_3PL)                    
                        if(jw.ContactId__c != constants.THIRD_PARTY_CONTACT_3PL_DENIED && newContact.Account.OneHubAccountType__c != constants.ACCOUNT_TYPE_3PL)                    
                        {
                            jw.ThirdPartyAgencyStatus__c = constants.JOB_ATTEMPT_WORKER_3PL_STATUS_CANCELED_REASSGINED_TO_CMK;
                        }
                        
                        jw.ThirdPartyAgency__c = newContact.Account.OneHubAccountType__c != constants.ACCOUNT_TYPE_3PL ? null : newContact.AccountId;                    
                    }  
                }
                
                unAssigned3PLAgencyList.add(oldjw.Id);
            }               
            
            if((oldjw.ThirdPartyAgency__c) != null && (oldjw.ThirdPartyAgency__c != jw.ThirdPartyAgency__c))
            {
                if (!thirdPartyAgencyContactChangeMap.containsKey(oldjw.Id)) {                          
                    thirdPartyAgencyContactChangeMap.put(oldjw.Id, oldjw);                            
                }
            }
            
            //Update Supervisor Email everytime we capture an update for a JAW
            //This is to make sure we get supervisor changes if any.
            //Update Supervisor information 
            if (contactsMap.get(jw.ContactId__c) != null)
            {
                UpdateSupervisorInfo(jw, contactsMap);                
            }
            
            CalculateTimeAdjusted(oldjw, jw);
            
            if (oldjw.ContactId__c != jw.ContactId__c && jw.ContactId__c != null && contactsMap.containsKey(jw.ContactId__c) && contactsMap.get(jw.ContactId__c).Is3PLReq__c == true) {
                
                if(plAssignmentMap.containsKey(jw.Id))
                {                    
                    JobAttemptWorker__c jobAttemptWorker  = plAssignmentMap.get(jw.Id); 
                    
                    string prjLocationContactAccount =jobAttemptWorker.JobAttempt__r.Job__r.ProjectLocation__r.ThirdPartyAgencyContact__r.AccountId !=null ? string.valueOf(jobAttemptWorker.JobAttempt__r.Job__r.ProjectLocation__r.ThirdPartyAgencyContact__r.AccountId):'';
                    
                    if(prjLocationContactAccount != '')                        
                    {
                        jw.ThirdPartyApprover__c  = jobAttemptWorker.JobAttempt__r.Job__r.ProjectLocation__r.ThirdPartyAgencyContact__r.Account.ThirdPartyApprover__c!=null? Id.valueOf(jobAttemptWorker.JobAttempt__r.Job__r.ProjectLocation__r.ThirdPartyAgencyContact__r.Account.ThirdPartyApprover__c): null; 
                        jw.ThirdPartyAgency__c  = Id.valueOf(jobAttemptWorker.JobAttempt__r.Job__r.ProjectLocation__r.ThirdPartyAgencyContact__r.AccountId);
                        jw.ThirdPartyAgencyStatus__c ='Requested';
                    }
                    else
                    {                        
                        jw.ThirdPartyApprover__c  = jobAttemptWorker.JobAttempt__r.Job__r.Project__r.ProjectType__r.Default3PLAccount__r.ThirdPartyApprover__c!=null? Id.valueOf(jobAttemptWorker.JobAttempt__r.Job__r.Project__r.ProjectType__r.Default3PLAccount__r.ThirdPartyApprover__c) : null;
                        jw.ThirdPartyAgency__c  = jobAttemptWorker.jobAttempt__r.Job__r.Project__r.ProjectType__r.Default3PLAccount__c !=null ? id.valueOf(jobAttemptWorker.jobAttempt__r.Job__r.Project__r.ProjectType__r.Default3PLAccount__c):'';
                        jw.ThirdPartyAgencyStatus__c ='Requested';
                    }
                }
            }
        }
        
        // To remove \ cancel pending approval process when contacts are being re assigned         
        JobAttemptWorkerHelper.CancelPending3PLRequest(unAssigned3PLAgencyList);        
        
        //OH-5487 - to send email on 3pl contact change
        thirdPartyAgencyChangeEmail(thirdPartyAgencyContactChangeMap);
        
        //To update job attempt with assigned supervisor - OH-4607
        updateLeadContactInJobAttempt(leadJobAttemptWorkerMap);
        
        //Update Job Attempt when a Team Lead is unassigned
        unassignLeadContactInJobAttempt(unassignedleadJobAttemptWorkerMap);        
        
    }

    Boolean Is3PLFirstLastNameChanged(JobAttemptWorker__c oldState, JobAttemptWorker__c newState) {
        return oldState.FirstName__c != newState.FirstName__c
            || oldState.LastName__c != newState.LastName__c;
    }

    Boolean is3PLAgentAccepted(JobAttemptWorker__c oldState) {
        return oldState.ThirdPartyAgencyStatus__c == CONSTANTS.JOB_ATTEMPT_WORKER_3PL_STATUS_ACCEPTED;
    }

    Boolean is3PLImportAllowed(JobAttemptWorker__c oldState) {
        return oldState.My3PLWork__c == true 
            && ( oldState.ThirdPartyAgencyStatus__c == CONSTANTS.JOB_ATTEMPT_WORKER_3PL_STATUS_ACCEPTED 
              || oldState.ThirdPartyAgencyStatus__c == CONSTANTS.JOB_ATTEMPT_WORKER_3PL_STATUS_COMMITTED);
    }

    Boolean isFirstLastNameValid(JobAttemptWorker__c newState) {
        return String.isNotBlank(newState.FirstName__c) 
            && String.isNotBlank(newState.LastName__c);
    }

    //OH2-1592
    void handle3PLImportLogic() { 
        for(JobAttemptWorker__c newState: (List<JobAttemptWorker__c>) Trigger.new) {
            JobAttemptWorker__c oldState = (JobAttemptWorker__c) Trigger.oldMap.get(newState.Id);  
            if( is3PLImportAllowed(oldState) ) {
                if (isFirstLastNameValid(newState)){
                    if (Is3PLFirstLastNameChanged(oldState, newState) && is3PLAgentAccepted(oldState)){
                        newState.ThirdPartyAgencyStatus__c = CONSTANTS.JOB_ATTEMPT_WORKER_3PL_STATUS_COMMITTED;
                    }
                } else {
                    newState.FirstName__c = oldState.FirstName__c;
                    newState.LastName__c = oldState.LastName__c;
                    newState.ThirdPartyAgencyStatus__c = oldState.ThirdPartyAgencyStatus__c;
                }
            }
        }
    }
    
    static void thirdPartyAgencyChangeEmail(Map<String, JobAttemptWorker__c> thirdPartyAgencyContactChangeMap){
        
        Set<Id> contactIds = new Set<Id>();
        
        for(Id key : thirdPartyAgencyContactChangeMap.keyset()) {
            contactIds.add(thirdPartyAgencyContactChangeMap.get(key).Contact__c);
        }
        
        Map<ID, Contact> contacts = new Map<ID, Contact>([select Id,Email, Is3PLReq__c from Contact where Id in :contactIds]);
        
        for(Id key : thirdPartyAgencyContactChangeMap.keyset()) {
            
            JobAttemptWorker__c jaw = thirdPartyAgencyContactChangeMap.get(key);
            Contact objContact = contacts.get(jaw.Contact__c);
            
            if (objContact.Is3PLReq__c){
                
                List<String> toRecipients = new List<String>();
                List<String>ccRecipients = new List<String>();
                String templateApiName;
                ID targetObjId, whatId;
                
                templateApiName = AppUtil.ThirdPartyAgencyChangeEmailTemplateName;
                
                if (templateApiName != null && templateApiName != ''){
                    toRecipients.add(objContact.Email);                
                    
                    AppUtil.sendTemplatedEmail(toRecipients,ccRecipients,templateApiName,objContact.Id,jaw.Id,false,null);
                }
            }
        }
    }
    
    //OH-4607 
    //Update the Job Attempt Status to assigned
    //and Assigned contact to Assigned COntact Id
    static void updateLeadContactInJobAttempt(Map<String, JobAttemptWorker__c> leadJobAttemptWorkerMap) {
        
        List<JobAttempt__c> jobAttempts =  [SELECT Id, AssignedContact__c, AssignedContactId__c FROM JobAttempt__c WHERE 
                                            ID IN :leadJobAttemptWorkerMap.keyset()];
        
        for(JobAttempt__c jobAttempt : jobAttempts){
            JobAttemptWorker__c jobAttemptWorker  = leadJobAttemptWorkerMap.get(jobAttempt.Id);            
            jobAttempt.AssignedContactId__c = jobAttemptWorker.ContactId__c;  
            jobAttempt.AssignedContact__c = jobAttemptWorker.Contact__c;  
            jobAttempt.AttemptStatus__c = CONSTANTS.JOB_ATTEMPT_STATUS_ASSIGNED;
        }                
        
        update jobAttempts;
    }
    
    static void unassignLeadContactInJobAttempt(Map<String, JobAttemptWorker__c> unassignedleadJobAttemptWorkerMap) {
        
        List<JobAttempt__c> jobAttempts =  [SELECT Id, AssignedContact__c, AssignedContactId__c FROM JobAttempt__c WHERE 
                                            ID IN :unassignedleadJobAttemptWorkerMap.keyset()];
        
        for(JobAttempt__c jobAttempt : jobAttempts){
            JobAttemptWorker__c jobAttemptWorker  = unassignedleadJobAttemptWorkerMap.get(jobAttempt.Id);            
            jobAttempt.AssignedContactId__c = null;  
            jobAttempt.AssignedContact__c = null;  
            jobAttempt.AttemptStatus__c = CONSTANTS.JOB_ATTEMPT_STATUS_OPEN;
        }                
        update jobAttempts;
    }    
    
    static Map<String,CONTACT> getContacts(Set<String> contactIdSet) {
        
        Map<String,CONTACT> result = new Map<String,CONTACT>();
        if (contactIdSet.size() == 0) {
            return result;
        }
        
        for(Contact person: [SELECT Id, ContactId__c, Email, FirstName, LastName, ReportsTo.Email, 
                             ReportsTo.FirstName, ReportsTo.LastName, ReportsTo.Phone, Is3PLReq__c, 
                             Account.OneHubAccountType__c, AccountId
                             FROM CONTACT 
                             WHERE ContactId__c != '' 
                             AND ContactId__c IN :contactIdSet]) {
                                 result.put(person.ContactId__c, person);
                             }
        
        return result;
    }
    
    static map<string,JobAttemptWorker__c> get3plAssignments(Set<String> jawIds)
    {
        
        Map<String,JobAttemptWorker__c> result = new Map<String,JobAttemptWorker__c>();
        
        if(jawIds.size()==0) {
            return result;
        }
        
        for(JobAttemptWorker__c jaw :[Select Id,name,JobAttempt__r.Job__r.ProjectLocation__r.ThirdPartyAgencyContact__r.AccountId,
                                      JobAttempt__r.Job__r.ProjectLocation__r.ThirdPartyAgencyContact__r.Account.ThirdPartyApprover__c,
                                      jobAttempt__r.Job__r.Project__r.ProjectType__r.Default3PLAccount__c,
                                      JobAttempt__r.Job__r.Project__r.ProjectType__r.Default3PLAccount__r.ThirdPartyApprover__c
                                      FROM JobAttemptWorker__c 
                                      where Id IN : jawIds  
                                     ])
        {
            
            
            result.put(jaw.Id,jaw);
        }
        
        return result;
        
    }    
    
    private void AssignWorker(JobAttemptWorker__c oldjw, JobAttemptWorker__c jw, Map<String,CONTACT> contactsMap, Map<String, JobAttemptWorker__c> leadJobAttemptWorkerMap)
    {
        
        if (contactsMap.containsKey(jw.ContactId__c)) {
            jw.Contact__c  = contactsMap.get(jw.ContactId__c).Id ;
            jw.DateAssigned__c = DateTime.Now();
            
            //collect all lead contact info to update Job Attempt sObject - OH-4607
            if (jw.WorkerType__c == CONSTANTS.JOB_ATTEMPT_WORKER_WORKER_TYPE_TEAM_LEAD){
                leadJobAttemptWorkerMap.put(jw.JobAttempt__c, jw);
            }                    
        }
        else
        {
            jw.addError('ContactId: ' + jw.ContactId__c + ' not found in the system.');
        }
        
    }
    
    private void UnassignWorker(JobAttemptWorker__c oldjw, JobAttemptWorker__c jw, Map<String,CONTACT> contactsMap, Map<String, JobAttemptWorker__c> unassignedLeads)
    {
        
        jw.Contact__c  = null;
        jw.ContactId__c  = null;
        //collect all lead contact info to update Job Attempt sObject - OH-4607
        if (jw.WorkerType__c == CONSTANTS.JOB_ATTEMPT_WORKER_WORKER_TYPE_TEAM_LEAD){
            unassignedLeads.put(jw.JobAttempt__c, jw);
        }                    
        
    }    
    
    private void UpdateSupervisorInfo(JobAttemptWorker__c jw, Map<String,CONTACT> contactsMap)
    {
        
        if (contactsMap.get(jw.ContactId__c).ReportsTo.Email != null)
        {
            jw.SupervisorEmail__c = contactsMap.get(jw.ContactId__c).ReportsTo.Email;
            jw.SupervisorFirstName__c = contactsMap.get(jw.ContactId__c).ReportsTo.FirstName;
            jw.SupervisorLastName__c = contactsMap.get(jw.ContactId__c).ReportsTo.LastName;
            jw.SupervisorPhone__c = contactsMap.get(jw.ContactId__c).ReportsTo.Phone;
        }
        jw.ContactEmail__c = contactsMap.get(jw.ContactId__c).Email;            
        
    }
    
    private void CalculateTimeAdjusted(JobAttemptWorker__c oldjw, JobAttemptWorker__c jw)
    {
        
        if (oldjw.ECWorkerTime__c != jw.ECWorkerTime__c || oldjw.TotalInStoreTime__c != jw.TotalInStoreTime__c || 
            oldjw.TotalInStoreNonBillableTime__c != jw.TotalInStoreNonBillableTime__c)
        {
            //Update the time adjusted
            if (jw.TotalInStoreTime__c != null && jw.ECWorkerTime__c != null && 
                jw.ECWorkerTime__c > 0)
            {
                jw.TimeAdjusted__c = jw.ECWorkerTime__c - (jw.TotalInStoreTime__c - jw.TotalInStoreNonBillableTime__c);    
            }
            
        }
        
        
    }
    
}