src_old/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ThirdPartyAgencyPrimaryContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>3PL Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ThirdPartyApprover__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Third Party Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src_old/objects/Job__c.object
<CustomObject>
    <description>Job defines the body of work to be performed at a Location and all of the dates related to the Job performance. A Job is related to a Project, Project Service, Project Location, Job Material, Contact, Exception, and Job Attempt.</description>
    <label>Job</label>
    <nameField>
        <displayFormat>JOB-{000000000}</displayFormat>
        <label>Job ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/JobAttempt__c.object
<CustomObject>
    <description>Job Attempt is an attempt of a Job performed at a location. Job Attempt is related to an Exception.</description>
    <fields>
        <fullName>Job__c</fullName>
        <label>Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Job Attempts</relationshipLabel>
        <relationshipName>Job_Attempts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ProjectLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Location</label>
        <referenceTo>ProjectLocation__c</referenceTo>
        <relationshipLabel>Job Attempts</relationshipLabel>
        <relationshipName>Job_Attempts_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Job Attempt</label>
    <nameField>
        <displayFormat>JA-{000000000}</displayFormat>
        <label>Job Attempt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Attempts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/JobAttemptWorker__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Job_Workers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>JobAttempt__c</fullName>
        <label>Job Attempt</label>
        <referenceTo>JobAttempt__c</referenceTo>
        <relationshipLabel>Job Attempt Workers</relationshipLabel>
        <relationshipName>Job_Attempt_Workers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ThirdPartyAgencyStatus__c</fullName>
        <label>3PL Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Requested</fullName>
                </value>
                <value>
                    <fullName>Canceled - Reassigned to CMK</fullName>
                </value>
                <value>
                    <fullName>Committed</fullName>
                </value>
                <value>
                    <fullName>Executed</fullName>
                </value>
                <value>
                    <fullName>Invoiced</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Agency Declined</fullName>
                </value>
                <value>
                    <fullName>Pending 3PL Agency Approval</fullName>
                </value>
                <value>
                    <fullName>CMK Rejected</fullName>
                </value>
                <value>
                    <fullName>Filled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ThirdPartyAgency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>3PL Agency</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Job Attempt Workers (3PL Agency)</relationshipLabel>
        <relationshipName>Job_Attempt_Workers1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ThirdPartyApprover__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>3PL Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Job_Attempt_Workers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Job Attempt Worker</label>
    <nameField>
        <displayFormat>JAW-{000000000}</displayFormat>
        <label>Job Attempt Worker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Attempt Workers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectLocation__c.object
<CustomObject>
    <description>Project Location relates a Location to a Project. Project Location is related Project, Job, and Location.</description>
    <label>Project Location</label>
    <nameField>
        <displayFormat>PL-{0000}</displayFormat>
        <label>Location ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ThirdpartyAgencyRecordsLocker__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Thirdparty Agency Records Locker</relationshipLabel>
        <relationshipName>Thirdparty_Agency_Records_Locker</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Thirdparty Agency Records Locker</label>
    <nameField>
        <displayFormat>TH-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Thirdparty Agency Records Locker</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/objects/User.object
<CustomObject>
    <fields>
        <fullName>ThirdPartyAgency__c</fullName>
        <label>ThirdPartyAgency</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src_old/classes/LightningJobAttemptWorkerController.cls
public without sharing class LightningJobAttemptWorkerController {
    @AuraEnabled
    public static string getThirdPartyAgencyReportUrl(string jobAttemptWorkerId)
    {
        jobAttemptWorkerId = jobAttemptWorkerId == null ? '' : jobAttemptWorkerId;
        string jobAttemptWorkerUrl = string.valueOf(AppUtil.ExportJobAttemptWorkerReportUrl.replace('{JobAttemptWorkerId}',jobAttemptWorkerId));
        return jobAttemptWorkerUrl; 
    }
    
    @AuraEnabled
    public static string getLoggedInUserThirdPartyAgency(string loggedInuserId)
    {
        list<Account> accList;
        List<ThirdpartyAgencyRecordsLocker__c> tal;
        string result;
        string accId;
        List<User> lstUser = [select id,Name,ThirdPartyAgency__c from User  where Id =:loggedInuserId]; 
        if(lstUser!=null && lstUser.size() >0)
        {
          user u =  lstUser[0];
          if(String.isBlank(u.ThirdPartyAgency__c) )
          {
              throw new AuraHandledException('please enter thrid party Agency Name on user object ');
          }
            
           String likeFilter ='\'%' + String.escapeSingleQuotes(u.ThirdPartyAgency__c) + '%\'';
           //string thirdPartyAgency = '%'+ String.escapeSingleQuotes() +'%';
           String Query = 'Select Id, Name FROM Account WHERE Name LIKE ' + likeFilter;
           accList = Database.Query(Query);
           if(accList.size()> 0) 
           {
              tal = [select Id,Account__c  from ThirdpartyAgencyRecordsLocker__c  where Account__c =:accList[0].Id]; 
              if( tal.isEmpty() ) {
                  
                  ThirdpartyAgencyRecordsLocker__c tar = new ThirdpartyAgencyRecordsLocker__c();
                  tar.Account__c = accList[0].Id;
                  insert tar;
                  
                  result = tar.Id;
                 // system.debug('Result++++'+result);
                  
              }
               else
               {
                   result=tal[0].Id;
               }
               
           }
        // system.debug('hello' + accList);
            
         // accList = [select Id,name from Account where name like :thirdPartyAgency];
          
        }
         if(!(String.isBlank(result)))
         {
             tal = [select Id,Account__c  from ThirdpartyAgencyRecordsLocker__c  where Id =:result];
             accId =tal[0].Account__c;
         }
         return accId;
    }
    
       @AuraEnabled
    public static List<JobAttemptWorkerWrapper> fetch3PLAgencyPendingApprovalList(string userId) {
        List<JobAttemptWorker__c> jawList = new List<JobAttemptWorker__c>();
        
        jawList = JobAttemptWorkerHelper.Get3PLAgencyPendingApprovalList();
        
        list<JobAttemptWorkerWrapper> awList = new list<JobAttemptWorkerWrapper>();
        for(JobAttemptWorker__c jw : jawList)
        {            
            awList.add(new JobAttemptWorkerWrapper(jw));
        }
        
        Return awList;
        
    }
     
    
    @AuraEnabled
    public static void pending3PLRequests(List<string> jawList,string reqComments, String approverReqStatus) 
    {
        
        JobAttemptWorkerHelper.ApprovePending3PLRequest(jawList,reqComments,approverReqStatus);
        
        /* if (approverReqStatus == CONSTANTS.APPROVAL_STATUS_APPROVE){
// Set Contact ID in Job Attempt Worker

Map<ID, JobAttemptWorker__c> jawMap = new Map<ID, JobAttemptWorker__c>([select Id,ThirdPartyAgency__c,Contact__c from JobAttemptWorker__c where Id in :jawList]);
Set<Id> accountIds = new Set<Id>();

for(Id key : jawMap.keyset()) {
accountIds.add(jawMap.get(key).ThirdPartyAgency__c);
}

Map<ID, Account> accounts = new Map<ID, Account>([select Id,ThirdPartyAgencyPrimaryContact__c from Account where Id in :accountIds]);

List<JobAttemptWorker__c> jawToBeUpdatedList = new List<JobAttemptWorker__c>();

for(Id key : jawMap.keyset()) {
JobAttemptWorker__c jaw = jawMap.get(key);
if (jaw.ThirdPartyAgency__c != null && accounts.get(jaw.ThirdPartyAgency__c) != null ){
jaw.Contact__c = accounts.get(jaw.ThirdPartyAgency__c).ThirdPartyAgencyPrimaryContact__c;
jawToBeUpdatedList.add(jaw);
}                
}

update jawToBeUpdatedList;

/* 
SELECT ID, JobAttempt__r.Job__r.ProjectLocation__r.ThirdPartyAgencyContact__c, jobAttempt__r.Job__r.Project__r.ProjectType__r.Default3PLAccount__c 
FROM JobAttemptWorker__c where ID : 


if(String.valueOf(jobAttemptWorker.JobAttempt__r.Job__r.ProjectLocation__r.ThirdPartyAgencyContact__r.AccountId)!=null  &&  String.valueOf(jobAttemptWorker.JobAttempt__r.Job__r.ProjectLocation__r.ThirdPartyAgencyContact__r.AccountId)!='')

{
system.debug('Iam inside');
// system.debug('agencey' + plAssignmentMap.get(jw.Id).JobAttempt__r.Job__r.ProjectLocation__r.ThirdPartyAgencyContact__r.AccountId);
jw.ThirdPartyApprover__c  = jobAttemptWorker.JobAttempt__r.Job__r.ProjectLocation__r.ThirdPartyAgencyContact__r.Account.ThirdPartyApprover__c!=null? Id.valueOf(jobAttemptWorker.JobAttempt__r.Job__r.ProjectLocation__r.ThirdPartyAgencyContact__r.Account.ThirdPartyApprover__c): null; 
jw.ThirdPartyAgency__c  = Id.valueOf(jobAttemptWorker.JobAttempt__r.Job__r.ProjectLocation__r.ThirdPartyAgencyContact__r.AccountId);
jw.ThirdPartyAgencyStatus__c ='Requested';
}
else
{
//system.debug('Iam else Part::' + jw.Id);
//system.debug('default contacts'+ defaultContacts.size());
jw.ThirdPartyApprover__c  =  jobAttemptWorker.JobAttempt__r.Job__r.Project__r.ProjectType__r.Default3PLAccount__r.ThirdPartyApprover__c!=null? Id.valueOf(jobAttemptWorker.JobAttempt__r.Job__r.Project__r.ProjectType__r.Default3PLAccount__r.ThirdPartyApprover__c) : null;
jw.ThirdPartyAgency__c  = jobAttemptWorker.jobAttempt__r.Job__r.Project__r.ProjectType__r.Default3PLAccount__c !=null?id.valueOf(jobAttemptWorker.jobAttempt__r.Job__r.Project__r.ProjectType__r.Default3PLAccount__c):'';
jw.ThirdPartyAgencyStatus__c ='Requested';


}

*/
        //    }
    }
}