src_old/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CMKOneHubAccountID__c</fullName>
        <label>Lawson Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UniqueKey__c</fullName>
        <label>Unique Key</label>
        <length>250</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <fields>
        <fullName>OverrideAccountAndServiceAccess__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Override Account And Service Access</label>
        <type>Checkbox</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ProjectAccount__c.object
<CustomObject>
    <description>Project Account maps an Account to a Project and defines how the Account will be billed. Project Account is related to Project, Account, and Account Address.</description>
    <fields>
        <fullName>AccountName__c</fullName>
        <formula>Account__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please make sure this account&apos;s &apos;Can Request Project&apos; setting is enabled.</errorMessage>
            <filterItems>
                <field>Account.CanRequestProjects__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Project Accounts</relationshipLabel>
        <relationshipName>Project_Accounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Project_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>UniqueKey__c</fullName>
        <label>UniqueKey</label>
        <length>250</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Project Account</label>
    <nameField>
        <displayFormat>PA-{0000000}</displayFormat>
        <label>Project Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectAccountServiceAccess__c.object
<CustomObject>
    <description>ProjectAccountServiceAccess</description>
    <fields>
        <fullName>AccessLevel__c</fullName>
        <label>AccessLevel</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Full Access</fullName>
                </value>
                <value>
                    <fullName>No Access</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <formula>CASESAFEID(ProjectAccount__r.Account__r.Id)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProjectAccount__c</fullName>
        <label>Project Account</label>
        <referenceTo>ProjectAccount__c</referenceTo>
        <relationshipLabel>Project Account Service Accesses</relationshipLabel>
        <relationshipName>Project_Account_Service_Accesses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ProjectService__c</fullName>
        <label>Project Service</label>
        <referenceTo>ProjectService__c</referenceTo>
        <relationshipLabel>Project Account Service Accesses</relationshipLabel>
        <relationshipName>Project_Account_Service_Accesses</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Account Service Accesses</relationshipLabel>
        <relationshipName>Project_Account_Service_Accesses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UniqueKey__c</fullName>
        <externalId>true</externalId>
        <label>Unique Key</label>
        <length>250</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Project Account Service Access</label>
    <nameField>
        <displayFormat>AA-{00000}</displayFormat>
        <label>ProjectAccountServiceAccess Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Account Service Accesses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectService__c.object
<CustomObject>
    <description>Project Service relates a Service to a Project and is a container used to define the instance of a Service for a specific Project. Project Service is related to Project, Job, Project Service Attribute, Project Service Certification, Project Service Equipment, Project Service Material, Project Service Question, Project Service Target, and Service.</description>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>ProjectServices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ServiceTitle__c</fullName>
        <inlineHelpText>Description of Service -- visible to rep and client</inlineHelpText>
        <label>Service Title</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>Project Services</relationshipLabel>
        <relationshipName>ProjectServices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UniqueKey__c</fullName>
        <externalId>true</externalId>
        <label>Unique Key</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Project Service</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/Service__c.object
<CustomObject>
    <description>Service contains the definition of a service. Service is related to Service Attribute, Service Exception, Service Question, Service Question Defined Response, Retailer Service, Retailer Service Equipment, and Project Service.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account specific service</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/ProjectAccountServiceAccessController.cls
public with sharing class ProjectAccountServiceAccessController {
    
    @AuraEnabled
    public static boolean checkIfProjectDataAccessOveride(String projectId) {
        Project__c project = [SELECT OverrideAccountAndServiceAccess__c from Project__c where Id  =:projectId]; 
        return project.OverrideAccountAndServiceAccess__c;       
    }  
    
    @AuraEnabled    
    public static Map<String,Object> GetProjectAccountServiceAccessList(String projectId) {
        
        Map<String,Object> ds = new Map<String, Object>();
        
        Set<ServiceWrapper> serviceList = new Set<ServiceWrapper>();
        
        List<ProjectAccountServiceDataAccessWrapper> PASDataaccess =  new List<ProjectAccountServiceDataAccessWrapper>();
        
        list<ProjectAccount__c> ProjectAccountList = [SELECT Id, Account__c, AccountName__c, Account__r.CMKOneHubAccountID__c FROM ProjectAccount__c where Project__c =:projectId];
        list<ProjectService__c> ProjectServiceList = [SELECT Id, Service__c, ServiceTitle__c FROM ProjectService__c where Project__c =:projectId];
        
        
        for(ProjectService__c projectService : ProjectServiceList){
            ServiceWrapper serviceWrapperObj = new ServiceWrapper();
            serviceWrapperObj.Name = projectService.ServiceTitle__c;            
            serviceList.add(serviceWrapperObj);
        }
        
        
        list<ProjectAccountServiceAccess__c> ProjectAccountServiceAccessList = [SELECT Id, Project__c, ProjectAccount__c,ProjectAccount__r.Id, ProjectAccount__r.AccountName__c, ProjectService__c, ProjectService__r.Id, 
                                                                                AccessLevel__c, UniqueKey__c FROM ProjectAccountServiceAccess__c where Project__c =:projectId];
        
        //When there is no project account or project service, Matrix cannot be built, We return an empty matrix.
        if (ProjectAccountList.size() == 0 || ProjectServiceList.size() == 0)
        {
            return ds;
        }
        
        for (ProjectAccount__c projectAccount :ProjectAccountList)
        {            
            ProjectAccountServiceDataAccessWrapper obj = new ProjectAccountServiceDataAccessWrapper();            
            obj.AccountName = projectAccount.AccountName__c;            
            
            List<ProjectAccountServiceDataAccessWrapper.ProjectAccountService> psList = new List<ProjectAccountServiceDataAccessWrapper.ProjectAccountService>();
            
            for (ProjectService__c projectService :ProjectServiceList)        
            {
                ProjectAccountServiceDataAccessWrapper.ProjectAccountService ps = new ProjectAccountServiceDataAccessWrapper.ProjectAccountService();
                
                String str;
                Id ProjectAccountServiceAccessId;
                ProjectAccountServiceAccess__c PASAccess;
                String ExternalId;
                
                for(ProjectAccountServiceAccess__c objPASAccessList: ProjectAccountServiceAccessList){
                    if (objPASAccessList.ProjectAccount__r.Id == projectAccount.Id && objPASAccessList.ProjectService__r.Id == projectService.Id)
                    {
                        str = objPASAccessList.AccessLevel__c;
                        ProjectAccountServiceAccessId = objPASAccessList.Id;
                        ExternalId = objPASAccessList.UniqueKey__c;
                        PASAccess = objPASAccessList;
                        
                        break;
                    }
                }
                
                if (PASAccess == null)
                {
                    PASAccess = new ProjectAccountServiceAccess__c();
                    PASAccess.Project__c = projectId;
                    PASAccess.ProjectAccount__c = projectAccount.Id;
                    PASAccess.ProjectService__c = projectService.Id;
                    PASAccess.AccessLevel__c = CONSTANTS.PROJECT_ACCOUNT_SERVICE_ACCESS_LEVEL_NO_ACCESS;
                }
                
                ps.ExternalId = ExternalId;
                ps.Access = (str == CONSTANTS.PROJECT_ACCOUNT_SERVICE_ACCESS_LEVEL_FULL_ACCESS ? true : false);
                ps.ProjectAccountServiceAccessId = ProjectAccountServiceAccessId;
                ps.ServiceName = projectService.ServiceTitle__c;
                
                ps.PASAccess = PASAccess;
                psList.add(ps);
            }
            
            obj.ProjectAccountService = psList;
            
            PASDataaccess.add(obj);
        }
        
        ds.put('PASDataAccess', PASDataaccess);
        ds.put('ServiceList', serviceList);
        
        return ds;
    }    
    
    @AuraEnabled    
    public static String saveDataAccess(String projectId,String dataAccessList, Boolean overrideAccess) {
        ResponseWrapper rw;    
        
        List<ProjectAccountServiceDataAccessWrapper> accessList = 
            (List<ProjectAccountServiceDataAccessWrapper>)JSON.deserialize(dataAccessList,List<ProjectAccountServiceDataAccessWrapper>.class);
        
        List<ProjectAccountServiceAccess__c> obj = new List<ProjectAccountServiceAccess__c>();
        List<ProjectAccountServiceAccess__c> objToBeDeleted = new List<ProjectAccountServiceAccess__c>();
        
        for(ProjectAccountServiceDataAccessWrapper accessObj : accessList) {
            for(ProjectAccountServiceDataAccessWrapper.ProjectAccountService obj1 : accessObj.ProjectAccountService){ 
                
                
                if ((!(String.isBlank(obj1.ExternalId)) && obj1.Access == false))
                {
                    objToBeDeleted.add(obj1.PASAccess);
                }
                else if ((!(String.isBlank(obj1.ExternalId)) && overrideAccess == false))
                {
                    objToBeDeleted.add(obj1.PASAccess);
                }
                else if (obj1.Access == true)
                {
                    obj1.PASAccess.AccessLevel__c = CONSTANTS.PROJECT_ACCOUNT_SERVICE_ACCESS_LEVEL_FULL_ACCESS;
                    obj.add(obj1.PASAccess);
                }
            }
        }
        
        try{
            
            // To save data access
            LightningProjectController.saveProjectAccess(projectId,overrideAccess);
            
            upsert obj;            
            
            delete objToBeDeleted;
            
            rw = ResponseWrapper.getInstance(CONSTANTS.RESPONSE_STATE_SUCCESS, 'Project account service data access has been update',CONSTANTS.RESPONSE_STATE_SUCCESS);
            
        }
        catch(Exception ex){            
            
            system.debug(JSON.serialize(rw));
            
            system.debug('ERROR - Project Account Service Data Access: ' + ex.getMessage());
            if(ex.getDmlMessage(0)!='')
                rw = ResponseWrapper.getInstance(CONSTANTS.RESPONSE_STATE_SUCCESS, 'Error updating project account service data access - ' + ex.getDmlMessage(0), CONSTANTS.RESPONSE_STATE_ERROR);
            else
                rw = ResponseWrapper.getInstance(CONSTANTS.RESPONSE_STATE_SUCCESS, 'Error updating project account service data access' , CONSTANTS.RESPONSE_STATE_ERROR);
        }
        return JSON.serialize(rw);
    }   
}