src_old/objects/AccountBudget__c.object
<CustomObject>
    <description>AccountBudget</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Budgets (Account)</relationshipLabel>
        <relationshipName>Account_Budgets</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BudgetType__c</fullName>
        <label>Budget Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Annually</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Semi- Annually</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PeriodEndDate__c</fullName>
        <label>Period End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PeriodStartDate__c</fullName>
        <label>Period Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PlannedAgainstBudget__c</fullName>
        <label>Planned Against Budget</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SubCategory__c</fullName>
        <label>Sub Category</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Account Budget</label>
    <nameField>
        <label>Budget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Budgets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>AccountBudget__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account Budget</description>
        <inlineHelpText>Account Budget</inlineHelpText>
        <label>Account Budget</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>AccountBudget__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>AccountBudget__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src_old/classes/OpportunityTriggerHandlerTest.cls
@isTest
public class OpportunityTriggerHandlerTest {

    @testSetup static void setup(){
        TriggerUtil.skipAllTriggers();
        Account acct = setupAccount();
        setupAccountBudgets(acct);
    }   

    static Account setupAccount() {
        Account acct = new Account (
                name = '7up'
            );
        insert acct;
        return acct;
    } 

    static void setupAccountBudgets(Account acct) {
        List<AccountBudget__c> budgets = new List<AccountBudget__c>();

        AccountBudget__c ab = new AccountBudget__c();
        ab.Name = 'budget=500';        
        ab.Account__c = acct.Id;        
        ab.PlannedAgainstBudget__c = 500;
        ab.Amount__c = 500;
        ab.BudgetType__c = 'Annual';
        ab.PeriodStartDate__c = Date.today();
        ab.PeriodEndDate__c = Date.today().addDays(10);       
        ab.SubCategory__c = 'test'; 
        budgets.add(ab);
        
        AccountBudget__c ab2 = new AccountBudget__c();
        ab2.Name = 'budget=null';
        ab2.Account__c = acct.Id;
        ab2.Amount__c = 500;
        ab2.BudgetType__c = 'Annual';
        ab2.PeriodStartDate__c = Date.today();
        ab2.PeriodEndDate__c = Date.today().addDays(10);
        ab2.SubCategory__c = 'test1'; 
        budgets.add(ab2);

        insert budgets;
    }

    @isTest static void itShouldNotThrowExceptionIfOpprAmountEqualTo0() {
        //GIVEN  
        Account acct = [select id from account limit 1];
        AccountBudget__c ab = [SELECT Id, PlannedAgainstBudget__c from AccountBudget__c where PlannedAgainstBudget__c = 500];

        Opportunity opp = new Opportunity();
        opp.AccountId = acct.Id;
        opp.Name = 'test opp 1';
        opp.StageName = 'Prospecting';      
        opp.CloseDate  = (Datetime.now()).date().addDays(20);  
        
        //WHEN                                        
        test.startTest();
        opp.AccountBudget__c = ab.Id;         
        insert opp;
                      
        //THEN
        List<AccountBudget__c> abList = [Select PlannedAgainstBudget__c from AccountBudget__c where id = : ab.Id];
        System.assertEquals(true, abList[0].PlannedAgainstBudget__c == 500);
    }
    
    @isTest
    public static void itShouldUpdateAccountBudgetPlanAgainstBudgetAmount(){
        
        //GIVEN  
        Account acct = [select id from account limit 1];
        AccountBudget__c ab = [SELECT Id, PlannedAgainstBudget__c from AccountBudget__c where PlannedAgainstBudget__c = 500];

        Opportunity opp = new Opportunity();
        opp.AccountId = acct.Id;
        opp.Amount = 300;
        opp.Name = 'test opp 1';
        opp.StageName = 'Prospecting';      
        opp.CloseDate  = (Datetime.now()).date().addDays(20);  
        
        //WHEN                                        
        test.startTest();
        opp.AccountBudget__c = ab.Id;         
        insert opp;
                      
        //THEN
        List<AccountBudget__c> abList = [Select PlannedAgainstBudget__c from AccountBudget__c where id = : ab.Id];
        System.assertEquals(true, abList[0].PlannedAgainstBudget__c == 800);
    }
}