src_old/objects/AILabel__c.object
<CustomObject>
    <description>used to define the AI model category that is used to identify the AI-analyzed result</description>
    <label>AI Label</label>
    <nameField>
        <label>AI Label Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AI Labels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/objects/JobImage__c.object
<CustomObject>
    <fields>
        <fullName>AIImageURL__c</fullName>
        <formula>$Setup.SurveyPhotoViewerSetting__c.AIImageURL__c + ImageURL__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AIImageURL</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AILabel__c</fullName>
        <formula>ProjectServiceQuestion__r.AILabel__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AI Label</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsDuplicated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>There is already another similar photo in the table.</description>
        <inlineHelpText>This photo is duplicated.</inlineHelpText>
        <label>Is Duplicated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsErrored__c</fullName>
        <defaultValue>false</defaultValue>
        <description>an error flag to indicate that the photo can not be hashed</description>
        <label>Is Errored</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PhotoHash__c</fullName>
        <description>PhotoHash</description>
        <label>PhotoHash</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PoorQualityCheck__c</fullName>
        <defaultValue>false</defaultValue>
        <description>PoorQualityCheck</description>
        <label>PoorQualityCheck</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isClassified__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Classified</label>
        <type>Checkbox</type>
    </fields>
    <label>Job Image</label>
    <nameField>
        <displayFormat>JI-{000000000}</displayFormat>
        <label>Job Images Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Images</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/classes/PhotoViewerCategorizerHandler.cls
global class PhotoViewerCategorizerHandler implements Database.Batchable<SOBject>, Database.AllowsCallouts {
    global Database.QueryLocator start(Database.BatchableContext bc){
        String sql = 'SELECT Id, AIImageUrl__c FROM JobImage__c WHERE AILabel__c != null AND PhotoHash__c != null AND IsClassified__c != true AND IsErrored__c != true AND IsDuplicated__c != true AND PoorQualityCheck__c != true';
        return Database.getQueryLocator(sql);
    }

    global void execute(Database.BatchableContext bc, List<JobImage__c> scope){
        IAIImageClassifier classifier = new AIImageClassifier(AIAccessTokenProvider.getTokenInMinutes());
        PhotoViewerCategorizer.create(classifier, scope).run();
    }

    global void finish(Database.BatchableContext bc){}
}