src_old/objects/AILabel__c.object
<CustomObject>
    <description>used to define the AI model category that is used to identify the AI-analyzed result</description>
    <label>AI Label</label>
    <nameField>
        <label>AI Label Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AI Labels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/objects/ProjectService__c.object
<CustomObject>
    <description>Project Service relates a Service to a Project and is a container used to define the instance of a Service for a specific Project. Project Service is related to Project, Job, Project Service Attribute, Project Service Certification, Project Service Equipment, Project Service Material, Project Service Question, Project Service Target, and Service.</description>
    <label>Project Service</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectServiceQuestion__c.object
<CustomObject>
    <description>Relates a Question to a Project Service. Questions from Service Question are added by default when a Service is added to a Project Service. Additional Questions can be added. Project Service Question is related to Project Service Question, Question, and Question Variant.</description>
    <fields>
        <fullName>AILabel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AI Label</label>
        <referenceTo>AILabel__c</referenceTo>
        <relationshipLabel>Project Service Questions</relationshipLabel>
        <relationshipName>Project_Service_Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectService__c</fullName>
        <label>Project Service</label>
        <referenceTo>ProjectService__c</referenceTo>
        <relationshipLabel>ProjectServiceQuestions</relationshipLabel>
        <relationshipName>ProjectServiceQuestions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>QuestionType__c</fullName>
        <formula>TEXT(Question__r.QuestionType__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Question Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Question__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>ProjectServiceQuestions</relationshipLabel>
        <relationshipName>ProjectServiceQuestions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Service Question</label>
    <nameField>
        <displayFormat>PSQ-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Service Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/Question__c.object
<CustomObject>
    <description>Question stores all of the questions stored in the system and defines the type of question (e.g. Date, Text, Y/N) and if the question is related to targets. Question is related to Question Defined Response, Question Variant.</description>
    <fields>
        <fullName>QuestionType__c</fullName>
        <label>Question Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Currency</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Multi-Select List</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Photo</fullName>
                </value>
                <value>
                    <fullName>Signature</fullName>
                </value>
                <value>
                    <fullName>Single-Select List</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                </value>
                <value>
                    <fullName>Time</fullName>
                </value>
                <value>
                    <fullName>Yes/No</fullName>
                </value>
                <value>
                    <fullName>Group</fullName>
                </value>
                <value>
                    <fullName>Barcode</fullName>
                </value>
                <value>
                    <fullName>Multi Select Target</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/classes/ProjectServiceQuestionRequest.cls
public with sharing class ProjectServiceQuestionRequest extends LightningRequestBase {
    
    public override Object filter(Object parameters) {
        String psId = parseServiceId(parameters);
        return filterQuestions(psId);
    }

    String parseServiceId(Object parameters){
        Map<String,Object> query = (Map<String,Object>) parameters;
        String psId = LightningRequestHelper.parseString(query.get('serviceId'));
        if(String.isEmpty(psId)){
            throw new AuraHandledException('The project serivce id is required.');
        }
        return psId;
    }

    List<List<String>> filterQuestions(String psId){
        List<String> rec;
        List<List<String>> rs = new List<List<String>>();
        
        for(ProjectServiceQuestion__c q: [SELECT Question__c, Question__r.Name, AILabel__c 
                                          FROM ProjectServiceQuestion__c 
                                          WHERE ProjectService__c=:psId 
                                          AND QuestionType__c = 'Photo']){
            rec = new List<String>();
            rec.add(q.Question__c);
            rec.add(q.Question__r.Name);
            rec.add(q.AILabel__c);
            rs.add(rec);
        }


        return rs;
    }
}