src_old/objects/ApexJobTracker__c.object
<CustomObject>
    <description>This will keep track of all the batch jobs.</description>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Apex Jobs Tracker</relationshipLabel>
        <relationshipName>Apex_Jobs_Tracker</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failure</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Apex Job Tracker</label>
    <nameField>
        <displayFormat>AJT-{000000000}</displayFormat>
        <label>Apex Job Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Jobs Tracker</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>NumberOfLocations__c</fullName>
        <label># of Locations</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PONumber__c</fullName>
        <label>PO #</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PreBill__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Pre Bill</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProjectType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Type</label>
        <referenceTo>ProjectType__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src_old/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>PreBillPercent__c</fullName>
        <label>PreBill %</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
</CustomObject>

src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>A search field that indicates the name of the opportunity for the Project.</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Type</label>
        <referenceTo>ProjectType__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planning</fullName>
                    <default>true</default>
                    <label>Planning</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Launched</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ended</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ProjectAccount__c.object
<CustomObject>
    <description>Project Account maps an Account to a Project and defines how the Account will be billed. Project Account is related to Project, Account, and Account Address.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please make sure this account&apos;s &apos;Can Request Project&apos; setting is enabled.</errorMessage>
            <filterItems>
                <field>Account.CanRequestProjects__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Project Accounts</relationshipLabel>
        <relationshipName>Project_Accounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Project Accounts</relationshipLabel>
        <relationshipName>Project_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PONumber__c</fullName>
        <label>PO #</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Project_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Account</label>
    <nameField>
        <displayFormat>PA-{0000000}</displayFormat>
        <label>Project Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectInvoice__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Project Invoices</relationshipLabel>
        <relationshipName>Project_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PONumber__c</fullName>
        <label>PO #</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProjectAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Account</label>
        <referenceTo>ProjectAccount__c</referenceTo>
        <relationshipLabel>Project Invoices</relationshipLabel>
        <relationshipName>Project_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Invoices</relationshipLabel>
        <relationshipName>Project_Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Invoiced</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Grouped</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>PreBill</fullName>
                    <label>Pre Bill</label>
                </value>
                <value>
                    <fullName>PostExecution</fullName>
                    <label>Post Execution</label>
                </value>
                <value>
                    <fullName>Reconcile</fullName>
                </value>
                <value>
                    <fullName>Unreconciled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project Invoice</label>
    <nameField>
        <displayFormat>INV-{000000000}</displayFormat>
        <label>Project Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectInvoiceLineItem__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Usage</fullName>
                </value>
                <value>
                    <fullName>Lumpsum</fullName>
                </value>
                <value>
                    <fullName>Unreconciled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project Invoice Line Item</label>
    <nameField>
        <displayFormat>INVLI-{000000000}</displayFormat>
        <label>Project Invoice Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectLocation__c.object
<CustomObject>
    <description>Project Location relates a Location to a Project. Project Location is related Project, Job, and Location.</description>
    <fields>
        <fullName>BillingStatus__c</fullName>
        <label>Billing Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Billable</fullName>
                    <default>true</default>
                    <label>Billable</label>
                </value>
                <value>
                    <fullName>NotBillable</fullName>
                    <label>Not Billable</label>
                </value>
                <value>
                    <fullName>NeedsReview</fullName>
                    <label>Needs Review</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Invoiced__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Invoiced</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LocationExecutedDate__c</fullName>
        <label>Location Executed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ProjectType__c</fullName>
        <formula>Project__r.ProjectType__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>ProjectLocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Job Created</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <formula>IF(Location__r.Parent__c != null, Location__r.Parent__r.Name, &apos;&apos;)</formula>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <label>Project Location</label>
    <nameField>
        <displayFormat>PL-{0000}</displayFormat>
        <label>Location ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/classes/BatchProcessApplyPBCreditTest.cls
@isTest
private class BatchProcessApplyPBCreditTest {
    @testSetup
    static void setup() {
        TriggerUtil.skipAllTriggers();

        TestDataUtil.init();
        
        TestProject tP = TestProject.create('demo')
                         .addAll();
        initTestData(tP.getInstance().Id);
    }

    static void initTestData(String pId) {
        setupProjectLocation(pId);
        setupOpportunity(pId);
        Project__c p = TestProject.getProjects()[0];
        createPreBillProjectInvoice(p);
        
        
        //setupPriBill(pId);
    }

    static void setupProjectLocation(String pId) {
        ProjectLocation__c pl = TestProject.getLocations(pId)[0];
        pl.LocationExecutedDate__c = Date.today();
        pl.Invoiced__c = false;
        pl.BillingStatus__c = CONSTANTS.BILLING_STATUS_BILLABLE;        
        update pl;
    }

    
    
    static void setupOpportunity(String pId) {
        
        Product2 Prod =  new Product2();
        Prod.Name='NewProd';        
        Prod.IsActive=True;
        Prod.PreBillPercent__c = 60;
        insert Prod;
        
        PricebookEntry pbe = new PricebookEntry();
        pbe.Product2Id=Prod.Id;
        pbe.IsActive=True;
        pbe.UnitPrice=70;
        pbe.Pricebook2Id = Test.getStandardPricebookId();
        pbe.UseStandardPrice=false;
        insert pbe;    
        
        
        Opportunity opp = new Opportunity();
        opp.Name = 'demo';
        opp.Project__c = pId;
        opp.ProjectType__c = [SELECT Id FROM ProjectType__c][0].Id;
        opp.StageName = 'Proposal/Price Quote';
        opp.CloseDate = Date.today().addDays(10);
        opp.PreBill__c = true;
        opp.NumberOfLocations__c = 5;
        insert opp;
        
        OpportunityLineItem opli = new OpportunityLineItem();
        opli.UnitPrice = 70;
        opli.Quantity = 12;
        opli.Product2Id = Prod.id;
        opli.OpportunityId=opp.Id;
        opli.PricebookEntryId=pbe.id;
        //opli.TotalPrice = 60;
        
        insert opli;

        List<ProjectAccount__c> accts = [Select id, Opportunity__c from ProjectAccount__c 
            where Project__c = :pId];
        for(ProjectAccount__c a: accts) {
            a.Opportunity__c = opp.Id;
        }
        update accts;
     }

    
     static void createPreBillProjectInvoice(Project__c project)
    {
        String account = '';
        List<String> oppIds = new List<String>();
        List<OpportunityLineItem> olList = new List<OpportunityLineItem>();
        Map<String, List<OpportunityLineItem>> oppToOppLImap = new Map<String, List<OpportunityLineItem>>();
        List<ProjectInvoiceLineItem__c> pils = new List<ProjectInvoiceLineItem__c>();
        
        List<ProjectAccount__c> projectaccounts = [Select Id, PONumber__c, Opportunity__r.RequestedDate__c, Opportunity__r.NumberOfLocations__c, 
                                                   Opportunity__r.ResponsibleParty__c, Opportunity__c, Opportunity__r.PreBill__c, 
                                                   ResponsibleParty__c, Account__c, BillToContact__c from ProjectAccount__c WHERE Project__c = :project.Id
                                                  AND Opportunity__c != null AND Opportunity__r.PreBill__c = true];

		if (projectaccounts.IsEmpty())
            return;
        

        for (ProjectAccount__c pa : projectaccounts)
        {
            if (pa.Opportunity__c != null)
            	oppIds.add(pa.Opportunity__c);
            
        }
        
        
        if (!oppIds.IsEmpty())
        {
            olList = [Select Id, Opportunity.NumberOfLocations__c, Opportunity.Id, UnitPrice, TotalPrice, Product2.PreBillPercent__c 
                      FROM OpportunityLineItem 
                      WHERE OpportunityId IN :oppIds AND Product2.PreBillPercent__c > 0 and TotalPrice > 0];
            
            
            for (OpportunityLineItem ol : olList)
            {
                if (oppToOppLImap.get(ol.Opportunity.Id) != null)
                {
                    oppToOppLImap.get(ol.Opportunity.Id).add(ol);
                }
                else
                {
                    List<OpportunityLineItem> firstolList = new List<OpportunityLineItem>();
                    firstolList.add(ol);
                    oppToOppLImap.put(ol.Opportunity.Id, firstolList);
                }
                
            }
            
        }

        for (ProjectAccount__c pa : projectaccounts)
        {
            if (oppToOppLImap.get(pa.Opportunity__c) == null) 
                continue;

            ProjectInvoice__c pi = new ProjectInvoice__c();
            pi.Project__c = project.Id;
            pi.Status__c = Constants.PROJECT_INVOICE_STATUS_CREATED;
            pi.Type__c = Constants.PROJECT_INVOICE_TYPE_PREBILL;
            pi.LawsonProcessType__c = Constants.LAWSON_PROCESS_TYPE_PB;
            pi.Account__c = pa.Account__c;
            pi.BillToContact__c = pa.BillToContact__c;
            pi.ProjectAccount__c = pa.Id;
            pi.PONumber__c = pa.PONumber__c;
            if (project.StartDate__c != null){
                
                Date duedate = project.StartDate__c.addDays(AppUtil.ProjectInvoiceDueDateThreshold * -1);

                //OH2-924
                pi.DueDate__c = (duedate > datetime.now().date()) ? duedate : datetime.now().date();
            }
            
            pi.ResponsibleParty__c = pa.Opportunity__r.ResponsibleParty__c;
            insert pi;

            for (OpportunityLineItem li : oppToOppLImap.get(pa.Opportunity__c))
            {
                ProjectInvoiceLineItem__c pil = new ProjectInvoiceLineItem__c();
                pil.ProjectInvoice__c = pi.Id;
                pil.Type__c = Constants.PROJECT_INVOICE_LINEITEM_TYPE_LUMPSUM;
                pil.Amount__c = li.TotalPrice * li.Product2.PreBillPercent__c;
                pil.Description__c = 'PP ' + li.Product2.PreBillPercent__c * 100 + '% ' + 'of ' + pa.Opportunity__r.NumberOfLocations__c + ' clubs ' + '@ $' + li.UnitPrice;
                pils.add(pil);
                
            }
        } 
        insert pils;                
    }
    
    
    static void setupPriBill(String pId) {
        ProjectLocation__c pl = TestProject.getLocations(pId)[0];
        pl.LocationExecutedDate__c = Date.today();
        pl.Invoiced__c = false;
        pl.BillingStatus__c = CONSTANTS.BILLING_STATUS_BILLABLE;        
        update pl;
    }

    
    static List<ApexJobTracker__c> getTrackers() {
        return [SELECT Status__c, Operation__c, Object__c, Response__c from ApexJobTracker__c];
    }

    @isTest
    static void testApplyCredit() {
        // Given
        Project__c p = TestProject.getProjects()[0];
        
        List<ApexJobTracker__c> trackers = getTrackers();
        QA.isTrue(trackers.isEmpty(), 'no trackers before test');

        // When
        test.startTest();
        BatchProcessApplyPBCredit pbInvoice = new BatchProcessApplyPBCredit();
        Database.executeBatch(pbInvoice);
        test.stopTest();

        // Then
        trackers = getTrackers();
        QA.isTrue(!trackers.isEmpty(), 'tracker is created');
        QA.EQ(1, trackers.size(), 'one tracker created.');
        ApexJobTracker__c tracker = trackers[0];
        QA.EQ('Success', tracker.Status__c, 'should succeed:' + tracker.Response__c);
        QA.EQ('ProjectInvoice', tracker.Object__c, 'project Invoice');
        QA.EQ('Apply PB Credit', tracker.Operation__c, 'Apply PB Credit');
    }

}