src_old/objects/ApexJobTracker__c.object
<CustomObject>
    <description>This will keep track of all the batch jobs.</description>
    <fields>
        <fullName>BatchProcessId__c</fullName>
        <label>Batch Process Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Id1__c</fullName>
        <label>Id1</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>ProjectService</fullName>
                </value>
                <value>
                    <fullName>ProjectLocation</fullName>
                </value>
                <value>
                    <fullName>Job</fullName>
                </value>
                <value>
                    <fullName>JobAttemptWorker</fullName>
                </value>
                <value>
                    <fullName>ProjectInvoice</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Operation__c</fullName>
        <label>Operation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Apply PB Credit</fullName>
                </value>
                <value>
                    <fullName>Cancel Job</fullName>
                </value>
                <value>
                    <fullName>Cancel Project</fullName>
                </value>
                <value>
                    <fullName>Cancel ProjectLocation</fullName>
                </value>
                <value>
                    <fullName>Cancel ProjectService</fullName>
                </value>
                <value>
                    <fullName>Close Project</fullName>
                </value>
                <value>
                    <fullName>Create Attempt</fullName>
                </value>
                <value>
                    <fullName>Create Job Materials</fullName>
                </value>
                <value>
                    <fullName>Create Jobs</fullName>
                </value>
                <value>
                    <fullName>Create Labor Invoice</fullName>
                </value>
                <value>
                    <fullName>Create Product Invoice</fullName>
                </value>
                <value>
                    <fullName>Create SalesTax Invoice</fullName>
                </value>
                <value>
                    <fullName>Delete AllProjectJobs</fullName>
                </value>
                <value>
                    <fullName>Delete Job</fullName>
                </value>
                <value>
                    <fullName>Delete Project</fullName>
                </value>
                <value>
                    <fullName>Delete ProjectLocation</fullName>
                </value>
                <value>
                    <fullName>Delete ProjectService</fullName>
                </value>
                <value>
                    <fullName>Import JobAttemptWorkers</fullName>
                </value>
                <value>
                    <fullName>Import Jobs</fullName>
                </value>
                <value>
                    <fullName>Import ProjectLocations</fullName>
                </value>
                <value>
                    <fullName>Launch Project</fullName>
                </value>
                <value>
                    <fullName>Schedule ProjectLocation</fullName>
                </value>
                <value>
                    <fullName>Schedule ProjectService</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Apex Jobs Tracker</relationshipLabel>
        <relationshipName>Apex_Jobs_Tracker</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartDateTime__c</fullName>
        <label>Start Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failure</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Apex Job Tracker</label>
    <nameField>
        <displayFormat>AJT-{000000000}</displayFormat>
        <label>Apex Job Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Jobs Tracker</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <fields>
        <fullName>ApexJobName__c</fullName>
        <description>A field that indicates the apex job name of the Project.</description>
        <inlineHelpText>The apex job name of the project</inlineHelpText>
        <label>ApexJobName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BatchProcessId__c</fullName>
        <description>A field that indicates the ID number of the Batch Process for the Project.</description>
        <inlineHelpText>The ID number for the batch process.</inlineHelpText>
        <label>BatchProcessId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BookBudgetedOnly__c</fullName>
        <defaultValue>false</defaultValue>
        <description>A checkbox that indicates whether the Project was book budgeted only.</description>
        <inlineHelpText>If selected, the project was book budgeted only.</inlineHelpText>
        <label>BookBudgetedOnly</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BudgetedLocationsCount__c</fullName>
        <description>An entry field that indicates the number of budgeted locations for the Project.</description>
        <inlineHelpText>Expected number of locations</inlineHelpText>
        <label>Budgeted Locations Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>An entry field that indicates the end date of the Project.</description>
        <inlineHelpText>The last date available to complete execution</inlineHelpText>
        <label>Project End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LocationTotalCount__c</fullName>
        <description>A field that indicates the count of the locations added to the project.</description>
        <inlineHelpText>The count of the locations added to the project.</inlineHelpText>
        <label>Actual Location Count</label>
        <summaryFilterItems>
            <field>ProjectLocation__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Canceled</value>
        </summaryFilterItems>
        <summaryForeignKey>ProjectLocation__c.Project__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>ProjectType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Type</label>
        <referenceTo>ProjectType__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>An entry field that indicates the start date of the Project.</description>
        <inlineHelpText>The date available to start execution</inlineHelpText>
        <label>Project Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planning</fullName>
                    <default>true</default>
                    <label>Planning</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Launched</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ended</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <recordTypes>
        <fullName>Canceled</fullName>
        <active>true</active>
        <label>Canceled</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ProjectLocation__c.object
<CustomObject>
    <description>Project Location relates a Location to a Project. Project Location is related Project, Job, and Location.</description>
    <fields>
        <fullName>ProjectType__c</fullName>
        <formula>Project__r.ProjectType__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>ProjectLocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Job Created</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project Location</label>
    <nameField>
        <displayFormat>PL-{0000}</displayFormat>
        <label>Location ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectService__c.object
<CustomObject>
    <description>Project Service relates a Service to a Project and is a container used to define the instance of a Service for a specific Project. Project Service is related to Project, Job, Project Service Attribute, Project Service Certification, Project Service Equipment, Project Service Material, Project Service Question, Project Service Target, and Service.</description>
    <fields>
        <fullName>ProjectType__c</fullName>
        <formula>Project__r.ProjectType__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>ProjectServices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RefreshSummary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag that indicates that project service needs it&apos;s summary refreshed</description>
        <label>RefreshSummary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Executed</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project Service</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Services</pluralLabel>
    <recordTypes>
        <fullName>Canceled</fullName>
        <active>true</active>
        <label>Canceled</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectType__c.object
<CustomObject>
    <description>Project Type defines a collection of Services and sets configuration options for a Project. Project Type is related to Project, Project Type Execution Company, Project Type Service, and Location Assignment.</description>
    <label>Project Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Types</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/classes/ScheduleLocationsModalController.cls
public with sharing class ScheduleLocationsModalController {
    
    public String messageHead {get;set;}
    public String messageBody {get;set;}
    public String messageSeverity {get;set;}
    public ScheduleLocationsModalController(){}
    
    public void submitSchedulingBatchJob()
    {
        
        Id projectid = ApexPages.currentPage().getParameters().get('projectid');
        String exceedBudgeted = ApexPages.currentPage().getParameters().get('ExceedBudgeted');
        
        
        Project__c project = [SELECT Id, Name, StartDate__c, EndDate__c, Status__c, ProjectType__c, 
                              ProjectType__r.Name, BudgetedLocationsCount__c, LocationTotalCount__c,   
                              ApexJobName__c, BatchProcessId__c, RecordTypeId, 
                              BookBudgetedOnly__c 
                              FROM Project__c WHERE ID = :projectid FOR UPDATE];
        if(!validateReserve(project)) {
            return;
        }
        
        try{
            TriggerUtil.skipProjectTrigger = true;
            project.BookBudgetedOnly__c= true;
            if(exceedBudgeted == '1'){
                project.BookBudgetedOnly__c= false;
            }
            update project; 
            
            SchedulingStrategy schedulingStrategyObject = SchedulingStrategyFactory.getSchedulingStrategy(project.ProjectType__r.Name);
            Boolean isBatchJob = schedulingStrategyObject.isBatchJob(project, exceedBudgeted);
            if(isBatchJob){
                
                ApexJobTracker__c ajt = new   ApexJobTracker__c();
                ajt.Object__c = 'Project';
                ajt.Operation__c = 'Create Jobs';
                ajt.Project__c = project.Id;
                ajt.Status__c = 'In Progress';
                ajt.StartDateTime__c = DateTime.Now();
                ajt.Id1__c = String.ValueOf(project.Id);
                insert ajt;
                
                string resultIds;
                Integer locationsBatchSize = (project.Status__c == CONSTANTS.PROJECT_STATUS_PLANNING) ? 250 : 100;
                ProjectScheduler batch = new ProjectScheduler(project);
                String batchId = Database.ExecuteBatch(batch, locationsBatchSize);
                
                ProjectActionsHelper.LockProject(project, 'Create Jobs', batchId);
                TriggerUtil.skipProjectTrigger = true;
                update project; 
            
                messageHead = 'Create jobs request has started.';
                messageBody = 'Please allow few minutes to process your request. You will receive an email notification once request is processed.';
                messageSeverity = 'info';
            }
            else {
                List<ProjectLocation__c> scope = Database.query(schedulingStrategyObject.getSchedulableLocationsQuery(project, ''));
                if(scope.size() == 0){
                    messageHead = 'No New Locations';
                    messageBody = 'There are no new locations to create jobs';
                    messageSeverity = 'warning';
                }
                else{
                    Integer ct = SchedulingStrategyObject.ScheduleLocations(scope, project.ID);
                    messageHead = 'Jobs created';
                    messageBody = 'Refer to location and job sections for results.';
                    messageSeverity = 'confirm';
                    
                    if(project.Status__c != CONSTANTS.PROJECT_STATUS_PLANNING){
                        //Set Project service refresh flag to true
                        TriggerUtil.SkipProjectServiceTrigger = true;
                        List<ProjectService__c> psList = [Select Id, RefreshSummary__c from ProjectService__c where Status__c != 'Canceled' AND Project__c =:project.Id];
                        for (ProjectService__c ps : psList){
                            ps.RefreshSummary__c = true;
                        }
                        update psList;  
                    }
                }
                TriggerUtil.skipProjectTrigger = true;
		        //Comment Versioning Code
                /*
                if(project.Status__c != CONSTANTS.PROJECT_STATUS_PLANNING) {
                    AppUtil.UpdateProjectVersion(project.Id);
                }
                */
            }
        }
        catch(System.DmlException e) {
            messageHead = 'Failed to create job(s)';
            messageBody = e.getDmlMessage(0);
            messageSeverity = 'error';
        }        
        catch(Exception ex){
            TriggerUtil.skipProjectTrigger = true;
            string err = '';
            update project; 
            messageHead = 'Create Error';
            messageBody = 'There was a problem processing your request. Please try again.';
            System.debug('The following exception has occurred: ' + ex.getMessage());
            messageSeverity = 'error';
            
        }
    }
    
    private Boolean validateReserve(Project__c project){
        Integer  psCount = [select count() FROM ProjectService__c WHERE Project__c =: project.Id AND Status__c != 'Canceled'];
        if(psCount == 0) {
            messageHead = 'Error - Missing Project Service.';
            messageBody = 'Please add Project Service(s) to Create Jobs.';
            messageSeverity = 'error';
            return false;
        }
        return true;
    }
}