src_old/objects/ApexJobTracker__c.object
<CustomObject>
    <description>This will keep track of all the batch jobs.</description>
    <fields>
        <fullName>EndDateTime__c</fullName>
        <label>End Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Operation__c</fullName>
        <label>Operation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Apply PB Credit</fullName>
                </value>
                <value>
                    <fullName>Cancel Job</fullName>
                </value>
                <value>
                    <fullName>Cancel Project</fullName>
                </value>
                <value>
                    <fullName>Cancel ProjectLocation</fullName>
                </value>
                <value>
                    <fullName>Cancel ProjectService</fullName>
                </value>
                <value>
                    <fullName>Close Project</fullName>
                </value>
                <value>
                    <fullName>Create Attempt</fullName>
                </value>
                <value>
                    <fullName>Create Job Materials</fullName>
                </value>
                <value>
                    <fullName>Create Jobs</fullName>
                </value>
                <value>
                    <fullName>Create Labor Invoice</fullName>
                </value>
                <value>
                    <fullName>Create Product Invoice</fullName>
                </value>
                <value>
                    <fullName>Create SalesTax Invoice</fullName>
                </value>
                <value>
                    <fullName>Delete AllProjectJobs</fullName>
                </value>
                <value>
                    <fullName>Delete Job</fullName>
                </value>
                <value>
                    <fullName>Delete Project</fullName>
                </value>
                <value>
                    <fullName>Delete ProjectLocation</fullName>
                </value>
                <value>
                    <fullName>Delete ProjectService</fullName>
                </value>
                <value>
                    <fullName>Import JobAttemptWorkers</fullName>
                </value>
                <value>
                    <fullName>Import Jobs</fullName>
                </value>
                <value>
                    <fullName>Import ProjectLocations</fullName>
                </value>
                <value>
                    <fullName>Launch Project</fullName>
                </value>
                <value>
                    <fullName>Schedule ProjectLocation</fullName>
                </value>
                <value>
                    <fullName>Schedule ProjectService</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Apex Jobs Tracker</relationshipLabel>
        <relationshipName>Apex_Jobs_Tracker</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failure</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Apex Job Tracker</label>
    <nameField>
        <displayFormat>AJT-{000000000}</displayFormat>
        <label>Apex Job Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Jobs Tracker</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <fields>
        <fullName>ProjectType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Type</label>
        <referenceTo>ProjectType__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planning</fullName>
                    <default>true</default>
                    <label>Planning</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Launched</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ended</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ProjectLocation__c.object
<CustomObject>
    <description>Project Location relates a Location to a Project. Project Location is related Project, Job, and Location.</description>
    <fields>
        <fullName>ProjectType__c</fullName>
        <formula>Project__r.ProjectType__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>ProjectLocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Job Created</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project Location</label>
    <nameField>
        <displayFormat>PL-{0000}</displayFormat>
        <label>Location ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectType__c.object
<CustomObject>
    <description>Project Type defines a collection of Services and sets configuration options for a Project. Project Type is related to Project, Project Type Execution Company, Project Type Service, and Location Assignment.</description>
    <label>Project Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Types</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/classes/ProjectScheduler.cls
global class ProjectScheduler implements Database.Batchable<sObject>, Database.Stateful {
    
    Project__c project;
    SchedulingStrategy algorithmStrategy;
    Integer scheduledItemCount = 0;
    Integer totalItemCount = 0;
    String operation = '';
    
    global ProjectScheduler(Project__c project){
        this.project = project;
    }
    
    global ProjectScheduler(Project__c project, String operation){
        this.project = project;
        this.operation = operation;
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        algorithmStrategy = SchedulingStrategyFactory.getSchedulingStrategy(this.project.ProjectType__r.Name);
        String projectId = project.Id;
        return Database.getQueryLocator(algorithmStrategy.getSchedulableLocationsQuery(this.project, operation));
    }
    
    global void execute(Database.BatchableContext BC, List<ProjectLocation__c> scope) {
        totalItemCount += scope.size();
        scheduledItemCount += algorithmStrategy.ScheduleLocations((List<ProjectLocation__c>)scope, this.project.Id, this.operation);
    }   
    
    global void finish(Database.BatchableContext BC) {
        // Get the ID of the AsyncApexJob representing this batch job
        // from Database.BatchableContext.
        // Query the AsyncApexJob object to retrieve the current job's information.
        AsyncApexJob a = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed, TotalJobItems, CreatedBy.Email FROM AsyncApexJob WHERE Id = :BC.getJobId()];        
        System.debug('Batch Job Status:' + a.Status);
        ProjectActionsHelper.UnlockProject(project);
        TriggerUtil.skipProjectTrigger = true;
        update project;
        
        List<ApexJobTracker__c> ajt = [Select Id,EndDateTime__c, Status__c FROM ApexJobTracker__c WHERE Project__c = :this.project.Id AND Operation__c = 'Create Jobs' AND Status__c != 'Success' ];
        
        if(ajt.size()>0){
           ajt[0].Status__c = 'Success';
           ajt[0].EndDateTime__c = DateTime.Now();
           update ajt;
        }
        
        
        if(this.operation == 'update jobs'){
            return;
        }
        
        try {
            // Send an email to the Apex job's submitter notifying of job completion.
            String messageBody = 'Your schedule locations job for ' + project.Name + ' is completed with ' + scheduledItemCount + ' bookings';
            String messageSubject = project.Name + ' schedule locations status - ' + a.Status;
            
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            
            AppUtil.setOrgWideEmailAddress(mail);
                        
            String[] toAddresses = new String[] {a.CreatedBy.Email};
 
            if(totalItemCount == 0){
                messageBody += '. No new locations to reserve.';
            }
            else if((totalItemCount -  scheduledItemCount) > 0){
                
                messageBody += ' and '+ (totalItemCount -  scheduledItemCount )+ ' failures.';
            }
            
            EmailHelper.SendEmail(mail,toAddresses,messageSubject,messageBody,true);
            
        }
        catch(Exception e){
            System.debug('Email send error:' + e);
        }
        
    }
}