src_old/objects/ApexJobTracker__c.object
<CustomObject>
    <description>This will keep track of all the batch jobs.</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failure</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Apex Job Tracker</label>
    <nameField>
        <displayFormat>AJT-{000000000}</displayFormat>
        <label>Apex Job Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Jobs Tracker</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/objects/ProcessLastSyncTime__c.object
<CustomObject>
    <fields>
        <fullName>CurrentProcessId__c</fullName>
        <label>Current Process Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProcessName__c</fullName>
        <label>Process Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Process Last Sync Time</label>
    <nameField>
        <label>Process Last Sync Time Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processes Last Sync Time</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/objects/ProjectInvoice__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Invoiced</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Grouped</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>PreBill</fullName>
                    <label>Pre Bill</label>
                </value>
                <value>
                    <fullName>PostExecution</fullName>
                    <label>Post Execution</label>
                </value>
                <value>
                    <fullName>Reconcile</fullName>
                </value>
                <value>
                    <fullName>Unreconciled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project Invoice</label>
    <nameField>
        <displayFormat>INV-{000000000}</displayFormat>
        <label>Project Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectInvoiceLineItem__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LawsonSubAccount2__c</fullName>
        <label>Lawson Sub Account</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0000</fullName>
                </value>
                <value>
                    <fullName>7605</fullName>
                </value>
                <value>
                    <fullName>7606</fullName>
                </value>
                <value>
                    <fullName>230</fullName>
                </value>
                <value>
                    <fullName>238</fullName>
                </value>
                <value>
                    <fullName>246</fullName>
                </value>
                <value>
                    <fullName>210</fullName>
                </value>
                <value>
                    <fullName>100</fullName>
                </value>
                <value>
                    <fullName>450</fullName>
                </value>
                <value>
                    <fullName>400</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ProjectInvoice__c</fullName>
        <label>Project Invoice</label>
        <referenceTo>ProjectInvoice__c</referenceTo>
        <relationshipLabel>Project Invoice Line Items</relationshipLabel>
        <relationshipName>Project_Invoice_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ServiceType__c</fullName>
        <label>Service Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Labor</fullName>
                </value>
                <value>
                    <fullName>Product</fullName>
                </value>
                <value>
                    <fullName>SalesTax</fullName>
                </value>
                <value>
                    <fullName>Unreconciled</fullName>
                </value>
                <value>
                    <fullName>PB Applied</fullName>
                </value>
                <value>
                    <fullName>Payment</fullName>
                </value>
                <value>
                    <fullName>Lawson</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Usage</fullName>
                </value>
                <value>
                    <fullName>Lumpsum</fullName>
                </value>
                <value>
                    <fullName>Unreconciled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project Invoice Line Item</label>
    <nameField>
        <displayFormat>INVLI-{000000000}</displayFormat>
        <label>Project Invoice Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectInvoiceLineItemDetail__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LaborTaxLawsonID__c</fullName>
        <label>Labor Tax Lawson ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProjectInvoiceLineItem__c</fullName>
        <label>Project Invoice Line Item</label>
        <referenceTo>ProjectInvoiceLineItem__c</referenceTo>
        <relationshipLabel>Project Invoice Line Items Detail</relationshipLabel>
        <relationshipName>Project_Invoice_Line_Items_Detail</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SalesTax__c</fullName>
        <formula>(BLANKVALUE(LaborTaxRate__c,0) * (Rate__c / 100))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Tax</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Project Invoice Line Item Detail</label>
    <nameField>
        <displayFormat>PILID-{000000000}</displayFormat>
        <label>Project Invoice Line Item Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Invoice Line Items Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/BatchProcessSalesTaxInvoice.cls
global class BatchProcessSalesTaxInvoice implements Database.Batchable<sObject>, Database.Stateful {
    
    
    
	Set<String> clearedpis = new Set<String>();    
	ApexJobTracker__c ajt {get; set;}    
    
    global BatchProcessSalesTaxInvoice() {
        
    }
    
    global BatchProcessSalesTaxInvoice(string projectTypeId) {
        
    }
        
    global Database.QueryLocator start(Database.BatchableContext BC) {
        
		ajt = AppUtil.InsertApexJobTrackerRecord('ProjectInvoice', 'Create SalesTax Invoice', '');        
        
        return Database.getQueryLocator([SELECT Id, Name, ProjectInvoice__c FROM ProjectInvoiceLineItem__c WHERE 
                                         ServiceType__c = :CONSTANTS.PROJECT_INVOICE_LINEITEM_SERVICETYPE_LABOR AND
                                         ProjectInvoice__r.Status__c = :CONSTANTS.PROJECT_INVOICE_STATUS_CREATED
                                        ]);
        
    }
   
    global void execute(Database.BatchableContext BC, List<ProjectInvoiceLineItem__c> scope) {
        
        List<ProjectInvoiceLineItem__c> newpilis = new List<ProjectInvoiceLineItem__c>();
        ProjectInvoiceLineItem__c pili = scope[0];
        
        //Check if there's an existing Line Item for SalesTax and remove it
        if (!clearedpis.contains(pili.ProjectInvoice__c))
        {
            delete [SELECT Id FROM ProjectInvoiceLineItem__c WHERE ProjectInvoice__c = :pili.ProjectInvoice__c AND 
                    ServiceType__c = :CONSTANTS.PROJECT_INVOICE_LINEITEM_SERVICETYPE_SALESTAX];
			clearedpis.add(pili.ProjectInvoice__c);
        }
        
        AggregateResult[] aggresults = [SELECT LaborTaxLawsonID__c, SUM(SalesTax__c) total FROM ProjectInvoiceLineItemDetail__c 
                                 		WHERE ProjectInvoiceLineItem__c = :pili.Id AND LaborTaxLawsonID__c != null 
                                        GROUP BY LaborTaxLawsonID__c HAVING SUM(SalesTax__c) > 0];
        
        for (AggregateResult ar : aggresults)  {
            string lawsontaxid = ar.get(CONSTANTS.CURRENTNAMESPACEPREFIX + 'LaborTaxLawsonID__c') == null? '':String.valueof(ar.get(CONSTANTS.CURRENTNAMESPACEPREFIX + 'LaborTaxLawsonID__c'));
            string lawsonsubaccount = lawsontaxid.right(3);
            ProjectInvoiceLineItem__c newpili = new ProjectInvoiceLineItem__c();
            newpili.ProjectInvoice__c = pili.ProjectInvoice__c;
            newpili.Description__c = 'Salestax for: ' + lawsontaxid; 
            newpili.Type__c = Constants.PROJECT_INVOICE_LINEITEM_TYPE_LUMPSUM;
            newpili.ServiceType__c = Constants.PROJECT_INVOICE_LINEITEM_SERVICETYPE_SALESTAX;
            newpili.Amount__c = ar.get('total') == null? 0:Decimal.valueOf(String.valueof(ar.get('total')));
            newpili.Rate__c = ar.get('total') == null? 0:Decimal.valueOf(String.valueof(ar.get('total')));
            newpili.LawsonSubAccount2__c = lawsonsubaccount;
            newpilis.add(newpili);
        }

		insert newpilis;        
    }

   	global void finish(Database.BatchableContext BC) {
    
        string status = 'Success';
        AsyncApexJob a = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed, TotalJobItems, CreatedBy.Email FROM AsyncApexJob WHERE Id = :BC.getJobId()];    
        
        if (a.NumberOfErrors > 0)
        {
        	status = 'Failure';
        }
        AppUtil.UpdateApexJobTracker(ajt.Id,status,null, DateTime.Now(), false);                
    
        //to clear batch processed
        EndProcess('ProjectInvoice');   
    }
    
     public static void EndProcess(String entity){
        
        List<ProcessLastSyncTime__c> plsts = [Select Id, CurrentProcessId__c 
                                              From ProcessLastSyncTime__c 
                                              WHERE ProcessName__c =: entity LIMIT 1];                
        
        plsts[0].CurrentProcessId__c = '';
        update plsts[0];
    }
    
}