src_old/objects/ApexJobTracker__c.object
<CustomObject>
    <description>This will keep track of all the batch jobs.</description>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>ProjectService</fullName>
                </value>
                <value>
                    <fullName>ProjectLocation</fullName>
                </value>
                <value>
                    <fullName>Job</fullName>
                </value>
                <value>
                    <fullName>JobAttemptWorker</fullName>
                </value>
                <value>
                    <fullName>ProjectInvoice</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Operation__c</fullName>
        <label>Operation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Apply PB Credit</fullName>
                </value>
                <value>
                    <fullName>Cancel Job</fullName>
                </value>
                <value>
                    <fullName>Cancel Project</fullName>
                </value>
                <value>
                    <fullName>Cancel ProjectLocation</fullName>
                </value>
                <value>
                    <fullName>Cancel ProjectService</fullName>
                </value>
                <value>
                    <fullName>Close Project</fullName>
                </value>
                <value>
                    <fullName>Create Attempt</fullName>
                </value>
                <value>
                    <fullName>Create Job Materials</fullName>
                </value>
                <value>
                    <fullName>Create Jobs</fullName>
                </value>
                <value>
                    <fullName>Create Labor Invoice</fullName>
                </value>
                <value>
                    <fullName>Create Product Invoice</fullName>
                </value>
                <value>
                    <fullName>Create SalesTax Invoice</fullName>
                </value>
                <value>
                    <fullName>Delete AllProjectJobs</fullName>
                </value>
                <value>
                    <fullName>Delete Job</fullName>
                </value>
                <value>
                    <fullName>Delete Project</fullName>
                </value>
                <value>
                    <fullName>Delete ProjectLocation</fullName>
                </value>
                <value>
                    <fullName>Delete ProjectService</fullName>
                </value>
                <value>
                    <fullName>Import JobAttemptWorkers</fullName>
                </value>
                <value>
                    <fullName>Import Jobs</fullName>
                </value>
                <value>
                    <fullName>Import ProjectLocations</fullName>
                </value>
                <value>
                    <fullName>Launch Project</fullName>
                </value>
                <value>
                    <fullName>Schedule ProjectLocation</fullName>
                </value>
                <value>
                    <fullName>Schedule ProjectService</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Apex Jobs Tracker</relationshipLabel>
        <relationshipName>Apex_Jobs_Tracker</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <description>tracker execution response</description>
        <label>Response</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failure</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Apex Job Tracker</label>
    <nameField>
        <displayFormat>AJT-{000000000}</displayFormat>
        <label>Apex Job Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Jobs Tracker</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>ProjectType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Type</label>
        <referenceTo>ProjectType__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>A search field that indicates the name of the opportunity for the Project.</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Type</label>
        <referenceTo>ProjectType__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planning</fullName>
                    <default>true</default>
                    <label>Planning</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Launched</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ended</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ProjectAccount__c.object
<CustomObject>
    <description>Project Account maps an Account to a Project and defines how the Account will be billed. Project Account is related to Project, Account, and Account Address.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Project Accounts</relationshipLabel>
        <relationshipName>Project_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Project_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Account</label>
    <nameField>
        <displayFormat>PA-{0000000}</displayFormat>
        <label>Project Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectLocation__c.object
<CustomObject>
    <description>Project Location relates a Location to a Project. Project Location is related Project, Job, and Location.</description>
    <fields>
        <fullName>BillingStatus__c</fullName>
        <label>Billing Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Billable</fullName>
                    <default>true</default>
                    <label>Billable</label>
                </value>
                <value>
                    <fullName>NotBillable</fullName>
                    <label>Not Billable</label>
                </value>
                <value>
                    <fullName>NeedsReview</fullName>
                    <label>Needs Review</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Invoiced__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Invoiced</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LocationExecutedDate__c</fullName>
        <label>Location Executed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ProjectType__c</fullName>
        <formula>Project__r.ProjectType__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>ProjectLocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Job Created</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project Location</label>
    <nameField>
        <displayFormat>PL-{0000}</displayFormat>
        <label>Location ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectType__c.object
<CustomObject>
    <description>Project Type defines a collection of Services and sets configuration options for a Project. Project Type is related to Project, Project Type Execution Company, Project Type Service, and Location Assignment.</description>
    <label>Project Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Types</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/classes/BatchProcessLaborInvoiceTest.cls
@isTest
private class BatchProcessLaborInvoiceTest {
    @testSetup
    static void setup() {
        TriggerUtil.skipAllTriggers();

        TestDataUtil.init();
        TestProject tP = TestProject.create('demo')
                         .addAll();
        initTestData(tP.getInstance().Id);
    }

    static void initTestData(String pId) {
        setupProjectLocation(pId);
        setupOpportunity(pId);
    }

    static void setupProjectLocation(String pId) {
        ProjectLocation__c pl = TestProject.getLocations(pId)[0];
        pl.LocationExecutedDate__c = Date.today();
        pl.Invoiced__c = false;
        pl.BillingStatus__c = CONSTANTS.BILLING_STATUS_BILLABLE;        
        update pl;
    }

    static void setupOpportunity(String pId) {
        Opportunity opp = new Opportunity();
        opp.Name = 'demo';
        opp.Project__c = pId;
        opp.ProjectType__c = [SELECT Id FROM ProjectType__c][0].Id;
        opp.StageName = 'Proposal/Price Quote';
        opp.CloseDate = Date.today().addDays(10);
        insert opp;

        List<ProjectAccount__c> accts = [Select id, Opportunity__c from ProjectAccount__c 
            where Project__c = :pId];
        for(ProjectAccount__c a: accts) {
            a.Opportunity__c = opp.Id;
        }
        update accts;
     }

    static List<ApexJobTracker__c> getTrackers() {
        return [SELECT Status__c, Operation__c, Object__c, Response__c from ApexJobTracker__c];
    }

    @isTest
    static void itShouldCreateAnInvoice() {
        // Given
        Project__c p = TestProject.getProjects()[0];
        Date cutoffDate = Date.today().addDays(15);
        List<ApexJobTracker__c> trackers = getTrackers();
        QA.isTrue(trackers.isEmpty(), 'no trackers before test');

        // When
        test.startTest();
        BatchProcessLaborInvoice laborInvoice = new BatchProcessLaborInvoice(cutoffDate);
        Database.executeBatch(laborInvoice);
        test.stopTest();

        // Then
        trackers = getTrackers();
        QA.isTrue(!trackers.isEmpty(), 'tracker is created');
        QA.EQ(1, trackers.size(), 'one tracker created.');
        ApexJobTracker__c tracker = trackers[0];
        QA.EQ('Success', tracker.Status__c, 'should succeed:' + tracker.Response__c);
        QA.EQ('ProjectLocation', tracker.Object__c, 'project location');
        QA.EQ('Create Labor Invoice', tracker.Operation__c, 'Create Labor Invoice');
    }

    @isTest static void itShouldGenDataMessage() {
        // GIVEN
        Id oId = null;
        String msg = 'test';

        // WHEN
        test.startTest();
        Map<String, Object> result = BatchProcessLaborInvoice.genDataMessage(oId, msg);
        test.stopTest();

        // THEN
        QA.EQ(oId, result.get('id'), 'null id');
        QA.EQ(msg, result.get('message'), 'msg is test');
    }
}