src_old/objects/ApexJobTracker__c.object
<CustomObject>
    <description>This will keep track of all the batch jobs.</description>
    <fields>
        <fullName>BatchProcessId__c</fullName>
        <label>Batch Process Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EndDateTime__c</fullName>
        <label>End Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Id1__c</fullName>
        <label>Id1</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Id2__c</fullName>
        <label>Id2</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Id3__c</fullName>
        <label>Id3</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IsFailureNotified__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if batch retry failure notification alert is sent</description>
        <label>Is Failure Notified?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsLongRunning__c</fullName>
        <formula>AND((Now()- StartDateTime__c)*24*60 &gt; 0, TEXT(Status__c) &lt;&gt; &apos;Success&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>IsLongRunning</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NumberofTries__c</fullName>
        <label>Number of Tries</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Operation__c</fullName>
        <label>Operation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Apply PB Credit</fullName>
                </value>
                <value>
                    <fullName>Cancel Job</fullName>
                </value>
                <value>
                    <fullName>Cancel Project</fullName>
                </value>
                <value>
                    <fullName>Cancel ProjectLocation</fullName>
                </value>
                <value>
                    <fullName>Cancel ProjectService</fullName>
                </value>
                <value>
                    <fullName>Close Project</fullName>
                </value>
                <value>
                    <fullName>Create Attempt</fullName>
                </value>
                <value>
                    <fullName>Create Job Materials</fullName>
                </value>
                <value>
                    <fullName>Create Jobs</fullName>
                </value>
                <value>
                    <fullName>Create Labor Invoice</fullName>
                </value>
                <value>
                    <fullName>Create Product Invoice</fullName>
                </value>
                <value>
                    <fullName>Create SalesTax Invoice</fullName>
                </value>
                <value>
                    <fullName>Delete AllProjectJobs</fullName>
                </value>
                <value>
                    <fullName>Delete Job</fullName>
                </value>
                <value>
                    <fullName>Delete Project</fullName>
                </value>
                <value>
                    <fullName>Delete ProjectLocation</fullName>
                </value>
                <value>
                    <fullName>Delete ProjectService</fullName>
                </value>
                <value>
                    <fullName>Import JobAttemptWorkers</fullName>
                </value>
                <value>
                    <fullName>Import Jobs</fullName>
                </value>
                <value>
                    <fullName>Import ProjectLocations</fullName>
                </value>
                <value>
                    <fullName>Launch Project</fullName>
                </value>
                <value>
                    <fullName>Schedule ProjectLocation</fullName>
                </value>
                <value>
                    <fullName>Schedule ProjectService</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Parameters__c</fullName>
        <description>This will hold the job specific parameters for the apex job execution.</description>
        <inlineHelpText>This will hold the job specific parameters for the apex job execution.</inlineHelpText>
        <label>Parameters</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Apex Jobs Tracker</relationshipLabel>
        <relationshipName>Apex_Jobs_Tracker</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartDateTime__c</fullName>
        <label>Start Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failure</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Apex Job Tracker</label>
    <nameField>
        <displayFormat>AJT-{000000000}</displayFormat>
        <label>Apex Job Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Jobs Tracker</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/objects/OrgCustomSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Generic org settings will be stored here</description>
    <fields>
        <fullName>BatchRetryAlertEmails__c</fullName>
        <label>BatchRetryAlertEmails</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NumberOfBatchRetries__c</fullName>
        <label>Number Of Batch Retries</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Org Custom Settings</label>
</CustomObject>

src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <fields>
        <fullName>ApexJobName__c</fullName>
        <description>A field that indicates the apex job name of the Project.</description>
        <inlineHelpText>The apex job name of the project</inlineHelpText>
        <label>ApexJobName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BatchProcessId__c</fullName>
        <description>A field that indicates the ID number of the Batch Process for the Project.</description>
        <inlineHelpText>The ID number for the batch process.</inlineHelpText>
        <label>BatchProcessId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BookBudgetedOnly__c</fullName>
        <defaultValue>false</defaultValue>
        <description>A checkbox that indicates whether the Project was book budgeted only.</description>
        <inlineHelpText>If selected, the project was book budgeted only.</inlineHelpText>
        <label>BookBudgetedOnly</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BudgetedLocationsCount__c</fullName>
        <description>An entry field that indicates the number of budgeted locations for the Project.</description>
        <inlineHelpText>Expected number of locations</inlineHelpText>
        <label>Budgeted Locations Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>An entry field that indicates the end date of the Project.</description>
        <inlineHelpText>The last date available to complete execution</inlineHelpText>
        <label>Project End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LocationTotalCount__c</fullName>
        <description>A field that indicates the count of the locations added to the project.</description>
        <inlineHelpText>The count of the locations added to the project.</inlineHelpText>
        <label>Actual Location Count</label>
        <summaryFilterItems>
            <field>ProjectLocation__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Canceled</value>
        </summaryFilterItems>
        <summaryForeignKey>ProjectLocation__c.Project__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>ProjectNumber__c</fullName>
        <displayFormat>{YY}{MM}{DD}{000000}</displayFormat>
        <inlineHelpText>this is help text in design</inlineHelpText>
        <label>Project Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>ProjectType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Type</label>
        <referenceTo>ProjectType__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>An entry field that indicates the start date of the Project.</description>
        <inlineHelpText>The date available to start execution</inlineHelpText>
        <label>Project Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planning</fullName>
                    <default>true</default>
                    <label>Planning</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Launched</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ended</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ProjectType__c.object
<CustomObject>
    <description>Project Type defines a collection of Services and sets configuration options for a Project. Project Type is related to Project, Project Type Execution Company, Project Type Service, and Location Assignment.</description>
    <label>Project Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Types</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/BatchRetryHandler.cls
global class BatchRetryHandler {

    global BatchRetryHandler() {}
    
    global void retry(){
        
        OrgCustomSettings__c settings = OrgCustomSettings__c.getInstance('Setting');
        Integer maxRetries = (settings == null || settings.NumberOfBatchRetries__c == null) ? 3 : Integer.valueOf(settings.NumberOfBatchRetries__c);
        
        List<ApexJobTracker__c> ajts = [Select Id, Id1__c, Id2__c, Id3__c, Operation__c, Parameters__c,NumberOfTries__c, IsFailureNotified__c, Project__c, BatchProcessId__c, StartDateTime__c, EndDateTime__c
                                        FROM ApexJobTracker__c 
                                        WHERE IsLongRunning__c = true AND IsFailureNotified__c != true LIMIT 20]; 
        try {
            for (ApexJobTracker__c ajt: ajts) {
                if(ajt.NumberOfTries__c != null && ajt.NumberOfTries__c > maxRetries){
                    notifyFailure(ajt);    
                    continue;
                }
                if(ajt.Project__c != null){
                    List<Project__c> batchedProject = [SELECT BatchProcessId__c FROM Project__c WHERE ID = :ajt.Project__c];
                    if(batchedProject.size() > 0 && batchedProject[0].BatchProcessId__c != null){
                        List<AsyncApexJob> a = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed, TotalJobItems, CreatedBy.Email FROM AsyncApexJob WHERE Id = :batchedProject[0].BatchProcessId__c];     
                        if(a.size()>0 && (a[0].Status == 'Holding' || a[0].Status == 'Queued' || a[0].Status == 'Preparing' || a[0].Status == 'Processing')){
                            continue;
                        }
                    }
                }
                
                if(ajt.Operation__c == 'Create Jobs'){
                    RetryCreateJobs(ajt);
                }
                else if(ajt.Operation__c == 'Create Job Materials'){
                    RetryCreateJobMaterials(ajt);
                }
                else{
                    RetryBatchJobs(ajt);
                }
            }    
        }
        catch(Exception e) {
            String messageSubject = 'Batch retry job failed';
            String messageBody = 'BatchRetryHandler.retry() failed: ' + e.getMessage();           
            String[] toAddresses = AppUtil.getAppSetting('DevAlertEmails').split(',');
            EmailHelper.SendEmail(toAddresses,messageSubject,messageBody,true);            
        }
    }
    
    public void RetryBatchJobs(ApexJobTracker__c ajt){
        Id[] ids = new Id[] {};
		String allIds = (ajt.Id1__c == null ? '' : ajt.Id1__c) + ',' + (ajt.Id2__c == null ? '' : ajt.Id2__c) + ',' + (ajt.Id3__c == null ? '' : ajt.Id3__c);
		for (string s: allIds.split(',')) {
            if(s!=''){
            	ids.add(Id.valueOf(s));    
            }
			
        }
        BatchProcessApexJobs batch = new BatchProcessApexJobs(ids, ajt);
        Database.ExecuteBatch(batch, JobActionsHelper.JOB_BATCH_SIZE);                    
    }
    
    public void RetryCreateJobs(ApexJobTracker__c ajt){
        Project__c project = [SELECT Id, Name, StartDate__c, EndDate__c, Status__c, ProjectType__c, 
                              ProjectType__r.Name, BudgetedLocationsCount__c, LocationTotalCount__c, 
                              BookBudgetedOnly__c, ApexJobName__c, BatchProcessId__c, RecordTypeId 
                              FROM Project__c WHERE ID = :ajt.Project__c];
        
        ajt.StartDateTime__c = DateTime.Now();
        ajt.NumberOfTries__c = ajt.NumberofTries__c == null ? 1 : (ajt.NumberofTries__c + 1);
        update ajt;
        
        ProjectScheduler batch = new ProjectScheduler(project);
        String batchProcessId = Database.ExecuteBatch(batch, 250);
        
		ProjectActionsHelper.LockProject(project,'Create Jobs', batchProcessId);        

        TriggerUtil.skipProjectTrigger = true;
        update project; 
        
    }
    
    public void RetryCreateJobMaterials(ApexJobTracker__c ajt){
        Project__c project = [SELECT Id, Name, StartDate__c, EndDate__c, Status__c, ProjectType__c, ProjectType__r.Name, BudgetedLocationsCount__c, LocationTotalCount__c, BookBudgetedOnly__c FROM Project__c WHERE ID = :ajt.Project__c];
        
        ajt.StartDateTime__c = DateTime.Now();
        ajt.NumberOfTries__c = ajt.NumberofTries__c == null ? 1 : (ajt.NumberofTries__c + 1);
        update ajt;
        
        JobUpdateBatcher batch = new JobUpdateBatcher(new List<Project__c>{ project });
        project.BatchProcessId__c = Database.ExecuteBatch(batch, JobUpdatesHelper.getJobUpdateBatchHandlerBatchSize(project));
        
        ProjectActionsHelper.LockProject(project, 'Create Jobs', '');
        
        TriggerUtil.skipProjectTrigger = true;
        update project; 
    }
    
    public void notifyFailure(ApexJobTracker__c ajt){
        if(ajt.IsFailureNotified__c == true) return;
        
        
        String messageSubject = 'Batch retry failed for ' + ajt.Operation__c;
        String messageBody = 'Apex Job Tracker Id: ' + ajt.Id;
        if(ajt.Project__c != null){
            Project__c p = [SELECT Id, Name, ProjectNumber__c FROM Project__c WHERE ID = :ajt.Project__c];
            messageBody += '\r\n\r\nProject: ' + p.Name + '\r\n\r\n Project Number: ' + p.ProjectNumber__c;
        }
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        String[] toAddresses = AppUtil.getAppSetting('DevAlertEmails').split(',');
        OrgCustomSettings__c settings = OrgCustomSettings__c.getInstance('Setting');
        if(settings.BatchRetryAlertEmails__c == null){
            toAddresses = AppUtil.getAppSetting('DevAlertEmails').split(',');
        }
        else{
            toAddresses = settings.BatchRetryAlertEmails__c.split(',');
        }
        
		try{
        	EmailHelper.SendEmail(toAddresses,messageSubject,messageBody);
        }
        catch(Exception ex){
            system.debug('BatchRetry failed to send email. Exception details:' + ex.getMessage());
        }        
        finally{
			ajt.IsFailureNotified__c = true;
            update ajt;                
        }
        
    }
}