src_old/objects/ApexJobTracker__c.object
<CustomObject>
    <description>This will keep track of all the batch jobs.</description>
    <fields>
        <fullName>BatchProcessId__c</fullName>
        <label>Batch Process Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EndDateTime__c</fullName>
        <label>End Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Id1__c</fullName>
        <label>Id1</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Id2__c</fullName>
        <label>Id2</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Id3__c</fullName>
        <label>Id3</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>NumberofTries__c</fullName>
        <label>Number of Tries</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>ProjectService</fullName>
                </value>
                <value>
                    <fullName>ProjectLocation</fullName>
                </value>
                <value>
                    <fullName>Job</fullName>
                </value>
                <value>
                    <fullName>JobAttemptWorker</fullName>
                </value>
                <value>
                    <fullName>ProjectInvoice</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Operation__c</fullName>
        <label>Operation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Apply PB Credit</fullName>
                </value>
                <value>
                    <fullName>Cancel Job</fullName>
                </value>
                <value>
                    <fullName>Cancel Project</fullName>
                </value>
                <value>
                    <fullName>Cancel ProjectLocation</fullName>
                </value>
                <value>
                    <fullName>Cancel ProjectService</fullName>
                </value>
                <value>
                    <fullName>Close Project</fullName>
                </value>
                <value>
                    <fullName>Create Attempt</fullName>
                </value>
                <value>
                    <fullName>Create Job Materials</fullName>
                </value>
                <value>
                    <fullName>Create Jobs</fullName>
                </value>
                <value>
                    <fullName>Create Labor Invoice</fullName>
                </value>
                <value>
                    <fullName>Create Product Invoice</fullName>
                </value>
                <value>
                    <fullName>Create SalesTax Invoice</fullName>
                </value>
                <value>
                    <fullName>Delete AllProjectJobs</fullName>
                </value>
                <value>
                    <fullName>Delete Job</fullName>
                </value>
                <value>
                    <fullName>Delete Project</fullName>
                </value>
                <value>
                    <fullName>Delete ProjectLocation</fullName>
                </value>
                <value>
                    <fullName>Delete ProjectService</fullName>
                </value>
                <value>
                    <fullName>Import JobAttemptWorkers</fullName>
                </value>
                <value>
                    <fullName>Import Jobs</fullName>
                </value>
                <value>
                    <fullName>Import ProjectLocations</fullName>
                </value>
                <value>
                    <fullName>Launch Project</fullName>
                </value>
                <value>
                    <fullName>Schedule ProjectLocation</fullName>
                </value>
                <value>
                    <fullName>Schedule ProjectService</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Parameters__c</fullName>
        <description>This will hold the job specific parameters for the apex job execution.</description>
        <inlineHelpText>This will hold the job specific parameters for the apex job execution.</inlineHelpText>
        <label>Parameters</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Apex Jobs Tracker</relationshipLabel>
        <relationshipName>Apex_Jobs_Tracker</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartDateTime__c</fullName>
        <label>Start Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failure</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Apex Job Tracker</label>
    <nameField>
        <displayFormat>AJT-{000000000}</displayFormat>
        <label>Apex Job Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Jobs Tracker</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/objects/Job__c.object
<CustomObject>
    <description>Job defines the body of work to be performed at a Location and all of the dates related to the Job performance. A Job is related to a Project, Project Service, Project Location, Job Material, Contact, Exception, and Job Attempt.</description>
    <fields>
        <fullName>ActiveJobAttempt__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field that displays Job Attempts</description>
        <label>Active Job Attempt</label>
        <referenceTo>JobAttempt__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ArchiveStatus__c</fullName>
        <description>The field that indicates the Archive Status of the Job.</description>
        <inlineHelpText>The archive status of the job</inlineHelpText>
        <label>Archive Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Archived</fullName>
                </value>
                <value>
                    <fullName>Queued</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ProjectLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field that indicates the Location of a Project.</description>
        <inlineHelpText>The location of the project</inlineHelpText>
        <label>Project Location</label>
        <referenceTo>ProjectLocation__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectService__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field that indicates the Project Service.</description>
        <inlineHelpText>The project service number</inlineHelpText>
        <label>Project Service</label>
        <referenceTo>ProjectService__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field that indicates the name of the Project to which a Job belongs.</description>
        <inlineHelpText>The name of the project for this job</inlineHelpText>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Job</label>
    <nameField>
        <displayFormat>JOB-{000000000}</displayFormat>
        <label>Job ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <fields>
        <fullName>ApexJobName__c</fullName>
        <description>A field that indicates the apex job name of the Project.</description>
        <inlineHelpText>The apex job name of the project</inlineHelpText>
        <label>ApexJobName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ApprovalDate__c</fullName>
        <description>A field that indicates the date and time that the Project was approved.</description>
        <inlineHelpText>The date and time that the project was approved.</inlineHelpText>
        <label>Approval Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ArchiveStatus__c</fullName>
        <label>Archive Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BatchProcessId__c</fullName>
        <description>A field that indicates the ID number of the Batch Process for the Project.</description>
        <inlineHelpText>The ID number for the batch process.</inlineHelpText>
        <label>BatchProcessId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planning</fullName>
                    <default>true</default>
                    <label>Planning</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Launched</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ended</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ProjectLocation__c.object
<CustomObject>
    <description>Project Location relates a Location to a Project. Project Location is related Project, Job, and Location.</description>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>ProjectLocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Job Created</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project Location</label>
    <nameField>
        <displayFormat>PL-{0000}</displayFormat>
        <label>Location ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectService__c.object
<CustomObject>
    <description>Project Service relates a Service to a Project and is a container used to define the instance of a Service for a specific Project. Project Service is related to Project, Job, Project Service Attribute, Project Service Certification, Project Service Equipment, Project Service Material, Project Service Question, Project Service Target, and Service.</description>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>ProjectServices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Executed</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project Service</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/BatchProcessApexJobs.cls
global class BatchProcessApexJobs implements Database.Batchable<sObject>, Database.Stateful {
    
    Id[] ids;
    public ApexJobTracker__c ajt {get; set;}

    String objectname;
    String operation;
    
    global BatchProcessApexJobs (Id[] ids, ApexJobTracker__c pajt) {
    
        this.ajt = [Select Id, Name, BatchProcessId__c, Object__c, Operation__c, Project__c, 
            StartDateTime__c, EndDateTime__c, Status__c, NumberofTries__c, Id1__c, Id2__c, Id3__c,
            Parameters__c FROM ApexJobTracker__c WHERE Id = :pajt.Id];    
        
        if (ids.size() == 0) return;
        this.ids = ids;
        this.operation = ajt.operation__c;
        
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
    
        system.debug('BatchProcessApexJobs Started');
        UpdateApexJobTracker('In Progress', DateTime.Now(), null, true);
        
        this.objectname = String.Valueof(ids[0].getSObjectType());
        
        if (String.Valueof(ids[0].getSObjectType()).containsignorecase('project__c'))       
        {
            return Database.getQueryLocator([SELECT Id, Project__c, ProjectService__c, ProjectLocation__c, Project__r.ApprovalDate__c FROM Job__c WHERE Project__c IN :ids]);
        }
        else if (String.Valueof(ids[0].getSObjectType()).containsignorecase('job__c'))       
        {
            return Database.getQueryLocator([SELECT Id, Project__c, ProjectService__c, ProjectLocation__c, Project__r.ApprovalDate__c  FROM Job__c WHERE Id IN :ids]);        
        } 
        else if (String.Valueof(ids[0].getSObjectType()).containsignorecase('projectservice__c'))       
        {
            return Database.getQueryLocator([SELECT Id, Project__c, ProjectService__c, ProjectLocation__c, Project__r.ApprovalDate__c  FROM Job__c WHERE ProjectService__c IN :ids]);        
        } 
        else if (String.Valueof(ids[0].getSObjectType()).containsignorecase('projectlocation__c'))       
        {
            return Database.getQueryLocator([SELECT Id, Project__c, ProjectService__c, ProjectLocation__c, Project__r.ApprovalDate__c  FROM Job__c WHERE ProjectLocation__c IN :ids]);        
        } 
        
        return null;   
    }
   
    global void execute(Database.BatchableContext BC, List<Job__c> scope) {
    
        Id[] jobIds = new Id[]{};
        for (Job__c job: scope)
        {
            jobIds.add(job.Id);
        }

        if (operation.containsignorecase('delete'))
        {
            JobActionsHelper.deletejobs(jobIds, true);        
        }
        else if (operation.containsignorecase('cancel'))
        {
            JobActionsHelper.canceljobs(jobIds, '','', true);                
        }
        else if (operation.containsignorecase('close'))
        {
            JobActionsHelper.closejobs(jobIds, true);                
        }
        else if (operation.containsignorecase('launch'))
        {
            //filter only 
            list<job__c> jobList = [select id from job__C where ActiveJobAttempt__c = null and id in: jobIds];
            Set<id> temp = (new Map<Id,job__C>(jobList)).keySet();
            jobIds = new list<id>(temp);
            JobActionsHelper.createAttempts(jobIds, null, '', true);                
        }
        else if (operation.containsignorecase('schedule projectservice'))
        {
            JobActionsHelper.resetScheduledDate(jobIds);
        }
        else if (operation.containsignorecase('schedule'))
        {
            Date scheduleDate = Date.parse(ajt.Parameters__c);
            JobActionsHelper.setScheduledDate(jobIds, scheduleDate);
        }
   }
    
    global void finish(Database.BatchableContext BC) {
    
        Savepoint sp = Database.setSavepoint(); 
        try
        {
            TriggerUtil.SkipAllTriggers();    
            
            AsyncApexJob a = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed, TotalJobItems, CreatedBy.Email FROM AsyncApexJob WHERE Id = :BC.getJobId()];    
            
            if (a.NumberOfErrors > 0)
            {
                UpdateApexJobTracker('Failure',null, null, true);
            }         
            else   
                HandleBatchFinish(operation);    
        }
        catch(Exception e)
        {
            Database.rollback(sp);
            UpdateApexJobTracker('Failure',null, null, true);              
            
            //Test
            throw e;
        }
   }   
   
   
   private void HandleBatchFinish(string operation)
   {
   
       Set<Id> projectIdsforUpdate = new Set<Id>();
   
        if (operation.containsignorecase('delete projectlocation'))
        {
            ProjectLocationActionsHelper.DeleteProjectLocationSansJobs(ids);     
            UpdateApexJobTracker('Success',null, DateTime.Now(), false);
            projectIdsforUpdate.add(ajt.Project__c);
        }
        else if (operation.containsignorecase('schedule projectlocation'))
        {
            UpdateApexJobTracker('Success',null, DateTime.Now(), false);
            projectIdsforUpdate.add(ajt.Project__c);
        }
        else if (operation.containsignorecase('schedule projectservice'))
        {
            UpdateApexJobTracker('Success',null, DateTime.Now(), false);
            projectIdsforUpdate.add(ajt.Project__c);
        }
        else if (operation.containsignorecase('delete projectservice'))
        {
            ProjectServiceActionsHelper.DeleteProjectServiceSansJobs(ids);     
            UpdateApexJobTracker('Success',null, DateTime.Now(), false);
            projectIdsforUpdate.add(ajt.Project__c);
        }
        else if (operation.containsignorecase('delete project'))
        {
            ProjectActionsHelper.DeleteProjectSansJobs(ids[0]);     
            UpdateApexJobTracker('Success',null, DateTime.Now(), false);
            return;
        }
        else if (operation.containsignorecase('delete job') || operation.containsignorecase('Delete AllProjectJobs'))
        {
            UpdateApexJobTracker('Success',null, DateTime.Now(), false);
            projectIdsforUpdate.add(ajt.Project__c);
        }
        else if (operation.containsignorecase('cancel projectservice'))
        {
            UpdateApexJobTracker('Success',null, DateTime.Now(), false);
            projectIdsforUpdate.add(ajt.Project__c);            
        }
        else if (operation.containsignorecase('cancel projectlocation'))
        {
            ProjectLocationActionsHelper.CancelProjectLocationSansJobs(ids,'','');     
            UpdateApexJobTracker('Success',null, DateTime.Now(), false);
            projectIdsforUpdate.add(ajt.Project__c);            
        }
        else if (operation.containsignorecase('cancel job'))
        {
            UpdateApexJobTracker('Success',null, DateTime.Now(), false);
            projectIdsforUpdate.add(ajt.Project__c);
        }
        else if (operation.containsignorecase('cancel project'))
        {
            string cancelreason = '';
            string cancelcomments = '';
            if (!String.IsBlank(ajt.Parameters__c))
            {
                string[] parameters = ajt.Parameters__c.split('@@@');
                for(string parameter : parameters)
                {
                    string[] keyvalue = parameter.split('::');
                    if (keyvalue.size() == 2 && keyvalue[0].toLowerCase() =='cancelreason')
                    {
                        cancelreason = keyvalue[1];
                    }
                    if (keyvalue.size() == 2 && keyvalue[0].toLowerCase() =='cancelcomments')
                    {
                        cancelcomments = keyvalue[1];
                    }
                    
                }
            }
             
            UpdateApexJobTracker('Success',null, DateTime.Now(), false);
            projectIdsforUpdate.add(ajt.Project__c);            
        }
        else if (operation.containsignorecase('close project'))
        {
            ProjectActionsHelper.CloseProjectsSansJobs(ids);     
            UpdateApexJobTracker('Success',null, DateTime.Now(), false);
            for (Id id : ids)
            {
                projectIdsforUpdate.add(id);
            }
            
        }
        else if (operation.containsignorecase('launch project'))
        {
            ProjectActionsHelper.LaunchProjectsSansJobs(ids);     
            UpdateApexJobTracker('Success',null, DateTime.Now(), false);
            for (Id id : ids)
            {
                projectIdsforUpdate.add(id);
            }
        }
       
       
        List<Project__c> projects = [Select Id, Status__c, ArchiveStatus__c, ApexJobName__c, BatchProcessId__c, RecordTypeId
                                     from Project__c where Id in :projectIdsforUpdate];
        for (Project__c project :projects)
        {
            //Temporary code to set the archive status to Complete
            //This needs to be rewritten when we start archiving the 
            //whole project
            //Currently archiving is piggy backing on the delete all jobs process
            if (operation.containsignorecase('Delete AllProjectJobs') 
               && project.Status__c == CONSTANTS.PROJECT_STATUS_CLOSED
               && project.ArchiveStatus__c == CONSTANTS.ARCHIVE_STATUS_ARCHIVED)
            {
                project.ArchiveStatus__c = CONSTANTS.ARCHIVE_STATUS_COMPLETE;
            }    
            
			ProjectActionsHelper.UnlockProject(project);
        }
        update projects;

        system.debug('SetJobOpenBatcher end');
   
   }
   
   private void UpdateApexJobTracker(string status, DateTime starttime, DateTime endtime, boolean incrementtries)
   {
   
       //getting ajt again because update throws an error if the ajt was updated in the meantime
       
       this.ajt = [Select Id, Name, BatchProcessId__c, Object__c, Operation__c, Project__c, 
            StartDateTime__c, EndDateTime__c, Status__c, NumberofTries__c, Id1__c, Id2__c, Id3__c,
            Parameters__c FROM ApexJobTracker__c WHERE Id = :ajt.Id];         
       
       ajt.Status__c = status;
       if (starttime != null) ajt.StartDateTime__c = starttime;
       if (endtime != null) ajt.EndDateTime__c = endtime;
       if (incrementtries) {
           if(ajt.NumberofTries__c == null)
                ajt.NumberofTries__c = 0;
           else
                ajt.NumberOfTries__c++;
       }
       update ajt;     
   
   } 
    
}