src_old/objects/ApexJobTracker__c.object
<CustomObject>
    <description>This will keep track of all the batch jobs.</description>
    <fields>
        <fullName>AppClassName__c</fullName>
        <description>Application Class Name</description>
        <label>App Class Name</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BatchProcessId__c</fullName>
        <label>Batch Process Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EndDateTime__c</fullName>
        <label>End Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Id1__c</fullName>
        <label>Id1</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Id2__c</fullName>
        <label>Id2</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Id3__c</fullName>
        <label>Id3</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IsFailureNotified__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if batch retry failure notification alert is sent</description>
        <label>Is Failure Notified?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NumberofTries__c</fullName>
        <label>Number of Tries</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>ProjectService</fullName>
                </value>
                <value>
                    <fullName>ProjectLocation</fullName>
                </value>
                <value>
                    <fullName>Job</fullName>
                </value>
                <value>
                    <fullName>JobAttemptWorker</fullName>
                </value>
                <value>
                    <fullName>ProjectInvoice</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Operation__c</fullName>
        <label>Operation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Apply PB Credit</fullName>
                </value>
                <value>
                    <fullName>Cancel Job</fullName>
                </value>
                <value>
                    <fullName>Cancel Project</fullName>
                </value>
                <value>
                    <fullName>Cancel ProjectLocation</fullName>
                </value>
                <value>
                    <fullName>Cancel ProjectService</fullName>
                </value>
                <value>
                    <fullName>Close Project</fullName>
                </value>
                <value>
                    <fullName>Create Attempt</fullName>
                </value>
                <value>
                    <fullName>Create Job Materials</fullName>
                </value>
                <value>
                    <fullName>Create Jobs</fullName>
                </value>
                <value>
                    <fullName>Create Labor Invoice</fullName>
                </value>
                <value>
                    <fullName>Create Product Invoice</fullName>
                </value>
                <value>
                    <fullName>Create SalesTax Invoice</fullName>
                </value>
                <value>
                    <fullName>Delete AllProjectJobs</fullName>
                </value>
                <value>
                    <fullName>Delete Job</fullName>
                </value>
                <value>
                    <fullName>Delete Project</fullName>
                </value>
                <value>
                    <fullName>Delete ProjectLocation</fullName>
                </value>
                <value>
                    <fullName>Delete ProjectService</fullName>
                </value>
                <value>
                    <fullName>Import JobAttemptWorkers</fullName>
                </value>
                <value>
                    <fullName>Import Jobs</fullName>
                </value>
                <value>
                    <fullName>Import ProjectLocations</fullName>
                </value>
                <value>
                    <fullName>Launch Project</fullName>
                </value>
                <value>
                    <fullName>Schedule ProjectLocation</fullName>
                </value>
                <value>
                    <fullName>Schedule ProjectService</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Parameters__c</fullName>
        <description>This will hold the job specific parameters for the apex job execution.</description>
        <inlineHelpText>This will hold the job specific parameters for the apex job execution.</inlineHelpText>
        <label>Parameters</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ParentId__c</fullName>
        <description>Attachment Parent ID</description>
        <label>Parent Id</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Apex Jobs Tracker</relationshipLabel>
        <relationshipName>Apex_Jobs_Tracker</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <description>tracker execution response</description>
        <label>Response</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>StartDateTime__c</fullName>
        <label>Start Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failure</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Apex Job Tracker</label>
    <nameField>
        <displayFormat>AJT-{000000000}</displayFormat>
        <label>Apex Job Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Jobs Tracker</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <fields>
        <fullName>BatchProcessId__c</fullName>
        <description>A field that indicates the ID number of the Batch Process for the Project.</description>
        <inlineHelpText>The ID number for the batch process.</inlineHelpText>
        <label>BatchProcessId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planning</fullName>
                    <default>true</default>
                    <label>Planning</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Launched</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ended</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/ApexJobTracker.cls
global without sharing class ApexJobTracker {
    static String AppNameSpace {get; set;}
    static {
        AppNameSpace = CONSTANTS.CURRENTNAMESPACE;
    }
    
    private ApexJobTracker__c record;
    public enum TrackerOperation {
        None,
            Delete_Project,
            Delete_ProjectService,
            Delete_ProjectLocation,
            Delete_Job,
            Cancel_Project,
            Cancel_ProjectService,
            Cancel_ProjectLocation,
            Import_ProjectLocations,
            Cancel_Job,
            Close_Project,
            Launch_Project,
            Create_Jobs,
            Import_Jobs,
            Import_JobAttemptWorkers,
            Create_Job_Materials,
            Schedule_ProjectLocation,
            Create_Attempt,
            Schedule_ProjectService,
            Delete_AllProjectJobs,
            Create_Labor_Invoice,
            Create_SalesTax_Invoice,
            Create_Product_Invoice,
            Apply_PB_Credit
            }
    public enum TrackerTarget {Project, ProjectService, ProjectLocation, Job, JobAttemptWorker, ProjectInvoice}
    public enum TrackerStatus {Initial, In_Progress, Success, Failure}
    
    public String TrackerId {get {return record.Id;}}
    public String ParentId {get {return record.ParentId__c;}}
    public Datetime StartTime {get {return record.StartDateTime__c;}}
    public Datetime EndTime {get {return record.EndDateTime__c;}}
    public String TargetId {get{return record.Object__c;}}
    public Double TryCount {get {return record.NumberofTries__c;}}
    public String BatchProcessId {get {return record.BatchProcessId__c;}}
    public String ClassName {get{return record.AppClassName__c;}}
    
    public String Id1 {get{return record.Id1__c;}}
    public String Id2 {get{return record.Id2__c;}}
    public String Id3 {get{return record.Id3__c;}}
    public String Parameters {get{return record.Parameters__c;}}
    public String ProjectId {get{return record.Project__c;}}
    public Boolean failureNotified {get {return record.IsFailureNotified__c;}}
    public String Response {get {return record.Response__c;}}
    
    public TrackerOperation Operation {
        get
        {
            switch on record.Operation__c {
                when 'Delete Project' {
                    return TrackerOperation.Delete_Project;
                }
                when 'Delete ProjectService' {
                    return TrackerOperation.Delete_ProjectService;
                }
                when 'Delete ProjectLocation' {
                    return TrackerOperation.Delete_ProjectLocation;
                }
                when 'Delete Job' {
                    return TrackerOperation.Delete_Job;
                }
                when 'Cancel Project' {
                    return TrackerOperation.Cancel_Project;
                }
                when 'Cancel ProjectService' {
                    return TrackerOperation.Cancel_ProjectService;
                }
                when 'Cancel ProjectLocation' {
                    return TrackerOperation.Cancel_ProjectLocation;
                }
                when 'Import ProjectLocations' {
                    return TrackerOperation.Import_ProjectLocations;
                }
                when 'Cancel Job' {
                    return TrackerOperation.Cancel_Job;
                }
                when 'Close Project' {
                    return TrackerOperation.Close_Project;
                }
                when 'Launch Project' {
                    return TrackerOperation.Launch_Project;
                }
                when 'Create Jobs' {
                    return TrackerOperation.Create_Jobs;
                }
                when 'Import Jobs' {
                    return TrackerOperation.Import_Jobs;
                }
                when 'Import JobAttemptWorkers' {
                    return TrackerOperation.Import_JobAttemptWorkers;
                }
                when 'Create Job Materials' {
                    return TrackerOperation.Create_Job_Materials;
                }
                when 'Schedule ProjectLocation' {
                    return TrackerOperation.Schedule_ProjectLocation;
                }
                when 'Create Attempt' {
                    return TrackerOperation.Create_Attempt;
                }
                when 'Schedule ProjectService' {
                    return TrackerOperation.Schedule_ProjectService;
                }
                when 'Delete AllProjectJobs' {
                    return TrackerOperation.Delete_AllProjectJobs;
                }
                when 'Create Labor Invoice' {
                    return TrackerOperation.Create_Labor_Invoice;
                }
                when 'Create SalesTax Invoice' {
                    return TrackerOperation.Create_SalesTax_Invoice;
                }
                when 'Create Product Invoice' {
                    return TrackerOperation.Create_Product_Invoice;
                }
                when 'Apply PB Credit' {
                    return TrackerOperation.Apply_PB_Credit;
                }
            }
            return TrackerOperation.None;
        }
    }
    
    
    public TrackerStatus Status {
        get{
            TrackerStatus value = TrackerStatus.Initial;
            switch on record.Status__c {
                when 'New' {
                    value = TrackerStatus.Initial;
                }
                when 'In Progress' {
                    value = TrackerStatus.In_Progress;
                }
                when 'Success' {
                    value = TrackerStatus.Success;
                }
                when 'Failure' {
                    value = TrackerStatus.Failure;
                }
            }
            return value;
        }
    }
    
    public Integer ElipsedTime {
        get {
            if (record.StartDateTime__c != null && record.EndDateTime__c != null) {
                return
                    record.EndDateTime__c.millisecond() - record.StartDateTime__c.millisecond();
            }
            return -1;
        }
    }
    
    private ApexJobTracker(ApexJobTracker__c record) {
        this.record = record;
    }
    
    public ApexJobTracker(String recordId) {
    }
    
    public ApexJobTracker(String trackerParentId, TrackerTarget enumTarget, TrackerOperation enumOperation) {
    }
    
    public static ApexJobTracker findTracker(List<String> predicates) {
        if (predicates == null || predicates.isEmpty()){
            throw new CustomException('The predicates are required to find the right apex job tracker record.');
        }
        ApexJobTracker__c rec = getTracker(String.join(predicates, ' AND '));
        return new ApexJobTracker(rec);
    }
    
    public static ApexJobTracker getById(String recordId) {
        if (String.isBlank(recordId)) {
            throw new CustomException('The object id is required.');
        }
        ApexJobTracker__c rec = getTracker('Id=\'' +  recordId + '\'');
        return new ApexJobTracker(rec);
    }
    
    private static ApexJobTracker__c getTracker(String clause) {
        List<ApexJobTracker__c> trackers = Database.query(AppUtil.genQuery('ApexJobTracker__c') + ' WHERE ' + clause);
        if (trackers.size() == 0) {
            throw new CustomException('The apex job tracker not found with the clause: ' + clause);
        }
        return trackers[0];
    }
    
    public static ApexJobTracker create(String trackerParentId, TrackerTarget enumTarget, TrackerOperation enumOperation) {
        return new ApexJobTracker(new ApexJobTracker__c(
            Status__c = 'New',
            ParentId__c = trackerParentId,
            Object__c = enumTarget.name().replace('_', ' '),
            Operation__c = enumOperation.name().replace('_', ' ')
        ));
    }
    
    public ApexJobTracker setStatus(TrackerStatus status) {
        String value = '';
        switch on Status {
            when Initial {
                value = 'New';
            }
            when In_Progress {
                value = 'In Progress';
            }
            when Success {
                value = 'Success';
            }
            when Failure {
                value = 'Failure';
            }
        }
        record.Status__c = value;
        return this;
    }
    
    public ApexJobTracker setNotified(boolean notified) {
        record.IsFailureNotified__c = notified;
        return this;
    }
    
    public void retry() {
        if (record.Id == null) {
            throw new CustomException('Apex Job Tracker not identified.');
        }
        if (String.isBlank(record.AppClassName__c)) {
            throw new CustomException('The apex job tracker classname is not specified.');
        }
        try {
            record.StartDateTime__c = Datetime.now(); 
            record.Status__c = 'New';
            executeAppClass();
        } 
        catch(Exception ex) {
            record.Status__c = 'Failure';
            record.response__c = ex.getStackTraceString();
        }
        finally {
            record.NumberofTries__c = 1 + record.NumberofTries__c;
        }
        save();
    }
    
    private void executeAppClass() {
        Type classType = Type.forName(AppNameSpace, record.AppClassName__c);
        IAppClass appInstance = (IAppClass) classType.newInstance();
        appInstance.execute(this.record);
    }
    
    public ApexJobTracker setClassName(String className) {
        record.AppClassName__c = className;
        return this;
    }
    
    public ApexJobTracker setParameters(String arguments) {
        record.Parameters__c = arguments;
        return this;
    }
    
    public ApexJobTracker setId1(String idOne) {
        record.Id1__c = idOne;
        return this;
    }
    
    public ApexJobTracker setProjectId(String projectId) {
        record.Project__c = projectId;
        return this;
    }
    
    public ApexJobTracker setId2(String idTwo) {
        record.Id2__c = idTwo;
        return this;
    }
    
    public ApexJobTracker setId3(String idThree) {
        record.Id3__c = idThree;
        return this;
    }
    
    public ApexJobTracker setResponse(String message) {
        String value = message + '';
        if (value.length() > 131072) {
            value = value.substring(0, 131072);
        }
        record.Response__c = value;
        return this;
    }
    
    public ApexJobTracker end() {
        record.EndDateTime__c = Datetime.now();
        return save();
    }
    
    public ApexJobTracker save() {
        Database.SaveResult result;
        
        if (String.isBlank(record.Id)) {
            record.StartDateTime__c = Datetime.now();
            record.NumberofTries__c = 1;
            result = Database.insert(record);
        } else {
            result = Database.update(record);
        }
        
        if (!result.isSuccess()) {
            throw new CustomException(AppUtil.genSaveResultError(result));
        }
        return this;
    }
    
    public static boolean isCompleted(String trackerParentId, TrackerTarget enumTarget, TrackerOperation enumOperation) {
        String objectId = enumTarget.name().replace('_', ' ');
        String operationId = enumOperation.name().replace('_', ' ');
        List<ApexJobTracker__c> trackers = [
            SELECT Status__c
            FROM ApexJobTracker__c
            WHERE ParentId__c = :trackerParentId AND
            Object__c = :objectId AND
            Operation__c = :operationId];
        if (trackers.isEmpty()) { return true; }
        ApexJobTracker__c tracker = trackers[0];
        return (tracker.Status__c == 'New' || tracker.Status__c == 'In Progress')
            ? false : true;
    }
}