src_old/objects/AppLocker__c.object
<CustomObject>
    <description>application locker</description>
    <fields>
        <fullName>RequestorId__c</fullName>
        <label>Requestor</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StartTime__c</fullName>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>token__c</fullName>
        <label>request token</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>AppLocker</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>AppLocker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AppLockers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/objects/AppLog__c.object
<CustomObject>
    <description>app log</description>
    <fields>
        <fullName>Message__c</fullName>
        <description>a log message that could be short description of the logging meaning</description>
        <label>Message</label>
        <length>5120</length>
        <type>LongTextArea</type>
    </fields>
    <label>Application Log</label>
    <nameField>
        <displayFormat>AL-{0000000000}</displayFormat>
        <label>Application Log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/objects/Datasource__c.object
<CustomObject>
    <description>Data source for import data defintion</description>
    <label>Datasource</label>
    <nameField>
        <label>Datasource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Datasources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/objects/ImportRequestQueueItem__c.object
<CustomObject>
    <description>Import request queue item</description>
    <fields>
        <fullName>AttachmentId__c</fullName>
        <label>Attachment</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BatchJobAssigned__c</fullName>
        <defaultValue>false</defaultValue>
        <description>the batch job is assigned</description>
        <label>BatchJobAssigned</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BatchJobId__c</fullName>
        <description>batch job id</description>
        <label>BatchJobId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ConsumerAppClassName__c</fullName>
        <formula>Queue__r.Datasource__r.ConsumerApexClass__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ConsumerAppClassName</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Datasource__c</fullName>
        <description>Data Source ID</description>
        <formula>Queue__r.Datasource__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Datasource</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EndTime__c</fullName>
        <label>End time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ErrorAttachment__c</fullName>
        <description>Error attachment ID</description>
        <label>Error Attachment</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ErrorCount__c</fullName>
        <label>ErrorCount</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Parentss</relationshipLabel>
        <relationshipName>Parents_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecordCount__c</fullName>
        <label>RecordCount</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <label>Response</label>
        <length>8192</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>RetryCount__c</fullName>
        <label>Retry Count</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>StartTime__c</fullName>
        <label>Start time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>queue item status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Queued</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SuccessCount__c</fullName>
        <label>SuccessCount</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>ImportRequestQueueItem</label>
    <nameField>
        <displayFormat>I-{00000}</displayFormat>
        <label>ImportRequestQueueItem Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ImportRequestQueueItems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <fields>
        <fullName>BundleServices__c</fullName>
        <defaultValue>true</defaultValue>
        <description>To bundle services with in the project for a specific location</description>
        <label>Bundle Services</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planning</fullName>
                    <default>true</default>
                    <label>Planning</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Launched</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ended</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/classes/ImportRequestQueueitemBatchTest.cls
@isTest
private class ImportRequestQueueitemBatchTest {
	@testSetup
	static void setupTestData() {
		TriggerUtil.skipAllTriggers();
		TestDataUtil.init();
		TestProject.create('demo')
		.addAllWithoutJobAttempts(20);
		setProjectUnbundled();
	}

	static void setProjectUnbundled() {
		String pid = TestProject.getProjects()[0].Id;
		Project__c p = new Project__c(
		  Id = pid,
		  BundleServices__c = false
		);
		update p;
	}

	@isTest
	static void testNewAttachmentAPI() {
		//GIVEN
		ImportRequestQueueTestUtil.setupQueueTestData(false);
		String pid = TestProject.getProjects()[0].Id;
		ImportRequestQueueItem__c item = getQItems()[0];
		List<List<String>> content = new List<List<String>>();
		content.add(new String[]{'1'});
		
		//WHEN
		test.startTest();
		ImportRequestQueueItemBatchHandler handler = 
			ImportRequestQueueItemBatchHandler.newInstance(pid);
		String attId = handler.newAttachment(item, content);
		test.stopTest();

		//THEN
		QA.isTrue(String.isNotBlank(attId), 'att generated:' + getError());
	}

	@isTest
	static void testHandleFailToGetLockWithMaxRetry() {
		//GIVEN
		ImportRequestQueueTestUtil.setupQueueTestData(false);
		String pid = TestProject.getProjects()[0].Id;
		ImportRequestQueueItem__c item = getQItems()[0];

		//WHEN
		test.startTest();
		ImportRequestQueueItemBatchHandler.handleFailedToGetLock(
			item.Id, 'failed to get lock.', 100);
		test.stopTest();

		//THEN
		item = getItem(item.Id);
		QA.EQ('Failed', item.Status__c, 'status should changed to failed');
		QA.isTrue(item.Response__c.indexOf('The maximum of retry') != -1, 'max retry message logged.');
	}

	@isTest
	static void testHandleFailToGetLock() {
		//GIVEN
		ImportRequestQueueTestUtil.setupQueueTestData(false);
		String pid = TestProject.getProjects()[0].Id;
		ImportRequestQueueItem__c item = getQItems()[0];

		//WHEN
		test.startTest();
		ImportRequestQueueItemBatchHandler.handleFailedToGetLock(
			item.Id, 'failed', 1);
		test.stopTest();

		//THEN
		item = getItem(item.Id);
		QA.EQ(2, item.RetryCount__c, '2 retries');
		QA.EQ('Queued', item.Status__c, 'still queued');
	}

	@isTest
	static void testErrorAttachmentScenario() {
		//GIVEN
		ImportRequestQueueTestUtil.setupQueueTestData(false);
		String pid = TestProject.getProjects()[0].Id;
		ImportRequestQueueItem__c item = getQItems()[0];

		//WHEN
		test.startTest();
		ImportRequestQueueItemBatchHandler handler = 
			ImportRequestQueueItemBatchHandler.newInstance(pid);
			handler.handleEachQueueItem(item);
		test.stopTest();

		//THEN
		item = getItem(item.Id);
		QA.isTrue(String.isNotBlank(item.ErrorAttachment__c), 'error attached');
		QA.isTrue(item.ErrorCount__c == item.RecordCount__c, 'data errored');
	}

	@isTest
	static void itShouldLogErrorOnQueueItem() {
		//GIVEN
		ImportRequestQueueTestUtil.setupQueueTestData();
		String pid = TestProject.getProjects()[0].Id;
		ImportRequestQueueItem__c item = getQItems()[0];

		//WHEN
		ImportRequestQueueItemBatchHandler.canNotHandleQueueItem(
		  item.Id,
		  'Failed',
		  'demo',
		  1);

		//THEN
		item = getQItems()[0];
		QA.EQ('Failed', item.Status__c, 'failed');
		QA.EQ(2, item.RetryCount__c, 'one retry');
	}

	static void assignBatchJob(ImportRequestQueueItem__c item){
		ImportRequestQueueItem__c rec = new ImportRequestQueueItem__c(
				Id = item.Id,
				BatchJobId__c = '1',
				BatchJobAssigned__c = true
			);
		update rec;
	}

	@isTest
	static void itShouldRetryQueueItemAndUnAssignBatchJobId() {
		//GIVEN
		ImportRequestQueueTestUtil.setupQueueTestData();
		String pid = TestProject.getProjects()[0].Id;
		ImportRequestQueueItem__c item = getQItems()[0];
		assignBatchJob(item);

		//WHEN
		ImportRequestQueueItemBatchHandler.canNotHandleQueueItem(
		  item.Id,
		  'Queued',
		  'demo',
		  1);

		//THEN
		item = getQItems()[0];
		QA.EQ('Queued', item.Status__c, 'failed');
		QA.EQ(2, item.RetryCount__c, 'one retry');
		QA.EQ(false, item.BatchJobAssigned__c, 'unassligned batch job');
		QA.isTrue(String.isBlank(item.BatchJobId__c), 'batch job id empty');
	}


	@isTest
	static void itShouldTrackAppLogIfUpdateFailed() {
		//GIVEN
		ImportRequestQueueTestUtil.setupQueueTestData();
		String pid = TestProject.getProjects()[0].Id;

		//WHEN
		ImportRequestQueueItemBatchHandler.canNotHandleQueueItem(
		  '',
		  'Failed',
		  'demo',
		  1);

		//THEN
		String error = getError();
		QA.isTrue(String.isNotBlank(error), 'error should be logged.');
	}

	@isTest
	static void itShouldExcuteBatchProperly() {
		//GIVEN
		ImportRequestQueueTestUtil.setupQueueTestData();
		String pid = TestProject.getProjects()[0].Id;

		//WHEN
		test.startTest();
		ImportRequestQueueItemBatchHandler handler =
		  ImportRequestQueueItemBatchHandler.newInstance(pid);
		Database.executeBatch(handler);
		test.stopTest();

		//THEN
		List<ImportRequestQueueItem__c> items = getQItems();
		Integer[] counts = getCounts(items);
		QA.EQ(counts[0], counts[1] + counts[2], '-- total matched error:'
		      + getError()
		      + ' responses:'
		      + getResponse(items));
		QA.isTrue(counts[2] == 0, 'no error');
		QA.isTrue(isQueueItemsInStatus(items, 'Completed'), 'completed');
		AppLocker__c lock = getLock();
		QA.isTrue(String.isBlank(lock.Token__c), 'lock reset');
	}

	@isTest
	static void itShouldHandleInvalidDataProperly() {
		//GIVEN
		ImportRequestQueueTestUtil.setupQueueTestData(false);
		String pid = TestProject.getProjects()[0].Id;

		//WHEN
		test.startTest();
		ImportRequestQueueItemBatchHandler handler =
		  ImportRequestQueueItemBatchHandler.newInstance(pid);
		Database.executeBatch(handler);
		test.stopTest();

		//THEN
		List<ImportRequestQueueItem__c> items = getQItems();
		Integer[] counts = getCounts(items);
		QA.EQ(counts[0], counts[1] + counts[2], '-- total matched error:'
		      + getError()
		      + ' responses:'
		      + getResponse(items));
		QA.isTrue(counts[2] == 20, 'has 20 errors');
		QA.isTrue(isQueueItemsInStatus(items, 'Failed'), 'failed');
		AppLocker__c lock = getLock();
		QA.isTrue(String.isBlank(lock.Token__c), 'lock reset');
		QA.isTrue(isQueueItemsErrorAttached(items), 'errors attached:' + getResponse(items));
	}

	@isTest
	static void itShouldHandleEachQueueItemProperly() {
		// Given
		String batchJobId = '1';
		ImportRequestQueueTestUtil.setupQueueTestData();
		String pId = TestProject.getProjects()[0].Id;
		ImportRequestQueueItem__c queueItem = getQItems()[0];

		// When
		test.startTest();
		ImportRequestQueueItemBatchHandler handler =
		  ImportRequestQueueItemBatchHandler.newInstance(pid);
		handler.handleEachQueueItem(queueItem);
		test.stopTest();

		// Then
		queueItem = getQItems()[0];
		AppLocker__c lock = getLock();
		QA.isTrue(queueItem.Status__c == 'Completed', 'completed:' + getError() + ':' + JSON.serialize(queueItem));
		QA.EQ('ImportRequestQueueItemBatchHandler', lock.RequestorId__c, 'requestid:ImportRequestQueueItemBatchHandler');
		QA.isTrue(String.isNotBlank(lock.Token__c), 'token assigned');
	}

	static Boolean isQueueItemsInStatus(List<ImportRequestQueueItem__c> items, String status) {
		Boolean result = true;
		for (ImportRequestQueueItem__c item : items) {
			if (item.Status__c != status) {
				result = false;
				break;
			}
		}
		return result;
	}

	static Boolean isQueueItemsErrorAttached(List<ImportRequestQueueItem__c> items) {
		Boolean result = true;
		for (ImportRequestQueueItem__c item : items) {
			if (String.isBlank(item.ErrorAttachment__c)) {
				result = false;
				break;
			}
		}
		return result;
	}

	static AppLocker__c getLock() {
		return [
		         SELECT
		         Id,
		         StartTime__c,
		         Token__c,
		         RequestorId__c
		         FROM AppLocker__c
		         LIMIT 1
		       ];
	}

	static ImportRequestQueueItem__c getItem(String itemId){
		for(ImportRequestQueueItem__c item: getQItems()){
			if (item.Id == itemId){
				return item;
			}
		}
		return null;
	}

	static List<ImportRequestQueueItem__c> getQItems() {
		return [
		         SELECT
		         Project__c,
		         AttachmentId__c,
		         SuccessCount__c,
		         ErrorCount__c,
		         BatchJobId__c,
		         BatchJobAssigned__c,
		         RecordCount__c,
		         Status__c,
		         RetryCount__c,
		         ConsumerAppClassName__c,
		         ErrorAttachment__c,
		         Datasource__c,
		         Response__c,
		         StartTime__c,
		         EndTime__c
		         FROM ImportRequestQueueItem__c
		       ];
	}
	static Integer[] getCounts(List<ImportRequestQueueItem__c> items) {
		Decimal total = 0, success = 0, error = 0;
		for (ImportRequestQueueItem__c item : items) {
			total += item.RecordCount__c;
			success += item.SuccessCount__c;
			error += item.ErrorCount__c;
		}
		return new Integer[] {
		         Integer.valueOf(total),
		         Integer.valueOf(success),
		         Integer.valueOf(error)
		       };
	}

	static String getResponse(List<ImportRequestQueueItem__c> items) {
		List<String> result = new List<String>();
		for (ImportRequestQueueItem__c item : items) {
			result.add(item.Response__c);
		}
		return String.join(result, ' ');
	}

	static String getError() {
		List<AppLog__c> logs = [
		                         SELECT
		                         Message__c
		                         FROM AppLog__c
		                       ];
		List<String> errs = new List<String>();
		for (AppLog__c log : logs) {
			errs.add(log.Message__c);
		}
		return String.Join(errs, ' ');
	}
}