src_old/objects/AppLog__c.object
<CustomObject>
    <description>app log</description>
    <fields>
        <fullName>Detail__c</fullName>
        <description>The log detail could be exception stack trace or detail of logging message</description>
        <label>Detail</label>
        <length>8192</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>EventSource__c</fullName>
        <description>the source where this log is generated</description>
        <label>Event Source</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LogLevel__c</fullName>
        <description>The log impact on the application.</description>
        <label>Log Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Debug</fullName>
                </value>
                <value>
                    <fullName>Info</fullName>
                </value>
                <value>
                    <fullName>Warning</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Critical</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <description>a log message that could be short description of the logging meaning</description>
        <label>Message</label>
        <length>5120</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Parameter__c</fullName>
        <description>a running data when the log is captured</description>
        <label>Parameter</label>
        <length>40960</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Phase__c</fullName>
        <description>the stage of the batch process when this log happens</description>
        <label>Phase</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RequestId__c</fullName>
        <description>Request Unique Identifier</description>
        <label>Request ID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Application Log</label>
    <nameField>
        <displayFormat>AL-{0000000000}</displayFormat>
        <label>Application Log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AppLogBatchTest.cls
@isTest
private class AppLogBatchTest {
    @isTest
    static void itShouldBeAbleToInsertBatchLog() {
        // Given
        AppLogBatch batch = AppLogBatch.createInstance();
        String phase = 'Start';
        String eventSource = AppLogBatch.EVENT_SOURCE_BATCHJOB;
        String errorType = 'demo';
        String parameter  = 'dummy';
        Boolean isTruncated = false;

        batch.newBatchJobLog()
        .setPhase(phase)
        .setRelatedIds('1', '2', '3')
        .setError()
        .setErrorType(errorType)
        .setMessageDetail('message', 'detail')
        .setParameter(parameter, isTruncated)
        .addToBatch();

        // When
        Test.startTest();
        batch.saveToDB();
        Test.stopTest();

        // Then
        AppLog__c result = getAppLog();
        QA.EQ(AppLogBatch.EVENT_SOURCE_BATCHJOB, result.EventSource__c, 'batch job');
        QA.EQ('detail', result.Detail__c,  'detail should be same');
        QA.EQ(phase, result.Phase__c, 'phase same');
        QA.EQ('Error', result.LogLevel__c, 'same error level');
    }

    @isTest 
    static void itShouldInsertAppLog() {
        // Given
        AppLogBatch batch = AppLogBatch.createInstance();
        String phase = 'Start';
        String eventSource = AppLogBatch.EVENT_SOURCE_ONLINE_APP;
        String errorType = 'demo';
        String parameter  = 'dummy';
        Boolean isTruncated = false;

        batch.newAppLog()
        .setPhase(phase)
        .setRelatedIds('1', '2', '3')
        .setError()
        .setErrorType(errorType)
        .setMessageDetail('message', 'detail')
        .setParameter(parameter, isTruncated)
        .addToBatch();

        // When
        Test.startTest();
        batch.saveToDB();
        Test.stopTest();

        //THEN
        AppLog__c result = getAppLog();
        QA.EQ(AppLogBatch.EVENT_SOURCE_ONLINE_APP, result.EventSource__c, 'app log');
    }

    @isTest
    static void itShouldappError() {
        //GIVEN
        CustomException ex = new CustomException('demo');
        String parameter = '1';
        String requestor = 'demo';

        //WHEN
        test.startTest();
        AppLogBatch.appError(ex, parameter,requestor);
        test.stopTest();

        //THEN
        AppLog__c result = getAppLog();
        QA.EQ(requestor, result.RequestId__c, 'requestor: demo');
        QA.EQ(parameter, result.Parameter__c, 'parameter: 1');
        QA.EQ('demo', result.Message__c, 'message: demo');
        QA.EQ('Error', result.LogLevel__c, 'level: error');
    }

    @isTest
    static void itShouldbatchError() {
         //GIVEN
        CustomException ex = new CustomException('demo');
        String parameter = '1';
        String requestor = 'demo';

        //WHEN
        test.startTest();
        AppLogBatch.batchError(ex, parameter,requestor);
        test.stopTest();

        //THEN
        AppLog__c result = getAppLog();
        QA.EQ(requestor, result.RequestId__c, 'requestor: demo');
        QA.EQ(parameter, result.Parameter__c, 'parameter: 1');
        QA.EQ('demo', result.Message__c, 'message: demo');
        QA.EQ('Error', result.LogLevel__c, 'level: error'); 
    }

    static string genTargetObjectName() {
        List<String> names = new List<String>();
        for(Integer i =0; i < 140; i++) {
            names.add(String.valueOf(i));
        }
        return String.join(names, '');
    }

    @isTest
    static void itShouldIncreaseCodeCoverage(){
        //when
        test.startTest();
        Database.SaveResult[] results = Database.insert(new Account[]{
            new Account(name='test 1'),
            new Account(name='test')
            });
        String tmp = AppLogBatch.LOG_LEVEL_CRITICAL;
        tmp = AppLogBatch.LOG_LEVEL_ERROR;
        tmp = AppLogBatch.LOG_LEVEL_INFO;
        tmp = AppLogBatch.LOG_LEVEL_WARNING;
        AppLogBatch.batchWarn('demo','detail','1','1');
        AppLogBatch.batchInfo('demo','detail','1','1');
        AppLogBatch.appInfo('demo','detail','1','1');
        AppLogBatch.appWarn('demo','detail','1','1');
        test.stopTest();

        //then
        String error = AppLogBatch.genSaveResultListError(results);
    }

    static AppLog__c getAppLog() {
        return AppLogBatch.getAll()[0];
    }
}