src_old/objects/AppSettings__mdt.object
<CustomObject>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>App Settings</label>
    <pluralLabel>App Settings</pluralLabel>
</CustomObject>

src_old/objects/Equipment__c.object
<CustomObject>
    <description>Equipment defines a piece of equipment that could either be an asset or tool. Equipment is related to Project Service Equipment and Retailer Service Equipment.</description>
    <fields>
        <fullName>EquipmentType__c</fullName>
        <description>A picklist that indicates the type of Equipment.</description>
        <inlineHelpText>Choose the type of equipment.</inlineHelpText>
        <label>Equipment Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Asset</fullName>
                </value>
                <value>
                    <fullName>Tool</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Equipment</label>
    <nameField>
        <label>Equipment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipment</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <fields>
        <fullName>IsLocked__c</fullName>
        <defaultValue>false</defaultValue>
        <description>A checkbox that indicates that the Project is locked</description>
        <inlineHelpText>If selected, the project is locked.</inlineHelpText>
        <label>Is Locked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Retailer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Retailer</label>
        <referenceTo>Retailer__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <recordTypes>
        <fullName>Locked</fullName>
        <active>true</active>
        <label>Locked</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ProjectService__c.object
<CustomObject>
    <description>Project Service relates a Service to a Project and is a container used to define the instance of a Service for a specific Project. Project Service is related to Project, Job, Project Service Attribute, Project Service Certification, Project Service Equipment, Project Service Material, Project Service Question, Project Service Target, and Service.</description>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>ProjectServices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Retailer__c</fullName>
        <formula>Project__r.Retailer__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Retailer</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>Project Services</relationshipLabel>
        <relationshipName>ProjectServices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Service</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Services</pluralLabel>
    <recordTypes>
        <fullName>Locked</fullName>
        <active>true</active>
        <label>Locked</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectServiceEquipment__c.object
<CustomObject>
    <description>Relates Equipment to a Project Service. Equipment from Retailer Service Equipment is added by default when a Service is added to a Project Service. Additional Equipment can also be added to the project. Project Service Equipment is related to Project Service and Equipment.</description>
    <fields>
        <fullName>Equipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Equipment</label>
        <referenceTo>Equipment__c</referenceTo>
        <relationshipLabel>Project Service Equipment</relationshipLabel>
        <relationshipName>ProjectServiceEquipment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsLocked__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Record cannot be deleted.</description>
        <label>Is Locked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProjectService__c</fullName>
        <label>Project Service</label>
        <referenceTo>ProjectService__c</referenceTo>
        <relationshipLabel>Project Service Equipment</relationshipLabel>
        <relationshipName>ProjectServiceEquipment</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Project Service Equipment</label>
    <nameField>
        <displayFormat>PSE-{0000000}</displayFormat>
        <label>Project Service Equipment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Service Equipment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/Retailer__c.object
<CustomObject>
    <description>Retailer stores the retailers for the system. Retailer is related to Location, Retailer Service, Retailer Service Certification, and Retailer Service Equipment.</description>
    <label>Retailer</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Retailers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/RetailerServiceEquipment__c.object
<CustomObject>
    <description>Retailer Service Equipment relates Equipment to a Retailer, which determines the Equipment that are available when building a Project Service. Retailer Service Equipment is related to Retailer, Service, and Equipment.</description>
    <fields>
        <fullName>Equipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Equipment</label>
        <referenceTo>Equipment__c</referenceTo>
        <relationshipLabel>Retailer Service Equipment</relationshipLabel>
        <relationshipName>RetailerServiceEquipment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsLocked__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if the equipment can be removed from project service</description>
        <inlineHelpText>Locked equipment cannot be deleted at project service level</inlineHelpText>
        <label>Is Locked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Retailer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Retailer</label>
        <referenceTo>Retailer__c</referenceTo>
        <relationshipLabel>Retailer Service Equipment</relationshipLabel>
        <relationshipName>RetailerServiceEquipment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>Retailer Service Equipment</relationshipLabel>
        <relationshipName>RetailerServiceEquipment</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Retailer Service Equipment</label>
    <nameField>
        <displayFormat>RSE-{0000}</displayFormat>
        <label>Retailer Service Equipment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retailer Service Equipment</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/Service__c.object
<CustomObject>
    <description>Service contains the definition of a service. Service is related to Service Attribute, Service Exception, Service Question, Service Question Defined Response, Retailer Service, Retailer Service Equipment, and Project Service.</description>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/ProjectServiceEquipmentTriggerHandler.cls
public class ProjectServiceEquipmentTriggerHandler extends TriggerHandler {
    
    
    public override void beforeUpdate() {

        if(TriggerUtil.skipLocationEquipmentTrigger == true){
            return;
        }
        
        list<AppSettings__mdt> lstappsettings = new list<AppSettings__mdt>();
        string eqAsset = '';
        lstappsettings = [SELECT Value__c FROM AppSettings__mdt WHERE DeveloperName = 'EquimentTypeAsset' limit 1];
        if(lstappsettings.size()>0){
            eqAsset = lstappsettings[0].Value__c;
        }
        
        set<Id> projectequipmentIds = new set<Id> ();
        projectequipmentIds = trigger.newmap.keyset();
        set<Id> serviceIds = new set<Id>();
        set<Id> retailerIds = new set<Id> ();
        //map<String,ProjectServiceEquipment__c> mapServiceRetailer = new map<String,ProjectServiceEquipment__c>();
        
        for(ProjectServiceEquipment__c pse : [Select ProjectService__r.Project__r.Retailer__c,ProjectService__r.Service__c from ProjectServiceEquipment__c where Id IN :projectequipmentIds]){
            serviceIds.add(pse.ProjectService__r.Service__c);
            retailerIds.add(pse.ProjectService__r.Project__r.Retailer__c);
           // mapServiceRetailer.put(pse.ProjectService__r.Project__r.Retailer__c+'-'+pse.ProjectService__r.Service__c,pse);
        }
        Map<ID,Decimal> lockedEquipmentMap = new Map<ID,Decimal>();
        for(RetailerServiceEquipment__c lockedEq : [SELECT Equipment__c, Quantity__c FROM RetailerServiceEquipment__c 
                                                            WHERE Equipment__r.EquipmentType__c=:eqAsset 
                                                            AND Retailer__c IN : retailerIds 
                                                            AND Service__c IN :serviceIds 
                                                            AND IsLocked__c = true]){
            lockedEquipmentMap.put(lockedEq.Equipment__c, lockedEq.Quantity__c);
        }
        for(projectServiceEquipment__c pse : (list<projectServiceEquipment__c>) trigger.new){
             if(lockedEquipmentMap.containsKey(pse.Equipment__c) && pse.Quantity__c < lockedEquipmentMap.get(pse.Equipment__c)){
                pse.addError('Locked equipment quantity cannot be reduced.'); 
                return;
            }  
        }
    }
    
    public override void afterUpdate() {
        // COMMENTING THE WHOLE TRIGGER AS IT NO MORE HAS VALID LOGIC 

        /*if(TriggerUtil.skipLocationEquipmentTrigger == true){
            return;
        }
        List<ProjectServiceEquipment__c> pseList = (List < ProjectServiceEquipment__c > ) Trigger.new;
        List<ProjectService__c> psList = [SELECT Id, Project__c FROM ProjectService__c WHERE ID = :pseList[0].ProjectService__c LIMIT 1];
        Project__c project = [SELECT Id FROM Project__c WHERE ID = :psList[0].Project__c LIMIT 1];
        system.debug('psList####'+psList);
        system.debug('project+++++'+project);
        system.debug('pseList####'+pseList);
        
        string eqAsset = [SELECT Value__c FROM AppSettings__mdt WHERE DeveloperName = 'EquimentTypeAsset' limit 1].Value__c;
        
        for (ProjectServiceEquipment__c pse: pseList) {
            
            Equipment__c eq = [SELECT Id, Name, EquipmentType__c FROM Equipment__c WHERE ID = :pse.Equipment__c];
            /*
            if(pse.IsCapacityImpact__c != ((ProjectServiceEquipment__c)Trigger.oldMap.get(pse.Id)).IsCapacityImpact__c){
                FeedItem post = new FeedItem();
                post.ParentId = project.Id;
                if(pse.IsCapacityImpact__c){
                    post.Body = userinfo.getname() + ' checked '+ eq.Name +' impact capcity flag';
                } 
                else {
                    post.Body = userinfo.getname() + '  removed '+ eq.Name +' impact capcity flag';
                }
                insert post;
               
            }
            if(pse.IsCapacityImpact__c == false){
                continue;
            }
            */
        //}  
    }
}