src_old/objects/AppSettings__mdt.object
<CustomObject>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>App Settings</label>
    <pluralLabel>App Settings</pluralLabel>
</CustomObject>

src_old/objects/Equipment__c.object
<CustomObject>
    <description>Equipment defines a piece of equipment that could either be an asset or tool. Equipment is related to Project Service Equipment and Retailer Service Equipment.</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>An entry field that describes the Equipment.</description>
        <inlineHelpText>Enter a description of the equipment.</inlineHelpText>
        <label>Description</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EquipmentType__c</fullName>
        <description>A picklist that indicates the type of Equipment.</description>
        <inlineHelpText>Choose the type of equipment.</inlineHelpText>
        <label>Equipment Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Asset</fullName>
                </value>
                <value>
                    <fullName>Tool</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>A checkbox that indicates if this Equipment is active</description>
        <inlineHelpText>Select this box if this equipment is active.</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Equipment</label>
    <nameField>
        <label>Equipment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipment</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <fields>
        <fullName>IsJobManualRegenReqd__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The check box will be set when a the Job Manual has to be generated.</description>
        <inlineHelpText>The check box will be set when a the Job Manual has to be generated.</inlineHelpText>
        <label>Regenerate Job Manual</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsLocked__c</fullName>
        <defaultValue>false</defaultValue>
        <description>A checkbox that indicates that the Project is locked</description>
        <inlineHelpText>If selected, the project is locked.</inlineHelpText>
        <label>Is Locked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Retailer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Retailer</label>
        <referenceTo>Retailer__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planning</fullName>
                    <default>true</default>
                    <label>Planning</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Launched</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ended</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <recordTypes>
        <fullName>Locked</fullName>
        <active>true</active>
        <label>Locked</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ProjectService__c.object
<CustomObject>
    <description>Project Service relates a Service to a Project and is a container used to define the instance of a Service for a specific Project. Project Service is related to Project, Job, Project Service Attribute, Project Service Certification, Project Service Equipment, Project Service Material, Project Service Question, Project Service Target, and Service.</description>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>ProjectServices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Retailer__c</fullName>
        <formula>Project__r.Retailer__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Retailer</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>Project Services</relationshipLabel>
        <relationshipName>ProjectServices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Executed</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project Service</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Services</pluralLabel>
    <recordTypes>
        <fullName>Locked</fullName>
        <active>true</active>
        <label>Locked</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectServiceEquipment__c.object
<CustomObject>
    <description>Relates Equipment to a Project Service. Equipment from Retailer Service Equipment is added by default when a Service is added to a Project Service. Additional Equipment can also be added to the project. Project Service Equipment is related to Project Service and Equipment.</description>
    <fields>
        <fullName>Equipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Equipment</label>
        <referenceTo>Equipment__c</referenceTo>
        <relationshipLabel>Project Service Equipment</relationshipLabel>
        <relationshipName>ProjectServiceEquipment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsLocked__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Record cannot be deleted.</description>
        <label>Is Locked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProjectService__c</fullName>
        <label>Project Service</label>
        <referenceTo>ProjectService__c</referenceTo>
        <relationshipLabel>Project Service Equipment</relationshipLabel>
        <relationshipName>ProjectServiceEquipment</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Project Service Equipment</label>
    <nameField>
        <displayFormat>PSE-{0000000}</displayFormat>
        <label>Project Service Equipment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Service Equipment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/Retailer__c.object
<CustomObject>
    <description>Retailer stores the retailers for the system. Retailer is related to Location, Retailer Service, Retailer Service Certification, and Retailer Service Equipment.</description>
    <label>Retailer</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Retailers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/RetailerServiceEquipment__c.object
<CustomObject>
    <description>Retailer Service Equipment relates Equipment to a Retailer, which determines the Equipment that are available when building a Project Service. Retailer Service Equipment is related to Retailer, Service, and Equipment.</description>
    <fields>
        <fullName>Equipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Equipment</label>
        <referenceTo>Equipment__c</referenceTo>
        <relationshipLabel>Retailer Service Equipment</relationshipLabel>
        <relationshipName>RetailerServiceEquipment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsLocked__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if the equipment can be removed from project service</description>
        <inlineHelpText>Locked equipment cannot be deleted at project service level</inlineHelpText>
        <label>Is Locked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Retailer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Retailer</label>
        <referenceTo>Retailer__c</referenceTo>
        <relationshipLabel>Retailer Service Equipment</relationshipLabel>
        <relationshipName>RetailerServiceEquipment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>Retailer Service Equipment</relationshipLabel>
        <relationshipName>RetailerServiceEquipment</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Retailer Service Equipment</label>
    <nameField>
        <displayFormat>RSE-{0000}</displayFormat>
        <label>Retailer Service Equipment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retailer Service Equipment</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/Service__c.object
<CustomObject>
    <description>Service contains the definition of a service. Service is related to Service Attribute, Service Exception, Service Question, Service Question Defined Response, Retailer Service, Retailer Service Equipment, and Project Service.</description>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/ProjectServiceEquipmentEditExt.cls
public with sharing class ProjectServiceEquipmentEditExt {
    
    public ProjectService__c ps{get;set;}
    public List<ProjectServiceEquipment__c> pseList {get;set;}
    public List<SelectOption> EquipmentSelectOptions {get;set;}
    public string SelectedEquipment{get;set;}
    public string SelectedQuantity{get;set;}
    public Project__c project {get;set;}    
    public Boolean showEqButtons{get;set;}
    public Boolean showToolsButtons{get;set;}
    public List<SelectOption> utensilList{get;set;}
    public List<SelectOption> SelectedUtensilList{get;set;} 
    public List<String> selectedUtensils{get;set;} 
    public Map<String,Boolean> editableMap {get;set;}
           
    /*public Boolean showEditCapacityImpact{
        get {
            return Schema.sObjectType.ProjectServiceEquipment__c.fields.IsCapacityImpact__c.isUpdateable();
        }
    }*/

    
    private void addMessage(ApexPages.Severity severity, String message){
        Apexpages.addMessage(new ApexPages.Message(severity, message));
    }
    public string eqAsset{get;set;}
    public string eqTools{get;set;}
    
    public ProjectServiceEquipmentEditExt(ApexPages.StandardController controller) {
        ps = [SELECT Id, Name, Project__r.Retailer__c, Project__c, Project__r.Status__c, Service__c FROM ProjectService__c where id =:ApexPages.CurrentPage().getParameters().get('id') ];
        eqAsset = [SELECT Value__c FROM AppSettings__mdt WHERE DeveloperName = 'EquimentTypeAsset' limit 1].Value__c;
        eqTools = [SELECT Value__c FROM AppSettings__mdt WHERE DeveloperName = 'Equimenttypetool' limit 1].Value__c;
         
        loadEquipment();
        EquipmentSelectOptions = new List<SelectOption>();
        EquipmentSelectOptions.add(new SelectOption('','-None-'));
        for(Equipment__c eq : [SELECT Id, Name FROM Equipment__c WHERE EquipmentType__c=:eqAsset and ID NOT IN (SELECT Equipment__c FROM RetailerServiceEquipment__c WHERE Retailer__c =: ps.Project__r.Retailer__c AND Service__c =: ps.Service__c)]){
            EquipmentSelectOptions.add(new SelectOption(eq.Id, eq.Name));
        }
        
        Set<String> editableFields = new Set<String>{'Project__c.RL_Equipment', 'Project__c.RL_Tools'};
        editableMap = UIConfig.isEditale(project.Status__c, editableFields);
        showEqButtons = editableMap.get('Project__c.RL_Equipment') && Schema.sObjectType.ProjectServiceEquipment__c.isUpdateable();
        showToolsButtons = editableMap.get('Project__c.RL_Tools') && Schema.sObjectType.ProjectServiceEquipment__c.isUpdateable();

        
        SelectedUtensilList = new List<SelectOption>();
        selectedUtensils = new List<String>();
        set<id> pse = new set<id>();
        for(projectserviceEquipment__c eq : [SELECT Id, equipment__r.Name,equipment__r.id,equipment__r.description__c   FROM projectserviceEquipment__c WHERE  equipment__r.EquipmentType__c=:eqTools and projectservice__c =: ps.id order by equipment__r.Name]){
            SelectedUtensilList.add(new SelectOption(eq.equipment__r.Id, eq.equipment__r.description__c));
            pse.add(eq.equipment__r.Id);
            selectedUtensils.add(eq.equipment__r.description__c);
        }
        
        utensilList= new List<SelectOption>();
        for(Equipment__c eq : [SELECT Id, Name,description__c FROM Equipment__c WHERE isactive__c =true and EquipmentType__c=:eqTools and id not in:pse order by name]){
            utensilList.add(new SelectOption(eq.Id, eq.description__c));    
        }
    }
    
    public void loadEquipment(){
        pseList = [SELECT Id, Equipment__c, ProjectService__c, Quantity__c, IsLocked__c, ProjectService__r.Project__c  FROM ProjectServiceEquipment__c WHERE ProjectService__c =:ps.Id and equipment__r.EquipmentType__c=:eqAsset ORDER BY IsLocked__c DESC];
        ProjectService__c tmpPs = [SELECT Id, Project__c, Service__c FROM ProjectService__c where id =:ApexPages.CurrentPage().getParameters().get('id') ];
        project = [SELECT Id, Status__c FROM Project__c where id =:tmpPs.Project__c];

    }
    
    public PageReference addEquipment() {
        try {
            if(String.isBlank(SelectedEquipment)){
                addMessage(ApexPages.Severity.ERROR,'Please select asset.');                
                return null;
            }
            
            for (ProjectServiceEquipment__c pse : pseList)    
            {
                if (pse.Equipment__c == SelectedEquipment)
                {
                    addMessage(
                        ApexPages.Severity.ERROR, 
                        'This asset has already been added. Please check and try again.'
                    );
                    return null;
                }
            }
            
            Pattern isnumber = Pattern.Compile('^[0-9]+$');
            Matcher patterMatch = isnumber.matcher(SelectedQuantity);
            if(!patterMatch.Matches() || (Integer.valueOf(SelectedQuantity) <= 0 || Integer.valueOf(SelectedQuantity) > 99999)){
                addMessage(ApexPages.Severity.ERROR, 'Invalid Quantity. Please check and try again.');
                return null;
            }
            
            Equipment__c e = [SELECT EquipmentType__c FROM Equipment__c WHERE ID  = :SelectedEquipment];
            ProjectServiceEquipment__c pse = new ProjectServiceEquipment__c();
            pse.ProjectService__c = ps.Id;
            pse.Equipment__c = SelectedEquipment;
            pse.Quantity__c = Decimal.valueOf(SelectedQuantity);
            
            pse.IsLocked__c = false;
            insert pse;
            loadEquipment();
            SelectedQuantity = '';
            SelectedEquipment = '';
            system.debug('project::::'+project);
            
            TriggerUtil.SkipProjectTrigger = true;
            update project;
            
            return null;
        }
        catch(Exception e){
                        addMessage(ApexPages.Severity.ERROR, e.getmessage());
            return null;
        }
    }
    
    public PageReference deleteEquipment(){
        try {  
            string pseDelId = ApexPages.currentpage().getParameters().get('pseDelId');
            for (ProjectServiceEquipment__c pse : pseList) {
                if (pseDelId == pse.Id) {
                    
                        delete pse;
                        break;
                }
            }
            addMessage(ApexPages.Severity.CONFIRM, 'Asset deleted.');
            loadEquipment();
           
            TriggerUtil.SkipProjectTrigger = true;
            update project;
                return null;
        }
                catch(Exception e) {
            addMessage(ApexPages.Severity.ERROR, e.getmessage());
            //system.debug('aaaaaa: '+e.getmessage());
            return null;
        }
    }
    
    
    public PageReference saveEditRows() {
        if(pseList.size() == 0) {
            return null;
        }
        try { 
            for(ProjectServiceEquipment__c pse:pseList){
                Map<ID,Decimal> lockedEqupmentMap = getLockedEqupment();
                if(lockedEqupmentMap.containsKey(pse.Equipment__c) && pse.Quantity__c < lockedEqupmentMap.get(pse.Equipment__c)){
                        addMessage(ApexPages.Severity.ERROR, 'Locked asset quantity cannot be reduced.');
                        return null;
                }
                
                if(pse.Quantity__c <= 0 || pse.Quantity__c > 99999){
                        addMessage(ApexPages.Severity.ERROR, 'Invalid Quantity. Please check and try again.');
                        return null;
                }
                
                if(String.isBlank(pse.Equipment__c)){
                        addMessage(ApexPages.Severity.ERROR, 'Please select Asset.');
                        return null;
                }
                
                }
            update pseList;
            addMessage(ApexPages.Severity.CONFIRM, 'Asset(s) saved successfully.');                
            loadEquipment();
            SelectedQuantity = '';
            SelectedEquipment = '';
                return null;
        }
        catch(Exception e) {
            addMessage(ApexPages.Severity.ERROR, e.getmessage());
            return null;
        }
    }
    
    private Map<ID,Decimal> getLockedEqupment(){
        Map<ID,Decimal> lockedEqupmentMap = new Map<ID,Decimal>();
        for(RetailerServiceEquipment__c lockedEq : [SELECT Equipment__c, Quantity__c FROM RetailerServiceEquipment__c WHERE Retailer__c =: ps.Project__r.Retailer__c AND Service__c =: ps.Service__c AND IsLocked__c = true]){
            lockedEqupmentMap.put(lockedEq.Equipment__c, lockedEq.Quantity__c);
        }
        return lockedEqupmentMap;
    }
    
    public pagereference SaveUtensil(){
        try{
            TriggerUtil.skipLocationEquipmentTrigger =true;
            delete [SELECT Id FROM projectserviceEquipment__c WHERE equipment__r.EquipmentType__c=:eqTools and projectservice__c =: ps.id];
            list<ProjectServiceEquipment__c>  pseList = new list<ProjectServiceEquipment__c>();
            ProjectServiceEquipment__c pse;
            for (SelectOption sl : SelectedUtensilList)
            {
                pse = new ProjectServiceEquipment__c();
                pse.equipment__c = sl.getValue();
                pse.ProjectService__c= ps.id;
                
                pse.quantity__c= 1;
                pse.islocked__c=false;
                pseList.add(pse);
            }
            upsert pseList;
            
            Project__c proj = [select id, Status__c,IsJobManualRegenReqd__c from project__c where id=: [select id,project__c from projectservice__c where id=:ps.ID limit 1].project__c];
            if(proj.Status__c == CONSTANTS.PROJECT_STATUS_BOOKED || proj.Status__c == CONSTANTS.PROJECT_STATUS_LAUNCHED || proj.Status__c == CONSTANTS.PROJECT_STATUS_INPROGRESS )
            {            
                TriggerUtil.skipProjectTrigger = true;
                proj.IsJobManualRegenReqd__c = true;
                update proj;
            }
            
            addMessage(ApexPages.Severity.CONFIRM, 'Tool(s) saved successfully.'); 
            return null;
        }
        catch(exception e){
            addMessage(ApexPages.Severity.ERROR, e.getmessage());
            return null;       
        }
        
    }
    
}