src_old/objects/Attribute__c.object
<CustomObject>
    <description>Attribute defines an attribute and includes a type definition (e.g. Picklist, Yes/No, Text, Multiple Choice, etc.), description, and other default values. Attributes are related to a Service Attribute and a Project Service Attribute.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>A checkbox that indicates whether this Attribute is active (this field must not be selected if the attribute is to be deleted or turned off).</description>
        <inlineHelpText>Select this box if the attribute active.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AttributeMaxLength__c</fullName>
        <description>A value that indicates the maximum length of the Attribute.</description>
        <label>Attribute Max Length</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AttributeTitle__c</fullName>
        <description>An entry field for the title of the Attribute.</description>
        <inlineHelpText>Enter the title of the attribute.</inlineHelpText>
        <label>Attribute Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AttributeType__c</fullName>
        <description>A picklist with that determines the type of Attribute.</description>
        <inlineHelpText>Choose the type of attribute.</inlineHelpText>
        <label>AttributeType</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Text</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Yes/No</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Single-Select List</fullName>
                </value>
                <value>
                    <fullName>Multi-Select List</fullName>
                </value>
                <value>
                    <fullName>Photo</fullName>
                </value>
                <value>
                    <fullName>File</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Attribute</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Attribute Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attributes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/objects/ImageServiceSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <label>UserName</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>ImageServiceSettings</label>
</CustomObject>

src_old/objects/OrgCustomSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Generic org settings will be stored here</description>
    <fields>
        <fullName>MaxServicesforManualGeneration__c</fullName>
        <label>Max Services for Manual Generation</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Org Custom Settings</label>
</CustomObject>

src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <fields>
        <fullName>ProjectTypeName__c</fullName>
        <formula>ProjectType__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Type Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Retailer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Retailer</label>
        <referenceTo>Retailer__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ProjectService__c.object
<CustomObject>
    <description>Project Service relates a Service to a Project and is a container used to define the instance of a Service for a specific Project. Project Service is related to Project, Job, Project Service Attribute, Project Service Certification, Project Service Equipment, Project Service Material, Project Service Question, Project Service Target, and Service.</description>
    <fields>
        <fullName>IncludeAutoGenManual__c</fullName>
        <defaultValue>true</defaultValue>
        <description>setting to include system generated manual. Default to true</description>
        <label>Attach System Generated Manual</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>JobManualURL__c</fullName>
        <description>URL to access event manual</description>
        <label>Job Manual URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>JobManual__c</fullName>
        <label>JobManual</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No Manual</fullName>
                </value>
                <value>
                    <fullName>Standard</fullName>
                </value>
                <value>
                    <fullName>Custom Manual</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ProjectTypeName__c</fullName>
        <formula>Project__r.ProjectTypeName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Type Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>ProjectServices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Retailer__c</fullName>
        <formula>Project__r.Retailer__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Retailer</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>Project Services</relationshipLabel>
        <relationshipName>ProjectServices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Service</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectServiceAttribute__c.object
<CustomObject>
    <description>Relates a Service Attribute to a Project Service and prepopulates default values. Service Attribute is related to Service, Project Service Attribute, and Attribute.</description>
    <fields>
        <fullName>AttachmentExt__c</fullName>
        <label>Attachment Ext</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AttachmentURL__c</fullName>
        <label>Attachment URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>AttributeTitle__c</fullName>
        <formula>Attribute__r.AttributeTitle__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Attribute Title</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AttributeType__c</fullName>
        <formula>TEXT(Attribute__r.AttributeType__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AttributeType</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attribute__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Attribute</label>
        <referenceTo>Attribute__c</referenceTo>
        <relationshipLabel>Project Service Attributes</relationshipLabel>
        <relationshipName>Project_Service_Attributes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectService__c</fullName>
        <label>Project Service</label>
        <referenceTo>ProjectService__c</referenceTo>
        <relationshipLabel>Project Service Attributes</relationshipLabel>
        <relationshipName>Project_Service_Attributes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>Project Service Attributes</relationshipLabel>
        <relationshipName>Project_Service_Attributes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Service Attribute</label>
    <nameField>
        <displayFormat>PSA-{00000000}</displayFormat>
        <label>Project Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Service Attributes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/Retailer__c.object
<CustomObject>
    <description>Retailer stores the retailers for the system. Retailer is related to Location, Retailer Service, Retailer Service Certification, and Retailer Service Equipment.</description>
    <label>Retailer</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Retailers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/Service__c.object
<CustomObject>
    <description>Service contains the definition of a service. Service is related to Service Attribute, Service Exception, Service Question, Service Question Defined Response, Retailer Service, Retailer Service Equipment, and Project Service.</description>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/AttachmentUrlGenerator.cls
/*
* this API is used to call APEX PageReference to generate PDF content 
* and send to image service for attachment
*/
@RestResource(urlMapping='/generateAttachmentUrl/*')
global without sharing class AttachmentUrlGenerator {
    
    @HttpGet
    global static void generateUrl() {
        RestResponse res = RestContext.response;
        try{
            String projectId = parseProjectId();
            generateJobManualFutureCall(projectId);
            res.statusCode = 201;
            
        } catch(Exception ex) {
            res.statusCode = 500;
            system.debug(ex);
            res.responseBody = Blob.valueof(ex.getMessage());
        }
    }
    
    
    public static void generateJobManualFutureCall(string projectId)
    {
        TriggerUtil.SkipProjectTrigger = true;
	 Integer maxservices = getMaxServicesForManualGeneration();                
                
        list<projectservice__c> projectservices = [select id, JobManual__c from projectservice__c where project__C=:projectId];            
        if (projectservices.size() <= maxservices)            
        {
            for(projectservice__c ps : projectservices)
            {
                if(ps.JobManual__c == CONSTANTS.JOB_MANUAL_STANDARD_TEMPLATE){
                    generateJobManual(ps.Id);    
                }
            }
        }

    }  
    
    
    @future (callout=true)
    public static void generateJobManual(string psId)
    {
        TriggerUtil.SkipAllTriggers();

        projectservice__c ps = [select name,project__c, JobManualURL__c,service__c,IncludeAutoGenManual__c,project__r.ProjectTypeName__c, Project__r.Retailer__c,JobManual__c from projectservice__C where id=: psId];
        Blob pdf = getPdfContent(ps);
       if(ps.IncludeAutoGenManual__c!=false)
        {
          if(ps.JobManualURL__c==null){
                string urlData = callImageServiceToPostAttachment(pdf);
                updateDetails(ps,urlData);    
            }
            else{
                system.debug('  JobManualURL not blank ' +ps.JobManualURL__c);                    
                Integer statusCode =  callImageServiceToPutAttachment(ps.JobManualURL__c,pdf);
                updateDetails(ps,ps.JobManualURL__c);                      
            }
        }
    }
    
    public static void generateJobManualNonFutureCall(string projectId)
    {
        TriggerUtil.SkipProjectTrigger = true;

		Integer maxservices = getMaxServicesForManualGeneration();                
                
        list<projectservice__c> projectservices = [select id,JobManual__c from projectservice__c where project__C=:projectId];            
        if (projectservices.size() <= maxservices)            
        {
            for(projectservice__c ps : projectservices)
            {
                  if(ps.JobManual__c == CONSTANTS.JOB_MANUAL_STANDARD_TEMPLATE){
                     generateJobManualNonFuture(ps.Id); 
                  }
            }
        
        }        
    }    
    
    
    public static void generateJobManualNonFuture(string psId)
    {
        TriggerUtil.SkipProjectTrigger = true; 
        TriggerUtil.SkipProjectServiceTrigger = true;
        TriggerUtil.skipProjectServiceTargetAttributeTrigger = true;
        projectservice__c ps = [select name,project__c, JobManualURL__c,service__c,IncludeAutoGenManual__c,project__r.ProjectTypeName__c, Project__r.Retailer__c,JobManual__c from projectservice__C where id=: psId for update];
        Blob pdf = getPdfContent(ps);
        if(ps.IncludeAutoGenManual__c!=false)
        {
            if(ps.JobManualURL__c==null){
                string urlData = callImageServiceToPostAttachment(pdf);
                updateDetails(ps,urlData);    
            }
            else{
                system.debug('  ps.JobManualURL__c  ' +ps.JobManualURL__c);                    
                Integer statusCode =  callImageServiceToPutAttachment(ps.JobManualURL__c,pdf);
                updateDetails(ps,ps.JobManualURL__c);                      
            }
        }
    }
    
    
    private static string parseProjectId(){
        RestRequest req = RestContext.request;
        return req.requestURI.substring(req.requestURI.lastIndexOf('/') + 1);
    }
    
    private static Blob getPdfContent(ProjectService__c ps) {        
        PageReference reference;        
       if(ps.JobManual__c != null){
            string pdfTemplateUrl = '/apex/' + CONSTANTS.CURRENTNAMESPACEPREFIX + 'pdftemplate?psId='+ps.Id;
            
            reference = New PageReference(pdfTemplateUrl);
            if(Test.isRunningTest())
                return Blob.valueOf(pdfTemplateUrl);
            return reference.getContentAsPDF();
        }   
        
        return  Blob.valueof('Error: Job Manual template may not be configured');
    }
    
    
    public static String callImageServiceToPostAttachment(Blob pdf) {
        try{
        
            ImageServiceSettings__c imgSvc = ImageServiceSettings__c.getValues('ImageService');
            HttpRequest req = new HttpRequest();
            req.setEndpoint(imgSvc.URL__c);  //req.setEndpoint(IMAGE_SERVICE_ENDPOINT);  
            req.setMethod('POST');
            String userName =  imgSvc.UserName__c; //'external\\m3.testing';
            String password =  imgSvc.Password__c; //'Password1';
            system.debug(userName +' ~~~up~~~ '+password );
            
            //create basicAuth header
            Blob headerValue = Blob.valueOf(userName + ':' + password);
             String authorizationHeader = 'Basic ' + EncodingUtil.base64Encode(headerValue);
            // set headers
            req.setHeader('Authorization', authorizationHeader);
            req.setHeader('Content-Type', 'application/pdf');
            req.setHeader('Accept', 'application/json');
            req.setBodyAsBlob(pdf);
            //Send request
            Http http = new Http();
            HttpResponse res = http.send(req);
            
            system.debug(' ~~~res~~~ '+res);
            system.debug(' ~~~res.getHeader(Location)~~~ '+res.getHeader('Location'));
            
            return res.getHeader('Location');   
        }
        catch(exception ex){
            system.debug('----' + ex.getMessage() );
            return null;
        }
    }
    
    public static Integer callImageServiceToPutAttachment(string attachUrl,Blob pdf) {
        try{
            ImageServiceSettings__c imgSvc = ImageServiceSettings__c.getValues('ImageService');
            HttpRequest req = new HttpRequest();
            req.setEndpoint(attachUrl);
            system.debug('----image url:' + attachUrl);
            req.setMethod('PUT');
            String userName = imgSvc.UserName__c; //'external\\m3.testing';
            String password = imgSvc.Password__c; //'Password1';
            
            //create basicAuth header
            Blob headerValue = Blob.valueOf(userName + ':' + password);
            String authorizationHeader = 'Basic ' + EncodingUtil.base64Encode(headerValue);
            // set headers
            req.setHeader('Authorization', authorizationHeader);
            req.setHeader('Content-Type', 'application/pdf');
            req.setHeader('Accept', 'application/json');
            req.setHeader('If-Match','"*"');
            req.setBodyAsBlob(pdf);
            //Send request
            Http http = new Http();
            HttpResponse res = http.send(req);
            system.debug('----etag:' + res.getHeader('Etag'));
            return res.getStatusCode();   
        }
        catch(exception ex){
            system.debug('----' + ex.getMessage() );
            return null;
        }
    }
    
    public static void updateDetails(projectservice__c ps,string URLdata)
    {
        try{
            system.debug('---URLdata---' + URLdata);
            attribute__c attr = [SELECT Id,Name, Attributetitle__c,Active__c,AttributeMaxLength__c,AttributeType__c FROM Attribute__c WHERE Attributetitle__c = 'Job Manual' limit 1 FOR UPDATE];
            system.debug('---attr.id---' + attr.id);
            ps.JobManualURL__c = URLdata;
            ProjectServiceAttribute__c psca = new ProjectServiceAttribute__c();
            list<ProjectServiceAttribute__c> pscaLst = [SELECT AttachmentURL__c,AttributeTitle__c,AttachmentExt__c FROM ProjectServiceAttribute__c WHERE ProjectService__c =:ps.id and Attribute__c =: attr.id FOR UPDATE];
            if(pscaLst!=null && pscaLst.size() > 0)
            {
                psca =  pscaLst[0];    
                system.debug('---pscaLst[0]---' + pscaLst[0]);
            }
            
            psca.AttachmentURL__c = URLdata;
            psca.service__C = ps.service__c;
            psca.Attribute__c= attr.id;
            psca.AttachmentExt__c='pdf';
            upsert psca;        
            
            system.debug('~~ psca update end !!! ~~');
            
            update ps;
        } catch(Exception ex) {
            system.debug('----' + ex.getMessage() + ':' + ex.getStackTraceString());
        }
    }
   
    private static Integer getMaxServicesForManualGeneration(){
        List<OrgCustomSettings__c> settings = [SELECT MaxServicesforManualGeneration__c FROM OrgCustomSettings__c LIMIT 1];
        if(settings == null || settings.size() == 0 || settings[0] == null || settings[0].MaxServicesforManualGeneration__c == null){
            return 20;
        }
        return integer.valueOf(settings[0].MaxServicesforManualGeneration__c);
    }        
    
    
}