src_old/objects/Attribute__c.object
<CustomObject>
    <description>Attribute defines an attribute and includes a type definition (e.g. Picklist, Yes/No, Text, Multiple Choice, etc.), description, and other default values. Attributes are related to a Service Attribute and a Project Service Attribute.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>A checkbox that indicates whether this Attribute is active (this field must not be selected if the attribute is to be deleted or turned off).</description>
        <inlineHelpText>Select this box if the attribute active.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AttributeType__c</fullName>
        <description>A picklist with that determines the type of Attribute.</description>
        <inlineHelpText>Choose the type of attribute.</inlineHelpText>
        <label>AttributeType</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Text</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Yes/No</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Single-Select List</fullName>
                </value>
                <value>
                    <fullName>Multi-Select List</fullName>
                </value>
                <value>
                    <fullName>Photo</fullName>
                </value>
                <value>
                    <fullName>File</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Attribute</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Attribute Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attributes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ProjectService__c.object
<CustomObject>
    <description>Project Service relates a Service to a Project and is a container used to define the instance of a Service for a specific Project. Project Service is related to Project, Job, Project Service Attribute, Project Service Certification, Project Service Equipment, Project Service Material, Project Service Question, Project Service Target, and Service.</description>
    <fields>
        <fullName>JobManualURL__c</fullName>
        <description>URL to access event manual</description>
        <label>Job Manual URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>ProjectServices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>Project Services</relationshipLabel>
        <relationshipName>ProjectServices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Service</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/Service__c.object
<CustomObject>
    <description>Service contains the definition of a service. Service is related to Service Attribute, Service Exception, Service Question, Service Question Defined Response, Retailer Service, Retailer Service Equipment, and Project Service.</description>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/classes/AttachmentUrlGeneratorTest.cls
@isTest
public class AttachmentUrlGeneratorTest implements HttpCalloutMock{
    
    private HttpResponse resp;
    
     public AttachmentUrlGeneratorTest(String testBody) {
        resp = new HttpResponse();
        resp.setBody(testBody);
        resp.setStatusCode(200);
    }

    @testSetup static void setup(){
        TestUtil.initBaseData();
        TestUtil.generateFullTestProject(ProjectType.MD, Date.today().addDays(10), Date.today().addDays(20));
    }
    
    public static testMethod void test_generateUrl(){
        
        Project__c project = (Project__c) TestUtil.getRecord('Project__c');
        String userSessionId = '00Dj0000001uLTs!ARgAQP128DkA0MNmhkVUKXG0Mg7_WZeRk.fHtzWA.fgFB0Qys2ly4k38xAekIgwTjzUl188npXUw.ykGzV94oeV0gMxKzU5O ';
        
        ProjectService__c ps = [SELECT Id,Service__c FROM ProjectService__c LIMIT 1];
        String url = '/services/apexrest/generateAttachmentUrl/'+project.Id;
        System.debug(userSessionId);

        RestRequest req = new RestRequest(); 
		RestResponse res = new RestResponse();

		req.requestURI = System.URL.getSalesforceBaseURL()+'/services/apexrest/generateAttachmentUrl/'+project.Id;  
		req.httpMethod = 'GET';
		RestContext.request = req;
		RestContext.response = res;

		AttachmentURLGenerator.GenerateURL();

		System.assertEquals(201, res.statusCode);
		System.assertEquals(null, String.valueof(res.responseBody));
        
        
        try{
            test.startTest();
            HttpCalloutMock mock = new AttachmentUrlGeneratorTest('This is a test');

        	Test.setMock(HttpCalloutMock.class, mock);

            test.stopTest();
        }
        catch(Exception e){
        	System.debug(e.getMessage());
        }

    }


    public static testMethod void test_generateJobManualUrl(){
        
        Project__c project = (Project__c) TestUtil.getRecord('Project__c');
        String userSessionId = '00Dj0000001uLTs!ARgAQP128DkA0MNmhkVUKXG0Mg7_WZeRk.fHtzWA.fgFB0Qys2ly4k38xAekIgwTjzUl188npXUw.ykGzV94oeV0gMxKzU5O ';
        
        ProjectService__c ps = [SELECT Id,Service__c FROM ProjectService__c LIMIT 1];
        String psID = ps.Id;
        String url = '/services/apexrest/generateAttachmentUrl/'+project.Id;
        ps.JobManualURL__c = url;
        
        update ps;
        
        attribute__c attr = new attribute__c(Active__c=true,
                                             AttributeType__c = 'Job Manual');
        insert attr;
        System.debug(userSessionId);

        RestRequest req = new RestRequest(); 
		RestResponse res = new RestResponse();

		req.requestURI = System.URL.getSalesforceBaseURL()+'/services/apexrest/generateAttachmentUrl/'+project.Id;  
		req.httpMethod = 'GET';
		RestContext.request = req;
		RestContext.response = res;

		AttachmentURLGenerator.GenerateURL();

		//System.assertEquals(null, res.statusCode);
		//System.assertEquals(null, String.valueof(res.responseBody));
        
        
        try{
            test.startTest();
            HttpCalloutMock mock = new AttachmentUrlGeneratorTest('This is a test');

        	Test.setMock(HttpCalloutMock.class, mock);

            test.stopTest();
        }
        catch(Exception e){
        	System.debug(e.getMessage());
        }

    }
    
    public HTTPResponse respond(HTTPRequest req) {
        return resp;
    }

}