src_old/objects/Attribute__c.object
<CustomObject>
    <description>Attribute defines an attribute and includes a type definition (e.g. Picklist, Yes/No, Text, Multiple Choice, etc.), description, and other default values. Attributes are related to a Service Attribute and a Project Service Attribute.</description>
    <fields>
        <fullName>AttributeType__c</fullName>
        <description>A picklist with that determines the type of Attribute.</description>
        <inlineHelpText>Choose the type of attribute.</inlineHelpText>
        <label>AttributeType</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Text</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Yes/No</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Single-Select List</fullName>
                </value>
                <value>
                    <fullName>Multi-Select List</fullName>
                </value>
                <value>
                    <fullName>Photo</fullName>
                </value>
                <value>
                    <fullName>File</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Attribute</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Attribute Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attributes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ProjectService__c.object
<CustomObject>
    <description>Project Service relates a Service to a Project and is a container used to define the instance of a Service for a specific Project. Project Service is related to Project, Job, Project Service Attribute, Project Service Certification, Project Service Equipment, Project Service Material, Project Service Question, Project Service Target, and Service.</description>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>ProjectServices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>Project Services</relationshipLabel>
        <relationshipName>ProjectServices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TargetType__c</fullName>
        <label>Target Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Project Service</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectServiceAttribute__c.object
<CustomObject>
    <description>Relates a Service Attribute to a Project Service and prepopulates default values. Service Attribute is related to Service, Project Service Attribute, and Attribute.</description>
    <fields>
        <fullName>AttributeType__c</fullName>
        <formula>TEXT(Attribute__r.AttributeType__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AttributeType</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AttributeValue__c</fullName>
        <label>Attribute Value</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Attribute__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Attribute</label>
        <referenceTo>Attribute__c</referenceTo>
        <relationshipLabel>Project Service Attributes</relationshipLabel>
        <relationshipName>Project_Service_Attributes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectService__c</fullName>
        <label>Project Service</label>
        <referenceTo>ProjectService__c</referenceTo>
        <relationshipLabel>Project Service Attributes</relationshipLabel>
        <relationshipName>Project_Service_Attributes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>Project Service Attributes</relationshipLabel>
        <relationshipName>Project_Service_Attributes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Service Attribute</label>
    <nameField>
        <displayFormat>PSA-{00000000}</displayFormat>
        <label>Project Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Service Attributes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectServiceTarget__c.object
<CustomObject>
    <description>Relates a Target to a Project Service. Targets are manually added when building a Project. Project Service Target related to Project Service, Target, and Account.</description>
    <fields>
        <fullName>IsDonated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Donated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Price</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ProjectService__c</fullName>
        <label>Project Service</label>
        <referenceTo>ProjectService__c</referenceTo>
        <relationshipLabel>Project Service Target</relationshipLabel>
        <relationshipName>ProjectServiceTargets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Service Target</relationshipLabel>
        <relationshipName>Project_Service_Target</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Quantity</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Target__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Target</label>
        <referenceTo>Target__c</referenceTo>
        <relationshipLabel>Project Service Target</relationshipLabel>
        <relationshipName>ServiceTargets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Primary</fullName>
                </value>
                <value>
                    <fullName>Secondary</fullName>
                </value>
                <value>
                    <fullName>Ingredients</fullName>
                </value>
                <value>
                    <fullName>Analytics</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>YieldPerUnit__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Yield Per Unit</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Project Service Target</label>
    <nameField>
        <displayFormat>SC-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Service Target</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/Service__c.object
<CustomObject>
    <description>Service contains the definition of a service. Service is related to Service Attribute, Service Exception, Service Question, Service Question Defined Response, Retailer Service, Retailer Service Equipment, and Project Service.</description>
    <fields>
        <fullName>TargetType__c</fullName>
        <label>Target Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Product</fullName>
                    <default>true</default>
                    <label>Product</label>
                </value>
                <value>
                    <fullName>Category</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/Target__c.object
<CustomObject>
    <description>Target defines what a Worker will observe and answer questions about. Targets could include Products, Categories, Displays, or any other type of Target configured for an instance. Target is related to Project Service Target and Retailer.</description>
    <fields>
        <fullName>DepartmentName__c</fullName>
        <label>Department Name</label>
        <length>140</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PackageSizeQty__c</fullName>
        <label>Yield Per Unit</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PackageSizeUnits__c</fullName>
        <label>Package Size (Units)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>count</fullName>
                </value>
                <value>
                    <fullName>lb</fullName>
                </value>
                <value>
                    <fullName>oz</fullName>
                </value>
                <value>
                    <fullName>pint</fullName>
                </value>
                <value>
                    <fullName>gallon</fullName>
                </value>
                <value>
                    <fullName>quart</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>StockCode__c</fullName>
        <externalId>true</externalId>
        <label>Stock ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>TargetType__c</fullName>
        <label>Target Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Product</fullName>
                </value>
                <value>
                    <fullName>Category</fullName>
                </value>
                <value>
                    <fullName>Sam&apos;s Club</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UPC__c</fullName>
        <label>UPC</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Target</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Targets</pluralLabel>
    <recordTypes>
        <fullName>Product</fullName>
        <active>true</active>
        <label>Product</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/ProjectServiceTargetsAddExtTest.cls
@isTest
public class ProjectServiceTargetsAddExtTest {
    public static testMethod void genericTest(){ 
        Project__c project = TestUtil.generateFullTestProject(ProjectType.MD, System.today().addDays(60), System.today().addDays(70));
        ProjectService__c ps  = [SELECT Id,Service__c FROM ProjectService__c LIMIT 1];
        ApexPages.currentPage().getParameters().put('Id', ps.Id);
        
        ApexPages.StandardController controller = new ApexPages.StandardController(new ProjectService__c());        
        ProjectServiceTargetsAddExt ctrl = new ProjectServiceTargetsAddExt(controller); 
        ctrl.projectid =  project.id;
        ctrl.QtyParam=0;
        ctrl.tempHeader = new string[]{};
        ctrl.ServiceObj = [select id from service__c limit 1];
        
        
        
        Target__c coll = new Target__c();
        coll.Name = 'CHEF SHAMY - Garlic Butter';
        coll.Targettype__c= 'Product';
        coll.DepartmentName__c = 'Dairy';
        coll.PackageSizeQty__c = 1;
        coll.PackageSizeUnits__c= 'oz';
        coll.StockCode__c = TestUtil.generateRandomString(8);
        coll.upc__c = TestUtil.generateRandomString(12);
        //coll.Type__c = 'Primary';
        insert coll;
        
        
        ProjectServiceTarget__c psc = new ProjectServiceTarget__c();
        psc.ProjectService__c = ps.Id;
        psc.Quantity__c = 0;
        psc.Price__c = 0;
        psc.YieldPerUnit__c = 0;
        psc.IsDonated__c = false;
        psc.Target__c = coll.Id;
        ctrl.psc = psc;
        ctrl.SelectedType = 'Primary';
        PageReference pageref = ctrl.AddProduct();
        
        
        List<Attribute__c> attributes = [Select Id, Name, AttributeType__c from Attribute__c LIMIT 5];
        
        ProjectServiceAttribute__c psca = new ProjectServiceAttribute__c();
        psca.Attribute__c = attributes[0].id;
        psca.AttributeValue__c   = '';
        
        psca.ProjectService__c =ps.id;
        psca.Service__c= ps.Service__c;
        insert psca;
        
        //system.assertEquals(pageref,null);
    } 
    
    public static testMethod void genericTest_Delete(){ 
        Project__c project = TestUtil.generateFullTestProject(ProjectType.MD, System.today().addDays(60), System.today().addDays(70));
        ProjectService__c ps  = [SELECT Id,Service__c FROM ProjectService__c LIMIT 1];
        ApexPages.currentPage().getParameters().put('Id', ps.Id);
        
        ApexPages.StandardController controller = new ApexPages.StandardController(new ProjectService__c());        
        ProjectServiceTargetsAddExt ctrl = new ProjectServiceTargetsAddExt(controller); 
        ctrl.projectid =  project.id;
        ctrl.QtyParam=0;
        ctrl.tempHeader = new string[]{};
        ctrl.ServiceObj = [select id from service__c limit 1];
        /*
        
        
        Target__c coll = new Target__c();
        coll.Name = 'CHEF SHAMY - Garlic Butter';
        coll.Targettype__c= 'Product';
        coll.DepartmentName__c = 'Dairy';
        coll.PackageSizeQty__c = 1;
        coll.PackageSizeUnits__c= 'oz';
        coll.StockCode__c = TestUtil.generateRandomString(8);
        coll.upc__c = TestUtil.generateRandomString(12);
        //coll.Type__c = 'Primary';
        insert coll;
        
        
        ProjectServiceTarget__c psc = new ProjectServiceTarget__c();
        psc.ProjectService__c = ps.Id;
        psc.Quantity__c = 0;
        psc.Price__c = 0;
        psc.YieldPerUnit__c = 0;
        psc.IsDonated__c = false;
        psc.Target__c = coll.Id;
        psc.Type__c = 'Primary';
        insert psc;
        
        ctrl.psc = psc;
        ctrl.SelectedType = 'Primary';
        
        psc = new ProjectServiceTarget__c();
        psc.ProjectService__c = ps.Id;
        psc.Quantity__c = 0;
        psc.Price__c = 0;
        psc.YieldPerUnit__c = 0;
        psc.IsDonated__c = false;
        psc.Target__c = coll.Id;
        psc.Type__c = 'Backup';
        insert psc;
        
        psc = new ProjectServiceTarget__c();
        psc.ProjectService__c = ps.Id;
        psc.Quantity__c = 0;
        psc.Price__c = 0;
        psc.YieldPerUnit__c = 0;
        psc.IsDonated__c = false;
        psc.Target__c = coll.Id;
        psc.Type__c = 'Halo';
        insert psc;
        
        List<Attribute__c> attributes = [Select Id, Name, AttributeType__c from Attribute__c LIMIT 5];
        
        ProjectServiceAttribute__c psca = new ProjectServiceAttribute__c();
        psca.Attribute__c = attributes[0].id;
        psca.AttributeValue__c   = '';
        
        psca.ProjectService__c =ps.id;
        psca.Service__c= ps.Service__c;
        insert psca;
        
        
        Test.startTest();
       
        ApexPages.currentPage().getParameters().put('pscParamDEL', psc.Id);
        ApexPages.currentPage().getParameters().put('Oper', 'Primary');
        pagereference pageref = ctrl.SaveAllChanges();
        pageref = ctrl.DeleteProducts();

        

        ApexPages.currentPage().getParameters().put('pscParamDEL', psc.Id);
        ApexPages.currentPage().getParameters().put('Oper', 'Backup');
        pageref = ctrl.SaveAllChanges();        
        pageref = ctrl.DeleteProducts();

        ApexPages.currentPage().getParameters().put('pscParamDEL', psc.Id);
        ApexPages.currentPage().getParameters().put('Oper', 'Halo');
        pageref = ctrl.SaveAllChanges();        
        pageref = ctrl.DeleteProducts();
        Test.stopTest();
        */
        
    }
}