src_old/objects/Attribute__c.object
<CustomObject>
    <description>Attribute defines an attribute and includes a type definition (e.g. Picklist, Yes/No, Text, Multiple Choice, etc.), description, and other default values. Attributes are related to a Service Attribute and a Project Service Attribute.</description>
    <fields>
        <fullName>AttributeTitle__c</fullName>
        <description>An entry field for the title of the Attribute.</description>
        <inlineHelpText>Enter the title of the attribute.</inlineHelpText>
        <label>Attribute Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AttributeType__c</fullName>
        <description>A picklist with that determines the type of Attribute.</description>
        <inlineHelpText>Choose the type of attribute.</inlineHelpText>
        <label>AttributeType</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Text</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Yes/No</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Single-Select List</fullName>
                </value>
                <value>
                    <fullName>Multi-Select List</fullName>
                </value>
                <value>
                    <fullName>Photo</fullName>
                </value>
                <value>
                    <fullName>File</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Attribute</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Attribute Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attributes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/objects/ServiceAttribute__c.object
<CustomObject>
    <description>Service Attribute relates one or more Attributes to a Service. Service Attribute is related to Service, Attribute, and Project Service Attribute.</description>
    <fields>
        <fullName>AttributeOrder__c</fullName>
        <label>Attribute Order</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AttributeTitle__c</fullName>
        <formula>Attribute__r.AttributeTitle__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Attribute Title</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AttributeType__c</fullName>
        <formula>TEXT(Attribute__r.AttributeType__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Attribute Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attribute__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Attribute</label>
        <referenceTo>Attribute__c</referenceTo>
        <relationshipLabel>Service Attributes</relationshipLabel>
        <relationshipName>Service_Attributes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Attribute</label>
    <nameField>
        <displayFormat>SA-{00000000}</displayFormat>
        <label>Service Attribute Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Attributes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AttributeWrapper.cls
public class AttributeWrapper
{
    public String   name                {get; set;}
    public String   id                  {get; set;}
    public String   attributeName       {get; set;}
    public String   attributeValue      {get; set;}
    public String   attributeType       {get; set;}    
    public String   renderFreeText      {get; set;}
    public String   renderNumber        {get; set;}
    public String  renderFile          {get; set;}      
    public boolean  isVisible           {get; set;}
    public String imageName             {get; set;}  
    transient public Blob imageBody     {get; set;}  
    public Integer attributeOrder       {get; set;}
    public String attachmentId {get;set;}
    public String imageFlag {get;set;}    
    public boolean showChooseFile {
        get {
            return String.isNotBlank(this.attachmentId) ? false : true;
        }
    }
    public boolean isImage {
        get {
            return AttachmentAnalyzer.isImage(this.id, this.imageName, this.attributeType);
        }
    }

    public Boolean isAttachment {
        get {
            return AttachmentAnalyzer.isFile(this.id, this.attributeType);
        }
    }

    private void init(){
        renderFreeText='false';
        renderNumber='false';        
        imageFlag = '0';
        attachmentId = '';
        renderFile = 'false';
    }
    
    private AttributeWrapper() { }
    

    public void flushValue() {
        this.attributeValue = '';
        this.attachmentId = '';
        this.imageName = '';
    }

    public static AttributeWrapper newInstance(ServiceAttribute__c sa, String pattributeValue) {
        return new AttributeWrapper(sa, pattributeValue);
    }

    private AttributeWrapper(ServiceAttribute__c sa, String pattributeValue) 
    {
        init();

        name = sa.AttributeTitle__c;
        id = sa.Attribute__c;
        attributeValue = String.isNotBlank(pattributeValue) ? pattributeValue : '';
        attributeName =  sa.AttributeTitle__c;
        attributeType = sa.AttributeType__c;
        attributeOrder = Integer.ValueOf(sa.AttributeOrder__c);

        if (attributeType=='Text'){
             renderFreeText='true';
        }
        else if (attributeType=='Number'){
             renderNumber='true';
        }
        else if (attributeType=='Photo'){
             assignAttachment(attributeValue);
        } else if (attributeType=='File') {
            assignAttachment(attributeValue);
        }
    }

    
    private void assignAttachment(String attrValue) {
        renderFile= 'true';
        String[] arr = parseValue(attributeValue);
        imageFlag = arr[1];
        String id = arr[0];
        if (String.isNotBlank(id)){
            List<Attachment> atts = [SELECT Id, Name FROM Attachment WHERE Id=:id LIMIT 1];
            if (atts.size() > 0) {
                attachmentId = atts[0].Id;
                imageName = atts[0].Name;
            }
        }
    }
     
    private String[] parseValue(String attrValue) {
        String[] res = new String[2];
        if (String.isNotBlank(attrValue)) {
            String[] arr = attrValue.split('=');
            res[0] = arr[0];
            res[1] = arr.size() == 2 ? arr[1] : '0';
        } else {
            res[0] = '';
            res[1] = '0';
        }
        return res;
    }
}