src_old/objects/Attribute__c.object
<CustomObject>
    <description>Attribute defines an attribute and includes a type definition (e.g. Picklist, Yes/No, Text, Multiple Choice, etc.), description, and other default values. Attributes are related to a Service Attribute and a Project Service Attribute.</description>
    <label>Attribute</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Attribute Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attributes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/objects/ProjectType__c.object
<CustomObject>
    <description>Project Type defines a collection of Services and sets configuration options for a Project. Project Type is related to Project, Project Type Execution Company, Project Type Service, and Location Assignment.</description>
    <label>Project Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Types</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ProjectTypeAttribute__c.object
<CustomObject>
    <description>Define a list of attributes that the project of different type captures</description>
    <fields>
        <fullName>Attribute__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Attribute</label>
        <referenceTo>Attribute__c</referenceTo>
        <relationshipLabel>Project Type attributes</relationshipLabel>
        <relationshipName>Project_Type_attributes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsVisible__c</fullName>
        <defaultValue>false</defaultValue>
        <description>determine if this attribute is visible or not</description>
        <inlineHelpText>Determine if this attribute is visible or not</inlineHelpText>
        <label>IsVisible</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProjectType__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project Type</label>
        <referenceTo>ProjectType__c</referenceTo>
        <relationshipLabel>Project Type attributes</relationshipLabel>
        <relationshipName>Project_Type_attributes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>isActive</label>
        <type>Checkbox</type>
    </fields>
    <label>Project Type attribute</label>
    <nameField>
        <displayFormat>PTA-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Type attributes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/classes/ProjectTypeHelper.cls
public with sharing class ProjectTypeHelper {
  Map<Id, ProjectTypeAttribute__c> PTAttributes{get;set;}

	public ProjectTypeHelper(Id projectTypeId) {
	      PTAttributes = new Map<Id, ProjectTypeAttribute__c>();
        List<ProjectTypeAttribute__c> ptAttrs = [SELECT Attribute__c, IsVisible__c FROM ProjectTypeAttribute__c WHERE ProjectType__c=:projectTypeId AND IsActive__c=true];
        for(ProjectTypeAttribute__c attr: ptAttrs){
            PTAttributes.put(attr.Attribute__c, attr);
        }
  }

  public Boolean IsAttributeVisible(Id attributeId){
    if (!PTAttributes.containsKey(attributeId)) {
      return false;
    }
    ProjectTypeAttribute__c ptAttr = PTAttributes.get(attributeId);
    return Boolean.valueOf(ptAttr.IsVisible__c);
  }
}