src_old/objects/Attribute__c.object
<CustomObject>
    <description>Attribute defines an attribute and includes a type definition (e.g. Picklist, Yes/No, Text, Multiple Choice, etc.), description, and other default values. Attributes are related to a Service Attribute and a Project Service Attribute.</description>
    <fields>
        <fullName>AttributeType__c</fullName>
        <description>A picklist with that determines the type of Attribute.</description>
        <inlineHelpText>Choose the type of attribute.</inlineHelpText>
        <label>AttributeType</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Text</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Yes/No</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Single-Select List</fullName>
                </value>
                <value>
                    <fullName>Multi-Select List</fullName>
                </value>
                <value>
                    <fullName>Photo</fullName>
                </value>
                <value>
                    <fullName>File</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Attribute</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Attribute Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attributes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ProjectAttribute__c.object
<CustomObject>
    <fields>
        <fullName>AttributeDescription__c</fullName>
        <formula>Attribute__r.Description__c</formula>
        <label>AttributeDescription</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AttributeName__c</fullName>
        <formula>Attribute__r.AttributeTitle__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AttributeName</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AttributeType__c</fullName>
        <formula>TEXT(Attribute__r.AttributeType__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AttributeType</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AttributeValue__c</fullName>
        <label>AttributeValue</label>
        <length>100000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Attribute__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Attribute</label>
        <referenceTo>Attribute__c</referenceTo>
        <relationshipLabel>Project Attributes</relationshipLabel>
        <relationshipName>Project_Attributes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsRequired__c</fullName>
        <formula>ProjectTypeAttribute__r.IsRequired__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>IsRequired</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProjectTypeAttribute__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project Type attribute</label>
        <referenceTo>ProjectTypeAttribute__c</referenceTo>
        <relationshipLabel>Project Attributes</relationshipLabel>
        <relationshipName>Project_Attributes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Attributes</relationshipLabel>
        <relationshipName>Project_Attributes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Attribute</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Project Attribute Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Attributes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectTypeAttribute__c.object
<CustomObject>
    <description>Define a list of attributes that the project of different type captures</description>
    <fields>
        <fullName>AttributeName__c</fullName>
        <formula>Attribute__r.AttributeTitle__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AttributeName</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AttributeType__c</fullName>
        <formula>TEXT(Attribute__r.AttributeType__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AttributeType</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AttributeValue__c</fullName>
        <description>Default attribute value</description>
        <inlineHelpText>Default attribute value</inlineHelpText>
        <label>AttributeValue</label>
        <length>100000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Attribute__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Attribute</label>
        <referenceTo>Attribute__c</referenceTo>
        <relationshipLabel>Project Type attributes</relationshipLabel>
        <relationshipName>Project_Type_attributes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsRequired</label>
        <type>Checkbox</type>
    </fields>
    <label>Project Type attribute</label>
    <nameField>
        <displayFormat>PTA-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Type attributes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/classes/ProjectAttributeWrapper.cls
public class ProjectAttributeWrapper {
    @AuraEnabled
    public string RecordID{get; set;}     
    @AuraEnabled
    public id Project{get; set;}
    @AuraEnabled
    public id Attribute{get; set;}
    @AuraEnabled
    public string AttributeValue{get; set;}    
    @AuraEnabled
    public string AttributeType{get; set;}    
    @AuraEnabled
    public id  ProjectTypeAttribute {get; set;} 
    @AuraEnabled
    public string  AttributeName {get; set;} 
    @AuraEnabled
    public string  AttributeDescription {get; set;} 
    @AuraEnabled
    public boolean  isRequired {get; set;}     
    @AuraEnabled
    public boolean  isReadOnly {get; set;}     
    @AuraEnabled
    public string  DefaultValue {get; set;}         
    @AuraEnabled
    public Id  DefaultDefinedReferenceValue {get; set;}         
    
    @AuraEnabled    
    public list<AttributeDefinedResponseWrapper>  ResponsesList {get; set;} 
    
    
    public ProjectAttributeWrapper(){}

    public ProjectAttributeWrapper(ProjectAttribute__c psa)
    {
        RecordID = psa.ID;
        Project = psa.Project__c;
        Attribute= psa.Attribute__c;
        AttributeValue = (psa.AttributeValue__c != null) ? htmlDecode(psa.AttributeValue__c) : ''; 
        AttributeType = psa.AttributeType__c;
        AttributeName =psa.AttributeName__c;
        isRequired = psa.IsRequired__c;
        ProjectTypeAttribute = psa.ProjectTypeAttribute__c;        
        AttributeDescription = psa.AttributeDescription__c;
    }
    public static String htmlDecode (String s) {  

    Map<String, String> htmlDecodingMap = new Map<String, String>();
    htmlDecodingMap.put('&lt;', '<');
    htmlDecodingMap.put('&gt;', '>');
    htmlDecodingMap.put('&amp;quot;', '"');
    htmlDecodingMap.put('&amp;', '&');
    htmlDecodingMap.put('&#39;', '\'');

    for (String token : htmlDecodingMap.keySet()) {
        s = s.replace(token, htmlDecodingMap.get(token));
    }
    return s;
}
    
}