src_old/objects/AttributeDefinedResponse__c.object
<CustomObject>
    <fields>
        <fullName>DefinedResponse__c</fullName>
        <label>Defined Response</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Indicates if the attribute response is active or inactive</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Attribute Defined Response</label>
    <nameField>
        <displayFormat>ADR-{00000}</displayFormat>
        <label>AttributeDefinedResponse Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AttributeDefinedResponse</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/AttributeDefinedResponseWrapper.cls
public class AttributeDefinedResponseWrapper {
    @AuraEnabled
    public id responseID {get; set;}   
    @AuraEnabled
    public String responseValue {get; set;}       
    @AuraEnabled
    public boolean isActive{get; set;}   
    
    public AttributeDefinedResponseWrapper(){}
    
    public AttributeDefinedResponseWrapper(Id objID, String objVal, Boolean objAct){
        responseID=objID;
        responseValue =objVal;
        isActive= objAct;
    }
    
    public AttributeDefinedResponseWrapper(AttributeDefinedResponse__c obj){               
       responseID =  obj.id;
       responseValue = htmlDecode(string.valueOf(obj.DefinedResponse__c));
       isActive =  obj.IsActive__c;
    }
     public static String htmlDecode (String s) {  

    Map<String, String> htmlDecodingMap = new Map<String, String>();
    htmlDecodingMap.put('&lt;', '<');
    htmlDecodingMap.put('&gt;', '>');
    htmlDecodingMap.put('&amp;quot;', '"');
    htmlDecodingMap.put('&amp;', '&');
    htmlDecodingMap.put('&#39;', '\'');
    
   for (String token : htmlDecodingMap.keySet()) {
        s = s.replace(token, htmlDecodingMap.get(token));
    }
    return s;
}
}