src_old/objects/Certification__c.object
<CustomObject>
    <description>Certification defines the standard list of certifications. Certifications are related to a Project Service Certification and a Retailer Service Certification.</description>
    <label>Certification</label>
    <nameField>
        <label>Certification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/objects/ProjectService__c.object
<CustomObject>
    <description>Project Service relates a Service to a Project and is a container used to define the instance of a Service for a specific Project. Project Service is related to Project, Job, Project Service Attribute, Project Service Certification, Project Service Equipment, Project Service Material, Project Service Question, Project Service Target, and Service.</description>
    <label>Project Service</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectServiceCertification__c.object
<CustomObject>
    <description>Relates a Certification to a Project Service. Certifications from Retailer Service Certification are added by default when a Service is added to a Project Service. Additional Certifications can be added. Project Service Certification is related to Certification and Project Service.</description>
    <fields>
        <fullName>Certification__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Certification</label>
        <referenceTo>Certification__c</referenceTo>
        <relationshipLabel>Project Service Certifications</relationshipLabel>
        <relationshipName>Project_Service_Certifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsLocked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsLocked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProjectService__c</fullName>
        <label>Project Service</label>
        <referenceTo>ProjectService__c</referenceTo>
        <relationshipLabel>Project Service Certifications</relationshipLabel>
        <relationshipName>ProjectServiceCertifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Service Certification</label>
    <nameField>
        <displayFormat>PSCERT-{000000000}</displayFormat>
        <label>Project Service Certification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Service Certifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/LightningPSCertificationController.cls
public class LightningPSCertificationController {
    @AuraEnabled
    public static PSCertViewModalWrapper GetPSCertifications(String projectServiceId) {
        PSCertViewModalWrapper pscWrapper;
        try{
            String pscQuery = QueryUtil.FetchQuery('ProjectServiceCertification__c') + ' WHERE ProjectService__c= \'' + projectServiceId + '\' ORDER BY Name ';
            System.debug(' >>>>>>>>>>>>>>>>>> pscQuery >>>>>>>>>>>>>> ' + pscQuery);
            List<ProjectServiceCertification__c> selCertifications = Database.query(pscQuery);    
            if(selCertifications==null)
                selCertifications= new  List<ProjectServiceCertification__c>();
            
            set<id> ExistingCertIDs = new set<id>();
            for(ProjectServiceCertification__c psc : selCertifications){
                ExistingCertIDs.add(psc.Certification__c);
            }
            
            
            
            String certQuery = QueryUtil.FetchQuery('Certification__c');
            certQuery += ' where id not IN : ExistingCertIDs order by name ';
            System.debug(' >>>>>>>>>>>>>>>>>> certQuery >>>>>>>>>>>>>> ' + certQuery);
            List<Certification__c> avlCertifications  = Database.query(certQuery); 
            
            
            System.debug(' >>>>>>>>>>>>>>>>>>avlCertifications >>>>>>>>>>>>>> ' + avlCertifications);
            if(avlCertifications==null)
                avlCertifications= new  List<Certification__c>();
            
            pscWrapper = new PSCertViewModalWrapper(avlCertifications,selCertifications);
            
        }
        catch(exception ex){
            pscWrapper= new PSCertViewModalWrapper();
            pscWrapper.isSuccess = false;
			pscWrapper.message = ex.getMessage();
        }
        return pscWrapper;
    }
    
    @AuraEnabled
    public static String getNamespaceApex() {
        return CONSTANTS.CURRENTNAMESPACEPREFIX;
    }        
        
    
    @AuraEnabled
    public static PSCertViewModalWrapper SavePSCertifications(String projectServiceId,string cert) {
        PSCertViewModalWrapper pscWrapper;
        try{
            ProjectServiceCertification__c psc = new ProjectServiceCertification__c();
            psc.ProjectService__c = projectServiceId;
            psc.Certification__c = cert;
            psc.IsLocked__c = false;
            insert psc; 
            pscWrapper = GetPSCertifications(projectServiceId);
            pscWrapper.message = 'Certification successfully Added !!';
        }
        catch(exception ex){
            pscWrapper= new PSCertViewModalWrapper();
            pscWrapper.isSuccess = false;
			pscWrapper.message = ex.getMessage();
        }
        return pscWrapper;
    }
    
    @AuraEnabled
    public static PSCertViewModalWrapper DeletePSCertifications(String pscID,string psID) {
        PSCertViewModalWrapper pscWrapper;
        try{
            String query = 'SELECT id from ProjectServicecertification__c where id = \'' + pscID + '\'';
            list<ProjectServicecertification__c> returnVals = Database.query(query);
            system.debug('~~~'+returnVals);
            delete returnVals;
            pscWrapper = GetPSCertifications(psID);
            pscWrapper.message = 'Certification successfully Deleted!!';
        }
        catch(exception ex){
            pscWrapper= new PSCertViewModalWrapper();
            pscWrapper.isSuccess = false;
            pscWrapper.message = ex.getMessage();
        }
        return pscWrapper;
    }
}