src_old/objects/Certification__c.object
<CustomObject>
    <description>Certification defines the standard list of certifications. Certifications are related to a Project Service Certification and a Retailer Service Certification.</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <label>Certification</label>
    <nameField>
        <label>Certification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/classes/CertificationWrapper.cls
public class CertificationWrapper {
  	@AuraEnabled
    public string RecordID{get; set;}     
    @AuraEnabled
    public string Name{get; set;}
    @AuraEnabled
    public string Description{get; set;}
    
    public CertificationWrapper(){        
    }

    public CertificationWrapper(Certification__c cert){
        RecordID=cert.id;
        Name= cert.Name;
        Description = cert.Description__c;
    }
}