src_old/objects/Certification__c.object
<CustomObject>
    <description>Certification defines the standard list of certifications. Certifications are related to a Project Service Certification and a Retailer Service Certification.</description>
    <label>Certification</label>
    <nameField>
        <label>Certification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/objects/ProjectServiceCertification__c.object
<CustomObject>
    <description>Relates a Certification to a Project Service. Certifications from Retailer Service Certification are added by default when a Service is added to a Project Service. Additional Certifications can be added. Project Service Certification is related to Certification and Project Service.</description>
    <fields>
        <fullName>Certification__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Certification</label>
        <referenceTo>Certification__c</referenceTo>
        <relationshipLabel>Project Service Certifications</relationshipLabel>
        <relationshipName>Project_Service_Certifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Service Certification</label>
    <nameField>
        <displayFormat>PSCERT-{000000000}</displayFormat>
        <label>Project Service Certification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Service Certifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/PSCertViewModalWrapper.cls
public class PSCertViewModalWrapper {
    @AuraEnabled
    public list<CertificationWrapper> AvailableCerts{get; set;}
    @AuraEnabled
    public list<ProjServCertificationWrapper> SelectedCerts{get; set;}
    @AuraEnabled
    public boolean isSuccess{get; set;}
    @AuraEnabled
    public string message{get; set;}
    
        
    public PSCertViewModalWrapper(){          
    }
    
    public PSCertViewModalWrapper(list<Certification__c> avlCertifications, list<ProjectServiceCertification__c> selCertifications){  
        try{
            system.debug('____inside wrapper _______'+avlCertifications+'____selCertifications_______'+selCertifications );
            AvailableCerts=new list<CertificationWrapper>();
            SelectedCerts=new list<ProjServCertificationWrapper>();
            
            if(avlCertifications!=null){
                for(Certification__c cert:avlCertifications){
                    AvailableCerts.add(new CertificationWrapper(cert));
                }
            }
            
            if(selCertifications!=null){
                for(ProjectServiceCertification__c cert:selCertifications){
                    SelectedCerts.add(new ProjServCertificationWrapper(cert));
                }                
            }
            isSuccess=true;
            message = 'Data loaded successfully !!';
        }
        catch(exception ex){
		    isSuccess=false;
            message = 'Data load failed. Please contact support team.';            
        }
    }
}