src_old/objects/Certification__c.object
<CustomObject>
    <description>Certification defines the standard list of certifications. Certifications are related to a Project Service Certification and a Retailer Service Certification.</description>
    <label>Certification</label>
    <nameField>
        <label>Certification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <fields>
        <fullName>IsLocked__c</fullName>
        <defaultValue>false</defaultValue>
        <description>A checkbox that indicates that the Project is locked</description>
        <inlineHelpText>If selected, the project is locked.</inlineHelpText>
        <label>Is Locked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Retailer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Retailer</label>
        <referenceTo>Retailer__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planning</fullName>
                    <default>true</default>
                    <label>Planning</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Launched</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ended</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ProjectService__c.object
<CustomObject>
    <description>Project Service relates a Service to a Project and is a container used to define the instance of a Service for a specific Project. Project Service is related to Project, Job, Project Service Attribute, Project Service Certification, Project Service Equipment, Project Service Material, Project Service Question, Project Service Target, and Service.</description>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>ProjectServices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Retailer__c</fullName>
        <formula>Project__r.Retailer__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Retailer</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>Project Services</relationshipLabel>
        <relationshipName>ProjectServices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Executed</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project Service</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectServiceCertification__c.object
<CustomObject>
    <description>Relates a Certification to a Project Service. Certifications from Retailer Service Certification are added by default when a Service is added to a Project Service. Additional Certifications can be added. Project Service Certification is related to Certification and Project Service.</description>
    <fields>
        <fullName>Certification__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Certification</label>
        <referenceTo>Certification__c</referenceTo>
        <relationshipLabel>Project Service Certifications</relationshipLabel>
        <relationshipName>Project_Service_Certifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsLocked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsLocked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProjectService__c</fullName>
        <label>Project Service</label>
        <referenceTo>ProjectService__c</referenceTo>
        <relationshipLabel>Project Service Certifications</relationshipLabel>
        <relationshipName>ProjectServiceCertifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Service Certification</label>
    <nameField>
        <displayFormat>PSCERT-{000000000}</displayFormat>
        <label>Project Service Certification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Service Certifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/Retailer__c.object
<CustomObject>
    <description>Retailer stores the retailers for the system. Retailer is related to Location, Retailer Service, Retailer Service Certification, and Retailer Service Equipment.</description>
    <label>Retailer</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Retailers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/RetailerServiceCertification__c.object
<CustomObject>
    <description>Retailer Service Certification relates Certifications to a Retailer, which determines the Services that are available when building a Project Service. Retailer Service Certification is related to Retailer, Service, and Certification.</description>
    <fields>
        <fullName>Certification__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Certification</label>
        <referenceTo>Certification__c</referenceTo>
        <relationshipLabel>Retailer Service Certifications</relationshipLabel>
        <relationshipName>Retailer_Service_Certifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Retailer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Retailer</label>
        <referenceTo>Retailer__c</referenceTo>
        <relationshipLabel>Retailer Service Certifications</relationshipLabel>
        <relationshipName>Retailer_Service_Certifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>Retailer Service Certifications</relationshipLabel>
        <relationshipName>Retailer_Service_Certifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Retailer Service Certification</label>
    <nameField>
        <displayFormat>RSC-{000000000}</displayFormat>
        <label>Retailer Service Certification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retailer Service Certifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/objects/Service__c.object
<CustomObject>
    <description>Service contains the definition of a service. Service is related to Service Attribute, Service Exception, Service Question, Service Question Defined Response, Retailer Service, Retailer Service Equipment, and Project Service.</description>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/classes/ProjectServiceCertificationsEditExt.cls
public with sharing class ProjectServiceCertificationsEditExt {
    
    public ProjectService__c ps{get;set;}
    public List<ProjectServiceCertification__c> pscList {get;set;}
    public List<SelectOption> CertificationSelectOptions {get;set;}
    public string SelectedCertification{get;set;}
    public Boolean showAddButton{get;set;}
    public Map<String,Boolean> editableMap {get;set;}
    
    private void addMessage(ApexPages.Severity severity, String message){
        Apexpages.addMessage(new ApexPages.Message(severity, message));
    }

    public ProjectServiceCertificationsEditExt(ApexPages.StandardController controller) {
        ps = [SELECT Id, Name, Project__r.Retailer__c, Service__c FROM ProjectService__c where id =:ApexPages.CurrentPage().getParameters().get('id') ];
        loadCertification();
        CertificationSelectOptions = new List<SelectOption>();
        CertificationSelectOptions.add(new SelectOption('','-None-'));
        for(Certification__c ct : [SELECT Id, Name FROM Certification__c WHERE ID NOT IN (SELECT Certification__c FROM RetailerServiceCertification__c WHERE Retailer__c =: ps.Project__r.Retailer__c AND Service__c =: ps.Service__c)]){
            CertificationSelectOptions.add(new SelectOption(ct.Id, ct.Name));
        }
        
        Project__c proj = [SELECT Id, Status__c FROM Project__c WHERE Id IN (Select Project__c from ProjectService__c where Id = :ps.Id ) LIMIT 1];
        
        Set<String> editableFields = new Set<String>{'Project__c.RL_Certifications'};
        editableMap = UIConfig.isEditale(proj.Status__c, editableFields);
        showAddButton = editableMap.get('Project__c.RL_Certifications') && Schema.sObjectType.ProjectServiceCertification__c.isUpdateable();
    }
    
    public void loadCertification(){
        pscList = [SELECT Id, Certification__c, ProjectService__c, IsLocked__c FROM ProjectServiceCertification__c WHERE ProjectService__c =:ps.Id ORDER BY IsLocked__c DESC];
    }
    
    
    
    public PageReference addCertification() {
    if(String.isBlank(SelectedCertification)){
                Apexpages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Please select a certification.'));
                return null;
            }

        try {
           
            ProjectServiceCertification__c psc = new ProjectServiceCertification__c();
            psc.ProjectService__c = ps.Id;
            psc.Certification__c = SelectedCertification;
            psc.IsLocked__c = false;
            insert psc;
            loadCertification();
            SelectedCertification = '';
            addMessage(ApexPages.Severity.CONFIRM, 'Certification(s) saved successfully.');  
            return null;
        }
        catch(Exception e){
            if (e.getMessage().Contains('duplicate'))
            {
                addMessage(ApexPages.Severity.ERROR, 'This certification has already been added. Please check and try again.');
                return null;
            
            }
            addMessage(ApexPages.Severity.ERROR, e.getmessage());
            return null;
        }
    }
    
    public PageReference deleteCertification(){
        try {  
            string pscDelId = ApexPages.currentpage().getParameters().get('pscCertId');
            for (ProjectServiceCertification__c psc : pscList) {
                if (pscDelId == psc.Id) {
                    
                    delete psc;
                    break;
                }
            }
            addMessage(ApexPages.Severity.CONFIRM, 'Certification deleted.');
            loadCertification();
            SelectedCertification = '';
            return null;
        }
        catch(Exception e) {
            addMessage(ApexPages.Severity.ERROR, e.getmessage());
            return null;
        }
    }
    
}