src_old/objects/Certification__c.object
<CustomObject>
    <description>Certification defines the standard list of certifications. Certifications are related to a Project Service Certification and a Retailer Service Certification.</description>
    <label>Certification</label>
    <nameField>
        <label>Certification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/objects/ProjectService__c.object
<CustomObject>
    <description>Project Service relates a Service to a Project and is a container used to define the instance of a Service for a specific Project. Project Service is related to Project, Job, Project Service Attribute, Project Service Certification, Project Service Equipment, Project Service Material, Project Service Question, Project Service Target, and Service.</description>
    <label>Project Service</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectServiceCertification__c.object
<CustomObject>
    <description>Relates a Certification to a Project Service. Certifications from Retailer Service Certification are added by default when a Service is added to a Project Service. Additional Certifications can be added. Project Service Certification is related to Certification and Project Service.</description>
    <fields>
        <fullName>CertificationName__c</fullName>
        <formula>Certification__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CertificationName</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Certification__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Certification</label>
        <referenceTo>Certification__c</referenceTo>
        <relationshipLabel>Project Service Certifications</relationshipLabel>
        <relationshipName>Project_Service_Certifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsLocked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsLocked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProjectService__c</fullName>
        <label>Project Service</label>
        <referenceTo>ProjectService__c</referenceTo>
        <relationshipLabel>Project Service Certifications</relationshipLabel>
        <relationshipName>ProjectServiceCertifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Service Certification</label>
    <nameField>
        <displayFormat>PSCERT-{000000000}</displayFormat>
        <label>Project Service Certification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Service Certifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/ProjServCertificationWrapper.cls
public class ProjServCertificationWrapper {
  	@AuraEnabled
    public string RecordID{get; set;}     
    @AuraEnabled
    public string Name{get; set;}    
    @AuraEnabled
    public id ProjectServiceID{get; set;}
  	@AuraEnabled
    public string CertificationName{get; set;}     
    @AuraEnabled
    public id CertificationID{get; set;}    
    @AuraEnabled
    public boolean IsLocked{get; set;}   
    
    public ProjServCertificationWrapper(){        
    }

    public ProjServCertificationWrapper(ProjectServiceCertification__c cert){
        RecordID=cert.id;
        Name= cert.Name;
        ProjectServiceID=cert.ProjectService__c;
        CertificationName= cert.CertificationName__c;
        CertificationID= cert.Certification__c;
        IsLocked= cert.IsLocked__c;        
    }
}