src_old/objects/Cloudinary_Setting__mdt.object
<CustomObject>
    <fields>
        <fullName>API_Key__c</fullName>
        <defaultValue>&apos;356145325228672&apos;</defaultValue>
        <label>API Key</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cloud_Name__c</fullName>
        <defaultValue>&apos;www-onehub-crossmark-com&apos;</defaultValue>
        <label>Cloud Name</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <label>Cloudinary Setting</label>
    <pluralLabel>Cloudinary Settings</pluralLabel>
</CustomObject>

src_old/objects/Job__c.object
<CustomObject>
    <description>Job defines the body of work to be performed at a Location and all of the dates related to the Job performance. A Job is related to a Project, Project Service, Project Location, Job Material, Contact, Exception, and Job Attempt.</description>
    <fields>
        <fullName>LocationNumber__c</fullName>
        <description>The field that indicates the location number of the Job.</description>
        <formula>Location__r.LocationNumber__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The location number of the job</inlineHelpText>
        <label>Location #</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field that indicates the location of the Job.</description>
        <inlineHelpText>The location of the job</inlineHelpText>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectService__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field that indicates the Project Service.</description>
        <inlineHelpText>The project service number</inlineHelpText>
        <label>Project Service</label>
        <referenceTo>ProjectService__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field that indicates the name of the Project to which a Job belongs.</description>
        <inlineHelpText>The name of the project for this job</inlineHelpText>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ReportedContactFirstName__c</fullName>
        <description>The field that indicates the first name of the Reported Contact.</description>
        <formula>ActiveJobAttempt__r.ReportedContactFirstName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Reported Contact First Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ReportedContactId__c</fullName>
        <description>The field that indicates the ID number of the Reported Contact.</description>
        <formula>ActiveJobAttempt__r.ReportedContactId__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The ID number of the reported contact</inlineHelpText>
        <label>Reported  Contact ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ReportedContactLastName__c</fullName>
        <description>The field that indicates the last name of the Reported Contact.</description>
        <formula>ActiveJobAttempt__r.ReportedContactLastName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Reported Contact Last Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ReportedContactTitle__c</fullName>
        <description>The field that indicates the title of the Reported Contact.</description>
        <formula>ActiveJobAttempt__r.ReportedContactTitle__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The title of the reported contact</inlineHelpText>
        <label>Reported Contact Title</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ReportedEmployeeId__c</fullName>
        <description>The field that indicates the ID number of the Reported Employee.</description>
        <formula>ActiveJobAttempt__r.ReportedEmployeeId__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The ID number of the reported employee</inlineHelpText>
        <label>Reported Employee ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ServiceName__c</fullName>
        <description>The field that indicates the name of the Service for the Job.</description>
        <inlineHelpText>The name for the service</inlineHelpText>
        <label>ServiceName</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field that indicates the Service for the Job.</description>
        <inlineHelpText>The service for the job</inlineHelpText>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Job</label>
    <nameField>
        <displayFormat>JOB-{000000000}</displayFormat>
        <label>Job ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/Location__c.object
<CustomObject>
    <description>Location defines a location and its type, address, and the Retailer is it associated with. Location is related to Retailer, Job, and Project Location.</description>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LocationNumber__c</fullName>
        <label>Location Number</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PostalCode__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Postal Code</label>
        <referenceTo>PostalCode__c</referenceTo>
        <relationshipLabel>Locations (Postal Code)</relationshipLabel>
        <relationshipName>Locations1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State/Province</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AS</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>FM</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>GU</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MH</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectService__c.object
<CustomObject>
    <description>Project Service relates a Service to a Project and is a container used to define the instance of a Service for a specific Project. Project Service is related to Project, Job, Project Service Attribute, Project Service Certification, Project Service Equipment, Project Service Material, Project Service Question, Project Service Target, and Service.</description>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>ProjectServices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ServiceName__c</fullName>
        <formula>Service__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Service Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>Project Services</relationshipLabel>
        <relationshipName>ProjectServices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Service</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectServiceQuestion__c.object
<CustomObject>
    <description>Relates a Question to a Project Service. Questions from Service Question are added by default when a Service is added to a Project Service. Additional Questions can be added. Project Service Question is related to Project Service Question, Question, and Question Variant.</description>
    <fields>
        <fullName>ProjectService__c</fullName>
        <label>Project Service</label>
        <referenceTo>ProjectService__c</referenceTo>
        <relationshipLabel>ProjectServiceQuestions</relationshipLabel>
        <relationshipName>ProjectServiceQuestions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>QuestionText__c</fullName>
        <formula>Question__r.QuestionText__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Question Text</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Question__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>ProjectServiceQuestions</relationshipLabel>
        <relationshipName>ProjectServiceQuestions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Service Question</label>
    <nameField>
        <displayFormat>PSQ-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Service Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/Question__c.object
<CustomObject>
    <description>Question stores all of the questions stored in the system and defines the type of question (e.g. Date, Text, Y/N) and if the question is related to targets. Question is related to Question Defined Response, Question Variant.</description>
    <fields>
        <fullName>QuestionText__c</fullName>
        <label>Question Text</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/classes/ProjectPhotoExt.cls
global with sharing class ProjectPhotoExt {
    static Boolean isTest;
    global Project__c projectRecord {get;private set;}
    public List<ProjectService__c> services {get; private set;}
    global Cloudinary_Setting__mdt cloudinarySettings {get; private set;}

    static {
        Map<String, Schema.SObjectType> gd = Schema.getGlobalDescribe();
        Schema.SObjectType obj = gd.get('Job_Survey_Answer__x');
        isTest = (obj !=  null) ? false : true;
    }

    global ProjectPhotoExt(ApexPages.StandardController stdController) {
        //Get Project Name for photo title
        this.projectRecord = (Project__c)stdController.getRecord();
        projectRecord = [SELECT Id, Name FROM Project__c WHERE id =: projectRecord.Id];
        services = [SELECT Service__c, Name, ServiceName__c FROM ProjectService__c WHERE Project__c=:ProjectRecord.Id];
        //Get API Settings
        //Retrieve Cloudinary Cloud Name and API Key from Cloudinary_Setting__mdt
        cloudinarySettings = [SELECT Id, DeveloperName, Cloud_Name__c, API_Key__c FROM Cloudinary_Setting__mdt WHERE DeveloperName = 'Global'];     
    }

    static String getString(Map<String,String> args, String key){
        Object val = args.get(key);
        return getString(val);
    }

    static String getString(Object obj){
        return (obj != null) ? String.valueOf(obj) : '';
    }

    static String getName(Object lastName, Object firstName){
        String f = getString(firstName), l = getString(lastName);
        if (String.isBlank(f) && String.isBlank(l)){
            return 'n/a';
        }
        return f + ', ' + l;
    }
    
    @RemoteAction
    global static Map<String,String> getPhotoDetail(Map<String,String> query) {
        Map<String,String> res = new Map<String,String>();
        String jobId = getString(query,'jobId');
        if (String.isBlank(jobId)){
            return res;
        }
        Job__c job = [SELECT Name, 
            ReportedContactFirstName__c, 
            ReportedContactLastName__c, 
            ReportedContactId__c,
            ReportedContactTitle__c,
            ReportedEmployeeId__c,
            Location__r.LocationNumber__c,
            Location__r.Address__c,
            Location__r.City__c, 
            Location__r.State__c,
            Location__r.PostalCode__r.Name
            FROM Job__c WHERE Id=:jobId];
        if (job != null){
            res.put('workerName', getName(job.ReportedContactFirstName__c, job.ReportedContactLastName__c));
            res.put('workerTitle', job.ReportedContactTitle__c);
            res.put('workerEmployeeId', job.ReportedEmployeeId__c);
            res.put('workerContactId', job.ReportedContactId__c);
            res.put('jobNumber', job.Name);
            res.put('jobLocationNumber', job.Location__r.LocationNumber__c);
            res.put('jobAddress', job.Location__r.Address__c);
            res.put('jobCity', job.Location__r.City__c);
            res.put('jobState', job.Location__r.State__c);
            res.put('jobPostalCode', job.Location__r.PostalCode__r.Name);
        }
        String questionId = getString(query, 'questionId');
        if (String.isBlank(questionId)) {
            return res;
        }
        Question__c q = [SELECT QuestionText__c FROM Question__c WHERE Id =:questionId];
        if (null != q){
            res.put('photoQuestion', q.QuestionText__c);
        }

        return res;
    }

    @RemoteAction
    global static List<String[]> searchPhotos(Map<String,String> query){
        String projectId = getString(query,'projectId');
        if (String.isBlank(projectId)){
            throw new ProjectPhotoException('ProjectId can\'t be empty.');
        }

        String serviceId = getString(query, 'serviceId');
        String locations = getString(query,'locations');
        if(String.isBlank(serviceId)){
            throw new ProjectPhotoException('Please select one service.');
        }

        if(String.isBlank(locations)){
            return getPhotosByService(projectId, serviceId);
        }

        return getPhotosByServiceLocations(projectId, serviceId, locations);
    }

    static List<String[]> getPhotosByService(String projectId, String serviceId){
        Set<Id> jobIds = getRelatedJobsByProjectService(projectId, serviceId);
        Set<Id> questionIds = getRelatedQuestionsByProjectService(projectId, serviceId);
        return getPhotos(jobIds, questionIds);
    }

    static List<String[]> getPhotosByServiceLocations(String projectId, String serviceId, String locations){
        set<Id> relatedJobs = getRelatedJobsByProjectServiceLocations(projectId, serviceId, locations);
        set<Id> questionIds = getRelatedQuestionsByProjectService(projectId, serviceId);
        return getPhotos(relatedJobs, questionIds);
    }

    static Set<Id> getRelatedJobsByProject(String projectId) {
        Id pId = Id.valueOf(projectId);
        return (new map<Id,Job__c>([SELECT Id from Job__c WHERE Project__c = :pId])).keyset();
    }

    static Set<Id> getRelatedJobsByProjectService(String projectId, String serviceId) {
        Id pId = Id.valueOf(projectId),
            sId = Id.valueOf(serviceId);
        return (new map<Id, Job__c>([SELECT Id from Job__c WHERE Project__c = :pId AND Service__c=:sId])).keyset();
    }

    static Set<Id> getRelatedJobsByProjectServiceLocations(String projectId, String serviceId, String locations) {
        Id pId = Id.valueOf(projectId);
        Id sId = Id.valueOf(serviceId);
        Set<String> locIdSet = getLocNumSet(locations);
        return (new map<Id, Job__c>([SELECT Id from Job__c WHERE Project__c = :pId  AND Service__c=:sId AND LocationNumber__c in :locIdSet])).keyset();
    }

    static set<String> getLocNumSet(String locations){
        String tmp = locations + '';
        Set<String> locIdSet = new Set<String>();
        for(String loc: tmp.split(',')){
            locIdSet.add(loc.trim());
        }
        return locIdSet;
    }

    static Set<Id> getRelatedQuestionsByProject(String projectId){
        Set<Id> result = new Set<Id>();
        String photoType = 'Photo';
        Id pId = Id.valueOf(projectId);
        for(ProjectServiceQuestion__c q: [SELECT Question__c from ProjectServiceQuestion__c WHERE ProjectService__r.Project__c = :pId AND QuestionType__c =:photoType]){
            result.add(q.Question__c);
        }
        return result;
    }

    static Set<Id> getRelatedQuestionsByProjectService(String projectId, String serviceId){
        Id pId = Id.valueOf(projectId),
            sId = Id.valueOf(serviceId);
         Set<Id> result = new Set<Id>();
        String photoType = 'Photo';
        for(ProjectServiceQuestion__c q: [SELECT Question__c from ProjectServiceQuestion__c WHERE ProjectService__r.Project__c = :pId AND ProjectService__r.Service__c=:sId AND QuestionType__c =:photoType]){
            result.add(q.Question__c);
        }
        return result;
    }

     static List<String[]> getPhotosByTable(Set<Id> jobIds, Set<Id> questionIds, String tableName){
        List<String[]> res = new List<String[]>();
        String dt;
         String sql = 'SELECT job__c, response__c, question__c, date_modified__c FROM ' + tableName + ' WHERE question__c in :questionIds and job__c in :jobIds LIMIT 10000';
        try {
            //todo need to replace Job_Survey_Answer__c to Job_Survey_Answer__x
            for(sObject o: database.query(sql)){
            dt = o.get('date_modified__c') != null ? Datetime.valueOf(o.get('date_modified__c')).format('MM/dd/YYYY'): '';
            res.add(new String[]{
                (String)o.get('response__c'),
                (String)o.get('job__c'),
                (String)o.get('question__c'),
                dt
                });
          }    
        }catch(Exception e){
            System.debug('The following exception has occurred: ' + e.getMessage());
            throw new ProjectPhotoException(e.getMessage());
        }
        return res;
    }

    static List<String[]> getPhotos(Set<Id> jobIds, Set<Id> questionIds){
        String table = (isTest) ? 'Job_Survey_Answer__c' : 'Job_Survey_Answer__x';
        return getPhotosByTable(jobIds, questionIds, table);
    }

    //notice: this API is deprecated. do not use it. use getPhotoUrls to get data
    @RemoteAction
    @ReadOnly
    global static String[] PhotoURLs(String projectId) {
        return new String[] {};
    }
    
    @RemoteAction
    @ReadOnly
    global static List<String[]> getPhotoURLs(String projectId){
        set<Id> relatedJobs = getRelatedJobsByProject(projectId);
        set<Id> questionIds = getRelatedQuestionsByProject(projectId);
        return getPhotos(relatedJobs, questionIds);
    }
    global class ProjectPhotoException extends Exception {} 
}