src_old/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ContactId__c</fullName>
        <externalId>true</externalId>
        <label>Contact Id</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src_old/objects/JobAttempt__c.object
<CustomObject>
    <description>Job Attempt is an attempt of a Job performed at a location. Job Attempt is related to an Exception.</description>
    <fields>
        <fullName>AssignedContactId__c</fullName>
        <label>Assigned Contact ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AssignedContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Job Attempts</relationshipLabel>
        <relationshipName>Job_Attempts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DateAssigned__c</fullName>
        <label>Date Assigned</label>
        <type>DateTime</type>
    </fields>
    <label>Job Attempt</label>
    <nameField>
        <displayFormat>JA-{000000000}</displayFormat>
        <label>Job Attempt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Attempts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/JobAttemptWorker__c.object
<CustomObject>
    <fields>
        <fullName>ContactId__c</fullName>
        <label>Contact Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Job_Workers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DateAssigned__c</fullName>
        <label>Date Assigned</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>JobAttempt__c</fullName>
        <label>Job Attempt</label>
        <referenceTo>JobAttempt__c</referenceTo>
        <relationshipLabel>Job Attempt Workers</relationshipLabel>
        <relationshipName>Job_Attempt_Workers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Checked In</fullName>
                </value>
                <value>
                    <fullName>Checked Out</fullName>
                </value>
                <value>
                    <fullName>No Show</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WorkerType__c</fullName>
        <label>Worker Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Team Lead</fullName>
                </value>
                <value>
                    <fullName>Team Member</fullName>
                    <default>true</default>
                    <label>Team Member</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Job Attempt Worker</label>
    <nameField>
        <displayFormat>JAW-{000000000}</displayFormat>
        <label>Job Attempt Worker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Attempt Workers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/classes/JobAttemptWorkerTriggerHandlerTest.cls
@isTest
public class JobAttemptWorkerTriggerHandlerTest {

    @testSetup
    static void init(){
        TestDataUtil.init();
        JobAttempt__c attempt = TestUtil.setupJobTestData(CONSTANTS.JOB_ATTEMPT_STATUS_ASSIGNED, CONSTANTS.JOB_STATUS_ASSIGNED);
        TestUtil.generateJobAttemptWorkers(attempt, 3);

    }
    
    @isTest
    static void itShouldUpdateJobAttemptWorkerContact(){
        
       
    	List<JobAttemptWorker__c> jaws = [Select Id, ContactId__c, Contact__c, JobAttempt__c FROM JobAttemptWorker__c 
                                          WHERE WorkerType__c = :CONSTANTS.JOB_ATTEMPT_WORKER_WORKER_TYPE_TEAM_LEAD LIMIT 1];
        
        System.assert(jaws.size() > 0, 'No job attempt workers found');
        System.assert(jaws[0].Contact__c == null);
        
        //Assign a contact Id
        List<Contact> contacts = [Select Id, ContactId__c from Contact LIMIT 1];
        System.assert(contacts.size() > 0, 'No contacts found');
        System.assert(jaws[0].Contact__c == null);

        //Assign a contactid and make sure the corresponding contact
        //is populated
        jaws[0].ContactId__c = contacts[0].ContactId__c;
        update jaws[0];
        string jawId = jaws[0].Id;
        
        //Refresh Job Attempt Worker
        List<JobAttemptWorker__c> jaws2 = [Select Id, ContactId__c, Contact__c, JobAttempt__c, WorkerType__c, JobAttempt__r.AssignedContactId__c, 
                                           JobAttempt__r.AssignedContact__c, DateAssigned__c FROM JobAttemptWorker__c WHERE Id = :jawId LIMIT 1];
        
        if (!jaws2.IsEmpty())
        {
            System.assert(jaws2[0].ContactId__c != null);
            System.assert(jaws2[0].DateAssigned__c != null);
            System.assert(jaws2[0].Contact__c != null);
            System.assert(jaws2[0].WorkerType__c == CONSTANTS.JOB_ATTEMPT_WORKER_WORKER_TYPE_TEAM_LEAD);
			List<JobAttempt__c> jas = [Select Id, AssignedContactId__c, AssignedContact__c FROM 
                                       JobAttempt__c WHERE Id = :jaws2[0].JobAttempt__c];
            if (!jas.IsEmpty())
            {
                System.assert(jas[0].AssignedContactId__c != null);
                System.assert(jas[0].AssignedContact__c != null);
                
            }
            
        }
    }
    
    /*
    @isTest
    static void itShouldSendEmailWhenWorkerIsCanceled(){
        
    	List<JobAttemptWorker__c> jaws = [Select Id, ContactId__c, Contact__c, JobAttempt__c, Status__c FROM JobAttemptWorker__c 
                                          WHERE WorkerType__c = :CONSTANTS.JOB_ATTEMPT_WORKER_WORKER_TYPE_TEAM_LEAD LIMIT 1];
        System.assert(jaws.size() > 0, 'No job attempt workers found');
        jaws[0].Status__c = CONSTANTS.JOB_ATTEMPT_WORKER_STATUS_CANCELED;
        update jaws;
        

        List<JobAttemptWorker__c> jaws2 = [Select Id, ContactId__c, Contact__c, JobAttempt__c, Status__c FROM JobAttemptWorker__c 
                                          WHERE WorkerType__c = :CONSTANTS.JOB_ATTEMPT_WORKER_WORKER_TYPE_TEAM_LEAD LIMIT 1];
        System.assert(jaws2[0].Status__c == CONSTANTS.JOB_ATTEMPT_WORKER_STATUS_CANCELED);
    }    
    */
    
}