src_old/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>MaxCheckInTime__c</fullName>
        <label>Max Check In Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>MaxCheckOutTime__c</fullName>
        <label>Max Check Out Time</label>
        <type>DateTime</type>
    </fields>
</CustomObject>

src_old/objects/Job__c.object
<CustomObject>
    <description>Job defines the body of work to be performed at a Location and all of the dates related to the Job performance. A Job is related to a Project, Project Service, Project Location, Job Material, Contact, Exception, and Job Attempt.</description>
    <fields>
        <fullName>IsShift__c</fullName>
        <formula>UPPER(TEXT(Service__r.Specialization__c)) == &apos;SHIFT&apos;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Shift</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field that indicates the location of the Job.</description>
        <inlineHelpText>The location of the job</inlineHelpText>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field that indicates the Location of a Project.</description>
        <inlineHelpText>The location of the project</inlineHelpText>
        <label>Project Location</label>
        <referenceTo>ProjectLocation__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectService__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field that indicates the Project Service.</description>
        <inlineHelpText>The project service number</inlineHelpText>
        <label>Project Service</label>
        <referenceTo>ProjectService__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field that indicates the name of the Project to which a Job belongs.</description>
        <inlineHelpText>The name of the project for this job</inlineHelpText>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ShiftClosureOverride__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Shift Closure Override</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>StartTime__c</fullName>
        <formula>JobStartTime__c</formula>
        <label>Start Time</label>
        <type>Text</type>
    </fields>
    <label>Job</label>
    <nameField>
        <displayFormat>JOB-{000000000}</displayFormat>
        <label>Job ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/JobAttempt__c.object
<CustomObject>
    <description>Job Attempt is an attempt of a Job performed at a location. Job Attempt is related to an Exception.</description>
    <fields>
        <fullName>AttemptScheduleDate__c</fullName>
        <label>Attempt Scheduled Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>AttemptStatus__c</fullName>
        <label>Attempt Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Started</fullName>
                </value>
                <value>
                    <fullName>Reported</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IsShift__c</fullName>
        <formula>Job__r.IsShift__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Shift</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Job__c</fullName>
        <label>Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Job Attempts</relationshipLabel>
        <relationshipName>Job_Attempts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ProjectLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Location</label>
        <referenceTo>ProjectLocation__c</referenceTo>
        <relationshipLabel>Job Attempts</relationshipLabel>
        <relationshipName>Job_Attempts_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartTime__c</fullName>
        <label>Start Time</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TeamLeadUserId__c</fullName>
        <formula>PrimaryJobAttemptWorker__r.UserId__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>TeamLeadUserId</label>
        <type>Text</type>
    </fields>
    <label>Job Attempt</label>
    <nameField>
        <displayFormat>JA-{000000000}</displayFormat>
        <label>Job Attempt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Attempts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/JobAttemptWorker__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Job_Workers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>JobAttempt__c</fullName>
        <label>Job Attempt</label>
        <referenceTo>JobAttempt__c</referenceTo>
        <relationshipLabel>Job Attempt Workers</relationshipLabel>
        <relationshipName>Job_Attempt_Workers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>StartTime__c</fullName>
        <formula>JobAttempt__r.StartTime__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Start Time</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TeamLeadUserId__c</fullName>
        <formula>JobAttempt__r.TeamLeadUserId__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Team Lead User Id</label>
        <type>Text</type>
    </fields>
    <label>Job Attempt Worker</label>
    <nameField>
        <displayFormat>JAW-{000000000}</displayFormat>
        <label>Job Attempt Worker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Attempt Workers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/JobAttemptWorkerTimeEntry__c.object
<CustomObject>
    <fields>
        <fullName>Duration__c</fullName>
        <label>Duration (in minutes)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IsBillable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Billable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>JobAttemptWorker__c</fullName>
        <label>Job Attempt Worker</label>
        <referenceTo>JobAttemptWorker__c</referenceTo>
        <relationshipLabel>Job Attempt Worker Time Entries</relationshipLabel>
        <relationshipName>Job_Attempt_Worker_Time_Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>StartTime__c</fullName>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>TeamLeadUserId__c</fullName>
        <formula>JobAttemptWorker__r.JobAttempt__r.TeamLeadUserId__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Team Lead User Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TimeEntryType__c</fullName>
        <label>Time Entry Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Check In</fullName>
                </value>
                <value>
                    <fullName>Check out</fullName>
                </value>
                <value>
                    <fullName>Lunch</fullName>
                </value>
                <value>
                    <fullName>Break</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Job Attempt Worker Time Entry</label>
    <nameField>
        <displayFormat>JAWTE-{000000000}</displayFormat>
        <label>Job Attempt Worker Time Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Attempt Worker Time Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/Location__c.object
<CustomObject>
    <description>Location defines a location and its type, address, and the Retailer is it associated with. Location is related to Retailer, Job, and Project Location.</description>
    <label>Location</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <recordTypes>
        <fullName>Canceled</fullName>
        <active>true</active>
        <label>Canceled</label>
    </recordTypes>
    <recordTypes>
        <fullName>Closed</fullName>
        <active>true</active>
        <label>Closed</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ProjectLocation__c.object
<CustomObject>
    <description>Project Location relates a Location to a Project. Project Location is related Project, Job, and Location.</description>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Project Locations</relationshipLabel>
        <relationshipName>ProjectLocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>ProjectLocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>StartTime__c</fullName>
        <label>Start Time</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Project Location</label>
    <nameField>
        <displayFormat>PL-{0000}</displayFormat>
        <label>Location ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectService__c.object
<CustomObject>
    <description>Project Service relates a Service to a Project and is a container used to define the instance of a Service for a specific Project. Project Service is related to Project, Job, Project Service Attribute, Project Service Certification, Project Service Equipment, Project Service Material, Project Service Question, Project Service Target, and Service.</description>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>ProjectServices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ServiceRank__c</fullName>
        <description>This is the priority rank of a service to be performed</description>
        <label>ServiceRank</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>StartTime__c</fullName>
        <inlineHelpText>Replaced by using Location Export/Import function</inlineHelpText>
        <label>Start Time - N/A FOR NEW PROJECTS</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Project Service</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Services</pluralLabel>
    <recordTypes>
        <fullName>Canceled</fullName>
        <active>true</active>
        <label>Canceled</label>
    </recordTypes>
    <recordTypes>
        <fullName>Closed</fullName>
        <active>true</active>
        <label>Closed</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/JobAttemptHelper.cls
public class JobAttemptHelper {
          
    public static void validateOverlap(JobAttempt__c current, 
                                       JobAttempt__c old,
                                       List<JobAttemptWorkerTimeEntryWrapper> jobAttemptWorkerTimeEntries,
                                       Map<ID,Contact> contacts){
                
        // Validate only when the status is changed to reported.
        if (current.AttemptStatus__c == CONSTANTS.JOB_ATTEMPT_STATUS_REPORTED && current.AttemptStatus__c != old.AttemptStatus__c){
            
            
            for(JobAttemptWorkerTimeEntryWrapper jobAttemptWorkerTimeEntry : jobAttemptWorkerTimeEntries)
            {                                    
                Contact vContact = new Contact();
                vContact = contacts.get(jobAttemptWorkerTimeEntry.ContactId);
                
                if (vContact.MaxCheckOutTime__c >= jobAttemptWorkerTimeEntry.StartTime)
                {                    
                    current.addError('Shift not closed. ' + vContact.FirstName + ' ' + vContact.LastName + ' has check in / check out overlap');
                }
            }
        }
    }  
    
    public static void validatePreviousOpenShifts(JobAttempt__c current, JobAttempt__c old, Job__c job){

        // When job attempt status change to reported
        if ((old.AttemptStatus__c != current.AttemptStatus__c) && (current.AttemptStatus__c == CONSTANTS.JOB_ATTEMPT_STATUS_REPORTED)){
            

                List<JobAttempt__c> jobAttempts = [SELECT Id,Name FROM JobAttempt__c 
                                                   WHERE Job__r.Project__r.ID = :job.Project__r.ID 
                                                   AND Job__r.Location__r.Id = :job.Location__r.ID
                                                   AND Job__r.IsShift__c = true 
                                                   AND (AttemptScheduleDate__c < :current.AttemptScheduleDate__c OR 
                                                        (AttemptScheduleDate__c =: current.AttemptScheduleDate__c 
                                                         AND Job__r.ProjectService__r.ServiceRank__c < :job.ProjectService__r.ServiceRank__c)
                                                       )
                                                   AND AttemptStatus__c != :CONSTANTS.JOB_ATTEMPT_STATUS_CANCELED
                                                   AND AttemptStatus__c != :CONSTANTS.JOB_ATTEMPT_STATUS_CLOSED
                                                   AND AttemptScheduleDate__c != null            
                                                  ];
                
                if (jobAttempts.size() > 0){
                    current.AttemptStatus__c.addError('Please close the previous open jobs.');
                }            
        }
    }   
    
    public static void validatePreviousOpenShifts(JobAttempt__c current, Job__c job,List<JobAttempt__c> jobAttempts){
        boolean isJobsOpen = false;
        system.debug('validatePreviousOpenShifts' + jobAttempts);
        system.debug('jobServiceRank__c' + job.ProjectService__r.ServiceRank__c);
        
        for(JobAttempt__c jobAttempt : jobAttempts) {
            if ((jobAttempt.ID != current.ID) &&
                (jobAttempt.ProjectLocation__c == current.ProjectLocation__c) &&               
                //(jobAttempt.AttemptScheduleDate__c < current.AttemptScheduleDate__c) //&&                    
                ((jobAttempt.AttemptScheduleDate__c < current.AttemptScheduleDate__c) || 
                (jobAttempt.AttemptScheduleDate__c == current.AttemptScheduleDate__c &&  jobAttempt.Job__r.ProjectService__r.ServiceRank__c < job.ProjectService__r.ServiceRank__c))
               )
            {                    
                
                system.debug('jobAttempt.Job__r.ProjectService__r.ServiceRank__c' + jobAttempt.Job__r.ProjectService__r.ServiceRank__c + ':::' + job.ProjectService__r.ServiceRank__c);
                isJobsOpen = true;
                break;
            }
        }
        
        if (isJobsOpen){
            current.AttemptStatus__c.addError('Please close the previous open jobs.');
        }   
        
    } 
    
    public static Set<String> GetContactIdsForJobAttempts(Set<ID> jobAttemptIds, Set<String> timeEntryType){
        Set<String> contactIds = new Set<String>();
        
        for (JobAttemptWorkerTimeEntry__c jobAttemptWorkerTimeEntry : [SELECT Name, Id, StartTime__c,TimeEntryType__c, JobAttemptWorker__c, JobAttemptWorker__r.Contact__c, JobAttemptWorker__r.JobAttempt__c ,Duration__c,IsBillable__c, TeamLeadUserId__c  
                                                                       FROM JobAttemptWorkerTimeEntry__c 
                                                                       WHERE JobAttemptWorker__r.JobAttempt__c in :jobAttemptIds                                                                       
                                                                       AND TimeEntryType__c in :timeEntryType
                                                                      ])
        {
            
            // To collect contactId's
            contactIds.add(jobAttemptWorkerTimeEntry.JobAttemptWorker__r.Contact__c);                                                                          
            
        }
        
        return contactIds;
    }
    
    public static MAP<ID,Contact> GetContactMap(Set<String> contactIdSet)
    {
		MAP<ID,Contact> contactMap = new MAP<ID,Contact>();
        
        for (Contact c: [SELECT Id, LastName, FirstName , MaxCheckInTime__c, MaxCheckOutTime__c FROM CONTACT WHERE ID IN :contactIdSet])
        {
            contactMap.put(c.Id, c);
        }
        
        return contactMap;
    }
    
    public static MAP<ID,List<JobAttemptWorkerTimeEntryWrapper>> GetTimeEntryMap(Set<ID> jobAttemptIds, Set<String> timeEntryType){
    
        MAP<ID,List<JobAttemptWorkerTimeEntryWrapper>> jobAttemptTimeEntryWrapperMap = new MAP<ID,List<JobAttemptWorkerTimeEntryWrapper>>();
        
        for (JobAttemptWorkerTimeEntry__c jobAttemptWorkerTimeEntry : [SELECT Name, Id, StartTime__c,TimeEntryType__c, JobAttemptWorker__c, JobAttemptWorker__r.Contact__c, JobAttemptWorker__r.JobAttempt__c ,Duration__c,IsBillable__c, TeamLeadUserId__c  
                                                                       FROM JobAttemptWorkerTimeEntry__c 
                                                                       WHERE JobAttemptWorker__r.JobAttempt__c in :jobAttemptIds                                                                       
                                                                       AND TimeEntryType__c in :timeEntryType
                                                                      ])
        {                                                                          
            
            //To collect job attempt time entry per job attempt
            if (jobAttemptTimeEntryWrapperMap.containskey(jobAttemptWorkerTimeEntry.JobAttemptWorker__r.JobAttempt__c)){
                
                List<JobAttemptWorkerTimeEntryWrapper> jobAttemptWorkerTimeEntrys =  jobAttemptTimeEntryWrapperMap.get(jobAttemptWorkerTimeEntry.JobAttemptWorker__r.JobAttempt__c);
                
                jobAttemptWorkerTimeEntrys.add(new JobAttemptWorkerTimeEntryWrapper(jobAttemptWorkerTimeEntry, jobAttemptWorkerTimeEntry.JobAttemptWorker__r.Contact__c));
                
                jobAttemptTimeEntryWrapperMap.put(jobAttemptWorkerTimeEntry.JobAttemptWorker__r.JobAttempt__c,jobAttemptWorkerTimeEntrys);
                
            }
            else
            {   
                List<JobAttemptWorkerTimeEntryWrapper> jobAttemptWorkerTimeEntrys = new List<JobAttemptWorkerTimeEntryWrapper>();
                
                jobAttemptWorkerTimeEntrys.add(new JobAttemptWorkerTimeEntryWrapper(jobAttemptWorkerTimeEntry, jobAttemptWorkerTimeEntry.JobAttemptWorker__r.Contact__c));
                
                jobAttemptTimeEntryWrapperMap.put(jobAttemptWorkerTimeEntry.JobAttemptWorker__r.JobAttempt__c,jobAttemptWorkerTimeEntrys);                                                                              
            }
        }
        return jobAttemptTimeEntryWrapperMap;
    }
    
    public static List<JobAttempt__c> GetJobAttemptForProjectLocation(Set<ID> projectLocationIds)
    {
        List<JobAttempt__c> result = [SELECT ID, ProjectLocation__c,Job__r.Project__r.ID,Job__r.Location__r.ID, AttemptStatus__c,AttemptScheduleDate__c,Job__r.ProjectService__r.ServiceRank__c FROM JobAttempt__c 
                                      WHERE ProjectLocation__c IN :projectLocationIds
                                      AND Job__r.IsShift__c = true 
                                      AND AttemptStatus__c NOT IN ('Reported','Canceled','Closed') 
                                      AND AttemptScheduleDate__c != null
                                     ];
        return result;
    }
 
	public static Map<String,Job__c> getJobs(Set<String> jobIdSet) {
        Map<String,Job__c> result = new Map<String,Job__c>();
        if (0 == jobIdSet.size()) {
            return result;
        }
            
        for(Job__c job: [SELECT Id,Project__r.ID ,Location__r.ID, ProjectService__r.ServiceRank__c ,IsShift__c, ShiftClosureOverride__c FROM Job__c WHERE Id IN :jobIdSet]) {
            result.put(job.Id, job);
        }
        return result;
    }
}