src_old/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>EmployeeId__c</fullName>
        <label>Employee Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ManagerId__c</fullName>
        <label>Manager Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pin__c</fullName>
        <label>Pin</label>
        <length>20</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
</CustomObject>

force-app/main/default/classes/ContactTriggerHandlerTest.cls
@isTest
public class ContactTriggerHandlerTest {

    @testSetup static void setup(){
        TriggerUtil.skipContactTrigger = true;
        TestUtil.initBaseData();
        
    }

    public static testMethod void Test_beforeUpdate(){
         Account testAccount = new Account();

        testAccount.Name='Test Account' ;

        insert testAccount;
        
        Test.startTest();   
       Contact a = new Contact(
                          FirstName = 'Test',
                          LastName = 'Test',
                          Pin__c ='1234',
                          Accountid = testAccount.Id,
                          ManagerId__c ='1234'
                          
                      );
        
         insert a;  
        try{
            Contact cont = [Select Id, Name,Pin__c,EmployeeId__c,ManagerId__c from Contact LIMIT 1];
            cont.EmployeeId__c = 'ChangedId';
            cont.Pin__c ='4568';
            cont.ManagerId__c='8769';
            update cont;
            system.assert(cont != null);         
            
        }
        catch(exception e){
            
        }
    }
    public static testMethod void test_beforeCreate()
    {
        
        try{
            
         Account testAccount = new Account();

        testAccount.Name='Test Account' ;

        insert testAccount;
        
        Test.startTest();   
       Contact a = new Contact(
                          FirstName = 'Test',
                          LastName = 'Test',
                          Pin__c ='1234',
             			  ManagerId__c ='1234',
                          Accountid = testAccount.Id
                          
                      );
        
         insert a;  
             
        Test.stopTest();
            
        }
        catch(exception e)
        {
            
        }
    }
    
    
}