src_old/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src_old/objects/Location__c.object
<CustomObject>
    <description>Location defines a location and its type, address, and the Retailer is it associated with. Location is related to Retailer, Job, and Project Location.</description>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LocationNumber__c</fullName>
        <label>Location Number</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PostalCodeName__c</fullName>
        <formula>PostalCode__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Postal Code Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Retailer__c</fullName>
        <label>Retailer</label>
        <referenceTo>Retailer__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State/Province</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AS</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>FM</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>GU</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MH</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Location</fullName>
                </value>
                <value>
                    <fullName>Retailer</fullName>
                </value>
                <value>
                    <fullName>Employee</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <fields>
        <fullName>ProjectRetailerONEHUBID__c</fullName>
        <label>Project Retailer One Hub ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Retailer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Retailer</label>
        <referenceTo>Retailer__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planning</fullName>
                    <default>true</default>
                    <label>Planning</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Launched</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ended</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <recordTypes>
        <fullName>Canceled</fullName>
        <active>true</active>
        <label>Canceled</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ProjectLocation__c.object
<CustomObject>
    <description>Project Location relates a Location to a Project. Project Location is related Project, Job, and Location.</description>
    <fields>
        <fullName>Address__c</fullName>
        <formula>Location__r.Address__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <formula>Location__r.City__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsNewLocation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates a if the project location i added in scheduled state</description>
        <label>is New Location</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LocationNumber__c</fullName>
        <formula>Location__r.LocationNumber__c</formula>
        <label>Location #</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Project Locations</relationshipLabel>
        <relationshipName>ProjectLocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>ProjectLocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Retailer__c</fullName>
        <formula>Project__r.Retailer__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Retailer</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <formula>TEXT(Location__r.State__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>State/Province/Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Job Created</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <formula>IF(Location__r.Parent__c != null, Location__r.Parent__r.Name, &apos;&apos;)</formula>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <label>Project Location</label>
    <nameField>
        <displayFormat>PL-{0000}</displayFormat>
        <label>Location ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/Retailer__c.object
<CustomObject>
    <description>Retailer stores the retailers for the system. Retailer is related to Location, Retailer Service, Retailer Service Certification, and Retailer Service Equipment.</description>
    <label>Retailer</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Retailers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/classes/UploadLocationsExt.cls
global with sharing class UploadLocationsExt {

    public ApexPages.StandardController controller;
    public Project__c proj {get;set;}
    public String projectName {get;set;}
    public String csvFileBody{get;set;}
    public list<errorClass> lstErr{get;set;}
    public list<errorClass> lstSucc{get;set;}
    public string csvAsString{get;set;}
    public boolean isGridVisible{get;set;}
    public String projectId {get;set;} 
    public boolean displayGrid{get;set;}
    public Project__c TmpProj{get;set;}
    public ProjectLocation__c TmpProjLoc{get;set;}
    public location__c TempLoc{get;set;}
    public list<location__c> TempLocList{get;set;}
    public string City{get;set;}
    public string Region{get;set;}
    public string RoadShowNo{get;set;}
    public string soqlQuery{get;set;}
    public boolean ShowServices{get;set;}
    public string VendorName{get;set;}
    public string ClubName{get;set;}
    public boolean initialLoad{get;set;}
    public string OwnerName{get;set;}
    public list<result> FullResult{get;set;}
    public string SuccessMsg{get;set;}
    public String AvlTags{get;set;}
    public String RetailerCode {get;set;}
    
    public String getNAMESPACE() {
        return CONSTANTS.CURRENTNAMESPACEPREFIX;
    }

    public UploadLocationsExt(ApexPages.StandardController controller) {
        lstErr= new list<errorClass>();
        lstSucc=new list<errorClass>();
                
        TmpProjLoc = new projectlocation__c();
        TempLoc = new location__C();
        TempLocList = new list<location__c>();   
        displayGrid = false;
        ProjectID = ApexPages.currentPage().getParameters().get('projectid');
        TmpProj = [select id,name from project__c where id=:projectid];
        SuccessMsg = '';
        
        project__c proj = [select id,name,retailer__c, ProjectRetailerONEHUBID__c from project__c where id=:projectId];
        retailer__c retl = [select id,name from retailer__c where id=:proj.retailer__c];
        RetailerCode = proj.ProjectRetailerONEHUBID__c;
        projectName = proj.name;
        set<string> AvlTagsSet = new set<string>();
        string locationQry = ' SELECT ItemId,Name,Type FROM Location__Tag where itemid  in (SELECT id FROM Location__c where Retailer__c = \'' + retl.id + '\')';
        system.debug(' ~~~~~ locationQry' +locationQry);
        list<location__tag> listTag = database.query(locationQry);
        for(location__tag td : listTag)
        {
            AvlTagsSet.add(td.Name);
        }
        AvlTags =  String.join((new list<string>(AvlTagsSet)), ','); 
        
        FullResult = new list<result>();
    }

    public class ErrorClass{
       public string locationNumber {get;set;}
       public string reason {get;set;}
       public string LocName{get;set;}
       public ErrorClass()
       {
       }
       public ErrorClass(string loc, string rsn, string obj)
       {
           locationNumber = loc;reason= rsn;LocName = obj;
       }
    }
   
   

    global class result{
        public location__c NewLoc{get;set;} 
        public string id{get;set;} 
        public string name{get;set;} 
        public string city{get;set;}  public string status{get;set;} 
        public result(location__c loc, string val){
            newLoc=loc;
            status=val;
        }
        public result(){}
    }

    
    
    public void importCSVFile()
    {  
        ProjectLocation__c pl ;
        String retURL;
        string csvAsString;
        String[] csvFileLines;
        string[] csvRecordData;    
        string TestRecordData;
        List<ProjectLocation__c> CollList = New List<ProjectLocation__c>(); 
        List<ProjectLocation__c> CollList2;
        List<Location__c> failedColl;
        List<ProjectLocation__c> AlreadyExists;
        ProjectLocation__c ProjectLocationObj ;
        Location__c LocationObj ;
        boolean isGridVisible;
        id temp;    
        String Query ;  
        set<string> SuccLoc = new set<string>();  
            
        try
        {
            List<ProjectLocation__c>  returnedList  = New List<ProjectLocation__c>(); 
           
            csvFileLines = csvFileBody.split('\n');
                
            Set<String> myset = new Set<String>();
            List<String> result = new List<String>();
            for(string s : csvFileLines)
            {
                myset.add(s.trim());
            }
            result.addAll(myset);
            
            String Projid = ApexPages.currentPage().getParameters().get('projectid');
            proj = [select retailer__c,retailer__r.name, ProjectRetailerONEHUBID__c from project__c where id=:Projid limit 1];
            system.debug('proj retailer      '+ proj.retailer__r.name + '______' +  proj.retailer__c);
            if(result.size() == 0 )
            {
                ApexPages.Message errorMessage = new ApexPages.Message(ApexPages.severity.ERROR,'Empty file/data. Please check and resubmit.');
                ApexPages.addMessage(errorMessage);           
                return;
            }
            
            location__c loc = new location__C();
            CollList = New List<ProjectLocation__c>(); 
            AlreadyExists= New List<ProjectLocation__c>(); 
            failedColl = New List<Location__c>(); 
            lstErr= new list<errorClass>();
            lstSucc=new list<errorClass>();
            
            list<string> invalidLoc= new list<string>();
            list<string> newLoc= new list<string>();
            
            system.debug(' search begins ');
            system.debug(' result '+String.join(result, ','));
            system.debug(' myset '+myset );
            
            set<string> AvlLocs = new set<string>();
            list<location__c> AvlLocsMap = [SELECT LocationNumber__c,name FROM Location__c where Type__c = 'Location' AND retailer__c =: proj.retailer__c and isactive__c=true and  LocationNumber__c IN :myset];
            for(location__c l:AvlLocsMap )
            { 
                AvlLocs.add(l.LocationNumber__c);
                System.debug('  AvlLocs   l.LocationNumber__c     ' + l.LocationNumber__c);
            }            
             
            if(AvlLocsMap!=null && AvlLocsMap.size()>0)
            {
                for(string s : result)
                {
                   if(!AvlLocs.contains(s)){
                       invalidLoc.add(s);
                   }
                }
            }
            else
            {
                system.debug(' AvlLocsMap is null ');
                invalidLoc = result;                
            }
            system.debug(' invalid loc '+String.join(invalidLoc, ','));
            
            if(invalidLoc.size() == result.size())
            {
                lstErr.add( new ErrorClass( String.join(invalidLoc, ',') ,'Invalid Location number.',''));
                return;
            }
            
            
            system.debug(' ProjectLocation search begins ');
            list<ProjectLocation__c> ExistingProjLocsMap = new list<ProjectLocation__c>([SELECT Location__r.LocationNumber__c FROM ProjectLocation__c where Project__c = : Proj.id   AND Status__c != 'Canceled' AND Location__r.LocationNumber__c IN :AvlLocs]);
            set<string> ExistingProjLocs = new set<string>();
            for(projectlocation__c plt : ExistingProjLocsMap)
            {
                ExistingProjLocs.add(plt.Location__r.LocationNumber__c);
                System.debug('     ExistingProjLocs     ' + plt.Location__r.LocationNumber__c);
            }
            
            Project__c p = [SELECT Id,Status__c FROM Project__c WHERE Id =:projectID];
            
            for(location__c newlocation:AvlLocsMap)
            {
               if(!ExistingProjLocs.contains(newlocation.locationnumber__c)){
                    ProjectLocationObj= new ProjectLocation__c();
                    ProjectLocationObj.Location__c =newlocation.ID;
                    ProjectLocationObj.Project__c =Projid ;
                    if(p.Status__c != CONSTANTS.PROJECT_STATUS_PLANNING){
                        ProjectLocationObj.IsNewLocation__c = true ;
                    }
                    CollList.add(ProjectLocationObj);
                    SuccLoc.add(newlocation.locationnumber__c);
               }
            }  
            insert CollList;
            
                       
            if(SuccLoc.size() >0 ){
                
                lstSucc.add( new ErrorClass(String.join((new list<string>(SuccLoc)), ','),'Location successfully added to the project',''));
            }
            
            if(ExistingProjLocs.size() >0 ){
                lstErr.add( new ErrorClass( String.join((new list<string>(ExistingProjLocs)), ',') ,'Location already added to the project.',''));
            }
            
            if(invalidLoc.size() >0 ) {
                lstErr.add( new ErrorClass( String.join(invalidLoc, ',') ,'Invalid Location number.',''));
            }
      

       }
       catch (System.DmlException e) {
            ApexPages.Message errorMessage = new ApexPages.Message(ApexPages.severity.ERROR,e.getDMLMessage(0));
            ApexPages.addMessage(errorMessage);
       }
       catch (System.NullPointerException e) {
            ApexPages.Message errorMessage = new ApexPages.Message(ApexPages.severity.ERROR,'Invalid file/data. Please check and resubmit.');
            ApexPages.addMessage(errorMessage);
       }        
       catch (Exception e)
       {           
            ApexPages.Message errorMessage = new ApexPages.Message(ApexPages.severity.ERROR,'Invalid file with errors.');            
            // ApexPages.Message errorMessage = new ApexPages.Message(ApexPages.severity.ERROR,e.getMessage()+ e.getTypeName());           
            ApexPages.addMessage(errorMessage);
       }          
    }
    
    
    @RemoteAction
    global static list<location__c> getProj(string tag,string state,string city,string postalcode, boolean IncludeProjLoc,string projectId, string Location) 
    {  
        project__c proj = [select id,retailer__c from project__c where id=:projectId];
        retailer__c retl = [select id,name from retailer__c where id=:proj.retailer__c];
        system.debug('retailer name  ' + retl.name);
        string LocationQry = 'Select name,Address__c,state__c,city__c,PostalCodeName__c,locationnumber__c from location__c where type__c=\'Location\' and isactive__c=true and  retailer__c =  \'' + retl.id+'\'  '; 
        Integer existingLocCount = [SELECT count() FROM ProjectLocation__c WHERE Project__c = :projectId AND Status__c != 'Canceled'];
        boolean isFilterExist = false;
        if(Location!=null && Location!='')
        {   
            isFilterExist =true;         
            LocationQry+= ' and locationnumber__c = \'' + string.valueof(Location) +'\'  '; 
        }
        
        if(state!='--NONE--' && state!=null)
        {   
            isFilterExist =true;         
            LocationQry+= ' and State__c = \'' + string.valueof(state) +'\'  '; 
        }     
        if(city!='' && city!=null)
        {   
            isFilterExist =true;         
            LocationQry+= ' and city__c like \'%' + string.valueof(city) +'%\'  '; 
        }  
         if(postalcode!='' && postalcode!=null)
        {   
            isFilterExist =true;         
            LocationQry+= ' and postalcodename__c like \'%' + string.valueof(postalcode) +'%\'  '; 
        }    
         system.debug('LocationQry  ' + LocationQry );
        
        if(!IncludeProjLoc){
            Set<string> locSet = new Set<string>();
            //string loc = ' select id from projectlocation__c where project__c=: \' ' + projectId + ' \' ' ;         
            string loc = ' select location__c from projectlocation__c where project__c=: projectId AND Status__c != \'Canceled\'' ;         
            system.debug('__#### loc __'+loc+'-----');  
            //list<AggregateResult> tagList =  Database.query(soqlQry);
            
            for(projectlocation__c ploc : Database.query(loc)){
                locSet.add((string)ploc.location__c);
            }
                        
            LocationQry+= ' and id not in :locSet ';    
        }

        system.debug('__#### tag__'+tag +'-----'); 
        if(tag!='')
        {
            isFilterExist=true;
            Set<string> subjectSet = new Set<string>();
            Set<string> SelectedTag = new Set<string>();     
            for(string item : tag.split(','))
            {
               SelectedTag.add(item);           
            }
            
            string soqlQry = ' SELECT ItemId,count(name) FROM Location__Tag where name in: SelectedTag group by itemid having count(name) = ' + SelectedTag.size()  ;         
            system.debug('__#### soqlQry __'+soqlQry+'-----');  
            list<AggregateResult> tagList =  Database.query(soqlQry);
            
            for(AggregateResult t : tagList){
                subjectSet.add((string)t.get('itemid'));
            }
            
            system.debug('__#### subjectSet __'+subjectSet+'-----'); 
            LocationQry+= ' and id in :subjectSet  ';
        }
        LocationQry+= '  order by name ';
        system.debug('__#### loc qry __'+LocationQry+'-----');  
        
        if(!isFilterExist){
            LocationQry+= '  limit 0 ';    
        }
        else{
            LocationQry+= '  limit ' + (9500 - existingLocCount);    
        }
       
        return Database.query(LocationQry);
        
    }
    
    @RemoteAction
    global static string Import(string allLocID,string projectID)
    {
        string msg = '';
        try{
            system.debug('inside import');
            list<ProjectLocation__c> ExistingProjLocsMap = new list<ProjectLocation__c>([SELECT Location__r.LocationNumber__c FROM ProjectLocation__c where Project__c = : ProjectID AND Status__c != 'Canceled']);
            Project__c p = [SELECT Id,Status__c FROM Project__c WHERE Id =:projectID];
            set<string> ExistingProjLocs = new set<string>();
            for(projectlocation__c plt : ExistingProjLocsMap)
            {
                ExistingProjLocs.add(plt.Location__r.LocationNumber__c);                
            }
            
            set<string> AllProjLocs = new set<string>();
            for(string item : allLocID.split(','))
            {
               AllProjLocs.add(item);           
            }
            
            result res = new result();
            list<result> lstresult = new list<result>();
            
            ProjectLocation__c ProjectLocationObj;
            list<ProjectLocation__c> CollList = new list<ProjectLocation__c>(); 
            
            list<location__c> locList = [select id,locationnumber__c,name,city__c from location__c where id in: AllProjLocs LIMIT 9500];
            
            for(location__c row: locList )
            {
                    res = new result();
                    res.id = row.id;
                    res.city = row.city__c;
                    res.name = row.name;
                    
               if(!ExistingProjLocs.contains(row.locationnumber__c)){
                    ProjectLocationObj= new ProjectLocation__c();
                    ProjectLocationObj.Location__c =row.id;
                    ProjectLocationObj.Project__c =ProjectID ;
                    if(p.Status__c != CONSTANTS.PROJECT_STATUS_PLANNING){
                        ProjectLocationObj.IsNewLocation__c = true ;
                    }
                    CollList.add(ProjectLocationObj);
                    res.status='Success';
               }
               else{
                    res.status='Location already exist';
               }
               lstresult.add(res);
            }  
            
            if(CollList.size()>0)
            {
                Database.SaveResult[] obj = database.insert(CollList);
                
                //Comment Versioning Code
                //AppUtil.UpdateProjectVersion(ProjectID);
                
                return CollList.size() + ' location(s) added to project';
            }
            else{
                return 'Location(s) already exist in the project';
            }
            
        }
        catch(exception ex){
                return string.valueof(ex);
            //return 'Error during Import. Contact Admin';
        }

    }
}