src_old/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>OneHubThirdPartyAgencyContactId__c</fullName>
        <externalId>true</externalId>
        <label>OneHub Third Party Agency ContactId</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src_old/objects/Job__c.object
<CustomObject>
    <description>Job defines the body of work to be performed at a Location and all of the dates related to the Job performance. A Job is related to a Project, Project Service, Project Location, Job Material, Contact, Exception, and Job Attempt.</description>
    <fields>
        <fullName>EstimatedMinutesOverride__c</fullName>
        <label>Estimated Minutes Override</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>JobScheduledDate__c</fullName>
        <description>The field that indicates the date a Job is scheduled.</description>
        <inlineHelpText>The date the job was scheduled</inlineHelpText>
        <label>Scheduled Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LocationNumber__c</fullName>
        <description>The field that indicates the location number of the Job.</description>
        <formula>Location__r.LocationNumber__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The location number of the job</inlineHelpText>
        <label>Location #</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProjectLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field that indicates the Location of a Project.</description>
        <inlineHelpText>The location of the project</inlineHelpText>
        <label>Project Location</label>
        <referenceTo>ProjectLocation__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field that indicates the name of the Project to which a Job belongs.</description>
        <inlineHelpText>The name of the project for this job</inlineHelpText>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PurchaseOverRideAmount__c</fullName>
        <label>Purchase OverRide Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Job</label>
    <nameField>
        <displayFormat>JOB-{000000000}</displayFormat>
        <label>Job ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/JobAttemptWorker__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Job_Workers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ECWorkerId__c</fullName>
        <label>EC Worker Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ECWorkerTime__c</fullName>
        <label>EC Worker Time</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ExecutionCompany__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Execution Company</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Job Attempt Workers</relationshipLabel>
        <relationshipName>Job_Attempt_Workers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FirstName__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LocationName__c</fullName>
        <formula>JobAttempt__r.Job__r.Location__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Location Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LocationNumber__c</fullName>
        <formula>JobAttempt__r.Job__r.Location__r.LocationNumber__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Location Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Checked In</fullName>
                </value>
                <value>
                    <fullName>Checked Out</fullName>
                </value>
                <value>
                    <fullName>No Show</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ThirdPartyAgencyStatus__c</fullName>
        <label>3PL Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Requested</fullName>
                </value>
                <value>
                    <fullName>Canceled - Reassigned to CMK</fullName>
                </value>
                <value>
                    <fullName>Committed</fullName>
                </value>
                <value>
                    <fullName>Executed</fullName>
                </value>
                <value>
                    <fullName>Invoiced</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Agency Declined</fullName>
                </value>
                <value>
                    <fullName>Pending 3PL Agency Approval</fullName>
                </value>
                <value>
                    <fullName>CMK Rejected</fullName>
                </value>
                <value>
                    <fullName>Filled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ThirdPartyAgency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>3PL Agency</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Job Attempt Workers (3PL Agency)</relationshipLabel>
        <relationshipName>Job_Attempt_Workers1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Job Attempt Worker</label>
    <nameField>
        <displayFormat>JAW-{000000000}</displayFormat>
        <label>Job Attempt Worker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Attempt Workers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/PostalCode__c.object
<CustomObject>
    <description>Postal Code stores a global list of Postal Codes with Country and Geolocation information that is referenced from multiple objects. Postal Code is related to Location, Job, and Project Location.</description>
    <label>Postal Code</label>
    <nameField>
        <label>Postal Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Postal Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <fields>
        <fullName>StatusComments__c</fullName>
        <description>Used to store Rejected or Canceled reasons</description>
        <label>Status Comments</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planning</fullName>
                    <default>true</default>
                    <label>Planning</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Launched</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ended</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ProjectLocation__c.object
<CustomObject>
    <description>Project Location relates a Location to a Project. Project Location is related Project, Job, and Location.</description>
    <fields>
        <fullName>Address__c</fullName>
        <formula>Location__r.Address__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <formula>Location__r.City__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExecutionCompany__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Execution Company</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Project Locations</relationshipLabel>
        <relationshipName>Project_Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LocationName__c</fullName>
        <formula>Location__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Location Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LocationNumber__c</fullName>
        <formula>Location__r.LocationNumber__c</formula>
        <label>Location #</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LocationScheduledDate__c</fullName>
        <label>Location Scheduled Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OneHubThirdPartyAgencyContactId__c</fullName>
        <label>3PL Agency ContactId</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PostalCode__c</fullName>
        <formula>Location__r.PostalCode__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Postal Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>ProjectLocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <formula>TEXT(Location__r.State__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>State/Province/Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StatusComments__c</fullName>
        <label>Status Comments</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Job Created</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project Location</label>
    <nameField>
        <displayFormat>PL-{0000}</displayFormat>
        <label>Location ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/User.object
<CustomObject>
    <fields>
        <fullName>ThirdPartyAgency__c</fullName>
        <label>ThirdPartyAgency</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/classes/BatchManageImportAttachmentsTest.cls
@isTest
private class BatchManageImportAttachmentsTest {
    static Date START_DATE = Datetime.Now().Date();
    static Date END_DATE = Datetime.Now().addDays(14).Date();
    static Date SCHEDULE_DATE = Datetime.Now().addDays(2).Date();
    static String THREEPL_CONTACT_ID = '3PL1';

    @testSetup
    static void setup() {
        TriggerUtil.skipAllTriggers();
        TestDataUtil.init();
        TestProject tP = TestProject.create('demo', START_DATE, END_DATE, null)
                         .addAll();
        setupJobAttemptWorkersFor3PLAgentcy(tP.ProjectInstance.Id);
    }

    static void setupJobAttemptWorkersFor3PLAgentcy(string pId) {
        Contact uContact = [SELECT Id, AccountId from Contact LIMIT 1];
        List<JobAttemptWorker__c> jaws = TestProject.getJobAttemptWorkers(pId);
        for (JobAttemptWorker__c jaw : jaws) {
            jaw.ThirdPartyAgency__c = uContact.AccountId;
        }
        update jaws;
    }

    static void createAttachment(String name, String body, String parentId) {
        Attachment att = new Attachment();
        att.ParentId = parentId;
        att.Name = name;
        att.Body = Blob.valueOf(body);
        insert att;
    }

    static String genCSVStringForImportLocations(ProjectLocation__c pl,
            String oh3PLContactId) {
        List<Object> contents = new List<Object>();
        contents.add(pl.Name);
        contents.add(pl.LocationNumber__c);
        contents.add(pl.LocationName__c);
        contents.add(pl.Address__c);
        contents.add(pl.City__c);
        contents.add(pl.State__c);
        contents.add(pl.PostalCode__c);
        contents.add(pl.Status__c);
        contents.add(pl.StatusComments__c);
        contents.add('');
        contents.add('');
        contents.add(pl.ExecutionCompany__c);
        contents.add(SCHEDULE_DATE.format());
        contents.add(oh3PLContactId);
        contents.add('');

        return JSON.serialize(new String[] {String.join(contents, ',')});
    }

    @isTest
    static void itShouldNamifyProperly() {
        //GIVEN
        String fields = 'Name-1,' + TestDataUtil.SystemNameSpace + 'Job__c-2';

        //WHEN
        String result = TestDataUtil.namifyImportFields(fields);

        //THEN
        QA.EQ(result, fields, 'matched:' + fields);
    }

    @isTest
    static void itShouldNotSetScheduleDateWhenImportInvalid3PL() {
        //GIVEN
        Project__c p = TestProject.getProjects()[0];
        ProjectLocation__c pl = TestProject.getLocations(p.Id)[0];

        String csvString = genCSVStringForImportLocations(pl, THREEPL_CONTACT_ID);
        createAttachment('import_locations', csvString, p.Id);
        EmailNotifierFake fakeNotifier = new EmailNotifierFake(true, '');

        //WHEN
        test.startTest();
        BatchManageImportAttachments batch = new BatchManageImportAttachments(p.Id, 'locations', fakeNotifier);
        string batchProcessId = Database.ExecuteBatch(batch, 1);
        test.stopTest();

        //THEN
        pl = TestProject.getLocations(p.Id)[0];
        QA.isTrue(String.isBlank(pl.OneHubThirdPartyAgencyContactId__c), '3PLId should not be set');
        QA.isTrue(String.isBlank(String.valueOf(pl.LocationScheduledDate__c)), 'schedule date should not be set');

        ApexJobTracker tracker = TestProject.getApexJobTracker();
        QA.EQ(ApexJobTracker.TrackerStatus.Success, tracker.Status, 'process succeeded:' + tracker.Response);
        QA.EQ(true, tracker.failureNotified, 'email sent out:' + tracker.Response);
    }

    @isTest
    static void itShouldImportProjectLocations() {
        // Given: create attachment
        Project__c p = TestProject.getProjects()[0];
        ProjectLocation__c pl = TestProject.getLocations(p.Id)[0];

        String csvString = genCSVStringForImportLocations(pl, '');
        createAttachment('import_locations', csvString, p.Id);
        EmailNotifierFake fakeNotifier = new EmailNotifierFake(true, '');

        // When
        test.startTest();
        BatchManageImportAttachments batch = new BatchManageImportAttachments(p.Id, 'locations', fakeNotifier);
        string batchProcessId = Database.ExecuteBatch(batch, 1);
        test.stopTest();

        // Then
        pl = TestProject.getLocations(p.Id)[0];
        QA.isTrue(String.isBlank(pl.OneHubThirdPartyAgencyContactId__c), '3PLId should not be set');
        QA.EQ(SCHEDULE_DATE, pl.LocationScheduledDate__c, 'schedule date is set');

        ApexJobTracker tracker = TestProject.getApexJobTracker();
        QA.EQ(ApexJobTracker.TrackerStatus.Success, tracker.Status, 'process succeeded:' + tracker.Response);
        QA.EQ(true, tracker.failureNotified, 'email sent out:' + tracker.Response);
    }

    static String genCSVStringForImportJobs(Job__c job) {
        List<String> cntn = new List<String>();
        cntn.add(job.Name); // 0
        cntn.add(''); // 1
        cntn.add(''); // 2
        cntn.add(''); // 3
        cntn.add(''); // 4
        cntn.add(''); // 5
        cntn.add(''); // 6
        cntn.add(''); // 7
        cntn.add(''); // 8
        cntn.add(SCHEDULE_DATE.format()); // 9
        cntn.add(''); // 10
        cntn.add('123'); // 11
        cntn.add('100'); // 12

        return JSON.serialize(new String[] {String.join(cntn, ',')});
    }

    @isTest
    static void itShouldImportJobs() {
        //GIVEN
        Project__c p = TestProject.getProjects()[0];
        Job__c job = TestProject.getJObs(p.Id)[0];
        String csvString = genCSVStringForImportJobs(job);
        createAttachment('import_jobs', csvString, p.Id);
        EmailNotifierFake fakeNotifier = new EmailNotifierFake(true, '');

        //WHEN
        test.startTest();
        BatchManageImportAttachments batch = new BatchManageImportAttachments(p.Id, 'jobs', fakeNotifier);
        string batchProcessId = Database.ExecuteBatch(batch, 1);
        test.stopTest();

        //THEN
        ApexJobTracker tracker = TestProject.getApexJobTracker();
        QA.EQ(ApexJobTracker.TrackerStatus.Success, tracker.Status, 'process succeeded:' + tracker.Response);
        QA.EQ(true, tracker.failureNotified, 'email sent out:' + tracker.Response);

        job = TestProject.getJobs(p.Id)[0];
        QA.EQ(SCHEDULE_DATE, job.JobScheduledDate__c, 'schedule date set:' + tracker.Response);
        QA.EQ(100, job.EstimatedMinutesOverride__c, 'est time set');
        QA.EQ(123, job.PurchaseOverRideAmount__c, 'purchase amount set');
    }


    // orgSetting.JAWImportFields__c = 'Name-0,ECWorkerId__c-1,FirstName__c-2,LastName__c-3,ThirdPartyAgencyStatus__c-6,ECWorkerTime__c-14';
    // orgSetting.JAWImportTitle_c__c = ' Job Attempt Worker Name,EC Worker Id,First Name,Last Name,Project Number,Project Title,3PL Status,Estimated Minutes,Location Number,Location Name,Location Address,Location City,LocationState,Start Time,EC Worker Time';

    static String genCSVStringJobAttemptWorkers(JobAttemptWorker__c j) {
        List<String> cntn = new List<String>();

        cntn.add(j.Name); // 0
        cntn.add(''); // 1
        cntn.add('first'); // 2
        cntn.add('last'); // 3
        cntn.add(''); // 4
        cntn.add(''); // 5
        cntn.add('Executed'); // 6
        cntn.add(''); // 7
        cntn.add(''); // 8
        cntn.add(''); // 9
        cntn.add(''); // 10
        cntn.add(''); // 11
        cntn.add(''); // 12
        cntn.add(''); // 13
        cntn.add('10'); // 14

        return JSON.serialize(new String[] {String.join(cntn, ',')});
    }


    @isTest
    static void itShouldImportJobAttemptWorkers() {
        ////GIVEN
        // Project__c p = TestProject.getProjects()[0];
        // JobAttemptWorker__c jaw = TestProject.getJobAttemptWorkers(p.Id)[0];
        // Contact uContact = [SELECT Id, AccountId, Account.Name from Contact WHERE Id=:jaw.Contact__c];
        // String csvString = genCSVStringJobAttemptWorkers(jaw);
        // createAttachment('import_jobattemptworker', csvString, uContact.Id);
        // EmailNotifierFake fakeNotifier = new EmailNotifierFake(true, '');

        // Profile pfl = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        // User testUser = new User(Alias = 'standt', Email = 'test.user@test.com',
        //                          EmailEncodingKey = 'UTF-8', LastName = 'Testing', LanguageLocaleKey = 'en_US',
        //                          LocaleSidKey = 'en_US', ProfileId = pfl.Id,
        //                          ThirdPartyAgency__c = uContact.Account.Name,
        //                          Contact = uContact,
        //                          TimeZoneSidKey = 'America/Los_Angeles',
        //                          UserName = 'unit.tester@test.com');

        // //WHEN
        // test.startTest();
        // System.runAs(testUser) {
        //     BatchManageImportAttachments batch = new
        //     BatchManageImportAttachments(uContact.Id, 'thirdparty', fakeNotifier);
        //     string batchProcessId = Database.ExecuteBatch(batch, 1);
        // }
        // test.stopTest();

        // //THEN
        // ApexJobTracker tracker = TestProject.getApexJobTracker();
        // QA.EQ(ApexJobTracker.TrackerStatus.Success, tracker.Status, 'process succeeded:' + tracker.Response);
        // QA.EQ(true, tracker.failureNotified, 'email sent out:' + tracker.Response);
        // JobAttemptWorker__c result = [SELECT Name, FirstName__c, LastName__c FROM JobAttemptWorker__c WHERE Id=:jaw.Id];
        // QA.EQ('first', result.FirstName__c, result.Name + ': first name should be first.' + tracker.Response);
        // QA.EQ('last', result.LastName__c, 'last name set');
    }
}