src_old/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>OneHubThirdPartyAgencyContactId__c</fullName>
        <externalId>true</externalId>
        <label>OneHub Third Party Agency ContactId</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src_old/objects/Job__c.object
<CustomObject>
    <description>Job defines the body of work to be performed at a Location and all of the dates related to the Job performance. A Job is related to a Project, Project Service, Project Location, Job Material, Contact, Exception, and Job Attempt.</description>
    <fields>
        <fullName>ProjectLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field that indicates the Location of a Project.</description>
        <inlineHelpText>The location of the project</inlineHelpText>
        <label>Project Location</label>
        <referenceTo>ProjectLocation__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SurveyPhotoViewerEncodedId__c</fullName>
        <label>Survey Photo Viewer Encoded Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Job</label>
    <nameField>
        <displayFormat>JOB-{000000000}</displayFormat>
        <label>Job ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ProjectLocation__c.object
<CustomObject>
    <description>Project Location relates a Location to a Project. Project Location is related Project, Job, and Location.</description>
    <fields>
        <fullName>BillingReviewed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Billing Reviewed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BillingStatus__c</fullName>
        <label>Billing Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Billable</fullName>
                    <default>true</default>
                    <label>Billable</label>
                </value>
                <value>
                    <fullName>NotBillable</fullName>
                    <label>Not Billable</label>
                </value>
                <value>
                    <fullName>NeedsReview</fullName>
                    <label>Needs Review</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LocationScheduledDate__c</fullName>
        <label>Location Scheduled Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OneHubThirdPartyAgencyContactId__c</fullName>
        <label>3PL Agency ContactId</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SurveyPhotoViewerEncodedId__c</fullName>
        <label>Survey Photo Viewer Encoded Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ThirdPartyAgencyContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>3PL Agency Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Project Locations</relationshipLabel>
        <relationshipName>Project_Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Location</label>
    <nameField>
        <displayFormat>PL-{0000}</displayFormat>
        <label>Location ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/SurveyPhotoViewerSetting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Iv__c</fullName>
        <label>Iv</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <label>Key</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Survey Photo Viewer</label>
</CustomObject>

force-app/main/default/classes/ProjectLocationTriggerHandler.cls
public class ProjectLocationTriggerHandler extends TriggerHandler {
    static final Blob cryptoIv;
    static final Blob cryptoKey;
    static {
        SurveyPhotoViewerSetting__c setting  = SurveyPhotoViewerSetting__c.getOrgDefaults();
        cryptoIv = Blob.ValueOf(String.valueOf(setting.Iv__c == null? '': setting.Iv__c));
        cryptoKey = Blob.ValueOf(String.valueOf(setting.Key__c == null? '': setting.Key__c));
    }
    
    public override void afterUpdate() 
    {
        
        Map<String,Date> schedDateLocationMap = new Map<String,Date>();
        
        for(ProjectLocation__c current : (List<ProjectLocation__c >) trigger.new)
        {
            ProjectLocation__c old = getOld(current.Id);
            if (current.LocationScheduledDate__c != old.LocationScheduledDate__c)    
            {                
                schedDateLocationMap.put(current.Id, current.LocationScheduledDate__c);    
            }
        }
        
        if (schedDateLocationMap.size() > 0)        
        {
            ProcessScheduledDateChanges(schedDateLocationMap);
        }
        
    }
    
    public override void beforeUpdate() {
        set<Id> projLocationIds = new set<Id>();
        
        Set<String> ThirdPartyAgencyContactIdList = new set<String>();
		Map<String, Contact> ThirdPartyAgencyContactListMap = new Map<String, Contact>();
        
        
        for(ProjectLocation__c current : (List<ProjectLocation__c >) trigger.new)
        {
            ProjectLocation__c old = getOld(current.Id);             
            
            if (String.isBlank(current.SurveyPhotoViewerEncodedId__c))
            	current.SurveyPhotoViewerEncodedId__c = processEncryption(current.Id);
            
           if (current.OneHubThirdPartyAgencyContactId__c != old.OneHubThirdPartyAgencyContactId__c){
                ThirdPartyAgencyContactIdList.add(current.OneHubThirdPartyAgencyContactId__c);
            }
            
            if (ThirdPartyAgencyContactIdList.size() > 0)        		
	        {		
	            ThirdPartyAgencyContactListMap = ProcessThirdPartyAgency(ThirdPartyAgencyContactIdList);		
	        }		
			
            if ((ThirdPartyAgencyContactListMap != null) && ThirdPartyAgencyContactListMap.size() > 0)		
            {
                if (current.OneHubThirdPartyAgencyContactId__c != old.OneHubThirdPartyAgencyContactId__c)    		
                {		
                    Contact acc = ThirdPartyAgencyContactListMap.get(current.OneHubThirdPartyAgencyContactId__c);                    		
                    
                    if (acc!= null){		
                        current.ThirdPartyAgencyContact__c = acc.Id;		
                    }
                }
            }
            
            if (current.BillingStatus__c != old.BillingStatus__c && 
                old.BillingStatus__c == CONSTANTS.BILLING_STATUS_NEEDSREVIEW)    
            {
                current.BillingReviewed__c = true;	    
            }
            
        }
    }
    
    @TestVisible 
    private static string processEncryption(Id recId){
        Blob cipherText = Crypto.encrypt('AES128', cryptoKey, cryptoIv, Blob.valueOf(recId));
        
        string encodedrecId = EncodingUtil.base64Encode(cipherText); 
        return encodedrecId;
    }
        
    private static ProjectLocation__c getOld(Id plId) {
        return (ProjectLocation__c) Trigger.oldMap.get(plId);
    }    
    
    @TestVisible
    private static void ProcessScheduledDateChanges(Map<String, Date> schedDateLocationMap) 
    {
        
        Map<String, Date> jobsSchedMap = new Map<String, Date>();       
        List<Job__c> jobs = [Select Id, name, projectlocation__c 
                             from job__c 
                             WHERE projectlocation__c in :schedDateLocationMap.keySet()];
        
        for (Job__c job: jobs)
        {
            if (schedDateLocationMap.get(job.ProjectLocation__c) != null)
            {
                jobsSchedMap.put(job.Id,schedDateLocationMap.get(job.projectlocation__c));    
            }
        }
        
        if (!jobsSchedMap.isEmpty())
        {
            List<ActionResponse> jars = JobActionsHelper.setScheduledDate(jobsSchedMap);
        }
        
    }
        
    @TestVisible
    private static Map<String, Contact> ProcessThirdPartyAgency(Set<String> ThirdPartyAgencyIdList) 		
    {		
        Map<String, Contact> ThirdPartyAgencyContactListMap = new Map<String, Contact>();  		
        
        List<Contact> contacts = [Select ID, OneHubThirdPartyAgencyContactId__c 
                                  From Contact 
                                  Where OneHubThirdPartyAgencyContactId__c in :ThirdPartyAgencyIdList];        		
        
        for (Contact contact: contacts)		
        {		
            ThirdPartyAgencyContactListMap.put(contact.OneHubThirdPartyAgencyContactId__c, contact);                		
        }      		
        
        return ThirdPartyAgencyContactListMap;		
    }

}