src_old/objects/Cycle__c.object
<CustomObject>
    <description>Cycle defines a Retailer cycle that includes a date range, type (e.g. Reset Cycle). Cycle is related to the Retailer and a Project.</description>
    <fields>
        <fullName>Retailer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>A search field that indicates the specific Retailer for this Cycle.</description>
        <inlineHelpText>Enter the retailer for this cycle.</inlineHelpText>
        <label>Retailer</label>
        <referenceTo>Retailer__c</referenceTo>
        <relationshipLabel>Cycles</relationshipLabel>
        <relationshipName>Cycles</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Cycle</label>
    <nameField>
        <label>Project Cycle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cycles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/objects/FulfillmentCenter__c.object
<CustomObject>
    <description>Fulfillment Center defines a fulfillment company that will ship materials to a Worker or Location to support a Job. Fulfillment Center is related to Material.</description>
    <fields>
        <fullName>Retailer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>A search field for the name of the retailer.</description>
        <inlineHelpText>Enter the name of the retailer.</inlineHelpText>
        <label>Retailer</label>
        <referenceTo>Retailer__c</referenceTo>
        <relationshipLabel>Fulfillment Centers</relationshipLabel>
        <relationshipName>FulfillmentCenters</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Fulfillment Center</label>
    <nameField>
        <label>Fulfillment Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fulfillment Centers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/Location__c.object
<CustomObject>
    <description>Location defines a location and its type, address, and the Retailer is it associated with. Location is related to Retailer, Job, and Project Location.</description>
    <fields>
        <fullName>PostalCode__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Postal Code</label>
        <referenceTo>PostalCode__c</referenceTo>
        <relationshipLabel>Locations (Postal Code)</relationshipLabel>
        <relationshipName>Locations1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Retailer__c</fullName>
        <label>Retailer</label>
        <referenceTo>Retailer__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/LocationAssignment__c.object
<CustomObject>
    <description>Location Assignment specifies the Execution Company for a Project Type at a specific Location. The Location Assignment is required to assign Jobs to an Execution Company for a Location. Location Assignment is related to Location, Account, and Project Type.</description>
    <fields>
        <fullName>ProjectType__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project Type</label>
        <referenceTo>ProjectType__c</referenceTo>
        <relationshipLabel>Location Assignments</relationshipLabel>
        <relationshipName>LocationAssignments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Location Assignment</label>
    <nameField>
        <displayFormat>LA-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Location Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/Material__c.object
<CustomObject>
    <description>Material defines a physical item that will be shipped to a Location to by a Fulfillment Center. Material is related to Fulfillment Center and Job Material.</description>
    <fields>
        <fullName>Retailer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Retailer</label>
        <referenceTo>Retailer__c</referenceTo>
        <relationshipLabel>Materials</relationshipLabel>
        <relationshipName>Materials</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Material</label>
    <nameField>
        <label>Material Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Materials</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectTypeService__c.object
<CustomObject>
    <description>Project Type Services relates a Service to a Project Type. Project Type Service is related to Project Type and Service.</description>
    <fields>
        <fullName>ProjectType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Type</label>
        <referenceTo>ProjectType__c</referenceTo>
        <relationshipLabel>Project Type Services</relationshipLabel>
        <relationshipName>ProjectTypeServices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Type Service</label>
    <nameField>
        <displayFormat>PTS-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Type Services</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/RetailerService__c.object
<CustomObject>
    <description>Retailer Service relates Services to a Retailer, which determines the Services that are available when building a Project Service. Retailer Service is related to Retailer and Service.</description>
    <fields>
        <fullName>Retailer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Retailer</label>
        <referenceTo>Retailer__c</referenceTo>
        <relationshipLabel>Retailer Services</relationshipLabel>
        <relationshipName>RetailerService_Retailers</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Retailer Service</label>
    <nameField>
        <displayFormat>RTSR-{000}</displayFormat>
        <label>Retailer Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retailer Services</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/RetailerServiceCertification__c.object
<CustomObject>
    <description>Retailer Service Certification relates Certifications to a Retailer, which determines the Services that are available when building a Project Service. Retailer Service Certification is related to Retailer, Service, and Certification.</description>
    <fields>
        <fullName>Retailer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Retailer</label>
        <referenceTo>Retailer__c</referenceTo>
        <relationshipLabel>Retailer Service Certifications</relationshipLabel>
        <relationshipName>Retailer_Service_Certifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Retailer Service Certification</label>
    <nameField>
        <displayFormat>RSC-{000000000}</displayFormat>
        <label>Retailer Service Certification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retailer Service Certifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/objects/RetailerServiceEquipment__c.object
<CustomObject>
    <description>Retailer Service Equipment relates Equipment to a Retailer, which determines the Equipment that are available when building a Project Service. Retailer Service Equipment is related to Retailer, Service, and Equipment.</description>
    <fields>
        <fullName>Retailer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Retailer</label>
        <referenceTo>Retailer__c</referenceTo>
        <relationshipLabel>Retailer Service Equipment</relationshipLabel>
        <relationshipName>RetailerServiceEquipment</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Retailer Service Equipment</label>
    <nameField>
        <displayFormat>RSE-{0000}</displayFormat>
        <label>Retailer Service Equipment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retailer Service Equipment</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/Target__c.object
<CustomObject>
    <description>Target defines what a Worker will observe and answer questions about. Targets could include Products, Categories, Displays, or any other type of Target configured for an instance. Target is related to Project Service Target and Retailer.</description>
    <fields>
        <fullName>Retailer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Retailer</label>
        <referenceTo>Retailer__c</referenceTo>
        <relationshipLabel>Targets</relationshipLabel>
        <relationshipName>Targets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Target</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Targets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/TestDataVerificationTest.cls
@isTest
private class TestDataVerificationTest
{
    static List<SObject> rs;
    SObject r;

    @testSetup static void init(){
        TestUtil.initBaseData();
    }

    @isTest static void testPostalCodesReady(){
        rs = TestUtil.getRecordset('PostalCode__c');
        System.assertEquals(2,rs.size(),'two postal codes are inited.');
    }
    @isTest static void testAccountsReady(){
        rs = TestUtil.getRecordset('Account');
        System.assertEquals(2,rs.size(), 'two accounts created.');
    }
    @isTest static void testContactsReady(){
        rs = TestUtil.getRecordset('Contact');
        System.assertEquals(12, rs.size(), 'two contacts created.');
    }
    @isTest static void testLanguagsReady(){
        rs = TestUtil.getRecordset('Language__c');
        System.assertEquals(1, rs.size(),'one language created.');
    }
    @isTest static void testRetailerReady(){
        rs= TestUtil.getRecordset('Retailer__c');
        System.assertEquals(1,rs.size(),'One retailer created.');
    }
    @isTest static void testProjectTypeReady(){
        rs = TestUtil.getRecordset('ProjectType__c');
        System.assertEquals(1,rs.size(),'One project type created.');
    }
    @isTest static void testCycleReady(){
        rs = TestUtil.getRecordset('Cycle__c');
        System.assertEquals(TestDataUtil.MaxCountSmall, rs.size(),'Cycles created.');
    }
    @isTest static void testProjectScheduleOptionsReady(){
        rs = TestUtil.getRecordset('ScheduleOption__c');
        System.assertEquals(3, rs.size(),'3 schedule options created.');
    }
    @isTest static void testProjectTypeCustomSettingReady(){
        rs = TestUtil.getRecordset('ProjectTypeCustomSettings__c');
        System.assertEquals('Merchandising', rs.get(0).get('Name'), 'one project type custom setting created.');
    }
    @isTest static void testEquipmentsReady(){
        rs = TestUtil.getRecordset('Equipment__c');
        System.assertEquals(TestDataUtil.MaxCountSmall,rs.size(),'equipments ready.');
    }
    @isTest static void testLocationsReady(){
        rs = TestUtil.getRecordset('Location__c');
        System.assertEquals(TestDataUtil.MaxCountLarge, rs.size(),'Locations created.');
    }
    @isTest static void testLocationAssignmentReady(){
        rs = TestUtil.getRecordset('LocationAssignment__c');
        System.assertEquals(TestDataUtil.MaxCountLarge, rs.size(),'LocationAssignment created.');
    }
    @isTest static void testCertificationsReady(){
        rs = TestUtil.getRecordset('Certification__c');
        System.assertEquals(TestDataUtil.MaxCountSmall,rs.size(),'Certifications created.');
    }
    @isTest static void testTargetsReady(){
        rs = TestUtil.getRecordset('Target__c');
        System.assertEquals(TestDataUtil.MaxCountSmall, rs.size(),'Targets Ready.');
    }
    @isTest static void testFulfillmentsReady(){
        rs = TestUtil.getRecordset('FulfillmentCenter__c');
        System.assertEquals(2, rs.size(),'fulfillmentcenters created.');
    }
    @isTest static void testMaterialReady(){
        rs = TestUtil.getRecordset('Material__c');
        System.assertEquals(2,rs.size(),'materials created.');
    }
    @isTest static void testServicesReady(){
        rs = TestUtil.getRecordset('Service__c');
        System.assertEquals(3,rs.size(),'3 services created.');
    }
    @isTest static void testProjectTypeServicesReady(){
        rs = TestUtil.getRecordset('ProjectTypeService__c');
        System.assertEquals(3, rs.size(),'3 project type services created.');
    }

    @isTest static void testRetailerServicesReady(){
        rs = TestUtil.getRecordset('RetailerService__c');
        System.assertEquals(3,rs.size(),'3 retailer services created.');
    }
    @isTest static void testQuestionsReady(){
        rs = TestUtil.getRecordset('Question__c');
        QA.isTrue(rs.size() > 0, 'question created');
    }
    
    @isTest static void testQuestionResponsesReady(){
        rs = TestUtil.getRecordset('QuestionDefinedResponse__c');
        QA.isTrue(rs.size() > 0, 'defined reponses created');
    }
    @isTest static void testAttributesReady(){
        rs = TestUtil.getRecordset('Attribute__c');
        System.assertEquals(9, rs.size(),'4 attributes created.');
    }
    @isTest static void testServiceAttributesReady(){
        rs =TestUtil.getRecordset('ServiceAttribute__c');
        System.assertEquals(27, rs.size(),'3 service attributes created.');
    }
    @isTest static void testServiceQuestionsReady(){
        rs = TestUtil.getRecordset('ServiceQuestion__c');
        QA.isTrue(rs.size() > 0, 'service question created.');
    }
    @isTest static void  testServiceQuestionResponsesReady(){
        rs = TestUtil.getRecordset('ServiceQuestionDefinedResponse__c');
        System.assertEquals(true, rs.size() > 0,'3 service question responses created.');
    }
    @isTest static void testRetailerServiceEquipmentReady(){
        rs = TestUtil.getRecordset('RetailerServiceEquipment__c');
        System.assertEquals(15, rs.size(),'retailer service equipments ready.');
    }
    @isTest static void testRetailerServiceCertificationsReady(){
        rs = TestUtil.getRecordset('RetailerServiceCertification__c');
        System.assertEquals(15,rs.size(),'retailer service certifications ready.');
    }
}