src_old/objects/Datasource__c.object
<CustomObject>
    <description>Data source for import data defintion</description>
    <label>Datasource</label>
    <nameField>
        <label>Datasource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Datasources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/objects/ImportRequestQueue__c.object
<CustomObject>
    <description>Import Request Queue</description>
    <fields>
        <fullName>Datasource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Datasource</label>
        <referenceTo>Datasource__c</referenceTo>
        <relationshipLabel>DatasourceInfos</relationshipLabel>
        <relationshipName>DatasourceInfo_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RequestDate__c</fullName>
        <label>Reuqest Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Requestor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Requestor</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Requestorss</relationshipLabel>
        <relationshipName>Requestors_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status</description>
        <inlineHelpText>Status</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Init</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Queued</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>ImportRequestQueue</label>
    <nameField>
        <displayFormat>IRQ-{0000000000}</displayFormat>
        <label>ImportRequestQueue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ImportRequestQueues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/objects/ImportRequestQueueItem__c.object
<CustomObject>
    <description>Import request queue item</description>
    <fields>
        <fullName>AttachmentId__c</fullName>
        <label>Attachment</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Datasource__c</fullName>
        <description>Data Source ID</description>
        <formula>Queue__r.Datasource__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Datasource</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Parentss</relationshipLabel>
        <relationshipName>Parents_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Queue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Queue</label>
        <referenceTo>ImportRequestQueue__c</referenceTo>
        <relationshipLabel>Queues</relationshipLabel>
        <relationshipName>Queue_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requestor__c</fullName>
        <formula>Queue__r.Requestor__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Requestor</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RetryCount__c</fullName>
        <label>Retry Count</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>queue item status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Queued</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>ImportRequestQueueItem</label>
    <nameField>
        <displayFormat>I-{00000}</displayFormat>
        <label>ImportRequestQueueItem Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ImportRequestQueueItems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planning</fullName>
                    <default>true</default>
                    <label>Planning</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Launched</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ended</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/classes/lwcImportProgramTest.cls
@istest
private class lwcImportProgramTest {
    
    @testSetup
    static void setup(){
        TestDataUtil.init();
        TestProject.create('demo');
        DatasourceTest.makeData();
    }

    static String getDatasourceId() {
        return [SELECT Id from Datasource__c limit 1].Id;
    }

    @istest
    static void itShouldCreateRequestQueue() {
        //GIVEN
        String datasource = getDatasourceId();

        //WHEN
        test.startTest();
        ImportRequestQueueWrapper result =lwcImportProgramController.createRequestQueue(datasource);
        test.stopTest();

        //THEN
        QA.EQ(datasource, result.datasource, 'queue created');
    }


    static ImportRequestQueue__c genTestQueue(String datasource) {
        ImportRequestQueue__c que = new ImportRequestQueue__c(
            Datasource__c = datasource,
            RequestDate__c = Datetime.now(),
            Requestor__c = UserInfo.getUserId(),
            Status__c = 'Init'
        );
        insert que;
        return que;
    }

    static String genProjectData(){
        return TestProject.getProjects()[0].Id;
    }

    @istest
    static void itShouldAddRequestQueueItem() {
        //GIVEN
        List<String[]> content = new List<String[]>{
           new String[]{'1','2'}
        };
        String datasource = getDatasourceId();
        String projectId = genProjectData();
        String queueId = genTestQueue(datasource).Id;


        //WHEN
        test.startTest();
        WebApiResult result = lwcImportProgramController.addRequestQueueItem(queueId, projectId, content);
        test.stopTest();

        //THEN
        QA.EQ(1, result.status,'queueItem added.');
        Attachment att = [SELECT name from Attachment WHERE ParentId = :queueId LIMIT 1];
        QA.EQ('import_request_queue', att.name, 'attachment created.');
    }

    static ImportRequestQueue__c genQueueData(string datasource) {
          ImportRequestQueue__c que = new ImportRequestQueue__c(
            Datasource__c = datasource,
            RequestDate__c = Datetime.now(),
            Requestor__c = UserInfo.getUserId(),
            Status__c = 'Init'
        );
        insert que;
        return que;
    }

    @isTest
    static void itShouldQueueImportRequest() {
        
        //GIVEN
        String datasource = getDatasourceId();
        ImportRequestQueue__c q = genQueueData(datasource);
        
        //WHEN
        test.startTest();
        WebApiResult res = lwcImportProgramController.submitQueue(q.Id);
        test.stopTest();

        //THEN
        ImportRequestQueue__c result = [SELECT Id,status__C FROM ImportRequestQueue__c limit 1];
        QA.EQ('Queued', result.status__c, 'should be queued');
    }

    static void genQueueItem(String queueId, String projectId){
          Attachment att = new Attachment();
            att.ParentId = queueId;
            att.Body = Blob.valueOf(JSON.serialize('123'));
            att.ContentType = 'application/json';
            att.Name = 'import_request_queue';
            insert att;

            ImportRequestQueueItem__c queItem = new ImportRequestQueueItem__c(
                AttachmentId__c = att.Id,
                Project__c = projectId,
                RetryCount__c = 0,
                Queue__c = queueId,
                Status__c = 'Queued'
            );
        insert queItem;
    }

    @isTest
    static void itShouldDeleteRequestQueueAndItem(){
        //GIVEN
        String datasource = getDatasourceId();
        String projectId = genProjectData();
        ImportRequestQueue__c q = genQueueData(datasource);
        genQueueItem(q.Id, projectId);

        //WHEN
        test.startTest();
        WebApiResult res = lwcImportProgramController.deleteQueue(q.Id);
        test.stopTest();

        //THEN
        Integer count = Database.countQuery('SELECT count() from ImportRequestQueueItem__c');
        QA.EQ(0, count, 'no queue items');
        count = Database.countQuery('SELECT count() FROM ImportRequestQueue__c');
        QA.EQ(0, count, 'no queue');
    }
}