src_old/objects/Datasource__c.object
<CustomObject>
    <description>Data source for import data defintion</description>
    <label>Datasource</label>
    <nameField>
        <label>Datasource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Datasources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/objects/ImportRequestQueue__c.object
<CustomObject>
    <description>Import Request Queue</description>
    <fields>
        <fullName>Datasource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Datasource</label>
        <referenceTo>Datasource__c</referenceTo>
        <relationshipLabel>DatasourceInfos</relationshipLabel>
        <relationshipName>DatasourceInfo_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EndTime__c</fullName>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Requestor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Requestor</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Requestorss</relationshipLabel>
        <relationshipName>Requestors_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <label>Processing Result</label>
        <length>8192</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>StartTime__c</fullName>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status</description>
        <inlineHelpText>Status</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Init</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Queued</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>ImportRequestQueue</label>
    <nameField>
        <displayFormat>IRQ-{0000000000}</displayFormat>
        <label>ImportRequestQueue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ImportRequestQueues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/objects/ImportRequestQueueItem__c.object
<CustomObject>
    <description>Import request queue item</description>
    <fields>
        <fullName>AttachmentId__c</fullName>
        <label>Attachment</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BatchJobAssigned__c</fullName>
        <defaultValue>false</defaultValue>
        <description>the batch job is assigned</description>
        <label>BatchJobAssigned</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BatchJobId__c</fullName>
        <description>batch job id</description>
        <label>BatchJobId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ConsumerAppClassName__c</fullName>
        <formula>Queue__r.Datasource__r.ConsumerApexClass__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ConsumerAppClassName</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Datasource__c</fullName>
        <description>Data Source ID</description>
        <formula>Queue__r.Datasource__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Datasource</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EndTime__c</fullName>
        <label>End time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ErrorAttachment__c</fullName>
        <description>Error attachment ID</description>
        <label>Error Attachment</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ErrorCount__c</fullName>
        <label>ErrorCount</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Parentss</relationshipLabel>
        <relationshipName>Parents_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Queue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Queue</label>
        <referenceTo>ImportRequestQueue__c</referenceTo>
        <relationshipLabel>Queues</relationshipLabel>
        <relationshipName>Queue_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecordCount__c</fullName>
        <label>RecordCount</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Requestor__c</fullName>
        <formula>Queue__r.Requestor__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Requestor</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <label>Response</label>
        <length>8192</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>RetryCount__c</fullName>
        <label>Retry Count</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>StartTime__c</fullName>
        <label>Start time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>queue item status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Queued</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SuccessCount__c</fullName>
        <label>SuccessCount</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>ImportRequestQueueItem</label>
    <nameField>
        <displayFormat>I-{00000}</displayFormat>
        <label>ImportRequestQueueItem Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ImportRequestQueueItems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/objects/OrgCustomSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Generic org settings will be stored here</description>
    <fields>
        <fullName>MaximumRetryCount__c</fullName>
        <defaultValue>3</defaultValue>
        <description>Maximum retry count</description>
        <label>MaximumRetryCount</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Org Custom Settings</label>
</CustomObject>

src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planning</fullName>
                    <default>true</default>
                    <label>Planning</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Launched</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ended</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <recordTypes>
        <fullName>Locked</fullName>
        <active>true</active>
        <label>Locked</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/ImportRequestQueueItemBatchHandler.cls
global class ImportRequestQueueItemBatchHandler implements Database.Batchable<sObject>,
	Database.Stateful, Database.RaisesPlatformEvents {
	private String pid;
	private AppLocker locker;
	private Map<String, DatasourceWrapper> datasources;
	private static final String APP_ID = 'ImportRequestQueueItemBatchHandler';

	private ImportRequestQueueItemBatchHandler(String projectId) {
		this.pid = projectId;
		this.datasources = new Map<String, DatasourceWrapper>();
		this.locker = AppLocker.newInstance('Project', projectId, APP_ID);
	}

	global static ImportRequestQueueItemBatchHandler newInstance(String projectId) {
		return new ImportRequestQueueItemBatchHandler(projectId);
	}

	global Database.QueryLocator start(Database.BatchableContext BC) {
		String projectId = this.pid;
		return Database.getQueryLocator([SELECT
		                                 Id,
		                                 AttachmentId__c,
		                                 Requestor__c,
		                                 RecordCount__c,
		                                 RetryCount__c,
		                                 ConsumerAppClassName__c,
		                                 Datasource__c
		                                 FROM ImportRequestQueueItem__c
		                                 WHERE  Project__c = :projectId
		                                     AND Status__c = 'Queued'
		                                         AND Queue__r.Status__c IN ('Queued', 'Processing')
		                                         ORDER BY CreatedDate ASC]);
	}

	//it handle each queue item per transaction
	global void execute(Database.BatchableContext BC , List<ImportRequestQueueItem__c> items) {
		for (ImportRequestQueueItem__c item : items) {
			handleEachQueueItem(item);
		}
	}



	@testVisible
	void handleEachQueueItem(ImportRequestQueueItem__c item) {
		//step 1: ensure consumer app class is defined
		if (String.isBlank(item.ConsumerAppClassName__c)) {
			canNotHandleQueueItem(item.Id, 'Failed', 'No consumer application class configured.', 0);
			return;
		}

		//step 2: ensure project is locked
		if (!locker.isLocked()) {
			try {
				locker.lock();
				beginHandleQueueItem(item.Id);
			} catch (AppLockException lockEx) {
				handleFailedToGetLock(item.Id, lockEx.getMessage(), Integer.valueOf(item.RetryCount__c));
				return;
			}	catch (Exception ex) {
				canNotHandleQueueItem(item.Id, 'Failed', ex.getMessage(), Integer.valueOf(item.RetryCount__c));
				return;
			}
		}

		Savepoint sp = Database.setSavepoint();
		try {
			DBResult response = tryToConsumeQueueItem(item);
			deleteAttachment(item.AttachmentId__c, response);
			endHandleQueueItem(item, response);
		} catch (CustomException custEx) {
			Database.rollback(sp);
			canNotHandleQueueItem(item.Id, 'Failed', custEx.getMessage(), Integer.valueOf(item.RetryCount__c));
		} catch (Exception ex) {
			Database.rollback(sp);
			canNotHandleQueueItem(item.Id, 'Failed', ex.getMessage() + ': ' + ex.getStackTraceString(), Integer.valueOf(item.RetryCount__c));
		}
	}

	global void finish(Database.BatchableContext BC) {

		try {
			if (locker.isLocked()) {
				locker.release();
			}
		} catch (Exception ex) {
			AppLogBatch.appError(ex, 'Project:' + pid, APP_ID);
		}

		BatchProcessUtil.logBatchLevelError(BC.getJobId(), APP_ID);
	}

	DBResult tryToConsumeQueueItem(ImportRequestQueueItem__c item ) {
		List<List<String>> content;

		Savepoint sp = Database.setSavepoint();
		try {
			DatasourceWrapper datasource = getDatasource(item.Datasource__c);
			content = getAttachContent(item.AttachmentId__c);
			IExecutor consumer = (IExecutor) Reflection.newInstance(datasource.consumerClass);

			DBResult result = consumer.doExecute(new Object[] {
			                                       item.Id,
			                                       datasource,
			                                       content
			                                     });
			return result.addData('errors', consumer.getFailedContent());
		} catch (CustomException custEx) {
			Database.rollback(sp);
			return DBResult.error(content.size(), custEx.getMessage());
		} catch (AuraHandledException auraEx) {
			Database.rollback(sp);
			return DBResult.error(content.size(), auraEx.getMessage());
		} catch (Exception ex) {
			Database.rollback(sp);
			return DBResult.error(content.size(), ex.getMessage() + ':' + ex.getStackTraceString());
		}
	}

	DatasourceWrapper getDatasource(String datasourceId) {
		if (datasources.containsKey(datasourceId)) {
			return (DatasourceWrapper) datasources.get(datasourceId);
		}
		DatasourceWrapper wrapper = DatasourceWrapper.createInstance(datasourceId);
		datasources.put(datasourceId, wrapper);
		return wrapper;
	}

	static void beginHandleQueueItem(String queueItemId) {
		try {
			ImportRequestQueueItem__c q = new ImportRequestQueueItem__c(
			  Id = queueItemId,
			  StartTime__c = Datetime.now(),
			  SuccessCount__c = 0,
			  ErrorCount__c = 0,
			  EndTime__c = null,
			  Status__c = 'Processing',
			  Response__c = ''
			);
			DBX.doUpdate(q);
		} catch (Exception ex) {
			AppLogBatch.batchError(ex, 'QueueItemId:' + queueItemId , APP_ID);
		}
	}

	void endHandleQueueItem(ImportRequestQueueItem__c item, DBResult result) {

		try {
			String errorAttachmentId = result.IsSucceeded()
				? ''
				: newAttachment(item, (List<List<String>>) result.getData('errors'));
			ImportRequestQueueItem__c q = new ImportRequestQueueItem__c(
			  Id = item.Id,
			  SuccessCount__c = result.SuccessCount,
			  ErrorCount__c = result.ErrorCount,
			  EndTime__c = Datetime.now(),
			  ErrorAttachment__c = errorAttachmentId,
			  Status__c = result.IsSucceeded() ? 'Completed' : 'Failed',
			  Response__c = result.Message
			);
			DBX.doUpdate(q);
		} catch (Exception ex) {
			AppLogBatch.batchError(ex, 'QueueItemId:' + item.Id, APP_ID);
		}
	}

	@testVisible
	String newAttachment(ImportRequestQueueItem__c item, List<List<String>> content) {
		if (content == null || content.isEmpty()) {return '';}
		
		String body = addHeaderToContent(item.Datasource__c, content);
		Attachment att = new Attachment();
		att.ParentId = item.Id;
		att.Body = Blob.valueOf(body);
		att.ContentType = 'text/csv';
		att.Name = 'error_' + item.Id + '.csv';
		att = (Attachment) DBX.doInsert(att);
		return att.Id;
	}

	@testVisible
	String addHeaderToContent(String datasourceId, List<List<String>> content){
		List<String> result = new List<String>();
		List<String> header = new List<String>();
		DatasourceWrapper datasource = getDatasource(datasourceId);
		for(DatasourceSchemaWrapper col: datasource.schemas){
			header.add(col.title);
		}
		result.add(listToCSVString(header));
		for(List<String> r: content){
			result.add(listToCSVString(r));
		}
		
		return String.join(result,'\n');
	}

	String listToCSVString(List<String> value){
		return '"' + String.join(value, '","') + '"';
	}

	@testVisible
	static void handleFailedToGetLock(String queueItemId, String msg, Integer retryCount) {
		OrgCustomSettings__c setting = OrgCustomSettings__c.getInstance('Setting');
		Integer maxRetries = setting.MaximumRetryCount__c != null
		                     ? Integer.valueOf(setting.MaximumRetryCount__c)
		                     : 5;
		String status = 'Queued';
		String message = msg;
		if (retryCount >= maxRetries) {
			status = 'Failed';
			message = 'The maximum of retry (' + maxRetries + ') is reached. ' + msg;
		}
		canNotHandleQueueItem(queueItemId, status, message, retryCount);
	}

	@testVisible
	static void canNotHandleQueueItem(String queueItemId, String status, String msg, Integer retryCount) {
		try {
			ImportRequestQueueItem__c q = new ImportRequestQueueItem__c (
			  Id = queueItemId,
			  StartTime__c = Datetime.now(),
			  EndTime__c = Datetime.now(),
			  Status__c = status,
			  RetryCount__c = retryCount + 1,
			  Response__c = msg
			);

			if (status == 'Queued'){
				q.BatchJobAssigned__c = false;
			  q.BatchJobId__c = '';
			}

			DBX.doUpdate(q);
		} catch (Exception ex) {
			AppLogBatch.batchError(ex, 'QueueItemId:' + queueItemId , APP_ID);
		}
	}

	static List<List<String>> getAttachContent(String attId) {
		Attachment att = getAttachment(attId);
		List<List<String>> content = (List<List<String>>) JSON.deserialize(att.body.toString(), List<List<String>>.class);
		if (content.isEmpty()) {
			throw new CustomException('The attachment failed to deserialized.');
		}
		return content;
	}

	static Attachment getAttachment(String attId) {
		List<Attachment> attList = [SELECT Body, BodyLength FROM Attachment WHERE Id = :attId];
		if (attList.isEmpty()) {
			throw new CustomException('Attachment Not Found');
		}
		if (attList.get(0).BodyLength == 0) {
			throw new CustomException('Attachment Is Empty');
		}
		return attList.get(0);
	}

	static void deleteAttachment(String attId, DBResult result) {
		if (result.IsSucceeded()) {
			Attachment att = new Attachment(Id = attId);
			DBX.doDelete(att);
		}
	}
}