src_old/objects/Datasource__c.object
<CustomObject>
    <description>Data source for import data defintion</description>
    <fields>
        <fullName>ConsumerApexClass__c</fullName>
        <label>Consumer ApexClass</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LockProject__c</fullName>
        <defaultValue>false</defaultValue>
        <label>LockProject</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>StopImport__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>The data source is not allowed to import if there is any invalid value</inlineHelpText>
        <label>Stop import if there is invalid value</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TargetObject__c</fullName>
        <label>Target SObject</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Datasource</label>
    <nameField>
        <label>Datasource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Datasources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/objects/DatasourceGuide__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Datasource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Datasource</label>
        <referenceTo>Datasource__c</referenceTo>
        <relationshipLabel>GuideDataSource</relationshipLabel>
        <relationshipName>DataSource_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Guide__c</fullName>
        <label>Guide</label>
        <length>2048</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>DatasourceGuide</label>
    <nameField>
        <displayFormat>DSG-{00000}</displayFormat>
        <label>DatasourceGuide Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DatasourceGuides</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/objects/DatasourceSchema__c.object
<CustomObject>
    <fields>
        <fullName>DataType__c</fullName>
        <description>data type</description>
        <label>Data Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>DateTime</fullName>
                </value>
                <value>
                    <fullName>Float</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                </value>
                <value>
                    <fullName>Time</fullName>
                </value>
                <value>
                    <fullName>Boolean</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Datasource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Datasource</label>
        <referenceTo>Datasource__c</referenceTo>
        <relationshipLabel>SchemaDatasource</relationshipLabel>
        <relationshipName>DatasourceId_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Field__c</fullName>
        <label>target sobject field api name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GroupBy__c</fullName>
        <defaultValue>false</defaultValue>
        <label>GroupBy</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Key</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Data Column Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>data file column title</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Updatable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Updatable</label>
        <type>Checkbox</type>
    </fields>
    <label>DatasourceSchema</label>
    <nameField>
        <displayFormat>DSS-{00000}</displayFormat>
        <label>DatasourceSchema Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DatasourceSchemas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/objects/OrgCustomSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Generic org settings will be stored here</description>
    <fields>
        <fullName>DataImportChunkSize__c</fullName>
        <description>Data import attachment chunk size, which is used by import jobs from program process</description>
        <label>Data Import Chunk Size</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Org Custom Settings</label>
</CustomObject>

force-app/main/default/classes/DatasourceWrapper.cls
public with sharing class DatasourceWrapper {
    public String consumerClass {get;private set;}
    public String targetObject {get; private set;}
    @AuraEnabled
    public String id {get; private set;}
    @AuraEnabled
    public Integer chunkSize {get; private set;}
    @AuraEnabled
    public string name {get;private set;}
    @AuraEnabled
    public Integer stopImport {get; private set;} 
    @AuraEnabled
    public Integer lockProject {get;private set;}
    @AuraEnabled
    public List<String> guides {get;private set;}
    @AuraEnabled
    public List<DatasourceSchemaWrapper> schemas {get; private set;}

    private DatasourceWrapper(String id){
        this.chunkSize = getChunkSize(); 
        this.initDatasource(id);
        this.initGuides(id);
        this.initSchemas(id);
    }

    static Integer getChunkSize() {
        OrgCustomSettings__c setting = OrgCustomSettings__c.getInstance('Setting');
        return setting.DataImportChunkSize__c > 0 
            ? Integer.valueOf(setting.DataImportChunkSize__c)
            : 1000; 
    }

    public static DatasourceWrapper createInstance(String recordId) {
        return new DatasourceWrapper(recordId);
    }

    void initDatasource(String recordId) {
        Datasource__c datasource = getDatasource(recordId);
        this.id = datasource.Id;
        this.name = datasource.Name;
        this.consumerClass = datasource.ConsumerApexClass__c;
        this.targetObject = datasource.TargetObject__c;
        this.stopImport = datasource.StopImport__c ? 1 : 0;
        this.lockProject = datasource.LockProject__c ? 1 : 0; 
    }

    Datasource__c getDatasource(String recordId) {
        List<Datasource__c> dsRS = [SELECT Id, name, TargetObject__c, StopImport__c,ConsumerApexClass__c, LockProject__c from Datasource__c where Id = :recordId];
        if (dsRS.isEmpty()){
            throw new AuraHandledException('The datasource is not found:' + recordId);
        }
        return dsRS[0];
    }

    void initGuides(String datasourceId){
        List<DatasourceGuide__c> rs = [SELECT Guide__c FROM DatasourceGuide__c where Datasource__c = :datasourceId and Active__c = true ORDER BY Order__c];
        this.guides = new List<String>();
        for(DatasourceGuide__c r: rs){
            if (String.isNotBlank(r.Guide__c)){
                this.guides.add(r.Guide__c);
            }
        }
    }

    void initSchemas(String datasourceId){
        List<DatasourceSchema__c> rs = [
            SELECT 
                Title__c, 
                Field__c, 
                Key__c, 
                DataType__c,
                GroupBy__c, 
                Required__c, 
                Updatable__c 
            FROM DatasourceSchema__c 
            WHERE Datasource__c = :datasourceId ORDER BY Order__c];
        this.schemas = new List<DatasourceSchemaWrapper>();

        for(DatasourceSchema__c s: rs){
            if(String.isNotBlank(s.Title__c)){
                this.schemas.add(genColumn(s));
            }
        }

        if (this.schemas.size() < 2){
            throw new AuraHandledException('The schema is not defined. Please contact site administrator.');
        }
    }

    DatasourceSchemaWrapper genColumn(DatasourceSchema__c schema) {
        DatasourceSchemaWrapper v = new DatasourceSchemaWrapper();
        v.field = schema.Field__c;
        v.title = schema.Title__c;
        v.dataType = schema.DataType__c;
        v.required = schema.Required__c ? 1 : 0;
        v.updatable = schema.Updatable__c ? 1 : 0;
        v.groupBy = schema.GroupBy__c ? 1 : 0;
        v.keyed = schema.Key__c ? 1 : 0;
        return v;
    }
}