src_old/objects/Datasource__c.object
<CustomObject>
    <description>Data source for import data defintion</description>
    <label>Datasource</label>
    <nameField>
        <label>Datasource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Datasources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/objects/ImportRequestQueue__c.object
<CustomObject>
    <description>Import Request Queue</description>
    <fields>
        <fullName>Datasource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Datasource</label>
        <referenceTo>Datasource__c</referenceTo>
        <relationshipLabel>DatasourceInfos</relationshipLabel>
        <relationshipName>DatasourceInfo_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EndTime__c</fullName>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>RequestDate__c</fullName>
        <label>Reuqest Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Requestor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Requestor</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Requestorss</relationshipLabel>
        <relationshipName>Requestors_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <label>Processing Result</label>
        <length>8192</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>StartTime__c</fullName>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status</description>
        <inlineHelpText>Status</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Init</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Queued</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>ImportRequestQueue</label>
    <nameField>
        <displayFormat>IRQ-{0000000000}</displayFormat>
        <label>ImportRequestQueue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ImportRequestQueues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/classes/ImportRequestQueueWrapper.cls
public without sharing class ImportRequestQueueWrapper {
    @AuraEnabled
    public String queueId {get;set;}

    @AuraEnabled
    public String datasource {get;set;}
    
    @AuraEnabled
    public string name {get;set;}
    
    @AuraEnabled
    public string queueDate {get;set;}

    @AuraEnabled
    public string status {get;set;}
    
    @AuraEnabled
    public string requestor {get;set;}

    @AuraEnabled
    public string response {get;set;}

    @AuraEnabled
    public string startTime {get;set;}

    @AuraEnabled
    public string endTime {get;set;}

    private ImportRequestQueueWrapper(String queueId) {
        ImportRequestQueue__c q = [SELECT Id, Name,Datasource__c, Status__c, Requestor__r.Name, RequestDate__c, Response__c, StartTime__c, EndTime__c FROM ImportRequestQueue__c WHERE Id = :queueId LIMIT 1];

        this.queueId = q.Id;
        this.name = q.Name;
        this.datasource = q.Datasource__c;
        this.queueDate = formatDate(q.RequestDate__c);
        this.requestor = q.Requestor__r.Name;
        this.status = q.Status__c;
        this.response = q.Response__c;
        this.startTime = formatDate(q.StartTime__c);
        this.endTime = formatDate(q.EndTime__c);
    }

    private String formatDate(Datetime dttm){
        return dttm != null 
            ? dttm.formatLong()
            : '';
    }

    public static ImportRequestQueueWrapper newInstance(String queueId){
        return new ImportRequestQueueWrapper(queueId);
    }
}