src_old/objects/Datasource__c.object
<CustomObject>
    <description>Data source for import data defintion</description>
    <label>Datasource</label>
    <nameField>
        <label>Datasource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Datasources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/objects/Program__c.object
<CustomObject>
    <description>Program is a logical grouping of Projects for an Account and is used only for reporting purposes. Program is related to Project.</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A search field that indicates the Program relating to the Project.</description>
        <inlineHelpText>Used to logically group projects for client reporting</inlineHelpText>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectNumber__c</fullName>
        <displayFormat>{YY}{MM}{DD}{000000}</displayFormat>
        <inlineHelpText>this is help text in design</inlineHelpText>
        <label>Project Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planning</fullName>
                    <default>true</default>
                    <label>Planning</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Launched</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ended</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <recordTypes>
        <fullName>Booked</fullName>
        <active>true</active>
        <label>Booked</label>
    </recordTypes>
    <recordTypes>
        <fullName>Launched</fullName>
        <active>true</active>
        <label>Launched</label>
    </recordTypes>
    <recordTypes>
        <fullName>Planning</fullName>
        <active>true</active>
        <label>Planning</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/classes/lwcProgramController.cls
public without sharing class lwcProgramController {
    
    @AuraEnabled
    public static ProgramWrapper getProgram(String recordId){
        if (String.isBlank(recordId)){
            throw new AuraHandledException('There is no program assgined.');
        }
        Program__c program = [SELECT Name from Program__c where id = :recordId limit 1];
        
        if (program == null) {
            throw new AuraHandledException('The program not found. ' + recordId);
        }

        Datasource__c datasource = [SELECT Id from Datasource__c WHERE Name like 'Import Jobs From Program%' limit 1];
        if (datasource == null){
            throw new AuraHandledException('import datasource not found: Import Jobs From Program');
        }

        DatasourceWrapper datasourceDef = DatasourceWrapper.createInstance(datasource.Id);

        List<String[]> projects = new List<String[]>();
        List<Project__c> rs= [SELECT Id,ProjectNumber__c FROM Project__c WHERE Program__c = :recordId AND Status__c in ('Planning', 'Booked', 'In Progress', 'Launched') limit 10000];
        
        if (rs.isEmpty()){
            throw new AuraHandledException('There are no projects for the given program: ' + recordId);
        }

        for(Project__c p: rs){
            projects.add(new String[]{p.ProjectNumber__c, p.Id});
        }
        
        return ProgramWrapper.newInstance(program.name, projects, datasourceDef);
    }
}