src_old/objects/Datasource__c.object
<CustomObject>
    <description>Data source for import data defintion</description>
    <label>Datasource</label>
    <nameField>
        <label>Datasource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Datasources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/objects/Job__c.object
<CustomObject>
    <description>Job defines the body of work to be performed at a Location and all of the dates related to the Job performance. A Job is related to a Project, Project Service, Project Location, Job Material, Contact, Exception, and Job Attempt.</description>
    <fields>
        <fullName>EstimatedMinutesOverride__c</fullName>
        <label>Estimated Minutes Override</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>JobStartTime__c</fullName>
        <description>The field that indicates the local start time for the Job.</description>
        <label>Start Time (Local)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NumberOfWorkers__c</fullName>
        <defaultValue>1</defaultValue>
        <inlineHelpText>Number of workers required on this job</inlineHelpText>
        <label>Number of Workers</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field that indicates the name of the Project to which a Job belongs.</description>
        <inlineHelpText>The name of the project for this job</inlineHelpText>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PurchaseOverRideAmount__c</fullName>
        <label>Purchase OverRide Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Job</label>
    <nameField>
        <displayFormat>JOB-{000000000}</displayFormat>
        <label>Job ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <fields>
        <fullName>BundleServices__c</fullName>
        <defaultValue>true</defaultValue>
        <description>To bundle services with in the project for a specific location</description>
        <label>Bundle Services</label>
        <type>Checkbox</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/classes/ImportQueueItemConsumerTest.cls
@isTest
private class ImportQueueItemConsumerTest
{
	@testSetup
	static void beforeTest(){
		TriggerUtil.skipAllTriggers();
		TestDataUtil.init();
		TestProject.create('demo')
		.addAllWithoutJobAttempts(20);
		ImportRequestQueueTestUtil.setupDatasource();
		setNonBundledProject();
	}

	static void setNonBundledProject(){
		String pid = [SELECT Id FROM Project__c LIMIT 1].Id;
		Project__c p = new Project__c (
			BundleServices__c = false,
			Id = pid
		);
		update p;
	}

	@isTest
	static void itShouldUpdateAllJobsThePositiveWay()
	{
		// Given
		String dsId = [SELECT Id FROM Datasource__c LIMIT 1].Id;
		DatasourceWrapper datasource = 
			DatasourceWrapper.createInstance(dsId);
		List<List<String>> bodyContent = ImportRequestQueueTestUtil.genAttachmentContent();
		
		// When
		test.startTest();
		IExecutor consumer = new ImportQueueItemConsumer();
		DBResult result = consumer.doExecute(new Object[] {
			'test',
			datasource,
			bodyContent
			});
		test.stopTest();
		
		// Then
		QA.isTrue(result.IsSucceeded(), 'updated:' + result.Message);
		QA.EQ(20, result.SuccessCount, '20 jobs updated');
	}

	static boolean jobUpdated(){
		Boolean result = true;
		List<Job__c> jobs = ImportRequestQueueTestUtil.getJobs();
		for(Job__c job: jobs) {
			if (
					job.JobStartTime__c != ImportRequestQueueTestUtil.START_TIME
				|| job.PurchaseOverRideAmount__c != ImportRequestQueueTestUtil.PURCHASE_AMOUNT
				|| job.EstimatedMinutesOverride__c != ImportRequestQueueTestUtil.TIME_ESTIMATE
				|| job.NumberOfWorkers__c != ImportRequestQueueTestUtil.NUM_OF_WORKERS					
				) {
				result = false;
			}
  	}	
		return result;
	}
}