src_old/objects/EntityChangeLog__c.object
<CustomObject>
    <fields>
        <fullName>ChangeDateTime__c</fullName>
        <label>Change Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ChangeType__c</fullName>
        <label>Change Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EntityId__c</fullName>
        <label>Entity Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <label>Entity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>ProjectService</fullName>
                </value>
                <value>
                    <fullName>Job</fullName>
                </value>
                <value>
                    <fullName>JobAttemptWorker</fullName>
                </value>
                <value>
                    <fullName>Contact</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Entity Change Logs</relationshipLabel>
        <relationshipName>Entity_Change_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectService__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Service</label>
        <referenceTo>ProjectService__c</referenceTo>
        <relationshipLabel>Entity Change Logs</relationshipLabel>
        <relationshipName>Entity_Change_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Type</label>
        <referenceTo>ProjectType__c</referenceTo>
        <relationshipLabel>Entity Change Logs</relationshipLabel>
        <relationshipName>EntityChangeLogs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Entity Change Logs</relationshipLabel>
        <relationshipName>Entity_Change_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Hold</fullName>
                    <default>true</default>
                    <label>Hold</label>
                </value>
                <value>
                    <fullName>Released</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>URI__c</fullName>
        <label>URI</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Entity Change Log</label>
    <nameField>
        <displayFormat>ECL-{0000000000}</displayFormat>
        <label>Entity Change Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Entity Change Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/objects/EntityChangeType__c.object
<CustomObject>
    <fields>
        <fullName>ChangeType__c</fullName>
        <label>Change Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ConditionField__c</fullName>
        <label>Condition Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <label>Entity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>ProjectService</fullName>
                </value>
                <value>
                    <fullName>Job</fullName>
                </value>
                <value>
                    <fullName>JobAttemptWorker</fullName>
                </value>
                <value>
                    <fullName>Contact</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Field__c</fullName>
        <label>Field</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Entity Change Type</label>
    <nameField>
        <displayFormat>ECT-{00000}</displayFormat>
        <label>Entity Change Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Entity Change Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/objects/Job__c.object
<CustomObject>
    <description>Job defines the body of work to be performed at a Location and all of the dates related to the Job performance. A Job is related to a Project, Project Service, Project Location, Job Material, Contact, Exception, and Job Attempt.</description>
    <fields>
        <fullName>IsCancellable__c</fullName>
        <description>The checkbox that indicates if this Job can be canceled.</description>
        <formula>OR 
(

JobCancelOverride__c == true, 

AND(

	AND(LOWER(ProjectStatus__c) != &apos;planning&apos;, LOWER(ProjectStatus__c) != &apos;closed&apos;, LOWER(ProjectStatus__c) != &apos;pending&apos;), 
	LOWER(TEXT(JobStatus__c)) != &apos;canceled&apos;, 
	LOWER(TEXT(JobStatus__c)) != &apos;closed&apos;, 

(DATETIMEVALUE(NULLVALUE(JobScheduledDate__c, JobStartDate__c)) - NOW() - 
													((NULLVALUE(JobCancelLeadTime__c,0) - 5)/24)) &gt; 0

))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Job can be canceled if Project Status = Booked, Launched or In Progress and Job is within Cancel Lead Time.</inlineHelpText>
        <label>Cancelable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProjectService__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field that indicates the Project Service.</description>
        <inlineHelpText>The project service number</inlineHelpText>
        <label>Project Service</label>
        <referenceTo>ProjectService__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectStatus__c</fullName>
        <description>The field that indicates the status of the Project.</description>
        <formula>TEXT(Project__r.Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The status of the project</inlineHelpText>
        <label>Project Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field that indicates the name of the Project to which a Job belongs.</description>
        <inlineHelpText>The name of the project for this job</inlineHelpText>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Job</label>
    <nameField>
        <displayFormat>JOB-{000000000}</displayFormat>
        <label>Job ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ProcessLastSyncTime__c.object
<CustomObject>
    <fields>
        <fullName>CurrentProcessId__c</fullName>
        <label>Current Process Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProcessName__c</fullName>
        <label>Process Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SyncTime__c</fullName>
        <label>Sync Time</label>
        <type>DateTime</type>
    </fields>
    <label>Process Last Sync Time</label>
    <nameField>
        <label>Process Last Sync Time Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processes Last Sync Time</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <fields>
        <fullName>ProjectType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Type</label>
        <referenceTo>ProjectType__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planning</fullName>
                    <default>true</default>
                    <label>Planning</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Launched</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ended</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <recordTypes>
        <fullName>Launched</fullName>
        <active>true</active>
        <label>Launched</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ProjectService__c.object
<CustomObject>
    <description>Project Service relates a Service to a Project and is a container used to define the instance of a Service for a specific Project. Project Service is related to Project, Job, Project Service Attribute, Project Service Certification, Project Service Equipment, Project Service Material, Project Service Question, Project Service Target, and Service.</description>
    <fields>
        <fullName>ProjectStatus__c</fullName>
        <formula>TEXT(Project__r.Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProjectType__c</fullName>
        <formula>Project__r.ProjectType__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>ProjectServices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Executed</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project Service</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Services</pluralLabel>
    <recordTypes>
        <fullName>Launched</fullName>
        <active>true</active>
        <label>Launched</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectType__c.object
<CustomObject>
    <description>Project Type defines a collection of Services and sets configuration options for a Project. Project Type is related to Project, Project Type Execution Company, Project Type Service, and Location Assignment.</description>
    <label>Project Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Types</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/classes/EntityHistoryActionHelper.cls
global without sharing class EntityHistoryActionHelper {
    
    public static void RunEntityHistoryGetter() {
        BatchGetHistoryChanges batch = new BatchGetHistoryChanges();      
        Id batchJobId = Database.ExecuteBatch(batch, 1);        
    }

    global static void RunEntityHistoryGetter(String entity) {
        BatchGetHistoryChanges batch = new BatchGetHistoryChanges();      
        Id batchJobId = Database.ExecuteBatch(batch, 1);            
    }            
    
    public static ProcessLastSyncTime__c GetLastSyncTime(String entity, Id batchJobId){
        
        List<ProcessLastSyncTime__c> plsts = [Select Id, CurrentProcessId__c, SyncTime__c from ProcessLastSyncTime__c WHERE ProcessName__c =: entity LIMIT 1];
        if (plsts.isEmpty())
        {
            ProcessLastSyncTime__c plst = new ProcessLastSyncTime__c();
            plst.SyncTime__c = DateTime.Now().addMinutes(-120);
            plst.CurrentProcessId__c = '';
            plst.ProcessName__c = entity;
            plsts.add(plst);
            insert plsts;
        }
                
        //If there's an existing process running, return
        if (!string.isBlank(plsts[0].CurrentProcessId__c))
            return null; 
                        
        plsts[0].CurrentProcessId__c = string.valueOf(batchJobId);
        update plsts[0];
        
        return plsts[0];        
    }
            
    public static void UpdateSyncTime(String entity, Id jobId, Datetime syncTime){
        
        TriggerUtil.SkipAllTriggers();
        List<ProcessLastSyncTime__c> plsts = [Select Id, CurrentProcessId__c, SyncTime__c from ProcessLastSyncTime__c WHERE ProcessName__c =: entity LIMIT 1];
                
        AsyncApexJob a = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed, TotalJobItems, CreatedBy.Email FROM AsyncApexJob WHERE Id = : jobId];    

        if (a.NumberOfErrors == 0 && syncTime != null)
        {
            plsts[0].SyncTime__c = syncTime;
        }
        
        plsts[0].CurrentProcessId__c = '';            
        update plsts[0];
    }
    
    global static void ProcessHistoryChanges(List<SObject> historyLogList, String entity, Map<String,String> fieldKey) {                                                       
         
        Map<string, string> mapChangeTypes = new Map<string, string>();     
        Map<string, string> mapChangeTypesToConditionField = new Map<string, string>();             
        
        List<EntityChangeLog__c> entityChangeLogList = new List<EntityChangeLog__c>();
        EntityChangeLog__c entityChangeLog;                                                  
        
        Map<string, string> newchanges = new Map<string, string>();
        
        List<EntityChangeType__c> entityChangeTypes = [Select Id, Name, Field__c, Value__c, ChangeType__c, ConditionField__c FROM EntityChangeType__c 
                                                       WHERE Entity__c =: entity];
		
        //boolean PostJobCancellation = true; //create an entry for job cancellation only for project that are  "In Progress"
        
        for (EntityChangeType__c entityChangeType : entityChangeTypes)
        {
            string changetypekey = '';
            
            //Check for changes looking for a particular value or any        
            if (entityChangeType.Value__c == null)
                changetypekey = entityChangeType.Field__c.toLowerCase();
            else
                changetypekey = entityChangeType.Field__c.toLowerCase() + '-'+ entityChangeType.Value__c.toLowerCase();
            mapChangeTypes.put(changetypekey, entityChangeType.ChangeType__c);
            
            if (entityChangeType.ConditionField__c != null)
                mapChangeTypesToConditionField.put(changetypekey, entityChangeType.ConditionField__c);
        }
        
        for (SObject historyLog : historyLogList)
        { 
            string newValue = historyLog.get('NewValue') == null? '' : string.valueof(historyLog.get('NewValue')).toLowerCase();                       
            
            if (mapChangeTypes.get(string.valueof(historyLog.get('Field')).toLowerCase()) == null && 
                mapChangeTypes.get(string.valueof(historyLog.get('Field')).toLowerCase() + '-'+ newValue) == null )
                continue;                
            
            boolean dateLaunchedValidation = true;
            
            // For some entity we might not need Date Launched check, if dateLaunchedValidation is needed we would need to set it up in the EntityChangeSettings__c
            if (! String.isBlank(fieldKey.get('DateLaunched'))){                 
                dateLaunchedValidation = datetime.valueOf(historyLog.get('CreatedDate')) >= datetime.valueOf(getObjectValue(fieldKey.get('DateLaunched'),historyLog));                
            }            
            
            List<Job__c> jobs;  
            id jobID = Id.valueof(string.valueof(historyLog.get('ParentId')).toLowerCase());
            
            /*if(historyLog.get('ChangeType__c')=='JobCanceled'){
                jobs = [Select Id,ProjectStatus__c,IsCancellable__c  from Job__c WHERE Id = :jobID];            	
                PostJobCancellation = (jobs[0].ProjectStatus__c== constants.PROJECT_STATUS_INPROGRESS && jobs[0].IsCancellable__c == true ? true  : false);                                       
            }*/
            
            
            if (dateLaunchedValidation)                
            {
				string changetypekey = '';
                string changeType = '';
				
                if (mapChangeTypes.get(string.valueof(historyLog.get('Field')).toLowerCase() + '-'+ string.valueof(newValue).toLowerCase()) == null)
                {
                    changetypekey = string.valueof(historyLog.get('Field')).toLowerCase();
                }
                else
                {
                    changetypekey = string.valueof(historyLog.get('Field')).toLowerCase() + '-'+ string.valueof(newValue).toLowerCase();
                }
                
                changeType = mapChangeTypes.get(changetypekey);
                string conditionfield = mapChangeTypesToConditionField.get(changetypekey) == null?'':mapChangeTypesToConditionField.get(changetypekey);
                
                if (!String.isEmpty(conditionfield))
                {
                    Boolean allowLog = false;
                    if (getObjectValue(conditionfield,historyLog) != null && Boolean.valueOf(getObjectValue(conditionfield,historyLog)))
                    {
                        allowLog = true;
                    }
                    
                    //If the condition rule is false, then skip this change.
                    if (!allowLog)
                        continue;
                }
                
                //INSERT UNIQUE CHANGES ONLY for the object and change type                
                if (!newchanges.containskey(string.valueof(historyLog.get('ParentId')) + changeType ))
                {
                    entityChangeLog = new EntityChangeLog__c();
                    entityChangeLog.Entity__c = entity;
                    entityChangeLog.ChangeDateTime__c = datetime.valueOf(historyLog.get('CreatedDate'));
                    entityChangeLog.ChangeType__c = changeType;
                    
                    if (fieldKey.containskey('EntityId')){
                        entityChangeLog.EntityId__c = string.valueOf(getObjectValue(fieldKey.get('EntityId'),historyLog));
                    }
                    
                    if (fieldKey.containskey('JobId')){   
                        entityChangeLog.Job__c = string.valueof(getObjectValue(fieldKey.get('JobId'),historyLog));
                    }
                    
                    if (fieldKey.containskey('ProjectId')){ 
                        entityChangeLog.Project__c = string.valueof(getObjectValue(fieldKey.get('ProjectId'),historyLog));
                    }
                    
                    if (fieldKey.containskey('ProjectServiceId')){ 
                        entityChangeLog.ProjectService__c = string.valueof(getObjectValue(fieldKey.get('ProjectServiceId'),historyLog));
                    }
                    
                    if(fieldKey.containskey('ProjectType')){
                        entityChangeLog.ProjectType__c = string.valueof(getObjectValue(fieldKey.get('ProjectType'),historyLog));
                    }
                                        
                    String uri = AppUtil.EntityChangeLogURI;
                    
                    if(!String.isBlank(uri)){
                        
                        if (fieldKey.containskey('ProjectId')){ 
                            uri = uri + '/Project/' + entityChangeLog.Project__c;
                        }
                        
                        if (fieldKey.containskey('ServiceId')){ 
                            uri = uri + '/Service/' + string.valueof(getObjectValue(fieldKey.get('ServiceId'),historyLog));
                        }
                        
                        if(fieldKey.containskey('JobId')){
                            uri = uri + '/Job/' + entityChangeLog.Job__c;
                        }
                        
                        entityChangeLog.URI__c = uri;
                    }                    
                    
                    entityChangeLog.Status__c = 'Hold';
                    
                    entityChangeLogList.add(entityChangeLog);    
                                                           
                    newchanges.put(string.valueof(historyLog.get('ParentId')) + changeType, string.valueof(historyLog.get('ParentId')) + changeType);
                }
            }
        }
        
        if (entityChangeLogList.size() > 0)        
        {              
            insert entityChangeLogList;                
        }                
    }
   
            
    global static void ProcessHistoryChanges(String entity, Map<String,String> fieldKey,List<SObject> historyLogList) {               
      
        Map<string, string> mapChangeTypes = new Map<string, string>();     
        
        List<EntityChangeLog__c> entityChangeLogList = new List<EntityChangeLog__c>();
        EntityChangeLog__c entityChangeLog;                                                  
        
        Map<string, string> newchanges = new Map<string, string>();
        String entityToProcess;
        
        for (SObject historyLog : historyLogList)
        { 
            
            //When entity changes populate mapChangeTypes with respective EntityChangeType config info
            String key = string.valueof(historyLog.getSObjectType()).replace('__History', '');
            if (entityToProcess != key){
                
                entityToProcess = key;
                
                List<EntityChangeType__c> entityChangeTypes = [Select Id, Name, Field__c, Value__c, ChangeType__c FROM EntityChangeType__c 
                                         WHERE Entity__c =: entity]; //entityChangeTypeMap.get(key);
                for (EntityChangeType__c entityChangeType : entityChangeTypes)
                {
                    //Check for changes looking for a particular value or any        
                    if (entityChangeType.Value__c == null)
                        mapChangeTypes.put(entityChangeType.Field__c.toLowerCase(),entityChangeType.ChangeType__c); 
                    else        
                        mapChangeTypes.put(entityChangeType.Field__c.toLowerCase() + '-'+ entityChangeType.Value__c.toLowerCase(), entityChangeType.ChangeType__c); 
                }
            }  
            
            string newValue = historyLog.get('NewValue') == null? '' : string.valueof(historyLog.get('NewValue')).toLowerCase();                       
            
            if (mapChangeTypes.get(string.valueof(historyLog.get('Field')).toLowerCase()) == null && 
                mapChangeTypes.get(string.valueof(historyLog.get('Field')).toLowerCase() + '-'+ newValue) == null )
                continue;                
            
            boolean dateLaunchedValidation = true;
            
            // For some entity we might not need Date Launched check, if dateLaunchedValidation is needed we would need to set it up in the EntityChangeSettings__c
            if (! String.isBlank(fieldKey.get('DateLaunched'))){                 
                dateLaunchedValidation = datetime.valueOf(historyLog.get('CreatedDate')) >= datetime.valueOf(getObjectValue(fieldKey.get('DateLaunched'),historyLog));                
            }            
                
            if (dateLaunchedValidation)                
            {                
                string changeType = mapChangeTypes.get(string.valueof(historyLog.get('Field')).toLowerCase() + '-'+ string.valueof(newValue).toLowerCase()) == null?
                    mapChangeTypes.get(string.valueof(historyLog.get('Field')).toLowerCase()):mapChangeTypes.get(string.valueof(historyLog.get('Field')).toLowerCase() + '-'+ string.valueof(newValue).toLowerCase());
                
                //INSERT UNIQUE CHANGES ONLY for the object and change type                
                if (!newchanges.containskey(string.valueof(historyLog.get('ParentId')) + changeType ))
                {   
                    entityChangeLog = new EntityChangeLog__c();
                    entityChangeLog.Entity__c = key;
                    entityChangeLog.ChangeDateTime__c = datetime.valueOf(historyLog.get('CreatedDate'));
                    entityChangeLog.ChangeType__c = changeType;
                    entityChangeLog.EntityId__c = string.valueOf(getObjectValue(fieldKey.get('EntityId'),historyLog));
                                        
                    if (fieldKey.containskey('JobId')){   
                        entityChangeLog.Job__c = string.valueof(getObjectValue(fieldKey.get('JobId'),historyLog));
                    }
                    
                    if (fieldKey.containskey('ProjectId')){ 
                        entityChangeLog.Project__c = string.valueof(getObjectValue(fieldKey.get('ProjectId'),historyLog));
                    }
                    
                    if (fieldKey.containskey('ProjectServiceId')){ 
                        entityChangeLog.ProjectService__c = string.valueof(getObjectValue(fieldKey.get('ProjectServiceId'),historyLog));
                    }
                    
                    if(fieldKey.containskey('ProjectType')){
                        entityChangeLog.ProjectType__c = string.valueof(getObjectValue(fieldKey.get('ProjectType'),historyLog));
                    }
                    
                    String uri = AppUtil.EntityChangeLogURI;
                                        
                    if (!string.isEmpty(uri))
                    {
                        if (fieldKey.containskey('ProjectId')){ 
                            uri = uri + '/Project/' + entityChangeLog.Project__c;
                        }
                        
                        if (fieldKey.containskey('ServiceId')){ 
                            uri = uri + '/Service/' + string.valueof(getObjectValue(fieldKey.get('ServiceId'),historyLog));
                        }
                        
                        if(fieldKey.containskey('JobId')){
                            uri = uri + '/Job/' + entityChangeLog.Job__c;
                        }
                        
                        entityChangeLog.URI__c = uri;
                    }
                    
                    entityChangeLog.Status__c = 'Hold';
                    entityChangeLogList.add(entityChangeLog);
                    
                    newchanges.put(string.valueof(historyLog.get('ParentId')) + changeType, string.valueof(historyLog.get('ParentId')) + changeType);
                }
            }
        }
        
        if (entityChangeLogList.size() > 0)        
        {              
            insert entityChangeLogList;                
        }                
    }

    
    global static Object getObjectValue(string feildRef, SObject sobj){       
        
        string[] myArray = feildRef.Split('\\.');
        
        SObject obj = sobj;
        for (Integer i = 0; i < myArray.Size() -  1; i++){
            
            obj = obj.getSobject(myArray[i]);
            
        }
        return obj.get(myArray[myArray.Size() - 1]); 
    }
    
}