src_old/objects/Equipment__c.object
<CustomObject>
    <description>Equipment defines a piece of equipment that could either be an asset or tool. Equipment is related to Project Service Equipment and Retailer Service Equipment.</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>An entry field that describes the Equipment.</description>
        <inlineHelpText>Enter a description of the equipment.</inlineHelpText>
        <label>Description</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EquipmentType__c</fullName>
        <description>A picklist that indicates the type of Equipment.</description>
        <inlineHelpText>Choose the type of equipment.</inlineHelpText>
        <label>Equipment Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Asset</fullName>
                </value>
                <value>
                    <fullName>Tool</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>A checkbox that indicates if this Equipment is active</description>
        <inlineHelpText>Select this box if this equipment is active.</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ToolIconClass__c</fullName>
        <label>Tool Icon Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Equipment</label>
    <nameField>
        <label>Equipment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipment</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ProjectService__c.object
<CustomObject>
    <description>Project Service relates a Service to a Project and is a container used to define the instance of a Service for a specific Project. Project Service is related to Project, Job, Project Service Attribute, Project Service Certification, Project Service Equipment, Project Service Material, Project Service Question, Project Service Target, and Service.</description>
    <label>Project Service</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectServiceEquipment__c.object
<CustomObject>
    <description>Relates Equipment to a Project Service. Equipment from Retailer Service Equipment is added by default when a Service is added to a Project Service. Additional Equipment can also be added to the project. Project Service Equipment is related to Project Service and Equipment.</description>
    <fields>
        <fullName>Equipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Equipment</label>
        <referenceTo>Equipment__c</referenceTo>
        <relationshipLabel>Project Service Equipment</relationshipLabel>
        <relationshipName>ProjectServiceEquipment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectService__c</fullName>
        <label>Project Service</label>
        <referenceTo>ProjectService__c</referenceTo>
        <relationshipLabel>Project Service Equipment</relationshipLabel>
        <relationshipName>ProjectServiceEquipment</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Service Equipment</label>
    <nameField>
        <displayFormat>PSE-{0000000}</displayFormat>
        <label>Project Service Equipment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Service Equipment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/LightningProjectEquipmentController.cls
public with sharing class LightningProjectEquipmentController {
    
    @AuraEnabled
    public static List<EquipmentWrapper> GetProjectServiceTools(String projectServiceId) {                
        List<EquipmentWrapper> ewList = new List<EquipmentWrapper>();
        for(Equipment__c e: [SELECT Name, Id, ToolIconClass__c, Description__c, isActive__c FROM Equipment__c WHERE EquipmentType__c = 'Tool' and isActive__c = true Order By Description__c]){
            EquipmentWrapper ew = new EquipmentWrapper();
            ew.Id = e.Id;
            ew.Name = e.Name;
            ew.ToolIconClass = e.ToolIconClass__c;
            ew.Description = e.Description__c;
            ew.IsActive = false;//e.isActive__c;  
            ewList.add(ew);
        }
        
        List<ProjectServiceEquipment__c> ps = [SELECT Equipment__c FROM ProjectServiceEquipment__c WHERE Equipment__r.EquipmentType__c = 'Tool' and ProjectService__c = :projectServiceId];
        
        /*if(ps.size()==0){
            for(EquipmentWrapper ew:ewList)
            {
                ew.IsActive=false;
            }
        }
        else{*/
            for(ProjectServiceEquipment__c p: ps) 
            {
                for(EquipmentWrapper ew:ewList)
                {
                    if(p.Equipment__c == ew.Id)
                    {
                        ew.IsActive=true;
                    }
                }
            }         
        //}
        

        
        
        return ewList;
    }
    
    
    @AuraEnabled
    public static void SetProjectServiceTool(String projectServiceId, String equipmentId, boolean checked) {
        
        try
        {
            
            List<ProjectServiceEquipment__c> equipment = [Select Id from ProjectServiceEquipment__c Where ProjectService__c =: projectServiceId and Equipment__c =: equipmentId ];
            if(checked)
            {
                if(equipment.isEmpty())
                {
                    system.debug('~~b4 insert~~~~~~');
                    ProjectServiceEquipment__c newEquipment = new ProjectServiceEquipment__c (ProjectService__c= projectServiceId, Equipment__c = equipmentId) ;   
                    insert newEquipment;
                    system.debug('~~after insert~~~~~~'+newEquipment.id);
                }            
            }
            else
            {
                if(!equipment.isEmpty())
                {
                    delete equipment;
                } 
            }
        }
        catch(Exception e)
        {
             throw new System.AuraHandledException(e.getMessage());   
        }
    }
}