src_old/objects/Equipment__c.object
<CustomObject>
    <description>Equipment defines a piece of equipment that could either be an asset or tool. Equipment is related to Project Service Equipment and Retailer Service Equipment.</description>
    <label>Equipment</label>
    <nameField>
        <label>Equipment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipment</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <fields>
        <fullName>IsLocked__c</fullName>
        <defaultValue>false</defaultValue>
        <description>A checkbox that indicates that the Project is locked</description>
        <inlineHelpText>If selected, the project is locked.</inlineHelpText>
        <label>Is Locked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Retailer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Retailer</label>
        <referenceTo>Retailer__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <recordTypes>
        <fullName>Locked</fullName>
        <active>true</active>
        <label>Locked</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ProjectService__c.object
<CustomObject>
    <description>Project Service relates a Service to a Project and is a container used to define the instance of a Service for a specific Project. Project Service is related to Project, Job, Project Service Attribute, Project Service Certification, Project Service Equipment, Project Service Material, Project Service Question, Project Service Target, and Service.</description>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>ProjectServices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Retailer__c</fullName>
        <formula>Project__r.Retailer__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Retailer</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>Project Services</relationshipLabel>
        <relationshipName>ProjectServices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Service</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Services</pluralLabel>
    <recordTypes>
        <fullName>Locked</fullName>
        <active>true</active>
        <label>Locked</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/Retailer__c.object
<CustomObject>
    <description>Retailer stores the retailers for the system. Retailer is related to Location, Retailer Service, Retailer Service Certification, and Retailer Service Equipment.</description>
    <label>Retailer</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Retailers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/RetailerServiceEquipment__c.object
<CustomObject>
    <description>Retailer Service Equipment relates Equipment to a Retailer, which determines the Equipment that are available when building a Project Service. Retailer Service Equipment is related to Retailer, Service, and Equipment.</description>
    <fields>
        <fullName>Equipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Equipment</label>
        <referenceTo>Equipment__c</referenceTo>
        <relationshipLabel>Retailer Service Equipment</relationshipLabel>
        <relationshipName>RetailerServiceEquipment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsLocked__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if the equipment can be removed from project service</description>
        <inlineHelpText>Locked equipment cannot be deleted at project service level</inlineHelpText>
        <label>Is Locked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Retailer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Retailer</label>
        <referenceTo>Retailer__c</referenceTo>
        <relationshipLabel>Retailer Service Equipment</relationshipLabel>
        <relationshipName>RetailerServiceEquipment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>Retailer Service Equipment</relationshipLabel>
        <relationshipName>RetailerServiceEquipment</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Retailer Service Equipment</label>
    <nameField>
        <displayFormat>RSE-{0000}</displayFormat>
        <label>Retailer Service Equipment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retailer Service Equipment</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/Service__c.object
<CustomObject>
    <description>Service contains the definition of a service. Service is related to Service Attribute, Service Exception, Service Question, Service Question Defined Response, Retailer Service, Retailer Service Equipment, and Project Service.</description>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/ProjectServiceEquipmentEditExtTest.cls
@isTest
public class ProjectServiceEquipmentEditExtTest {

    @testSetup static void setup(){
        TestUtil.initBaseData();
        TestUtil.generateFullTestProject(ProjectType.MD, Date.today(),Date.today().addDays(2));
    }

    public static testMethod void testProjectServiceEquipmentEditExtController(){
        /*
        List<Project__c> projects = (List<Project__c>) TestUtil.getRecordset('Project__c');
        List<ProjectService__c> projServs = (List<ProjectService__c>)TestUtil.getRecordset('ProjectService__c');
        List<Equipment__c> eqpList =(List<Equipment__c>)TestUtil.getRecordset('Equipment__c');
        List<Equipment__c> eqpListNoCapImpact = (List<Equipment__c>)TestUtil.getRecordset('Equipment__c');
        
        PageReference pageRef = Page.ProjectServiceEquipmentEdit;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('Id', projServs.get(0).Id);
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(projServs.get(0));
        ProjectServiceEquipmentEditExt controllerExt = new ProjectServiceEquipmentEditExt(stdController);
        
        System.assertNotEquals(controllerExt, null,'ProjectServiceEquipmentEditExt  is null');
        System.debug('controllerExt: '+controllerExt);
        
        //test add equipment
        Integer equipmentSize = controllerExt.pseList.size();
        controllerExt.SelectedEquipment =  String.valueOf(eqpList[0].Id);
        controllerExt.SelectedQuantity = String.valueOf(10);
        controllerExt.addEquipment();
        controllerExt.loadEquipment();
        System.assertEquals(equipmentSize + 1, controllerExt.pseList.size());
        
        //test utensils
        equipmentSize = controllerExt.pseList.size();
        controllerExt.SelectedUtensilList.add(new SelectOption(eqpListNoCapImpact[0].Id, eqpListNoCapImpact[0].Name));
        controllerExt.SaveUtensil();
        //System.assertEquals(equipmentSize + 1, controllerExt.pseList.size());
        
        // -ve case
        equipmentSize = controllerExt.pseList.size();
        controllerExt.SelectedEquipment =  'failureid';
        controllerExt.SelectedQuantity = String.valueOf(10);
        controllerExt.addEquipment();
        controllerExt.loadEquipment();
        //System.assertEquals(equipmentSize, controllerExt.pseList.size());
        
        //test delete equipment
        String lastPSEId = controllerExt.pseList[controllerExt.pseList.size()-1].Id;
        equipmentSize = controllerExt.pseList.size();
        ApexPages.currentPage().getParameters().put('pseDelId', lastPSEId);
        controllerExt.deleteEquipment();
        controllerExt.loadEquipment();
        System.assertEquals(equipmentSize - 1, controllerExt.pseList.size());
        
        //test delete equipment
        equipmentSize = controllerExt.pseList.size();
        ApexPages.currentPage().getParameters().put('pseDelId', 'failureid');
        controllerExt.deleteEquipment();
        controllerExt.loadEquipment();
        System.assertEquals(equipmentSize, controllerExt.pseList.size());
        
        //test save equipment
        controllerExt.pseList[0].quantity__c = 100;
        controllerExt.saveEditRows();
        System.assertEquals(100, controllerExt.pseList[0].Quantity__c);
        
        RetailerServiceEquipment__c rse = new RetailerServiceEquipment__c();
        rse.Retailer__c = projects[0].Retailer__c;
        rse.Service__c = projServs[0].Service__c;
        rse.Equipment__c = controllerExt.pseList[0].Equipment__c;
        rse.IsLocked__c = true;
        rse.Quantity__c = 10;
        insert rse;
        //controllerExt.lockedEqupmentMap.put(rse.Equipment__c, rse.Quantity__c);
        
        //test locked equipent edit validation
        controllerExt.pseList[0].IsLocked__c = true;
        controllerExt.pseList[0].quantity__c = 9;
        controllerExt.saveEditRows();
        controllerExt.loadEquipment();
        System.assertNotEquals(9, controllerExt.pseList[0].Quantity__c);
        
        
        //test add duplicate equipment
        equipmentSize = controllerExt.pseList.size();
        controllerExt.SelectedEquipment =  String.valueOf(controllerExt.pseList[0].Equipment__c);
        controllerExt.SelectedQuantity = String.valueOf(99);
        controllerExt.addEquipment();
        controllerExt.loadEquipment();
        //system.debug('controllerExt.pseList:: ' + controllerExt.pseList);
        //system.debug('eqpList[0].Id:: ' + eqpList[0].Id);
        //system.debug('eqpList[1].Id:: ' + eqpList[1].Id);
        System.assertEquals(equipmentSize, controllerExt.pseList.size());
        
        //test add equipment with invalid qty
        equipmentSize = controllerExt.pseList.size();
        controllerExt.SelectedEquipment =  eqpList[2].Id;
        controllerExt.SelectedQuantity = String.valueOf(0);
        controllerExt.addEquipment();
        controllerExt.loadEquipment();
        System.assertEquals(equipmentSize, controllerExt.pseList.size());
       */
    }
}