src_old/objects/EventChangeNotification__e.object
<CustomObject>
    <fields>
        <fullName>EntityId__c</fullName>
        <label>Entity Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EntityType__c</fullName>
        <label>Entity Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EventType__c</fullName>
        <label>Event Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>EventChangeNotification</label>
    <pluralLabel>EventChangeNotifications</pluralLabel>
</CustomObject>

force-app/main/default/classes/EventChangeNotificationTest.cls
@isTest
public class EventChangeNotificationTest {
    
    @isTest 
    static void testValidEventChangeNotification_JobStarted() {
        
        // Create a test event instance
        EventChangeNotification__e en = new EventChangeNotification__e(EventType__c='JobStarted', 
                                             EntityType__c='Job', 
                                             EntityId__c='JOB-0123456');
        
        Test.startTest();
        
        // Publish test event
        Database.SaveResult sr = EventBus.publish(en);
        
        Test.stopTest();
        
        // Verify SaveResult value
        System.assertEquals(true, sr.isSuccess());
        
        //Check if the corresponding job attempt changed the status and DateStarted
        
    }
}