src_old/objects/Exception__c.object
<CustomObject>
    <description>Exception defines a type of exception that occurs when a Worker attempts a Job. Exception is related to Service Exception.</description>
    <fields>
        <fullName>ExceptionCodeDesc__c</fullName>
        <label>Exception Code Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ExceptionCode__c</fullName>
        <description>A field for the code that uniquely identifies this Exception.</description>
        <externalId>true</externalId>
        <inlineHelpText>The code for this exception.</inlineHelpText>
        <label>Exception Code</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Exception</label>
    <nameField>
        <label>Exception Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/objects/Job__c.object
<CustomObject>
    <description>Job defines the body of work to be performed at a Location and all of the dates related to the Job performance. A Job is related to a Project, Project Service, Project Location, Job Material, Contact, Exception, and Job Attempt.</description>
    <fields>
        <fullName>ActiveJobAttempt__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field that displays Job Attempts</description>
        <label>Active Job Attempt</label>
        <referenceTo>JobAttempt__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EstimatedMinutes__c</fullName>
        <description>The field that indicates the estimated minutes for the Job.</description>
        <formula>IF(ISBLANK(EstimatedMinutesOverride__c), ProjectService__r.EstimatedMinutes__c, EstimatedMinutesOverride__c)</formula>
        <label>Time Estimate (Minutes)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ExceptionCode__c</fullName>
        <description>The field that indicates the code of the exception.</description>
        <formula>ActiveJobAttempt__r.ExceptionCode__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The code of the exception</inlineHelpText>
        <label>Exception Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>JobManualUrl__c</fullName>
        <description>The field that displays the link to the Job manual.</description>
        <formula>ProjectService__r.JobManualURL__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Job Manual Url</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>JobScheduledDate__c</fullName>
        <description>The field that indicates the date a Job is scheduled.</description>
        <inlineHelpText>The date the job was scheduled</inlineHelpText>
        <label>Scheduled Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>JobStatus__c</fullName>
        <description>A picklist that indicates the status of the Job.</description>
        <inlineHelpText>The status of the job</inlineHelpText>
        <label>Job Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Started</fullName>
                </value>
                <value>
                    <fullName>Reported</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LocationNumber__c</fullName>
        <description>The field that indicates the location number of the Job.</description>
        <formula>Location__r.LocationNumber__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The location number of the job</inlineHelpText>
        <label>Location #</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field that indicates the location of the Job.</description>
        <inlineHelpText>The location of the job</inlineHelpText>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectNumber__c</fullName>
        <description>The field that indicates the Project Number.</description>
        <formula>Project__r.ProjectNumber__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProjectService__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field that indicates the Project Service.</description>
        <inlineHelpText>The project service number</inlineHelpText>
        <label>Project Service</label>
        <referenceTo>ProjectService__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field that indicates the name of the Project to which a Job belongs.</description>
        <inlineHelpText>The name of the project for this job</inlineHelpText>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Job</label>
    <nameField>
        <displayFormat>JOB-{000000000}</displayFormat>
        <label>Job ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/JobAttempt__c.object
<CustomObject>
    <description>Job Attempt is an attempt of a Job performed at a location. Job Attempt is related to an Exception.</description>
    <fields>
        <fullName>ExceptionCode__c</fullName>
        <label>Exception Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExceptionCommentsLong__c</fullName>
        <label>Exception Comments Long</label>
        <length>1024</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Exception__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Exception</label>
        <referenceTo>Exception__c</referenceTo>
        <relationshipLabel>Job Attempts</relationshipLabel>
        <relationshipName>Job_Attempts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Job__c</fullName>
        <label>Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Job Attempts</relationshipLabel>
        <relationshipName>Job_Attempts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PercentComplete__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Percent Complete</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Job Attempt</label>
    <nameField>
        <displayFormat>JA-{000000000}</displayFormat>
        <label>Job Attempt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Attempts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/Location__c.object
<CustomObject>
    <description>Location defines a location and its type, address, and the Retailer is it associated with. Location is related to Retailer, Job, and Project Location.</description>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LocationNumber__c</fullName>
        <label>Location Number</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>An entry field that indicates the end date of the Project.</description>
        <inlineHelpText>The last date available to complete execution</inlineHelpText>
        <label>Project End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ProjectNumber__c</fullName>
        <displayFormat>{YY}{MM}{DD}{000000}</displayFormat>
        <inlineHelpText>this is help text in design</inlineHelpText>
        <label>Project Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>An entry field that indicates the start date of the Project.</description>
        <inlineHelpText>The date available to start execution</inlineHelpText>
        <label>Project Start Date</label>
        <type>Date</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ProjectService__c.object
<CustomObject>
    <description>Project Service relates a Service to a Project and is a container used to define the instance of a Service for a specific Project. Project Service is related to Project, Job, Project Service Attribute, Project Service Certification, Project Service Equipment, Project Service Material, Project Service Question, Project Service Target, and Service.</description>
    <fields>
        <fullName>EstimatedMinutes__c</fullName>
        <inlineHelpText>Estimated Project Service minutes per rep</inlineHelpText>
        <label>Estimated Minutes</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>JobManualURL__c</fullName>
        <description>URL to access event manual</description>
        <label>Job Manual URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>ProjectNumber__c</fullName>
        <formula>Project__r.ProjectNumber__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>ProjectServices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ServiceTitle__c</fullName>
        <inlineHelpText>Description of Service -- visible to rep and client</inlineHelpText>
        <label>Service Title</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Project Service</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/classes/JobWrapper.cls
public class JobWrapper {
    
    @AuraEnabled
    public String JobId {get; set;}

    @AuraEnabled
    public String Name {get; set;}
    
    @AuraEnabled
    public Integer PercentComplete {get; set;}
    
    @AuraEnabled
    public Integer EstimatedMinutes {get; set;}
    
    @AuraEnabled
    public Date ScheduledDate {get; set;}

    @AuraEnabled
    public String Status {get; set;}
    
    @AuraEnabled
    public String ExceptionId {get; set;}
    
    @AuraEnabled
    public String ExceptionCode {get; set;}
    
    @AuraEnabled
    public String ExceptionComments {get; set;}
    
    @AuraEnabled
    public String ExceptionName {get; set;}
    
    @AuraEnabled
    public String ExceptionCodeDesc {get; set;}
    
    @AuraEnabled
    public String ServiceTitle {get; set;}
    
    @AuraEnabled
    public String ProjectTitle {get; set;}

    @AuraEnabled
    public String ProjectNumber {get; set;}

    @AuraEnabled
    public String ProjectName {get; set;}

    @AuraEnabled
    public String ProjectStartDate {get; set;}

    @AuraEnabled
    public String ProjectEndDate {get; set;}
    
    @AuraEnabled
    public String LocationNumber {get; set;}

    @AuraEnabled
    public String LocationAddress {get; set;}
    
    @AuraEnabled
    public String JobManualUrl {get; set;}
    

    
    public JobWrapper(Job__c job) {
        JobId = job.Id;
        Name = job.Name;
        if (job.ActiveJobAttempt__r.PercentComplete__c == null)
        {
            PercentComplete = 0;
        }
        else
        {
        	PercentComplete = Integer.valueOf(job.ActiveJobAttempt__r.PercentComplete__c);    
        }
        
        EstimatedMinutes = Integer.valueOf(job.EstimatedMinutes__c);        
        Status = job.JobStatus__c;
        ProjectName = job.Project__r.Name;
        ProjectNumber = job.Project__r.ProjectNumber__c;        
        ProjectStartDate = String.valueOf(job.Project__r.StartDate__c);        
        ProjectEndDate = String.ValueOf(job.Project__r.EndDate__c); 
        ExceptionId = job.ActiveJobAttempt__r.Exception__c;
        ExceptionCode = job.ActiveJobAttempt__r.ExceptionCode__c;
        ExceptionComments = job.ActiveJobAttempt__r.ExceptionCommentsLong__c;
        ExceptionName = job.ActiveJobAttempt__r.Exception__r.ExceptionCodeDesc__c;
        ExceptionCodeDesc = job.ActiveJobAttempt__r.Exception__r.ExceptionCodeDesc__c;
        ProjectTitle = job.Project__r.Name;
        ServiceTitle = job.ProjectService__r.ServiceTitle__c;
        ScheduledDate = job.JobScheduledDate__c;
        LocationNumber = job.LocationNumber__c;
        LocationAddress = job.Location__r.Address__c;
        JobManualUrl = job.ProjectService__r.JobManualUrl__c;
        
    }
}