src_old/objects/ImageServiceSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <label>UserName</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>ImageServiceSettings</label>
</CustomObject>

src_old/objects/ProjectService__c.object
<CustomObject>
    <description>Project Service relates a Service to a Project and is a container used to define the instance of a Service for a specific Project. Project Service is related to Project, Job, Project Service Attribute, Project Service Certification, Project Service Equipment, Project Service Material, Project Service Question, Project Service Target, and Service.</description>
    <fields>
        <fullName>IncludeAutoGenManual__c</fullName>
        <defaultValue>true</defaultValue>
        <description>setting to include system generated manual. Default to true</description>
        <label>Attach System Generated Manual</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>JobManualFileName__c</fullName>
        <description>Stores the file name of custom template</description>
        <label>Job Manual File Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>JobManualURL__c</fullName>
        <description>URL to access event manual</description>
        <label>Job Manual URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>JobManual__c</fullName>
        <label>JobManual</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No Manual</fullName>
                </value>
                <value>
                    <fullName>Standard</fullName>
                </value>
                <value>
                    <fullName>Custom Manual</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>isManualGenInProgress__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isManualGenInProgress</label>
        <type>Checkbox</type>
    </fields>
    <label>Project Service</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectServiceAttribute__c.object
<CustomObject>
    <description>Relates a Service Attribute to a Project Service and prepopulates default values. Service Attribute is related to Service, Project Service Attribute, and Attribute.</description>
    <fields>
        <fullName>AttachmentExt__c</fullName>
        <label>Attachment Ext</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AttachmentURL__c</fullName>
        <label>Attachment URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>AttchFileName__c</fullName>
        <label>AttchFileName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AttributeTitle__c</fullName>
        <formula>Attribute__r.AttributeTitle__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Attribute Title</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsClonedAttachment__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Cloned Attachment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProjectService__c</fullName>
        <label>Project Service</label>
        <referenceTo>ProjectService__c</referenceTo>
        <relationshipLabel>Project Service Attributes</relationshipLabel>
        <relationshipName>Project_Service_Attributes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Service Attribute</label>
    <nameField>
        <displayFormat>PSA-{00000000}</displayFormat>
        <label>Project Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Service Attributes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/GenerateURL.cls
global with sharing class GenerateURL
{
    
    @future(callout=true)
    public static void GenerateNewURL(string pscaID, string attachmentID)
    {
        DoGenerateNewURL(pscaID, attachmentID);
    }
    
    public static void GenerateNewURLNonFutureCall(string pscaID, string attachmentID)
    {
        DoGenerateNewURL(pscaID, attachmentID);
    }
    
    
    @future(callout=true)
    public static void UpdateURL(string pscaID,string attachUrl, string attachmentID)
    {
        ImageServiceSettings__c imgSvc = ImageServiceSettings__c.getValues('ImageService');
        System.debug('   attachUrl   '+ attachUrl);
        System.debug('   attachmentID  '+ attachmentID);
        if(attachmentID.indexOf('=')!=-1)
        {
            attachmentID = attachmentID.split('=')[0];
        }
        Attachment attmnt = [Select ID, ParentID, body, Name from Attachment where Id = :attachmentID limit 1];
        string cntType;
        String ext = string.valueof(attmnt.Name).split('\\.')[1].toLowerCase();
        
        if(attmnt.Name.toLowerCase().contains('pdf'))
        {
            cntType = 'application/pdf';
            ext = 'pdf';        
        }
        else if(attmnt.Name.toLowerCase().contains('jpg'))
        {
            cntType = 'image/jpeg';    
            ext = 'jpg';
        }  
        else 
            cntType = 'image/'+ ext;

        system.debug(' !!!! values ' + ext+'___'+cntType);
        
        HttpRequest req = new HttpRequest();
        req.setEndpoint(attachUrl);
        req.setMethod('PUT');
        String userName = imgSvc.UserName__c;//
        String password = imgSvc.Password__c;
        
        //create basicAuth header
        Blob headerValue = Blob.valueOf(userName + ':' + password);
        String authorizationHeader = 'Basic ' + EncodingUtil.base64Encode(headerValue);
        // set headers
        req.setHeader('Authorization', authorizationHeader);
        req.setHeader('Content-Type',cntType);
        req.setHeader('Accept', 'application/json');
        req.setHeader('if-match', '\"*\"');
        
        //set body
        System.debug('   attmnt.body   '+ attmnt.body);
        req.setBodyAsBlob(attmnt.body);
        
        //Send request
        Http http = new Http();
        HttpResponse res = new HttpResponse();
        if(!Test.isRunningTest())
        {        
            res = http.send(req);
        }
        
        //analyze the result
        System.debug('dvid result 1   '+ res.getStatus());
        System.debug('dvid result 2  '+ res.getHeader('Location'));
        
        ProjectServiceAttribute__c psca = [select AttachmentExt__c,AttachmentURL__c,AttchFileName__c from ProjectServiceAttribute__c where id=: pscaID limit 1 ];        
        psca.AttachmentExt__c = ext;
        psca.AttchFileName__c = attmnt.Name;
        update psca;
        
        
    }
    
    
    private static void DoGenerateNewURL(string pscaID, string attachmentID)
    {
		ImageServiceSettings__c imgSvc = ImageServiceSettings__c.getValues('ImageService');
        Attachment attmnt = [Select ID, ParentID, body, Name from Attachment where Id = :attachmentID limit 1];
        
        string cntType;
        String ext = string.valueof(attmnt.Name).split('\\.')[1].toLowerCase();
        
        
        if(attmnt.Name.toLowerCase().contains('pdf'))
        {
            cntType = 'application/pdf';
            ext = 'pdf';        
        }
        else if(attmnt.Name.toLowerCase().contains('jpg'))
        {
            cntType = 'image/jpeg';    
            ext = 'jpg';
        }  
        else 
            cntType = 'image/'+ ext;

        system.debug(' !!!! values ' + ext+'___'+cntType);
        String attachUrl = imgSvc.URL__c; 
        String userName = imgSvc.UserName__c;
        String password = imgSvc.Password__c;
        system.debug('~~~~' + attachUrl+'~~~~' +  imgSvc.UserName__c+  '~~~~' + imgSvc.Password__c);
        //create basicAuth header
        Blob headerValue = Blob.valueOf(userName + ':' + password);
        String authorizationHeader = 'Basic ' + EncodingUtil.base64Encode(headerValue);
        system.debug('~~~~' + authorizationHeader);        
        
        // create new attachment URL
        HttpRequest req = new HttpRequest();        
        req.setEndpoint(attachUrl);
        req.setMethod('POST');

        // set headers
        req.setHeader('Authorization', authorizationHeader);
        req.setHeader('Content-Type', cntType);
        req.setHeader('Accept', 'application/json');
        
        //set body
        //Blob body = Blob.valueOf(a.body);        
        req.setBodyAsBlob(attmnt.body);
        
        //Send request
        HttpResponse res = new HttpResponse();
        if(!Test.isRunningTest())
        {
            Http http = new Http();
            res = http.send(req);
        }        
        
        //analyze the result
        System.debug('dvid result 1   '+ res.getStatus());
        System.debug('dvid result 2  '+ res.getHeader('Location'));
        ProjectServiceAttribute__c psca = [select AttachmentExt__c,AttachmentURL__c,AttchFileName__c,projectservice__c,attributetitle__c, IsClonedAttachment__c from ProjectServiceAttribute__c where id=: pscaID limit 1];
        psca.AttachmentURL__c = res.getHeader('Location');
        psca.AttachmentExt__c = ext;
        psca.IsClonedAttachment__c = false;
        //psca.AttchFileName__c = attmnt.Name;
        update psca;
        
        if(psca.attributetitle__c==CONSTANTS.MANUAL){
        //update ps
            TriggerUtil.skipAllTriggers();
            projectservice__c ps = [select id,JobManualURL__c,IncludeAutoGenManual__c,JobManualFileName__c,JobManual__c,isManualGenInProgress__c from projectservice__C where id=:psca.projectservice__c limit 1];
            ps.JobManualURL__c = res.getHeader('Location');
            ps.IncludeAutoGenManual__c = false;
            ps.isManualGenInProgress__c=false;
            ps.JobManualFileName__c = attmnt.Name; 
        	update ps;
        }
    

        
    }
    
 
}