src_old/objects/ImportRequestQueue__c.object
<CustomObject>
    <description>Import Request Queue</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status</description>
        <inlineHelpText>Status</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Init</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Queued</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>ImportRequestQueue</label>
    <nameField>
        <displayFormat>IRQ-{0000000000}</displayFormat>
        <label>ImportRequestQueue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ImportRequestQueues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/objects/ImportRequestQueueItem__c.object
<CustomObject>
    <description>Import request queue item</description>
    <fields>
        <fullName>BatchJobAssigned__c</fullName>
        <defaultValue>false</defaultValue>
        <description>the batch job is assigned</description>
        <label>BatchJobAssigned</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BatchJobId__c</fullName>
        <description>batch job id</description>
        <label>BatchJobId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Parentss</relationshipLabel>
        <relationshipName>Parents_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Queue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Queue</label>
        <referenceTo>ImportRequestQueue__c</referenceTo>
        <relationshipLabel>Queues</relationshipLabel>
        <relationshipName>Queue_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>queue item status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Queued</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>ImportRequestQueueItem</label>
    <nameField>
        <displayFormat>I-{00000}</displayFormat>
        <label>ImportRequestQueueItem Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ImportRequestQueueItems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/objects/OrgCustomSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Generic org settings will be stored here</description>
    <fields>
        <fullName>MaxProjectsPerWakeup__c</fullName>
        <description>The maximum number of projects to handle per schedule wake up</description>
        <inlineHelpText>The maximum number of projects to handle per schedule wake up</inlineHelpText>
        <label>MaxProjectsPerWakeup</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Org Custom Settings</label>
</CustomObject>

src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planning</fullName>
                    <default>true</default>
                    <label>Planning</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Launched</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ended</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/classes/ImportRequestQueueIngestor.cls
global class ImportRequestQueueIngestor implements Schedulable {
	private static final String APP_ID = 'ImportRequestQueueIngestor';

	global static String scheduleToRun(String cronSetting) {
		return scheduleToRun(APP_ID, cronSetting);
	}

	global static String scheduleToRun(String jobName, String cronSetting) {
		ImportRequestQueueIngestor ingestor = new ImportRequestQueueIngestor();
		String cron_exp = String.isNotBlank(cronSetting)
		                  ? cronSetting
		                  : '0 15 * * * ?';
		return System.schedule(APP_ID + jobName, cron_exp, ingestor);
	}

	global void execute(SchedulableContext SC) {
		AggregateResult[] queues = getQueueItemProjectGroups();
		if (queues.size() == 0) {
			return;
		}
		List<ImportRequestQueueItem__c> qItems = new List<ImportRequestQueueItem__c>();
		String jobId;
		String projectId;
		String triggerId = SC.getTriggerId();

		for (AggregateResult que : queues) {
			if (Integer.valueOf(que.get('total')) > 0) {
				projectId = String.valueOf(que.get('projectId'));
				jobId = enqueueBatchJob(projectId, true);
				List<ImportRequestQueueItem__c> unassignedQueueItems = getBatchJobNotAssignedQueueItem(projectId);
				if (String.isNotBlank(jobId)) {
					for (ImportRequestQueueItem__c item : unassignedQueueItems) {
						qItems.add(new ImportRequestQueueItem__c(
						             Id = item.Id,
						             BatchJobId__c = jobId,
						             BatchJobAssigned__c = true
						           ));
					}
				}
			}
		}
		assignBatchJobToQueueItem(triggerId, qItems);
	}

	@testVisible
	static void assignBatchJobToQueueItem(String triggerId, List<ImportRequestQueueItem__c> qItems) {
		if (qItems.isEmpty()) return;
		try {
			DBResult result = DBX.doBulkUpdate(qItems);
			String subject = 'assignBatchJobToQueueItem: success:' + String.valueOf(result.SuccessCount) +
			                 String.valueOf(result.ErrorCount);
			if (!result.IsSucceeded()) {
				AppLogBatch.batchError(subject, result.Message, triggerId, APP_ID);
			}
		} catch (AuraHandledException auraEx) {
			AppLogBatch.batchError('Failed to assignBatchJobToQueueItem', auraEx.getMessage(), triggerId , APP_ID);
		} catch (Exception ex) {
			AppLogBatch.batchError(ex, triggerId, APP_ID);
		}
	}

	@testVisible
	static String enqueueBatchJob(String projectId, Boolean batchPerProject) {
		String jobId = '';

		try {
			ImportRequestQueueItemBatchHandler batcher =
			  ImportRequestQueueItemBatchHandler.newInstance(projectId);
			if (batchPerProject) {
				jobId = Database.executeBatch(batcher, 1);
			} else {
				jobId = Database.executeBatch(batcher);
			}

			if (jobId == '000000000000000') {
				jobId = '';
				AppLogBatch.batchWarn('Faild to submit batch job', 'The executeBatch call fails and will resbumit in the next wakeup cycle.', projectId, APP_ID);
			}
		} catch (Exception ex) {
			jobId = '';
			AppLogBatch.batchError(ex, projectId, APP_ID);
		}
		return jobId;
	}

	@testVisible
	static List<ImportRequestQueueItem__c> getBatchJobNotAssignedQueueItem(String projectId) {
		return [
		         SELECT
		         Id
		         FROM ImportRequestQueueItem__c
		         WHERE  Status__c = 'Queued'
		                            AND BatchJobAssigned__c != true
		                            AND Queue__r.Status__c IN ('Queued', 'Processing')
		                            AND Project__c = :projectId];
	}

	@testVisible
	static AggregateResult[] getQueueItemProjectGroups() {
		Integer limitSize = getMaxProjectsToHandle();
		return [
		         SELECT
		         Project__c projectId,
		         Count(Id) total
		         FROM ImportRequestQueueItem__c
		         WHERE Status__c = 'Queued'
		                           AND Queue__r.Status__c IN ('Queued', 'Processing')
		                           AND BatchJobAssigned__c != true
		                           GROUP BY Project__c
		                           LIMIT :limitSize
		       ];
	}

	@testVisible
	static Integer getMaxProjectsToHandle() {
		OrgCustomSettings__c setting = OrgCustomSettings__c.getInstance('Setting');
		return setting.MaxProjectsPerWakeup__c > 0
		       ? Integer.valueOf(setting.MaxProjectsPerWakeup__c)
		       : 50;
	}
}