src_old/objects/ImportRequestQueueItem__c.object
<CustomObject>
    <description>Import request queue item</description>
    <fields>
        <fullName>BatchJobAssigned__c</fullName>
        <defaultValue>false</defaultValue>
        <description>the batch job is assigned</description>
        <label>BatchJobAssigned</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BatchJobId__c</fullName>
        <description>batch job id</description>
        <label>BatchJobId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Parentss</relationshipLabel>
        <relationshipName>Parents_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ImportRequestQueueItem</label>
    <nameField>
        <displayFormat>I-{00000}</displayFormat>
        <label>ImportRequestQueueItem Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ImportRequestQueueItems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <fields>
        <fullName>BundleServices__c</fullName>
        <defaultValue>true</defaultValue>
        <description>To bundle services with in the project for a specific location</description>
        <label>Bundle Services</label>
        <type>Checkbox</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/classes/ImportRequestQueueIngestorTest.cls
@isTest
private class ImportRequestQueueIngestorTest {
	@testSetup
	static void setupTestData() {
		TriggerUtil.skipAllTriggers();
		TestDataUtil.init();
		TestProject.create('demo')
		.addAllWithoutJobAttempts(20);
		setProjectUnbundled();
	}

	static void setProjectUnbundled() {
		String pid = TestProject.getProjects()[0].Id;
		Project__c p = new Project__c(
		  Id = pid,
		  BundleServices__c = false
		);
		update p;
	}

	@isTest
	static void itShouldExecutedAsExpected() {
		//GIVEN
		//WHEN
		test.startTest();
		ImportRequestQueueIngestor provider = new ImportRequestQueueIngestor();
		provider.execute(new ScheduleContextFake());
		test.stopTest();

		//THEN
		QA.EQ(true, qItemsBatchJobAssigned(), 'batchjob assigned');
		QA.EQ(true, qItemsBatchJobIdAssigned(), 'batch job id assigned');
	}

	@isTest
	static void ensureBatchJobAssigned() {
		//GIVEN
		ImportRequestQueueTestUtil.setupQueueTestData();
		List<ImportRequestQueueItem__c> qItems = getQItems();
		for (ImportRequestQueueItem__c item : qItems) {
			item.BatchJobAssigned__c = true;
			item.BatchJobId__c = '1';
		}
		//WHEN
		test.startTest();
		ImportRequestQueueIngestor.assignBatchJobToQueueItem('1', qItems);
		test.stopTest();

		//THEN
		QA.EQ(true, qItemsBatchJobAssigned(), 'batchjob assigned');
	}


	@isTest
	static void itShouldGetGroupResult() {
		// Given
		ImportRequestQueueTestUtil.setupQueueTestData();

		// When
		test.startTest();
		AggregateResult[] result = ImportRequestQueueIngestor.getQueueItemProjectGroups();
		test.stopTest();

		// Then
		QA.EQ(1, result.size(), 'one project');
	}

	@isTest
	static void itShouldProcessQueues() {
		// Given
		ImportRequestQueueTestUtil.setupQueueTestData();
		String pId = TestProject.getProjects()[0].Id;

		// When
		test.startTest();
		ImportRequestQueueIngestor.enqueueBatchJob(pId, false);
		test.stopTest();

		// THEN
		QA.isTrue(ImportRequestQueueTestUtil.isQueueItemsCompleted(), 'completed:'
		          + ImportRequestQueueTestUtil.getQueueItemsStatus()  );
	}

	static List<ImportRequestQueueItem__c> getQItems() {
		return [
		         SELECT
		         Id,
		         BatchJobAssigned__c,
		         BatchJobId__c
		         FROM ImportRequestQueueItem__c
		       ];
	}

	static boolean qItemsBatchJobAssigned() {
		Boolean assigned = true;
		for (ImportRequestQueueItem__c item : getQItems()) {
			if (item.BatchJobAssigned__c != true) {
				assigned = false;
			}
		}
		return assigned;
	}

	static boolean qItemsBatchJobIdAssigned() {
		Boolean assigned = true;
		for (ImportRequestQueueItem__c item : getQItems()) {
			if (String.isBlank(item.BatchJobId__c)) {
				assigned = false;
			}
		}
		return assigned;
	}

	class ScheduleContextFake implements SchedulableContext {
		public String getTriggerId() {
			return '1';
		}
	}
}