src_old/objects/Job__c.object
<CustomObject>
    <description>Job defines the body of work to be performed at a Location and all of the dates related to the Job performance. A Job is related to a Project, Project Service, Project Location, Job Material, Contact, Exception, and Job Attempt.</description>
    <fields>
        <fullName>JobScheduledDate__c</fullName>
        <description>The field that indicates the date a Job is scheduled.</description>
        <inlineHelpText>The date the job was scheduled</inlineHelpText>
        <label>Scheduled Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field that indicates the name of the Project to which a Job belongs.</description>
        <inlineHelpText>The name of the project for this job</inlineHelpText>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Job</label>
    <nameField>
        <displayFormat>JOB-{000000000}</displayFormat>
        <label>Job ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/classes/JobTriggerHandler1Test.cls
@isTest
private class JobTriggerHandler1Test
{
    @testSetup
    static void setup(){
        TriggerUtil.skipAllTriggers();

        Date dtStart = datetime.now().date();
        Date dtEnd = datetime.now().addDays(10).date();
        TestDataUtil.init();
        TestProject tP = TestProject.create('demo', dtStart, dtEnd);
        tP.addAccount()
        .addService()
        .addLocations(2)
        .addJobs()
        .addJobAttempts('');
    }

    @isTest
    static void itShouldNotUpdateJobScheduledDateIfLessThanProjectStartDate()
    {
        // Given
        Date dtSchedule = datetime.now().addDays(-1).date();
        Project__c p = [SELECT Id from Project__c limit 1];
        List<Job__c> jobs = TestProject.getJobs(p.Id);
        for(Job__c job: jobs){
            job.JobScheduledDate__c = dtSchedule;
        }

        String err = '';
        // When
        test.startTest();
        try{
            update jobs;            
        }
        catch (DmlException dml){
            err = dml.getMessage();
        }
        test.stopTest();

        // Then
        QA.isTrue(err.length() > 0, 'should not set schedule date');
    }

    @isTest
    static void itShouldSetJobScheduledDateIfLaterThanProjectStartDate()
    {
        // Given
        Date dtSchedule = datetime.now().addDays(5).date();
        Project__c p = [SELECT Id from Project__c limit 1];
        List<Job__c> jobs = TestProject.getJobs(p.Id);
        for(Job__c job: jobs){
            job.JobScheduledDate__c = dtSchedule;
        }

        // When
        test.startTest();
        update jobs;
        test.stopTest();

        // Then
        jobs = TestProject.getJobs(p.Id);
        QA.EQ(2, jobs.size(), '2 jobs created.');
        QA.EQ(dtSchedule, jobs[0].JobScheduledDate__c, 'scheduled date should be set');
        QA.EQ(dtSchedule, jobs[1].JobScheduledDate__c, 'scheduled date should be set');
    }
}