src_old/objects/Job__c.object
<CustomObject>
    <description>Job defines the body of work to be performed at a Location and all of the dates related to the Job performance. A Job is related to a Project, Project Service, Project Location, Job Material, Contact, Exception, and Job Attempt.</description>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field that indicates the name of the Project to which a Job belongs.</description>
        <inlineHelpText>The name of the project for this job</inlineHelpText>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Job</label>
    <nameField>
        <displayFormat>JOB-{000000000}</displayFormat>
        <label>Job ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/JobAttempt__c.object
<CustomObject>
    <description>Job Attempt is an attempt of a Job performed at a location. Job Attempt is related to an Exception.</description>
    <fields>
        <fullName>Job__c</fullName>
        <label>Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Job Attempts</relationshipLabel>
        <relationshipName>Job_Attempts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PrimaryJobAttemptWorker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Job Attempt Worker</label>
        <referenceTo>JobAttemptWorker__c</referenceTo>
        <relationshipLabel>Job Attempts</relationshipLabel>
        <relationshipName>Job_Attempts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Job Attempt</label>
    <nameField>
        <displayFormat>JA-{000000000}</displayFormat>
        <label>Job Attempt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Attempts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/OrgCustomSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Generic org settings will be stored here</description>
    <label>Org Custom Settings</label>
</CustomObject>

src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/classes/ShiftNotCloseNotificationHandlerTest.cls
@isTest
private class ShiftNotCloseNotificationHandlerTest {
	
    @testSetup
    static void setup(){
        ShiftNotCloseNotificationTest.setup();
    }

    @isTest
    static void itShouldCoverUpCodes(){
        //GIVEN
        ShiftNotCloseNotificationHandler hdl = 
            ShiftNotCloseNotificationHandler.create(new List<Job__c>());

        //WHEN
        test.startTest();
        Integer errCount = hdl.ErrorCount;
        Integer total = hdl.TotalCount;
        Integer emailCount = hdl.EmailCount;
        Id emailTemplateId = ShiftNotCloseNotificationHandler.getEmailTemplateId();
        Id orgWideId = ShiftNotCloseNotificationHandler.getOrgWideEmailId();
        OrgCustomSettings__c orgSettings = ShiftNotCloseNotificationHandler.getCustomSettings(); 
        hdl.logError('job', 'test.test@test.com', 'test');
        test.stopTest();

        //THEN
        EQ(0, errCount,'err 0');
        EQ(1, hdl.ErrorCount, 'one error just added');
        EQ(0, total,'total 0');
        EQ(0, emailCount, 'email 0');
        EQ(0, hdl.shifts.size(), 'no shift');
        OK(emailTemplateId != null, 'has email template');
        
    }

    @isTest 
    static void itShouldRunExecuteAndSendEmail(){
        //GIVEN
        List<SObject> shifts = getShifts();
        Project__c project= TestProject.getProjects().get(0);
        List<JobAttempt__c> attempts = TestProject.getJobAttempts(project.Id);
        ShiftNotCloseNotificationHandler hdl = 
            ShiftNotCloseNotificationHandler.create(shifts);

        //WHEN
        test.startTest();
        OK(attempts.get(0).PrimaryJobAttemptWorker__c != null, 'primary worker assigned to job');
        hdl.execute();
        hdl.validateWhoAndWhat((Job__c)shifts.get(0));
        hdl.sendEmail((Job__c)shifts.get(0));
        hdl.doExecute();
        test.stopTest();

        //THEN

    }

    static List<SObject> getShifts(){
       return Database.query(BatchShiftNotCloseNotification.buildQuery());
    }

    static void EQ(object expected, object result, String msg) {
        System.assertEquals(expected, result, msg);
    }

    static void OK(Boolean condition,String msg){
        System.assertEquals(true, condition,msg);
    }
}