src_old/objects/Job__c.object
<CustomObject>
    <description>Job defines the body of work to be performed at a Location and all of the dates related to the Job performance. A Job is related to a Project, Project Service, Project Location, Job Material, Contact, Exception, and Job Attempt.</description>
    <fields>
        <fullName>ActiveJobAttempt__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field that displays Job Attempts</description>
        <label>Active Job Attempt</label>
        <referenceTo>JobAttempt__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsShift__c</fullName>
        <formula>UPPER(TEXT(Service__r.Specialization__c)) == &apos;SHIFT&apos;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Shift</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>JobUTCEndTime__c</fullName>
        <description>The field that indicates the UTC end time of the Job.</description>
        <label>End Time (UTC)</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field that indicates the name of the Project to which a Job belongs.</description>
        <inlineHelpText>The name of the project for this job</inlineHelpText>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Job</label>
    <nameField>
        <displayFormat>JOB-{000000000}</displayFormat>
        <label>Job ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/OrgCustomSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Generic org settings will be stored here</description>
    <fields>
        <fullName>ErrorNotificationEmail__c</fullName>
        <label>Error Notification Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NonClosedShiftEmailTemplate__c</fullName>
        <description>an email template used to send email notification that the shift is not closed within X timeframe</description>
        <label>Non Closed Shift Email Template</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Org Custom Settings</label>
</CustomObject>

src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <recordTypes>
        <fullName>Closed</fullName>
        <active>true</active>
        <label>Closed</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/ShiftNotCloseNotificationTest.cls
@isTest
public class ShiftNotCloseNotificationTest
{
    @testSetup
    public static void setup(){
        TriggerUtil.skipAllTriggers();
        TestDataUtil.init();
        TestProject.create('shift')
            .addAccount()
            .addAttributes()
            .addShiftService()
            .addLocations(1)
            .addJobs()
            .addJobAttempts()
            .addJobAttemptWorkers();
        tweakShiftsForTest();
        initTest();
    }

    static void tweakShiftsForTest(){
        Project__c p = TestProject.getProjects().get(0);
        Datetime endDTTM = Datetime.now().addMinutes(-30);
        List<Job__c> shifts = [
            SELECT Id, JobUTCEndTime__c FROM JOB__c WHERE Project__c = :p.Id];
        for(Job__c shift: shifts){
            shift.JobUTCEndTime__c = endDTTM;
        }
        update shifts;
    }

    public static void initTest(){
        initEmailTemplate();
    }

    @Future
    static void initEmailTemplate(){
        EmailTemplate et = new EmailTemplate();
        et.IsActive = true;
        et.Name = 'non_closed_shift_email_template';
        et.UIType= 'Aloha';
        et.DeveloperName = 'test';
        et.TemplateType = 'text';
        et.FolderId = UserInfo.getUserId();
        insert et;
        
    }

    @isTest 
    static void itShouldInitProperly(){
        //GIEVN
        BatchShiftNotCloseNotification notify = new BatchShiftNotCloseNotification();
        
        //WHEN
        test.startTest();
        Project__c testP = TestProject.getProjects().get(0);
        List<Job__c> testJ = TestProject.getJobs(testP.Id);
        OrgCustomSettings__c settings = TestDataUtil.getOrgCustomSettings();
        notify.start(null);
        notify.execute(null, new List<Job__c>());
        test.stopTest();
        
        //THEN
        EQ(1, testJ.size(), 'one job created');
        EQ(true, testJ.get(0).IsShift__c,'A shift job');
        EQ('no.reply@crossmark.com',settings.ErrorNotificationEmail__c,'error email setup');
        EQ('non_closed_shift_email_template',settings.NonClosedShiftEmailTemplate__c,'non closed shift email template setup');
    }

    @isTest
    static void itShouldRetrieveExpectedShifts(){
        //GIVEN
        Project__c p = TestProject.getProjects().get(0);
        List<Job__c> shifts = TestProject.getJobs(p.Id);

        //WHEN
        test.startTest();
        string sql = BatchShiftNotCloseNotification.buildQuery();
        List<Job__c> results = Database.Query(sql);
        test.stopTest();

        //THEN
        OK(shifts.get(0).ActiveJobAttempt__c != null, 'shift has An active attempt');
        EQ(shifts.size(), results.size(),'expect number of shifts returned');

    }

    @isTest
    static void isShouldCoverUpCodes(){
        //GIVEN
        BatchShiftNotCloseNotification notify = new BatchShiftNotCloseNotification();
        
        Map<String,String>error = new Map<String,String>();
        error.put('job','job');
        error.put('user','user');
        error.put('message','message');
        notify.Errors.add(error);

        //WHEN
        test.startTest();
        String errorStr = notify.genErrorString();
        String errorEmail = BatchShiftNotCloseNotification.getEmailDistribution();
        String errorRow = notify.genRow(error);
        String html = notify.genHtmlBody();
        Integer total = notify.totalCount;
        Integer errCount = notify.errorCount;
        Integer emailCount = notify.sendEmailCount;
        test.stopTest();

        //THEN
        EQ(0, total, 'total 0');
        EQ(0, errCount, ' error 0');
    }


    static void EQ(object expected, object result, String msg) {
        System.assertEquals(expected, result, msg);
    }

    static void OK(Boolean condition,String msg){
        System.assertEquals(true, condition,msg);
    }
}