src_old/objects/Job__c.object
<CustomObject>
    <description>Job defines the body of work to be performed at a Location and all of the dates related to the Job performance. A Job is related to a Project, Project Service, Project Location, Job Material, Contact, Exception, and Job Attempt.</description>
    <fields>
        <fullName>ProjectService__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field that indicates the Project Service.</description>
        <inlineHelpText>The project service number</inlineHelpText>
        <label>Project Service</label>
        <referenceTo>ProjectService__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field that indicates the name of the Project to which a Job belongs.</description>
        <inlineHelpText>The name of the project for this job</inlineHelpText>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Job</label>
    <nameField>
        <displayFormat>JOB-{000000000}</displayFormat>
        <label>Job ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <fields>
        <fullName>ApexJobName__c</fullName>
        <description>A field that indicates the apex job name of the Project.</description>
        <inlineHelpText>The apex job name of the project</inlineHelpText>
        <label>ApexJobName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BatchProcessId__c</fullName>
        <description>A field that indicates the ID number of the Batch Process for the Project.</description>
        <inlineHelpText>The ID number for the batch process.</inlineHelpText>
        <label>BatchProcessId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planning</fullName>
                    <default>true</default>
                    <label>Planning</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Launched</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ended</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ProjectService__c.object
<CustomObject>
    <description>Project Service relates a Service to a Project and is a container used to define the instance of a Service for a specific Project. Project Service is related to Project, Job, Project Service Attribute, Project Service Certification, Project Service Equipment, Project Service Material, Project Service Question, Project Service Target, and Service.</description>
    <fields>
        <fullName>LastSummaryRefreshDateTime__c</fullName>
        <label>Last Summary Refresh Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>ProjectServices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RefreshSummary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag that indicates that project service needs it&apos;s summary refreshed</description>
        <label>RefreshSummary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Executed</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project Service</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/classes/BatchCreateAttempts.cls
global class BatchCreateAttempts implements Database.Batchable<sObject>, Database.Stateful {
    
    //batch delete records, then kick off job update process
    Id[] ids;
    Date scheduledDate;
    String attemptReason;
    Set<Id> psIds = new Set<Id>(); 
    Set<Id> projectIds = new Set<Id>();

    global BatchCreateAttempts(Id[] ids, Date scheduledDate, string attemptReason) {
        
        if (ids.size() == 0) return;
        this.ids = ids;
        this.scheduledDate = scheduledDate;
        this.attemptReason = attemptReason;
    }
    
    
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        system.debug('SetJobOpenBatcher Started');
        if (String.Valueof(ids[0].getSObjectType()).containsignorecase('project__c'))       
        {
            return Database.getQueryLocator([SELECT Id, Project__c, ProjectService__c FROM Job__c WHERE Project__c IN :ids]);
        }
        else if (String.Valueof(ids[0].getSObjectType()).containsignorecase('job__c'))       
        {
            return Database.getQueryLocator([SELECT Id, Project__c, ProjectService__c  FROM Job__c WHERE Id IN :ids]);        
        } 
        return null;   
    }
   
    global void execute(Database.BatchableContext BC, List<Job__c> scope) {
    
        Id[] jobIds = new Id[]{};
        for (Job__c job: scope)
        {
            jobIds.add(job.Id);
            psIds.add(job.ProjectService__c); 
            projectIds.add(job.Project__c);           
        }

        JobActionsHelper.CreateAttempts(jobIds, scheduledDate, attemptReason);
    

        
   }
    
    global void finish(Database.BatchableContext BC) {
    
        List<Project__c> projects = [Select Id, Status__c, ApexJobName__c, BatchProcessId__c, RecordTypeId 
                                     from Project__c where Id in :projectIds];
        for (Project__c project :projects)
        {
			ProjectActionsHelper.UnlockProject(project);            
        }
        update projects; 
        

        
        List<ProjectService__c> pss = [Select Id, Name, Project__c, RefreshSummary__c, LastSummaryRefreshDateTime__c from ProjectService__c where Id IN :psIds];
        for (ProjectService__c ps : pss)
        {
            ps.RefreshSummary__c = true;

        }
        update pss;                
        
        system.debug('SetJobOpenBatcher end');
   }    
    
}