src_old/objects/Job__c.object
<CustomObject>
    <description>Job defines the body of work to be performed at a Location and all of the dates related to the Job performance. A Job is related to a Project, Project Service, Project Location, Job Material, Contact, Exception, and Job Attempt.</description>
    <fields>
        <fullName>DayNumber__c</fullName>
        <label>Day Number</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>JobStatus__c</fullName>
        <description>A picklist that indicates the status of the Job.</description>
        <inlineHelpText>The status of the job</inlineHelpText>
        <label>Job Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Started</fullName>
                </value>
                <value>
                    <fullName>Reported</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ProjectLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field that indicates the Location of a Project.</description>
        <inlineHelpText>The location of the project</inlineHelpText>
        <label>Project Location</label>
        <referenceTo>ProjectLocation__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectService__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field that indicates the Project Service.</description>
        <inlineHelpText>The project service number</inlineHelpText>
        <label>Project Service</label>
        <referenceTo>ProjectService__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field that indicates the name of the Project to which a Job belongs.</description>
        <inlineHelpText>The name of the project for this job</inlineHelpText>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Job</label>
    <nameField>
        <displayFormat>JOB-{000000000}</displayFormat>
        <label>Job ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/JobMaterial__c.object
<CustomObject>
    <description>Job Material is a helper object that stores tracking information and other Job specific information about Material needed to perform a Job.</description>
    <fields>
        <fullName>Job__c</fullName>
        <label>Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Job Materials</relationshipLabel>
        <relationshipName>Job_Materials</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Material__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Material</label>
        <referenceTo>Material__c</referenceTo>
        <relationshipLabel>Job Materials</relationshipLabel>
        <relationshipName>Job_Materials</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectServiceMaterial__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Service Material</label>
        <referenceTo>ProjectServiceMaterial__c</referenceTo>
        <relationshipLabel>Job Materials</relationshipLabel>
        <relationshipName>Job_Materials</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Job Material</label>
    <nameField>
        <displayFormat>JM-{000000000}</displayFormat>
        <label>Job Material Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Materials</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/Material__c.object
<CustomObject>
    <description>Material defines a physical item that will be shipped to a Location to by a Fulfillment Center. Material is related to Fulfillment Center and Job Material.</description>
    <label>Material</label>
    <nameField>
        <label>Material Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Materials</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planning</fullName>
                    <default>true</default>
                    <label>Planning</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Launched</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ended</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ProjectLocation__c.object
<CustomObject>
    <description>Project Location relates a Location to a Project. Project Location is related Project, Job, and Location.</description>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>ProjectLocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Job Created</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project Location</label>
    <nameField>
        <displayFormat>PL-{0000}</displayFormat>
        <label>Location ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectService__c.object
<CustomObject>
    <description>Project Service relates a Service to a Project and is a container used to define the instance of a Service for a specific Project. Project Service is related to Project, Job, Project Service Attribute, Project Service Certification, Project Service Equipment, Project Service Material, Project Service Question, Project Service Target, and Service.</description>
    <fields>
        <fullName>DayNumber__c</fullName>
        <label>DEPRECATED Day Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>ProjectServices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Executed</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project Service</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectServiceMaterial__c.object
<CustomObject>
    <description>Relates Material to a Project Service. Material is added manually when building a Project. Project Service Material is related to Project Service and Material.</description>
    <fields>
        <fullName>Material__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Material</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Material__c.IsActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Material__c</referenceTo>
        <relationshipLabel>Project Service Material</relationshipLabel>
        <relationshipName>ProjectServiceMaterial</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectService__c</fullName>
        <label>Project Service</label>
        <referenceTo>ProjectService__c</referenceTo>
        <relationshipLabel>Project Service Materials</relationshipLabel>
        <relationshipName>ProjectServiceMaterials</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Service Material</label>
    <nameField>
        <displayFormat>PSM-{00000000}</displayFormat>
        <label>Project Service Material Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Service Material</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/classes/JobUpdatesHelper.cls
public class JobUpdatesHelper {
    public static void createJobMaterials(List<Job__c> jobs, List<ProjectServiceMaterial__c> psmList) {
        system.debug('IN createJobMaterials:::: ' + jobs.size());
        system.debug('IN psmList:::: ' + psmList.size());
        if(jobs.size() > 0) {
            
            List<Job__c> jobsp = [Select Id, DayNumber__c, ProjectService__c FROM Job__c WHERE Id IN :jobs];
            List<JobMaterial__c> jmList = new List<JobMaterial__c>();
            for (Job__c job: jobsp) {
                
                for (ProjectServiceMaterial__c psm: psmList) {
                    if(psm.ProjectService__c  == job.ProjectService__c){
                        JobMaterial__c jm = new JobMaterial__c();
                        jm.Job__c = job.Id;
                        jm.Material__c = psm.Material__c;
                        jm.ProjectServiceMaterial__c = psm.id;
                        jm.Status__c = 'Pending';
                        jmList.add(jm);
                    }
                }
            }
            TriggerUtil.skipJobTrigger = true;
            system.debug('IN jmList.size():::: ' + jmList.size());
            if(jmList.size()>0){
                insert jmList;               
            }
        }
    }
    
    public static void createJobMaterials(List<Job__c> jobs, ProjectServiceMaterial__c psm) {
        createJobMaterials(jobs, new List<ProjectServiceMaterial__c>{ psm });
    }
    
    public static Set<String> createJobRelatedRecords(Id[] jobIds, Set<String> materalAddedJobs) {
        
        //Create materials only for the first day in
        //a multi day job

        Job__c[] jobs = [SELECT Id, JobStatus__c, ProjectService__c, ProjectLocation__c, Project__c, Project__r.Status__c 
                         FROM Job__c WHERE Id IN :jobIds];

        if (!jobs.isEmpty()) {
            List<JobMaterial__c> jmList = new List<JobMaterial__c>();
            Set<Id> projectIds = new Set<Id>();
            Map<Id, ProjectServiceMaterial__c[]> projectIdToServiceMaterials = new Map<Id, ProjectServiceMaterial__c[]>();

            for (Job__c job : jobs) projectIds.add(job.Project__c);
            for (ProjectServiceMaterial__c psm : [SELECT Id, Material__c, ProjectService__c, ProjectService__r.Project__c FROM ProjectServiceMaterial__c WHERE ProjectService__r.Project__c IN :projectIds]) {

                Id projId = psm.ProjectService__r.Project__c;
                if (!projectIdToServiceMaterials.containsKey(projId)) projectIdToServiceMaterials.put(projId, new ProjectServiceMaterial__c[]{});
                projectIdToServiceMaterials.get(projId).add(psm);
            }
            
            for (Job__c job : jobs) {
                if (projectIdToServiceMaterials.containsKey(job.Project__c)) {
                    for (ProjectServiceMaterial__c psm : projectIdToServiceMaterials.get(job.Project__c)) {
                        if(psm.ProjectService__c  == job.ProjectService__c){
                            JobMaterial__c jm = new JobMaterial__c();
                            jm.Job__c = job.Id;
                            jm.Material__c = psm.Material__c;
                            jm.ProjectServiceMaterial__c = psm.id;
                            jm.Status__c = 'Pending';
                            jmList.add(jm);
                        }
                    }
                }
            }
			TriggerUtil.skipJobTrigger = true;
            if(jmList.size()>0){
                insert jmList;               
            }
        }
        
        return materalAddedJobs;
    }

 
    public static Integer getJobUpdateBatchHandlerBatchSize(Project__c[] projects) {
        Integer psmCount = [SELECT count() FROM ProjectServiceMaterial__c WHERE ProjectService__r.Project__c IN :projects];
        if(psmCount == 0){
            return 2000;
        }
        Integer batchSize = 10000/psmCount;
        return batchSize < 2000 ? batchSize : 2000;
    }
    
    public static Integer getJobUpdateBatchHandlerBatchSize(Project__c p) {
		Integer psmCount = [SELECT count() FROM ProjectServiceMaterial__c WHERE ProjectService__r.Project__c = :p.Id];
        if(psmCount == 0){
            return 2000;
        }
        Integer batchSize = 10000/psmCount;
        return batchSize < 2000 ? batchSize : 2000;
    }
}