src_old/objects/Job__c.object
<CustomObject>
    <description>Job defines the body of work to be performed at a Location and all of the dates related to the Job performance. A Job is related to a Project, Project Service, Project Location, Job Material, Contact, Exception, and Job Attempt.</description>
    <fields>
        <fullName>ProjectService__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field that indicates the Project Service.</description>
        <inlineHelpText>The project service number</inlineHelpText>
        <label>Project Service</label>
        <referenceTo>ProjectService__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectStatus__c</fullName>
        <description>The field that indicates the status of the Project.</description>
        <formula>TEXT(Project__r.Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The status of the project</inlineHelpText>
        <label>Project Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ServiceName__c</fullName>
        <description>The field that indicates the name of the Service for the Job.</description>
        <inlineHelpText>The name for the service</inlineHelpText>
        <label>ServiceName</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field that indicates the Service for the Job.</description>
        <inlineHelpText>The service for the job</inlineHelpText>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Job</label>
    <nameField>
        <displayFormat>JOB-{000000000}</displayFormat>
        <label>Job ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <fields>
        <fullName>ChangeRecordType__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Change Record Type</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProjectType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Type</label>
        <referenceTo>ProjectType__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planning</fullName>
                    <default>true</default>
                    <label>Planning</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Launched</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ended</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <recordTypes>
        <fullName>Locked</fullName>
        <active>true</active>
        <label>Locked</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ProjectService__c.object
<CustomObject>
    <description>Project Service relates a Service to a Project and is a container used to define the instance of a Service for a specific Project. Project Service is related to Project, Job, Project Service Attribute, Project Service Certification, Project Service Equipment, Project Service Material, Project Service Question, Project Service Target, and Service.</description>
    <fields>
        <fullName>ChangeRecordType__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ChangeRecordType</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProjectStatus__c</fullName>
        <formula>TEXT(Project__r.Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProjectType__c</fullName>
        <formula>Project__r.ProjectType__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ServiceName__c</fullName>
        <formula>Service__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Service Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>Project Services</relationshipLabel>
        <relationshipName>ProjectServices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Executed</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project Service</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Services</pluralLabel>
    <recordTypes>
        <fullName>Locked</fullName>
        <active>true</active>
        <label>Locked</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectServiceCertification__c.object
<CustomObject>
    <description>Relates a Certification to a Project Service. Certifications from Retailer Service Certification are added by default when a Service is added to a Project Service. Additional Certifications can be added. Project Service Certification is related to Certification and Project Service.</description>
    <fields>
        <fullName>ProjectService__c</fullName>
        <label>Project Service</label>
        <referenceTo>ProjectService__c</referenceTo>
        <relationshipLabel>Project Service Certifications</relationshipLabel>
        <relationshipName>ProjectServiceCertifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Service Certification</label>
    <nameField>
        <displayFormat>PSCERT-{000000000}</displayFormat>
        <label>Project Service Certification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Service Certifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectServiceEquipment__c.object
<CustomObject>
    <description>Relates Equipment to a Project Service. Equipment from Retailer Service Equipment is added by default when a Service is added to a Project Service. Additional Equipment can also be added to the project. Project Service Equipment is related to Project Service and Equipment.</description>
    <fields>
        <fullName>ProjectService__c</fullName>
        <label>Project Service</label>
        <referenceTo>ProjectService__c</referenceTo>
        <relationshipLabel>Project Service Equipment</relationshipLabel>
        <relationshipName>ProjectServiceEquipment</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Service Equipment</label>
    <nameField>
        <displayFormat>PSE-{0000000}</displayFormat>
        <label>Project Service Equipment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Service Equipment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectTypeService__c.object
<CustomObject>
    <description>Project Type Services relates a Service to a Project Type. Project Type Service is related to Project Type and Service.</description>
    <fields>
        <fullName>ProjectType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Type</label>
        <referenceTo>ProjectType__c</referenceTo>
        <relationshipLabel>Project Type Services</relationshipLabel>
        <relationshipName>ProjectTypeServices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>Project Type Services</relationshipLabel>
        <relationshipName>ProjectTypeServices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Type Service</label>
    <nameField>
        <displayFormat>PTS-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Type Services</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/RetailerService__c.object
<CustomObject>
    <description>Retailer Service relates Services to a Retailer, which determines the Services that are available when building a Project Service. Retailer Service is related to Retailer and Service.</description>
    <fields>
        <fullName>Service__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>Retailer Services</relationshipLabel>
        <relationshipName>RetailerService_Services</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Retailer Service</label>
    <nameField>
        <displayFormat>RTSR-{000}</displayFormat>
        <label>Retailer Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retailer Services</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/RetailerServiceCertification__c.object
<CustomObject>
    <description>Retailer Service Certification relates Certifications to a Retailer, which determines the Services that are available when building a Project Service. Retailer Service Certification is related to Retailer, Service, and Certification.</description>
    <fields>
        <fullName>Service__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>Retailer Service Certifications</relationshipLabel>
        <relationshipName>Retailer_Service_Certifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Retailer Service Certification</label>
    <nameField>
        <displayFormat>RSC-{000000000}</displayFormat>
        <label>Retailer Service Certification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retailer Service Certifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/objects/RetailerServiceEquipment__c.object
<CustomObject>
    <description>Retailer Service Equipment relates Equipment to a Retailer, which determines the Equipment that are available when building a Project Service. Retailer Service Equipment is related to Retailer, Service, and Equipment.</description>
    <fields>
        <fullName>Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>Retailer Service Equipment</relationshipLabel>
        <relationshipName>RetailerServiceEquipment</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Retailer Service Equipment</label>
    <nameField>
        <displayFormat>RSE-{0000}</displayFormat>
        <label>Retailer Service Equipment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retailer Service Equipment</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/UIConfiguration__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This will store record type settings for OH screens.</description>
    <fields>
        <fullName>ProjectLockedRecordType__c</fullName>
        <label>Project Locked RecordType</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProjectRecordtypePattern__c</fullName>
        <label>Project Recordtype Pattern</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProjectServiceLockedRecordType__c</fullName>
        <label>Project Service Locked RecordType</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProjectServiceRecordtypePattern__c</fullName>
        <label>Project Service Recordtype Pattern</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>UI Configuration</label>
</CustomObject>

force-app/main/default/classes/ProjectServiceTriggerHandler.cls
public class ProjectServiceTriggerHandler extends TriggerHandler {
   
    public override void beforeUpdate() {
        
       Boolean changeRecordType = false;
       for (ProjectService__c ps: (List < ProjectService__c > ) Trigger.new) {
           if (ps.ChangeRecordType__c) 
           {
               changeRecordType = true;
               break;
           }
           
       }

        if (changeRecordType)
        {
            Map<String, String> rtmap = AppUtil.GetRecordTypeIds(CONSTANTS.CURRENTNAMESPACEPREFIX + 'ProjectService__c');
            string projectservicertPattern = 'ProjectStatus__c,ProjectType__c,ServiceName__c'; //Default
            string lockedRT = '';
            
            List<UIConfiguration__c> settings = [SELECT ProjectRecordtypePattern__c, ProjectServiceRecordtypePattern__c,
                                                 ProjectLockedRecordType__c, ProjectServiceLockedRecordType__c
                                                 FROM UIConfiguration__c LIMIT 1];
            
            if(settings == null || settings.size() == 0 || settings[0] == null || settings[0].ProjectServiceRecordtypePattern__c == null){
                projectservicertPattern = 'ProjectStatus__c,ProjectTypeName__c,ServiceName__c';
            }
            else
            {
                projectservicertPattern = settings[0].ProjectServiceRecordtypePattern__c;
            }
            
            if(settings == null || settings.size() == 0 || settings[0] == null || settings[0].ProjectServiceLockedRecordType__c == null){
                lockedRT = 'Locked';
            }
            else
            {
                lockedRT = settings[0].ProjectServiceLockedRecordType__c;
            }
            
            
            for (ProjectService__c ps: (List < ProjectService__c > ) Trigger.new) {
                if (ps.ChangeRecordType__c)
                {
                    if (ps.ProjectLocked__c)
                    {
                        ps.RecordTypeId = rtmap.get(lockedRT);
                    }
                    else
                    {
                        ps.RecordTypeId = ProjectServiceActionsHelper.GetRecordType(ps, projectservicertPattern, rtmap);    
                    }
                    ps.ChangeRecordType__c = false;                
                }
            }
            
            
        }
        

        
        if (TriggerUtil.SkipProjectServiceTrigger){
            return;
        }
        
        TriggerUtil.SkipProjectServiceTrigger = true;
        
        List<EntityChangeType__c> ects = [Select Id, Field__c from EntityChangeType__c WHERE Entity__c = 'ProjectService'];
        
        
        Set<Id> pids = new Set<Id>(); 
        
        //Collect all the Project Ids
        for (ProjectService__c ps: (List < ProjectService__c > ) Trigger.new) {
            if (IsProjectServiceChanged(ps, (ProjectService__c) Trigger.oldMap.get(ps.Id),ects))
            {
                pids.add(ps.Project__c);            
            }
            
        }
        List<Project__c> projects = [SELECT Id, IsPendingChanges__c, Status__c FROM Project__c WHERE ID IN : pids and DateLaunched__c != null];
        for (Project__c project: projects ) 
        {
            project.IsPendingChanges__c = true;
        }
        
        TriggerUtil.skipProjectTrigger = true;   
        update projects;
        
    }
   
    public override void afterUpdate() {
        
        /*
        //non bulk scenario. handle project service edits on ui, logic copied from vf ps ctrl
        List<ProjectService__c> newPSList = (List<ProjectService__c>) Trigger.new;
        if(newPSList.size() == 1){
            ProjectService__c newRecord = newPSList[0];
            ProjectService__c oldRecord = (ProjectService__c) Trigger.oldMap.get(newRecord.Id);
            Boolean updateJobs = false;
            Boolean resetJobScheduleDates = false;
            
            system.debug(newRecord.DayNumber__c + ':::' + oldRecord.NumberOfWorkers__c);
            
            if (newRecord.DayNumber__c != oldRecord.DayNumber__c ||  newRecord.NumberOfWorkers__c != oldRecord.NumberOfWorkers__c)
            {
                Integer jobCount = [SELECT count() FROM Job__c WHERE  ProjectService__c = :newPSList[0].Id LIMIT 1];
                
                if (jobCount > 0)
                {
                	newRecord.addError('Changes to Day Number/Number Of Workers not allowed when there are jobs tied to the service. Please delete jobs and retry.');    
                }

            }
        }
		*/
	}
    
    public override void beforeInsert() {

        if(TriggerUtil.skipDeepClonedRecords == true)
            return; 
        //non bulk scenario. prevent wrong services to be added to project
        ProjectService__c ps = ((List<ProjectService__c>) Trigger.new)[0];
        
        Project__c p = [SELECT Id,ProjectType__r.name, Retailer__c,IsSingleServiceProject__c FROM Project__c WHERE Id = :ps.Project__c];
        service__c serv = [select id,IsSingleService__c from service__c where id=:ps.Service__c limit 1];
        Integer validCount = [SELECT count() FROM ProjectTypeService__c where ProjectType__r.Name =: p.ProjectType__r.name and  Service__c = :ps.Service__c AND Service__c  in (SELECT Service__c FROM RetailerService__c where Retailer__c =: p.Retailer__c )];
        
        if(validCount != 1){
            ps.addError('Service cannot be added to the project. Please check the project type and retailer mappings.');
        }
        
        if(serv.IsSingleService__c)
        {
            p.IsSingleServiceProject__c=true;
        }
        else{
            integer cnt = [select count() from projectservice__c where project__c=: p.id and Service__r.IsSingleService__c=true];
            if(cnt==0)
            	p.IsSingleServiceProject__c=false;     
        }
		update p; 
    }
    
    public override void afterInsert() {
        if(TriggerUtil.skipDeepClonedRecords == true)
            return; 
        set<Id> setProjectServiceIds = new set<Id>();
        setProjectServiceIds = Trigger.newmap.keyset();
        set<Id> serviceIds = new set<Id>();
        set<Id> retailerIds = new set<Id>();
        map<string,ProjectService__c> mapRetailService = new map<string,ProjectService__c>();
        
        set<Id> SingleServiceProjID = new set<Id>();
        set<Id> NonSingleServiceProjID = new set<Id>();
        for(ProjectService__c ps: [Select Id,
                                   Project__c,
                                   Project__r.Retailer__c,
                                   Project__r.Status__c,
                                   Service__c,
                                   Service__r.IsSingleService__c,
                                   Project__r.ProjectType__r.Name
                                   FROM ProjectService__c 
                                   where ID IN :setProjectServiceIds])
        {
            if(ps.Service__r.IsSingleService__c)
                SingleServiceProjID.add(ps.project__c);
            else
                NonSingleServiceProjID.add(ps.Project__c);
            
            mapRetailService.put(ps.Project__r.Retailer__c + '-' +  ps.Service__c,ps);
            serviceIds.add(ps.Service__c);
            retailerIds.add(ps.Project__r.Retailer__c);            
        }
      
        
        
        //Insert Project Service Equipment 
        List<ProjectServiceEquipment__c> pseList = new List<ProjectServiceEquipment__c>();
        for(RetailerServiceEquipment__c rse :[SELECT Id, Equipment__c, Retailer__c, Quantity__c, IsLocked__c, Service__c, Equipment__r.EquipmentType__c FROM RetailerServiceEquipment__c WHERE Retailer__c  IN: retailerIds AND Service__c IN : serviceIds]){
            if(mapRetailService.get(rse.Retailer__c + '-' + rse.Service__c) != null){
                ProjectServiceEquipment__c pse = new ProjectServiceEquipment__c();
                pse.ProjectService__c = mapRetailService.get(rse.Retailer__c + '-' + rse.Service__c).Id;
                pse.Equipment__c = rse.Equipment__c;
                pse.Quantity__c = rse.Quantity__c;
                pse.IsLocked__c = rse.IsLocked__c;
                pseList.add(pse);
            }
        }
        if(!pseList.isEmpty()){
            insert pseList;
        }
        
        //Insert Project Service Certification
        List<ProjectServiceCertification__c> pscList = new List<ProjectServiceCertification__c>();
        for(RetailerServiceCertification__c rsc : [SELECT Id, Service__c,Retailer__c, Certification__c FROM RetailerServiceCertification__c WHERE Retailer__c IN : retailerIds AND Service__c IN : serviceIds]){
            if(mapRetailService.get(rsc.Retailer__c + '-' + rsc.Service__c) != null){
                ProjectServiceCertification__c psc = new ProjectServiceCertification__c();
                psc.ProjectService__c = mapRetailService.get(rsc.Retailer__c + '-' + rsc.Service__c).Id;
                psc.Certification__c = rsc.Certification__c;
                psc.IsLocked__c = true;
                pscList.add(psc);
            }
        }
        if(!pscList.isEmpty()){
            insert pscList;
        }
        
    }    
    
    public static Boolean IsProjectServiceChanged(ProjectService__c newprojectservice, ProjectService__c oldprojectservice, List<EntityChangeType__c> ects) {
        
        for (EntityChangeType__c ect : ects)
        {
            system.debug('ect field: ' + ect.Field__c + ':' + newprojectservice.get(ect.Field__c) + ':' + oldprojectservice.get(ect.Field__c));
            
            if (newprojectservice.get(ect.Field__c) != oldprojectservice.get(ect.Field__c))
            {
                system.debug('-----  ect changed -----');
                return true;
            }
        }
        
        return false;
    }    
}