src_old/objects/Job__c.object
<CustomObject>
    <description>Job defines the body of work to be performed at a Location and all of the dates related to the Job performance. A Job is related to a Project, Project Service, Project Location, Job Material, Contact, Exception, and Job Attempt.</description>
    <fields>
        <fullName>ProjectCancelLeadTime__c</fullName>
        <description>The field that indicates the lead time for a Project to be canceled</description>
        <formula>Project__r.ProjectCancelLeadTime__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The lead name for a project to be canceled</inlineHelpText>
        <label>Project Cancel Lead Time</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProjectService__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field that indicates the Project Service.</description>
        <inlineHelpText>The project service number</inlineHelpText>
        <label>Project Service</label>
        <referenceTo>ProjectService__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field that indicates the name of the Project to which a Job belongs.</description>
        <inlineHelpText>The name of the project for this job</inlineHelpText>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Retailer__c</fullName>
        <description>The field that indicates the Retailer ID.</description>
        <formula>CASESAFEID(Project__r.Retailer__r.Id)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The Retailer ID from the project</inlineHelpText>
        <label>Retailer</label>
        <type>Text</type>
    </fields>
    <label>Job</label>
    <nameField>
        <displayFormat>JOB-{000000000}</displayFormat>
        <label>Job ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/JobMaterial__c.object
<CustomObject>
    <description>Job Material is a helper object that stores tracking information and other Job specific information about Material needed to perform a Job.</description>
    <fields>
        <fullName>Job__c</fullName>
        <label>Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Job Materials</relationshipLabel>
        <relationshipName>Job_Materials</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Material__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Material</label>
        <referenceTo>Material__c</referenceTo>
        <relationshipLabel>Job Materials</relationshipLabel>
        <relationshipName>Job_Materials</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Job Material</label>
    <nameField>
        <displayFormat>JM-{000000000}</displayFormat>
        <label>Job Material Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Materials</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/Material__c.object
<CustomObject>
    <description>Material defines a physical item that will be shipped to a Location to by a Fulfillment Center. Material is related to Fulfillment Center and Job Material.</description>
    <fields>
        <fullName>Retailer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Retailer</label>
        <referenceTo>Retailer__c</referenceTo>
        <relationshipLabel>Materials</relationshipLabel>
        <relationshipName>Materials</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Material</label>
    <nameField>
        <label>Material Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Materials</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <fields>
        <fullName>BudgetedLocationsCount__c</fullName>
        <description>An entry field that indicates the number of budgeted locations for the Project.</description>
        <inlineHelpText>Expected number of locations</inlineHelpText>
        <label>Budgeted Locations Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>An entry field that indicates the end date of the Project.</description>
        <inlineHelpText>The last date available to complete execution</inlineHelpText>
        <label>Project End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FulfillmentLeadTime__c</fullName>
        <description>A field that indicates the lead time for fulfillment of the Project.</description>
        <formula>Retailer__r.FulfillmentLeadTime__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The lead time for fulfillment of the project.</inlineHelpText>
        <label>Fulfillment Lead Time</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OriginID__c</fullName>
        <description>A field that indicates the ID number for the origin of the Project.</description>
        <externalId>true</externalId>
        <label>Origin ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ProjectCancelLeadTime__c</fullName>
        <description>A field that indicates the lead time to cancel the Project.</description>
        <formula>Retailer__r.JobCancelLeadTime__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The lead time to cancel the project.</inlineHelpText>
        <label>Project Cancel Lead Time</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProjectType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Type</label>
        <referenceTo>ProjectType__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Retailer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Retailer</label>
        <referenceTo>Retailer__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>An entry field that indicates the start date of the Project.</description>
        <inlineHelpText>The date available to start execution</inlineHelpText>
        <label>Project Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planning</fullName>
                    <default>true</default>
                    <label>Planning</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Launched</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ended</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UpdateJobsFlag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To show &quot;Create Jobs&quot; button in scheduled state when services are modified.</description>
        <label>Update Jobs Flag</label>
        <type>Checkbox</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <recordTypes>
        <fullName>Booked</fullName>
        <active>true</active>
        <label>Booked</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ProjectService__c.object
<CustomObject>
    <description>Project Service relates a Service to a Project and is a container used to define the instance of a Service for a specific Project. Project Service is related to Project, Job, Project Service Attribute, Project Service Certification, Project Service Equipment, Project Service Material, Project Service Question, Project Service Target, and Service.</description>
    <fields>
        <fullName>ProjectType__c</fullName>
        <formula>Project__r.ProjectType__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>ProjectServices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Retailer__c</fullName>
        <formula>Project__r.Retailer__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Retailer</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Executed</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project Service</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Services</pluralLabel>
    <recordTypes>
        <fullName>Booked</fullName>
        <active>true</active>
        <label>Booked</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectType__c.object
<CustomObject>
    <description>Project Type defines a collection of Services and sets configuration options for a Project. Project Type is related to Project, Project Type Execution Company, Project Type Service, and Location Assignment.</description>
    <label>Project Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Types</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/Retailer__c.object
<CustomObject>
    <description>Retailer stores the retailers for the system. Retailer is related to Location, Retailer Service, Retailer Service Certification, and Retailer Service Equipment.</description>
    <fields>
        <fullName>FulfillmentLeadTime__c</fullName>
        <label>Fulfillment Lead Time</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProjectCancelLeadTime__c</fullName>
        <label>Project Cancel Lead Time</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>isMaterialReqd__c</fullName>
        <defaultValue>true</defaultValue>
        <description>To determine if materials are needed for this retailer.</description>
        <label>Is Material Reqd</label>
        <type>Checkbox</type>
    </fields>
    <label>Retailer</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Retailers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/JobUpdateBatchHandlerTest.cls
@isTest
public class JobUpdateBatchHandlerTest {
    @testSetup static void setup(){
        TestUtil.initBaseData();
        TestUtil.generateFullTestProject(ProjectType.MD, Date.today().addDays(10), Date.today().addDays(20));
    }

    public static testMethod void test_Handler(){
        Project__c project = (Project__c) TestUtil.getRecord('Project__c');
        
        List<Material__c> mts = (List<Material__c>) TestUtil.getRecordset('Material__c');
        List<ProjectService__c> psLsit = [SELECT Id FROM ProjectService__c WHERE Project__c =:project.Id ];
        TestUtil.generateProjectServiceMaterial(psLsit[0].Id, mts[0]);
        
        ProjectScheduler batch = new ProjectScheduler([SELECT Name, StartDate__c, EndDate__c, ProjectType__c, ProjectType__r.Name, Status__c FROM Project__c WHERE ID = :project.Id]);
        Database.executeBatch(batch);
        
        project = [SELECT Id, Status__c FROM Project__c WHERE Id =: project.Id];
        Integer jobMateralCount = [SELECT Count() FROM JobMaterial__c WHERE Job__c IN (SELECT ID FROM JOB__c WHERE Project__c =: project.Id)];
        system.assertEquals(jobMateralCount, 0);
        
        /*
        jobMateralCount = [SELECT Count() FROM JobMaterial__c WHERE Job__c IN (SELECT ID FROM JOB__c WHERE Project__c =: project.Id)];
        project = [SELECT Id, Name, Status__c, ProjectType__c, ProjectType__r.Name, FulfillmentLeadTime__c, ProjectCancelLeadTime__c,StartDate__c,EndDate__c,retailer__r.isMaterialReqd__c, OriginID__c, BudgetedLocationsCount__c, UpdateJobsFlag__c FROM Project__c WHERE Id =: project.Id];
        project.Status__c = 'Booked';
        update project;
        
        Test.startTest();
        JobUpdateBatchHandler jobupdatebatch = new JobUpdateBatchHandler(project);
        Database.ExecuteBatch(jobupdatebatch, 100);
        Test.stopTest();
        
        jobMateralCount = [SELECT Count() FROM JobMaterial__c WHERE Job__c IN (SELECT ID FROM JOB__c WHERE Project__c =: project.Id)];
        
        system.assertNotEquals(jobMateralCount, 0);
        */
    }
}