src_old/objects/Job__c.object
<CustomObject>
    <description>Job defines the body of work to be performed at a Location and all of the dates related to the Job performance. A Job is related to a Project, Project Service, Project Location, Job Material, Contact, Exception, and Job Attempt.</description>
    <fields>
        <fullName>ProjectLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field that indicates the Location of a Project.</description>
        <inlineHelpText>The location of the project</inlineHelpText>
        <label>Project Location</label>
        <referenceTo>ProjectLocation__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectService__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field that indicates the Project Service.</description>
        <inlineHelpText>The project service number</inlineHelpText>
        <label>Project Service</label>
        <referenceTo>ProjectService__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field that indicates the name of the Project to which a Job belongs.</description>
        <inlineHelpText>The name of the project for this job</inlineHelpText>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Job</label>
    <nameField>
        <displayFormat>JOB-{000000000}</displayFormat>
        <label>Job ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/JobAttempt__c.object
<CustomObject>
    <description>Job Attempt is an attempt of a Job performed at a location. Job Attempt is related to an Exception.</description>
    <fields>
        <fullName>Job__c</fullName>
        <label>Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Job Attempts</relationshipLabel>
        <relationshipName>Job_Attempts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ProjectLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Location</label>
        <referenceTo>ProjectLocation__c</referenceTo>
        <relationshipLabel>Job Attempts</relationshipLabel>
        <relationshipName>Job_Attempts_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Job Attempt</label>
    <nameField>
        <displayFormat>JA-{000000000}</displayFormat>
        <label>Job Attempt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Attempts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/JobComment__c.object
<CustomObject>
    <fields>
        <fullName>JobAttempt__c</fullName>
        <label>Job Attempt</label>
        <referenceTo>JobAttempt__c</referenceTo>
        <relationshipLabel>Job Comments</relationshipLabel>
        <relationshipName>Job_Comments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Job Comments</relationshipLabel>
        <relationshipName>Job_Comments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Location</label>
        <referenceTo>ProjectLocation__c</referenceTo>
        <relationshipLabel>Job Comments</relationshipLabel>
        <relationshipName>Job_Comments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectService__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Service</label>
        <referenceTo>ProjectService__c</referenceTo>
        <relationshipLabel>Job Comments</relationshipLabel>
        <relationshipName>Job_Comments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Job Comments</relationshipLabel>
        <relationshipName>Job_Comments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Job Comment</label>
    <nameField>
        <displayFormat>JC-{000000000}</displayFormat>
        <label>Job Comment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ProjectLocation__c.object
<CustomObject>
    <description>Project Location relates a Location to a Project. Project Location is related Project, Job, and Location.</description>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>ProjectLocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Location</label>
    <nameField>
        <displayFormat>PL-{0000}</displayFormat>
        <label>Location ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectService__c.object
<CustomObject>
    <description>Project Service relates a Service to a Project and is a container used to define the instance of a Service for a specific Project. Project Service is related to Project, Job, Project Service Attribute, Project Service Certification, Project Service Equipment, Project Service Material, Project Service Question, Project Service Target, and Service.</description>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>ProjectServices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Service</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/classes/JobCommentTriggerHandler.cls
public class JobCommentTriggerHandler extends TriggerHandler {
    
    public override void beforeInsert(){

        set<Id> jobAttemptIds = new set<Id>();
        for (JobComment__c ji :(List<JobComment__c> ) Trigger.new) {
             if(!(string.isEmpty(ji.JobAttempt__c)))
             {
              	jobAttemptIds.add(ji.JobAttempt__c); 
             }
                        
        }
        
        Map<Id,JobAttempt__c> jobattemptMap = new Map<Id,JobAttempt__c>([Select Id,name,Job__c,Job__r.ProjectLocation__c, job__r.Project__c, Job__r.ProjectService__c   from JobAttempt__c where Id IN : jobAttemptIds]);
        
        for(Jobcomment__c jc :(List<JobComment__c> ) Trigger.new)
        {
            if(jobattemptMap.containsKey(jc.JobAttempt__c)){
                
                jc.Job__c = jobattemptMap.get(jc.JobAttempt__c).Job__c;
                jc.ProjectLocation__c = jobattemptMap.get(jc.JobAttempt__c).Job__r.ProjectLocation__c;
                jc.Project__c = jobattemptMap.get(jc.JobAttempt__c).Job__r.Project__c;
                jc.ProjectService__c = jobattemptMap.get(jc.JobAttempt__c).Job__r.ProjectService__c;
            }
               
        }
      
   }
}