src_old/objects/Job__c.object
<CustomObject>
    <description>Job defines the body of work to be performed at a Location and all of the dates related to the Job performance. A Job is related to a Project, Project Service, Project Location, Job Material, Contact, Exception, and Job Attempt.</description>
    <fields>
        <fullName>ProjectNumber__c</fullName>
        <description>The field that indicates the Project Number.</description>
        <formula>Project__r.ProjectNumber__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProjectService__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field that indicates the Project Service.</description>
        <inlineHelpText>The project service number</inlineHelpText>
        <label>Project Service</label>
        <referenceTo>ProjectService__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field that indicates the name of the Project to which a Job belongs.</description>
        <inlineHelpText>The name of the project for this job</inlineHelpText>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ReferralJob__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The search field for the Referral Job.</description>
        <label>Referral Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ResponsibleExecutionCompany__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field that indicates the Execution Company responsible for the Job.</description>
        <inlineHelpText>The name of the execution company responsible for this job</inlineHelpText>
        <label>Responsible Execution Company</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field that indicates the Service for the Job.</description>
        <inlineHelpText>The service for the job</inlineHelpText>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Job</label>
    <nameField>
        <displayFormat>JOB-{000000000}</displayFormat>
        <label>Job ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>An entry field that indicates the end date of the Project.</description>
        <inlineHelpText>The last date available to complete execution</inlineHelpText>
        <label>Project End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IsDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>A checkbox that indicates that the Project is deleted.</description>
        <inlineHelpText>If selected, the project is deleted.</inlineHelpText>
        <label>Is Deleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LocationTotalCount__c</fullName>
        <description>A field that indicates the count of the locations added to the project.</description>
        <inlineHelpText>The count of the locations added to the project.</inlineHelpText>
        <label>Actual Location Count</label>
        <summaryFilterItems>
            <field>ProjectLocation__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Canceled</value>
        </summaryFilterItems>
        <summaryForeignKey>ProjectLocation__c.Project__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>ProjectLaunchDate__c</fullName>
        <description>A field that indicates the launch date for the Project</description>
        <inlineHelpText>The date the project becomes visible on execution platforms and fulfillment entities.</inlineHelpText>
        <label>Project Launch Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ProjectNumber__c</fullName>
        <displayFormat>{YY}{MM}{DD}{000000}</displayFormat>
        <inlineHelpText>this is help text in design</inlineHelpText>
        <label>Project Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>An entry field that indicates the start date of the Project.</description>
        <inlineHelpText>The date available to start execution</inlineHelpText>
        <label>Project Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planning</fullName>
                    <default>true</default>
                    <label>Planning</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Launched</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ended</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <recordTypes>
        <fullName>Booked</fullName>
        <active>true</active>
        <label>Booked</label>
    </recordTypes>
    <recordTypes>
        <fullName>Canceled</fullName>
        <active>true</active>
        <label>Canceled</label>
    </recordTypes>
    <recordTypes>
        <fullName>Closed</fullName>
        <active>true</active>
        <label>Closed</label>
    </recordTypes>
    <recordTypes>
        <fullName>Ended</fullName>
        <active>true</active>
        <label>Ended</label>
    </recordTypes>
    <recordTypes>
        <fullName>Launched</fullName>
        <active>true</active>
        <label>Launched</label>
    </recordTypes>
    <recordTypes>
        <fullName>Planning</fullName>
        <active>true</active>
        <label>Planning</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ProjectAccount__c.object
<CustomObject>
    <description>Project Account maps an Account to a Project and defines how the Account will be billed. Project Account is related to Project, Account, and Account Address.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please make sure this account&apos;s &apos;Can Request Project&apos; setting is enabled.</errorMessage>
            <filterItems>
                <field>Account.CanRequestProjects__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Project Accounts</relationshipLabel>
        <relationshipName>Project_Accounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Project_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Account</label>
    <nameField>
        <displayFormat>PA-{0000000}</displayFormat>
        <label>Project Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectService__c.object
<CustomObject>
    <description>Project Service relates a Service to a Project and is a container used to define the instance of a Service for a specific Project. Project Service is related to Project, Job, Project Service Attribute, Project Service Certification, Project Service Equipment, Project Service Material, Project Service Question, Project Service Target, and Service.</description>
    <fields>
        <fullName>IsDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Deleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProjectNumber__c</fullName>
        <formula>Project__r.ProjectNumber__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>ProjectServices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>Project Services</relationshipLabel>
        <relationshipName>ProjectServices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Executed</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project Service</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Services</pluralLabel>
    <recordTypes>
        <fullName>Booked</fullName>
        <active>true</active>
        <label>Booked</label>
    </recordTypes>
    <recordTypes>
        <fullName>Canceled</fullName>
        <active>true</active>
        <label>Canceled</label>
    </recordTypes>
    <recordTypes>
        <fullName>Closed</fullName>
        <active>true</active>
        <label>Closed</label>
    </recordTypes>
    <recordTypes>
        <fullName>Ended</fullName>
        <active>true</active>
        <label>Ended</label>
    </recordTypes>
    <recordTypes>
        <fullName>Launched</fullName>
        <active>true</active>
        <label>Launched</label>
    </recordTypes>
    <recordTypes>
        <fullName>Planning</fullName>
        <active>true</active>
        <label>Planning</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/Service__c.object
<CustomObject>
    <description>Service contains the definition of a service. Service is related to Service Attribute, Service Exception, Service Question, Service Question Defined Response, Retailer Service, Retailer Service Equipment, and Project Service.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account specific service</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/classes/ProjectManagementController.cls
public with sharing class ProjectManagementController {

	public String filterSelections {get;private set;}

	public ProjectManagementController() {

		//load pre-selected filter selections (optional)
		filterSelections = ApexPages.currentPage().getParameters().get('fs');
	}

	@RemoteAction
	@ReadOnly
	public static Project[] filterProjects(Map<String, String> filterMap) {

		if (filterMap == null) filterMap = new Map<String, String>();

		system.debug('filterMap' + filterMap);
		String baseQuery = 'SELECT Id, Name, ProjectNumber__c, StartDate__c, EndDate__c, ProjectLaunchDate__c, Owner.Name, LocationTotalCount__c, (SELECT Id, Service__r.Name FROM ProjectServices__r), (SELECT Id, Account__r.Name FROM Project_Accounts__r)'
						+ ' FROM Project__c'
						+ ' WHERE IsDeleted__c = false';

		Map<String, String> filterLabelToAPIName = new Map<String, String>{
			'Number' => 'ProjectNumber__c'
        	, 'Title' => 'Name'
        	, 'Suppliers' => 'Account__r.Name'
        	, 'Services' => 'Service__r.Name'
        	, '# Locations' => 'LocationTotalCount__c'
        	// TODO , '# Jobs' => '' NOTE: This one can be filtered by related object, but the requirement is to filter on the count, which is not possible without a custom count field
        	, 'Start Date' => 'StartDate__c'
        	, 'End Date' => 'EndDate__c'
        	, 'Launch Date' => 'ProjectLaunchDate__c'
        	, 'Owner' => 'Owner.Name'
    	};

    	String whereClause = '';
		system.debug('keySet' + filterMap.keySet());

		for (String filterLabel : filterMap.keySet()) {

			system.debug('filterLabel' + filterLabel);
			if (filterLabelToAPIName.containsKey(filterLabel)){

				String apiName = filterLabelToAPIName.get(filterLabel);
				Boolean searchTypeIsString = (new Set<String>{ 'Number', 'Title', 'Owner', 'Suppliers', 'Services' }).contains(filterLabel);

				String aggregatedSearchStrings = '';
				for (String searchString : filterMap.get(filterLabel).split(',')) {

					searchString = String.escapeSingleQuotes(searchString.trim());

					if (searchTypeIsString && searchString.toLowerCase() == 'null') searchString = '';

					if (searchTypeIsString && !String.isBlank(searchString)) {
						aggregatedSearchStrings += apiName + ' LIKE \'%' + searchString + '%\' OR ';
					} else {
						aggregatedSearchStrings += searchString + ',';
					}
				}

				aggregatedSearchStrings = aggregatedSearchStrings.removeEnd(',').removeEnd(' OR ');

				if (!String.isBlank(aggregatedSearchStrings)) {

					if (filterLabel == 'Start Date' || filterLabel == 'End Date' || filterLabel == 'Launch Date') {
						aggregatedSearchStrings = String.valueOf(Date.parse(aggregatedSearchStrings));
						whereClause += ' AND ' + apiName + ' = ' + aggregatedSearchStrings;
					} else if (filterLabel == 'Suppliers') {
						whereClause += ' AND Id IN (SELECT Project__c FROM ProjectAccount__c WHERE Project__r.IsDeleted__c = false AND (' + aggregatedSearchStrings + '))';
					} else if (filterLabel == 'Services') {
						whereClause += ' AND Id IN (SELECT Project__c FROM ProjectService__c WHERE Project__r.IsDeleted__c = false AND (' + aggregatedSearchStrings + '))';
					} else if (searchTypeIsString) {
						whereClause += ' AND (' + aggregatedSearchStrings + ')';
					} else {
						whereClause += ' AND ' + apiName + ' IN (' + aggregatedSearchStrings + ')';
					}
				}
			}
		}

		String orderBy = ' ORDER BY Name';
		String query = baseQuery + whereClause + orderBy;

		Map<Id, Project> outputMap = new Map<Id, Project>();
		System.debug('DEVDEBUG Querying: ' + query);
		for (Project__c project : Database.query(query)) {
			outputMap.put(project.Id, new Project(project));
		}

		for (AggregateResult res : [SELECT Project__c, count(Id) recCount FROM Job__c WHERE Project__c IN :outputMap.keySet() GROUP BY Project__c]) {
			outputMap.get((Id) res.get('Project__c')).numberOfJobs = String.valueOf((Integer) res.get('recCount'));
		}

		return outputMap.values();
	}

	//fetch a list of possible filters
    @ReadOnly
    @RemoteAction
    public static Filter[] getFilters() {

    	SelectOption[] servicesOptions = new SelectOption[]{};
    	for (AggregateResult res : [SELECT Service__c value, Service__r.Name label FROM ProjectService__c WHERE Project__r.IsDeleted__c = false GROUP BY Service__c, Service__r.Name]) {
    		servicesOptions.add(new SelectOption((Id) res.get('value'), (String) res.get('label')));
    	}

        return new Filter[]{
        	new Filter('Number', 'text', new SelectOption[]{})
        	, new Filter('Title', 'text', new SelectOption[]{})
        	, new Filter('Suppliers', 'text', new SelectOption[]{})
        	, new Filter('Services', 'picklist', servicesOptions)
        	, new Filter('# Locations', 'text-operator', new SelectOption[]{})
        	, new Filter('# Jobs', 'text-operator', new SelectOption[]{})
        	, new Filter('Start Date', 'date-operator', new SelectOption[]{})
        	, new Filter('End Date', 'date-operator', new SelectOption[]{})
        	, new Filter('Launch Date', 'date-operator', new SelectOption[]{})
        	, new Filter('Owner', 'text', new SelectOption[]{})
        };
    }

    @ReadOnly
    @RemoteAction
    public static SummaryCount[] getProjectSummary() {
    	SummaryCount[] output = new SummaryCount[]{
    		new SummaryCount('My Projects', [SELECT count() FROM Project__c WHERE OwnerId = :UserInfo.getUserId()])
    	};

    	Map<String, Integer> statusToResultCount = new Map<String, Integer>();
    	for (AggregateResult res : [SELECT Status__c status, count(Id) projectCount FROM Project__c WHERE Status__c IN ('Planning', 'Booked', 'Pending', 'In Progress', 'Ended', 'Canceled', 'Closed') GROUP BY Status__c]) {
    		statusToResultCount.put((String) res.get('status'), (Integer) res.get('projectCount'));
    	}

    	output.add(new SummaryCount('Planning', statusToResultCount.get('Planning')));
    	output.add(new SummaryCount('Booked', statusToResultCount.get('Booked')));
    	output.add(new SummaryCount('Launched', statusToResultCount.get('Pending')));
    	output.add(new SummaryCount('In Progress', statusToResultCount.get('In Progress')));
    	output.add(new SummaryCount('Ended', statusToResultCount.get('Ended')));
    	output.add(new SummaryCount('Canceled', statusToResultCount.get('Canceled')));
    	output.add(new SummaryCount('Closed', statusToResultCount.get('Closed')));

    	return output;
    }

    public class SummaryCount {
    	public String label;
    	public Integer count;
    	public SummaryCount(String label, Integer count) {
    		this.label = label;
    		this.count = count;
    	}
    }

	public class Project {
        public String id {get;set;}
		public String projectNumber {get;set;}
		public String title {get;set;}
		public String[] suppliers {get;set;}
		public String[] services {get;set;}
		public String numberOfLocations {get;set;}
		public String numberOfJobs {get;set;}
		public String startDate {get;set;}
		public String endDate {get;set;}
		public String launchDate {get;set;}
		public String owner {get;set;}

		public Project(Project__c project){

            this.id = project.Id;
			this.projectNumber = project.ProjectNumber__c;
			this.title = project.Name;
			this.numberOfLocations = '' + project.LocationTotalCount__c;
			//this.numberOfJobs = '' + project.Jobs__r.size();
			this.startDate = project.StartDate__c == null ? '' : project.StartDate__c.format();
			this.endDate = project.EndDate__c == null ? '' : project.EndDate__c.format();
			this.launchDate = project.ProjectLaunchDate__c == null ? '' : project.ProjectLaunchDate__c.format();
			this.owner = project.Owner.Name;

			this.suppliers = new String[]{};
			for (ProjectAccount__c projectAccount : project.Project_Accounts__r) this.suppliers.add(projectAccount.Account__r.Name);

			this.services = new String[]{};
			for (ProjectService__c projService : project.ProjectServices__r) this.services.add(projService.Service__r.Name);
		}
	}

	public class Filter {
        public String label { get; set; }
        public SelectOption[] options { get; set; }
        public String type { get; set; }
        public Filter(String label, String type, SelectOption[] options) {
            this.label = label;
            this.type = type;
            this.options = options;
        }
    }

    public class SelectOption {
        public String value { get; set; }
        public String label { get; set; }
        public Boolean selected { get; set; }
        public SelectOption(String value, String label) {
            this.value = value;
            this.label = label;
            selected = false;
        }
    }

}