src_old/objects/Job__c.object
<CustomObject>
    <description>Job defines the body of work to be performed at a Location and all of the dates related to the Job performance. A Job is related to a Project, Project Service, Project Location, Job Material, Contact, Exception, and Job Attempt.</description>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field that indicates the name of the Project to which a Job belongs.</description>
        <inlineHelpText>The name of the project for this job</inlineHelpText>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Job</label>
    <nameField>
        <displayFormat>JOB-{000000000}</displayFormat>
        <label>Job ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/ScheduleLocationsModalControllerTest.cls
@isTest
private class ScheduleLocationsModalControllerTest {
    static testMethod void test_validateReserve_MD() {
        
        Project__c project = TestUtil.generateFullTestProject(ProjectType.MD, Date.today().addDays(10), Date.today().addDays(20));
      
        
        PageReference vfPage = Page.ScheduleLocationsModal;
        Test.setCurrentPage(vfPage);
        System.currentPageReference().getParameters().put('projectid', project.Id);
        ScheduleLocationsModalController modalController = new ScheduleLocationsModalController();
        
        modalController.submitSchedulingBatchJob();
        List<Job__c> jobs = [SELECT Id FROM Job__c WHERE Project__c =: project.Id];
        //System.assertNotEquals(jobs.size(), 0);
        
    }
    
    static testMethod void test_batchjob() {
        
        Project__c project = TestUtil.generateFullTestProject(ProjectType.MD, Date.today().addDays(10), Date.today().addDays(20));
        
       
        
        PageReference vfPage = Page.ScheduleLocationsModal;
        Test.setCurrentPage(vfPage);
        System.currentPageReference().getParameters().put('projectid', project.Id);
        ScheduleLocationsModalController modalController = new ScheduleLocationsModalController();
        
        Test.startTest();
        modalController.submitSchedulingBatchJob();
        Test.stopTest();
        
        List<Job__c> jobs = [SELECT Id FROM Job__c WHERE Project__c =: project.Id];
        System.assertNotEquals(jobs.size(), 0);
        
    }
}