src_old/objects/Job__c.object
<CustomObject>
    <description>Job defines the body of work to be performed at a Location and all of the dates related to the Job performance. A Job is related to a Project, Project Service, Project Location, Job Material, Contact, Exception, and Job Attempt.</description>
    <fields>
        <fullName>JobCanceledReason__c</fullName>
        <description>A picklist that indicates reasons why a job was canceled.</description>
        <inlineHelpText>The reason that the job was canceled.</inlineHelpText>
        <label>Canceled Reason</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Supplier Requested</fullName>
                </value>
                <value>
                    <fullName>Retailer Requested</fullName>
                </value>
                <value>
                    <fullName>No Product</fullName>
                </value>
                <value>
                    <fullName>Item not approved</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>JobDateCanceled__c</fullName>
        <description>The field that indicates the date and time a Job was canceled.</description>
        <inlineHelpText>The date and time the job was canceled</inlineHelpText>
        <label>Date Canceled</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>JobStartDate__c</fullName>
        <description>The field that indicates the start date for the Job.</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>JobStatus__c</fullName>
        <description>A picklist that indicates the status of the Job.</description>
        <inlineHelpText>The status of the job</inlineHelpText>
        <label>Job Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Started</fullName>
                </value>
                <value>
                    <fullName>Reported</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ProjectCancelLeadTime__c</fullName>
        <description>The field that indicates the lead time for a Project to be canceled</description>
        <formula>Project__r.ProjectCancelLeadTime__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The lead name for a project to be canceled</inlineHelpText>
        <label>Project Cancel Lead Time</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProjectLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field that indicates the Location of a Project.</description>
        <inlineHelpText>The location of the project</inlineHelpText>
        <label>Project Location</label>
        <referenceTo>ProjectLocation__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectService__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field that indicates the Project Service.</description>
        <inlineHelpText>The project service number</inlineHelpText>
        <label>Project Service</label>
        <referenceTo>ProjectService__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field that indicates the name of the Project to which a Job belongs.</description>
        <inlineHelpText>The name of the project for this job</inlineHelpText>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Job</label>
    <nameField>
        <displayFormat>JOB-{000000000}</displayFormat>
        <label>Job ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <fields>
        <fullName>CancelReason__c</fullName>
        <description>A picklist that indicates reasons that the project was canceled.</description>
        <inlineHelpText>Select the reason the project was canceled.</inlineHelpText>
        <label>Cancel Reason</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Supplier Requested</fullName>
                </value>
                <value>
                    <fullName>Retailer Requested</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                    <default>true</default>
                    <label>Other</label>
                </value>
                <value>
                    <fullName>Item not approved</fullName>
                    <isActive>false</isActive>
                    <label>Item not approved</label>
                </value>
                <value>
                    <fullName>No Capacity</fullName>
                    <isActive>false</isActive>
                    <label>No Capacity</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ProjectCancelLeadTime__c</fullName>
        <description>A field that indicates the lead time to cancel the Project.</description>
        <formula>Retailer__r.JobCancelLeadTime__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The lead time to cancel the project.</inlineHelpText>
        <label>Project Cancel Lead Time</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planning</fullName>
                    <default>true</default>
                    <label>Planning</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Launched</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ended</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <recordTypes>
        <fullName>Booked</fullName>
        <active>true</active>
        <label>Booked</label>
    </recordTypes>
    <recordTypes>
        <fullName>Canceled</fullName>
        <active>true</active>
        <label>Canceled</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ProjectLocation__c.object
<CustomObject>
    <description>Project Location relates a Location to a Project. Project Location is related Project, Job, and Location.</description>
    <fields>
        <fullName>CancelReason__c</fullName>
        <label>Cancel Reason</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Supplier Requested</fullName>
                </value>
                <value>
                    <fullName>Retailer Requested</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>ProjectLocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Job Created</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project Location</label>
    <nameField>
        <displayFormat>PL-{0000}</displayFormat>
        <label>Location ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectService__c.object
<CustomObject>
    <description>Project Service relates a Service to a Project and is a container used to define the instance of a Service for a specific Project. Project Service is related to Project, Job, Project Service Attribute, Project Service Certification, Project Service Equipment, Project Service Material, Project Service Question, Project Service Target, and Service.</description>
    <fields>
        <fullName>CancelReason__c</fullName>
        <label>Cancel Reason</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Supplier Requested</fullName>
                </value>
                <value>
                    <fullName>Retailer Requested</fullName>
                </value>
                <value>
                    <fullName>No Capacity</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>ProjectServices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Executed</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project Service</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Services</pluralLabel>
    <recordTypes>
        <fullName>Booked</fullName>
        <active>true</active>
        <label>Booked</label>
    </recordTypes>
    <recordTypes>
        <fullName>Canceled</fullName>
        <active>true</active>
        <label>Canceled</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/classes/CancelLocationExt.cls
public without sharing class CancelLocationExt {
    ApexPages.StandardSetController setCon;
    public String errorMessage {get;set;}
    public ProjectLocation__c locationObj{get;set;}
    public string locationName{get;set;}
    public Project__c projObj{get;set;} 
    
    public CancelLocationExt(ApexPages.StandardSetController controller) {
        setCon = controller;
        locationObj=new ProjectLocation__c();
        if(setCon.getSelected().size()==0)
        {
            errorMessage = 'No locations selected'; 
        }
        else
        {
            ProjectLocation__c loc = (ProjectLocation__c)(setCon.getSelected()[0]);
            loc = [select name,project__c from ProjectLocation__c where id=: loc.id];
            projObj = [select name, status__c,ProjectCancelLeadTime__c from project__c where id=:loc.project__c ];
        }    
        getlocationName();
    }
    
    
    public string getlocationName() {                
        locationName='';
        list<ProjectLocation__c> lstlocations = (list<ProjectLocation__c>)setCon.getSelected();

        
        for(ProjectLocation__c j: lstlocations)
        {            
            j = [select name,project__c from ProjectLocation__c where id=: j.id];
            locationName = locationName + j.Name + ' , ';
        }
        return locationName;         
    }
    
    
    
    
    public pagereference cancel()
    {
    
        Savepoint sp = Database.setSavePoint();        
        try{
        
            string selReason = (string)locationObj.CancelReason__c;
            list<ProjectLocation__c> lstlocations = (list<ProjectLocation__c>)setCon.getRecords(); 
            String projstatus = [select project__r.status__c from ProjectLocation__c where id=:lstlocations[0].id limit 1].project__r.status__c ;
            
            
            
            Set<Id> executedprojectLocationsSet = new Set<Id>();
            Set<String> canceledJobsProjectServicesSet = new Set<String>();
            Set<Id> canceledJobsProjectLocationsSet = new Set<Id>();        
            
                    
            for(ProjectLocation__c loc: lstlocations)
            {
                canceledJobsProjectLocationsSet.add(loc.Id);
            
            }
    
            
            List<Job__c> cancellableJobs = [select id, name, jobStatus__c, Jobcanceledreason__c, ProjectLocation__c, ProjectService__c, JobStartDate__c from job__c where Project__c =: projObj.Id  and projectlocation__c in :canceledJobsProjectLocationsSet and jobStatus__c != 'Completed' and jobstartdate__c > :Date.Today().addDays(Integer.ValueOf(projObj.ProjectCancelLeadTime__c))];            
            List<Job__c> executedJobs = [select id, name, jobStatus__c, Jobcanceledreason__c, ProjectLocation__c, ProjectService__c from job__c where Project__c =: projObj.Id  and projectlocation__c in :canceledJobsProjectLocationsSet and (jobStatus__c = 'Completed' OR jobstartdate__c <= :Date.Today().addDays(Integer.ValueOf(projObj.ProjectCancelLeadTime__c)))];                        
    
    
            for(job__c job: cancellableJobs )
            {
                job.jobStatus__c = 'Canceled';
                job.Jobcanceledreason__c= selReason ;
                job.JobDateCanceled__c = Date.Today();
                canceledJobsProjectServicesSet.Add(String.valueOf(job.ProjectService__c).substring(0, 15));
            }
    
            for(job__c job: executedJobs )
            {
                executedprojectLocationsSet.Add(job.ProjectLocation__c);
            }
            
            canceledJobsProjectLocationsSet.RemoveAll(executedprojectLocationsSet);
            
            List<ProjectLocation__c> cancellableProjectLocations = [Select Id, Name, Status__c, CancelReason__c from ProjectLocation__c where Id in :canceledJobsProjectLocationsSet];        
            
            for(ProjectLocation__c loc:cancellableProjectLocations)
            {            
                loc.Status__c = 'Canceled';
                loc.CancelReason__c = selReason ;
            }
            
            
            TriggerUtil.SkipAllTriggers();    
            update cancellableJobs ;            
            update cancellableProjectLocations;
            
            //projObj.ReservedLocationsCount__c = [SELECT count() FROM ProjectLocation__c WHERE Project__c =: projObj.Id and Status__c = 'Booked'];
            update projObj; 
            
        }
        catch(Exception ex){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, ex.getMessage()));
            Database.rollback(sp);
            return null;
        }

        PageReference cancel = setCon.cancel();        
        system.debug('cancel::'+cancel);
        return cancel;           
    
        
    }
    
    public pagereference DoNotCancel()
    {
        /*PageReference cancel = setCon.cancel();        
        return cancel;*/
        
        PageReference pageRef  = new ApexPages.StandardController(projObj).view();
        pageRef.setRedirect(true);
        return pageRef;
        
    }

    
}