src_old/objects/Job__c.object
<CustomObject>
    <description>Job defines the body of work to be performed at a Location and all of the dates related to the Job performance. A Job is related to a Project, Project Service, Project Location, Job Material, Contact, Exception, and Job Attempt.</description>
    <fields>
        <fullName>NumberOfDays__c</fullName>
        <label>Number of Days</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OneHubRetailerId__c</fullName>
        <description>The field that indicates the OneHub Retailer ID number.</description>
        <inlineHelpText>The OneHub retailer ID of the job.</inlineHelpText>
        <label>OneHub Retailer ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProjectService__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field that indicates the Project Service.</description>
        <inlineHelpText>The project service number</inlineHelpText>
        <label>Project Service</label>
        <referenceTo>ProjectService__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field that indicates the name of the Project to which a Job belongs.</description>
        <inlineHelpText>The name of the project for this job</inlineHelpText>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Retailer__c</fullName>
        <description>The field that indicates the Retailer ID.</description>
        <formula>CASESAFEID(Project__r.Retailer__r.Id)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The Retailer ID from the project</inlineHelpText>
        <label>Retailer</label>
        <type>Text</type>
    </fields>
    <label>Job</label>
    <nameField>
        <displayFormat>JOB-{000000000}</displayFormat>
        <label>Job ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/Location__c.object
<CustomObject>
    <description>Location defines a location and its type, address, and the Retailer is it associated with. Location is related to Retailer, Job, and Project Location.</description>
    <fields>
        <fullName>OneHubRetailerId__c</fullName>
        <label>OneHub Retailer ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Retailer__c</fullName>
        <label>Retailer</label>
        <referenceTo>Retailer__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>An entry field that indicates the end date of the Project.</description>
        <inlineHelpText>The last date available to complete execution</inlineHelpText>
        <label>Project End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IsExternalProject__c</fullName>
        <defaultValue>false</defaultValue>
        <description>A checkbox that indicates that the Project is external.</description>
        <inlineHelpText>If selected, the project is external.</inlineHelpText>
        <label>Is External Project</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NumberOfDays__c</fullName>
        <inlineHelpText>Number of days available to complete project execution at a location</inlineHelpText>
        <label>Number of Days</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OneHubRetailerId__c</fullName>
        <description>A field that indicates the ID number of the OneHub retailer.</description>
        <inlineHelpText>The ID number of the OneHub retailer.</inlineHelpText>
        <label>OneHub Retailer Id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProjectScheduleOption__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Determines soft-dated or hard-dated scheduling of work</inlineHelpText>
        <label>Project Schedule Option</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>ScheduleOption__c.IsActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ScheduleOption__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Type</label>
        <referenceTo>ProjectType__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Retailer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Retailer</label>
        <referenceTo>Retailer__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>An entry field that indicates the start date of the Project.</description>
        <inlineHelpText>The date available to start execution</inlineHelpText>
        <label>Project Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planning</fullName>
                    <default>true</default>
                    <label>Planning</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Launched</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ended</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <recordTypes>
        <fullName>Canceled</fullName>
        <active>true</active>
        <label>Canceled</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ProjectLocation__c.object
<CustomObject>
    <description>Project Location relates a Location to a Project. Project Location is related Project, Job, and Location.</description>
    <fields>
        <fullName>OneHubRetailerId__c</fullName>
        <label>OneHub Retailer Id</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProjectType__c</fullName>
        <formula>Project__r.ProjectType__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>ProjectLocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Retailer__c</fullName>
        <formula>Project__r.Retailer__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Retailer</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Job Created</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project Location</label>
    <nameField>
        <displayFormat>PL-{0000}</displayFormat>
        <label>Location ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectService__c.object
<CustomObject>
    <description>Project Service relates a Service to a Project and is a container used to define the instance of a Service for a specific Project. Project Service is related to Project, Job, Project Service Attribute, Project Service Certification, Project Service Equipment, Project Service Material, Project Service Question, Project Service Target, and Service.</description>
    <fields>
        <fullName>NumberOfDays__c</fullName>
        <defaultValue>1</defaultValue>
        <inlineHelpText>Replaced with Project Number of Days</inlineHelpText>
        <label>Number of Days - N/A FOR NEW PROJECTS</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OneHubRetailerId__c</fullName>
        <label>One Hub Retailer ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProjectType__c</fullName>
        <formula>Project__r.ProjectType__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>ProjectServices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Retailer__c</fullName>
        <formula>Project__r.Retailer__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Retailer</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StartDayNumber__c</fullName>
        <inlineHelpText>Replaced with Day Number(s)</inlineHelpText>
        <label>Start Day Number - N/A FOR NEW PROJECTS</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Executed</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project Service</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Services</pluralLabel>
    <recordTypes>
        <fullName>Canceled</fullName>
        <active>true</active>
        <label>Canceled</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectType__c.object
<CustomObject>
    <description>Project Type defines a collection of Services and sets configuration options for a Project. Project Type is related to Project, Project Type Execution Company, Project Type Service, and Location Assignment.</description>
    <fields>
        <fullName>AllowMultidays__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Allow Multi-days</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SetScheduleDateLeadTime__c</fullName>
        <defaultValue>3</defaultValue>
        <label>Set Schedule Date Lead Time</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Project Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Types</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/Retailer__c.object
<CustomObject>
    <description>Retailer stores the retailers for the system. Retailer is related to Location, Retailer Service, Retailer Service Certification, and Retailer Service Equipment.</description>
    <fields>
        <fullName>OneHubRetailerId__c</fullName>
        <label>One Hub Retailer ID</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Retailer</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Retailers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ScheduleOption__c.object
<CustomObject>
    <description>Schedule Option defines the schedule options that are available when building a Project. Schedule Option is related to Project and Job.</description>
    <fields>
        <fullName>Code__c</fullName>
        <description>Unique value that should be used within APEX code when referencing the Schedule Option.</description>
        <inlineHelpText>Unique value that should be used within APEX code when referencing the Schedule Option.</inlineHelpText>
        <label>Code</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Schedule Option</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/classes/ManageJobsLocationsExt.cls
global without sharing class ManageJobsLocationsExt {
    
    public Project__c proj {get;set;}
    public String projectName {get;set;}
    public String projectId {get;set;} 
    public Boolean showCancelButton {get;set;}
    public Boolean showDeleteButton {get;set;}
    public Map<String,Boolean> hiddenMap {get;set;}
    public boolean showSetSchedule {get;set;}
    public String scheduleWindowStartDate {get;set;}
    public String scheduleWindowEndDate{get;set;}
    public Integer maxServiceDaysNeeded{get;set;}
    public boolean showScheduledate{get;set;}
    public String getNAMESPACE() {
        return CONSTANTS.CURRENTNAMESPACEPREFIX;
    }
    
    public ManageJobsLocationsExt(ApexPages.StandardController controller) {               
        ProjectID = ApexPages.currentPage().getParameters().get('projectid'); 
        proj = [select id,name,retailer__c, OneHubRetailerId__c,Status__c,IsExternalProject__c, ProjectScheduleOption__r.Code__c, format(StartDate__c), format(EndDate__c),NumberOfDays__c, ProjectType__r.SetScheduleDateLeadTime__c,ProjectType__r.AllowMultidays__c from project__c where id=:projectId];
        List<ProjectService__c> psList = [select id, NumberOfDays__c, StartDayNumber__c from ProjectService__c where Project__c =:projectId];
        maxServiceDaysNeeded = Integer.valueOf(proj.NumberOfDays__c);
        if(maxServiceDaysNeeded == null){
            maxServiceDaysNeeded = 1;
        }
        /*maxServiceDaysNeeded = 1;
        for(ProjectService__c ps:psList){
            if(ps.NumberOfDays__c > maxServiceDaysNeeded ){
                maxServiceDaysNeeded = Integer.valueOf(ps.NumberOfDays__c);
            }
        }*/
        showSetSchedule = false;
        showScheduledate = false;
        boolean hasScheduleLeadTime = false;
        if(proj.ProjectType__r.SetScheduleDateLeadTime__c != NULL && proj.StartDate__c.addDays(Integer.valueOf(proj.ProjectType__r.SetScheduleDateLeadTime__c * -1)) >= date.today()) {
            hasScheduleLeadTime = true;
        }
        if(proj.ProjectScheduleOption__r.Code__c == CONSTANTS.SCHEDULE_OPTION_USER){
            showScheduledate = true;
            if(hasScheduleLeadTime){
                showSetSchedule = true;
            }
        }
        scheduleWindowStartDate = String.valueOf(proj.StartDate__c);
        scheduleWindowEndDate = String.valueOf(proj.EndDate__c.addDays((maxServiceDaysNeeded * -1) + 1));
        projectName = proj.name;
        //showSetSchedule =  (proj.ProjectScheduleOption__r.Code__c != CONSTANTS.SCHEDULE_OPTION_EC) && (proj.Status__c == CONSTANTS.PROJECT_STATUS_BOOKED || proj.Status__c == CONSTANTS.PROJECT_STATUS_LAUNCHED || proj.Status__c == CONSTANTS.PROJECT_STATUS_PLANNING);
        Set<String> hiddenElemets = new Set<String>{'ProjectLocation__c.Delete', 'ProjectLocation__c.Cancel'};
        hiddenMap = UIConfig.isHidden(proj.Status__c, hiddenElemets);        
        showCancelButton = !hiddenMap.get('ProjectLocation__c.Cancel');
        showDeleteButton = !hiddenMap.get('ProjectLocation__c.Delete');
                  
    }
    
    //deprecated
    @RemoteAction
    global static list<location__c> getProj(string state,string city,string zipcode, string projectId, string Location,string Status) 
    {
        return null;
    }
    @RemoteAction
    global static list<location__c> getLocations(string state,string city,string zipcode, string projectId, string Location,string Status, string showScheduledOnly) 
    {  
        project__c proj = [select id,retailer__c from project__c where id=:projectId];
        string LocationQry = 'Select name,Status__c,Project__c, location__r.Address__c,location__r.state__c,location__r.name,location__r.city__c,location__r.postalcodename__c,location__r.postalcode__r.name,location__r.locationnumber__c,location__c, statuscomments__c, format(LocationScheduledDate__c) from ProjectLocation__c where project__c =  \'' + ProjectID +'\'  '; 
        boolean isFilterExist = false;
        
        Set<String> locsTofilter = new Set<String>();
        Location = Location.replace(' ','').replace(',','\n');
        for(String item : Location.split('\n'))
        {
           locsTofilter.add(item);           
        }
        
        if(Location!=null && Location!='')
        {   
            isFilterExist =true;         
            LocationQry+= ' and location__r.locationnumber__c IN :locsTofilter '; 
        }        
        
        if(state.indexOf('NONE') == -1 && state!=null)
        {   
            isFilterExist =true;         
            LocationQry+= ' and location__r.State__c = \'' + string.valueof(state) +'\'  '; 
        }     
        if(city!='' && city!=null)
        {   
            isFilterExist =true;         
            LocationQry+= ' and location__r.city__c like \'%' + string.valueof(city) +'%\'  '; 
        }     
        
        if(zipcode!='' && zipcode!=null)
        {            
            isFilterExist =true;
            LocationQry+= ' and location__r.postalcode__r.name like \'%' + string.valueof(zipcode) +'%\'  '; 
        }
        if(showScheduledOnly == 'yes'){
            isFilterExist =true;
            LocationQry+= ' and LocationScheduledDate__c != NULL  '; 
        }
        system.debug('__#### Status __'+Status+'-----'+Status.indexOf('NONE'));  
        //if(Status!='' && Status!=null)
        if(Status.indexOf('NONE') == -1)
        {            
            isFilterExist =true;
            if(Status=='Reserve'){
                LocationQry+= ' and  location__c in ( select location__c from job__c where project__c =  \'' + ProjectID +'\' )' ; 
            }
            else{
                LocationQry+= ' and  location__c not in ( select location__c from job__c where project__c =  \'' + ProjectID +'\' )' ; 
            }
        }        
        
        LocationQry+= '  order by status__c desc,name ';
        
        system.debug('__#### loc qry __'+LocationQry+'-----');  
        
        return Database.query(LocationQry);
        
    }
    
    @RemoteAction
    global static string Cancel(string allLocID,string projectID,string operation,string reason)
    {
        string msg = '';
        
        set<string> AllUniqIDSet = new set<string>();
        Id[] allIds = new Id[]{};
        for(string item : allLocID.split(','))
        {
            AllUniqIDSet.add(item);           
            allIds.add(item);
        }
        
        project__c projObj = [select name, status__c, ProjectCancelLeadTime__c from project__c where id=:projectID];
        
        TriggerUtil.SkipAllTriggers(); 
        
        if(operation=='Delete'){
   
            Integer jobCount = [Select count() from Job__c WHERE ProjectLocation__c in :AllUniqIDSet LIMIT :JobActionsHelper.JOB_BATCH_DELETE_DECISION_COUNT];
            
            List<ActionResponse> responses = ProjectLocationActionsHelper.DeleteProjectLocations(allIds);
            
            
            if (jobCount == JobActionsHelper.JOB_BATCH_DELETE_DECISION_COUNT)
            {
                return  'Delete Project Location(s) in progress';
            }
            if(responses[0].IsSuccessful){
                return  AllUniqIDSet.size() +' Project Location(s) deleted from project';
            }
            return  'Error deleting Project Location(s)';
            
        }
        else { //cancel    
            Integer jobCount = [Select count() from Job__c WHERE ProjectLocation__c in :AllUniqIDSet AND ProjectLocation__r.Status__c != :CONSTANTS.PROJECT_LOCATION_CANCELED LIMIT :JobActionsHelper.JOB_BATCH_CANCEL_DECISION_COUNT];
            List<ActionResponse> responses = ProjectLocationActionsHelper.CancelProjectLocation(allIds, reason, 'Cancel at Project Location(s) level');
            if (jobCount == JobActionsHelper.JOB_BATCH_CANCEL_DECISION_COUNT)
            {
                return  'Cancel Project Location(s) in progress';
            }
            if(responses[0].IsSuccessful){
                return  AllUniqIDSet.size() +' Project Location(s) canceled from project';
            }
            return  'Error canceling Project Location(s)';
        }
        
    } 
    
    @RemoteAction
    global static string setScheduleDate(string ids, string projectID, string scheduleDateString)
    {
        string msg = '';
        Date scheduleDate = Date.parse(scheduleDateString);
        
        Id[] allIds = new Id[]{};
        for(string item : ids.split(','))
        {
            allIds .add(item);
        }
        system.debug('allIds::::: '+allIds);
        Integer jobCount = [Select count() from Job__c WHERE ProjectLocation__c in :allIds AND ProjectLocation__r.Status__c != :CONSTANTS.PROJECT_LOCATION_CANCELED LIMIT :JobActionsHelper.JOB_BATCH_SCHEDULEDATE_DECISION_COUNT];
        if(jobCount == 0){
            return  'Error, no jobs found.';
        }
        List<ActionResponse> responses = ProjectLocationActionsHelper.setScheduleDates(allIds, scheduleDate);
        
        if (jobCount == JobActionsHelper.JOB_BATCH_SCHEDULEDATE_DECISION_COUNT)
        {
            return  'Schedule dates in progress';
        }
        if(responses[0].IsSuccessful){
            return  'Scheduled ' + jobCount + ' job(s)';
        }
        return  'Error processing your request. ' + responses[0].ResponseMessage;        
    }   
}