src_old/objects/Job__c.object
<CustomObject>
    <description>Job defines the body of work to be performed at a Location and all of the dates related to the Job performance. A Job is related to a Project, Project Service, Project Location, Job Material, Contact, Exception, and Job Attempt.</description>
    <fields>
        <fullName>ProjectLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field that indicates the Location of a Project.</description>
        <inlineHelpText>The location of the project</inlineHelpText>
        <label>Project Location</label>
        <referenceTo>ProjectLocation__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field that indicates the name of the Project to which a Job belongs.</description>
        <inlineHelpText>The name of the project for this job</inlineHelpText>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Job</label>
    <nameField>
        <displayFormat>JOB-{000000000}</displayFormat>
        <label>Job ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ProcessLastSyncTime__c.object
<CustomObject>
    <fields>
        <fullName>ProcessName__c</fullName>
        <label>Process Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SyncTime__c</fullName>
        <label>Sync Time</label>
        <type>DateTime</type>
    </fields>
    <label>Process Last Sync Time</label>
    <nameField>
        <label>Process Last Sync Time Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processes Last Sync Time</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <fields>
        <fullName>ApexJobName__c</fullName>
        <description>A field that indicates the apex job name of the Project.</description>
        <inlineHelpText>The apex job name of the project</inlineHelpText>
        <label>ApexJobName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsPendingChangeReleaseRequest__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Pending Change Release Requested</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsPendingChanges__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Pending Changes</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planning</fullName>
                    <default>true</default>
                    <label>Planning</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Launched</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ended</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <recordTypes>
        <fullName>Booked</fullName>
        <active>true</active>
        <label>Booked</label>
    </recordTypes>
    <recordTypes>
        <fullName>Canceled</fullName>
        <active>true</active>
        <label>Canceled</label>
    </recordTypes>
    <recordTypes>
        <fullName>Closed</fullName>
        <active>true</active>
        <label>Closed</label>
    </recordTypes>
    <recordTypes>
        <fullName>Ended</fullName>
        <active>true</active>
        <label>Ended</label>
    </recordTypes>
    <recordTypes>
        <fullName>Launched</fullName>
        <active>true</active>
        <label>Launched</label>
    </recordTypes>
    <recordTypes>
        <fullName>Planning</fullName>
        <active>true</active>
        <label>Planning</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ProjectLocation__c.object
<CustomObject>
    <description>Project Location relates a Location to a Project. Project Location is related Project, Job, and Location.</description>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>ProjectLocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Job Created</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project Location</label>
    <nameField>
        <displayFormat>PL-{0000}</displayFormat>
        <label>Location ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/ProjectActionsHelperTest.cls
@isTest
private class ProjectActionsHelperTest {
  static Date CURRENT_DATE;

  static {
    CURRENT_DATE = Date.today();
  }

  @testSetup static void setup(){
    TestDataUtil.init();
    TestDataUtil.disableTriggers();
    TestProject.create('demo').addAll();
    TestDataUtil.enableTriggers();
  }

  @isTest
  static void itShouldResetReleaseFields(){
    //given
    TriggerUtil.skipAllTriggers();
    Project__c p = TestProject.getProjects().get(0);
    p.ApexJobName__c = 'test';
    p.IsPendingChangeReleaseRequest__c = true;
    p.IsPendingChanges__c = true;
    update p;
    Set<Id> idSet = new Set<Id>{p.Id};

    //when
    test.startTest();
    ProjectActionsHelper.ResetProjectReleaseChangeFields(idSet);
    test.stopTest();

    //then
    Project__c r = TestProject.getProjects().get(0);
    QA.isTrue(r.ApexJobName__c != p.ApexJobName__c,'reset');
  }

  @isTest
  static void itShouldRunProjectHistoryGetter(){
    //given
    Project__c p = TestProject.getProjects().get(0);

    //when
    test.startTest();
    ProjectActionsHelper.LockProject(p,'test','test');
    ProjectActionsHelper.UnLockProject(p);
    ProjectActionsHelper.RunProjectHistoryGetter(); 
    test.stopTest();
    
    //then
  }

  @isTest
  static void itShouldRunProjectHistoryGetterTheOtherWay(){
    //given
    Project__c p = TestProject.getProjects().get(0);
    List<ProcessLastSyncTime__c> times = new List<ProcessLastSyncTime__c>{
        new ProcessLastSyncTime__c(
                ProcessName__c = 'ProjectChangeTracking',
                SyncTime__c = Datetime.now().addHours(-8)
            )
    };
    insert times;

    //when
    test.startTest();
    ProjectActionsHelper.RunProjectHistoryGetter(); 
    test.stopTest();
    
    //then
  }


  @isTest 
  static void itShouldMoveToLauched(){
    //given
    TriggerUtil.skipAllTriggers();
    Project__c p = TestProject.getProjects().get(0);
    p.Status__c = 'Booked';    
    update p;

    //when
    test.startTest();
    List<ActionResponse> result = ProjectActionsHelper.MoveProjectsTolaunched();
    test.stopTest();

    //then
    Project__c r = TestProject.getProjects().get(0);
    QA.EQ('Launched', r.Status__c, 'lauched');
  }

    @isTest 
  static void itShouldDeleteProject(){
    //given
    TriggerUtil.skipAllTriggers();
    Project__c p = TestProject.getProjects().get(0);
    p.Status__c = 'Booked';    
    update p;

    //when
    test.startTest();
    List<ActionResponse> result = ProjectActionsHelper.DeleteProject(p.Id, false);
    test.stopTest();

    //then
    List<Sobject> results = TestProject.getProjects();
    QA.EQ(0, results.size(), 'no projects');
  }

      @isTest 
  static void itShouldDeleteProjectInBatch(){
    //given
    TriggerUtil.skipAllTriggers();
    Project__c p = TestProject.getProjects().get(0);
    p.Status__c = 'Booked';    
    update p;

    //when
    test.startTest();
    List<ActionResponse> result = ProjectActionsHelper.DeleteProject(p.Id, true);
    test.stopTest();

    //then
    List<Sobject> results = TestProject.getProjects();
    QA.EQ(0, results.size(), 'no projects');
  }


    @isTest 
  static void itShouldCancelProject(){
    //given
    TriggerUtil.skipAllTriggers();
    Project__c p = TestProject.getProjects().get(0);
    p.Status__c = 'Booked';    
    update p;

    //when
    test.startTest();
    List<ActionResponse> result = ProjectActionsHelper.CancelProject(p.Id, 'Other','comment');
    test.stopTest();

    //then
    Project__c r = TestProject.getProjects().get(0);
    QA.EQ('Canceled', r.status__c, 'canceled');
  }

      @isTest 
  static void itShouldCancelProjectTheOtherWay(){
    //given
    TriggerUtil.skipAllTriggers();
    Project__c p = TestProject.getProjects().get(0);
    p.Status__c = 'Booked';    
    update p;

    //when
    test.startTest();
    List<ActionResponse> result = ProjectActionsHelper.CancelProject(null, 'Other','comment');
    test.stopTest();

  }


      @isTest 
  static void itShouldCancelProjectTheThirdWay(){
    //given
    TriggerUtil.skipAllTriggers();
    Project__c p = TestProject.getProjects().get(0);
    p.Status__c = 'Booked';    
    update p;
    delete [select id from job__c where project__c=:p.Id];
    delete [select id from projectlocation__c where project__c=:p.Id];
    
    TestProject tp = TestProject.get(p.Id)
        .addLocations(500)
        .addJobs();

    //when
    test.startTest();
    List<ActionResponse> result = ProjectActionsHelper.CancelProject(p.Id, 'Other','comment');
    test.stopTest();

  }


    @isTest 
  static void itShouldCloseProject(){
    //given
    TriggerUtil.skipAllTriggers();
    Project__c p = TestProject.getProjects().get(0);
    p.Status__c = 'Ended';    
    update p;

    //when
    test.startTest();
    List<ActionResponse> result = ProjectActionsHelper.CloseProject(p.Id);

    test.stopTest();

    //then
    Project__c r = TestProject.getProjects().get(0);
    QA.EQ('Closed', r.status__c, 'closed');
  }

    @isTest 
  static void itShouldCloseProjects(){
    //given
    TriggerUtil.skipAllTriggers();
    Project__c p = TestProject.getProjects().get(0);
    p.Status__c = 'Ended';    
    update p;

    //when
    test.startTest();
    List<ActionResponse> result = ProjectActionsHelper.CloseProjects(new List<Id>{p.Id});

    test.stopTest();

    //then
    Project__c r = TestProject.getProjects().get(0);
    QA.EQ('Closed', r.status__c, 'closed');
  }

      @isTest 
  static void itShouldCloseJobs(){
    //given
    TriggerUtil.skipAllTriggers();
    Project__c p = TestProject.getProjects().get(0);
    p.Status__c = 'Launched';    
    update p;

    //when
    test.startTest();
    List<ActionResponse> result = ProjectActionsHelper.CloseProjectsSansJobs(New List<Id>{p.Id});
    
    test.stopTest();

    //then
    Project__c r = TestProject.getProjects().get(0);
    QA.EQ('Closed', r.status__c, 'closed');
  }


      @isTest 
  static void itShouldLaunchProjects(){
    //given
    TriggerUtil.skipAllTriggers();
    Project__c p = TestProject.getProjects().get(0);
    p.Status__c = 'Booked';    
    update p;

    //when
    test.startTest();
    List<ActionResponse> result = ProjectActionsHelper.LaunchProjects(New List<Id>{p.Id});
    
    test.stopTest();

    //then
    Project__c r = TestProject.getProjects().get(0);
    QA.EQ('Launched', r.status__c, 'closed');
  }

  @isTest
  static void ItShouldDoCodeCoverage()
  {
        Project__c p = TestProject.getProjects().get(0);
        ProjectActionsHelper.ChangeStatus(p, 'Planning');


        integer size = ProjectActionsHelper.getUpdateSequenceChangeLogSize();
        size = ProjectActionsHelper.getMaxServicesForManualGeneration();

        ProjectActionsHelper.ReOrderProjectServiceRanks(p.Id);

        Map<String,String> rtMap = new Map<String,String>();
        rtMap.put('idname','');
        String pattern = 'id,name';
        ProjectActionsHelper.SetRecordType(p, rtMap, pattern);
  }


    @isTest 
  static void itShouldLaunchProjectSandsJobs(){
    //given
    TriggerUtil.skipAllTriggers();
    Project__c p = TestProject.getProjects().get(0);
    p.Status__c = 'Booked';    
    update p;

    //when
    test.startTest();
    List<ActionResponse> result = ProjectActionsHelper.LaunchProjectSansJobs(p.Id);
    
    test.stopTest();

    //then
    Project__c r = TestProject.getProjects().get(0);
    QA.EQ('Launched', r.status__c, 'closed');
  }


      @isTest 
  static void itShouldLaunchProject()
  {
    //given
    TriggerUtil.skipAllTriggers();
    Project__c p = TestProject.getProjects().get(0);
    p.Status__c = 'Booked';    
    update p;

    //when
    test.startTest();
    List<ActionResponse> result = ProjectActionsHelper.LaunchProject(p.Id);
    
    test.stopTest();

    //then
    Project__c r = TestProject.getProjects().get(0);
    QA.EQ('Launched', r.status__c, 'closed');
  }

        @isTest 
  static void itShouldLaunchProjectsSansJobs()
  {
    //given
    TriggerUtil.skipAllTriggers();
    Project__c p = TestProject.getProjects().get(0);
    p.Status__c = 'Booked';    
    update p;

    //when
    test.startTest();
    List<ActionResponse> result = ProjectActionsHelper.LaunchProjectsSansJobs(new Id[]{p.Id});
    
    test.stopTest();

    //then
    Project__c r = TestProject.getProjects().get(0);
    QA.EQ('Launched', r.status__c, 'closed');
  }

         @isTest 
  static void itShouldCloseProjectSansJobs()
  {
    //given
    TriggerUtil.skipAllTriggers();
    Project__c p = TestProject.getProjects().get(0);
    p.Status__c = 'Ended';    
    update p;

    //when
    test.startTest();
    List<ActionResponse> result = ProjectActionsHelper.CloseProjectSansJobs(p.Id);
    
    test.stopTest();

    //then
    Project__c r = TestProject.getProjects().get(0);
    QA.EQ('Closed', r.status__c, 'closed');
  }

         @isTest 
  static void itShouldCancelProjectSansJobs()
  {
    //given
    TriggerUtil.skipAllTriggers();
    Project__c p = TestProject.getProjects().get(0);
    p.Status__c = 'Ended';    
    update p;

    //when
    test.startTest();
    List<ActionResponse> result = ProjectActionsHelper.CancelProjectSansJobs(p.Id,'Other','comment');
    
    test.stopTest();

    //then
    Project__c r = TestProject.getProjects().get(0);
    QA.EQ('Canceled', r.status__c, 'canceled');
  }

         @isTest 
  static void itShouldDeleteAllJobsByProject()
  {
    //given
    TriggerUtil.skipAllTriggers();
    Project__c p = TestProject.getProjects().get(0);
    p.Status__c = 'Ended';    
    update p;

    //when
    test.startTest();
    List<ActionResponse> result = ProjectActionsHelper.DeleteAllJobsByProject(p.Id);
    test.stopTest();
  }

 @isTest 
  static void itShouldDeleteAllJobsByProjectInBatch()
  {
    //given
    TriggerUtil.skipAllTriggers();
    Project__c p = TestProject.getProjects().get(0);
    delete [select id from job__c where project__c=:p.Id];
    delete [select id from projectlocation__c where project__c=:p.Id];

    TestProject tP = TestProject.get(p.Id);
    tP.addLocations(500)
        .addJobs();

    integer count = [SELECT COUNT() FROM Job__c WHERE Project__c=:p.Id];

    //when
    test.startTest();
    List<ActionResponse> result = ProjectActionsHelper.DeleteAllJobsByProject(p.Id);
    test.stopTest();
  }

  @isTest
  static void itShouldProcessProjectHistoryChanges(){
    //given
     TriggerUtil.skipAllTriggers();
    Project__c p = TestProject.getProjects().get(0);
    p.Status__c = 'Ended';    
    update p;
    List<Project__History> phs = New list<Project__History>();
    

    //when
    test.startTest();
    ProjectActionsHelper.ProcessProjectHistoryChanges(phs);
    test.stopTest();
    //then

  }

  @isTest 
  static void itShouldRunProjectSequenceUpdater(){

    test.startTest();
    ProjectActionsHelper.RunProjectSequenceUpdater();
    test.stopTest();
  }
}