src_old/objects/Job__c.object
<CustomObject>
    <description>Job defines the body of work to be performed at a Location and all of the dates related to the Job performance. A Job is related to a Project, Project Service, Project Location, Job Material, Contact, Exception, and Job Attempt.</description>
    <fields>
        <fullName>ProjectLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field that indicates the Location of a Project.</description>
        <inlineHelpText>The location of the project</inlineHelpText>
        <label>Project Location</label>
        <referenceTo>ProjectLocation__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field that indicates the name of the Project to which a Job belongs.</description>
        <inlineHelpText>The name of the project for this job</inlineHelpText>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Job</label>
    <nameField>
        <displayFormat>JOB-{000000000}</displayFormat>
        <label>Job ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/JobImage__c.object
<CustomObject>
    <fields>
        <fullName>AttachmentId__c</fullName>
        <label>Attachment Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ImageContentType__c</fullName>
        <label>Image Content Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ImageDescription__c</fullName>
        <label>Image Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ImageName__c</fullName>
        <label>Image Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ImageURL__c</fullName>
        <label>ImageURL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Job Images</relationshipLabel>
        <relationshipName>Job_Images</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProcessingPickupDateTime__c</fullName>
        <label>Processing Pickup Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ProjectLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Location</label>
        <referenceTo>ProjectLocation__c</referenceTo>
        <relationshipLabel>Job Images</relationshipLabel>
        <relationshipName>Job_Images</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Job Images</relationshipLabel>
        <relationshipName>Job_Images</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Job Image</label>
    <nameField>
        <displayFormat>JI-{000000000}</displayFormat>
        <label>Job Images Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Images</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ProjectLocation__c.object
<CustomObject>
    <description>Project Location relates a Location to a Project. Project Location is related Project, Job, and Location.</description>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>ProjectLocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Location</label>
    <nameField>
        <displayFormat>PL-{0000}</displayFormat>
        <label>Location ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/classes/BatchGenerateJobImageUrl.cls
global class BatchGenerateJobImageUrl implements Database.Batchable<sObject>, Database.AllowsCallouts, Database.Stateful, Database.RaisesPlatformEvents{
    
    @testVisible 
    Id[] jobImageIds;
    
    global BatchGenerateJobImageUrl (Id[] jobImageIds){
        this.jobImageIds = jobImageIds;
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator([Select Id,name,ImageURL__c,ImageContentType__c,ProcessingPickupDateTime__c,ImageName__c, ImageDescription__c, Job__c,AttachmentId__c, ProjectLocation__c, Project__c  from JobImage__c  where Id in :jobImageIds]);
    }
    
    global void execute(Database.BatchableContext BC, List<JobImage__c> scope) {
        for(JobImage__c ji: scope)
        {
            
            if(!(String.isBlank(ji.AttachmentId__c)))
            {
                JobImageHandler.DoGenerateNewJobImageURL(ji);
            }
        }
        
    }
    
    global void finish(Database.BatchableContext BC) {
        List<JobImage__c> lstjobImage = [Select Id,name,ImageURL__c,ImageContentType__c,ProcessingPickupDateTime__c,ImageName__c, ImageDescription__c, Job__c,AttachmentId__c, ProjectLocation__c, Project__c  from JobImage__c  where id IN :jobImageIds];
        AsyncApexJob a = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed, TotalJobItems, CreatedBy.Email FROM AsyncApexJob WHERE Id = :BC.getJobId()];    
        List<Id> failedJobImages = new List<Id>();
        if (a.NumberOfErrors > 0 )
        {
            for(JobImage__c ji :lstjobImage )
            {
                
                if(string.isEmpty(ji.ImageURL__c))
                {
                    failedJobImages.add(ji.Id);
                }
            }
            
            String email = EmailHelper.getEmailDistribution();
            If (String.isBlank(email)) {return;} 
            List<String> emailList= new List<String>{email};
            string subject = 'batch Job Images failed Email Notification';
            EmailHelper.SendEmail(emailList,subject,genHtmlBody(failedJobImages));
            
            
        }
        
    }
    
    @testVisible 
    String genHtmlBody(List<Id> failedJobImages){
        List<String> html = new List<String>();
        html.add('<h1>Job Image failed  List</h1>');
        html.add('<br/></br>');
        //html.add('<div>Total Number of Job Images Failed : ' + failedJobImages.size() + '</div>');
        
        html.add('<div>Total Number of Job Image Id\'s Failed : ' + String.Join(failedJobImages,',') + '</div>');
        
        return String.join(html,'');
    }
    
}