src_old/objects/Job__c.object
<CustomObject>
    <description>Job defines the body of work to be performed at a Location and all of the dates related to the Job performance. A Job is related to a Project, Project Service, Project Location, Job Material, Contact, Exception, and Job Attempt.</description>
    <fields>
        <fullName>CompletionStatus__c</fullName>
        <description>A picklist that indicates if a Job was completed.</description>
        <inlineHelpText>Whether or not the job was completed</inlineHelpText>
        <label>Completion Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Not Completed</fullName>
                    <default>true</default>
                    <label>Not Completed</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IsExecuted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The checkbox that indicates if a Job has been executed.</description>
        <inlineHelpText>If selected, the job has been executed.</inlineHelpText>
        <label>Executed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsRescheduled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The checkbox that indicates that the Job is rescheduled.</description>
        <inlineHelpText>If selected, the job is rescheduled.</inlineHelpText>
        <label>Rescheduled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>JobCompletedDate__c</fullName>
        <description>The field that indicates the date the Job was completed.</description>
        <inlineHelpText>The date the job was completed</inlineHelpText>
        <label>Completed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>JobDateAssigned__c</fullName>
        <description>The field that indicates the date and time a Job was last assigned.	.</description>
        <inlineHelpText>The date and time the job was last assigned</inlineHelpText>
        <label>Date Assigned</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>JobDateOriginallyAssigned__c</fullName>
        <description>The field that indicates the date and time a Job was originally assigned.</description>
        <inlineHelpText>The date and time the job was originally assigned</inlineHelpText>
        <label>Date Originally Assigned</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>JobDateStarted__c</fullName>
        <description>The field that indicates the date and time a Job started.</description>
        <inlineHelpText>The date and time the job started</inlineHelpText>
        <label>Date Started</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>JobExecutedDate__c</fullName>
        <description>The field that indicates the date a Job was executed.</description>
        <inlineHelpText>The date the job was executed</inlineHelpText>
        <label>Executed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>JobScheduledDate__c</fullName>
        <description>The field that indicates the date a Job is scheduled.</description>
        <inlineHelpText>The date the job was scheduled</inlineHelpText>
        <label>Scheduled Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>JobStatus__c</fullName>
        <description>A picklist that indicates the status of the Job.</description>
        <inlineHelpText>The status of the job</inlineHelpText>
        <label>Job Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Started</fullName>
                </value>
                <value>
                    <fullName>Reported</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field that indicates the name of the Project to which a Job belongs.</description>
        <inlineHelpText>The name of the project for this job</inlineHelpText>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SurveyPhotoViewerEncodedId__c</fullName>
        <label>Survey Photo Viewer Encoded Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Job</label>
    <nameField>
        <displayFormat>JOB-{000000000}</displayFormat>
        <label>Job ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/JobAttempt__c.object
<CustomObject>
    <description>Job Attempt is an attempt of a Job performed at a location. Job Attempt is related to an Exception.</description>
    <fields>
        <fullName>IsExecuted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Executed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Job__c</fullName>
        <label>Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Job Attempts</relationshipLabel>
        <relationshipName>Job_Attempts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Job Attempt</label>
    <nameField>
        <displayFormat>JA-{000000000}</displayFormat>
        <label>Job Attempt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Attempts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/classes/JobTriggerHandlerTest.cls
@isTest

public class JobTriggerHandlerTest {
    static Date START_DATE = Datetime.Now().Date();
    static Date END_DATE = Datetime.Now().addDays(14).Date();
    static final Integer MAX_CONTACTS = 10;
    
    @testSetup static void setup() {
        TestUtil.turnOffTrigger();
        TestUtil.initBaseData();
        TestUtil.setupJobTestData(CONSTANTS.JOB_ATTEMPT_STATUS_OPEN, CONSTANTS.JOB_STATUS_PENDING);
        
    }
    static void triggersOff(){
        TriggerUtil.skipAllTriggers();
        
    }
    @isTest static void itShouldEncryptJob(){
        TestUtil.turnOffTrigger();
        String expName = 'demo';
        TestProject testP = TestProject.create(expName);
        testP.addLocations(1);
        testP.addJobs();
        //When
        Test.startTest();
        testP.addJobs();
        Test.stopTest();
        project__c result =TestProject.getProjects()[0];
        system.debug('project Id'+ result.Id);
        List<job__c> projJobs = TestProject.getJobs(result.Id);
        // system.assert(projLocations.size()>0);
        // system.debug('project Locations Size' +projLocations.size());
        system.assert(projJobs[0].SurveyPhotoViewerEncodedId__c != null);  
        
        
    }
    
    
    @isTest static void testIfJobNotCompletedThenCompletedDateShouldBeNull(){
        
        //given
        TestUtil.turnOffTrigger();
        JobAttempt__c attempt = TestUtil.getAttempt(null);
        Job__c job = TestUtil.getJob(attempt.Job__c);
        job.JobStatus__c = CONSTANTS.JOB_STATUS_OPEN;
        job.CompletionStatus__c = CONSTANTS.JOB_COMPLETION_STATUS_NOT_COMPLETED;
        job.JobCompletedDate__c = START_DATE.addDays(10);
        update job;
        
        //when
        TestUtil.turnOnJobTrigger();
        TEST.startTest();
        job.JobStatus__c = CONSTANTS.JOB_STATUS_OPEN;
        update job;
        TEST.stopTest();
        
        //then
        job = TestUtil.getJob(job.Id);
        System.assertEquals(null, job.JobCompletedDate__c, 'Job completed date should not be assigned.');
    }
    
    @isTest static void testIfJobCompeletedThenCompletedDateShouldBeNotNull(){
        
        //given
        TestUtil.turnOffTrigger();
        JobAttempt__c attempt = TestUtil.getAttempt(null);
        Job__c job = TestUtil.getJob(attempt.Job__c);
        Job.JobStatus__c = CONSTANTS.JOB_STATUS_STARTED;
        job.CompletionStatus__c = CONSTANTS.JOB_COMPLETION_STATUS_NOT_COMPLETED;
        job.JobCompletedDate__c = null;
        update job;
        
        //when
        TestUtil.turnOnJobTrigger();
        Test.startTest();
        job.CompletionStatus__c = CONSTANTS.JOB_COMPLETION_STATUS_COMPLETED;
        update job;
        Test.stopTest();
        
        //then
        job = TestUtil.getJob(job.Id);
        System.assertNotEquals(null, job.JobCompletedDate__c, 'Job completed date should be assigned.');
    }
    
    @isTest static void testIfJobNotExecutedThenExecutedDateShouldBeNull() {
        
        //given
        TestUtil.turnOffTrigger();
        JobAttempt__c attempt = TestUtil.getAttempt(null);
        Job__c job = TestUtil.getJob(attempt.Job__c);
        job.JobStatus__c = CONSTANTS.JOB_STATUS_OPEN;
        job.JobExecutedDate__c = START_DATE.addDays(3);
        update job;
        
        //when
        Test.startTest();
        TestUtil.turnOnJobTrigger();
        job.JobStatus__c = CONSTANTS.JOB_STATUS_REPORTED;
        job.IsExecuted__c = false;
        update job;
        Test.stopTest();
        
        //then
        job = TestUtil.getJob(job.Id);
        System.assertEquals(null, job.JobExecutedDate__c, 'Job executed date should not be assigned.');
    }
    
    @isTest static void testIfJobStartedThenJobStartedDateIsAssigned() {
        
        //given
        TestUtil.turnOffTrigger();
        JobAttempt__c attempt = TestUtil.getAttempt(null);
        Job__c job = TestUtil.getJob(attempt.Job__c);
        job.JobStatus__c = CONSTANTS.JOB_STATUS_PENDING;
        update job;
        
        //when
        Test.startTest();
        TestUtil.turnOnJobTrigger();
        Datetime today = Datetime.now().addDays(10);
        job.JobStatus__c = CONSTANTS.JOB_STATUS_STARTED;
        job.JobDateStarted__c = START_DATE;
        update job;
        Test.stopTest();
        
        //then
        job = TestUtil.getJob(job.Id);
        System.assertEquals(job.JobStatus__c, CONSTANTS.JOB_STATUS_STARTED, 'Job Status = Started');
        System.assertEquals(START_DATE, job.JobDateStarted__c,'Job started date assigned');
    }
    
    @isTest static void testIfJobAssignedThenDateAssigned() {
        
        //given
        TestUtil.turnOffTrigger();
        JobAttempt__c attempt = TestUtil.getAttempt(null);
        Job__c job = TestUtil.getJob(attempt.Job__c);
        job.JobStatus__c = CONSTANTS.JOB_STATUS_PENDING;
        update job;
        
        //when
        TestUtil.turnOnJobTrigger();
        Test.startTest();
        job.JobStatus__c = CONSTANTS.JOB_STATUS_ASSIGNED;
        update job;
        Test.stopTest();
        
        //then
        job = TestUtil.getJob(job.Id);
        System.assertEquals(CONSTANTS.JOB_ATTEMPT_STATUS_ASSIGNED, job.JobStatus__c, 'status assigned');
        System.assertNotEquals(null, job.JobDateAssigned__c,'Assigned Date set');
        System.assertNotEquals(null, job.JobDateOriginallyAssigned__c,'Originally Assigned Date set');
    }
    
    //scenario: <oh435: Job status is not updated to reported from open/assigned when job attempt is reported > ----
    @isTest static void testJobStatusTobeReported() {
        
        //--given--
        TestUtil.turnOffTrigger();
        JobAttempt__c attempt = TestUtil.getAttempt(null);
        Job__c job = TestUtil.getJob(attempt.Job__c);
        job.JobStatus__c = CONSTANTS.JOB_STATUS_OPEN;
        update job;
        
        //--when--
        TestUtil.turnOnJobTrigger();
        Test.startTest();
        job.JobStatus__c = CONSTANTS.JOB_STATUS_REPORTED;
        update job;
        Test.stopTest();
        
        //--then--
        Job__c r = TestUtil.getJob(job.Id);
        System.assertEquals(CONSTANTS.JOB_STATUS_REPORTED, r.JobStatus__c, 'Job Status is updated as Reported');
    }
        

    @istest static void testWhenJobScheduledSecondTimeRescheduleFlagShouldbeTrue() {
        // given
        TestUtil.turnOffTrigger();
        ID jobId = TestUtil.getAttempt(null).Job__c;
        Job__c job = TestUtil.getJob(jobId);
        Job.IsReScheduled__c = false;
        Job.JobScheduledDate__c = START_DATE.addDays(1);
        update job;
        
        // when
        Test.startTest();
        TestUtil.turnOnJobTrigger();
        job.JobScheduledDate__c = START_DATE.addDays(2);
        update job;
        Test.stopTest();
        
        // then
        Job__c result = TestUtil.getJob(jobId);
        System.assertEquals(true, result.IsReScheduled__c, 'IsReScheduled should be true');
    }
    
}