src_old/objects/Job__c.object
<CustomObject>
    <description>Job defines the body of work to be performed at a Location and all of the dates related to the Job performance. A Job is related to a Project, Project Service, Project Location, Job Material, Contact, Exception, and Job Attempt.</description>
    <fields>
        <fullName>JobCanceledReason__c</fullName>
        <description>A picklist that indicates reasons why a job was canceled.</description>
        <inlineHelpText>The reason that the job was canceled.</inlineHelpText>
        <label>Canceled Reason</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Supplier Requested</fullName>
                </value>
                <value>
                    <fullName>Retailer Requested</fullName>
                </value>
                <value>
                    <fullName>No Product</fullName>
                </value>
                <value>
                    <fullName>Item not approved</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NumberOfDays__c</fullName>
        <label>Number of Days</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OneHubLocationId__c</fullName>
        <formula>Location__r.OneHubLocationID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Location ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProjectNumber__c</fullName>
        <description>The field that indicates the Project Number.</description>
        <formula>Project__r.ProjectNumber__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field that indicates the name of the Project to which a Job belongs.</description>
        <inlineHelpText>The name of the project for this job</inlineHelpText>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Job</label>
    <nameField>
        <displayFormat>JOB-{000000000}</displayFormat>
        <label>Job ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <fields>
        <fullName>AddLocationsLeadTime__c</fullName>
        <formula>ProjectType__r.AddLocationsLeadTime__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AddLocationsLeadTime</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ApexJobName__c</fullName>
        <description>A field that indicates the apex job name of the Project.</description>
        <inlineHelpText>The apex job name of the project</inlineHelpText>
        <label>ApexJobName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>An entry field that indicates the end date of the Project.</description>
        <inlineHelpText>The last date available to complete execution</inlineHelpText>
        <label>Project End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NumberOfDays__c</fullName>
        <inlineHelpText>Number of days available to complete project execution at a location</inlineHelpText>
        <label>Number of Days</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProjectNumber__c</fullName>
        <displayFormat>{YY}{MM}{DD}{000000}</displayFormat>
        <inlineHelpText>this is help text in design</inlineHelpText>
        <label>Project Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>ProjectScheduleOption__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Determines soft-dated or hard-dated scheduling of work</inlineHelpText>
        <label>Project Schedule Option</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>ScheduleOption__c.IsActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ScheduleOption__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Type</label>
        <referenceTo>ProjectType__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RetailerAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Inherited from Project Type, but can be edited. Retailer Account will determine the Category selections at the Project Service.</inlineHelpText>
        <label>Retailer Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.OneHubAccountType__c</field>
                <operation>equals</operation>
                <value>Retailer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>An entry field that indicates the start date of the Project.</description>
        <inlineHelpText>The date available to start execution</inlineHelpText>
        <label>Project Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planning</fullName>
                    <default>true</default>
                    <label>Planning</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Launched</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ended</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <recordTypes>
        <fullName>Locked</fullName>
        <active>true</active>
        <label>Locked</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ProjectType__c.object
<CustomObject>
    <description>Project Type defines a collection of Services and sets configuration options for a Project. Project Type is related to Project, Project Type Execution Company, Project Type Service, and Location Assignment.</description>
    <fields>
        <fullName>AddLocationsLeadTime__c</fullName>
        <label>Add Locations Lead Time</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SetScheduleDateLeadTime__c</fullName>
        <defaultValue>3</defaultValue>
        <label>Set Schedule Date Lead Time</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UseReservations__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Use Reservations</label>
        <type>Checkbox</type>
    </fields>
    <label>Project Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Types</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ScheduleOption__c.object
<CustomObject>
    <description>Schedule Option defines the schedule options that are available when building a Project. Schedule Option is related to Project and Job.</description>
    <fields>
        <fullName>Code__c</fullName>
        <description>Unique value that should be used within APEX code when referencing the Schedule Option.</description>
        <inlineHelpText>Unique value that should be used within APEX code when referencing the Schedule Option.</inlineHelpText>
        <label>Code</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Schedule Option</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ProjectLocationSettings.cls
public without sharing class ProjectLocationSettings extends LightningRequestBase {
    public static final Map<Id, Integer> ADDLOCATION_LEADTIMES;
    public static final Map<Id, Boolean> ADDLOCATION_HASRESERVATIONS;
    public static final Integer SEARCHLOCATIONFIELD_BY_ONEHUBLOCATIONID;
    public static final Map<Id, String> PROJECT_RECORD_TYPES;
    
    static {
        ADDLOCATION_LEADTIMES = new Map<Id, Integer>();
        ADDLOCATION_HASRESERVATIONS = new Map<Id, boolean>();
        for(ProjectType__c pt: [SELECT Id, AddLocationsLeadTime__c, UseReservations__c FROM ProjectType__c]){
            ADDLOCATION_LEADTIMES.put(pt.Id, Integer.valueOf(pt.AddLocationsLeadTime__c));
            ADDLOCATION_HASRESERVATIONS.put(pt.Id, Boolean.valueOf(pt.UseReservations__c));
        }
        SEARCHLOCATIONFIELD_BY_ONEHUBLOCATIONID = checkSearchByOneHubId() ? 1: 0;
        PROJECT_RECORD_TYPES = initProjectRecordTypes();
    }
    
    static Map<Id, String> initProjectRecordTypes(){
        string namespace = CONSTANTS.CURRENTNAMESPACE;
        string sObjectName = CONSTANTS.CURRENTNAMESPACE.indexOf('CMK') != -1 ? 'CMKOneHub__Project__c': 'Project__c';
        Map<Id, String> objMap = new Map<Id, String>();
        for(RecordType tp: [SELECT Id, Name FROM RecordType WHERE SobjectType=:sObjectName]){
            objMap.put(tp.Id, tp.Name);      
        }
        return objMap;
    }
    
    static Boolean checkSearchByOneHubId(){
        String field = AppUtil.LocationSearchField;
        return (field != null && field.equalsIgnoreCase('OneHubLocationId__c'));
    }
    
    public static Boolean IsSearchLocationByOneHubId(){
        return SEARCHLOCATIONFIELD_BY_ONEHUBLOCATIONID == 1;
    }
    
    public override Object get(Object parameters) {
        Map<String,object> query = (Map<String,Object>) parameters;
        String projectId = LightningRequestHelper.parseString(query.get('projectId'));
        if (String.isBlank(projectId)){
            throw new AuraHandledException('The Project Id is required when retrieving the project location application settings.');
        }
        Map<String,Object> response = new Map<String,Object>();
        response.put('project', getProject(projectId));
        response.put('cancelReasons', getJobCancelReasons());
        return response;
    }
    
    Map<String,Object> getProject(String projectId){
        Map<String,Object> result = new Map<String,Object>();
        List<Project__c> pList = [SELECT Id, ProjectNumber__c, RecordTypeId, Status__c, StartDate__c, EndDate__c, 
                                  ProjectType__c, NumberOfDays__c, ProjectType__r.SetScheduleDateLeadTime__c, 
                                  ProjectScheduleOption__r.Code__c, ApexJobName__c, RetailerAccount__c 
                                  FROM Project__c Where Id=:projectId];
        if(pList.size() == 0){
            throw new AuraHandledException('The project can not be found.');
        }
        Project__c p = pList.get(0);
        result.put('locationReportUrl', AppUtil.LocationReportUrl.replace('{ProjectNumber}',p.ProjectNumber__c));
        result.put('startDate', p.StartDate__c);
        result.put('endDate', getEndDate(p));
        result.put('hasAccount', String.isNotBlank(p.RetailerAccount__c) ? 1 : 0);
        result.put('NumberOfDays', p.NumberOfDays__c != null ? p.NumberOfDays__c: 0);
        result.put('status', p.Status__c);
        result.put('locked', isProjectLocked(p.RecordTypeId) ? 1: 0);
        result.put('batchJob', String.isBlank(String.valueOf(p.ApexJobName__c)) ? 0: 1);
        result.put('canAddLocation', canAddLocation(p.EndDate__c, p.ProjectType__c));
        result.put('searchByOneHubId', SEARCHLOCATIONFIELD_BY_ONEHUBLOCATIONID);
        addScheduleSetting(p, result);
        return result;
    }
    
    static Boolean isProjectLocked(Id recordTypeId){
        if (!PROJECT_RECORD_TYPES.containsKey(recordTypeId)){
            return false;
        }
        String name = String.valueOf(PROJECT_RECORD_TYPES.get(recordTypeId));
        return name == 'Locked' ? true: false;
    }
    
    
    static Date getEndDate(Project__c proj){
        try{
            Integer maxServiceDaysNeeded = Integer.valueOf(proj.NumberOfDays__c) == null ? 1 : Integer.valueOf(proj.NumberOfDays__c);
            return proj.EndDate__c.addDays(1-maxServiceDaysNeeded);
        }catch(Exception ex){
        }
        return proj.EndDate__c;
    }
    
    static void addScheduleSetting(Project__c p, Map<String,Object> result){
        try{
            if (p.ProjectScheduleOption__r.Code__c == CONSTANTS.SCHEDULE_OPTION_USER){
                result.put('showSchedule', 1);
                result.put('canSchedule',canSchedule(p) ? 1: 0);
                return;
            }
        } catch(Exception ex){
            system.debug(ex.getLineNumber() + ':' + ex.getMessage());
        }
        
        result.put('showSchedule', 0);
        result.put('canSchedule', 0);
    }
    
    static Boolean canSchedule(Project__c proj){
        try{
            
            if( proj.ProjectType__r.SetScheduleDateLeadTime__c != NULL && 
               (Integer.valueOf(proj.ProjectType__r.SetScheduleDateLeadTime__c) <= -1 || 
                (proj.StartDate__c.addDays(Integer.valueOf(-proj.ProjectType__r.SetScheduleDateLeadTime__c))) >= date.today())) 
            {
                return true;
            }
        }catch(Exception ex){
            system.debug(ex.getLineNumber() + ':' + ex.getMessage());
        }
        return false;
    }
    
    static Integer canAddLocation(Date endDate, Id projectType){
        
        boolean hasReservation = Boolean.valueOf(ADDLOCATION_HASRESERVATIONS.get(projectType));
        if (hasReservation ){
            return 0;
        }
        
        if(endDate == null) {
            return 1;
        }
        
        Date dateEnd = Date.valueOf(endDate);
        Date today = Date.today();
        
        if (projectType == null || ADDLOCATION_LEADTIMES.get(projectType) == null){
            return dateEnd > today ? 1: 0;
        }
        
        Integer i = Integer.valueOf(ADDLOCATION_LEADTIMES.get(projectType));
        Date leadStartDate = dateEnd.addDays(-i);
        return leadStartDate > today ? 1: 0;
    }
    
    List<Map<String,String>> getJobCancelReasons(){
        return LightningRequestHelper.getPicklist('Job__c', 'JobCanceledReason__c');
    }
}