src_old/objects/Job__c.object
<CustomObject>
    <description>Job defines the body of work to be performed at a Location and all of the dates related to the Job performance. A Job is related to a Project, Project Service, Project Location, Job Material, Contact, Exception, and Job Attempt.</description>
    <fields>
        <fullName>EstimatedMinutes__c</fullName>
        <description>The field that indicates the estimated minutes for the Job.</description>
        <formula>IF(ISBLANK(EstimatedMinutesOverride__c), ProjectService__r.EstimatedMinutes__c, EstimatedMinutesOverride__c)</formula>
        <label>Time Estimate (Minutes)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LocationNumber__c</fullName>
        <description>The field that indicates the location number of the Job.</description>
        <formula>Location__r.LocationNumber__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The location number of the job</inlineHelpText>
        <label>Location #</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field that indicates the location of the Job.</description>
        <inlineHelpText>The location of the job</inlineHelpText>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjLocationName__c</fullName>
        <description>The field that indicates the name of the Project Location.</description>
        <formula>ProjectLocation__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The name of the project location</inlineHelpText>
        <label>Project Location Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProjServiceName__c</fullName>
        <description>The field that indicates the name of the Project Service.</description>
        <formula>ProjectService__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The name of the project service</inlineHelpText>
        <label>Project Service Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProjectLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field that indicates the Location of a Project.</description>
        <inlineHelpText>The location of the project</inlineHelpText>
        <label>Project Location</label>
        <referenceTo>ProjectLocation__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectNumber__c</fullName>
        <description>The field that indicates the Project Number.</description>
        <formula>Project__r.ProjectNumber__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProjectService__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field that indicates the Project Service.</description>
        <inlineHelpText>The project service number</inlineHelpText>
        <label>Project Service</label>
        <referenceTo>ProjectService__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field that indicates the name of the Project to which a Job belongs.</description>
        <inlineHelpText>The name of the project for this job</inlineHelpText>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ServiceName__c</fullName>
        <description>The field that indicates the name of the Service for the Job.</description>
        <inlineHelpText>The name for the service</inlineHelpText>
        <label>ServiceName</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Job</label>
    <nameField>
        <displayFormat>JOB-{000000000}</displayFormat>
        <label>Job ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/Location__c.object
<CustomObject>
    <description>Location defines a location and its type, address, and the Retailer is it associated with. Location is related to Retailer, Job, and Project Location.</description>
    <fields>
        <fullName>Banner__c</fullName>
        <label>Store Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Banner XYZ</fullName>
                    <default>true</default>
                    <label>Banner XYZ</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LocationNumber__c</fullName>
        <label>Location Number</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State/Province</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AS</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>FM</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>GU</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MH</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <fields>
        <fullName>ProjectNumber__c</fullName>
        <displayFormat>{YY}{MM}{DD}{000000}</displayFormat>
        <inlineHelpText>this is help text in design</inlineHelpText>
        <label>Project Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planning</fullName>
                    <default>true</default>
                    <label>Planning</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Launched</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ended</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <recordTypes>
        <fullName>Canceled</fullName>
        <active>true</active>
        <label>Canceled</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ProjectLocation__c.object
<CustomObject>
    <description>Project Location relates a Location to a Project. Project Location is related Project, Job, and Location.</description>
    <fields>
        <fullName>City__c</fullName>
        <formula>Location__r.City__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LocationName__c</fullName>
        <formula>Location__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Location Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LocationNumber__c</fullName>
        <formula>Location__r.LocationNumber__c</formula>
        <label>Location #</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Project Locations</relationshipLabel>
        <relationshipName>ProjectLocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>ProjectLocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <formula>TEXT(Location__r.State__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>State/Province/Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Job Created</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project Location</label>
    <nameField>
        <displayFormat>PL-{0000}</displayFormat>
        <label>Location ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectService__c.object
<CustomObject>
    <description>Project Service relates a Service to a Project and is a container used to define the instance of a Service for a specific Project. Project Service is related to Project, Job, Project Service Attribute, Project Service Certification, Project Service Equipment, Project Service Material, Project Service Question, Project Service Target, and Service.</description>
    <fields>
        <fullName>EstimatedMinutes__c</fullName>
        <inlineHelpText>Estimated Project Service minutes per rep</inlineHelpText>
        <label>Estimated Minutes</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProjectNumber__c</fullName>
        <formula>Project__r.ProjectNumber__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>ProjectServices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ServiceName__c</fullName>
        <formula>Service__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Service Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ServiceTitle__c</fullName>
        <inlineHelpText>Description of Service -- visible to rep and client</inlineHelpText>
        <label>Service Title</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Executed</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project Service</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Services</pluralLabel>
    <recordTypes>
        <fullName>Canceled</fullName>
        <active>true</active>
        <label>Canceled</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/classes/JobsCSV.cls
public with sharing class JobsCSV {

    Map<String, Integer> JobKeyIndexMap {get;set;}
    List<Job__c> Jobs {get;set;}
    List<ProjectLocation__c> ProjectLocations {get;set;}
    List<ProjectService__c> ProjectServices {get;set;}

    public String get(string projectId) {
        loadProjectServices(projectId);
        loadProjectLocations(projectId);
        loadJobs(projectId);
        setJobKeyIndexMap();
        return exportJobs();
    }

    void loadProjectServices(String projectId){
        this.ProjectServices =[SELECT ID,Name, ProjectNumber__c, ServiceName__c,ServiceTitle__c 
            FROM ProjectService__c  WHERE Project__c = :projectId AND Status__c != 'Canceled'];     
        if(this.ProjectServices.size() == 0)        
        {
            throw new AuraHandledException('there are no services for this project to export the  jobs');
        }
    }

    void loadProjectLocations(string projectId){
        this.ProjectLocations =[SELECT ID,Name,LocationName__c,State__c, City__c,LocationNumber__c,
            Location__r.Banner__c FROM  ProjectLocation__c  
            WHERE  Project__c = :projectId AND Status__c != 'Canceled'
            ORDER BY Location__r.Banner__c, LocationNumber__c LIMIT 10000];
        if(this.ProjectLocations.size() == 0){
            throw new AuraHandledException('There are no valid project locations.');
        }
    }

    void loadJobs(String projectId) {
        this.Jobs = [Select id, EstimatedMinutes__c, ProjServiceName__c,ProjLocationName__c,
            AccountableExecutionCompany__r.Name,NumberOfWorkers__c,JobStartDate__c,JobStartTime__c, 
            ProjectService__c,ProjectLocation__c, PurchaseAmount__c,Name,JobScheduledDate__c 
            from Job__c WHERE Project__c = :projectId  
            AND JobStatus__c !='Canceled'
            AND ProjectService__c IN (SELECT Id from ProjectService__c WHERE Project__c=:projectId 
            AND Status__c != 'Canceled') 
            AND ProjectLocation__c IN (SELECT Id from ProjectLocation__c WHERE Project__c=:projectId 
            AND Status__c != 'Canceled') LIMIT 200000];
    }

    void setJobKeyIndexMap(){        
        this.JobKeyIndexMap = new Map<string,Integer>();
        Integer count = this.Jobs.size();
        Job__c job;

        for(Integer i=0; i < count; i++)
        {
            job = this.Jobs.get(i);
            this.JobKeyIndexMap.put(genUniqueKey(job.ProjectService__c,job.ProjectLocation__c), i);
        }
    }

    static String genUniqueKey(Id psId, Id plId){
        return String.valueOf(psId) + String.valueOf(plId);
    }

    String exportJobs(){
        List<String> data = new  List<String>();
        data.add('"Project Service","Service Title","Project Location","State","City","Location Number","Banner","Job","Number Of Workers","Job Start Date","Job Start Time","Purchase Amount"');
        for(ProjectLocation__c pl :this.ProjectLocations)
        {
            for(ProjectService__c ps :this.ProjectServices) 
            {                
                data.add(transformJobs(ps,pl));
            }
        }
        return  String.join(data,'\n');
    }

    String transformJobs(ProjectService__c ps ,ProjectLocation__c pl){
        Job__c job;
        List<String> rec = new List<String>();
        string uniqueKey = genUniqueKey(ps.Id, pl.Id);

        rec.add('"' + ps.name + '"');
        rec.add('"' + ps.ServiceTitle__c + '"');
        rec.add('"' + pl.name + '"');
        rec.add('"' + pl.State__c + '"');
        rec.add('"' + pl.City__c + '"');
        rec.add('"' + pl.LocationNumber__c + '"');
        rec.add('"' + pl.Location__r.Banner__c + '"');
        
        if (this.JobKeyIndexMap.size() == 0 || !this.JobKeyIndexMap.containsKey(uniqueKey)){
            rec.add('""');
            rec.add('""');
            rec.add('""');
            rec.add('""');
            rec.add('""');
            return String.join(rec,',');
        } 

        job = this.Jobs.get(this.JobKeyIndexMap.get(uniqueKey));
        rec.add('"' + (String.isBlank(job.Name) ? '' : job.Name) + '"');
        rec.add('"' + (String.isBlank(String.valueOf(job.NumberOfWorkers__c)) ? '' : String.valueOf(job.NumberOfWorkers__c)) + '"');
        rec.add('"' + (job.JobStartDate__c != null ? String.valueOf(job.JobStartDate__c) : '') + '"');
        rec.add('"' + (String.isBlank(job.JobStartTime__c) ? '' : job.JobStartTime__c) + '"');
        rec.add('"' + (String.isBlank(String.valueOf(job.PurchaseAmount__c)) ? '': String.valueOf(job.PurchaseAmount__c)) + '"');
        return String.join(rec,',');
    }
}