src_old/objects/Job__c.object
<CustomObject>
    <description>Job defines the body of work to be performed at a Location and all of the dates related to the Job performance. A Job is related to a Project, Project Service, Project Location, Job Material, Contact, Exception, and Job Attempt.</description>
    <fields>
        <fullName>ActiveJobAttempt__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field that displays Job Attempts</description>
        <label>Active Job Attempt</label>
        <referenceTo>JobAttempt__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EndTime__c</fullName>
        <formula>JobEndTime__c</formula>
        <label>End Time</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>JobStatus__c</fullName>
        <description>A picklist that indicates the status of the Job.</description>
        <inlineHelpText>The status of the job</inlineHelpText>
        <label>Job Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Started</fullName>
                </value>
                <value>
                    <fullName>Reported</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>JobUTCEndTime__c</fullName>
        <description>The field that indicates the UTC end time of the Job.</description>
        <label>End Time (UTC)</label>
        <type>DateTime</type>
    </fields>
    <label>Job</label>
    <nameField>
        <displayFormat>JOB-{000000000}</displayFormat>
        <label>Job ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/JobAttempt__c.object
<CustomObject>
    <description>Job Attempt is an attempt of a Job performed at a location. Job Attempt is related to an Exception.</description>
    <fields>
        <fullName>EndTime__c</fullName>
        <label>End Time</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job__c</fullName>
        <label>Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Job Attempts</relationshipLabel>
        <relationshipName>Job_Attempts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PrimarySupervisorEmail__c</fullName>
        <formula>PrimaryJobAttemptWorker__r.SupervisorEmail__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PrimarySupervisorEmail</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrimaryWorkerEmail__c</fullName>
        <formula>PrimaryJobAttemptWorker__r.Email__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PrimarytWorkerEmail</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TeamLeadContactId__c</fullName>
        <formula>PrimaryJobAttemptWorker__r.Contact__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Team Lead Contact Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TeamLeadUserId__c</fullName>
        <formula>PrimaryJobAttemptWorker__r.UserId__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>TeamLeadUserId</label>
        <type>Text</type>
    </fields>
    <label>Job Attempt</label>
    <nameField>
        <displayFormat>JA-{000000000}</displayFormat>
        <label>Job Attempt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Attempts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/OrgCustomSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Generic org settings will be stored here</description>
    <fields>
        <fullName>ErrorNotificationEmail__c</fullName>
        <label>Error Notification Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Org Custom Settings</label>
</CustomObject>

force-app/main/default/classes/BatchShiftNotCloseNotification.cls
global without sharing class BatchShiftNotCloseNotification implements Database.Batchable<SObject>, Database.stateful {
   @testVisible
    Integer totalCount;
    @testVisible
    Integer errorCount;
    @testVisible
    Integer sendEmailCount;
    @testVisible
    List<Map<String,String>> Errors {get; private set;}

    global BatchShiftNotCloseNotification(){
        totalCount = 0;
        errorCount = 0;
        sendEmailCount = 0;
        Errors = new List<Map<String,String>>();
    }

    @testVisible
    static string buildQuery(){
        Datetime currentDTTM = Datetime.now().addMinutes(-15);
        String currentEndTime = currentDTTM.format('yyyy-MM-dd\'T\'HH:mm:ss.SSSZ','UTC');
        return 'SELECT Id, Name, EndTime__c, ActiveJobAttempt__r.TeamLeadContactId__c, ActiveJobAttempt__r.TeamLeadUserId__c, ActiveJobAttempt__r.PrimaryWorkerEmail__c,ActiveJobAttempt__r.PrimarySupervisorEmail__c FROM JOB__c WHERE ActiveJobAttempt__c != null AND JobUTCEndTime__c <=' + currentEndTime + ' AND JobStatus__c NOT IN (\'Closed\',\'Canceled\')';
    }

    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(buildQuery());
    }

    global void execute(Database.BatchableContext BC, List<SObject> scope) {
        ShiftNotCloseNotificationHandler handler= ShiftNotCloseNotificationHandler.create(scope).execute();
        this.totalCount += handler.TotalCount;
        this.errorCount += handler.ErrorCount;
        this.sendEmailCount += handler.EmailCount;
        if(handler.ErrorCount > 0){
            this.Errors.addAll(handler.Errors);
        }
    }

    global void finish(Database.BatchableContext BC) {
        String email = getEmailDistribution();
        If (String.isBlank(email)) {return;}

        List<String> emailList= new List<String>{email};
        List<Messaging.SingleEmailMessage> emailMessages = new List<Messaging.SingleEmailMessage>();
        Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
        message.setSubject('Non-Closed Shift Email Notification');
        message.setHtmlBody(genHtmlBody());
        message.setToAddresses(emailList);
        emailMessages.add(Message);
        Messaging.sendEmail(emailMessages);
    }

    @testVisible
    String genHtmlBody(){
        List<String> html = new List<String>();
        html.add('<h1>Shift Not Closed Primary Worker Emai Notification Process Report</h1>');
        html.add('<br/></br>');
        html.add('<div>Total Shifts to process: ' + this.totalCount + '</div>');
        html.add('<div>SendEmailCount: ' + this.sendEmailCount + '</div>');
        html.add('<div>ErrorCount: ' + this.errorCount + '</div>');
        html.add('<br/></br>');
        html.add(genErrorString());
        return String.join(html,'');
    }

    @testVisible
    String genErrorString(){
        List<String> html = new List<String>{
            '<table>',
            '<thead>',
            '<tr>',
            '<th>Shift</th>',
            '<th>Prmary Worker</th>',
            '<th>error</th>',
            '</tr>',
            '</thead>',
            '<tbody>'
        };
        for(Map<String,String> err: this.Errors){
            html.add(genRow(err));
        }
        html.add('</tbody></table>');
        return String.join(html,'');
    }
    
    @testVisible
    String genRow(Map<String,String> err){
        String[] html = new String[]{
            '<tr>',
            '<td>',
            err.get('job'),
            '</td>',
            '<td>',
            err.get('user'),
            '</td>',
            '<td>',
            err.get('message'),
            '</td>',
            '</tr>'
        };
        return String.join(html,'');
    }

    @testVisible
    static string getEmailDistribution(){
        OrgCustomSettings__c setting = [SELECT ErrorNotificationEmail__c FROM OrgCustomSettings__c LIMIT 1];
        return setting.ErrorNotificationEmail__c;
    }
}