src_old/objects/Job__c.object
<CustomObject>
    <description>Job defines the body of work to be performed at a Location and all of the dates related to the Job performance. A Job is related to a Project, Project Service, Project Location, Job Material, Contact, Exception, and Job Attempt.</description>
    <fields>
        <fullName>AccountableExecutionCompany__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field that indicates the Execution Company accountable for this Job.</description>
        <inlineHelpText>The execution company accountable for the job</inlineHelpText>
        <label>Accountable Execution Company</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Jobs (Accountable For Execution Company)</relationshipLabel>
        <relationshipName>Jobs_AccountableForExecutionCompany</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EstimatedMinutes__c</fullName>
        <description>The field that indicates the estimated minutes for the Job.</description>
        <formula>IF(ISBLANK(EstimatedMinutesOverride__c), ProjectService__r.EstimatedMinutes__c, EstimatedMinutesOverride__c)</formula>
        <label>Time Estimate (Minutes)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LocationNumber__c</fullName>
        <description>The field that indicates the location number of the Job.</description>
        <formula>Location__r.LocationNumber__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The location number of the job</inlineHelpText>
        <label>Location #</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LocationState__c</fullName>
        <description>The field that indicates the state where the Job is located.</description>
        <formula>TEXT(Location__r.State__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The state where the job is located</inlineHelpText>
        <label>Location State</label>
        <type>Text</type>
    </fields>
    <label>Job</label>
    <nameField>
        <displayFormat>JOB-{000000000}</displayFormat>
        <label>Job ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/JobAttempt__c.object
<CustomObject>
    <description>Job Attempt is an attempt of a Job performed at a location. Job Attempt is related to an Exception.</description>
    <fields>
        <fullName>DateAssigned__c</fullName>
        <label>Date Assigned</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ExpectedNumberofWorkers__c</fullName>
        <label>Expected Number of Workers</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Job__c</fullName>
        <label>Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Job Attempts</relationshipLabel>
        <relationshipName>Job_Attempts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PrimaryJobAttemptWorker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Job Attempt Worker</label>
        <referenceTo>JobAttemptWorker__c</referenceTo>
        <relationshipLabel>Job Attempts</relationshipLabel>
        <relationshipName>Job_Attempts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Job Attempt</label>
    <nameField>
        <displayFormat>JA-{000000000}</displayFormat>
        <label>Job Attempt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Attempts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/JobAttemptWorker__c.object
<CustomObject>
    <fields>
        <fullName>DateAssigned__c</fullName>
        <label>Date Assigned</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>EstimatedMinutes__c</fullName>
        <formula>JobAttempt__r.Job__r.EstimatedMinutes__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Estimated Minutes</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ExecutionCompany__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Execution Company</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Job Attempt Workers</relationshipLabel>
        <relationshipName>Job_Attempt_Workers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>JobAttempt__c</fullName>
        <label>Job Attempt</label>
        <referenceTo>JobAttempt__c</referenceTo>
        <relationshipLabel>Job Attempt Workers</relationshipLabel>
        <relationshipName>Job_Attempt_Workers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>LocationCity__c</fullName>
        <formula>JobAttempt__r.Job__r.Location__r.City__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Location City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LocationName__c</fullName>
        <formula>JobAttempt__r.Job__r.Location__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Location Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LocationNumber__c</fullName>
        <formula>JobAttempt__r.Job__r.Location__r.LocationNumber__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Location Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LocationState__c</fullName>
        <formula>TEXT(JobAttempt__r.Job__r.Location__r.State__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Location State</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>My3PLWork__c</fullName>
        <formula>if( $User.ThirdPartyAgency__c = ThirdPartyAgency__r.Name, True, false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>My3PLWork</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ScheduledDate__c</fullName>
        <formula>JobAttempt__r.AttemptScheduleDate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Scheduled Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Checked In</fullName>
                </value>
                <value>
                    <fullName>Checked Out</fullName>
                </value>
                <value>
                    <fullName>No Show</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ThirdPartyAgencyStatus__c</fullName>
        <label>3PL Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Requested</fullName>
                </value>
                <value>
                    <fullName>Canceled - Reassigned to CMK</fullName>
                </value>
                <value>
                    <fullName>Committed</fullName>
                </value>
                <value>
                    <fullName>Executed</fullName>
                </value>
                <value>
                    <fullName>Invoiced</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Agency Declined</fullName>
                </value>
                <value>
                    <fullName>Pending 3PL Agency Approval</fullName>
                </value>
                <value>
                    <fullName>CMK Rejected</fullName>
                </value>
                <value>
                    <fullName>Filled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WorkerType__c</fullName>
        <label>Worker Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Team Lead</fullName>
                </value>
                <value>
                    <fullName>Team Member</fullName>
                    <default>true</default>
                    <label>Team Member</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Job Attempt Worker</label>
    <nameField>
        <displayFormat>JAW-{000000000}</displayFormat>
        <label>Job Attempt Worker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Attempt Workers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/classes/JobAttemptWorkerHelper.cls
//#OH-4439
public class JobAttemptWorkerHelper {
    public static void Create(List<JobAttempt__c> jobAttempts) {
        
        List<JobAttempt__c> jas = [Select Id, Job__r.AccountableExecutionCompany__c, ExpectedNumberofWorkers__c from JobAttempt__c where Id in :jobAttempts];
        Map<Id, JobAttempt__c> jaMap = new Map<Id, JobAttempt__c>(jas);
        
        List<JobAttemptWorker__c> jobAttemptWorkers = new List<JobAttemptWorker__c>();
        Map<ID,JobAttempt__c> jobAttemptMap = new Map<ID,JobAttempt__c>();           
            
        for (JobAttempt__c jobAttempt : jobAttempts)
        {            
            jobAttempt = jaMap.get(jobAttempt.Id);                
                
            for(Integer i=0; i < jobAttempt.ExpectedNumberofWorkers__c; i++){
                
                jobAttemptMap.put(jobAttempt.Id, jobAttempt);
                    
                JobAttemptWorker__c jobAttemptWorker = new JobAttemptWorker__c();
                jobAttemptWorker.JobAttempt__c = jobAttempt.Id;  
                jobAttemptWorker.ExecutionCompany__c = jobAttempt.Job__r.AccountableExecutionCompany__c;
                jobAttemptWorker.WorkerType__c = (i == 0) ? CONSTANTS.JOB_ATTEMPT_WORKER_WORKER_TYPE_TEAM_LEAD : CONSTANTS.JOB_ATTEMPT_WORKER_WORKER_TYPE_TEAM_MEMBER;
                jobAttemptWorker.Status__c = CONSTANTS.JOB_ATTEMPT_WORKER_STATUS_OPEN;
                jobAttemptWorkers.add(jobAttemptWorker);
            }
        }
        
        insert jobAttemptWorkers;
        
        List<JobAttempt__c> jobAttemptWithPrimaryWorkerLists = new List<JobAttempt__c>();
        
        for (JobAttemptWorker__c jobAttemptWorker: jobAttemptWorkers)        
        {            
            if (jobAttemptWorker.WorkerType__c == CONSTANTS.JOB_ATTEMPT_WORKER_WORKER_TYPE_TEAM_LEAD )
            {          
                JobAttempt__c jobAttempt = jobAttemptMap.get(jobAttemptWorker.JobAttempt__c);                    
                jobAttempt.PrimaryJobAttemptWorker__c = jobAttemptWorker.Id;
                jobAttemptWithPrimaryWorkerLists.add(jobAttempt);
            }
        }       
        
        update jobAttemptWithPrimaryWorkerLists;
        
    }
   
    public static void AdjustJobAttemptWorker(JobAttempt__c jobAttempt,Integer previousNumberOfWorkers,Integer currentNumberOfWorkers)
    {
        
        // In case of increased number.
        if (previousNumberOfWorkers < currentNumberOfWorkers){
            AddJobAttemptWorker(jobAttempt ,(currentNumberOfWorkers - previousNumberOfWorkers));
        } else if (previousNumberOfWorkers > currentNumberOfWorkers){
            CancelJobAttemptWorker(jobAttempt ,(previousNumberOfWorkers - currentNumberOfWorkers));
        }
    }
    
   static void AddJobAttemptWorker(JobAttempt__c jobAttempt, Integer noOfWorkersToBeAdded){
        
        List<JobAttemptWorker__c> jobAttemptWorkers = new List<JobAttemptWorker__c>();
        
        for(Integer i=0; i < noOfWorkersToBeAdded; i++){
            JobAttemptWorker__c jobAttemptWorker = new JobAttemptWorker__c();
            jobAttemptWorker.JobAttempt__c = jobAttempt.Id;                            
            jobAttemptWorker.WorkerType__c = CONSTANTS.JOB_ATTEMPT_WORKER_WORKER_TYPE_TEAM_MEMBER;
            jobAttemptWorker.Status__c = CONSTANTS.JOB_ATTEMPT_WORKER_STATUS_OPEN;
            jobAttemptWorkers.add(jobAttemptWorker);
        }  
        
        insert jobAttemptWorkers;
    }
    
   static void CancelJobAttemptWorker(JobAttempt__c jobAttempt, Integer noOfWorkersToBeAdjusted){
                
        List<JobAttemptWorker__c> jobAttemptWorkers =[SELECT Id, Status__c FROM JobAttemptWorker__c 
                                                      	WHERE JobAttempt__c =: jobAttempt.Id 
                                                      	AND WorkerType__c != :CONSTANTS.JOB_ATTEMPT_WORKER_WORKER_TYPE_TEAM_LEAD 
                                                      	AND Status__c != :CONSTANTS.JOB_ATTEMPT_WORKER_STATUS_CANCELED 
                                                      	ORDER BY DateAssigned__c DESC
                                                     	LIMIT :noOfWorkersToBeAdjusted];
        
        for (JobAttemptWorker__c jobAttemptWorker: jobAttemptWorkers){
            jobAttemptWorker.Status__c = CONSTANTS.JOB_ATTEMPT_WORKER_STATUS_CANCELED;
        }
        
        update jobAttemptWorkers;
    }
    
    
    /*
     public static JobAttemptWorker__c getJobAttemptWorker(Id jobAttemptId)
     {
           return Database.query(
            TestUtil.genQuery('JobAttemptWorker__c') + ' WHERE JobAttempt__c=:jobAttemptId Limit 1'
            );
     
     }    
    */
    
    //sankar added
    // approvalStatus : Approve or Reject
    public static void CancelPending3PLRequest(List<string> jawList)    	
    {
        
        List<ProcessInstance> piList  = [SELECT Id, TargetObject.Name, TargetObjectId, Status, SubmittedById, CompletedDate, CreatedDate 
                                         FROM ProcessInstance 
                                         Where TargetObjectId in : jawList];
        
        ApprovePending3PLRequest(jawList,'Reassigned to CMK',CONSTANTS.APPROVAL_STATUS_REMOVED);
        
    }
    
    
    public static List<JobAttemptWorker__c> Get3PLAgencyPendingApprovalList(){
        
        //Set<ID> jwIdList = [select ProcessInstance.TargetObjectId from ProcessInstanceWorkitem where ProcessInstance.TargetObject.type = 'JobAttemptWorker__c'];
        Set<ID> jwIdList = new Set<ID>();
        
        List<ProcessInstanceWorkitem> instanceWorker = [Select ProcessInstance.TargetObjectId From ProcessInstanceWorkitem 
                                                        where ProcessInstance.TargetObject.type =: CONSTANTS.CURRENTNAMESPACEPREFIX + 'JobAttemptWorker__c'];
        for(ProcessInstanceWorkitem pi : instanceWorker)
        {
            jwIdList.add(pi.ProcessInstance.TargetObjectId);
        }
        
        List<JobAttemptWorker__c> jawList = [Select Id, Name,ScheduledDate__c, LocationName__c, LocationNumber__c, LocationCity__c, LocationState__c, EstimatedMinutes__c 
                                             From JobAttemptWorker__c 
                                             Where ThirdPartyAgencyStatus__c =:CONSTANTS.JOB_ATTEMPT_WORKER_3PL_STATUS_PENDING_3PL_AGENCY_APPROVAL
                                             AND My3PLWork__c = true                                             
                                             And Id in : jwIdList];
        
        return jawList;
    }
    
    // approvalStatus : Approve or Reject or Removed
    public static void ApprovePending3PLRequest(List<string> jawList, String reqComments, string approverReqStatus)    	
    {
        
        List<ProcessInstance> piList  = [SELECT Id, TargetObject.Name, TargetObjectId, Status, SubmittedById, CompletedDate, CreatedDate 
                                         FROM ProcessInstance 
                                         Where TargetObjectId in : jawList];
        
        Set<Id> reservationIds = new Set<Id>();
        Set<Id> processInstanceIds = new Set<Id>();
        
        for(ProcessInstance obj: piList){            
            processInstanceIds.add(obj.TargetObjectId);                                    
        }
        
        //Getting Work Item Id
        List<ProcessInstanceWorkitem> pItemList = [Select Id from ProcessInstanceWorkitem 
                                                   where ProcessInstance.TargetObjectId in: processInstanceIds];
        
        for(ProcessInstanceWorkitem pItem: pItemList){  
            if (pItemList != null && pItemList.size() > 0)
            {
                
                Approval.ProcessWorkitemRequest req = new Approval.ProcessWorkitemRequest();
                req.setComments(reqComments);
                
                //Approve / Reject / Removed Record
                req.setAction(approverReqStatus);            
                
                req.setWorkitemId(pItem.Id);
                
                // Submit the request for approval
                Approval.ProcessResult result = Approval.process(req);
            }  
        }
    }  
    //end sankar
}