src_old/objects/Job__c.object
<CustomObject>
    <description>Job defines the body of work to be performed at a Location and all of the dates related to the Job performance. A Job is related to a Project, Project Service, Project Location, Job Material, Contact, Exception, and Job Attempt.</description>
    <fields>
        <fullName>OneHubRetailerId__c</fullName>
        <description>The field that indicates the OneHub Retailer ID number.</description>
        <inlineHelpText>The OneHub retailer ID of the job.</inlineHelpText>
        <label>OneHub Retailer ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProjectCancelLeadTime__c</fullName>
        <description>The field that indicates the lead time for a Project to be canceled</description>
        <formula>Project__r.ProjectCancelLeadTime__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The lead name for a project to be canceled</inlineHelpText>
        <label>Project Cancel Lead Time</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProjectNumber__c</fullName>
        <description>The field that indicates the Project Number.</description>
        <formula>Project__r.ProjectNumber__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProjectOrigin__c</fullName>
        <description>The field that indicates the Project Origin.</description>
        <formula>Project__r.ProjectOrigin__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The project origin</inlineHelpText>
        <label>Project Origin</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProjectService__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field that indicates the Project Service.</description>
        <inlineHelpText>The project service number</inlineHelpText>
        <label>Project Service</label>
        <referenceTo>ProjectService__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field that indicates the name of the Project to which a Job belongs.</description>
        <inlineHelpText>The name of the project for this job</inlineHelpText>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field that indicates the Service for the Job.</description>
        <inlineHelpText>The service for the job</inlineHelpText>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Job</label>
    <nameField>
        <displayFormat>JOB-{000000000}</displayFormat>
        <label>Job ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/JobMaterial__c.object
<CustomObject>
    <description>Job Material is a helper object that stores tracking information and other Job specific information about Material needed to perform a Job.</description>
    <fields>
        <fullName>Material__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Material</label>
        <referenceTo>Material__c</referenceTo>
        <relationshipLabel>Job Materials</relationshipLabel>
        <relationshipName>Job_Materials</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectServiceMaterial__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Service Material</label>
        <referenceTo>ProjectServiceMaterial__c</referenceTo>
        <relationshipLabel>Job Materials</relationshipLabel>
        <relationshipName>Job_Materials</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Job Material</label>
    <nameField>
        <displayFormat>JM-{000000000}</displayFormat>
        <label>Job Material Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Materials</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/Material__c.object
<CustomObject>
    <description>Material defines a physical item that will be shipped to a Location to by a Fulfillment Center. Material is related to Fulfillment Center and Job Material.</description>
    <fields>
        <fullName>FulfillmentCenterName__c</fullName>
        <formula>FulfillmentCenter__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Fulfillment Center Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OneHubRetailerId__c</fullName>
        <label>One Hub Retailer ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Material</label>
    <nameField>
        <label>Material Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Materials</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <fields>
        <fullName>ApexJobName__c</fullName>
        <description>A field that indicates the apex job name of the Project.</description>
        <inlineHelpText>The apex job name of the project</inlineHelpText>
        <label>ApexJobName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FulfillmentLeadTime__c</fullName>
        <description>A field that indicates the lead time for fulfillment of the Project.</description>
        <formula>Retailer__r.FulfillmentLeadTime__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The lead time for fulfillment of the project.</inlineHelpText>
        <label>Fulfillment Lead Time</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IsJobManualRegenReqd__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The check box will be set when a the Job Manual has to be generated.</description>
        <inlineHelpText>The check box will be set when a the Job Manual has to be generated.</inlineHelpText>
        <label>Regenerate Job Manual</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OneHubRetailerId__c</fullName>
        <description>A field that indicates the ID number of the OneHub retailer.</description>
        <inlineHelpText>The ID number of the OneHub retailer.</inlineHelpText>
        <label>OneHub Retailer Id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProjectCancelLeadTime__c</fullName>
        <description>A field that indicates the lead time to cancel the Project.</description>
        <formula>Retailer__r.JobCancelLeadTime__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The lead time to cancel the project.</inlineHelpText>
        <label>Project Cancel Lead Time</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProjectNumber__c</fullName>
        <displayFormat>{YY}{MM}{DD}{000000}</displayFormat>
        <inlineHelpText>this is help text in design</inlineHelpText>
        <label>Project Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>ProjectOrigin__c</fullName>
        <label>Project Origin System</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>An entry field that indicates the start date of the Project.</description>
        <inlineHelpText>The date available to start execution</inlineHelpText>
        <label>Project Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planning</fullName>
                    <default>true</default>
                    <label>Planning</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Launched</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ended</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <recordTypes>
        <fullName>Planning</fullName>
        <active>true</active>
        <label>Planning</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ProjectService__c.object
<CustomObject>
    <description>Project Service relates a Service to a Project and is a container used to define the instance of a Service for a specific Project. Project Service is related to Project, Job, Project Service Attribute, Project Service Certification, Project Service Equipment, Project Service Material, Project Service Question, Project Service Target, and Service.</description>
    <fields>
        <fullName>FulfillmentCenterName__c</fullName>
        <label>Fulfillment Center Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OneHubRetailerId__c</fullName>
        <label>One Hub Retailer ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProjectNumber__c</fullName>
        <formula>Project__r.ProjectNumber__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>ProjectServices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>Project Services</relationshipLabel>
        <relationshipName>ProjectServices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Executed</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TargetType__c</fullName>
        <label>Target Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Project Service</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Services</pluralLabel>
    <recordTypes>
        <fullName>Planning</fullName>
        <active>true</active>
        <label>Planning</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectServiceMaterial__c.object
<CustomObject>
    <description>Relates Material to a Project Service. Material is added manually when building a Project. Project Service Material is related to Project Service and Material.</description>
    <fields>
        <fullName>InvoiceType__c</fullName>
        <label>Invoice Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Standard</fullName>
                </value>
                <value>
                    <fullName>Additional Cost</fullName>
                </value>
                <value>
                    <fullName>Partner 1</fullName>
                </value>
                <value>
                    <fullName>Partner 2</fullName>
                </value>
                <value>
                    <fullName>Partner 3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Material__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Material</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Material__c.IsActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Material__c</referenceTo>
        <relationshipLabel>Project Service Material</relationshipLabel>
        <relationshipName>ProjectServiceMaterial</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectService__c</fullName>
        <label>Project Service</label>
        <referenceTo>ProjectService__c</referenceTo>
        <relationshipLabel>Project Service Materials</relationshipLabel>
        <relationshipName>ProjectServiceMaterials</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Service Material</label>
    <nameField>
        <displayFormat>PSM-{00000000}</displayFormat>
        <label>Project Service Material Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Service Material</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/Service__c.object
<CustomObject>
    <description>Service contains the definition of a service. Service is related to Service Attribute, Service Exception, Service Question, Service Question Defined Response, Retailer Service, Retailer Service Equipment, and Project Service.</description>
    <fields>
        <fullName>TargetType__c</fullName>
        <label>Target Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Product</fullName>
                    <default>true</default>
                    <label>Product</label>
                </value>
                <value>
                    <fullName>Category</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/classes/ProjectServiceMaterialsAddExt.cls
public with sharing class ProjectServiceMaterialsAddExt {

   public ApexPages.StandardController controller;
    public ID psID {get;set;}    
    public Project__c project {get;set;}
    public ProjectService__c ps{get;set;}
    public projectservicematerial__c psm {get;set;}
    public Boolean IsLeadTimeAvailabe {get;set;}
    
    public list<projectservicematerial__c> materials{get;set;}
    public Boolean showMaterialButtons {get;private set;        }    
    public Map<String,Boolean> editableMap {get;set;}
    private void addMessage(ApexPages.Severity severity, String message){
    Apexpages.addMessage(new ApexPages.Message(severity, message));
    }

    private void initPSM() {
        psm= new projectservicematerial__c();
        psm.InvoiceType__c = 'Standard';
    }
    
    
    public ProjectServiceMaterialsAddExt(ApexPages.StandardController controller) {

        psID = ApexPages.CurrentPage().getParameters().get('id');   //'a0Hj0000002sPDp'; 'a0Hj00000037Dt5';
        ps = [SELECT Id, Name, Project__c, Project__r.ProjectNumber__c,    Service__c, TargetType__c, Status__c, FulfillmentCenterName__c, OneHubRetailerId__c FROM ProjectService__c where id =:psID ];
        
        initPSM();
        
        LoadMaterials();
        
        project = [Select Id, Name, Status__c, FulfillmentLeadTime__c,IsJobManualRegenReqd__c, ProjectCancelLeadTime__c , Project__c.StartDate__c, ProjectOrigin__c,ApexJobName__c, BatchProcessId__c from Project__c where Id =: ps.Project__c];
        
        Set<String> editableFields = new Set<String>{'Project__c.RL_Materials'};
        editableMap = UIConfig.isEditale(project.Status__c, editableFields);
        showMaterialButtons = editableMap.get('Project__c.RL_Materials');
        showMaterialButtons = showMaterialButtons && Schema.sObjectType.ProjectServiceMaterial__c.isUpdateable();  
        IsLeadTimeAvailabe = AppUtil.hasProjectLeadTimeByProjectId(project.Id);
        
    }

    private Boolean isAlaCarteMaterial(Material__c m) {
        return m.Kit__c == false ? true : false;
    }

    
    public PageReference AddMaterial(){ 
        //SaveAllChanges();   
        if(psm.Material__c == null) { return null; }
        if (psm.Quantity__c == null) {
            addMessage(ApexPages.Severity.ERROR, 'The quantity is required.');
            return null;
        }
        
        try{
            Material__c mat = [Select Id, Name, Description__c, EstimatedCostPerUnit__c, Kit__c from Material__c where Id = :psm.Material__c LIMIT 1];
            
            projectservicematerial__C pscObj = new projectservicematerial__C();
            pscObj.ProjectService__c = psID;
            pscObj.Material__c = psm.Material__c;
            pscObj.InvoiceType__c = psm.InvoiceType__c;
            //pscObj.MaterialName__c = mat.Name;
            pscObj.Quantity__c = psm.Quantity__c;
            pscObj.MaterialDescription__c = mat.Description__c;
            //pscObj.Kit__c=mat.Kit__c;
            //pscObj.CostPerUnit__c=mat.EstimatedCostPerUnit__c;
            insert pscObj;
            
            initPSM();

            UpdateProjectServiceFulfillmentCenter();        
            LoadMaterials();
            
            if(project.Status__c != CONSTANTS.PROJECT_STATUS_PLANNING)
            {
                List<ProjectServiceMaterial__c> psmList = [SELECT Id, ProjectService__c, Material__c FROM ProjectServiceMaterial__c WHERE id = :pscObj.Id];
                List<Job__c> jobs = [SELECT Id, ProjectService__c FROM Job__c WHERE  Project__c  = :project.Id AND ProjectService__c =: psId AND JobStatus__c != :CONSTANTS.JOB_ATTEMPT_STATUS_CANCELED];
                JobUpdatesHelper.createJobMaterials(jobs, psmList);
                project.IsJobManualRegenReqd__c=true;
                TriggerUtil.skipProjectTrigger = true;
                update project; 
            }
        }
        catch (Exception ex){
        
            if (ex.getMessage().Contains('duplicate'))
            {
                addMessage(ApexPages.Severity.ERROR, 'Material already added. Please check and try again.');
            }
            else if(!ex.getMessage().contains('VALIDATION_EXCEPTION')){
                addMessage(ApexPages.Severity.ERROR, ex.getMessage());
            }
            return null;
        }   
        
        return null;
    }
    
    public PageReference SaveAllChanges()
    {       
        update materials;
        if(project.Status__c != CONSTANTS.PROJECT_STATUS_PLANNING)
        {
            project.IsJobManualRegenReqd__c=true;
            TriggerUtil.skipProjectTrigger = true;
            update project; 
        }                
        UpdateProjectServiceFulfillmentCenter();        
        LoadMaterials();
        addMessage(ApexPages.Severity.CONFIRM, 'Material(s) saved successfully.'); 
        return null;
    }

    
    public PageReference DeleteMaterials()
    {
        
        string psmParamVal = ApexPages.currentpage().getParameters().get('psmParamDEL');

         if(project.Status__c != CONSTANTS.PROJECT_STATUS_PLANNING)
        {
            TriggerUtil.SkipAllTriggers();
            delete [SELECT Id FROM JobMaterial__c WHERE ProjectServiceMaterial__c =:psmParamVal];
            project.IsJobManualRegenReqd__c=true;
            TriggerUtil.skipProjectTrigger = true;
            update project; 
        }
        
        
        for (ProjectServiceMaterial__c m : materials) {
            if (psmParamVal == m.Id) {
                delete m;
                break;
            }
        }
        UpdateProjectServiceFulfillmentCenter();
        LoadMaterials();
        
        
        addMessage(ApexPages.Severity.CONFIRM, 'Material(s) deleted successfully.'); 
        return null;
    }
    

    public void LoadMaterials(){
        materials = [SELECT Id, ProjectService__c, Material__c, InvoiceType__c, MaterialDescription__c, CostPerUnit__c, TotalPrice__c, 
        Quantity__c, Kit__c,MaterialName__c, CustomDescription__c FROM ProjectServiceMaterial__c where ProjectService__c=:psid];       
		
    }
    
    private void UpdateProjectServiceFulfillmentCenter()
    {
        ProjectServiceMaterial__c psm;
        ProjectServiceMaterial__c[] psms = [Select Id, Material__r.FulfillmentCenterName__c from ProjectServiceMaterial__c where ProjectService__c = :ps.Id Limit 1];
        if (psms.size() > 0)
        {
            psm = psms[0];        
        }
        
        if (psm != null)
        {
            ps.FulfillmentCenterName__c = psm.Material__r.FulfillmentCenterName__c;
        }
        else
        {
            ps.FulfillmentCenterName__c = '';
        }

        TriggerUtil.SkipAllTriggers();
        update ps;
        //Comment Versioning Code
		/*        
        if (project.Status__c != 'Planning'){
                AppUtil.UpdateProjectVersion(project.Id);
        }
        */
    
    }       
}