src_old/objects/Job__c.object
<CustomObject>
    <description>Job defines the body of work to be performed at a Location and all of the dates related to the Job performance. A Job is related to a Project, Project Service, Project Location, Job Material, Contact, Exception, and Job Attempt.</description>
    <fields>
        <fullName>ProjectLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field that indicates the Location of a Project.</description>
        <inlineHelpText>The location of the project</inlineHelpText>
        <label>Project Location</label>
        <referenceTo>ProjectLocation__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectService__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field that indicates the Project Service.</description>
        <inlineHelpText>The project service number</inlineHelpText>
        <label>Project Service</label>
        <referenceTo>ProjectService__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field that indicates the name of the Project to which a Job belongs.</description>
        <inlineHelpText>The name of the project for this job</inlineHelpText>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Job</label>
    <nameField>
        <displayFormat>JOB-{000000000}</displayFormat>
        <label>Job ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <fields>
        <fullName>ApprovalDate__c</fullName>
        <description>A field that indicates the date and time that the Project was approved.</description>
        <inlineHelpText>The date and time that the project was approved.</inlineHelpText>
        <label>Approval Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>An entry field that indicates the end date of the Project.</description>
        <inlineHelpText>The last date available to complete execution</inlineHelpText>
        <label>Project End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ProjectLaunchDate__c</fullName>
        <description>A field that indicates the launch date for the Project</description>
        <inlineHelpText>The date the project becomes visible on execution platforms and fulfillment entities.</inlineHelpText>
        <label>Project Launch Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>An entry field that indicates the start date of the Project.</description>
        <inlineHelpText>The date available to start execution</inlineHelpText>
        <label>Project Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planning</fullName>
                    <default>true</default>
                    <label>Planning</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Launched</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ended</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ProjectLocation__c.object
<CustomObject>
    <description>Project Location relates a Location to a Project. Project Location is related Project, Job, and Location.</description>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>ProjectLocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Job Created</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project Location</label>
    <nameField>
        <displayFormat>PL-{0000}</displayFormat>
        <label>Location ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectService__c.object
<CustomObject>
    <description>Project Service relates a Service to a Project and is a container used to define the instance of a Service for a specific Project. Project Service is related to Project, Job, Project Service Attribute, Project Service Certification, Project Service Equipment, Project Service Material, Project Service Question, Project Service Target, and Service.</description>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>ProjectServices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Executed</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TargetType__c</fullName>
        <label>Target Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Project Service</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectServiceQuestion__c.object
<CustomObject>
    <description>Relates a Question to a Project Service. Questions from Service Question are added by default when a Service is added to a Project Service. Additional Questions can be added. Project Service Question is related to Project Service Question, Question, and Question Variant.</description>
    <fields>
        <fullName>ProjectService__c</fullName>
        <label>Project Service</label>
        <referenceTo>ProjectService__c</referenceTo>
        <relationshipLabel>ProjectServiceQuestions</relationshipLabel>
        <relationshipName>ProjectServiceQuestions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Service Question</label>
    <nameField>
        <displayFormat>PSQ-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Service Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/classes/SubmitProjectExtTest.cls
@isTest
public class SubmitProjectExtTest {
    @testSetup static void setup(){
        TestUtil.initBaseData();
        TestUtil.setupJobTestData(CONSTANTS.JOB_ATTEMPT_STATUS_OPEN, 
            CONSTANTS.JOB_ATTEMPT_STATUS_OPEN);
    }

    public static testMethod void Test_SubmitProject()
    {
        Project__c project = (Project__c) TestUtil.getRecord('Project__c');
        List<ProjectService__c> projServs = (List<ProjectService__c>) TestUtil.getRecordset('ProjectService__c');

        ApexPages.StandardController controller = new ApexPages.StandardController(project);
        ApexPages.currentPage().getParameters().put('id', project.Id);
        ApexPages.currentPage().getParameters().put('stage','submit');

        Test.startTest();
        projServs[0].TargetType__c=null;
        update projServs[0];
        project.StartDate__c = System.Today();
        project.approvaldate__c = System.Today().adddays(-10);
        project.ProjectLaunchDate__c = project.StartDate__c;
        update project;
        
        // now pass it to the extension
        SubmitProjectExt ext= new SubmitProjectExt(controller);
        ext.init();
        Test.stopTest();
        
        system.assert(ext != null);
        system.assert(ext.project != null);
        
        //system.assert(ext.invalidps.size() > 0);
        
        //system.assert(ext.leadtime == false);
        //system.assert(ext.invalidsq.size() > 0);
        //system.assert(ext.reservedLocation == false);
        //system.assert(ext.invalidjobsps.size() == 0);       
    }
    
    public static testMethod void Test_SubmitProjectwithJobs(){
        Project__c newproject = (Project__c) TestUtil.getRecord('Project__c');
        newproject.StartDate__c = System.Today();
        newproject.EndDate__c = System.Today().addDays(31);
        update newproject;
        
        List<ProjectService__c> newprojServs = (List<ProjectService__c>) TestUtil.getRecordset('ProjectService__c');
        //List<ProjectServiceQuestion__c> newsurveyQuestions = TestUtil.generateSurveyQuestions(1, newprojServs.get(0).Id, 'Multi-Select List');
        
        List<ProjectLocation__c> newpl = (List<ProjectLocation__c>) TestUtil.getRecordset('ProjectLocation__c');
        List<job__c> jobs = (List<job__c>) TestUtil.getRecordset('Job__c');

        Test.startTest();
        ApexPages.StandardController controller = new ApexPages.StandardController(newproject);
        ApexPages.currentPage().getParameters().put('id', newproject.Id);
        SubmitProjectExt ext= new SubmitProjectExt(controller);
        ext.init();
        Test.stopTest();

        system.assert(ext != null);
        system.assert(ext.project != null);
        
        system.assert(ext.invalidps.size() == 0);
        
        system.assert(ext.leadtime == true);
        
        
        //system.assert(ext.reservedLocation == true);
        
        //system.assert(ext.project.Status__c == 'Pending Approval');              
        
    }
}