src_old/objects/JobAttempt__c.object
<CustomObject>
    <description>Job Attempt is an attempt of a Job performed at a location. Job Attempt is related to an Exception.</description>
    <fields>
        <fullName>StartTime__c</fullName>
        <label>Start Time</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TotalInStoreTime__c</fullName>
        <label>Total In-Store Time</label>
        <summarizedField>JobAttemptWorker__c.TotalInStoreTime__c</summarizedField>
        <summaryForeignKey>JobAttemptWorker__c.JobAttempt__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Job Attempt</label>
    <nameField>
        <displayFormat>JA-{000000000}</displayFormat>
        <label>Job Attempt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Attempts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/JobAttemptWorker__c.object
<CustomObject>
    <fields>
        <fullName>CheckinTimeEntry__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Check In Time Entry</label>
        <referenceTo>JobAttemptWorkerTimeEntry__c</referenceTo>
        <relationshipLabel>Job Attempt Workers</relationshipLabel>
        <relationshipName>Job_Attempt_Workers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CheckoutTimeEntry__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Checkout Time Entry</label>
        <referenceTo>JobAttemptWorkerTimeEntry__c</referenceTo>
        <relationshipLabel>Job Attempt Workers (Checkout Time Entry)</relationshipLabel>
        <relationshipName>Job_Attempt_Workers1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>JobAttempt__c</fullName>
        <label>Job Attempt</label>
        <referenceTo>JobAttempt__c</referenceTo>
        <relationshipLabel>Job Attempt Workers</relationshipLabel>
        <relationshipName>Job_Attempt_Workers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>StartTime__c</fullName>
        <formula>JobAttempt__r.StartTime__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Start Time</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TotalInStoreTime__c</fullName>
        <label>Total In-Store Time</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Job Attempt Worker</label>
    <nameField>
        <displayFormat>JAW-{000000000}</displayFormat>
        <label>Job Attempt Worker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Attempt Workers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/JobAttemptWorkerTimeEntry__c.object
<CustomObject>
    <fields>
        <fullName>JobAttemptWorker__c</fullName>
        <label>Job Attempt Worker</label>
        <referenceTo>JobAttemptWorker__c</referenceTo>
        <relationshipLabel>Job Attempt Worker Time Entries</relationshipLabel>
        <relationshipName>Job_Attempt_Worker_Time_Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>StartTime__c</fullName>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>TimeEntryType__c</fullName>
        <label>Time Entry Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Check In</fullName>
                </value>
                <value>
                    <fullName>Check out</fullName>
                </value>
                <value>
                    <fullName>Lunch</fullName>
                </value>
                <value>
                    <fullName>Break</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Job Attempt Worker Time Entry</label>
    <nameField>
        <displayFormat>JAWTE-{000000000}</displayFormat>
        <label>Job Attempt Worker Time Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Attempt Worker Time Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/JobAttemptWorkerTimeEntryTriggerTest.cls
@isTest
private class JobAttemptWorkerTimeEntryTriggerTest {
        
    @testSetup 
    static void setup() 
    {
        TestUtil.initBaseData();
        JobAttempt__c attempt = TestUtil.setupJobTestData(CONSTANTS.JOB_ATTEMPT_STATUS_OPEN, CONSTANTS.JOB_STATUS_PENDING);
        TestUtil.generateJobAttemptWorkers(attempt, 3);
        
    }
    
    @isTest
    static void testTimeEntriesforJobWorker ()
    {
    	List<JobAttemptWorker__c> jaws = [Select Id, CheckinTimeEntry__c, CheckoutTimeEntry__c from JobAttemptWorker__c LIMIT 1];
        System.assert(jaws.size() > 0, 'No job attempt workers found');
        
        System.assert(jaws[0].CheckinTimeEntry__c == null);
        System.assert(jaws[0].CheckoutTimeEntry__c == null);
        
        //Insert a checkin time entry
        TestUtil.createJobAttemptWorkerTimeEntry(jaws[0], 'Check in');
        TestUtil.createJobAttemptWorkerTimeEntry(jaws[0], 'Check out');
        

    	List<JobAttemptWorkerTimeEntry__c> jawtes = [Select Id, TimeEntryType__c, StartTime__c from JobAttemptWorkerTimeEntry__c];
        System.assert(jawtes.size() > 0, 'No time entries found for the job attempt worker');
        

    	List<JobAttemptWorker__c> jaws2 = [Select Id, CheckinTimeEntry__c, CheckoutTimeEntry__c, TotalInStoreTime__c from JobAttemptWorker__c WHERE Id = :jaws[0].Id];
        System.assert(jaws2.size() > 0, 'No job attempt workers found');
		        
        System.assert(jaws2[0].CheckinTimeEntry__c != null);
        System.assert(jaws2[0].CheckoutTimeEntry__c != null);
        
        
        
    }	    

}