src_old/objects/JobAttemptWorker__c.object
<CustomObject>
    <fields>
        <fullName>EstimatedMinutes__c</fullName>
        <formula>JobAttempt__r.Job__r.EstimatedMinutes__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Estimated Minutes</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LocationCity__c</fullName>
        <formula>JobAttempt__r.Job__r.Location__r.City__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Location City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LocationName__c</fullName>
        <formula>JobAttempt__r.Job__r.Location__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Location Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LocationNumber__c</fullName>
        <formula>JobAttempt__r.Job__r.Location__r.LocationNumber__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Location Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LocationState__c</fullName>
        <formula>TEXT(JobAttempt__r.Job__r.Location__r.State__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Location State</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ScheduledDate__c</fullName>
        <formula>JobAttempt__r.AttemptScheduleDate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Scheduled Date</label>
        <type>Date</type>
    </fields>
    <label>Job Attempt Worker</label>
    <nameField>
        <displayFormat>JAW-{000000000}</displayFormat>
        <label>Job Attempt Worker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Attempt Workers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/classes/JobAttemptWorkerWrapper.cls
public class JobAttemptWorkerWrapper {
    @AuraEnabled
    public string Id{get; set;}
    @AuraEnabled
    public string Name{get; set;}
    
    @AuraEnabled
    public string ScheduledDate{get; set;}
    @AuraEnabled
    public string LocationName{get; set;}
    @AuraEnabled
    public string LocationNumber{get; set;}
    @AuraEnabled
    public string LocationCity{get; set;}
    @AuraEnabled
    public string LocationState{get; set;}
    @AuraEnabled
    public string EstimatedMinutes{get; set;}
    
    Public JobAttemptWorkerWrapper(){}
    public JobAttemptWorkerWrapper(JobAttemptWorker__c jaw){
        
        Id = jaw.Id;
        Name = jaw.Name;
        ScheduledDate = string.valueOf(jaw.ScheduledDate__c);
        LocationName =jaw.LocationName__c ;
        LocationNumber = jaw.LocationNumber__c;
        LocationCity=jaw.LocationCity__c;
        LocationState =jaw.LocationState__c;
        EstimatedMinutes= string.valueOf(jaw.EstimatedMinutes__c);
        
    }
}