src_old/objects/JobAttemptWorker__c.object
<CustomObject>
    <fields>
        <fullName>CheckinTimeEntry__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Check In Time Entry</label>
        <referenceTo>JobAttemptWorkerTimeEntry__c</referenceTo>
        <relationshipLabel>Job Attempt Workers</relationshipLabel>
        <relationshipName>Job_Attempt_Workers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CheckoutTimeEntry__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Checkout Time Entry</label>
        <referenceTo>JobAttemptWorkerTimeEntry__c</referenceTo>
        <relationshipLabel>Job Attempt Workers (Checkout Time Entry)</relationshipLabel>
        <relationshipName>Job_Attempt_Workers1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartTime__c</fullName>
        <formula>JobAttempt__r.StartTime__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Start Time</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TotalInStoreTime__c</fullName>
        <label>Total In-Store Time</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Job Attempt Worker</label>
    <nameField>
        <displayFormat>JAW-{000000000}</displayFormat>
        <label>Job Attempt Worker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Attempt Workers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/JobAttemptWorkerTimeEntry__c.object
<CustomObject>
    <fields>
        <fullName>JobAttemptWorker__c</fullName>
        <label>Job Attempt Worker</label>
        <referenceTo>JobAttemptWorker__c</referenceTo>
        <relationshipLabel>Job Attempt Worker Time Entries</relationshipLabel>
        <relationshipName>Job_Attempt_Worker_Time_Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>StartTime__c</fullName>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>TimeEntryType__c</fullName>
        <label>Time Entry Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Check In</fullName>
                </value>
                <value>
                    <fullName>Check out</fullName>
                </value>
                <value>
                    <fullName>Lunch</fullName>
                </value>
                <value>
                    <fullName>Break</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Job Attempt Worker Time Entry</label>
    <nameField>
        <displayFormat>JAWTE-{000000000}</displayFormat>
        <label>Job Attempt Worker Time Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Attempt Worker Time Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/JobAttemptWorkerTimeEntryTriggerHandler.cls
public class JobAttemptWorkerTimeEntryTriggerHandler extends TriggerHandler {
    
    
    public override void afterInsert(){
        
        Set<String> jawids = new Set<String>();
		Map<String, JobAttemptWorkerTimeEntry__c> checkincheckoutTimeEntries = new Map<String, JobAttemptWorkerTimeEntry__c>();
            
        for(JobAttemptWorkerTimeEntry__c jawte : (List<JobAttemptWorkerTimeEntry__c>) Trigger.New)
        {
            if (jawte.TimeEntryType__c == Constants.JOB_ATTEMPT_WORKER_TIME_ENTRY_TIME_ENTRY_TYPE_CHECK_IN ||
               jawte.TimeEntryType__c == Constants.JOB_ATTEMPT_WORKER_TIME_ENTRY_TIME_ENTRY_TYPE_CHECK_OUT)
            {
            	jawids.add(jawte.JobAttemptWorker__c);
                checkincheckoutTimeEntries.put(jawte.JobAttemptWorker__c + '-' + jawte.TimeEntryType__c, jawte);
            }
            
            
        }
        
        if (checkincheckoutTimeEntries.size() > 0)
        {
            List<JobAttemptWorker__c> jaws = [Select Id, CheckinTimeEntry__c, CheckinTimeEntry__r.StartTime__c, 
                                              CheckoutTimeEntry__c, CheckoutTimeEntry__r.StartTime__c, TotalInStoreTime__c 
                                              FROM JobAttemptWorker__c WHERE Id in :jawids];
        	for (JobAttemptWorker__c jaw : jaws)
            {
                DateTime checkinTime, checkoutTime;
                
				if (checkincheckoutTimeEntries.get(jaw.Id + '-' + Constants.JOB_ATTEMPT_WORKER_TIME_ENTRY_TIME_ENTRY_TYPE_CHECK_IN) != null)
                {
                    jaw.CheckinTimeEntry__c = checkincheckoutTimeEntries.get(jaw.Id + '-' + Constants.JOB_ATTEMPT_WORKER_TIME_ENTRY_TIME_ENTRY_TYPE_CHECK_IN).Id;
                	checkinTime = checkincheckoutTimeEntries.get(jaw.Id + '-' + Constants.JOB_ATTEMPT_WORKER_TIME_ENTRY_TIME_ENTRY_TYPE_CHECK_IN).StartTime__c;
                }
                else
                {
                    checkinTime = jaw.CheckinTimeEntry__r.StartTime__c;
                }
                
				if (checkincheckoutTimeEntries.get(jaw.Id + '-' + Constants.JOB_ATTEMPT_WORKER_TIME_ENTRY_TIME_ENTRY_TYPE_CHECK_OUT) != null)
                {
                    jaw.CheckoutTimeEntry__c = checkincheckoutTimeEntries.get(jaw.Id + '-' + Constants.JOB_ATTEMPT_WORKER_TIME_ENTRY_TIME_ENTRY_TYPE_CHECK_OUT).Id;
                    checkoutTime = checkincheckoutTimeEntries.get(jaw.Id + '-' + Constants.JOB_ATTEMPT_WORKER_TIME_ENTRY_TIME_ENTRY_TYPE_CHECK_OUT).StartTime__c;
                }
                else
                {
                    checkoutTime = jaw.CheckoutTimeEntry__r.StartTime__c;
                }
                
                if (checkinTime != null && checkoutTime != null)
                {
                    jaw.TotalInStoreTime__c = CalculateTotalInstoreTimeInMinutes(checkinTime, checkoutTime);
                }

            }
			update jaws;            
            
        }
       
    }
    
    public override void afterUpdate(){

	    Set<String> jawids = new Set<String>();        
        for(JobAttemptWorkerTimeEntry__c jawte : (List<JobAttemptWorkerTimeEntry__c>) Trigger.New)
        {
            JobAttemptWorkerTimeEntry__c oldjawte = (JobAttemptWorkerTimeEntry__c) System.Trigger.oldMap.get(jawte.Id);
            if (oldjawte.StartTime__c != jawte.StartTime__c && (jawte.TimeEntryType__c == Constants.JOB_ATTEMPT_WORKER_TIME_ENTRY_TIME_ENTRY_TYPE_CHECK_IN 
                                                                || jawte.TimeEntryType__c == Constants.JOB_ATTEMPT_WORKER_TIME_ENTRY_TIME_ENTRY_TYPE_CHECK_OUT))
            {

	        	jawids.add(jawte.JobAttemptWorker__c);        
                
            }
            
            
            List<JobAttemptWorker__c> jaws = [Select Id, CheckinTimeEntry__c, CheckinTimeEntry__r.StartTime__c, 
                                              CheckoutTimeEntry__c, CheckoutTimeEntry__r.StartTime__c, TotalInStoreTime__c 
                                              FROM JobAttemptWorker__c WHERE Id in :jawids];
        	for (JobAttemptWorker__c jaw : jaws)
            {
                if (jaw.CheckinTimeEntry__c != null && jaw.CheckoutTimeEntry__c != null && 
                    jaw.CheckinTimeEntry__r.StartTime__c != null && jaw.CheckoutTimeEntry__r.StartTime__c != null)
                {
                	jaw.TotalInStoreTime__c = CalculateTotalInstoreTimeInMinutes(jaw.CheckinTimeEntry__r.StartTime__c,jaw.CheckoutTimeEntry__r.StartTime__c);    
                }
            }   
            
            update jaws;
        }
    }
    
    private Integer CalculateTotalInstoreTimeInMinutes(DateTime checkinTime, DateTime checkoutTime)
    {
        return Integer.valueOf((checkoutTime.getTime() - checkinTime.getTime())/60000);
    }
    

}