src_old/objects/JobAttempt__c.object
<CustomObject>
    <description>Job Attempt is an attempt of a Job performed at a location. Job Attempt is related to an Exception.</description>
    <fields>
        <fullName>ProjectLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Location</label>
        <referenceTo>ProjectLocation__c</referenceTo>
        <relationshipLabel>Job Attempts</relationshipLabel>
        <relationshipName>Job_Attempts_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ReportedContactFirstName__c</fullName>
        <formula>ReportedContact__r.FirstName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Reported Contact First Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ReportedContactLastName__c</fullName>
        <formula>ReportedContact__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Reported Contact Last Name</label>
        <type>Text</type>
    </fields>
    <label>Job Attempt</label>
    <nameField>
        <displayFormat>JA-{000000000}</displayFormat>
        <label>Job Attempt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Attempts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/JobImage__c.object
<CustomObject>
    <fields>
        <fullName>CloudinaryImageUrl__c</fullName>
        <formula>$Setup.SurveyPhotoViewerSetting__c.CloudinaryImageURL__c + ImageURL__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CloudinaryImageUrl</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ImageURL__c</fullName>
        <label>ImageURL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>IsDuplicated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>There is already another similar photo in the table.</description>
        <inlineHelpText>This photo is duplicated.</inlineHelpText>
        <label>Is Duplicated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsFavorite__c</fullName>
        <defaultValue>false</defaultValue>
        <description>IsFavorite</description>
        <label>IsFavorite</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsUserFavorite__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The external user favorite indicator</description>
        <inlineHelpText>The external user favorite indicator</inlineHelpText>
        <label>Is User Favorite</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>JobAttempt__c</fullName>
        <label>Job Attempt</label>
        <referenceTo>JobAttempt__c</referenceTo>
        <relationshipLabel>Job Images</relationshipLabel>
        <relationshipName>Job_Images</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>JobDateReported__c</fullName>
        <label>Job Date Reported</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ParentLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Parent Location</description>
        <label>ParentLocation</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>ParentLocation</relationshipLabel>
        <relationshipName>Job_Images</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PhotoHash__c</fullName>
        <description>PhotoHash</description>
        <label>PhotoHash</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PoorQualityCheck__c</fullName>
        <defaultValue>false</defaultValue>
        <description>PoorQualityCheck</description>
        <label>PoorQualityCheck</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProjectLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Location</label>
        <referenceTo>ProjectLocation__c</referenceTo>
        <relationshipLabel>Job Images</relationshipLabel>
        <relationshipName>Job_Images</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectService__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Service</label>
        <referenceTo>ProjectService__c</referenceTo>
        <relationshipLabel>Job Images</relationshipLabel>
        <relationshipName>Job_Images</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Job Images</relationshipLabel>
        <relationshipName>Job_Images</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Job Images</relationshipLabel>
        <relationshipName>Job_Images</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Target__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Target</label>
        <referenceTo>Target__c</referenceTo>
        <relationshipLabel>Job Images</relationshipLabel>
        <relationshipName>Job_Images</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Job Image</label>
    <nameField>
        <displayFormat>JI-{000000000}</displayFormat>
        <label>Job Images Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Images</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/Location__c.object
<CustomObject>
    <description>Location defines a location and its type, address, and the Retailer is it associated with. Location is related to Retailer, Job, and Project Location.</description>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LocationNumber__c</fullName>
        <label>Location Number</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State/Province</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AS</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>FM</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>GU</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MH</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>An entry field that indicates the end date of the Project.</description>
        <inlineHelpText>The last date available to complete execution</inlineHelpText>
        <label>Project End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ProjectNumber__c</fullName>
        <displayFormat>{YY}{MM}{DD}{000000}</displayFormat>
        <inlineHelpText>this is help text in design</inlineHelpText>
        <label>Project Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>An entry field that indicates the start date of the Project.</description>
        <inlineHelpText>The date available to start execution</inlineHelpText>
        <label>Project Start Date</label>
        <type>Date</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ProjectLocation__c.object
<CustomObject>
    <description>Project Location relates a Location to a Project. Project Location is related Project, Job, and Location.</description>
    <fields>
        <fullName>City__c</fullName>
        <formula>Location__r.City__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LocationName__c</fullName>
        <formula>Location__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Location Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LocationNumber__c</fullName>
        <formula>Location__r.LocationNumber__c</formula>
        <label>Location #</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>ProjectLocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <formula>TEXT(Location__r.State__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>State/Province/Region</label>
        <type>Text</type>
    </fields>
    <label>Project Location</label>
    <nameField>
        <displayFormat>PL-{0000}</displayFormat>
        <label>Location ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectService__c.object
<CustomObject>
    <description>Project Service relates a Service to a Project and is a container used to define the instance of a Service for a specific Project. Project Service is related to Project, Job, Project Service Attribute, Project Service Certification, Project Service Equipment, Project Service Material, Project Service Question, Project Service Target, and Service.</description>
    <fields>
        <fullName>ProjectNumber__c</fullName>
        <formula>Project__r.ProjectNumber__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>ProjectServices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ServiceTitle__c</fullName>
        <inlineHelpText>Description of Service -- visible to rep and client</inlineHelpText>
        <label>Service Title</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Project Service</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/Question__c.object
<CustomObject>
    <description>Question stores all of the questions stored in the system and defines the type of question (e.g. Date, Text, Y/N) and if the question is related to targets. Question is related to Question Defined Response, Question Variant.</description>
    <fields>
        <fullName>QuestionText__c</fullName>
        <label>Question Text</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/objects/Target__c.object
<CustomObject>
    <description>Target defines what a Worker will observe and answer questions about. Targets could include Products, Categories, Displays, or any other type of Target configured for an instance. Target is related to Project Service Target and Retailer.</description>
    <fields>
        <fullName>ImageURL__c</fullName>
        <description>Photo of the target</description>
        <inlineHelpText>Photo of the target</inlineHelpText>
        <label>ImageURL</label>
        <type>Url</type>
    </fields>
    <label>Target</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Targets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/classes/PhotoRequest.cls
public with sharing class PhotoRequest extends LightningRequestBase {

    public override Object get(Object parameters){
        String jobImageId = getJobImageId(parameters);
        validateId(jobImageId);
        return this.getOneImageDetail(jobImageId);
    }

    public override Object filter(Object parameters) {
        List<String> idSet = this.parseJobImageIds(parameters);
        return this.getImageDetails(idSet);
    }

    public override Object modify(Object parameters){
        String jobImageId = getJobImageId(parameters);
        validateId(jobImageId);

        JobImage__c img = getJobImage(jobImageId);
        if(hasParameter(parameters, 'favorite')){
            boolean favorite = getBoolean(parameters, 'favorite');
            String usage = getString(parameters, 'usage');
            String favoriteClause;

            if(isCommunitySite(usage)) {
                img.IsUserFavorite__c = favorite;
                favoriteClause = 'IsUserFavorite__c = true';
            } else{
                img.IsFavorite__c = favorite;
                favoriteClause = 'IsFavorite__c = true';                
            }

            if(favorite){
                validateMarkFavorite(jobImageId, favoriteClause);
            }
        }

        if(hasParameter(parameters, 'qc')){
            img.PoorQualityCheck__c = getBoolean(parameters, 'qc');
        }

        Database.SaveResult result = Database.update(img);
        if(!result.isSuccess()){
            throw new AuraHandledException(AppUtil.genSaveResultError(result));
        }
        return this.getOneImageDetail(jobImageId);
    }

    boolean isCommunitySite(String usage){
        return usage == 'Retailer' || usage == 'Community Viewer';
    }

    @testvisible
    void validateMarkFavorite(String currentImageId, string favoriteClause){
        integer maxCount = AppUtil.MaxFavoritePhotoCount;
        JobImage__c img = getJobImage(currentImageId);

        if(img == null || string.isBlank(img.Project__c)){
            throw new AuraHandledException(img == null ? 'The photo record is not found.' : 'The photo record does not have project identifier.');
        }

        string projectId = img.Project__c;
        integer count = Database.countQuery('SELECT COUNT() FROM JobImage__c Where Project__c=:projectId AND ' + favoriteClause + ' AND Id != :currentImageId');
        if(count >= maxCount) {
            throw new AuraHandledException('The maximum number of favorite photos is reached.');
        }
    }

    JobImage__c getJobImage(String id){
        return [SELECT Id, Project__c FROM JobImage__c WHERE Id=:id LIMIT 1];
    }

    @testvisible
    void validateId(String jobImageId){
        if (String.isBlank(jobImageId))
        {
            throw new AuraHandledException('The Photo Id is required when retrieving the photo detail.');
        }
    }

    @testvisible
    List<String> parseJobImageIds(Object parameters){
        Map<String,Object> query = (Map<String,Object>)parameters;
        return LightningRequestHelper.parseArrayOfString(query.get('ids'));
    }


    @testvisible
    String getJobImageId(Object parameters){
        Map<String,object> query = (Map<String,Object>) parameters;
        return LightningRequestHelper.parseString(query.get('id'));
    }

    @testvisible
    boolean hasParameter(Object parameters, String parameterId){
        Map<String,Object> query = (Map<String,Object>) parameters;
        return query.get(parameterId) != null;
    }

    @testvisible
    boolean getBoolean(Object parameters,String parameterId){
        Map<String,Object> query = (Map<String,Object>) parameters;
        String flag = LightningRequestHelper.parseString(query.get(parameterId));
        return flag == '1' ? true : false;
    }

    String getString(Object parameters, String parameterId){
        Map<String,Object> query = (Map<String,Object>) parameters;
        return LightningRequestHelper.parseString(query.get(parameterId));
    }

    Map<String,Object> getOneImageDetail(String imageId){
        List<Map<String,Object>> result = this.getImageDetails(new List<String>{imageId});
        return result.size() > 0 ? result[0]: new Map<String,Object>();
    }

    @testvisible
    List<Map<String,Object>> getImageDetails(List<String> idSet){
        List<Map<String,Object>> resList = new List<Map<String,Object>>();
        Map<String,Object> res;
        String url;

        List<JobImage__c> images = [SELECT Id, Question__r.Name, Question__r.QuestionText__c, IsFavorite__c, PoorQualityCheck__c, ImageUrl__c, CloudinaryImageUrl__c, IsDuplicated__c, PhotoHash__c, JobAttempt__r.ReportedContactFirstName__c,JobAttempt__r.ReportedContactLastName__c, Project__r.Name, Project__r.ProjectNumber__c, ProjectService__r.ServiceTitle__c, ProjectLocation__r.LocationName__c, JobDateReported__c, ProjectLocation__r.City__c, ProjectLocation__r.State__c, ProjectLocation__r.LocationNumber__c, Target__r.Name, ParentLocation__r.Name, IsUserFavorite__c, Project__r.StartDate__c, Project__r.EndDate__c, IsErrored__c, ErrorMessage__c, JobAttempt__r.ECAttemptId__c FROM JobImage__c WHERE Id IN :idSet];
        
        RegExEngine regEx = RegExEngine.createInstance(RegExEngine.UrlPattern);
        for(JobImage__c ph: images){
            res = new Map<String,Object>();
            res.put('id', ph.Id);
            res.put('title', ph.Question__r.Name);
            res.put('question', ph.Question__r.QuestionText__c);
            if (regEx.matches(ph.ImageUrl__c)){
                res.put('url', ph.ImageUrl__c);
                res.put('url1', ph.CloudinaryImageUrl__c);
            } else {
                res.put('url','');
            }

            res.put('externalId', ph.JobAttempt__r.ECAttemptId__c);
            res.put('project', ph.Project__r.Name);
            res.put('projectNumber', ph.Project__r.ProjectNumber__c);
            res.put('service', ph.ProjectService__r.ServiceTitle__c);
            res.put('target', ph.Target__r.Name);
            res.put('location',ph.ProjectLocation__r.LocationName__c);
            res.put('locationNumber', ph.ProjectLocation__r.LocationNumber__c);
            res.put('banner', ph.ParentLocation__r.Name);
            res.put('city', ph.ProjectLocation__r.City__c);
            res.put('duplicated', ph.IsDuplicated__c ? 1:0);
            res.put('hash', ph.PhotoHash__c);
            res.put('state', ph.ProjectLocation__r.State__c);
            res.put('repName', genRepName(ph.JobAttempt__r.ReportedContactFirstName__c,ph.JobAttempt__r.ReportedContactLastName__c));
            res.put('favorite', ph.IsFavorite__c ? 1 : 0);
            res.put('userFavorite', ph.IsUserFavorite__c ? 1 : 0);
            res.put('qc', ph.PoorQualityCheck__c ? 1 : 0);
            res.put('photoDate', formatDatetime(ph.JobDateReported__c));
            res.put('startDate', formatDate(ph.Project__r.StartDate__c));
            res.put('endDate', formatDate(ph.Project__r.EndDate__c));
            res.put('error', ph.IsErrored__c ? 1 : 0);
            res.put('message',ph.ErrorMessage__c != null ? ph.ErrorMessage__c  : '');
            resList.add(res);
        }

        return resList;
    }

    String formatDate(Date dt){
        return (dt != null) ? dt.format(): '';
    }

    String formatDatetime(Datetime dttm){
        return (dttm != null) ? dttm.format('M/d/yyyy h:mm a', 'America/Chicago') : '';
    }

    @testvisible
    String genRepName(String firstName, string lastName){
        List<String> names = new List<String>();
        if(String.isNotEmpty(firstName)){
            names.add(firstName);
        }
        if(String.isNotEmpty(lastName)){
            names.add(lastName);
        }
        return String.join(names, ', ');
    }
}