src_old/objects/JobAttempt__c.object
<CustomObject>
    <description>Job Attempt is an attempt of a Job performed at a location. Job Attempt is related to an Exception.</description>
    <fields>
        <fullName>ProjectLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Location</label>
        <referenceTo>ProjectLocation__c</referenceTo>
        <relationshipLabel>Job Attempts</relationshipLabel>
        <relationshipName>Job_Attempts_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ReportedContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reported Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Job Attempts (Reported Contact)</relationshipLabel>
        <relationshipName>Job_Attempts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Job Attempt</label>
    <nameField>
        <displayFormat>JA-{000000000}</displayFormat>
        <label>Job Attempt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Attempts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/JobImage__c.object
<CustomObject>
    <fields>
        <fullName>ImageURL__c</fullName>
        <label>ImageURL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>IsDuplicated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>There is already another similar photo in the table.</description>
        <inlineHelpText>This photo is duplicated.</inlineHelpText>
        <label>Is Duplicated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsErrored__c</fullName>
        <defaultValue>false</defaultValue>
        <description>an error flag to indicate that the photo can not be hashed</description>
        <label>Is Errored</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsFavorite__c</fullName>
        <defaultValue>false</defaultValue>
        <description>IsFavorite</description>
        <label>IsFavorite</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsUserFavorite__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The external user favorite indicator</description>
        <inlineHelpText>The external user favorite indicator</inlineHelpText>
        <label>Is User Favorite</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>JobAttempt__c</fullName>
        <label>Job Attempt</label>
        <referenceTo>JobAttempt__c</referenceTo>
        <relationshipLabel>Job Images</relationshipLabel>
        <relationshipName>Job_Images</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>JobDateReported__c</fullName>
        <label>Job Date Reported</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ParentLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Parent Location</description>
        <label>ParentLocation</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>ParentLocation</relationshipLabel>
        <relationshipName>Job_Images</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PoorQualityCheck__c</fullName>
        <defaultValue>false</defaultValue>
        <description>PoorQualityCheck</description>
        <label>PoorQualityCheck</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProjectLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Location</label>
        <referenceTo>ProjectLocation__c</referenceTo>
        <relationshipLabel>Job Images</relationshipLabel>
        <relationshipName>Job_Images</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectService__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Service</label>
        <referenceTo>ProjectService__c</referenceTo>
        <relationshipLabel>Job Images</relationshipLabel>
        <relationshipName>Job_Images</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Job Images</relationshipLabel>
        <relationshipName>Job_Images</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Job Images</relationshipLabel>
        <relationshipName>Job_Images</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Target__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Target</label>
        <referenceTo>Target__c</referenceTo>
        <relationshipLabel>Job Images</relationshipLabel>
        <relationshipName>Job_Images</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ThumbnailURL__c</fullName>
        <formula>$Setup.SurveyPhotoViewerSetting__c.CloudinaryThumbnailURL__c  + ImageURL__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ThumbnailURL</label>
        <type>Text</type>
    </fields>
    <label>Job Image</label>
    <nameField>
        <displayFormat>JI-{000000000}</displayFormat>
        <label>Job Images Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Images</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/Location__c.object
<CustomObject>
    <description>Location defines a location and its type, address, and the Retailer is it associated with. Location is related to Retailer, Job, and Project Location.</description>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State/Province</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AS</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>FM</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>GU</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MH</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A search field that indicates the Program relating to the Project.</description>
        <inlineHelpText>Used to logically group projects for client reporting</inlineHelpText>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ProjectAccount__c.object
<CustomObject>
    <description>Project Account maps an Account to a Project and defines how the Account will be billed. Project Account is related to Project, Account, and Account Address.</description>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Project_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Account</label>
    <nameField>
        <displayFormat>PA-{0000000}</displayFormat>
        <label>Project Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectLocation__c.object
<CustomObject>
    <description>Project Location relates a Location to a Project. Project Location is related Project, Job, and Location.</description>
    <fields>
        <fullName>City__c</fullName>
        <formula>Location__r.City__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Project Locations</relationshipLabel>
        <relationshipName>ProjectLocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>ProjectLocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <formula>TEXT(Location__r.State__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>State/Province/Region</label>
        <type>Text</type>
    </fields>
    <label>Project Location</label>
    <nameField>
        <displayFormat>PL-{0000}</displayFormat>
        <label>Location ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectService__c.object
<CustomObject>
    <description>Project Service relates a Service to a Project and is a container used to define the instance of a Service for a specific Project. Project Service is related to Project, Job, Project Service Attribute, Project Service Certification, Project Service Equipment, Project Service Material, Project Service Question, Project Service Target, and Service.</description>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>ProjectServices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ServiceTitle__c</fullName>
        <inlineHelpText>Description of Service -- visible to rep and client</inlineHelpText>
        <label>Service Title</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Project Service</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/Target__c.object
<CustomObject>
    <description>Target defines what a Worker will observe and answer questions about. Targets could include Products, Categories, Displays, or any other type of Target configured for an instance. Target is related to Project Service Target and Retailer.</description>
    <fields>
        <fullName>ImageURL__c</fullName>
        <description>Photo of the target</description>
        <inlineHelpText>Photo of the target</inlineHelpText>
        <label>ImageURL</label>
        <type>Url</type>
    </fields>
    <label>Target</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Targets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/PhotoViewerFilterQueryGetter.cls
public with sharing class PhotoViewerFilterQueryGetter {
    private Map<String,String> filter;
    private List<String> predicates;
    public List<String> SQLStatements {get;set;}

    public string getProjectId(){
        return this.filter.get('projectId');
    }

    public string getFilterParameter(String key){
        return this.filter.get(key);
    }

    public void resetPredicates(){
        this.predicates = new List<String>();
    }

	private PhotoViewerFilterQueryGetter(Map<String,String> filter) {
        this.filter = filter;
        this.predicates = new List<String>();
        this.SQLStatements = new List<String>();
    }

    private void addSQL(String sql){
        this.SQLStatements.add(sql);
    }

    public static PhotoViewerFilterQueryGetter create(Map<String,String> filter){
        return new PhotoViewerFilterQueryGetter(filter);
    }

    public List<SObject> execute(boolean forCount, List<String>extraConditions, integer pageOffset){

        String projectId = this.getProjectId();
        String accountId = filter.get('userAccountId');
        String filterAccountId = filter.get('filterAccountId');
        String programId = filter.get('programId');
        String serviceId = filter.get('serviceId');
        String locationId = filter.get('locationId');
        String chainId = filter.get('chainId');
        String startDate = filter.get('startDate');
        String endDate = filter.get('endDate');
        String state = filter.get('state');
        String repId = filter.get('repId');
        String city = filter.get('city');
        String questionId = filter.get('questionId');
        String targetId = filter.get('targetId');
        String cityName = city;
        String favorite = filter.get('favorite');
        String userFavorite = filter.get('userFavorite');
        String duplicated = filter.get('duplicated');
        String unclassified = filter.get('unclassified');

        String baseSQL = (forCount)
            ? 'SELECT count(Id) cnt FROM JobImage__c'
            : 'SELECT Id, ThumbnailURL__c, ImageUrl__c, ProjectService__r.ServiceTitle__c, IsFavorite__c, PoorQualityCheck__c, IsDuplicated__c, IsUserFavorite__c,IsErrored__c FROM JobImage__c';

        if(this.predicates.size() == 0){
            if(String.isNotEmpty(projectId)){
                this.predicates.add('Project__c = :projectId');
            }

            if(favorite == '1'){
                this.predicates.add('IsFavorite__c = true');
            }
            
            if(userFavorite == '1'){
                this.predicates.add('IsUserFavorite__c = true');
            }

            if(duplicated == '1'){
                this.predicates.add('IsDuplicated__c = true');
            }

            if(String.isNotEmpty(serviceId)){
                this.predicates.add('ProjectService__c = :serviceId');
            }

            if(String.isNotEmpty(locationId)){
                this.predicates.add('ProjectLocation__r.Location__c = :locationId');
            }

            if(String.isNotEmpty(chainId)){
                this.predicates.add('ParentLocation__c =:chainId');
            }

            if(String.isNotEmpty(questionId)){
                this.predicates.add('Question__c = :questionId');
            }

            if(String.isNotEmpty(targetId)){
                this.predicates.add('Target__c = :targetId');
            }

            if(String.isNotEmpty(state)){
                this.predicates.add('ProjectLocation__r.State__c = :state');
            }

            if(String.isNotEmpty(cityName)){
                this.predicates.add('ProjectLocation__r.City__c LIKE \'' + cityName + '%\'');
            }

            if(String.isNotEmpty(repId)){
                this.predicates.add('JobAttempt__r.ReportedContact__c = :repId');
            }

            if(String.isNotBlank(startDate)){
                this.predicates.add('JobDateReported__c >= ' + startDate + 'T00:00:00.000Z');
            }

            if(String.isNotBlank(endDate)){
                this.predicates.add('JobDateReported__c <= ' + endDate + 'T23:59:59.999Z');
            }

            if(String.isNotEmpty(programId)){
                this.predicates.add('Project__r.Program__c = :programId');
            }

            if(isInternalUser() && String.isNotEmpty(filterAccountId)){
                this.predicates.add('Project__c IN (SELECT Project__c FROM ProjectAccount__c WHERE Account__c=:filterAccountId)');
            }
 			if(unclassified == '1'){
                this.predicates.add('AIMatchedStates__c = \'UnMatched\' ');
            } else {
                this.predicates.add('AIMatchedStates__c IN (\'Matched\',\'Not Enabled\') ');
            }
        }

        List<String> conditions = new List<String>();
        conditions.add('ImageUrl__c != null');
        conditions.addAll(this.predicates);

        if(extraConditions != null && extraConditions.size() > 0){
            conditions.addAll(extraConditions);
        }

        baseSQL += whereFromPredicates(conditions);
        if(!forCount){
            baseSQL += getOrderPageClause(pageOffset);
        }

        this.addSQL(baseSQL);
        return Database.query(baseSQL);
    }

    boolean isInternalUser(){
        return this.filter.get('usage') == 'Internal User';
    }

    boolean isCommunitySite() {
        String usage = this.filter.get('usage');
        return usage == 'Retailer' || usage == 'Community Viewer';
    }

    String parseCity(String city){
        List<Location__c> locations = [SELECT City__c FROM Location__c WHERE Id=:city LIMIT 1];
        return locations.size() > 0 ? locations[0].City__c : '';
    }


    String whereFromPredicates(List<String> wheres){

        return wheres.size() > 0
            ? ' WHERE ' + String.join(wheres, ' AND ')
            : '';
    }

    String getOrderPageClause(integer pageOffset) {
        string filter =  ' Order By SystemModstamp DESC LIMIT ' + String.valueOf(AppUtil.PhotoViewerPageSize + 1);
        if(pageOffset > 0){
            filter += ' OFFSET ' + String.valueOf(pageOffset);
        }
        return filter;
    }


}