src_old/objects/JobImage__c.object
<CustomObject>
    <fields>
        <fullName>ClassifiedLabel__c</fullName>
        <label>Classified Label</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsErrored__c</fullName>
        <defaultValue>false</defaultValue>
        <description>an error flag to indicate that the photo can not be hashed</description>
        <label>Is Errored</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Job Images</relationshipLabel>
        <relationshipName>Job_Images</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Job Image</label>
    <nameField>
        <displayFormat>JI-{000000000}</displayFormat>
        <label>Job Images Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Images</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/PhotoViewerCategorizerTest.cls
@isTest
private class PhotoViewerCategorizerTest {
    @testSetup
    static void setup() {
        TriggerUtil.SkipAllTriggers();
        TestDataUtil.init();
        TestProject tp = TestProject.create('demo').addAll();
        tp.TestProjectServiceList[0].addSurvey();
        tp.addJobImages();
    }

    @isTest
    static void itShouldAssignRightLabelToPhoto() {
        // Given
        Project__c p = TestProject.getProjects()[0];
        List<JobImage__c> images = TestProject.getJobImages(p.Id);
        IAIImageClassifier classifier = new AIImageClassifierFake();

        // When
        test.startTest();
        PhotoViewerCategorizer.create(classifier, images).run();
        test.stopTest();

        // Then
        images = TestProject.getJobImages(p.Id);
        QA.isTrue(images.size() > 0, 'has images');
        JobImage__c image = images[0];
        QA.EQ('ShelfDisplay', image.ClassifiedLabel__c, 'labeled as ' + image.ClassifiedLabel__c);
    }

    @isTest
    static void itShouldCaptureException() {
        // Given
        Project__c p = TestProject.getProjects()[0];
        List<JobImage__c> images = TestProject.getJobImages(p.Id);
        IAIImageClassifier classifier = new AIImageClassifierFakeForNotMatch();

        // When
        test.startTest();
        PhotoViewerCategorizer.create(classifier, images).run();
        test.stopTest();

        // Then
        images = TestProject.getJobImages(p.Id);
        QA.isTrue(images.size() > 0, 'has images');
        JobImage__c image = images[0];
        QA.EQ(true, image.IsErrored__c, 'error flagged');
    }

}