src_old/objects/JobImage__c.object
<CustomObject>
    <fields>
        <fullName>AIImageURL__c</fullName>
        <formula>$Setup.SurveyPhotoViewerSetting__c.AIImageURL__c + ImageURL__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AIImageURL</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ClassifiedLabel__c</fullName>
        <label>Classified Label</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ClassifiedResponse__c</fullName>
        <label>Classified Response</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ErrorMessage__c</fullName>
        <label>Error Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsErrored__c</fullName>
        <defaultValue>false</defaultValue>
        <description>an error flag to indicate that the photo can not be hashed</description>
        <label>Is Errored</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isClassified__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Classified</label>
        <type>Checkbox</type>
    </fields>
    <label>Job Image</label>
    <nameField>
        <displayFormat>JI-{000000000}</displayFormat>
        <label>Job Images Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Images</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/PhotoViewerCategorizer.cls
global with sharing class PhotoViewerCategorizer {
    List<JobImage__c> dataset;
    IAIImageClassifier classifier;

    private PhotoViewerCategorizer(IAIImageClassifier classifier, List<JobImage__c> scope) {
        this.dataset = new List<JobImage__c>(scope);
        this.classifier = (scope.size() > 0) ? classifier : null;
    }

    global static PhotoViewerCategorizer create(IAIImageClassifier classifier, List<JobImage__c> scope) {
        return new PhotoViewerCategorizer(classifier, scope);
    }

    global void run() {
        if (this.classifier == null) {
            return;
        }
        List<JobImage__c> images = new List<JobImage__c>();
        for (JobImage__c img : this.dataset) {
            try {
                Map<String, Double> result = this.classifier.predict(img.AIImageUrl__c);

                images.add(new JobImage__c(
                    id = img.Id,
                    isClassified__c = true,
                    classifiedLabel__c = this.findLikelyLabel(result),
                    ClassifiedResponse__c = JSON.serialize(result)
                ));
            } catch (Exception ex) {

                images.add(new JobImage__c(
                    id = img.Id,
                    IsErrored__c = true,
                    ErrorMessage__c = ex.getMessage()
                    ));
            }
        }
        if (images.size() > 0) {
            update images;
        }
    }


    private String findLikelyLabel(Map<String, Double> result) {
        Double max = 0.0;
        String maxLabel = '';
        for(String label: result.keySet()){
            Double val = Double.valueOf(result.get(label));
            if (val > max) {
                max = val;
                maxLabel = label; 
            }
        }
        return maxLabel;
    }
}