src_old/objects/JobImage__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Job Images</relationshipLabel>
        <relationshipName>Job_Images</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Job Image</label>
    <nameField>
        <displayFormat>JI-{000000000}</displayFormat>
        <label>Job Images Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Images</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/PhotoRequestTest.cls
@isTest
private class PhotoRequestTest
{
    @testSetup
    static void setup(){
        TriggerUtil.SkipAllTriggers();
        TestDataUtil.init();
        TestProject tp = TestProject.create('demo').addAll();
        tp.TestProjectServiceList[0].addAll();
        tp.addJobImages();
    }

    @isTest
    static void itShouldGetPhoto()
    {
        //GIVEN
        Project__c p = TestProject.getProjects()[0];
        JobImage__c img = TestProject.getJobImages(p.Id)[0];

        Map<String,Object> query = new Map<String,Object>();
        query.put('id', img.Id);
        LightningRequestBase req = new PhotoRequest();

        //WHEN
        test.startTest();
        Map<String,Object> result = (Map<String,Object>) req.get(query);
        test.stopTest();

        //THEN
        QA.EQ(img.Id, result.get('id'), 'same id');
    }

    @isTest
    static void itShouldUpdatePhoto() {
        //GIVEN
         Project__c p = TestProject.getProjects()[0];
        JobImage__c img = TestProject.getJobImages(p.Id)[0];

        Map<String,Object> query = new Map<String,Object>();
        query.put('id', img.Id);
        query.put('favorite', 1);
        query.put('qc',1);
        LightningRequestBase req = new PhotoRequest();

        //WHEN
        test.startTest();
        Map<String,Object> result = (Map<String,Object>) req.modify(query);
        test.stopTest();

        //THEN
        QA.EQ(1, result.get('qc'), 'qc is checked');
    }
}