src_old/objects/JobImage__c.object
<CustomObject>
    <fields>
        <fullName>PhotoHash__c</fullName>
        <description>PhotoHash</description>
        <label>PhotoHash</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Processed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Job Images</relationshipLabel>
        <relationshipName>Job_Images</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Job Image</label>
    <nameField>
        <displayFormat>JI-{000000000}</displayFormat>
        <label>Job Images Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Images</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/PhotoViewerHashDuplicationHandler.cls
global class PhotoViewerHashDuplicationHandler implements Database.Batchable<SObject> {

	global Database.QueryLocator start(Database.BatchableContext bc){
        return Database.getQueryLocator([SELECT Id, PhotoHash__c, Project__c FROM JobImage__c WHERE Processed__c = false AND PhotoHash__c != null]);
    }

    global void execute(Database.BatchableContext bc, List<SObject> scope){
        PhotoViewerHashDetection.create(scope).run();
    }


    global void finish(Database.BatchableContext bc){}
}