src_old/objects/JobManualVariant__c.object
<CustomObject>
    <description>Job Manual Variant stores the various language variants for the Job Manual templates.</description>
    <fields>
        <fullName>EngLabel__c</fullName>
        <label>English Label</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FraLabel__c</fullName>
        <label>French Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Job Manual Variant</label>
    <nameField>
        <label>Label Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Manual Variants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Language__c/Language__c.object-meta.xml
<CustomObject>
    <description>Defines a list of languages.</description>
    <label>Language</label>
    <nameField>
        <label>Language Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Languages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/objects/Variant__c.object
<CustomObject>
    <description>Variant stores variants such as language that is used throughout the system. Variant is related to Question Defined Response Variant, Question Variant, Job Manual Variant, and Language.</description>
    <fields>
        <fullName>Language__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Language</label>
        <referenceTo>Language__c</referenceTo>
        <relationshipLabel>Variants</relationshipLabel>
        <relationshipName>Variants</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Variant</label>
    <nameField>
        <displayFormat>VAR-{000000000}</displayFormat>
        <label>Variant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Variants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/LocaleManager.cls
public class LocaleManager {
    private Map<String,String> dictionary;
    
    public static String ENGLISH_CODE = 'ENG';
    public static String FRENCH_CODE = 'FRA';

    public String VariantId {get; private set;}
    public String LanguageCode {get; private set;}
    public Map<String,String> Labels {
        get {
            return dictionary;
        }
    }
    public Boolean IsEnglish {get {
        return this.LanguageCode == LocaleManager.ENGLISH_CODE ? true : false;  
        }}

    public static LocaleManager newInstance() {
        return new LocaleManager();
    }

    public static LocaleManager newInstance(String languageCode) {
        return new LocaleManager(languageCode);
    }

    private LocaleManager() {
        this.LanguageCode = LocaleManager.ENGLISH_CODE;
        this.Init();
    }

    private LocaleManager(String languageCode) {
        this.LanguageCode = String.isNotBlank(languageCode) ? languageCode.toUpperCase() : LocaleManager.ENGLISH_CODE;
        this.init();    
    }

    private void Init() {
        dictionary = new Map<String,String>();
        if (this.LanguageCode == LocaleManager.FRENCH_CODE) {
            InitLanguageId('French');
            initEventManualVariant([SELECT Name, FraLabel__c FROM JobManualVariant__c],'FraLabel__c');
        } else {
            this.VariantId = '';
            initEventManualVariant([SELECT Name, EngLabel__c FROM JobManualVariant__c],'EngLabel__c');
        }
    }

    private void InitLanguageId(String name) {
        List<Variant__c> langs = [SELECT Id FROM Variant__c WHERE Language__r.Name=:name LIMIT 1];
        this.VariantId = langs.size() > 0 ? String.valueOf(langs[0].Id): '';
    }

    private void initEventManualVariant(List<JobManualVariant__c> items, String label) {
        String key;
        String value;

        for(JobManualVariant__c e: items) {
            key = String.valueOf(e.Name);
            value = String.valueOf(e.get(label));

            if (dictionary.containsKey(key)) { dictionary.remove(key);}
            dictionary.put(key, value);
        }
    }
}