src_old/objects/Location__c.object
<CustomObject>
    <description>Location defines a location and its type, address, and the Retailer is it associated with. Location is related to Retailer, Job, and Project Location.</description>
    <fields>
        <fullName>Retailer__c</fullName>
        <label>Retailer</label>
        <referenceTo>Retailer__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <fields>
        <fullName>Retailer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Retailer</label>
        <referenceTo>Retailer__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planning</fullName>
                    <default>true</default>
                    <label>Planning</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Launched</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ended</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <recordTypes>
        <fullName>Booked</fullName>
        <active>true</active>
        <label>Booked</label>
    </recordTypes>
    <recordTypes>
        <fullName>Planning</fullName>
        <active>true</active>
        <label>Planning</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ProjectLocation__c.object
<CustomObject>
    <description>Project Location relates a Location to a Project. Project Location is related Project, Job, and Location.</description>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Project Locations</relationshipLabel>
        <relationshipName>ProjectLocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>ProjectLocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Retailer__c</fullName>
        <formula>Project__r.Retailer__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Retailer</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Job Created</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project Location</label>
    <nameField>
        <displayFormat>PL-{0000}</displayFormat>
        <label>Location ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/Retailer__c.object
<CustomObject>
    <description>Retailer stores the retailers for the system. Retailer is related to Location, Retailer Service, Retailer Service Certification, and Retailer Service Equipment.</description>
    <label>Retailer</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Retailers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/ProjectTriggerHandlerTest.cls
@isTesT
public class ProjectTriggerHandlerTest {
       
    @testSetup static void setup(){
        TestUtil.initBaseData();
    } 
    static testMethod void test_beforeInsert() {

        Test.startTest();
        Project__c[] projects = TestUtil.generateProjects(2);
        Test.stopTest();

        for (Project__c project : [SELECT Status__c FROM Project__c WHERE Id = :projects]) {
            System.assertEquals('Planning', project.Status__c);
        }

        
    }
    
    static testMethod void test_beforeUpdate() {

        Project__c[] projects = TestUtil.generateProjects(2);

        Map<Id, Boolean> projectIdToHasReserved = AppUtil.getProjectIdToHasReserved(projects);
        Map<Id, Location__c> retailerIdToLocation = new Map<Id, Location__c>();
        for (Project__c project : [SELECT Retailer__c FROM Project__c WHERE Id IN :projects]) {

            //System.assertEquals(false, project.IsEventManualRegenReqd__c);
            System.assertEquals(false, projectIdToHasReserved.get(project.Id));
           

            if (!retailerIdToLocation.containsKey(project.Retailer__c)) retailerIdToLocation.put(project.Retailer__c, TestUtil.buildLocation(project.Retailer__c));
        }
        insert retailerIdToLocation.values();

        ProjectLocation__c[] testProjectLocations = new ProjectLocation__c[]{};
        for (Project__c project : projects) {
            testProjectLocations.add(new ProjectLocation__c(
                Project__c = project.Id
                , Location__c = retailerIdToLocation.get(project.Retailer__c).Id
                , Status__c = 'Booked'
            ));
        }
        insert testProjectLocations;

        Test.startTest();

        TriggerUtil.SkipProjectTrigger = false;

        for (Project__c project : projects) {
            project.Name = 'Test Updated Name ' + project.Id;
            project.Status__c = 'Booked';
        }
        update projects;

        projectIdToHasReserved = AppUtil.getProjectIdToHasReserved(projects);
        for (Project__c project : [SELECT Id FROM Project__c WHERE Id IN :projects]) {
            //System.assertEquals(true, project.IsEventManualRegenReqd__c);
            //System.assertEquals(true, projectIdToHasReserved.get(project.Id));
            /*System.assertEquals(true, project.RereserveFlag__c);*/
        }

        Test.stopTest();
    }

    /* TODO: Complete this test */
    /*static testMethod void test_beforeUpdateWithApprovalRequest() {

        Project__c[] projects = TestUtil.generateProjects(2);

        System.assertEquals(0, [SELECT count() FROM Project__c WHERE Id IN :projects AND Status__c = 'Pending Approval']);

        Test.startTest();

        TriggerUtil.SkipProjectTrigger = false;

        for (Project__c project : projects) {
            project.Status__c = 'Pending Approval';
        }
        update projects;

        Set<Id> projectIdsWithWorkItem = new Set<Id>();
        for (ProcessInstanceWorkItem workItem : [SELECT ProcessInstance.TargetObjectId FROM ProcessInstanceWorkItem WHERE ProcessInstance.TargetObjectId IN :projects]) projectIdsWithWorkItem.add(workItem.ProcessInstance.TargetObjectId);

        for (Project__c project : projects) {
            System.assertEquals(true, projectIdsWithWorkItem.contains(project.Id));
        }

        Test.stopTest();
    }*/
    }