src_old/objects/Location__c.object
<CustomObject>
    <description>Location defines a location and its type, address, and the Retailer is it associated with. Location is related to Retailer, Job, and Project Location.</description>
    <fields>
        <fullName>LocationNumber__c</fullName>
        <label>Location Number</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State/Province</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AS</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>FM</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>GU</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MH</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planning</fullName>
                    <default>true</default>
                    <label>Planning</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Launched</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ended</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ProjectAccount__c.object
<CustomObject>
    <description>Project Account maps an Account to a Project and defines how the Account will be billed. Project Account is related to Project, Account, and Account Address.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please make sure this account&apos;s &apos;Can Request Project&apos; setting is enabled.</errorMessage>
            <filterItems>
                <field>Account.CanRequestProjects__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Project Accounts</relationshipLabel>
        <relationshipName>Project_Accounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Project_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Account</label>
    <nameField>
        <displayFormat>PA-{0000000}</displayFormat>
        <label>Project Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectInvoice__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Project Invoices</relationshipLabel>
        <relationshipName>Project_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LawsonCompanyCode__c</fullName>
        <label>Lawson Company Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1000</fullName>
                </value>
                <value>
                    <fullName>2025</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ProjectAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Account</label>
        <referenceTo>ProjectAccount__c</referenceTo>
        <relationshipLabel>Project Invoices</relationshipLabel>
        <relationshipName>Project_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Invoices</relationshipLabel>
        <relationshipName>Project_Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Invoiced</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Grouped</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project Invoice</label>
    <nameField>
        <displayFormat>INV-{000000000}</displayFormat>
        <label>Project Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectInvoiceLineItem__c.object
<CustomObject>
    <fields>
        <fullName>ProjectInvoice__c</fullName>
        <label>Project Invoice</label>
        <referenceTo>ProjectInvoice__c</referenceTo>
        <relationshipLabel>Project Invoice Line Items</relationshipLabel>
        <relationshipName>Project_Invoice_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project Invoice Line Item</label>
    <nameField>
        <displayFormat>INVLI-{000000000}</displayFormat>
        <label>Project Invoice Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectInvoiceLineItemDetail__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Project Invoice Line Items Detail</relationshipLabel>
        <relationshipName>Project_Invoice_Line_Items_Detail</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LocationNumber__c</fullName>
        <description>This field can be populated when there is no project location info available.</description>
        <label>Location Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProjectId__c</fullName>
        <formula>CASESAFEID(ProjectInvoiceLineItem__r.ProjectInvoice__r.Project__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ProjectId</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProjectInvoiceLineItem__c</fullName>
        <label>Project Invoice Line Item</label>
        <referenceTo>ProjectInvoiceLineItem__c</referenceTo>
        <relationshipLabel>Project Invoice Line Items Detail</relationshipLabel>
        <relationshipName>Project_Invoice_Line_Items_Detail</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ProjectLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Location</label>
        <referenceTo>ProjectLocation__c</referenceTo>
        <relationshipLabel>Project Invoice Line Items Detail</relationshipLabel>
        <relationshipName>Project_Invoice_Line_Items_Detail</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Invoice Line Item Detail</label>
    <nameField>
        <displayFormat>PILID-{000000000}</displayFormat>
        <label>Project Invoice Line Item Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Invoice Line Items Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectLocation__c.object
<CustomObject>
    <description>Project Location relates a Location to a Project. Project Location is related Project, Job, and Location.</description>
    <fields>
        <fullName>LocationNumber__c</fullName>
        <formula>Location__r.LocationNumber__c</formula>
        <label>Location #</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Project Locations</relationshipLabel>
        <relationshipName>ProjectLocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>ProjectLocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <formula>TEXT(Location__r.State__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>State/Province/Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Job Created</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project Location</label>
    <nameField>
        <displayFormat>PL-{0000}</displayFormat>
        <label>Location ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/classes/PILineItemDetailTriggerHandler.cls
public class PILineItemDetailTriggerHandler extends TriggerHandler{
    
    public override void beforeUpdate() {      
        
        Map<id,ProjectInvoiceLineItemDetail__c> pilidAccountChangedList = new Map<id,ProjectInvoiceLineItemDetail__c>();
        
        if (TriggerUtil.skipProjectInvoiceLineItemDetailTrigger) return;        
        
        for (ProjectInvoiceLineItemDetail__c pilid: (List<ProjectInvoiceLineItemDetail__c> ) Trigger.new) {
            
            sObject obj = Trigger.oldMap.get(pilid.Id);
            
            if (obj == null){ continue; }
            
            ProjectInvoiceLineItemDetail__c oldPilid = (ProjectInvoiceLineItemDetail__c)obj;
            
            if (pilid.Account__c != oldPilid.Account__c) 
            {
                pilidAccountChangedList.put(pilid.Id,pilid);                
            }
        }       
        
        saveAccountChange(pilidAccountChangedList);
    }
    
    public void saveAccountChange(Map<id,ProjectInvoiceLineItemDetail__c> pilidAccountChangedList){
        
        set<id> projectIds = new set<id>();
        set<String> locationNumbers = new set<String>();
        List<ProjectInvoiceLineItem__c> newpilis = new List<ProjectInvoiceLineItem__c>();
        set<id> projectInvoiceLineItemDetailIds = new Set<id>();
        Map<string, ProjectAccount__c> projectAccountMap = new Map<string, ProjectAccount__c>();
        map<String,ProjectInvoice__c> piMap = new map<String,ProjectInvoice__c>();		
        List<ProjectInvoice__c> newPiList= new List<ProjectInvoice__c>();
        map<string,ProjectInvoiceLineItem__c> projectInvoiceToLineItemMap = new map<string,ProjectInvoiceLineItem__c>();
        Map<String, ProjectInvoiceLineItem__c> piliMap =new Map<String, ProjectInvoiceLineItem__c>(); 
        
        List<Location__c> locationList = new List<Location__c>();
        Map<String,Location__c> locationMap = new Map<String,Location__c>();
                
        for (ProjectInvoiceLineItemDetail__c pilid: pilidAccountChangedList.values()) {            
            projectIds.add(pilid.ProjectId__c);
            
            // In case if there is no project location attached
            if (pilid.ProjectLocation__c == null && pilid.LocationNumber__c != null){
                locationNumbers.add(pilid.LocationNumber__c);
            }
        }
        
        if (locationNumbers.size() > 0)
        {
            locationList = [select Id,LocationNumber__c, State__c from Location__c where LocationNumber__c in :locationNumbers];    
            if (locationList != null && locationList.size() > 0)
            {
                for(Location__c loc :locationList){
                    locationMap.put(loc.LocationNumber__c, loc);
                }
            }            
        }
        

        List<ProjectAccount__c> paList = [Select Id, Project__c, Account__c 
                                          From ProjectAccount__c 
                                          where Project__c in: projectIds];
        
        for(ProjectAccount__c pa : paList){
            projectAccountMap.put(string.valueOf(pa.Project__c) + string.valueOf(pa.Account__c), pa);
        }        
        
        List<ProjectInvoice__c> piList = [Select Id, Account__c, Project__c, ProjectAccount__c, LawsonCompanyCode__c  
                                          From ProjectInvoice__c 
                                          Where Project__c in :projectIds
                                          AND Status__c = :CONSTANTS.PROJECT_INVOICE_STATUS_CREATED 
                                          AND Type__c = :CONSTANTS.PROJECT_INVOICE_TYPE_POSTEXECUTION];       
        
        for(ProjectInvoice__c pi : piList){
            piMap.put(string.valueOf(pi.Project__c) + string.valueOf(pi.Account__c) + string.valueOf(pi.LawsonCompanyCode__c), pi);
        }
        
        for (ProjectInvoiceLineItemDetail__c pilid: pilidAccountChangedList.values()) {
            
            ProjectAccount__c pa;           
            
            //If no project account is found for the account selected then raise error
            if (pilid.Account__c != null){                         
                pa = projectAccountMap.get(pilid.ProjectId__c + string.valueOf(pilid.Account__c));
                if (pa == null) { 
                    
                    system.debug('error with pilid.Account__c:' + pilid.Account__c);
                    pilid.addError('selected account is not mapped to this project');
                    continue;
                }
            }
            
            string lawsonCompanyCode = (pilid.ProjectLocationState__c == CONSTANTS.STATE_CODE_PR ? CONSTANTS.LAWSON_COMPANY_CODE_PR : CONSTANTS.LAWSON_COMPANY_CODE_US);
            if (pilid.ProjectLocation__c == null){
                Location__c loc = locationMap.get(pilid.LocationNumber__c);
                if (loc != null){
                    lawsonCompanyCode = (loc.State__c == CONSTANTS.STATE_CODE_PR ? CONSTANTS.LAWSON_COMPANY_CODE_PR : CONSTANTS.LAWSON_COMPANY_CODE_US);
                }
                
            }
            
            // To create project invoice if project invoice does not exist for the account \ un reconciled
            if (!(piMap.containsKey(pilid.ProjectId__c + string.valueOf(pilid.Account__c) + lawsonCompanyCode))){
                
                ProjectInvoice__c pi = new ProjectInvoice__c();
                pi.Project__c = pilid.ProjectId__c;
                pi.Status__c = CONSTANTS.PROJECT_INVOICE_STATUS_CREATED;
                pi.Type__c = CONSTANTS.PROJECT_INVOICE_TYPE_POSTEXECUTION;
                pi.LawsonCompanyCode__c = lawsonCompanyCode;
                if (pilid.Account__c != null) { pi.Account__c = pilid.Account__c; }
                
                if (pa != null) { pi.ProjectAccount__c = pa.Id; }
                
                newPiList.add(pi);
                
                // Add the newly created project invoice to the map
                piMap.put(string.valueOf(pi.Project__c) + string.valueOf(pi.Account__c) + string.valueOf(pi.LawsonCompanyCode__c), pi);
                
            }            
        }
        
        insert newPiList;
        
        //To get the id of the new project invoice 
        newPiList = [Select Id, Account__c, Project__c, ProjectAccount__c 
                     From ProjectInvoice__c 
                     Where Id in :newPiList];                  
        
        //Adding to existing list of project invoice
        piList.addall(newPiList);
        
        //To get all project invoice line item for the projects where account has been changed in line item details
        List<ProjectInvoiceLineItem__c> piliList = [SELECT 
                                                    Id, 
                                                    ProjectInvoice__c,
                                                    ProjectInvoice__r.Project__c,                                                    
                                                    ProjectInvoice__r.Account__c,
                                                    ProjectInvoice__r.LawsonCompanyCode__c,
                                                    ServiceType__c
                                                    FROM ProjectInvoiceLineItem__c 
                                                    WHERE ProjectInvoice__r.Project__c in :projectIds
                                                    AND ProjectInvoice__r.Status__c = :CONSTANTS.PROJECT_INVOICE_STATUS_CREATED 
                                                    AND ProjectInvoice__r.Type__c = :CONSTANTS.PROJECT_INVOICE_TYPE_POSTEXECUTION
                                                    And ServiceType__c =: CONSTANTS.PROJECT_INVOICE_LINEITEM_SERVICETYPE_PRODUCT];               
        
        for(ProjectInvoiceLineItem__c pili : piliList)
        {
            projectInvoiceToLineItemMap.put(pili.ProjectInvoice__c,pili);
        }
        
        //Check if all project invoice has corresponding project invoice line item if not create one
        for(ProjectInvoice__c pi : piList){
            if (!(projectInvoiceToLineItemMap.containsKey(pi.id))){
                ProjectInvoiceLineItem__c pili = new ProjectInvoiceLineItem__c();
                pili.ProjectInvoice__c = pi.Id;
                pili.Type__c = Constants.PROJECT_INVOICE_LINEITEM_TYPE_USAGE;
                pili.ServiceType__c = Constants.PROJECT_INVOICE_LINEITEM_SERVICETYPE_PRODUCT;    
                pili.Amount__c = 0;
                newpilis.add(pili);  
            }
        }
        
        insert newpilis;
        
        List<ProjectInvoiceLineItem__c> newPiliList = [Select 
                                                       Id, 
                                                       ProjectInvoice__c,
                                                       ProjectInvoice__r.Project__c,                    
                                                       ProjectInvoice__r.Account__c,
                                                       ProjectInvoice__r.LawsonCompanyCode__c,
                                                       ServiceType__c
                                                       From ProjectInvoiceLineItem__c 
                                                       where Id in : newpilis];               
        
        piliList.addall(newPiliList);        
        
        
        // create a map project invoice line item
        for(ProjectInvoiceLineItem__c pili : piliList){
            piliMap.put(string.valueOf(pili.ProjectInvoice__r.Project__c) + string.valueOf(pili.ProjectInvoice__r.Account__c) + string.valueOf(pili.ProjectInvoice__r.LawsonCompanyCode__c), pili);
        }
        
        // To assign ProjectInvoiceLineItemDetail to approriate ProjectInvoiceLineItem
        for (ProjectInvoiceLineItemDetail__c pilid: pilidAccountChangedList.values()) {
            
            string lawsonCompanyCode = (pilid.ProjectLocationState__c == CONSTANTS.STATE_CODE_PR ? CONSTANTS.LAWSON_COMPANY_CODE_PR : CONSTANTS.LAWSON_COMPANY_CODE_US);
            
            if (pilid.ProjectLocation__c == null){
               	Location__c loc = locationMap.get(pilid.LocationNumber__c);				
                if (loc != null){
                    lawsonCompanyCode = (loc.State__c == CONSTANTS.STATE_CODE_PR ? CONSTANTS.LAWSON_COMPANY_CODE_PR : CONSTANTS.LAWSON_COMPANY_CODE_US);
                }
            }
            
            ProjectInvoiceLineItem__c piliObj = piliMap.get(string.valueOf(pilid.ProjectId__c) + string.valueOf(pilid.Account__c) + lawsonCompanyCode);
            
            if (piliObj != null){
                pilid.ProjectInvoiceLineItem__c = piliObj.Id;
            }
        }        
    }    
}