src_old/objects/Location__c.object
<CustomObject>
    <description>Location defines a location and its type, address, and the Retailer is it associated with. Location is related to Retailer, Job, and Project Location.</description>
    <label>Location</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/LocationAssignment__c.object
<CustomObject>
    <description>Location Assignment specifies the Execution Company for a Project Type at a specific Location. The Location Assignment is required to assign Jobs to an Execution Company for a Location. Location Assignment is related to Location, Account, and Project Type.</description>
    <fields>
        <fullName>AccountableExecutionCompany__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Accountable Execution Company</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>ExecutionCompany</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Location Assignments</relationshipLabel>
        <relationshipName>Location_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Location Assignments</relationshipLabel>
        <relationshipName>LocationAssignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ProjectType__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project Type</label>
        <referenceTo>ProjectType__c</referenceTo>
        <relationshipLabel>Location Assignments</relationshipLabel>
        <relationshipName>LocationAssignments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Location Assignment</label>
    <nameField>
        <displayFormat>LA-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Location Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <fields>
        <fullName>ProjectType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Type</label>
        <referenceTo>ProjectType__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ResponsibleForExecution__c</fullName>
        <label>Responsible For Execution</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Execution Company</fullName>
                    <default>true</default>
                    <label>Execution Company</label>
                </value>
                <value>
                    <fullName>Retailer</fullName>
                </value>
                <value>
                    <fullName>Supplier</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planning</fullName>
                    <default>true</default>
                    <label>Planning</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Launched</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ended</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <recordTypes>
        <fullName>Canceled</fullName>
        <active>true</active>
        <label>Canceled</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ProjectLocation__c.object
<CustomObject>
    <description>Project Location relates a Location to a Project. Project Location is related Project, Job, and Location.</description>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Project Locations</relationshipLabel>
        <relationshipName>ProjectLocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectType__c</fullName>
        <formula>Project__r.ProjectType__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>ProjectLocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Job Created</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project Location</label>
    <nameField>
        <displayFormat>PL-{0000}</displayFormat>
        <label>Location ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectService__c.object
<CustomObject>
    <description>Project Service relates a Service to a Project and is a container used to define the instance of a Service for a specific Project. Project Service is related to Project, Job, Project Service Attribute, Project Service Certification, Project Service Equipment, Project Service Material, Project Service Question, Project Service Target, and Service.</description>
    <fields>
        <fullName>NumberOfWorkers__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Enter the number of workers need to finish the job</description>
        <inlineHelpText>Number of reps allocated to complete project execution at a location</inlineHelpText>
        <label>Number of Workers</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProjectType__c</fullName>
        <formula>Project__r.ProjectType__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>ProjectServices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ResponsibleForExecution__c</fullName>
        <label>Responsible For Execution</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Execution Company</fullName>
                    <default>true</default>
                    <label>Execution Company</label>
                </value>
                <value>
                    <fullName>Retailer</fullName>
                </value>
                <value>
                    <fullName>Supplier</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>Project Services</relationshipLabel>
        <relationshipName>ProjectServices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Executed</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project Service</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Services</pluralLabel>
    <recordTypes>
        <fullName>Canceled</fullName>
        <active>true</active>
        <label>Canceled</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectType__c.object
<CustomObject>
    <description>Project Type defines a collection of Services and sets configuration options for a Project. Project Type is related to Project, Project Type Execution Company, Project Type Service, and Location Assignment.</description>
    <label>Project Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Types</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/Service__c.object
<CustomObject>
    <description>Service contains the definition of a service. Service is related to Service Attribute, Service Exception, Service Question, Service Question Defined Response, Retailer Service, Retailer Service Equipment, and Project Service.</description>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/classes/SchedulingStrategy.cls
global abstract class SchedulingStrategy {
    
    global virtual List<ProjectLocation__c> getProjectLocations(ID projectID){
         return [SELECT Id, Status__c FROM ProjectLocation__c WHERE Project__c = :projectID];
    }
    
    global virtual List<ProjectService__c> getProjectServices(ID projectID){
         return [Select Id, Service__c,  Service__r.Name, Project__c,  ResponsibleForExecution__c, NumberOfWorkers__c From ProjectService__c WHERE Project__c = :projectID AND Status__c != 'Canceled'];
    }

    
    //returns null if ResponsibleForExecution is not 'Execution Company', returns an set instance otherwsie
    global virtual Set<String> getLocationAssignments(Project__c project, Set<Id> scopeLocationIds){
        Integer  ecCount = [SELECT COUNT() FROM ProjectService__c where Project__c =: project.ID AND ResponsibleForExecution__c = 'Execution Company'];
        Set<String> locAssignmentSet =  null;
        if(ecCount > 0){
            locAssignmentSet = new Set<String>();
            List<LocationAssignment__c> laList = [SELECT Location__c FROM LocationAssignment__c WHERE ProjectType__c =: project.ProjectType__c AND AccountableExecutionCompany__c != NULL AND Location__c IN :scopeLocationIds];
            for(LocationAssignment__c la : laList){
                locAssignmentSet.add(la.Location__c);
            }
        }
        return locAssignmentSet;
    }
    
    global abstract Integer ScheduleLocations(List<ProjectLocation__c> scope, String projectID);
    
    //only virtual global methods (with implementations) can be added to previously managed virtual or abstract classes
    global virtual Integer ScheduleLocations(List<ProjectLocation__c> scope, String projectID, String operation){
        return 0;
    }
    
    //obsolte -- keep the signature for managed package
    global abstract String getSchedulableLocationsQuery(Project__c project);
    
    //only virtual global methods (with implementations) can be added to previously managed virtual or abstract classes
    global virtual String getSchedulableLocationsQuery(Project__c project, String operation){
        return '';
    }
    
    global abstract Boolean deallocateLocations(List<ProjectLocation__c> scope);
    
    global abstract Boolean isBatchJob(Project__c p, String exceedBudgeted);
    
    
}