src_old/objects/Location__c.object
<CustomObject>
    <description>Location defines a location and its type, address, and the Retailer is it associated with. Location is related to Retailer, Job, and Project Location.</description>
    <label>Location</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/Target__c.object
<CustomObject>
    <description>Target defines what a Worker will observe and answer questions about. Targets could include Products, Categories, Displays, or any other type of Target configured for an instance. Target is related to Project Service Target and Retailer.</description>
    <fields>
        <fullName>AccountInfo__c</fullName>
        <label>Account</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>BrandInfo__c</fullName>
        <label>Brand</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>CategoryInfo__c</fullName>
        <label>Category</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>DepartmentName__c</fullName>
        <label>Department Name</label>
        <length>140</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>PackageSizeQty__c</fullName>
        <label>Yield Per Unit</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PackageSizeUnits__c</fullName>
        <label>Package Size (Units)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>count</fullName>
                </value>
                <value>
                    <fullName>lb</fullName>
                </value>
                <value>
                    <fullName>oz</fullName>
                </value>
                <value>
                    <fullName>pint</fullName>
                </value>
                <value>
                    <fullName>gallon</fullName>
                </value>
                <value>
                    <fullName>quart</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>StockCode__c</fullName>
        <externalId>true</externalId>
        <label>Stock ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>TargetType__c</fullName>
        <label>Target Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Product</fullName>
                </value>
                <value>
                    <fullName>Category</fullName>
                </value>
                <value>
                    <fullName>Sam&apos;s Club</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UPC__c</fullName>
        <label>UPC</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Target</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Targets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/classes/TargetAddViewExt.cls
public with sharing class TargetAddViewExt {
    public Blob csvFileBody{get;set;}
    public string csvAsString{get;set;}
    public String[] csvFileLines{get;set;}
    public string[] csvRecordData{get;set;}    
    public List<Target__c> CollList{get;set;}
    public List<Target__c> failedColl{get;set;}
    public Target__c TargetObj{get;set;}    
    public boolean isGridVisible{get;set;}
    public string docID{get;set;}
    
    public TargetAddViewExt(ApexPages.StandardController controller) {
        csvFileLines = new String[]{};
        CollList = New List<Target__c>(); 
        failedColl = New List<Target__c>(); 
        isGridVisible=false;
        TargetObj = new Target__c();
        docID = [select id from document where developername='Upload_Item_template' limit 1].id;
    }
    public void importCSVFile(){  
        try
        {
           location__c loc = new location__C();
           CollList = New List<Target__c>(); 
           failedColl = New List<Target__c>();           
           List<Target__c>  returnedList  = New List<Target__c>(); 
           
           system.debug('~~~~  b44 ~~~~');
           
           csvAsString = csvFileBody.toString();
           //csvAsString = EncodingUtil.base64Encode(csvAsString);
           
           system.debug('~~~~  csvFileLines ~~~~'+ csvFileLines);
           
           csvFileLines = csvAsString.split('\n');  

           string t ;

           system.debug('~~~~  csvRecordData ~~~~' + csvFileLines);
                  
                            
           for(Integer i=1;i<csvFileLines.size();i++)
           {
           
               csvRecordData = csvFileLines[i].split(',');
               system.debug('~~~~  csvRecordData ~~~~' + csvRecordData);
               /*
               returnedList = [select id from Target__c where Target__c.StockCode__c =: csvRecordData[1]];
               if(returnedList.size()>0)
               {
                   TargetObj = new Target__c();
                   TargetObj.Name = csvRecordData[0];
                   TargetObj.StockCode__c = csvRecordData[1];
                   TargetObj.UPC__c = csvRecordData[2];                     
                   TargetObj.Description__c = 'Target already exist in the system.';
                   failedColl.add(TargetObj);
               }
               else
               {     
                   try{                 
                      TargetObj = new Target__c();
                      TargetObj.Name = csvRecordData[0];
                      TargetObj.StockCode__c = csvRecordData[1];  
                      TargetObj.UPC__c = csvRecordData[2] ;                   
                      TargetObj.AccountInfo__c= csvRecordData[3];
                      TargetObj.BrandInfo__c= csvRecordData[4];
                      TargetObj.CategoryInfo__c= csvRecordData[5];
                      TargetObj.TargetType__c= csvRecordData[6];
                      TargetObj.DescriptionName__c= csvRecordData[7];
                      TargetObj.PackageSizeQty__C= Decimal.valueOf(csvRecordData[8]);
                      TargetObj.PackageSizeUnits__c = csvRecordData[9];
                      TargetObj.department__c = csvRecordData[10];
                      insert TargetObj;  //inserting every object and not the whole list to catch exceptions at object level
                      CollList.add(TargetObj);
                     
                  }
                  catch(exception ex){
                        TargetObj = new Target__c();
                        TargetObj.Name = csvRecordData[0];
                        TargetObj.StockCode__c = csvRecordData[1];
                        TargetObj.UPC__c = csvRecordData[2];                        
                        TargetObj.Description__c = ex.getdmlMessage(0);
                        failedColl.add(TargetObj);
                  } 
             }      
                  */
                  system.debug('~~~~  csvRecordData ~~~~' + csvRecordData);
                  
                  try{                 
                      TargetObj = new Target__c();
                      TargetObj.Name = csvRecordData[0];
                      TargetObj.StockCode__c = csvRecordData[1];  
                      TargetObj.UPC__c = csvRecordData[2] ;                   
                      TargetObj.AccountInfo__c= csvRecordData[3];
                      TargetObj.BrandInfo__c= csvRecordData[4];
                      TargetObj.CategoryInfo__c= csvRecordData[5];
                      TargetObj.TargetType__c= csvRecordData[6];
                      TargetObj.Description__c= csvRecordData[7];
                      TargetObj.PackageSizeQty__C= Decimal.valueOf(csvRecordData[8]);
                      TargetObj.PackageSizeUnits__c = csvRecordData[9];
                      TargetObj.DepartmentName__c = csvRecordData[10];
                      insert TargetObj;  //inserting every object and not the whole list to catch exceptions at object level
                      CollList.add(TargetObj);
                     
                  }
                  catch(exception ex){
                        TargetObj = new Target__c();
                        TargetObj.Name = csvRecordData[0];
                        TargetObj.StockCode__c = csvRecordData[1];
                        TargetObj.UPC__c = csvRecordData[2];                        
                        TargetObj.Description__c = ex.getdmlMessage(0);
                        failedColl.add(TargetObj);
                  }
               
          }
          
         //  insert CollList;
          isGridVisible=true;                      
        
        
       }
       catch (System.DmlException e) {
            ApexPages.Message errorMessage = new ApexPages.Message(ApexPages.severity.ERROR,e.getDMLMessage(0));
            ApexPages.addMessage(errorMessage);
        }
       catch (Exception e)
       {
            //ApexPages.Message errorMessage = new ApexPages.Message(ApexPages.severity.ERROR,'Invalid file with errors.');
            ApexPages.Message errorMessage = new ApexPages.Message(ApexPages.severity.ERROR,e.getMessage());            
            ApexPages.addMessage(errorMessage);
       }          
   }
}