src_old/objects/Location__c.object
<CustomObject>
    <description>Location defines a location and its type, address, and the Retailer is it associated with. Location is related to Retailer, Job, and Project Location.</description>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Banner__c</fullName>
        <label>Store Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Banner XYZ</fullName>
                    <default>true</default>
                    <label>Banner XYZ</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LocationNumber__c</fullName>
        <label>Location Number</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PostalCode__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Postal Code</label>
        <referenceTo>PostalCode__c</referenceTo>
        <relationshipLabel>Locations (Postal Code)</relationshipLabel>
        <relationshipName>Locations1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State/Province</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AS</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>FM</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>GU</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MH</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>NY</fullName>
                </value>
                <value>
                    <fullName>OH</fullName>
                </value>
                <value>
                    <fullName>TX</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/PostalCode__c.object
<CustomObject>
    <description>Postal Code stores a global list of Postal Codes with Country and Geolocation information that is referenced from multiple objects. Postal Code is related to Location, Job, and Project Location.</description>
    <label>Postal Code</label>
    <nameField>
        <label>Postal Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Postal Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planning</fullName>
                    <default>true</default>
                    <label>Planning</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Launched</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ended</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ProjectLocation__c.object
<CustomObject>
    <description>Project Location relates a Location to a Project. Project Location is related Project, Job, and Location.</description>
    <fields>
        <fullName>Address__c</fullName>
        <formula>Location__r.Address__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <formula>Location__r.City__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsNewLocation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates a if the project location i added in scheduled state</description>
        <label>is New Location</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LocationNumber__c</fullName>
        <formula>Location__r.LocationNumber__c</formula>
        <label>Location #</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Project Locations</relationshipLabel>
        <relationshipName>ProjectLocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PostalCode__c</fullName>
        <formula>Location__r.PostalCode__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Postal Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>ProjectLocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <formula>TEXT(Location__r.State__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>State/Province/Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Job Created</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project Location</label>
    <nameField>
        <displayFormat>PL-{0000}</displayFormat>
        <label>Location ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/classes/LightningProjectLocationsController.cls
public with sharing class LightningProjectLocationsController {
  private static Integer MAX_ROW_SIZE;
  static {
    MAX_ROW_SIZE = 100;
  }
@AuraEnabled
  public static void createJobs(Map<String,String> query){
    try{
      //todo call create job logic
    }
    catch(Exception ex){
        throw new AuraHandledException(ex.getStackTraceString() + ' :' + ex.getMessage());
    }
  }

  @AuraEnabled
  public static Map<String,Object> getSettings(Map<String,String> query){
    try{
    Map<String,Object> result = new Map<String,Object>();
    String projectId = parseString(query.get('projectId'));
    
    if (String.isBlank(projectId)){
      throw new AuraHandledException('The project identifier and location identifiers are required.');
    }
    result.put('storeTypes', getStoreTypes());
    result.put('services',getServices(projectId));
    return result;
    }catch(Exception ex){
      throw new AuraHandledException(ex.getStackTraceString() + ' :' + ex.getMessage());
    }
  }

  private static  List<Map<String,String>> getServices(String projectId){
    List<Map<String,String>> services = new List<Map<String,String>>();
    String[] names = new String[] {'Beer Test','Drug Test'};
    for(String name: names){
      Map<String,String> mapItem = new Map<String,String>();
      mapItem.put('id', name);
      mapItem.put('value', name);
      services.add(mapItem);
    }
    return services;

  }
  private static  List<Map<String,String>> getStoreTypes(){
    List<Map<String,String>> storeTypes = new List<Map<String,String>>();
    String[] names = new String[] {'Banner XYZ','24 Hrs Pharmacy'};
    for(String name: names){
      Map<String,String> mapItem = new Map<String,String>();
      mapItem.put('id', name);
      mapItem.put('value', name);
      storeTypes.add(mapItem);
    }
    return storeTypes;
  }
  @AuraEnabled
  public static void addLocations(Map<String,Object> query){
    try {
      List<Map<String,Object>> data = new List<Map<String,Object>>();
      String projectId = parseString(query.get('id'));
      List<String> locations = parseStringList(query.get('locations'));
      if (locations.size() > 0 && !String.isBlank(projectId)){
        addProjectLocations(projectId, locations);
        return;
      }
    }
    catch(Exception ex){
      throw new AuraHandledException(ex.getMessage() + ':' + ex.getStackTraceString());
    }
    throw new AuraHandledException('The project identifier and location identifiers are required when adding locations.');
  }

  private static void addProjectLocations(String projectId, List<String>locations){
    List<ProjectLocation__c> recordSet= new List<ProjectLocation__c>();
    ProjectLocation__c projectLocation;
    Project__c project = [SELECT Id,Status__c FROM Project__c WHERE Id =:projectId];
    Boolean isNewLocation = CONSTANTS.PROJECT_STATUS_PLANNING.equalsIgnoreCase(project.Status__c)?false: true; 
    List<String> sql = new List<String>();
    sql.add('SELECT Id From Location__c WHERE IsActive__c=true');
    sql.add('AND Id In :locations');
    sql.add('AND Id Not In (Select Location__c FROM ProjectLocation__c Where Project__c=:projectId)');
    
    for(Location__c location: database.query(String.join(sql, ' '))){
      projectLocation = new ProjectLocation__c();
      projectLocation.Location__c = location.id;
      projectLocation.Project__c = projectId;
      projectLocation.IsNewLocation__c = isNewLocation;
      recordSet.add(projectLocation);
    }
    if (recordSet.size() > 0) {
      database.insert(recordset);
    }
  }

  @AuraEnabled
  public static void removeProjectLocations(Map<String,Object>query){
    try
    {
      String projectId = parseString(query.get('id'));
      List<String> locations = parseStringList(query.get('locations'));
      if (locations.isEmpty() || String.isBlank(projectId)){
        throw new AuraHandledException('The project identifier and locations\' identifiers are required.');
      }
      //todo remove project locations
    }
    catch(Exception ex)
    {
      throw new AuraHandledException(ex.getMessage());
    }
  }

  private static List<String> parseStringList(Object val){
    List<String> result = new List<String>();
    List<Object> values;
    if (null != val) {
      values = (List<Object>)val;
      for(Object obj: values){
        result.add(String.valueOf(obj));
      }
    }
    return result;
  }

  @AuraEnabled
  public static List<Map<String,Object>> searchKeyword(Map<String,String> query){
    List<Map<String,Object>> data = new List<Map<String,Object>>();
    String[] params = validateKeywordSearch(query);
    try{
      List<Location__c> locations = getLocationsByKeyword(params[0], params[1]);
      for(Location__c rec: locations){
        data.add(transformLocation(rec));
      }
      return data;
    }
    catch(Exception ex){
      throw new AuraHandledException(ex.getMessage() + ':' + ex.getStackTraceString());
    }
  }

  private static String[] validateKeywordSearch(Map<String,String> query){
    String projectId = parseString(query.get('projectId'));
    String keyword = parseString(query.get('keyword'));
    if (String.isBlank(projectId)){
      throw new AuraHandledException('The project identifier is required when searching locations.');
    }
    return new String[] {projectId, keyword};
  }

  private static List<Location__c> getLocationsByKeyword(String projectId, String keyword){
    List<String> sql = genLocationSelectBaseSoql();
    if (!String.isBlank(keyword)){
      keyword = keyword + '%';
      sql.add('AND (LocationNumber__c Like :keyword OR Name Like :keyword)');
    }
    sql.add(' LIMIT ' + MAX_ROW_SIZE);
    return database.query(String.join(sql,' '));
  }

  private static Map<String,Object> transformLocation(Location__c location){
    Map<String,Object> rec = new Map<String,Object>();
    rec.put('id', location.Id);
    rec.put('num', location.LocationNumber__c);
    rec.put('name', location.Name);
    rec.put('postal', location.PostalCode__r != null ? location.PostalCode__r.Name : '');
    rec.put('city', location.City__c);
    rec.put('state', location.State__c);
    rec.put('type', location.Banner__c);
    return rec;
  }

  @AuraEnabled
  public static List<Map<String,Object>> searchProjectLoctionsByKeyword(Map<String,String>query){
    List<Map<String,Object>> data = new List<Map<String,Object>>();
    String[] params = validateKeywordSearch(query);
    try{
      List<ProjectLocation__c> projectLocations = getProjectLocationByKeyword(params[0], params[1]);
      for(ProjectLocation__c rec: projectLocations){
        data.add(transformProjectLocation(rec));
      }
      return data;
    }
    catch(Exception ex){
      throw new AuraHandledException(ex.getMessage() + ':' + ex.getStackTraceString());
    }
    
    return data;
  }

  private static List<ProjectLocation__c> getProjectLocationByKeyword(string projectId, string keyword){
    List<String> sql = new List<String>();

    return new List<ProjectLocation__c>();
  }

  private static Map<String,Object> transformProjectLocation(ProjectLocation__c c){
      Map<String,Object>item = new Map<String,Object>();
      /*
      item.put('id', 100 + i);
      item.put('name', names[remainder]);
      item.put('postal', 75020 + i);
      item.put('city', cities[remainder]);
      item.put('state',states[remainder]);
      item.put('workers',remainder + 1);
      item.put('hours', remainder + 1);
      item.put('type',storeTypes[remainder]);
      item.put('address', (100+i) + ' ' + addresses[remainder]);
      item.put('schedule',baseDate.addDays(i));
      item.put('execution',executions[math.mod(i,3)]);
      item.put('company',companies[remainder]);
      */
      return item;
  }

  @AuraEnabled
  public static List<Map<String,Object>> filterLocations(Map<String,String> query){
    List<Map<String,Object>> data = new List<Map<String,Object>>();
    String city = parseString(query.get('city'));

    return data;
  }

  private static List<Location__c> getLocationsByFilter(Map<String,String>query){
    List<String> sql = genLocationSelectBaseSoql();
    String projectId = parseString(query.get('projectId'));
    return database.query(String.join(sql,' '));
  }

  private static List<String> genLocationSelectBaseSoql(){
    List<String> sql = new List<String>();
    sql.add('SELECT Id, LocationNumber__c, Name, Address__c, City__c, State__c, PostalCode__r.Name, Banner__c FROM Location__c');
    sql.add('WHERE IsActive__c=true');
    sql.add('AND Id Not In (SELECT Location__c FROM ProjectLocation__c WHERE Project__c=:projectId)');
    return sql;
  }

  @AuraEnabled
  public static List<Map<String,Object>> filterProjectLocations(Map<String,String> query){
    List<Map<String,Object>> data = new List<Map<String,Object>>();
    List<Map<String,Object>> results = getProjectLocationTestData();
    String city = parseString(query.get('city')),
      state = parseString(query.get('state')),
      postal = parseString(query.get('postal'));
      for(Map<String,Object> rec: results){
        if (String.valueOf(rec.get('city')).containsIgnoreCase(city)){
          data.add(rec);
        }
    }
    return data;
  }

  private static String parseString(object val){
    return val != null ? String.valueOf(val): '';
  }

  /* demo API */
  private static String[] names {get;set;}
  private static String[] cities {get;set;}
  private static String[] states {get;set;}
  private static String[] storeTypes {get;set;}
  private static String[] addresses {get;set;}
  private static Integer[] executions{get;set;}
  private static String[] companies {get;set;}

  static {
    names = new String[] {
      'Walmart',
      'Walmart SuperCenter',
      'Walgreen',
      'LoneStar Drugstore'
    };
    cities = new String[] {
      'Dallas',
      'Plano',
      'Frisco',
      'Irving'
    };
    storeTypes = new String[] {'24 Hr Pharmacy','Drugstore','Foot&Wear','Food Store'};
    states = new String[] {'TX','CA','OH','NY'};
    addresses = new String[] {
      'main st.','monroe ave.','LaGrange Blvd','Palor St'
    };
    executions = new Integer[]{-1,0,1,0};
    companies = new String[]{
      'Walmart Inc',
      'Soloman Tech Inc',
      'American Airline Inc',
      'User'
    };
  }
  private static List<Map<String,Object>> getLocationTestData(){
    List<Map<String,Object>> data = new List<Map<String,Object>>();
    Map<String,Object> item;
    Integer remainder;
    for(Integer i=0; i < 200; i++){
      remainder = math.mod(i,4);
      item = new Map<String,Object>();
      item.put('id', (100 + i) + '');
      item.put('name', names[remainder]);
      item.put('postal', 75020 + i);
      item.put('city', cities[remainder]);
      item.put('state',states[remainder]);
      item.put('type',storeTypes[remainder]);
      data.add(item);
    }
    return data;
  }

    private static List<Map<String,Object>> getProjectLocationTestData(){
    List<Map<String,Object>> data = new List<Map<String,Object>>();
    Map<String,Object> item;
    Integer remainder;
    Date baseDate = Date.newInstance(2017,1,1);

    for(Integer i=0; i < 200; i++){
      remainder = math.mod(i,4);
      item = new Map<String,Object>();
      item.put('id', 100 + i);
      item.put('name', names[remainder]);
      item.put('postal', 75020 + i);
      item.put('city', cities[remainder]);
      item.put('state',states[remainder]);
      item.put('workers',remainder + 1);
      item.put('hours', remainder + 1);
      item.put('type',storeTypes[remainder]);
      item.put('address', (100+i) + ' ' + addresses[remainder]);
      item.put('schedule',baseDate.addDays(i));
      item.put('execution',executions[math.mod(i,3)]);
      item.put('company',companies[remainder]);
      data.add(item);
    }
    return data;
  }
}