src_old/objects/Location__c.object
<CustomObject>
    <description>Location defines a location and its type, address, and the Retailer is it associated with. Location is related to Retailer, Job, and Project Location.</description>
    <fields>
        <fullName>LocationNumber__c</fullName>
        <label>Location Number</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ProjectLocation__c.object
<CustomObject>
    <description>Project Location relates a Location to a Project. Project Location is related Project, Job, and Location.</description>
    <fields>
        <fullName>LocationNumber__c</fullName>
        <formula>Location__r.LocationNumber__c</formula>
        <label>Location #</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Project Locations</relationshipLabel>
        <relationshipName>ProjectLocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>ProjectLocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Location</label>
    <nameField>
        <displayFormat>PL-{0000}</displayFormat>
        <label>Location ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/classes/UploadLocationsExtTest.cls
@isTest
public class UploadLocationsExtTest {
    @testSetup static void setup(){
        TestUtil.initBaseData();
        TestUtil.generateFullTestProject(ProjectType.MD, System.today().addDays(60), System.today().addDays(70));
    }

    public static testMethod void test_importCSVFile(){ 
        Project__c project = (Project__c) TestUtil.getRecord('Project__c');
        List<Location__c> locs = [SELECT Id,LocationNumber__c FROM Location__c];
        ApexPages.currentPage().getParameters().put('projectid', project.Id);
        
        ApexPages.StandardController controller = new ApexPages.StandardController(new ProjectLocation__c());        
        UploadLocationsExt ctrl = new UploadLocationsExt(controller); 
        ctrl.csvFileBody = locs[0].LocationNumber__c;
        ctrl.importCSVFile();
        ApexPages.Message[] pageMessages = ApexPages.getMessages();
		System.assertEquals(0, pageMessages.size());
        
        ctrl.csvFileBody = locs[0].LocationNumber__c;
        ctrl.importCSVFile();
        pageMessages = ApexPages.getMessages();
		System.assertEquals(0, pageMessages.size());
        
        ctrl.csvFileBody = '-9999';
        ctrl.importCSVFile();
        pageMessages = ApexPages.getMessages();
		System.assertEquals(0, pageMessages.size());
	} 
}