src_old/objects/Location__c.object
<CustomObject>
    <description>Location defines a location and its type, address, and the Retailer is it associated with. Location is related to Retailer, Job, and Project Location.</description>
    <fields>
        <fullName>RetailerAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Retailer Account</description>
        <label>Retailer Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>RetailerAccount</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/Reservation__c.object
<CustomObject>
    <fields>
        <fullName>CancelReason__c</fullName>
        <description>Reservation Cancel reasons</description>
        <label>CancelReason</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Reduced Budget</fullName>
                </value>
                <value>
                    <fullName>Insufficient Funds</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DateRequestSubmitted__c</fullName>
        <label>Request Submit Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>RequestPending__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Request Pending</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RequestStatus__c</fullName>
        <label>Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending Reservation</fullName>
                </value>
                <value>
                    <fullName>Pending Cancellation</fullName>
                </value>
                <value>
                    <fullName>Pending Expiration</fullName>
                </value>
                <value>
                    <fullName>Pending UnReserve</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RetailerAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Retailer Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Reservations (Retailer Account)</relationshipLabel>
        <relationshipName>Reservations1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Reservation</label>
    <nameField>
        <label>Reservation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/LightningReservationController.cls
public with sharing class LightningReservationController 
{
    
    @AuraEnabled
    public static List<ReservationRequestWrapper>  getLocationsApex(Id reservationId, Integer maxCount , string requestedDate, string advancedFilters, string reservationData) {
        try
        {
            Date reqDate = DateUtil.ToDate(requestedDate);
            if (reservationData.trim().length() > 0)
            {
                system.debug('RL: ' + reservationData);
                List<ReservationRequestWrapper> reservationLocations = (List<ReservationRequestWrapper>) JSON.deserialize(reservationData,List<ReservationRequestWrapper>.class);
                return ReservationHelper.GetAvailableLocationsByList(reservationId, reservationLocations, advancedFilters);
            }
            else
            {
	            return ReservationHelper.GetAvailableLocationsByNumber(reservationId, Integer.valueof(maxCount), reqDate, advancedFilters);
            }
                
        }
        catch(Exception ex)
        {
            throw new System.AuraHandledException(ex.getMessage());
        }
    }     
    
    @AuraEnabled
    public static Map<String, List<ReservationRequestWrapper>>  getAlternateReservationOptions(string reservationId, string locationId, string requestedDate, string advancedFilters) {
        try
        {
            Date reqDate = DateUtil.ToDate(requestedDate);
            return ReservationHelper.getAlternateReservationOptions(reservationId, locationId, reqDate, advancedFilters);
        }
        catch(Exception ex)
        {
            throw new System.AuraHandledException(ex.getMessage());
        }
    }     
    
    @AuraEnabled
    public static List<ReservationRequestWrapper>  getReservationLocations(Id reservationId) {
        
        try
        {
            return ReservationHelper.GetReservationLocations(reservationId);
        }
        catch(Exception ex)
        {
            throw new System.AuraHandledException(ex.getMessage());
        }
    }     
    
    
    @AuraEnabled
    public static Integer  getTotalLocationsApex(Id retailerAccountId) {
        
        try
        {
            Integer locationCount = [Select count() FROM Location__c WHERE RetailerAccount__c = :retailerAccountId];
            return locationCount;
        }
        catch(Exception ex)
        {
            throw new System.AuraHandledException(ex.getMessage());
        }
    }     
    
    @AuraEnabled
    public static String getNamespaceApex() {
        return CONSTANTS.CURRENTNAMESPACEPREFIX;
    }    
    
    
    @AuraEnabled
    public static void  reserveLocationsApex(Id reservationId, string reservationData) {
        
        try
        {
            system.debug('RL: ' + reservationData);
            List<ReservationRequestWrapper> reservationLocations = (List<ReservationRequestWrapper>) JSON.deserialize(reservationData,List<ReservationRequestWrapper>.class);
            ReservationHelper.ReserveLocations(reservationId, reservationLocations);
        }
        catch(Exception ex)
        {
            throw new System.AuraHandledException(ex.getMessage());
        }
    }     
    
    @AuraEnabled
    public static void  unreserveLocationsApex(Id reservationId, string reservationData) {
        
        try
        {
            
            system.debug('RL: ' + reservationData);
            List<ReservationRequestWrapper> reservationLocations = (List<ReservationRequestWrapper>) JSON.deserialize(reservationData,List<ReservationRequestWrapper>.class);
            system.debug(reservationLocations);
            ReservationHelper.UnReserveLocations(reservationId, reservationLocations);
        }
        catch(Exception ex)
        {
            throw new System.AuraHandledException(ex.getMessage());
        }
    }
    
    @AuraEnabled
    public static string getReservationReportUrl(string reservationId)
    {
        string ReservationUrl = string.valueOf(AppUtil.ExportReservationReportUrl.replace('{ReservationId}',reservationId));
        return ReservationUrl;
        
    }
    
    @AuraEnabled
    public static string GetReservation(Id reservationId) {
        
        try
        {
            string rw = ReservationHelper.GetReservationDetail(reservationId);
            return rw;
        }
        catch(Exception ex)
        {
            throw new System.AuraHandledException(ex.getMessage());
        }
    } 
    @AuraEnabled
    public static List<String> GetReservationCancelReasons()
    {        
        List<String> options = new List<String>();        
        Schema.DescribeFieldResult fieldResult = Reservation__c.CancelReason__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        options.add('--SELECT--');
        for(Schema.PicklistEntry f : ple)
        {
            options.add(f.getLabel());
        }
        return options;
    }
    
    @AuraEnabled
    public static string  cancelReservationApex(Id reservationId, string cancelReason, string cancelComments) {
        ResponseWrapper rw = ResponseWrapper.getInstance(CONSTANTS.RESPONSE_STATE_SUCCESS, 'Cancel request has been successfully queued.', null);
        try
        {
            List<Reservation__c> reservations = [Select Id, Name, RequestStatus__c, RequestPending__c, DateRequestSubmitted__c FROM Reservation__c 
                                                 WHERE Id = :reservationId];
            if (!reservations.isEmpty())
            {
                ReservationHelper.CancelReservation(reservationId, cancelReason, cancelComments);               
            }
        }
        catch(Exception ex)
        {
            rw.State = CONSTANTS.RESPONSE_STATE_ERROR;
            rw.Message = 'Unable to cancel the reservation : ' + reservationId + ', ' + ex.getMessage();
        }
        return JSON.serialize(rw);  
    }     
    
    //Unused method that needs to be deprecated
    @AuraEnabled
    public static List<ReservationRequestWrapper>  getLocationsByListApex(Id reservationId, string reservationData) {
        
        try
        {
            system.debug('RL: ' + reservationData);
            List<ReservationRequestWrapper> reservationLocations = (List<ReservationRequestWrapper>) JSON.deserialize(reservationData,List<ReservationRequestWrapper>.class);
            return ReservationHelper.GetAvailableLocationsByList(reservationId, reservationLocations);
            
        }
        catch(Exception ex)
        {
            throw new System.AuraHandledException(ex.getMessage());
        }
    }     
    
    
    
}