src_old/objects/Location__c.object
<CustomObject>
    <description>Location defines a location and its type, address, and the Retailer is it associated with. Location is related to Retailer, Job, and Project Location.</description>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LocationNumber__c</fullName>
        <label>Location Number</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OneHubLocationID__c</fullName>
        <description>This is crossmark location identifier.</description>
        <externalId>true</externalId>
        <label>OneHub Location ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Children</relationshipLabel>
        <relationshipName>Children</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PostalCode__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Postal Code</label>
        <referenceTo>PostalCode__c</referenceTo>
        <relationshipLabel>Locations (Postal Code)</relationshipLabel>
        <relationshipName>Locations1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RetailerAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Retailer Account</description>
        <label>Retailer Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>RetailerAccount</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Retailer__c</fullName>
        <label>Retailer</label>
        <referenceTo>Retailer__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State/Province</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AS</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>FM</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>GU</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MH</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Location</fullName>
                </value>
                <value>
                    <fullName>Retailer</fullName>
                </value>
                <value>
                    <fullName>Employee</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/PostalCode__c.object
<CustomObject>
    <description>Postal Code stores a global list of Postal Codes with Country and Geolocation information that is referenced from multiple objects. Postal Code is related to Location, Job, and Project Location.</description>
    <label>Postal Code</label>
    <nameField>
        <label>Postal Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Postal Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <fields>
        <fullName>RetailerAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Inherited from Project Type, but can be edited. Retailer Account will determine the Category selections at the Project Service.</inlineHelpText>
        <label>Retailer Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.OneHubAccountType__c</field>
                <operation>equals</operation>
                <value>Retailer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Retailer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Retailer</label>
        <referenceTo>Retailer__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planning</fullName>
                    <default>true</default>
                    <label>Planning</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Launched</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ended</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <recordTypes>
        <fullName>Canceled</fullName>
        <active>true</active>
        <label>Canceled</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ProjectLocation__c.object
<CustomObject>
    <description>Project Location relates a Location to a Project. Project Location is related Project, Job, and Location.</description>
    <fields>
        <fullName>Address__c</fullName>
        <formula>Location__r.Address__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <formula>Location__r.City__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LocationNumber__c</fullName>
        <formula>Location__r.LocationNumber__c</formula>
        <label>Location #</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Project Locations</relationshipLabel>
        <relationshipName>ProjectLocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OneHubLocationId__c</fullName>
        <formula>Location__r.OneHubLocationID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>OneHub Location ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PostalCode__c</fullName>
        <formula>Location__r.PostalCode__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Postal Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>ProjectLocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Retailer__c</fullName>
        <formula>Project__r.Retailer__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Retailer</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <formula>TEXT(Location__r.State__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>State/Province/Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Job Created</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <formula>IF(Location__r.Parent__c != null, Location__r.Parent__r.Name, &apos;&apos;)</formula>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <label>Project Location</label>
    <nameField>
        <displayFormat>PL-{0000}</displayFormat>
        <label>Location ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/Retailer__c.object
<CustomObject>
    <description>Retailer stores the retailers for the system. Retailer is related to Location, Retailer Service, Retailer Service Certification, and Retailer Service Equipment.</description>
    <label>Retailer</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Retailers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/Locations.cls
public without sharing class Locations extends LightningRequestBase {
  static Integer MAX_ROW_SIZE;
  public static String ACTION_UPLOADFILE;

  static {
    MAX_ROW_SIZE = 9500;
    ACTION_UPLOADFILE = 'uploadFile';
  }

  //api: search
  public override Object search(Object parameters) {
    Map<String, object> query = (Map<String, object>) parameters;
    String action = LightningRequestHelper.getRequestAction(query);
    String projectId = LightningRequestHelper.parseString(query.get('projectId'));
    String keyword = LightningRequestHelper.parseString(query.get('keyword'));

    if (String.isBlank(projectId)) {
      throw new AuraHandledException('The project identifier is required when searching locations.');
    }

    Project__c project = getProject(projectId);

    if (action == ACTION_UPLOADFILE) {
      List<String> locations = LightningRequestHelper.parseArrayOfString(query.get('locations'));
      Boolean useGuid = LightningRequestHelper.parseString(query.get('useGuid')) == '1';
      return handleFileUpload(project, locations, useGuid);
    }

    Map<String, Object> response = new Map<String, Object>();
    List<Map<String, Object>> data = new List<Map<String, Object>>();
    List<Location__c> locations = getLocationsByKeyword(project, keyword);
    for (Location__c rec : locations) {
      data.add(transformLocation(rec));
    }
    return data;
  }

  static Integer countExistedProjectLocations(String projectId) {
    AggregateResult[] results = [SELECT count(id) cnt FROM ProjectLocation__c WHERE Project__c = :projectId];
    return Integer.valueOf(results[0].get('cnt'));
  }

  Map<String, Object> handleFileUpload(Project__c project, List<String> idSet, Boolean useGuid) {
    Map<String, Object> result = new Map<String, Object>();
    //step 1: if no data to upload, error out
    if (idSet.size() == 0) {
      throw new AuraHandledException('No locations to upload.');
    }

    LocationUploadPasteAnalyzer analyzer = new LocationUploadPasteAnalyzer(idSet, useGuid);
    Map<String, List<Map<String, Object>>> data = analyzer.getData(project.Id, project.Retailer__c, project.RetailerAccount__c);
    result.put(LocationUploadPasteAnalyzer.LocationsKey, data.get(LocationUploadPasteAnalyzer.LocationsKey));
    result.put(LocationUploadPasteAnalyzer.ExclusionsKey, data.get(LocationUploadPasteAnalyzer.ExclusionsKey));

    return result;
  }

  private static List<Location__c> getLocationsByKeyword(Project__c project, String keyword) {
    String projectId = project.Id;
    List<String> sql = genLocationSelectBaseSoql();
    if (String.isNotBlank(keyword)) {
      keyword = keyword + '%';
      sql.add('AND (OneHubLocationId__c Like :keyword OR Name Like :keyword)');
    }

    String retailerId = project.Retailer__c;
    if (String.isNotBlank(retailerId)) {
      sql.add('AND Retailer__c = :retailerId');
    }

    String retailerAccountId = project.RetailerAccount__c;
    if (String.isNotBlank(retailerAccountId)) {
      sql.add('AND RetailerAccount__c = :retailerAccountId');
    }

    Integer count = MAX_ROW_SIZE - countExistedProjectLocations(project.Id);
    sql.add('LIMIT ' + count);
    return database.query(String.join(sql, ' '));
  }

  private static Map<String, Object> transformLocation(Location__c location) {
    Map<String, Object> rec = new Map<String, Object>();
    rec.put('id', location.Id);
    rec.put('uid', location.OneHubLocationID__c);
    rec.put('num', location.LocationNumber__c);
    rec.put('name', location.Name);
    rec.put('postal', location.PostalCode__r != null ? location.PostalCode__r.Name : '');
    rec.put('city', location.City__c);
    rec.put('state', location.State__c);
    rec.put('type', location.Parent__r != null ? location.Parent__r.Name : '');
    return rec;
  }

  private static List<String> genLocationSelectBaseSoql() {
    List<String> sql = new List<String>();
    sql.add('SELECT Id, LocationNumber__c, OneHubLocationID__c, Name, Address__c, City__c, State__c, PostalCode__r.Name, Parent__r.Name FROM Location__c');
    sql.add('WHERE IsActive__c=true AND Type__c=\'Location\'');
    sql.add('AND OneHubLocationID__c <> null');
    sql.add('AND Id Not In (SELECT Location__c FROM ProjectLocation__c WHERE Project__c=:projectId AND Status__c != \'Canceled\')');
    return sql;
  }

  //api: filter
  public override Object filter(Object parameters) {
    Map<String, object> query = (Map<String, object>) parameters;
    String projectId = LightningRequestHelper.parseString(query.get('projectId'));

    if (String.isBlank(projectId)) {
      throw new AuraHandledException('The project identifier is required when filtering locations.');
    }

    Project__c project = getProject(projectId);

    String keyword = LightningRequestHelper.parseString(query.get('keyword'));
    String city = LightningRequestHelper.parseString(query.get('city'));
    String state = LightningRequestHelper.parseString(query.get('state'));
    String postal = LightningRequestHelper.parseString(query.get('postal'));
    String storeType = LightningRequestHelper.parseString(query.get('type'));

    Map<String, Object> response = new Map<String, Object>();
    List<Map<String, Object>> data = new List<Map<String, Object>>();
    List<Location__c> locations = getLocationsByFilter(project,keyword, city, state, postal, storeType);
    for (Location__c rec : locations) {
      data.add(transformLocation(rec));
    }
    return data;
  }
  static List<Location__c> getLocationsByFilter(Project__c project,  String keyword, String city, String state, String postal, String storeType) {
    Integer count = MAX_ROW_SIZE - countExistedProjectLocations(project.Id);
    if (count == 0) {
      throw new AuraHandledException('The maximum of 9500 Locations has been reached.');
    }
    String projectId = project.Id;
    List<String> sql = genLocationSelectBaseSoql();
    
    String retailerId = project.Retailer__c;
    if (String.isNotBlank(retailerId)) {
      sql.add('AND Retailer__c = :retailerId');
    }

    String retailerAccountId = project.RetailerAccount__c;
    if (String.isNotBlank(retailerAccountId)) {
      sql.add('AND RetailerAccount__c = :retailerAccountId');
    }

    if (!String.isBlank(keyword)) {
      keyword = keyword + '%';
      sql.add('AND (LocationNumber__c Like :keyword OR Name Like :keyword)');
    }
    if (!String.isBlank(city)) {
      city = city + '%';
      sql.add('AND City__c like :city');
    }
    if (!String.isBlank(city)) {
      city = city + '%';
      sql.add('AND City__c like :city');
    }
    if (!String.isBlank(state)) {
      state = state + '%';
      sql.add('AND State__c like :state');
    }
    if (!String.isBlank(postal)) {
      postal = postal + '%';
      sql.add('AND PostalCode__r.Name like :postal');
    }
    if (!String.isBlank(storeType)) {
      storeType = storeType + '%';
      sql.add('AND Parent__r.Name LIKE :storeType');
    }

    sql.add('LIMIT ' + count);
    return database.query(String.join(sql, ' '));
  }

  static Project__c getProject(String projectId) {
    List<Project__c> pList = [SELECT Id, Retailer__c, RetailerAccount__c FROM Project__c WHERE Id = :projectId];
    if (pList.isEmpty()) {
      throw new AuraHandledException('The project is not found.');
    }

    return pList[0];
  }
}