src_old/objects/Material__c.object
<CustomObject>
    <description>Material defines a physical item that will be shipped to a Location to by a Fulfillment Center. Material is related to Fulfillment Center and Job Material.</description>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FulfillmentCenterName__c</fullName>
        <formula>FulfillmentCenter__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Fulfillment Center Name</label>
        <type>Text</type>
    </fields>
    <label>Material</label>
    <nameField>
        <label>Material Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Materials</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planning</fullName>
                    <default>true</default>
                    <label>Planning</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Launched</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ended</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ProjectService__c.object
<CustomObject>
    <description>Project Service relates a Service to a Project and is a container used to define the instance of a Service for a specific Project. Project Service is related to Project, Job, Project Service Attribute, Project Service Certification, Project Service Equipment, Project Service Material, Project Service Question, Project Service Target, and Service.</description>
    <fields>
        <fullName>FulfillmentCenterName__c</fullName>
        <label>Fulfillment Center Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>ProjectServices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ServiceTitle__c</fullName>
        <inlineHelpText>Description of Service -- visible to rep and client</inlineHelpText>
        <label>Service Title</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Executed</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project Service</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectServiceMaterial__c.object
<CustomObject>
    <description>Relates Material to a Project Service. Material is added manually when building a Project. Project Service Material is related to Project Service and Material.</description>
    <fields>
        <fullName>MaterialName__c</fullName>
        <formula>Material__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Material Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Material__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Material</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Material__c.IsActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Material__c</referenceTo>
        <relationshipLabel>Project Service Material</relationshipLabel>
        <relationshipName>ProjectServiceMaterial</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectService__c</fullName>
        <label>Project Service</label>
        <referenceTo>ProjectService__c</referenceTo>
        <relationshipLabel>Project Service Materials</relationshipLabel>
        <relationshipName>ProjectServiceMaterials</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ShipTo__c</fullName>
        <label>ShipTo</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Rep</fullName>
                    <default>true</default>
                    <label>Rep</label>
                </value>
                <value>
                    <fullName>Location</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UseType__c</fullName>
        <label>UseType</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>By Location</fullName>
                    <default>true</default>
                    <label>By Location</label>
                </value>
                <value>
                    <fullName>By Rep</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project Service Material</label>
    <nameField>
        <displayFormat>PSM-{00000000}</displayFormat>
        <label>Project Service Material Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Service Material</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/classes/ProjectServiceMaterialWrapper.cls
public class ProjectServiceMaterialWrapper {
    
    @AuraEnabled
    public String ProjectServiceMaterialId {get;set;}
    
    @AuraEnabled
    public String ProjectServiceId {get;set;}
    
    @AuraEnabled
    public String MaterialId {get;set;}
    
    @AuraEnabled
    public String MaterialName {get;set;}
    
    @AuraEnabled
    public Decimal Quantity {get;set;}
    
    @AuraEnabled
    public Boolean Selected {get; set;}
    
    @AuraEnabled
    public String ProjectServiceTitle {get;set;}
    
    @AuraEnabled
    public String FulfillmentCenterName {get;set;}
    
    @AuraEnabled
    public String UseType {get;set;}
    
    @AuraEnabled
    public String ShipTo {get;set;}
    
    @AuraEnabled
    public String ExternalId {get;set;}
    
    @AuraEnabled
    public String ProjectStatus {get;set;}
    
        
    public ProjectServiceMaterialWrapper()
    {
        
    }
    
    public ProjectServiceMaterialWrapper(ProjectServiceMaterial__c projectServiceMaterial)
    {
        ProjectServiceMaterialId = projectServiceMaterial.Id;
        ProjectServiceId = projectServiceMaterial.ProjectService__c;
        MaterialId = projectServiceMaterial.Material__c;
        MaterialName = projectServiceMaterial.MaterialName__c;           
        Quantity = projectServiceMaterial.Quantity__c;
        ProjectServiceTitle = projectServiceMaterial.ProjectService__r.ServiceTitle__c;
        FulfillmentCenterName = projectServiceMaterial.Material__r.FulfillmentCenterName__c;
        ExternalId = projectServiceMaterial.Material__r.ExternalId__c;
        ShipTo = projectServiceMaterial.ShipTo__c;
        UseType = projectServiceMaterial.UseType__c;
        ProjectStatus = projectServiceMaterial.Projectservice__r.Project__r.Status__c;
        Selected = false;
    }
    
    public ProjectServiceMaterialWrapper(Material__c material)
    {        
        MaterialId = material.Id;
        MaterialName = material.Name;  
        Quantity = 0;
        Selected = false;
        FulfillmentCenterName = material.FulfillmentCenterName__c;
        ExternalId = material.ExternalId__c;
    }
}