src_old/objects/Material__c.object
<CustomObject>
    <description>Material defines a physical item that will be shipped to a Location to by a Fulfillment Center. Material is related to Fulfillment Center and Job Material.</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>2500</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>EstimatedCostPerUnit__c</fullName>
        <formula>FulfillmentBundling__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Estimated Cost Per Unit</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Kit__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Kit</label>
        <type>Checkbox</type>
    </fields>
    <label>Material</label>
    <nameField>
        <label>Material Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Materials</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ProjectService__c.object
<CustomObject>
    <description>Project Service relates a Service to a Project and is a container used to define the instance of a Service for a specific Project. Project Service is related to Project, Job, Project Service Attribute, Project Service Certification, Project Service Equipment, Project Service Material, Project Service Question, Project Service Target, and Service.</description>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>ProjectServices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Service</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectServiceMaterial__c.object
<CustomObject>
    <description>Relates Material to a Project Service. Material is added manually when building a Project. Project Service Material is related to Project Service and Material.</description>
    <fields>
        <fullName>CostPerUnit__c</fullName>
        <formula>Material__r.EstimatedCostPerUnit__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Cost Per Unit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Kit__c</fullName>
        <formula>Material__r.Kit__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Kit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MaterialDescription__c</fullName>
        <label>Material Description</label>
        <length>2500</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>MaterialName__c</fullName>
        <formula>Material__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Material Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Material__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Material</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Material__c.IsActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Material__c</referenceTo>
        <relationshipLabel>Project Service Material</relationshipLabel>
        <relationshipName>ProjectServiceMaterial</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectService__c</fullName>
        <label>Project Service</label>
        <referenceTo>ProjectService__c</referenceTo>
        <relationshipLabel>Project Service Materials</relationshipLabel>
        <relationshipName>ProjectServiceMaterials</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Project Service Material</label>
    <nameField>
        <displayFormat>PSM-{00000000}</displayFormat>
        <label>Project Service Material Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Service Material</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/classes/ProjectServiceMaterialsAddExtTest.cls
@isTest
public class ProjectServiceMaterialsAddExtTest {

    @testSetup static void setup(){
        TestUtil.initBaseData();
        TestUtil.generateFullTestProject(ProjectType.MD, Date.today().addDays(10), Date.today().addDays(20));
    }

    public static testMethod void Test_ProjServiceMaterialsAdd()
    {
        Project__c project = (Project__c) TestUtil.getRecord('Project__c');
        List<ProjectService__c> projServs = [SELECT Id FROM ProjectService__c WHERE Project__c = :project.Id];
        List<Material__c> mts = (List<Material__c>) TestUtil.getRecordset('Material__c');
        
        // create a new standard controller by passing it the account record
        ApexPages.StandardController controller = new ApexPages.StandardController(projServs[0]);
        ApexPages.currentPage().getParameters().put('id', projServs[0].Id);
        
        // now pass it to the extension
        ProjectServiceMaterialsAddExt ext= new ProjectServiceMaterialsAddExt(controller);
        
        system.assert(ext != null);        
        system.assert(ext.materials.size() == 0);        
        
        Material__c mat = mts[0];
        
        projectservicematerial__C pscObj = new projectservicematerial__C();
        pscObj.ProjectService__c = projServs[0].Id;
        pscObj.Material__c = mat.Id;
        //pscObj.MaterialName__c = mat.Name;
        pscObj.Quantity__c = 1;
        pscObj.MaterialDescription__c = mat.Description__c;
        //pscObj.Kit__c=mat.Kit__c;
        //pscObj.CostPerUnit__c=mat.EstimatedCostPerUnit__c;
        
        ext.psm = pscObj;
        ext.AddMaterial();
        
        //system.assert(ext.materials.size() == 0);
        
        //ApexPages.currentPage().getParameters().put('psmParamDEL', ext.materials[0].Id); 
        
        //ext.DeleteMaterials();
        //system.assert(ext.materials.size() == 0);
               
        
    }    
}