src_old/objects/NamespaceSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>ClassPrefix__c</fullName>
        <description>Namespace followed by . to prefix apex classes and visualforce pages</description>
        <inlineHelpText>Namespace followed by . to prefix apex classes and visualforce pages</inlineHelpText>
        <label>Class Prefix</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ObjectPrefix__c</fullName>
        <defaultValue>&apos;&apos;</defaultValue>
        <description>The namespace followed by __ to prefix Salesforce Objects</description>
        <inlineHelpText>The namespace followed by __ to prefix Salesforce Objects</inlineHelpText>
        <label>Object Prefix</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RawPrefix__c</fullName>
        <defaultValue>&apos;&apos;</defaultValue>
        <description>The namespace prefix by itself</description>
        <inlineHelpText>The namespace prefix by itself</inlineHelpText>
        <label>Raw Prefix</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Namespace Settings</label>
</CustomObject>

src_old/objects/ProjectService__c.object
<CustomObject>
    <description>Project Service relates a Service to a Project and is a container used to define the instance of a Service for a specific Project. Project Service is related to Project, Job, Project Service Attribute, Project Service Certification, Project Service Equipment, Project Service Material, Project Service Question, Project Service Target, and Service.</description>
    <label>Project Service</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/PostInstall.cls
public with sharing class PostInstall implements installHandler {
public void onInstall(InstallContext context) {
    //fetch custom setting or create it for the first time
    NamespaceSettings__c ns = NamespaceSettings__c.getOrgDefaults();
    if (ns == null) ns = new NamespaceSettings__c();

    //ns
    ns.RawPrefix__c = CancelProjectServiceExt.class.getName().substringBefore('CancelProjectServiceExt').substringBefore('.');

    //ns.
    ns.ClassPrefix__c = CancelProjectServiceExt.class.getName().substringBefore('CancelProjectServiceExt');

    //ns__
    ns.ObjectPrefix__c = SObjectType.ProjectService__c.Name.substringBefore('ProjectService__c');

    //write the values away
    upsert ns;
}
}