src_old/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>A search field that indicates the name of the opportunity for the Project.</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/cdlinkTriggerHandler.cls
public class cdlinkTriggerHandler extends TriggerHandler {
    
    public override void beforeInsert(){
        if (TriggerUtil.skipCDLinkTrigger) return;
        Schema.DescribeSObjectResult inv = Opportunity.sObjectType.getDescribe();
        String invKeyPrefix = inv.getKeyPrefix(); 
        system.debug('invKeyPrefix:::' + invKeyPrefix);
        
        if(trigger.isInsert){
            map<string,string> ContentDocumentLinkMap = new map<string,string>();
            for(ContentDocumentLink a :(List<ContentDocumentLink> )trigger.new){
                
                if(invKeyPrefix == String.valueOf(a.LinkedEntityId).left(3))
                {
                    ContentDocumentLinkMap.put(a.LinkedEntityId,a.ContentDocumentId);
                    a.ShareType = 'I';
                    
                }
                
            }
            
            if(ContentDocumentLinkMap.size()>0)
            {
                List<Project__c> lstProjects = [SELECT Id,name,Opportunity__c FROM Project__c WHERE Opportunity__c = :ContentDocumentLinkMap.keySet()];
                
                if(lstProjects.size() >0 )
                {
                    List<ContentDocumentLink> cdList = new List<ContentDocumentLink>();
                    for(Project__c p  :lstProjects)
                    {
                        
                        ContentDocumentLink cdl = new ContentDocumentLink(LinkedEntityId = p.Id, ContentDocumentId = ContentDocumentLinkMap.get(p.Opportunity__c) ,ShareType ='I');
                        cdList.add(cdl);
                        
                    }
                    
                    if(cdList.size() > 0){
                        insert cdList;
                    }
                }
                
            }
        }
    }
    
}