src_old/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Reservation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reservation</label>
        <referenceTo>Reservation__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src_old/objects/Reservation__c.object
<CustomObject>
    <fields>
        <fullName>NumberofReservedLocations__c</fullName>
        <label>Number of Reserved Locations</label>
        <summaryFilterItems>
            <field>ReservationLocation__c.Status__c</field>
            <operation>equals</operation>
            <value>Reserved</value>
        </summaryFilterItems>
        <summaryForeignKey>ReservationLocation__c.Reservation__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>PrimaryOpportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Reservations</relationshipLabel>
        <relationshipName>Reservations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>&apos;Draft&apos;</defaultValue>
        <description>Status of the reservation</description>
        <inlineHelpText>Status of the Reservation.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Reserved</fullName>
                    <label>Booked</label>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Reservation</label>
    <nameField>
        <label>Reservation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/objects/ReservationLocation__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <formula>Location__r.Address__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <formula>Location__r.City__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LocationNumber__c</fullName>
        <formula>Location__r.LocationNumber__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Location Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reservation__c</fullName>
        <label>Reservation</label>
        <referenceTo>Reservation__c</referenceTo>
        <relationshipLabel>Reservation Locations</relationshipLabel>
        <relationshipName>Reservation_Locations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ReservedDate__c</fullName>
        <label>Reserved Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <formula>TEXT(Location__r.State__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>State</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending Reservation</fullName>
                </value>
                <value>
                    <fullName>Reserved</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Pending Cancellation</fullName>
                </value>
                <value>
                    <fullName>Pending Expiration</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Reservation Location</label>
    <nameField>
        <displayFormat>RL-{00000}</displayFormat>
        <label>Reservation Location Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservation Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/classes/ReservationLocationsExportController.cls
public class ReservationLocationsExportController {
    public List<Map<String,Object>> Locations {get;set;}
    
    public ReservationLocationsExportController() {
        try{
            String recordId = ApexPages.currentPage().getParameters().get('id');
            
            List<ReservationLocation__c> locations = this.getLocations(recordId);
			if(!locations.isEmpty()){ this.Locations = this.mapLocations(locations); }
            
        } catch(Exception ex){
            system.debug(ex.getStackTraceString());
        }
        
    }
    
    List<Map<String,Object>> mapLocations(List<ReservationLocation__c> locations){
        List<Map<String,Object>> results = new List<Map<String,Object>>();
        for(ReservationLocation__c res: locations) {
            
            results.add(
                new Map<String,Object> {
                    'LocationNumber' => normalizeValue(res.LocationNumber__c),
                        'Address' => normalizeValue(res.Address__c),
                        'ReservationName' => normalizeValue(res.Reservation__r.Name),
                        'NumberOfReservedLocations' => string.valueOf(normalizeValue(string.valueOf(res.Reservation__r.NumberofReservedLocations__c))),
                        'PrimaryOpportunity' => normalizeValue(res.Reservation__r.PrimaryOpportunity__r.Name),
                        'City' => normalizeValue(res.City__c),
                        'State' => normalizeValue(res.State__c),
                        'Status' => normalizeValue(res.Status__c),
                        'Id' => normalizeValue(res.Id),
                        'ReservedDate' =>  normalizeValue(res.ReservedDate__c)
                        });
        }
        
        return results;
    }
    
    Object normalizeValue(Object val){
        return val != null ? val : '';
    }
    public List<ReservationLocation__c> getLocations(string id) {
        try{
            
            String recordId = apexpages.currentpage().getparameters().get('id');
            List<ReservationLocation__c> results =[SELECT Id, Name, Reservation__c, Status__c, State__c, City__c, 
                                                   LocationNumber__c, Address__c, Reservation__r.Name, 
                                                   Reservation__r.NumberofReservedLocations__c, 
                                                   Reservation__r.PrimaryOpportunity__r.Name, ReservedDate__c
                                                   FROM ReservationLocation__c 
                                                   WHERE Reservation__c =: id
                                                   AND Status__c =: CONSTANTS.RESERVATION_STATUS_RESERVED]; 
            
            system.debug(results);
            return results;
            
        } catch(Exception ex){
            system.debug(ex.getStackTraceString());
        }
        return null;
    }
}