src_old/objects/OrgCustomSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Generic org settings will be stored here</description>
    <fields>
        <fullName>ClosedProjectPendingArchiveDays__c</fullName>
        <defaultValue>30</defaultValue>
        <description>Number days since the project close date to set project archive status to pending</description>
        <label>ClosedProjectPendingArchiveDays</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ClosedProjectRetentionDays__c</fullName>
        <defaultValue>30</defaultValue>
        <label>Closed Project Retention Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Org Custom Settings</label>
</CustomObject>

src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <fields>
        <fullName>ArchiveStatus__c</fullName>
        <label>Archive Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ProjectGracePeriodDuration__c</fullName>
        <description>A field that indicates the duration of the grace period for the Project.</description>
        <label>Project Grace Period Duration</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planning</fullName>
                    <default>true</default>
                    <label>Planning</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Launched</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ended</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/classes/DataArchiveHandlerTest.cls
@isTest
public class DataArchiveHandlerTest {
    
    @testSetup static void init(){
        TestUtil.initBaseData();
        
        OrgCustomSettings__c settings = [SELECT Id, ClosedProjectRetentionDays__c FROM OrgCustomSettings__c LIMIT 1];
        settings.ClosedProjectPendingArchiveDays__c = -100;
        settings.ClosedProjectRetentionDays__c = -100;
        update settings;
        
    }
    
    @isTest static void test_SetProjectArchiveStatusToPending(){
        //arrange
        Project__c project = TestUtil.generateFullTestProject(ProjectType.MD, Date.today().addDays(20),Date.today().addDays(30));
        DataArchiveHandler daHandler = new DataArchiveHandler();
        project.Status__c = CONSTANTS.PROJECT_STATUS_CLOSED;
        project.ProjectGracePeriodDuration__c = 0;
        update project;
        
        //act
        Test.startTest();
        daHandler.archive();
        Test.stopTest();
        
        //assert
        Integer count  = [SELECT count() FROM Project__c WHERE ArchiveStatus__c = :CONSTANTS.ARCHIVE_STATUS_PENDING];
        system.assertEquals(1, count, 'look for project archive status: pending');
        
    }    
    
    
    @isTest static void test_DeleteProject(){
        //arrange
        Project__c project = TestUtil.generateFullTestProject(ProjectType.MD, Date.today().addDays(20),Date.today().addDays(30));
        DataArchiveHandler daHandler = new DataArchiveHandler();
        project.Status__c = CONSTANTS.PROJECT_STATUS_CLOSED;
        project.ProjectGracePeriodDuration__c = 0;
        project.ArchiveStatus__c = CONSTANTS.ARCHIVE_STATUS_ARCHIVED;
        update project;
        
        system.debug('update project '+project);
        //act
        Test.startTest();
        daHandler.archive();
        Test.stopTest();
        
        //assert
        //This is no longer valid as we don't delete project
        //for now we just delete the jobs and attempts
        //Integer count  = [SELECT count() FROM Project__c];
        //system.assertEquals(0, count, 'project should be deleted');

        
    }      
}