src_old/objects/OrgCustomSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Generic org settings will be stored here</description>
    <fields>
        <fullName>ClosedProjectPendingArchiveDays__c</fullName>
        <defaultValue>30</defaultValue>
        <description>Number days since the project close date to set project archive status to pending</description>
        <label>ClosedProjectPendingArchiveDays</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ClosedProjectRetentionDays__c</fullName>
        <defaultValue>30</defaultValue>
        <label>Closed Project Retention Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DataArchivePendingProjectsLimit__c</fullName>
        <label>Data Archive Pending Projects Limit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DataArchiveProjectsLimit__c</fullName>
        <defaultValue>50</defaultValue>
        <label>DataArchiveProjectsLimit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Org Custom Settings</label>
</CustomObject>

src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <fields>
        <fullName>ApexJobName__c</fullName>
        <description>A field that indicates the apex job name of the Project.</description>
        <inlineHelpText>The apex job name of the project</inlineHelpText>
        <label>ApexJobName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ArchiveStatus__c</fullName>
        <label>Archive Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IsOneHubMobile__c</fullName>
        <formula>ProjectType__r.IsOneHubMobile__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is OneHub Mobile</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProjectCloseDate__c</fullName>
        <description>A field that indicates the close date and time for the Project.</description>
        <formula>if(ISPICKVAL(Status__c,&apos;Canceled&apos;), NULL ,EndDate__c+ProjectGracePeriodDuration__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The close date and time for the project.</inlineHelpText>
        <label>Project Close Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SkipValidationRules__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SkipValidationRules</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planning</fullName>
                    <default>true</default>
                    <label>Planning</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Launched</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ended</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/DataArchiveHandler.cls
global class DataArchiveHandler {
	global DataArchiveHandler() {}
    
    global void archive(){
        
        OrgCustomSettings__c settings = OrgCustomSettings__c.getInstance('Setting');
        Integer projectArchivePendingDays = (settings == null || settings.ClosedProjectPendingArchiveDays__c == null) ? 30 : Integer.valueOf(settings.ClosedProjectPendingArchiveDays__c);
        Integer projectRetentionDays = (settings == null || settings.ClosedProjectRetentionDays__c == null) ? 30 : Integer.valueOf(settings.ClosedProjectRetentionDays__c);
        Integer dataArchiveProjectsLimit = (settings == null || settings.DataArchiveProjectsLimit__c == null) ? 50 : Integer.valueOf(settings.DataArchiveProjectsLimit__c);
		Integer dataArchivePendingProjectsLimit = (settings == null || settings.DataArchivePendingProjectsLimit__c == null) ? 50 : Integer.valueOf(settings.DataArchivePendingProjectsLimit__c);        
        
        Date pendingArchiveDay = (DateTime.now()).AddDays(projectArchivePendingDays * -1).date();
        Date deleteDay = (DateTime.now()).AddDays(projectRetentionDays * -1).date();
        
        system.debug('pendingArchiveDay::::::: '+pendingArchiveDay);
        system.debug('deleteDay::::::: '+deleteDay);
        try {
            TriggerUtil.SkipAllTriggers();
            //mark arcive status for projects that are colsed for more than x days to pending
            //Excluding OHM projects for now until we have a plan for JobImages
  			List<Project__c> projects = [SELECT Id, ArchiveStatus__c, SkipValidationRules__c, ProjectCloseDate__c FROM Project__c WHERE 
                                         Status__c = :CONSTANTS.PROJECT_STATUS_CLOSED AND ProjectCloseDate__c <= :pendingArchiveDay 
                                         AND ArchiveStatus__c = null AND IsOneHubMobile__c = false 
                                         ORDER BY ProjectCloseDate__c LIMIT :dataArchivePendingProjectsLimit];
            for(Project__c p: projects){
                p.ArchiveStatus__c = CONSTANTS.ARCHIVE_STATUS_PENDING;
                p.SkipValidationRules__c = true;
            }
            update projects;
            
            projects = [SELECT Id, ArchiveStatus__c FROM Project__c WHERE Status__c = :CONSTANTS.PROJECT_STATUS_CLOSED 
                        AND ProjectCloseDate__c <= :deleteDay AND ArchiveStatus__c =:CONSTANTS.ARCHIVE_STATUS_ARCHIVED
                        AND (ApexJobName__c = '' OR ApexJobName__c = null) 
                        ORDER BY ProjectCloseDate__c LIMIT :dataArchiveProjectsLimit];
            system.debug('Projects to Archive' + projects);
            //Changes by RN on 12/4/2017
            //For now, we'll remove only Jobs and Job Attempts so
            //the archived project can be cloned
            for(Project__c p :projects){
                ProjectActionsHelper.DeleteAllJobsByProject(p.Id);
            }
        }
        catch(Exception e) {
        	
            String messageSubject = 'Data archive job failed';
            String messageBody = e.getMessage();            
            String[] toAddresses = AppUtil.getAppSetting('DevAlertEmails').split(',');
            EmailHelper.SendEmail(toAddresses,messageSubject,messageBody,true); 
        }
    }
}