src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <fields>
        <fullName>NumberOfDays__c</fullName>
        <inlineHelpText>Number of days available to complete project execution at a location</inlineHelpText>
        <label>Number of Days</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProjectType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Type</label>
        <referenceTo>ProjectType__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ResponsibleForExecution__c</fullName>
        <label>Responsible For Execution</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Execution Company</fullName>
                    <default>true</default>
                    <label>Execution Company</label>
                </value>
                <value>
                    <fullName>Retailer</fullName>
                </value>
                <value>
                    <fullName>Supplier</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planning</fullName>
                    <default>true</default>
                    <label>Planning</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Launched</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ended</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ProjectService__c.object
<CustomObject>
    <description>Project Service relates a Service to a Project and is a container used to define the instance of a Service for a specific Project. Project Service is related to Project, Job, Project Service Attribute, Project Service Certification, Project Service Equipment, Project Service Material, Project Service Question, Project Service Target, and Service.</description>
    <fields>
        <fullName>CheckDistribution__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Adding Distribution Check service, set flag so that distribution repository is checked at each Location.</description>
        <inlineHelpText>Select to create Target questions only for Products in distribution (PDS) at the rep&apos;s location.</inlineHelpText>
        <label>Filter Targets by Location</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EndTime__c</fullName>
        <label>End Time</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EstimatedMinutes__c</fullName>
        <inlineHelpText>Estimated Project Service minutes per rep</inlineHelpText>
        <label>Estimated Minutes</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IncludeAutoGenManual__c</fullName>
        <defaultValue>true</defaultValue>
        <description>setting to include system generated manual. Default to true</description>
        <label>Attach System Generated Manual</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsMaterialNeeded__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Select when Project Service Materials are required.</inlineHelpText>
        <label>Is Material Needed?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>JobManualFileName__c</fullName>
        <description>Stores the file name of custom template</description>
        <label>Job Manual File Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>JobManualURL__c</fullName>
        <description>URL to access event manual</description>
        <label>Job Manual URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>JobManual__c</fullName>
        <label>JobManual</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No Manual</fullName>
                </value>
                <value>
                    <fullName>Standard</fullName>
                </value>
                <value>
                    <fullName>Custom Manual</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NumberOfDays__c</fullName>
        <defaultValue>1</defaultValue>
        <inlineHelpText>Replaced with Project Number of Days</inlineHelpText>
        <label>Number of Days - N/A FOR NEW PROJECTS</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NumberOfTargets__c</fullName>
        <label>Number of Targets</label>
        <summaryForeignKey>ProjectServiceTarget__c.ProjectService__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>NumberOfWorkers__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Enter the number of workers need to finish the job</description>
        <inlineHelpText>Number of reps allocated to complete project execution at a location</inlineHelpText>
        <label>Number of Workers</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PopulateTargetQuestions__c</fullName>
        <defaultValue>true</defaultValue>
        <description>To populate Target questions on Job manual</description>
        <inlineHelpText>When selected, survey questions will be repeated for each Target on the system-generated Job Manual.</inlineHelpText>
        <label>Populate Target Questions</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProjectType__c</fullName>
        <formula>Project__r.ProjectType__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>ProjectServices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ResponsibleForExecution__c</fullName>
        <label>Responsible For Execution</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Execution Company</fullName>
                    <default>true</default>
                    <label>Execution Company</label>
                </value>
                <value>
                    <fullName>Retailer</fullName>
                </value>
                <value>
                    <fullName>Supplier</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ServiceName__c</fullName>
        <formula>Service__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Service Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ServiceObjective__c</fullName>
        <label>Service Objective</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ServiceRank__c</fullName>
        <description>This is the priority rank of a service to be performed</description>
        <label>ServiceRank</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ServiceTitle__c</fullName>
        <inlineHelpText>Description of Service -- visible to rep and client</inlineHelpText>
        <label>Service Title</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>Project Services</relationshipLabel>
        <relationshipName>ProjectServices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ShippingPreference__c</fullName>
        <description>Shipping Preference</description>
        <inlineHelpText>Shipping Preference</inlineHelpText>
        <label>Shipping Preference</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ship to Worker</fullName>
                    <default>true</default>
                    <label>Ship to Worker</label>
                </value>
                <value>
                    <fullName>Ship to Location</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                    <isActive>false</isActive>
                    <label>None</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>StartTime__c</fullName>
        <inlineHelpText>Replaced by using Location Export/Import function</inlineHelpText>
        <label>Start Time - N/A FOR NEW PROJECTS</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Executed</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>isManualGenInProgress__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isManualGenInProgress</label>
        <type>Checkbox</type>
    </fields>
    <label>Project Service</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectServiceAttribute__c.object
<CustomObject>
    <description>Relates a Service Attribute to a Project Service and prepopulates default values. Service Attribute is related to Service, Project Service Attribute, and Attribute.</description>
    <fields>
        <fullName>AttributeTitle__c</fullName>
        <formula>Attribute__r.AttributeTitle__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Attribute Title</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProjectService__c</fullName>
        <label>Project Service</label>
        <referenceTo>ProjectService__c</referenceTo>
        <relationshipLabel>Project Service Attributes</relationshipLabel>
        <relationshipName>Project_Service_Attributes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>Project Service Attributes</relationshipLabel>
        <relationshipName>Project_Service_Attributes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Service Attribute</label>
    <nameField>
        <displayFormat>PSA-{00000000}</displayFormat>
        <label>Project Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Service Attributes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectType__c.object
<CustomObject>
    <description>Project Type defines a collection of Services and sets configuration options for a Project. Project Type is related to Project, Project Type Execution Company, Project Type Service, and Location Assignment.</description>
    <fields>
        <fullName>AllowMultidays__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Allow Multi-days</label>
        <type>Checkbox</type>
    </fields>
    <label>Project Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Types</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/Service__c.object
<CustomObject>
    <description>Service contains the definition of a service. Service is related to Service Attribute, Service Exception, Service Question, Service Question Defined Response, Retailer Service, Retailer Service Equipment, and Project Service.</description>
    <fields>
        <fullName>AllowDistribution__c</fullName>
        <defaultValue>false</defaultValue>
        <description>when adding Distribution Check service, set flag so that distribution repository is checked at each Location.</description>
        <inlineHelpText>Checking Allow Distribution will add the attributes to the service level for the user to specify using Distribution  check.</inlineHelpText>
        <label>Allow Product Filtering by Location</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsNumberOfWorkersRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <description>It can be used when there is team service on a project</description>
        <inlineHelpText>Enter number of workers required for this team service</inlineHelpText>
        <label>Allow Multiple Workers</label>
        <type>Checkbox</type>
    </fields>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/classes/ProjServiceWrapper.cls
public class ProjServiceWrapper {
    @AuraEnabled
    public String Id{get;set;}
    @AuraEnabled
    public String Name{get;set;}
    @AuraEnabled
    public String RecordID{get;set;}
    @AuraEnabled
    public String ProjectId{get;set;}
    @AuraEnabled
    public string ServiceTitle{get; set;}
    @AuraEnabled
    public string JobManualTemplate{get; set;}
    //public string JobManual{get; set;}
    @AuraEnabled
    public decimal NumberOfWorkers{get; set;}
    @AuraEnabled
    public decimal EstimatedMinutes{get; set;}
    @AuraEnabled
    public decimal NumberOfDays{get; set;}   
    @AuraEnabled
    public string ServiceObjective{get; set;}  
    @AuraEnabled
    public String JobManualUrl{get;set;}
    @AuraEnabled
    public String JobManualFileName{get;set;}
    @AuraEnabled    
    public String StartTime{get;set;}    
    @AuraEnabled    
    public String ResponsibleForExecution{get;set;}    
    @AuraEnabled    
    public boolean IncludeAutoGenManual{get;set;}    
    @AuraEnabled    
    public decimal ServiceRank{get;set;}    
    @AuraEnabled
    public boolean CheckDistribution{get;set;}
    @AuraEnabled
    public boolean AllowDistribution{get;set;}
    @AuraEnabled    
    public boolean isSuccess{get;set;}
    @AuraEnabled    
    public String message{get;set;}
    @AuraEnabled
    public list<PSAttributeWrapper> AvlPSA{get; set;}
    @AuraEnabled
    public String Title {get;set;}
    @AuraEnabled
    public String ServiceName{get;set;}
    @AuraEnabled
    public list<String> AvlTime{get;set;}
    @AuraEnabled
    public list<String> JobManual{get;set;}
    @AuraEnabled    
    public boolean PopulateTargetQuestions{get;set;}
    @AuraEnabled
    public list<String> ECValues{get;set;}
    @AuraEnabled
    public String ShippingPreference{get;set;}
    @AuraEnabled
    public list<String> AvlShippingPreference{get;set;}
    @AuraEnabled    
    public boolean IsMaterialNeeded{get;set;}    
    @AuraEnabled    
    public boolean AllowMultiDays{get;set;} 
    @AuraEnabled    
    public boolean AllowMultiRep{get;set;}  
    @AuraEnabled    
    public String EndTime{get;set;}   
    @AuraEnabled    
    public Boolean IsFirstService{get;set;}   
    @AuraEnabled    
    public Boolean IsLastService{get;set;}   
    @AuraEnabled    
    public String Status{get;set;}      
    @AuraEnabled
    public boolean isManualGenInProgress{get;set;}  
    @AuraEnabled
    public decimal NumberOfTargets{get; set;}
    @AuraEnabled
    public boolean IsJobManualAttributeAdded{get;set;}  
    
    
    public ProjServiceWrapper(){        
    }
    
    public ProjServiceWrapper(projectservice__c ps,list<ProjectServiceAttribute__c> psaList)
    {
        IsJobManualAttributeAdded=false;
        ECValues = AppUtil.getAppSetting('ResponsibleForExecution').split(',');
        string stdTempURL = '/apex/' + CONSTANTS.CURRENTNAMESPACEPREFIX + 'pdftemplate?psId='+ps.Id;
        ID = ps.ID;
        RecordID = ps.ID;
        Name = ps.Name;
        ServiceTitle = (ps.ServiceTitle__c!=null)?ps.ServiceTitle__c:'';
        NumberOfWorkers= ps.NumberOfWorkers__c;
        EstimatedMinutes =  ps.EstimatedMinutes__c!=null?ps.EstimatedMinutes__c:0;
        ProjectId = ps.Project__c;
        NumberOfDays = ps.NumberOfDays__c;
        ShippingPreference=ps.ShippingPreference__c;
        ServiceObjective = (ps.ServiceObjective__c!=null)?ps.ServiceObjective__c:'';
        StartTime = (ps.StartTime__c!=null)?ps.StartTime__c:'12.00am';
        if(ps.JobManual__c == CONSTANTS.JOB_MANUAL_STANDARD_TEMPLATE)
        {
            JobManualUrl =stdTempURL;
            JobManualFileName = ps.JobManualFileName__c;
            IncludeAutoGenManual= (ps.IncludeAutoGenManual__c!=null)?ps.IncludeAutoGenManual__c:true; 
            isManualGenInProgress = ps.isManualGenInProgress__c;
        }
        else if(ps.JobManual__c == CONSTANTS.JOB_NOMANUAL_TEMPLATE)
        {
            JobManualUrl ='';
            JobManualFileName = '';
            IncludeAutoGenManual =false;
            isManualGenInProgress = false;
        }
        else
        {
            JobManualUrl =  ps.JobManualURL__c; 
            JobManualFileName = ps.JobManualFileName__c;
            IncludeAutoGenManual= (ps.IncludeAutoGenManual__c!=null)?ps.IncludeAutoGenManual__c:true; 
            isManualGenInProgress = ps.isManualGenInProgress__c;
        }
        
        JobManualTemplate = (ps.JobManual__c!=null)?ps.JobManual__c:CONSTANTS.JOB_MANUAL_STANDARD_TEMPLATE;
        
        ResponsibleForExecution = ps.ResponsibleForExecution__c;
        ServiceRank = ps.ServiceRank__c;
        CheckDistribution = (ps.CheckDistribution__c!=null)?ps.CheckDistribution__c:false;
        Title = ps.ServiceTitle__c;
        ServiceName = ps.ServiceName__c;
        PopulateTargetQuestions=(ps.PopulateTargetQuestions__c!=null)?ps.PopulateTargetQuestions__c:true;
        AvlShippingPreference = getShippingPreference();
        JobManual = getJobManualInfo();
        IsMaterialNeeded= (ps.IsMaterialNeeded__c!=null)?ps.IsMaterialNeeded__c:false;
        AllowMultiDays=ps.Project__r.ProjectType__r.AllowMultidays__c;
        AllowMultiRep=ps.service__r.IsNumberOfWorkersRequired__c;
        EndTime= ps.EndTime__c!=null?ps.EndTime__c:'12:00am';
        Status =ps.Status__c;
        
        NumberOfTargets = ps.NumberOfTargets__c;
        
        string[] sec = new string[]{'00','15','30','45'};
            string[] hrs = new string[]{'12','1','2','3','4','5','6','7','8','9','10','11'};    
                AvlTime= new list<string>();
        for(string i:hrs){
            for(string j : sec){
                AvlTime.add(string.valueof(i)+':'+string.valueOf(j)+'am');    
            }
        }
        for(string i:hrs){
            for(string j : sec){
                AvlTime.add(string.valueof(i)+':'+string.valueOf(j)+'pm');    
            }
        }        
        
        //AllowDistribution=false;
        //if(ps.Service__r != null){
        AllowDistribution = ps.Service__r.AllowDistribution__c;
        //}
        
        list<PSAttributeWrapper> objList = new list<PSAttributeWrapper>();
        if(psaList != null){
            for(ProjectServiceAttribute__c psa : psaList){
                objList.add(new PSAttributeWrapper(psa));
                if(psa.AttributeTitle__c == 'Job Manual'){
                    IsJobManualAttributeAdded = true;
                }
            }
            AvlPSA = objList;
        }
        isSuccess=true;
    }    
    
    public List<string> getShippingPreference()
    {
        List<string> options = new List<string>();       
        Schema.DescribeFieldResult fieldResult = ProjectService__c.ShippingPreference__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        options.add('--SELECT--');
        for(Schema.PicklistEntry f : ple)
        {
            options.add(f.getValue());
        }               
        return options;
    }
    public List<string> getJobManualInfo()
    {
        List<string> options = new List<string>();       
        Schema.DescribeFieldResult fieldResult = ProjectService__c.JobManual__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for(Schema.PicklistEntry f : ple)
        {
            options.add(f.getValue());
        }               
        return options;
    }
    
    
    
}