src_old/objects/ProjectInvoice__c.object
<CustomObject>
    <fields>
        <fullName>NumberofLineItems__c</fullName>
        <label>Number of Line Items</label>
        <summaryForeignKey>ProjectInvoiceLineItem__c.ProjectInvoice__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Project Invoice</label>
    <nameField>
        <displayFormat>INV-{000000000}</displayFormat>
        <label>Project Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectInvoiceLineItem__c.object
<CustomObject>
    <fields>
        <fullName>LineItemOrder__c</fullName>
        <label>Line Item Order</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProjectInvoice__c</fullName>
        <label>Project Invoice</label>
        <referenceTo>ProjectInvoice__c</referenceTo>
        <relationshipLabel>Project Invoice Line Items</relationshipLabel>
        <relationshipName>Project_Invoice_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Project Invoice Line Item</label>
    <nameField>
        <displayFormat>INVLI-{000000000}</displayFormat>
        <label>Project Invoice Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/ProjectInvoiceLineItemTriggerHandler.cls
public class ProjectInvoiceLineItemTriggerHandler  extends TriggerHandler {
    
    public override void beforeInsert(){
        
        Set<String> piids = new Set<String>();
        Map<String, Integer> pimaxitemsmap = new Map<String, Integer>();       
        
        
        if (TriggerUtil.skipProjectInvoiceLineItemTrigger) return;
        
        for(ProjectInvoiceLineItem__c pili :(List<ProjectInvoiceLineItem__c> )Trigger.new){
        
            piids.add(pili.ProjectInvoice__c);
        }        
        List<ProjectInvoice__c> pis = [SELECT Id, Name, NumberOfLineItems__c FROM ProjectInvoice__c 
                                       WHERE ID IN :piids FOR UPDATE];
        for (ProjectInvoice__c pi : pis)
        {
            pimaxitemsmap.put(pi.Id, Integer.valueof(pi.NumberOfLineItems__c));
        }
        for(ProjectInvoiceLineItem__c pili :(List<ProjectInvoiceLineItem__c> )Trigger.new){
            Integer maxno = 0;
            if (pimaxitemsmap.get(pili.ProjectInvoice__c) != null)
                maxno = pimaxitemsmap.get(pili.ProjectInvoice__c);
            pili.LineItemOrder__c = maxno + 1;
            pimaxitemsmap.put(pili.ProjectInvoice__c, maxno + 1);
        }        
    }
        
    
}