src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <fields>
        <fullName>ApexJobName__c</fullName>
        <description>A field that indicates the apex job name of the Project.</description>
        <inlineHelpText>The apex job name of the project</inlineHelpText>
        <label>ApexJobName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BatchProcessId__c</fullName>
        <description>A field that indicates the ID number of the Batch Process for the Project.</description>
        <inlineHelpText>The ID number for the batch process.</inlineHelpText>
        <label>BatchProcessId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CloneStatus__c</fullName>
        <description>Started,Complete</description>
        <label>Clone Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Started</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ProjectNumber__c</fullName>
        <displayFormat>{YY}{MM}{DD}{000000}</displayFormat>
        <inlineHelpText>this is help text in design</inlineHelpText>
        <label>Project Number</label>
        <type>AutoNumber</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ProjectService__c.object
<CustomObject>
    <description>Project Service relates a Service to a Project and is a container used to define the instance of a Service for a specific Project. Project Service is related to Project, Job, Project Service Attribute, Project Service Certification, Project Service Equipment, Project Service Material, Project Service Question, Project Service Target, and Service.</description>
    <fields>
        <fullName>ProjectNumber__c</fullName>
        <formula>Project__r.ProjectNumber__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>ProjectServices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Service</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectServiceAttribute__c.object
<CustomObject>
    <description>Relates a Service Attribute to a Project Service and prepopulates default values. Service Attribute is related to Service, Project Service Attribute, and Attribute.</description>
    <fields>
        <fullName>AttchFileName__c</fullName>
        <label>AttchFileName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AttributeType__c</fullName>
        <formula>TEXT(Attribute__r.AttributeType__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AttributeType</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AttributeValue__c</fullName>
        <label>Attribute Value</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>IsClonedAttachment__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Cloned Attachment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProjectService__c</fullName>
        <label>Project Service</label>
        <referenceTo>ProjectService__c</referenceTo>
        <relationshipLabel>Project Service Attributes</relationshipLabel>
        <relationshipName>Project_Service_Attributes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Service Attribute</label>
    <nameField>
        <displayFormat>PSA-{00000000}</displayFormat>
        <label>Project Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Service Attributes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/BatchClonedProjectAttachmentsHandler.cls
global class BatchClonedProjectAttachmentsHandler implements Database.Batchable<sObject>, Database.Stateful, Database.AllowsCallouts {
    
    Id projectId;
    global BatchClonedProjectAttachmentsHandler(Id projectId){
        this.projectId = projectId;
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        string query = 'SELECT Id, AttchFileName__c, AttributeValue__c, IsClonedAttachment__c FROM ProjectServiceAttribute__c ';
        query += 'WHERE  ProjectService__r.Project__c = \''+ projectId + '\' AND (AttributeType__c = \'Photo\' OR AttributeType__c = \'File\')';
        system.debug('Clone PSA Query:::: '+query);
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<ProjectServiceAttribute__c> scope) {
        ProjectServiceAttribute__c psa = ((List<ProjectServiceAttribute__c>)scope)[0];
        if(psa.AttributeValue__c != null && psa.AttributeValue__c != ''){         
            system.debug('Before GenerateURL'+psa);
            GenerateURL.GenerateNewURLNonFutureCall(psa.id, psa.AttributeValue__c.split('=')[0]);
            system.debug('After GenerateURL'+psa);
        }
    }   
    
    global void finish(Database.BatchableContext BC) {
        
        String messageBody = '';
        Project__c project = [Select Id, Name, ProjectNumber__c, ApexJobName__c, BatchProcessId__c, RecordTypeId 
                              from Project__c WHERE Id =: this.projectId];
        string link = System.URL.getSalesforceBaseUrl().toExternalForm() + '/' + project.Id;
        messageBody = 'Your request to clone project has completed successfully.<br>Cloned Project Id: ' + project.ProjectNumber__c + '<br>Cloned Project Title: ' + project.Name;
        messageBody = messageBody + '<br><br><a href=' + link + '>Click here to directly access the Cloned project.</a>';            
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        User activeUser = [Select Email From User where Username = :UserInfo.getUserName() limit 1];
        
        TriggerUtil.skipAllTriggers();
        project.CloneStatus__c = CONSTANTS.CLONE_STATUS_COMPLETE;
		ProjectActionsHelper.UnlockProject(project);
        update project;
        
        if (activeUser != null)
        {
            try{
                String[] toAddresses = new String[] {activeUser.Email};
                String messageSubject = 'Clone Request Status: ' + project.Name;
                EmailHelper.SendEmail(toAddresses,messageSubject,messageBody);                
            }
            catch(Exception ex){
                system.debug('ERROR: Failed to send clone success email. Details: ' + ex.getMessage());
            }
        }
    }
    
}