src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <fields>
        <fullName>ApexJobName__c</fullName>
        <description>A field that indicates the apex job name of the Project.</description>
        <inlineHelpText>The apex job name of the project</inlineHelpText>
        <label>ApexJobName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BatchProcessId__c</fullName>
        <description>A field that indicates the ID number of the Batch Process for the Project.</description>
        <inlineHelpText>The ID number for the batch process.</inlineHelpText>
        <label>BatchProcessId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ProjectService__c.object
<CustomObject>
    <description>Project Service relates a Service to a Project and is a container used to define the instance of a Service for a specific Project. Project Service is related to Project, Job, Project Service Attribute, Project Service Certification, Project Service Equipment, Project Service Material, Project Service Question, Project Service Target, and Service.</description>
    <fields>
        <fullName>LastSummaryRefreshDateTime__c</fullName>
        <label>Last Summary Refresh Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>ProjectServices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RefreshSummary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag that indicates that project service needs it&apos;s summary refreshed</description>
        <label>RefreshSummary</label>
        <type>Checkbox</type>
    </fields>
    <label>Project Service</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/classes/BatchUpdateJobSummary.cls
global class BatchUpdateJobSummary implements Database.Batchable<sObject>, Database.Stateful {
    
    //batch delete records, then kick off job update process
    //This batch ONLY runs for ONE Project Service
    Id[] ids;
    Id id;
    Set<Id> projectIds = new Set<Id>();


    global BatchUpdateJobSummary(Id id) {
        
        this.id = id;
        this.ids = new Id[] {id};
    }


    global BatchUpdateJobSummary(Id[] ids) {
        
        if (ids.size() == 0) return;
        this.ids = ids;
        this.id = ids[0];
    }
    
    
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        system.debug('Set Delete Job Batcher Started');
        return Database.getQueryLocator([SELECT Id, name, Project__c FROM ProjectService__c WHERE Id IN :ids]);        
    }
   
    global void execute(Database.BatchableContext BC, List<ProjectService__c> scope) {
    
        for (ProjectService__c ps: scope)
        {
            projectIds.add(ps.Project__c);
                              
        }    
    
        Id[] psIds = new Id[]{};
        for (ProjectService__c ps: scope)
        {
            psIds.add(ps.Id);
        }

        ProjectServiceActionsHelper.UpdateJobSummaryCount(psIds[0]);
   }
    
    global void finish(Database.BatchableContext BC) {
    
        TriggerUtil.SkipAllTriggers();
    
    
        List<ProjectService__c> pss = [Select Id, Name, Project__c, RefreshSummary__c, LastSummaryRefreshDateTime__c from ProjectService__c where Id IN :ids];
        for (ProjectService__c ps : pss)
        {
        
            ps.RefreshSummary__c = false;
            ps.LastSummaryRefreshDateTime__c = DateTime.Now();
        
        }
        
        update pss;
        
        //Clear the batch information form project ONLY if there are no more project services
        //pending for the project
        
        List<Project__c> projects = [Select Id, name, ApexJobName__c, BatchProcessId__c, RecordTypeId
                                     from Project__c where Id IN :projectIds];
                    
        for (Project__c project : projects)
        {
			ProjectActionsHelper.UnlockProject(project);
        }
        update projects;
    
        system.debug('Update Job Summary Batcher Finished');
        
   }    
    
}