src_old/objects/ProjectService__c.object
<CustomObject>
    <description>Project Service relates a Service to a Project and is a container used to define the instance of a Service for a specific Project. Project Service is related to Project, Job, Project Service Attribute, Project Service Certification, Project Service Equipment, Project Service Material, Project Service Question, Project Service Target, and Service.</description>
    <label>Project Service</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectServiceTarget__c.object
<CustomObject>
    <description>Relates a Target to a Project Service. Targets are manually added when building a Project. Project Service Target related to Project Service, Target, and Account.</description>
    <fields>
        <fullName>ProjectService__c</fullName>
        <label>Project Service</label>
        <referenceTo>ProjectService__c</referenceTo>
        <relationshipLabel>Project Service Target</relationshipLabel>
        <relationshipName>ProjectServiceTargets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Primary</fullName>
                </value>
                <value>
                    <fullName>Secondary</fullName>
                </value>
                <value>
                    <fullName>Ingredients</fullName>
                </value>
                <value>
                    <fullName>Analytics</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project Service Target</label>
    <nameField>
        <displayFormat>SC-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Service Target</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/classes/ProjectServiceTargetTriggerHandler.cls
public class ProjectServiceTargetTriggerHandler extends TriggerHandler {

    public override void afterInsert() {
        if(TriggerUtil.skipProjectServiceTargetTrigger){
            return;
        } 
        TriggerUtil.skipProjectServiceTargetTrigger = true;
        String psId = ((List <ProjectServiceTarget__c> ) Trigger.new)[0].projectservice__c;
        
        Set<Id> primaryHaloPSIds = new Set<Id>();
        for (ProjectServiceTarget__c psc: (List <ProjectServiceTarget__c> ) Trigger.new) {
            if(psc.Type__c == 'primary' || psc.Type__c == 'supplemental'){
                primaryHaloPSIds.add(psc.ProjectService__c);
            }
        }

        if(primaryHaloPSIds.size()>0)
            AppUtil.updateProjectService(primaryHaloPSIds);
        
    }
    
    public override void afterUpdate() {
        if(TriggerUtil.skipProjectServiceTargetTrigger) {
            return;
        }
        TriggerUtil.skipProjectServiceTargetTrigger = true;
        
        
        Set<Id> primaryHaloPSIds = new Set<Id>();
        string psID;
        for (ProjectServiceTarget__c psc: (List <ProjectServiceTarget__c> ) Trigger.new) {
            psID = psc.projectservice__c;
            if(psc.Type__c == 'primary' || psc.Type__c == 'supplemental'){
                primaryHaloPSIds.add(psc.ProjectService__c);
            }
        }
        
        if(primaryHaloPSIds.size()>0){
            AppUtil.updateProjectService(primaryHaloPSIds);
        }
    }

    public override void afterDelete() {
         if(TriggerUtil.skipProjectServiceTargetTrigger){
            return;
        } 
        TriggerUtil.skipProjectServiceTargetTrigger = true;
        
        String psId = ((List <ProjectServiceTarget__c> ) Trigger.old)[0].projectservice__c;
        
        Set<Id> primaryHaloPSIds = new Set<Id>();
        for (ProjectServiceTarget__c psc: (List <ProjectServiceTarget__c> ) Trigger.old) {
            if(psc.Type__c == 'primary' || psc.Type__c == 'supplemental'){
                primaryHaloPSIds.add(psc.ProjectService__c);
            }
        }
        if(primaryHaloPSIds.size()>0)
            AppUtil.updateProjectService(primaryHaloPSIds);
        
    }
}