src_old/objects/ProjectServiceQuestion__c.object
<CustomObject>
    <description>Relates a Question to a Project Service. Questions from Service Question are added by default when a Service is added to a Project Service. Additional Questions can be added. Project Service Question is related to Project Service Question, Question, and Question Variant.</description>
    <fields>
        <fullName>QuestionNumber__c</fullName>
        <label>Question Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>QuestionText__c</fullName>
        <formula>Question__r.QuestionText__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Question Text</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QuestionType__c</fullName>
        <formula>TEXT(Question__r.QuestionType__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Question Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Question__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>ProjectServiceQuestions</relationshipLabel>
        <relationshipName>ProjectServiceQuestions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Service Question</label>
    <nameField>
        <displayFormat>PSQ-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Service Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/Question__c.object
<CustomObject>
    <description>Question stores all of the questions stored in the system and defines the type of question (e.g. Date, Text, Y/N) and if the question is related to targets. Question is related to Question Defined Response, Question Variant.</description>
    <fields>
        <fullName>QuestionText__c</fullName>
        <label>Question Text</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QuestionType__c</fullName>
        <label>Question Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Currency</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Multi-Select List</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Photo</fullName>
                </value>
                <value>
                    <fullName>Signature</fullName>
                </value>
                <value>
                    <fullName>Single-Select List</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                </value>
                <value>
                    <fullName>Time</fullName>
                </value>
                <value>
                    <fullName>Yes/No</fullName>
                </value>
                <value>
                    <fullName>Group</fullName>
                </value>
                <value>
                    <fullName>Barcode</fullName>
                </value>
                <value>
                    <fullName>Multi Select Target</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/objects/QuestionDefinedResponse__c.object
<CustomObject>
    <description>Question Defined Response defines the acceptable responses for a Question. Question Defined Response is related to Question and Question Defined Response Variant.</description>
    <fields>
        <fullName>DefinedResponseOrder__c</fullName>
        <label>Defined Response Order</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DefinedResponseText__c</fullName>
        <label>Defined Response Text</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Question Defined Response (SurveyQuestionBank)</relationshipLabel>
        <relationshipName>Question_Defined_Response1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Question Defined Response</label>
    <nameField>
        <displayFormat>QBDR-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Defined Response</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/Question.cls
/** Class: question
    *  Retrieves the question information and puts it in the question object
    */      
    public class Question
    {
        public String   name                   {get; set;}
        public String   id                     {get; set;}
        public String   questionId             {get; set;}
        public String   question               {get; set;}
        public String   answer                 {get; set;}
        public Date     dateanswer             {get; set;}
        public String   orderNumber            {get; set;}
        public String   choices                {get; set;}
        public String   selectedOption         {get;set;}
        public List<String> selectedOptions    {get;set;}
        public List<SelectOption> singleOptions{get; set;}
        public List<SelectOption> multiOptions {get; set;}
        public Boolean  required               {get; set;}
        public String   questionType           {get; set;}    
        public String   surveyName             {get; set;}
        public String   renderFreeText         {get; set;}
        public String   renderNumber           {get; set;}
        public String   renderDate             {get; set;}
        public String   renderFile             {get; set;}      
        public String   renderSelectRadio      {get; set;}
        public String   renderSelectCheckboxes {get; set;} 
        public String   renderSelectRow        {get; set;}
        public List<String> responses          {get; set;}
        public String   singleOptionsForChart  {get; set;}
        public String   qResultsForChart       {get; set;} 
        public List<String> strList            {get; set;} // The question's option as a list of string
        public List<Integer> resultsCounts     {get; set;} // The count of each response to a question's choices
        public List<SelectOption> rowOptions   {get; set;}
        public boolean  noData                 {get; set;}
        public string imageName             {get; set;}  
        transient public Blob imageBody     {get; set;}  
        
        public question() 
        {
        
        }
          
      
      /** Fills up the question object
       *  param:    Survey_Question__c 
       */     
     public question(ProjectServiceQuestion__c sq, string answerText) 
     {
         name = sq.Name;
         id = sq.Id;
         questionId = sq.Question__c;
         answer = answerText;
         question = sq.QuestionText__c;
         system.debug('Question: ' + question + ' - Answer: ' + answer);
         orderNumber = String.valueOf(sq.QuestionNumber__c);
         required = false;
         questionType = sq.QuestionType__c;
         singleOptionsForChart = ' ';
         selectedOption = '';
         selectedOptions = new List<String>();
         renderSelectCheckboxes='false';
         renderFreeText='false';
         renderNumber='false';
         renderDate='false';
         renderFile='false';        
         renderSelectRow = 'false';
         renderSelectRadio='false';        
            
         if (questionType=='Yes/No'){
            choices = 'Yes\nNo';
            renderSelectRadio='true';
            singleOptions = stringToSelectOptions(choices);
            if (answer != '' && answer!= null)
            {
              selectedOption = getselectedoption(choices, answer);
            }
            selectedOptions = new List<String>();                               
          }
         else if (questionType=='Multi-Select List'){        
              choices = getchoices(sq.Question__c);
              renderSelectCheckboxes='true';
              multiOptions = stringToSelectOptions(choices);
              selectedOption = '';
              selectedOptions = new List<String>(); 
              if (answer != '' && answer!= null)
              {
                  selectedOptions = getselectedoptions(choices, answer);
              }
              
          }
         else if (questionType=='Single-Select List'){   
              choices = getchoices(sq.Question__c);
              rowOptions = stringToSelectOptions(choices);
              renderSelectRow = 'true';
              if (answer != '' && answer!= null)
              {
                  selectedOption = getselectedoption(choices, answer);
              }
              selectedOptions = new List<String>();     
          }
         else if (questionType=='Text'){
              renderFreeText='true';
              choices='';
          }
         else if (questionType=='Number'){
              renderNumber='true';
              choices='';
          }
         else if (questionType=='Date'){
              renderDate='true';
              if (answer != '' && answer!= null)
              {
                  dateanswer = Date.ValueOf(answer);
              }
              choices='';
          }
         else if (questionType=='Photo'){
              renderFile='true';
              choices='';
          }
          
     }
     
    
     /** Splits up the string as given by the user and adds each option
      *  to a list to be displayed as option on the Visualforce page
      *  param: str   String as submitted by the user
      *  returns the List of SelectOption for the visualforce page
     */  
     private List<SelectOption> stringToSelectOptions(String str)
     {
         if (str == '')
         {
             return new List<SelectOption>();
         }
         strList = str.split('\n');
          
         List<SelectOption> returnVal = new List<SelectOption>();
         Integer i = 0;
         for(String s: strList){
             if (s!='') {    
                 if (s != 'null' && s!= null) {
                     String sBis = s.replace(' ', '%20');
                     singleOptionsForChart += s.trim()+'|';
                     
                     /*RSC2012-02-20
                     String st = s.replace (' ', '&nbsp;');
                     returnVal.add(new SelectOption(String.valueOf(i),st));
                     */
                     returnVal.add(new SelectOption(s,s));
                     System.debug('*****VALUES: ' + s);
                 }
             }
         }
         singleOptionsForChart = singleOptionsForChart.substring(0, singleOptionsForChart.length()-1);
         return returnVal;
     } 

     private string getchoices(Id qstnId)
     {
         string choices = '';
        
         List<QuestionDefinedResponse__c> qdr = [Select Id, DefinedResponseText__c, DefinedResponseOrder__c from QuestionDefinedResponse__c
                                        where Question__c =: qstnId Order by DefinedResponseOrder__c];
                                        
         for (QuestionDefinedResponse__c dr : qdr)
         {
             choices = choices + dr.DefinedResponseText__c + '\n';
            
         }
         return choices;
    
     }
     
     private string getselectedoption(string options, string answer)
     {
         List<string> optionList = options.split('\n');
         
         for(String option: optionList){
             if (option.toLowerCase() == answer.toLowerCase())       
             {
                 return option;
             }
         
         }

         return '';         
     
     }
     private List<string> getselectedoptions(string options, string answer)
     {
         string optionsString = '';

         List<string> optionList = options.split('\n');
         
         List<string> answers = answer.split('@@@');
         
         for(string ans: answers)
         {
             for(String option: optionList){
                 
                 if (option.toLowerCase() == ans.toLowerCase())       
                 {
                     optionsString = optionsString + option + '@@@';
                     break;
                 }
             }
         }
         
         if (optionsString != '' && optionsString != null)
         {
             return optionsString.left(optionsString.length() - 3).split('@@@');
         }
         
         return new List<string>();
     
     }
     
    
   }