src_old/objects/ProjectServiceQuestion__c.object
<CustomObject>
    <description>Relates a Question to a Project Service. Questions from Service Question are added by default when a Service is added to a Project Service. Additional Questions can be added. Project Service Question is related to Project Service Question, Question, and Question Variant.</description>
    <fields>
        <fullName>ParentProjectServiceQuestion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Parent Project Service Question</description>
        <inlineHelpText>Parent Project Service Question</inlineHelpText>
        <label>Parent Project Service Question</label>
        <referenceTo>ProjectServiceQuestion__c</referenceTo>
        <relationshipLabel>Project Service Questions</relationshipLabel>
        <relationshipName>ParentProjectServiceQuestion</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Service Question</label>
    <nameField>
        <displayFormat>PSQ-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Service Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectServiceQuestionRule__c.object
<CustomObject>
    <description>Project Service Question Rule</description>
    <fields>
        <fullName>DefinedResponseValueText__c</fullName>
        <formula>DefinedResponseValue__r.DefinedResponseText__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Defined Response Value Text</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DefinedResponseValue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Defined Response Value</label>
        <referenceTo>ProjectServiceQuestionDefinedResponse__c</referenceTo>
        <relationshipLabel>Service Question Rules</relationshipLabel>
        <relationshipName>Service_Question_Rules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <label>Operator</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentProjectServiceQuestionText__c</fullName>
        <formula>ParentProjectServiceQuestion__r.QuestionText__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Parent Project Service Question Text</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentProjectServiceQuestionType__c</fullName>
        <formula>ParentProjectServiceQuestion__r.QuestionType__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Parent Project Service Question Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentProjectServiceQuestion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Project Service Question</label>
        <referenceTo>ProjectServiceQuestion__c</referenceTo>
        <relationshipLabel>Service Question Rules</relationshipLabel>
        <relationshipName>Service_Question_Rules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectServiceQuestionText__c</fullName>
        <formula>ProjectServiceQuestion__r.QuestionText__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Service Question Text</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProjectServiceQuestion__c</fullName>
        <label>Project Service Question</label>
        <referenceTo>ProjectServiceQuestion__c</referenceTo>
        <relationshipLabel>Service Question Rules (Project Service Question)</relationshipLabel>
        <relationshipName>Service_Question_Rules1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Project Service Question Rule</label>
    <nameField>
        <displayFormat>PQR-{00000000}</displayFormat>
        <label>Project Service Question Rule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Service Question Rules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/classes/ProjectServiceQuestionRuleWrapper.cls
public class ProjectServiceQuestionRuleWrapper {
    
    @AuraEnabled
    public String Id{get;set;}
    @AuraEnabled
    public String Name{get;set;}
    @AuraEnabled
    public String ProjectServiceQuestion{get;set;}
    @AuraEnabled
    public String ParentProjectServiceQuestion{get;set;}
    @AuraEnabled
    public String SqOperator{get;set;}
    @AuraEnabled
    public String SqValue{get;set;}
    @AuraEnabled
    public String ServiceQuestionText{get;set;}
    @AuraEnabled
    public String ParentProjectServiceQuestionText{get;set;}    
    
    @AuraEnabled
    public String RuleText{get;set;}
    
    @AuraEnabled
    public List<String> RuleValueText{get;set;}
    
    @AuraEnabled
    public ResponseWrapper DefinedResponses {get;set;}
        
    public ProjectServiceQuestionRuleWrapper()
    {
        
    }
    
    public ProjectServiceQuestionRuleWrapper(ProjectServiceQuestionRule__c projectServiceQuestionRule)
    {
        Map<String, Object> fieldsToValue = projectServiceQuestionRule.getPopulatedFieldsAsMap();
        
        Id = projectServiceQuestionRule.Id;
		Name = projectServiceQuestionRule.Name;             
        ProjectServiceQuestion = projectServiceQuestionRule.ProjectServiceQuestion__c;                        
        ParentProjectServiceQuestion = projectServiceQuestionRule.ParentProjectServiceQuestion__c;                         
        SqOperator = projectServiceQuestionRule.Operator__c;         
        SqValue = projectServiceQuestionRule.DefinedResponseValue__c;//projectServiceQuestionRule.Value__c == null ? '' : projectServiceQuestionRule.Value__c;
        ServiceQuestionText = projectServiceQuestionRule.ProjectServiceQuestionText__c;
        ParentProjectServiceQuestionText = projectServiceQuestionRule.ParentProjectServiceQuestionText__c;
        RuleText = SqOperator + ' ' + ((projectServiceQuestionRule.ParentProjectServiceQuestionType__c == 'Single-Select List' || projectServiceQuestionRule.ParentProjectServiceQuestionType__c == 'Multi-Select List') ?  projectServiceQuestionRule.DefinedResponseValueText__c : SqValue);                    
    }
    
}