src_old/objects/ProjectService__c.object
<CustomObject>
    <description>Project Service relates a Service to a Project and is a container used to define the instance of a Service for a specific Project. Project Service is related to Project, Job, Project Service Attribute, Project Service Certification, Project Service Equipment, Project Service Material, Project Service Question, Project Service Target, and Service.</description>
    <fields>
        <fullName>Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>Project Services</relationshipLabel>
        <relationshipName>ProjectServices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Service</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectServiceQuestion__c.object
<CustomObject>
    <description>Relates a Question to a Project Service. Questions from Service Question are added by default when a Service is added to a Project Service. Additional Questions can be added. Project Service Question is related to Project Service Question, Question, and Question Variant.</description>
    <fields>
        <fullName>ProjectService__c</fullName>
        <label>Project Service</label>
        <referenceTo>ProjectService__c</referenceTo>
        <relationshipLabel>ProjectServiceQuestions</relationshipLabel>
        <relationshipName>ProjectServiceQuestions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Question__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>ProjectServiceQuestions</relationshipLabel>
        <relationshipName>ProjectServiceQuestions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ServiceQuestion__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Service Question</label>
        <type>Checkbox</type>
    </fields>
    <label>Project Service Question</label>
    <nameField>
        <displayFormat>PSQ-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Service Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/Question__c.object
<CustomObject>
    <description>Question stores all of the questions stored in the system and defines the type of question (e.g. Date, Text, Y/N) and if the question is related to targets. Question is related to Question Defined Response, Question Variant.</description>
    <fields>
        <fullName>ExceptionQuestion__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ExceptionQuestion</label>
        <type>Checkbox</type>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/objects/Service__c.object
<CustomObject>
    <description>Service contains the definition of a service. Service is related to Service Attribute, Service Exception, Service Question, Service Question Defined Response, Retailer Service, Retailer Service Equipment, and Project Service.</description>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ServiceQuestion__c.object
<CustomObject>
    <description>Service Question relates one or more Questions to a Service and defines how the questions are rendered when building a Project Service. Service Question is related to Service, Question, and Project Service Question.</description>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Service Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>Service Questions</relationshipLabel>
        <relationshipName>Service_Questions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Service Question</label>
    <nameField>
        <displayFormat>SQ-{00000000}</displayFormat>
        <label>Service Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SurveyState.cls
public without sharing class SurveyState {
	boolean hasExceptionQuestion;
	Set<Id> questions;

	private SurveyState(Set<Id> added, Boolean hasException) {
		questions = added;
		hasExceptionQuestion = hasException;
	}

	public static SurveyState fromProjectBuilder(String objId){
		List<Object> result = getAlreadyAddedQuestions(objId, true);
		return new SurveyState((Set<Id>) result[0], (Boolean) result[1]);
	}

	public static SurveyState fromServiceBuilder(String objId){
		List<Object> result = getAlreadyAddedQuestions(objId, false);
		return new SurveyState((Set<Id>) result[0], (Boolean) result[1]);
	}

	public Boolean isQuestionValidToAdd(Id questionId, Boolean isException){
		if (questions.contains(questionId)) {return false;}
		if (hasExceptionQuestion && isException){
			return false;
		}
		return true;
	}

	@testVisible
	static List<Object> getAlreadyAddedQuestions(String sId, Boolean isProjectService) {
		List<Object> result = new List<Object>();
		Set<Id> targets = new Set<Id>();
		Boolean hasException = false;

		if (isProjectService) {
			for (ProjectServiceQuestion__c psq : [SELECT Question__c, Question__r.ExceptionQuestion__c
			                                      FROM ProjectServiceQuestion__c WHERE ProjectService__c = :sId]) {
				targets.add(psq.Question__c);
				if (psq.Question__r.ExceptionQuestion__c){
					hasException = true;
				}
			}
		} else {
			for (ServiceQuestion__c sq : [SELECT Question__c, Question__r.ExceptionQuestion__c
			                              FROM ServiceQuestion__c WHERE Service__c = :sId]) {
				targets.add(sq.Question__c);
				if (sq.Question__r.ExceptionQuestion__c){
					hasException = true;
				}	
			}
		}

		result.addAll(new Object[]{targets, hasException});
		return result;
	}
}