src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <fields>
        <fullName>CancelReasonComment__c</fullName>
        <description>An entry field that indicates the reason(s) the Project was canceled.</description>
        <inlineHelpText>Enter the reason(s) the project was canceled.</inlineHelpText>
        <label>Cancel Reason Comment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CancelReason__c</fullName>
        <description>A picklist that indicates reasons that the project was canceled.</description>
        <inlineHelpText>Select the reason the project was canceled.</inlineHelpText>
        <label>Cancel Reason</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Supplier Requested</fullName>
                </value>
                <value>
                    <fullName>Retailer Requested</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                    <default>true</default>
                    <label>Other</label>
                </value>
                <value>
                    <fullName>Item not approved</fullName>
                    <isActive>false</isActive>
                    <label>Item not approved</label>
                </value>
                <value>
                    <fullName>No Capacity</fullName>
                    <isActive>false</isActive>
                    <label>No Capacity</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ProjectCancelLeadTime__c</fullName>
        <description>A field that indicates the lead time to cancel the Project.</description>
        <formula>Retailer__r.JobCancelLeadTime__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The lead time to cancel the project.</inlineHelpText>
        <label>Project Cancel Lead Time</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>An entry field that indicates the start date of the Project.</description>
        <inlineHelpText>The date available to start execution</inlineHelpText>
        <label>Project Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planning</fullName>
                    <default>true</default>
                    <label>Planning</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Launched</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ended</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <recordTypes>
        <fullName>Canceled</fullName>
        <active>true</active>
        <label>Canceled</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ProjectService__c.object
<CustomObject>
    <description>Project Service relates a Service to a Project and is a container used to define the instance of a Service for a specific Project. Project Service is related to Project, Job, Project Service Attribute, Project Service Certification, Project Service Equipment, Project Service Material, Project Service Question, Project Service Target, and Service.</description>
    <fields>
        <fullName>CancelReasonComment__c</fullName>
        <label>Cancel Reason Comment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CancelReason__c</fullName>
        <label>Cancel Reason</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Supplier Requested</fullName>
                </value>
                <value>
                    <fullName>Retailer Requested</fullName>
                </value>
                <value>
                    <fullName>No Capacity</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>ProjectServices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>Project Services</relationshipLabel>
        <relationshipName>ProjectServices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Executed</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project Service</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Services</pluralLabel>
    <recordTypes>
        <fullName>Canceled</fullName>
        <active>true</active>
        <label>Canceled</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/Service__c.object
<CustomObject>
    <description>Service contains the definition of a service. Service is related to Service Attribute, Service Exception, Service Question, Service Question Defined Response, Retailer Service, Retailer Service Equipment, and Project Service.</description>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/classes/CancelProjectServiceExt.cls
public with sharing class CancelProjectServiceExt {

    ApexPages.StandardSetController setCon;
    public String errorMessage {get;set;}
    
    public projectservice__c  psObj;
   
    public string psNames{get;set;}
    public Project__c projObj{get;set;}
    public List<ProjectService__c> selectedProjectServices{get; set;}
    public string CancelComment{get;set;}  

    public project__c proj{get;set;}  
    
     public projectservice__c getpsObj(){
       psObj=new projectservice__c();
       system.debug('RUN...'+psObj); 
       return psObj;
     }
     
     public void setpsObj(projectservice__c psObj){
         system.debug('RUN SETTER...'+psObj); 
         this.psObj = psObj;
     }

    public project__c getproj() {return proj;}
    public void setproj(project__c value) {proj = value;}    
    
    public CancelProjectServiceExt(ApexPages.StandardSetController controller) {
        setCon = controller;  
        selectedProjectServices = new List<ProjectService__c>();
        String psids = Apexpages.CurrentPage().getParameters().get('psids');
        String projectId = Apexpages.CurrentPage().getParameters().get('id');
        projObj = [select id, name, StartDate__c, Status__c,ProjectCancelLeadTime__c from project__c where id=:projectId];
        selectedProjectServices = [select id, Name, Status__c, Service__r.Name, Project__c, CancelReason__c, CancelReasonComment__c  from projectservice__c where id  IN:  controller.getSelected() and status__c!= 'Canceled'];
        if(selectedProjectServices.size()==0){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, 'Please select a valid Project Service.',''));
        }
        getpsNames();        
    }
    

 
    public string getpsNames() {                
        psNames='';
        for(projectservice__c ps: selectedProjectServices)
        {            
            psNames = psNames + ps.Name + ' - ' + ps.Service__r.Name + ' , ';
        }
        psNames = psNames.removeEnd(', ');
        return psNames;
    }
    
   
    public pagereference CancelService()
    {
        Savepoint sp = Database.setSavePoint();        
        try{
            Id[] PSIDArr =new List<Id>(new Map<Id, ProjectService__c>(selectedProjectServices).keySet());
             ProjectServiceActionsHelper.CancelProjectService(PSIDArr, psObj.CancelReason__c,psObj.CancelReasonComment__c );
            
        }
        catch(Exception ex){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, ex.getMessage(),''));
            Database.rollback(sp);
            return null;
        }
       PageReference cancel = setCon.cancel();        
        system.debug('cancel::'+cancel);
        return cancel;           
        
    }

    public pagereference DoNotCancel()
    {
        PageReference pageRef  = new ApexPages.StandardController(projObj).view();
        pageRef.setRedirect(true);
        return pageRef;
    }    
    
    
}