src_old/objects/ProjectServiceQuestion__c.object
<CustomObject>
    <description>Relates a Question to a Project Service. Questions from Service Question are added by default when a Service is added to a Project Service. Additional Questions can be added. Project Service Question is related to Project Service Question, Question, and Question Variant.</description>
    <fields>
        <fullName>ParentProjectServiceQuestion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Parent Project Service Question</description>
        <inlineHelpText>Parent Project Service Question</inlineHelpText>
        <label>Parent Project Service Question</label>
        <referenceTo>ProjectServiceQuestion__c</referenceTo>
        <relationshipLabel>Project Service Questions</relationshipLabel>
        <relationshipName>ParentProjectServiceQuestion</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ServiceQuestion__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Service Question</label>
        <type>Checkbox</type>
    </fields>
    <label>Project Service Question</label>
    <nameField>
        <displayFormat>PSQ-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Service Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectServiceQuestionRule__c.object
<CustomObject>
    <description>Project Service Question Rule</description>
    <fields>
        <fullName>Operator__c</fullName>
        <label>Operator</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentProjectServiceQuestionText__c</fullName>
        <formula>ParentProjectServiceQuestion__r.QuestionText__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Parent Project Service Question Text</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentProjectServiceQuestionType__c</fullName>
        <formula>ParentProjectServiceQuestion__r.QuestionType__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Parent Project Service Question Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentProjectServiceQuestion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Project Service Question</label>
        <referenceTo>ProjectServiceQuestion__c</referenceTo>
        <relationshipLabel>Service Question Rules</relationshipLabel>
        <relationshipName>Service_Question_Rules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectServiceQuestionText__c</fullName>
        <formula>ProjectServiceQuestion__r.QuestionText__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Service Question Text</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProjectServiceQuestion__c</fullName>
        <label>Project Service Question</label>
        <referenceTo>ProjectServiceQuestion__c</referenceTo>
        <relationshipLabel>Service Question Rules (Project Service Question)</relationshipLabel>
        <relationshipName>Service_Question_Rules1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Project Service Question Rule</label>
    <nameField>
        <displayFormat>PQR-{00000000}</displayFormat>
        <label>Project Service Question Rule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Service Question Rules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ServiceQuestion__c.object
<CustomObject>
    <description>Service Question relates one or more Questions to a Service and defines how the questions are rendered when building a Project Service. Service Question is related to Service, Question, and Project Service Question.</description>
    <fields>
        <fullName>ParentServiceQuestion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Service Question</label>
        <referenceTo>ServiceQuestion__c</referenceTo>
        <relationshipLabel>Service Questions</relationshipLabel>
        <relationshipName>ParentServiceQuestionID</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Question</label>
    <nameField>
        <displayFormat>SQ-{00000000}</displayFormat>
        <label>Service Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/objects/ServiceQuestionRule__c.object
<CustomObject>
    <description>Service Question Rules store this table</description>
    <fields>
        <fullName>Operator__c</fullName>
        <label>Operator</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentServiceQuestionText__c</fullName>
        <formula>ParentServiceQuestion__r.QuestionText__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Parent Service Question Text</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentServiceQuestionType__c</fullName>
        <formula>ParentServiceQuestion__r.QuestionType__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Parent Service Question Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentServiceQuestion__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Parent Service Question</label>
        <referenceTo>ServiceQuestion__c</referenceTo>
        <relationshipLabel>ServiceQuestionRules (Service Question)</relationshipLabel>
        <relationshipName>ParentServiceQuestion</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ServiceQuestionText__c</fullName>
        <formula>ServiceQuestion__r.QuestionText__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Service Question Text</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ServiceQuestion__c</fullName>
        <label>Service Question</label>
        <referenceTo>ServiceQuestion__c</referenceTo>
        <relationshipLabel>ServiceQuestionRules</relationshipLabel>
        <relationshipName>ServiceQuestionRules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <label>Service Question  Rule</label>
    <nameField>
        <displayFormat>QR-{00000000}</displayFormat>
        <label>SurveyQuestionruleName</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ServiceQuestionRules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/classes/ServiceQuestionRuleWrapper.cls
public class ServiceQuestionRuleWrapper {
    
    @AuraEnabled
    public String Id{get;set;}
    @AuraEnabled
    public String Name{get;set;}
    @AuraEnabled
    public String ServiceQuestion{get;set;}
    @AuraEnabled
    public String ParentServiceQuestion{get;set;}
    @AuraEnabled
    public String SqOperator{get;set;}
    @AuraEnabled
    public String SqValue{get;set;}
    @AuraEnabled
    public String ServiceQuestionText{get;set;}
    @AuraEnabled
    public String ParentServiceQuestionText{get;set;}
    
    @AuraEnabled
    public String RuleText{get;set;}
    
    @AuraEnabled
    public List<String> RuleValueText{get;set;}
    
    @AuraEnabled
    public ResponseWrapper DefinedResponses {get;set;}
        
    public ServiceQuestionRuleWrapper()
    {
        
    }
    
    public ServiceQuestionRuleWrapper(ServiceQuestionRule__c serviceQuestionRule)
    {
        Map<String, Object> fieldsToValue = serviceQuestionRule.getPopulatedFieldsAsMap();
        
        Id = serviceQuestionRule.Id;
		Name = serviceQuestionRule.Name;             
        ServiceQuestion = serviceQuestionRule.ServiceQuestion__c;                        
        ParentServiceQuestion = serviceQuestionRule.ParentServiceQuestion__c;                         
        SqOperator = serviceQuestionRule.Operator__c;         
        SqValue =serviceQuestionRule.Value__c;
        ServiceQuestionText = serviceQuestionRule.ServiceQuestionText__c;
        ParentServiceQuestionText = serviceQuestionRule.ParentServiceQuestionText__c;
        //OH2-2168
        RuleText = SqOperator + ' ' + ((serviceQuestionRule.ParentServiceQuestionType__c == 'Single-Select List' || serviceQuestionRule.ParentServiceQuestionType__c == 'Multi-Select List'  ) ? serviceQuestionRule.Value__c : '');
        //RuleText = SqOperator + ' ' + ((serviceQuestionRule.ParentServiceQuestionType__c == 'Single-Select List' ) ? serviceQuestionRule.Value__c : '');
    }
    
    public ServiceQuestionRuleWrapper(ProjectServiceQuestionRule__c projectServiceQuestionRule)
    {
        Map<String, Object> fieldsToValue = projectServiceQuestionRule.getPopulatedFieldsAsMap();
        
        Id = projectServiceQuestionRule.Id;
        Name = projectServiceQuestionRule.Name;             
        ServiceQuestion = projectServiceQuestionRule.ProjectServiceQuestion__c;                        
        ParentServiceQuestion = projectServiceQuestionRule.ParentProjectServiceQuestion__c;                         
        SqOperator = projectServiceQuestionRule.Operator__c;         
        SqValue = projectServiceQuestionRule.Value__c;//projectServiceQuestionRule.Value__c == null ? '' : projectServiceQuestionRule.Value__c;
        ServiceQuestionText = projectServiceQuestionRule.ProjectServiceQuestionText__c;
        ParentServiceQuestionText = projectServiceQuestionRule.ParentProjectServiceQuestionText__c;
        RuleText = SqOperator + ' ' + ((projectServiceQuestionRule.ParentProjectServiceQuestionType__c == 'Single-Select List' ) ?  projectServiceQuestionRule.value__c : SqValue);                    
    }
    
}