src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <fields>
        <fullName>PrimaryAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PrimaryAccount</label>
        <referenceTo>ProjectAccount__c</referenceTo>
        <relationshipLabel>ProjectAccounts</relationshipLabel>
        <relationshipName>ProjectAccounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ProjectAccount__c.object
<CustomObject>
    <description>Project Account maps an Account to a Project and defines how the Account will be billed. Project Account is related to Project, Account, and Account Address.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please make sure this account&apos;s &apos;Can Request Project&apos; setting is enabled.</errorMessage>
            <filterItems>
                <field>Account.CanRequestProjects__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Project Accounts</relationshipLabel>
        <relationshipName>Project_Accounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsPrimary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsPrimary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Project_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Account</label>
    <nameField>
        <displayFormat>PA-{0000000}</displayFormat>
        <label>Project Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectService__c.object
<CustomObject>
    <description>Project Service relates a Service to a Project and is a container used to define the instance of a Service for a specific Project. Project Service is related to Project, Job, Project Service Attribute, Project Service Certification, Project Service Equipment, Project Service Material, Project Service Question, Project Service Target, and Service.</description>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>ProjectServices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Service</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectServiceQuestion__c.object
<CustomObject>
    <description>Relates a Question to a Project Service. Questions from Service Question are added by default when a Service is added to a Project Service. Additional Questions can be added. Project Service Question is related to Project Service Question, Question, and Question Variant.</description>
    <fields>
        <fullName>ProjectService__c</fullName>
        <label>Project Service</label>
        <referenceTo>ProjectService__c</referenceTo>
        <relationshipLabel>ProjectServiceQuestions</relationshipLabel>
        <relationshipName>ProjectServiceQuestions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Question__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>ProjectServiceQuestions</relationshipLabel>
        <relationshipName>ProjectServiceQuestions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Service Question</label>
    <nameField>
        <displayFormat>PSQ-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Service Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/Question__c.object
<CustomObject>
    <description>Question stores all of the questions stored in the system and defines the type of question (e.g. Date, Text, Y/N) and if the question is related to targets. Question is related to Question Defined Response, Question Variant.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ProjectAccountTriggerHandler.cls
public class ProjectAccountTriggerHandler extends TriggerHandler{
    
    public override void beforeDelete(){
          
        if (TriggerUtil.skipProjectAccountTrigger) return;
        
        Map<String,List<ProjectServiceQuestion__c >> psqMap = new Map<String,List<ProjectServiceQuestion__c>>();                
        Set<ID> projectIds = new Set<ID>();
        for (ProjectAccount__c pa :(List<ProjectAccount__c> ) Trigger.old) {
            projectIds.add(pa.Project__c);
        }

        for(ProjectServiceQuestion__c psq : [SELECT Id,Question__r.Account__c,ProjectService__r.Project__c from ProjectServiceQuestion__c 
                                             Where ProjectService__r.Project__c =: projectIds
                                             AND Question__r.Account__c != null]){
                                                 
                                                 string identifier = String.valueOf(psq.ProjectService__r.Project__c) + String.valueOf(psq.Question__r.Account__c);
                                                 
                                                 List<ProjectServiceQuestion__c> psqList = new List<ProjectServiceQuestion__c>();
                                                 psqList.add(psq);
                                                 
                                                 if (psqMap.get(identifier) != null) {
                                                     psqList.addall(psqMap.get(identifier));
                                                 }
                                                 psqMap.put(identifier,psqList);   
                                             }
        
        for (ProjectAccount__c pa :(List<ProjectAccount__c> ) Trigger.old) {
            
            system.debug('psqMap>>' + psqMap.size());
            
            string identifier = String.valueOf(pa.Project__c) + String.valueOf(pa.Account__c);
            if (psqMap != null && psqMap.size() > 0){
                if (psqMap.containsKey(identifier)){
                    
                    system.debug('error>>' +identifier);
                    string bodyText = 'This account has Survey Question(s) associated with it. Please remove or re-associate the Survey Question(s) before deleting the account.';
                    pa.addError(bodyText);
                }
            }
			//pa.addError('bodyText');
        }      

    }
    
    public override void afterInsert(){
        if (TriggerUtil.skipProjectAccountTrigger) return;
        Map<Id,Id> mapPA = new Map<Id,Id>();
        for (ProjectAccount__c pa :(List<ProjectAccount__c> ) Trigger.new) {
            if(pa.IsPrimary__c)
            {
                mapPA.put(pa.project__c,pa.Id);
                
            }
            
        }
        
        List<Project__c> lstProj = [select Id,name,PrimaryAccount__c from Project__c where Id IN :mapPA.keySet()];
        List<project__c>lstprojupdates =new List<project__c>();
        for(project__c p:lstProj)
        {
            Id pa = mapPA.get(p.Id);
            p.PrimaryAccount__c = pa;
            lstprojupdates.add(p);
        }
        if(lstprojupdates.size()>0) 
        {
            update lstprojupdates;
        }
        
        
    }
    
    public override void afterUpdate()
    {
       if (TriggerUtil.skipProjectAccountTrigger) return;
        Map<Id,Id> mapPA = new Map<Id,Id>();
         for (ProjectAccount__c pa :(List<ProjectAccount__c> )Trigger.new) {
            
            if(pa.IsPrimary__c)
            {
                mapPA.put(pa.project__c,pa.Id);
                
            }
            
        }
        
        List<Project__c> lstProj = [select Id, PrimaryAccount__c from Project__c where Id IN :mapPA.keySet()];
        List<project__c>lstprojupdates =new List<project__c>();
        for(project__c p:lstProj)
        {
            Id pa = mapPA.get(p.Id);
            if (p.PrimaryAccount__c != pa){
            	p.PrimaryAccount__c = pa;
            	lstprojupdates.add(p);    
            }
            
        }
        if(lstprojupdates.size()>0) 
        {
            update lstprojupdates;
        }
        
        
    }
   
    
}