src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <fields>
        <fullName>NumberOfJobs__c</fullName>
        <label>Number of Jobs</label>
        <summarizedField>ProjectService__c.NumberOfJobs__c</summarizedField>
        <summaryForeignKey>ProjectService__c.Project__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>NumberofJobsAssigned__c</fullName>
        <label>Number of Jobs Assigned</label>
        <summarizedField>ProjectService__c.NumberOfAssignedJobs__c</summarizedField>
        <summaryForeignKey>ProjectService__c.Project__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>NumberofJobsCanceled__c</fullName>
        <label>Number of Jobs Canceled</label>
        <summarizedField>ProjectService__c.NumberOfCanceledJobs__c</summarizedField>
        <summaryForeignKey>ProjectService__c.Project__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>NumberofJobsClosed__c</fullName>
        <label>Number of Jobs Closed</label>
        <summarizedField>ProjectService__c.NumberOfClosedJobs__c</summarizedField>
        <summaryForeignKey>ProjectService__c.Project__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>NumberofJobsCompleted__c</fullName>
        <label>Number of Jobs Completed</label>
        <summarizedField>ProjectService__c.NumberOfCompletedJobs__c</summarizedField>
        <summaryForeignKey>ProjectService__c.Project__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>NumberofJobsException__c</fullName>
        <label>Number of Jobs Exception</label>
        <summarizedField>ProjectService__c.NumberOfExceptionJobs__c</summarizedField>
        <summaryForeignKey>ProjectService__c.Project__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>NumberofJobsExecuted__c</fullName>
        <label>Number of Jobs Executed</label>
        <summarizedField>ProjectService__c.NumberOfExecutedJobs__c</summarizedField>
        <summaryForeignKey>ProjectService__c.Project__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>NumberofJobsFailedQC__c</fullName>
        <label>Number of Jobs Failed QC</label>
        <summarizedField>ProjectService__c.NumberOfFailedQCJobs__c</summarizedField>
        <summaryForeignKey>ProjectService__c.Project__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>NumberofJobsNotCanceled__c</fullName>
        <label>Number of Jobs Not Canceled</label>
        <summarizedField>ProjectService__c.NumberOfNotCanceledJobs__c</summarizedField>
        <summaryForeignKey>ProjectService__c.Project__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>NumberofJobsOpen__c</fullName>
        <label>Number of Jobs Open</label>
        <summarizedField>ProjectService__c.NumberOfOpenJobs__c</summarizedField>
        <summaryForeignKey>ProjectService__c.Project__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>NumberofJobsPending__c</fullName>
        <label>Number of Jobs Pending</label>
        <summarizedField>ProjectService__c.NumberOfPendingJobs__c</summarizedField>
        <summaryForeignKey>ProjectService__c.Project__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>NumberofJobsReported__c</fullName>
        <label>Number of Jobs Reported</label>
        <summarizedField>ProjectService__c.NumberOfReportedJobs__c</summarizedField>
        <summaryForeignKey>ProjectService__c.Project__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>NumberofJobsRescheduled__c</fullName>
        <label>Number of Jobs Rescheduled</label>
        <summarizedField>ProjectService__c.NumberofJobsRescheduled__c</summarizedField>
        <summaryForeignKey>ProjectService__c.Project__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>NumberofJobsScheduled__c</fullName>
        <label>Number of Jobs Scheduled</label>
        <summarizedField>ProjectService__c.NumberOfScheduledJobs__c</summarizedField>
        <summaryForeignKey>ProjectService__c.Project__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>NumberofJobsStarted__c</fullName>
        <label>Number of Jobs Started</label>
        <summarizedField>ProjectService__c.NumberOfStartedJobs__c</summarizedField>
        <summaryForeignKey>ProjectService__c.Project__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TotalEstimatedMinutes__c</fullName>
        <description>Sum of estimated minutes across all services.</description>
        <inlineHelpText>Sum of Project Service minutes per rep</inlineHelpText>
        <label>Total Estimated Minutes</label>
        <summarizedField>ProjectService__c.EstimatedMinutes__c</summarizedField>
        <summaryForeignKey>ProjectService__c.Project__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TotalTimeReported__c</fullName>
        <label>Depracated - Total Time Reported</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/ProjectDisplaySummaryControllerExt.cls
public with sharing class ProjectDisplaySummaryControllerExt {
   public Project__c Project {get; private set;}

    public ProjectDisplaySummaryControllerExt(ApexPages.StandardController controller) {
        String id = ApexPages.CurrentPage().getParameters().get('id');
        this.Project = [SELECT TotalTimeReported__c, TotalEstimatedMinutes__c, NumberOfJobs__c, NumberOfJobsPending__c, NumberOfJobsOpen__c, NumberOfJobsAssigned__c, NumberOfJobsStarted__c, NumberOfJobsReported__c, NumberOfJobsCanceled__c, NumberOfJobsClosed__c, NumberOfJobsNotCanceled__c, NumberOfJobsExecuted__c, NumberOfJobsCompleted__c, NumberOfJobsScheduled__c, NumberOfJobsRescheduled__c, NumberOfJobsException__c, NumberOfJobsFailedQC__c FROM Project__c WHERE Id=:id];        
        
    }
}