src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <fields>
        <fullName>OneHubRetailerId__c</fullName>
        <description>A field that indicates the ID number of the OneHub retailer.</description>
        <inlineHelpText>The ID number of the OneHub retailer.</inlineHelpText>
        <label>OneHub Retailer Id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Retailer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Retailer</label>
        <referenceTo>Retailer__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ProjectLocation__c.object
<CustomObject>
    <description>Project Location relates a Location to a Project. Project Location is related Project, Job, and Location.</description>
    <fields>
        <fullName>OneHubRetailerId__c</fullName>
        <label>OneHub Retailer Id</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>ProjectLocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Retailer__c</fullName>
        <formula>Project__r.Retailer__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Retailer</label>
        <type>Text</type>
    </fields>
    <label>Project Location</label>
    <nameField>
        <displayFormat>PL-{0000}</displayFormat>
        <label>Location ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectService__c.object
<CustomObject>
    <description>Project Service relates a Service to a Project and is a container used to define the instance of a Service for a specific Project. Project Service is related to Project, Job, Project Service Attribute, Project Service Certification, Project Service Equipment, Project Service Material, Project Service Question, Project Service Target, and Service.</description>
    <fields>
        <fullName>JobManual__c</fullName>
        <label>JobManual</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No Manual</fullName>
                </value>
                <value>
                    <fullName>Standard</fullName>
                </value>
                <value>
                    <fullName>Custom Manual</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NumberOfWorkers__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Enter the number of workers need to finish the job</description>
        <inlineHelpText>Number of reps allocated to complete project execution at a location</inlineHelpText>
        <label>Number of Workers</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OneHubRetailerId__c</fullName>
        <label>One Hub Retailer ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>ProjectServices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Retailer__c</fullName>
        <formula>Project__r.Retailer__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Retailer</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ServiceTitle__c</fullName>
        <inlineHelpText>Description of Service -- visible to rep and client</inlineHelpText>
        <label>Service Title</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>Project Services</relationshipLabel>
        <relationshipName>ProjectServices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TargetType__c</fullName>
        <label>Target Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Project Service</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectServiceQuestion__c.object
<CustomObject>
    <description>Relates a Question to a Project Service. Questions from Service Question are added by default when a Service is added to a Project Service. Additional Questions can be added. Project Service Question is related to Project Service Question, Question, and Question Variant.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProjectService__c</fullName>
        <label>Project Service</label>
        <referenceTo>ProjectService__c</referenceTo>
        <relationshipLabel>ProjectServiceQuestions</relationshipLabel>
        <relationshipName>ProjectServiceQuestions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>QuestionType__c</fullName>
        <formula>TEXT(Question__r.QuestionType__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Question Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Question__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>ProjectServiceQuestions</relationshipLabel>
        <relationshipName>ProjectServiceQuestions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Service Question</label>
    <nameField>
        <displayFormat>PSQ-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Service Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectServiceQuestionDefinedResponse__c.object
<CustomObject>
    <description>Relates a Service Question Defined Response to a Project Service Question. Project Service Question Def Response is related to Project Service Question, Question, Question Defined Response, and Question Defined Repsonse Variant.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProjectServiceQuestion__c</fullName>
        <label>Project Service Question</label>
        <referenceTo>ProjectServiceQuestion__c</referenceTo>
        <relationshipName>ProjectServiceQuestionDefResponses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <formula>ProjectServiceQuestion__r.Question__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Question</label>
        <type>Text</type>
    </fields>
    <label>Project Service Question Def Response</label>
    <nameField>
        <displayFormat>PSQDR-{00000000}</displayFormat>
        <label>Project Service Question  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Service Question Def Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/Question__c.object
<CustomObject>
    <description>Question stores all of the questions stored in the system and defines the type of question (e.g. Date, Text, Y/N) and if the question is related to targets. Question is related to Question Defined Response, Question Variant.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>QuestionType__c</fullName>
        <label>Question Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Currency</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Multi-Select List</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Photo</fullName>
                </value>
                <value>
                    <fullName>Signature</fullName>
                </value>
                <value>
                    <fullName>Single-Select List</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                </value>
                <value>
                    <fullName>Time</fullName>
                </value>
                <value>
                    <fullName>Yes/No</fullName>
                </value>
                <value>
                    <fullName>Group</fullName>
                </value>
                <value>
                    <fullName>Barcode</fullName>
                </value>
                <value>
                    <fullName>Multi Select Target</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TargetType__c</fullName>
        <label>Target Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Product</fullName>
                </value>
                <value>
                    <fullName>Display</fullName>
                </value>
                <value>
                    <fullName>Event</fullName>
                </value>
                <value>
                    <fullName>Brand</fullName>
                </value>
                <value>
                    <fullName>Manufacturer</fullName>
                </value>
                <value>
                    <fullName>Category</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/objects/Retailer__c.object
<CustomObject>
    <description>Retailer stores the retailers for the system. Retailer is related to Location, Retailer Service, Retailer Service Certification, and Retailer Service Equipment.</description>
    <fields>
        <fullName>OneHubRetailerId__c</fullName>
        <label>One Hub Retailer ID</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Retailer</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Retailers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/RetailerService__c.object
<CustomObject>
    <description>Retailer Service relates Services to a Retailer, which determines the Services that are available when building a Project Service. Retailer Service is related to Retailer and Service.</description>
    <fields>
        <fullName>Retailer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Retailer</label>
        <referenceTo>Retailer__c</referenceTo>
        <relationshipLabel>Retailer Services</relationshipLabel>
        <relationshipName>RetailerService_Retailers</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>Retailer Services</relationshipLabel>
        <relationshipName>RetailerService_Services</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Retailer Service</label>
    <nameField>
        <displayFormat>RTSR-{000}</displayFormat>
        <label>Retailer Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retailer Services</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/Service__c.object
<CustomObject>
    <description>Service contains the definition of a service. Service is related to Service Attribute, Service Exception, Service Question, Service Question Defined Response, Retailer Service, Retailer Service Equipment, and Project Service.</description>
    <fields>
        <fullName>TargetType__c</fullName>
        <label>Target Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Product</fullName>
                    <default>true</default>
                    <label>Product</label>
                </value>
                <value>
                    <fullName>Category</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/CloneUtilTest.cls
@isTest
public class CloneUtilTest {

    @testSetup static void setup() {
        TestDataUtil.init();
        TestProject tP = TestProject.create('demo');
        tP.addAccount()
        .addServices(3)
        .addLocations(2);
        for(TestProjectService tPs: tP.TestProjectServiceList) {
            tPs.addSurvey();
        }
    }

    static void add100ServiceToProject(Project__c project) {
        TestDataUtil.disableTriggers();
        //step1 create 100 service
        List<String> names = new List<String>();
        for (Integer i = 0; i < 200; i++) {
            names.add('name' + String.valueOf(i));
        }

        List<Service__c> rs = TestDataUtil.initServicesByNames(names);

        //step2 add to retailer service
        Retailer__c retailer = [select id from Retailer__c limit 1];
        TestDataUtil.initRetailerServicesByServiceList(retailer, rs);
        List<RetailerService__c> retailerServices = [SELECT Id,Service__r.Name, Service__c,Retailer__c FROM RetailerService__c];

        //step3 add to project services
        List<ProjectService__c> psList = new List<ProjectService__c>();

        for (RetailerService__c service : retailerServices) {
            ProjectService__c ps = new ProjectService__c(
                Project__c = project.Id,
                Service__c = service.Service__c,
                ServiceTitle__c = service.Service__r.Name,
                TargetType__c = 'Brand',
                JobManual__c = 'Standard',
                NumberOfWorkers__c = 1,
                OneHubRetailerId__c = 'OH' + String.valueOf(service.Retailer__c)
            );
            psList.add(ps);
        }
        TestDataUtil.enableTriggers();
        insert psList;
    }

    static Integer getProjectServiceCount(string projectId){
        List<AggregateResult> results = [Select Count(Id) total FROM ProjectService__c
         WHERE Project__c=:projectId];
         return Integer.valueOf(results.get(0).get('total'));
    }

    static Integer getProjectLocationCount(string projectId){
        list<AggregateResult> results = [SELECT Count(Id) total FROM ProjectLocation__c 
        WHERE Project__c=:projectId];
        return Integer.valueOf(results.get(0).get('total'));
    }

    
    @istest static void itShouldCloneMoreThan100Services() {
        //GIVEN
        Project__c p = [SELECT Id from Project__c WHERE Name = 'demo' LIMIT 1];
        TestProject tP = TestProject.get(p.Id);
        add100ServiceToProject(tP.ProjectInstance);

        Integer expectedProjectServiceCount = getProjectServiceCount(p.Id);
        integer expectedProjectLocationCount = getProjectLocationCount(p.Id);

        //WHEN
        test.startTest();
        Id projectId = CloneUtil.CloneAll(p.Id);
        test.stopTest();

        //THEN
        List<Project__c> cPList = [SELECT Id from Project__c WHERE id = :projectId];
        QA.isTrue(cPList.size() > 0, 'Cloned project created');

        Integer resultProjectServiceCount = getProjectServiceCount(cPList[0].Id);
        QA.EQ(expectedProjectServiceCount, resultProjectServiceCount, 'The same number of project services created.' + resultProjectServiceCount);
        integer resultProjectLocationCount = getProjectLocationCount(p.Id);
        QA.EQ(expectedProjectLocationCount, resultProjectLocationCount, 'The same number of project locations created.' + resultProjectLocationCount);
    }

    static Map<String, List<ProjectServiceQuestionDefinedResponse__c>> groupResponses(String pId) {
        Set<Id> psIdSet = new Set<Id>();
        for(ProjectServiceQuestion__c s: 
            [SELECT Id from ProjectServiceQuestion__c
            WHERE ProjectService__r.Project__c = :pId]) {
            psIdSet.add(s.Id);
        }

        Map<String, List<ProjectServiceQuestionDefinedResponse__c>>
        answerMap = new Map<String, List<ProjectServiceQuestionDefinedResponse__c>>();
        List<ProjectServiceQuestionDefinedResponse__c> deleteList = new List<ProjectServiceQuestionDefinedResponse__c>();
        List<ProjectServiceQuestionDefinedResponse__c> items;
        
        for(ProjectServiceQuestionDefinedResponse__c a: [
            SELECT ProjectServiceQuestion__c, Id, Active__c FROM ProjectServiceQuestionDefinedResponse__c
            WHERE ProjectServiceQuestion__c in :psIdSet 
            AND ProjectServiceQuestion__r.Question__r.QuestionType__c = 'Single-Select List' ORDER BY ProjectServiceQuestion__c]) {
            if (answerMap.containsKey(a.ProjectServiceQuestion__c)) {
                items = answerMap.get(a.ProjectServiceQuestion__c);
            }
            else {
                items = new List<ProjectServiceQuestionDefinedResponse__c>();
            }
            items.add(a);
            answerMap.put(a.ProjectServiceQuestion__c, items);
        }
        return answerMap;
    }

    static void setupTestDataForProjectServiceQuestions(String pId) {

        Map<String, List<ProjectServiceQuestionDefinedResponse__c>> answerMap = groupResponses(pId);
        List<ProjectServiceQuestionDefinedResponse__c> deleteList = new List<ProjectServiceQuestionDefinedResponse__c>();
        List<ProjectServiceQuestionDefinedResponse__c> items;
        
        integer index = 0;
        integer cursor = 0;
        integer len = 0;

        List<ProjectServiceQuestionDefinedResponse__c> updates = 
            new  List<ProjectServiceQuestionDefinedResponse__c>();
         List<ProjectServiceQuestionDefinedResponse__c> deletes = 
         new  List<ProjectServiceQuestionDefinedResponse__c>();

        for(List<ProjectServiceQuestionDefinedResponse__c> aList: answerMap.values()) {
            len= aList.size() - 2;
            if (Math.mod(cursor, 2) == 0) {
            cursor++;
                for (integer i=0; i < len; i++) {
                    deletes.add(aList.get(i));                    
                }
            } else {
                for(integer i = 0; i < len; i++){
                 aList.get(i).Active__c = false;       
                 updates.add(aList.get(i));
                }
            }
        }
        if (deletes.isEmpty()){
            throw new CustomException('no answer to delete');
        }
        if (updates.isEmpty()){
         throw new CustomException('no answer to update');   
        }
        delete deletes;
        update updates;
    }



    static void ensureEachQuestionHasTwoAnswers(string pId) {
        Map<String, List<ProjectServiceQuestionDefinedResponse__c>> answerMap = groupResponses(pId);
        integer size = 0;

        for (List<ProjectServiceQuestionDefinedResponse__c> aList: answerMap.values()){
            size = 0;
            for(ProjectServiceQuestionDefinedResponse__c a: aList){
                if (a.Active__c == true) {
                    size++;
                }
            }
            if (size != 2) {
                throw new CustomException('there are more answers:' + string.valueOf(size));
            }
        }
    }

    @istest static void itShouldCloneProjectWithTwoTrueQuestionResponses() {
        //GIVEN
        Project__c p = [SELECT Id from Project__c LIMIT 1];
        setupTestDataForProjectServiceQuestions(p.Id);
        ensureEachQuestionHasTwoAnswers(p.Id);

        //WHEN
        test.startTest();
        String pId = CloneUtil.CloneAll(p.Id);
        test.stopTest();

        //THEN
        ensureEachQuestionHasTwoAnswers(pId);
    }
}