src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>An entry field that indicates the end date of the Project.</description>
        <inlineHelpText>The last date available to complete execution</inlineHelpText>
        <label>Project End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IsDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>A checkbox that indicates that the Project is deleted.</description>
        <inlineHelpText>If selected, the project is deleted.</inlineHelpText>
        <label>Is Deleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsExternalProject__c</fullName>
        <defaultValue>false</defaultValue>
        <description>A checkbox that indicates that the Project is external.</description>
        <inlineHelpText>If selected, the project is external.</inlineHelpText>
        <label>Is External Project</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LocationTotalCount__c</fullName>
        <description>A field that indicates the count of the locations added to the project.</description>
        <inlineHelpText>The count of the locations added to the project.</inlineHelpText>
        <label>Actual Location Count</label>
        <summaryFilterItems>
            <field>ProjectLocation__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Canceled</value>
        </summaryFilterItems>
        <summaryForeignKey>ProjectLocation__c.Project__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>OriginID__c</fullName>
        <description>A field that indicates the ID number for the origin of the Project.</description>
        <externalId>true</externalId>
        <label>Origin ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ProjectNumber__c</fullName>
        <displayFormat>{YY}{MM}{DD}{000000}</displayFormat>
        <inlineHelpText>this is help text in design</inlineHelpText>
        <label>Project Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>ProjectType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Type</label>
        <referenceTo>ProjectType__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>An entry field that indicates the start date of the Project.</description>
        <inlineHelpText>The date available to start execution</inlineHelpText>
        <label>Project Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planning</fullName>
                    <default>true</default>
                    <label>Planning</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Launched</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ended</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <recordTypes>
        <fullName>Booked</fullName>
        <active>true</active>
        <label>Booked</label>
    </recordTypes>
    <recordTypes>
        <fullName>Canceled</fullName>
        <active>true</active>
        <label>Canceled</label>
    </recordTypes>
    <recordTypes>
        <fullName>Closed</fullName>
        <active>true</active>
        <label>Closed</label>
    </recordTypes>
    <recordTypes>
        <fullName>Draft</fullName>
        <active>true</active>
        <label>Draft</label>
    </recordTypes>
    <recordTypes>
        <fullName>Ended</fullName>
        <active>true</active>
        <label>Ended</label>
    </recordTypes>
    <recordTypes>
        <fullName>Launched</fullName>
        <active>true</active>
        <label>Launched</label>
    </recordTypes>
    <recordTypes>
        <fullName>Planning</fullName>
        <active>true</active>
        <label>Planning</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ProjectType__c.object
<CustomObject>
    <description>Project Type defines a collection of Services and sets configuration options for a Project. Project Type is related to Project, Project Type Execution Company, Project Type Service, and Location Assignment.</description>
    <label>Project Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Types</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/classes/ProjectDashboardController.cls
public with sharing class ProjectDashboardController {
    Public string inputtext{get;set;}
    Public string SelectedET_Status{get;set;}
    Public string SelectedRS_Status{get;set;}
    public list<project__c> EventProjs{get;set;}
    public id projID{get;set;}

    /*{!URLFOR($Action.Project__c.Edit,a.id)}" styleClass="actionLink" rendered="{!OR(a.Status__c == 'Planning',a.Status__c == 'In Progress',a.Status__c == 'Booked',a.Status__c == 'Finished', a.Status__c == 'Rejected')} */

    public PageReference SetStatus() {
        PageReference ConfirmPage = new PageReference('/CancelProjectView');
        ConfirmPage.setRedirect(true);
        return ConfirmPage;
    }

    public list<SelectOption> getEventTrackStatus(){
       List<SelectOption> options = new List<SelectOption>();
       for(string str: new list<string>{'ET All','ET Draft','ET Pending Approval','ET Scheduled','ET Executed'})
       {
            options.add(new SelectOption(str,str));
       }
       return options;
    }

    public list<SelectOption> getRSStatus(){
       List<SelectOption> options = new List<SelectOption>();
       for(string str: new list<string>{'All','Planning','Pending Approval','Booked','In Progress','Finished','Canceled','Rejected'})
       {
            options.add(new SelectOption(str,str));
       }
       return options;
    }


    public List < Project__c > getMyProjects() {
        return [select id, name, status__c, owner.Id, owner.Name, OriginID__c,  StartDate__c, EndDate__c,  ProjectNumber__c, ProjectType__c,LocationTotalCount__c,isdeleted__c  from Project__c
            where ownerid = : UserInfo.getUserId() order by status__c, LastModifiedDate desc LIMIT 1000
        ];
    }

    public List < Project__c > getDraftProjects() {
        return [select id, name, status__c, owner.Id, owner.Name,  StartDate__c, EndDate__c, ProjectNumber__c, ProjectType__c, LocationTotalCount__c from Project__c
            where status__c = 'Planning' and isdeleted__c=false
            order by LastModifiedDate desc LIMIT 1000
        ];
    }

    public List < Project__c > getExternalProjects() {
        return [select id, name, status__c, owner.Id, owner.Name,  StartDate__c, EndDate__c, ProjectNumber__c, ProjectType__c, OriginID__c, LocationTotalCount__c from Project__c
            where IsExternalProject__c = true
            order by LastModifiedDate desc LIMIT 1000
        ];
    }

    public List < Project__c > getPendingProjects() {
        return [select id, name, status__c, owner.Id, owner.Name,  StartDate__c, EndDate__c, ProjectNumber__c, ProjectType__c, LocationTotalCount__c, OriginID__c  from Project__c
            where status__c = 'Pending Approval'
            order by LastModifiedDate desc LIMIT 1000
        ];
    }

    public List < Project__c > getScheduledProjects() {
        return [select id, name, status__c, owner.Id, owner.Name,  StartDate__c, EndDate__c, ProjectNumber__c, ProjectType__c, LocationTotalCount__c from Project__c
            where status__c = 'Booked'
            order by LastModifiedDate desc LIMIT 1000
        ];
    }
    
    public List < Project__c > getlaunchedProjects() {
        return [select id, name, status__c, owner.Id, owner.Name,  StartDate__c, EndDate__c, ProjectNumber__c, ProjectType__c, LocationTotalCount__c from Project__c
            where status__c = 'Launched'
            order by LastModifiedDate desc LIMIT 1000
        ];
    }

    public List < Project__c > getExecutedProjects() {
        return [select id, name, status__c, owner.Id, owner.Name,  StartDate__c, EndDate__c, ProjectNumber__c, ProjectType__c, LocationTotalCount__c from Project__c
            where status__c = 'Ended'  LIMIT 1000
        ];
    }

    public List < Project__c > getInProgressProjects() {
        return [select id, name, status__c, owner.Id, owner.Name,  StartDate__c, EndDate__c, ProjectNumber__c, ProjectType__c, LocationTotalCount__c from Project__c
            where status__c = 'In Progress'
            order by LastModifiedDate desc LIMIT 1000
        ];
    }

    public List < Project__c > getCanceledProjects() {
        return [select id, name, status__c, owner.Id, owner.Name,  StartDate__c, EndDate__c, ProjectNumber__c, ProjectType__c, LocationTotalCount__c from Project__c
            where status__c = 'Canceled'
            order by LastModifiedDate desc LIMIT 1000
        ];
    }

    public List<Project__c> getRejectedProjects() {
        return [select id, name, status__c, owner.Id, owner.Name,  StartDate__c, EndDate__c, ProjectNumber__c, ProjectType__c, LocationTotalCount__c from Project__c
            where status__c = 'Closed'
            order by LastModifiedDate desc LIMIT 1000
        ];
    }


    public List<Project__c> getDeletedProjects() {
        return [select id, name, status__c, owner.Id, owner.Name,  StartDate__c, EndDate__c, ProjectNumber__c, ProjectType__c, LocationTotalCount__c from Project__c
            where status__c = 'Planning' and isdeleted__c=true order by LastModifiedDate desc LIMIT 1000];
    }
    public void cloneProject(){
        /*Id cloneProj;// = CloneUtil.CloneAll(projID);
        PageReference pageRef = new PageReference('/apex/ProjectDetailsView?id=' + cloneProj);
        pageRef.setRedirect(true);
        return pageRef;*/
    }

}