src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planning</fullName>
                    <default>true</default>
                    <label>Planning</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Launched</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ended</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/DevUtilTest.cls
@isTest
public class DevUtilTest {
    public static testMethod void test_deleteProject() {
        List<Project__c> projects = new List<Project__c>();
        Project__c project = TestUtil.generateFullTestProject(ProjectType.MD, Date.today(),Date.today().addDays(2)); 
        DevUtil.deleteProject(project.id);
        projects = [SELECT Id From Project__c where id = :project.id];
        system.assert(projects.size() == 0);
    }

    public static testMethod void test_updateProjectReserved() {
        List<Project__c> projects = new List<Project__c>();
        Project__c project = TestUtil.generateFullTestProject(ProjectType.MD, Date.today(),Date.today().addDays(2)); 
        DevUtil.UpdateProjectStatus(project.id,'reserved');
        project = [SELECT status__c From Project__c where id = :project.id];
        system.assert(project.status__c != 'reserved');
    }

    public static testMethod void test_updateProject() {
        List<Project__c> projects = new List<Project__c>();
        Project__c project = TestUtil.generateFullTestProject(ProjectType.MD, Date.today(),Date.today().addDays(2)); 
        DevUtil.UpdateProjectStatus(project.id,'open');
        project = [SELECT status__c From Project__c where id = :project.id];
        system.assert(project.status__c == 'open');
    }
    
    public static testMethod void test_deleteProjects() {
        List<Project__c> projects = new List<Project__c>();
        Project__c project = TestUtil.generateFullTestProject(ProjectType.MD, Date.today(),Date.today().addDays(2)); 
        projects.add(project);
        DevUtil.deleteProjects(projects);
        projects = [SELECT Id From Project__c where id = :project.id];
        system.assert(projects.size() == 0);
    }    
}