src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <fields>
        <fullName>ApexJobName__c</fullName>
        <description>A field that indicates the apex job name of the Project.</description>
        <inlineHelpText>The apex job name of the project</inlineHelpText>
        <label>ApexJobName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BatchProcessId__c</fullName>
        <description>A field that indicates the ID number of the Batch Process for the Project.</description>
        <inlineHelpText>The ID number for the batch process.</inlineHelpText>
        <label>BatchProcessId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ProjectService__c.object
<CustomObject>
    <description>Project Service relates a Service to a Project and is a container used to define the instance of a Service for a specific Project. Project Service is related to Project, Job, Project Service Attribute, Project Service Certification, Project Service Equipment, Project Service Material, Project Service Question, Project Service Target, and Service.</description>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>ProjectServices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Service</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectServiceAttribute__c.object
<CustomObject>
    <description>Relates a Service Attribute to a Project Service and prepopulates default values. Service Attribute is related to Service, Project Service Attribute, and Attribute.</description>
    <fields>
        <fullName>AttchFileName__c</fullName>
        <label>AttchFileName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AttributeType__c</fullName>
        <formula>TEXT(Attribute__r.AttributeType__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AttributeType</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AttributeValue__c</fullName>
        <label>Attribute Value</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>IsClonedAttachment__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Cloned Attachment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProjectService__c</fullName>
        <label>Project Service</label>
        <referenceTo>ProjectService__c</referenceTo>
        <relationshipLabel>Project Service Attributes</relationshipLabel>
        <relationshipName>Project_Service_Attributes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Service Attribute</label>
    <nameField>
        <displayFormat>PSA-{00000000}</displayFormat>
        <label>Project Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Service Attributes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/classes/CloneProjectQueuebleJob.cls
public class CloneProjectQueuebleJob implements Queueable, Database.RaisesPlatformEvents{

    private Id projectId {get; Set;}

    public CloneProjectQueuebleJob(Id projectId) {
        this.projectId = projectId;
    }

    public void execute(QueueableContext context) {
        try {

            //clone project and invoke batch job to process ps attachments
            Id clonedProjectId = CloneUtil.CloneAll(projectId);

            List<ProjectServiceAttribute__c> psas = [SELECT Id, AttchFileName__c, AttributeValue__c, IsClonedAttachment__c FROM ProjectServiceAttribute__c WHERE  ProjectService__r.Project__c = :clonedProjectId AND (AttributeType__c = 'Photo' OR AttributeType__c = 'File')];
            for (ProjectServiceAttribute__c psa : psas) {
                if (psa.AttributeValue__c != null && psa.AttributeValue__c != '') {
                    String[] arr = psa.AttributeValue__c.split('=');
                    List<Attachment> oldAttachments = [select id, name, body from Attachment where Id = :arr[0] LIMIT 1];

                    if (oldAttachments.isEmpty()) continue;

                    Attachment oldAttachment = oldAttachments[0];

                    Attachment newAttachment = new Attachment(name = oldAttachment.name, body = oldAttachment.body, parentid = this.projectId);
                    insert newAttachment;
                    string imageflag = '';
                    if (arr.size() > 1) {
                        imageflag = '=' + arr[1];
                    }
                    psa.AttributeValue__c = string.valueof(newAttachment.Id) + imageflag;
                }
            }
            update psas;


            Project__c project = [SELECT Id, Name, BatchProcessId__c, ApexJobName__c, RecordTypeId
                                  FROM Project__c WHERE Id = :clonedProjectId];
            BatchClonedProjectAttachmentsHandler batch = new BatchClonedProjectAttachmentsHandler(clonedProjectId);
            string batchProcessId = Database.ExecuteBatch(batch, 1);

            ProjectActionsHelper.LockProject(project, 'Clone Project', batchProcessId);
            TriggerUtil.skipProjectTrigger = true;
            update project;
            
        } catch (Exception ex) {
            throw new CustomException(ex.getMessage() + ': line ' + ex.getLineNumber());
        }
    }
}