src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <fields>
        <fullName>BookBudgetedOnly__c</fullName>
        <defaultValue>false</defaultValue>
        <description>A checkbox that indicates whether the Project was book budgeted only.</description>
        <inlineHelpText>If selected, the project was book budgeted only.</inlineHelpText>
        <label>BookBudgetedOnly</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>An entry field that indicates the end date of the Project.</description>
        <inlineHelpText>The last date available to complete execution</inlineHelpText>
        <label>Project End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ProjectType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Type</label>
        <referenceTo>ProjectType__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Retailer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Retailer</label>
        <referenceTo>Retailer__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>An entry field that indicates the start date of the Project.</description>
        <inlineHelpText>The date available to start execution</inlineHelpText>
        <label>Project Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planning</fullName>
                    <default>true</default>
                    <label>Planning</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Launched</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ended</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UpdateSequence__c</fullName>
        <label>Update Sequence</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <recordTypes>
        <fullName>Booked</fullName>
        <active>true</active>
        <label>Booked</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ProjectType__c.object
<CustomObject>
    <description>Project Type defines a collection of Services and sets configuration options for a Project. Project Type is related to Project, Project Type Execution Company, Project Type Service, and Location Assignment.</description>
    <label>Project Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Types</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/Retailer__c.object
<CustomObject>
    <description>Retailer stores the retailers for the system. Retailer is related to Location, Retailer Service, Retailer Service Certification, and Retailer Service Equipment.</description>
    <label>Retailer</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Retailers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/AppUtilTest.cls
@isTest
public class AppUtilTest {
    
    public static testMethod void test_All(){
        TriggerUtil.SkipAllTriggers();
        Project__c project = TestUtil.generateFullTestProject(ProjectType.MD, Date.today().addDays(10), Date.today().addDays(20));
        
        Test.startTest();
        ProjectScheduler batch = new ProjectScheduler([SELECT Id,Name, StartDate__c, EndDate__c, ProjectType__c,  ProjectType__r.Name, Status__c, BookBudgetedOnly__c FROM Project__c WHERE ID = :project.Id]);
        Database.executeBatch(batch);
        Test.stopTest();
        /*
        Boolean hasReserved = AppUtil.projectHasReserved(project);
        system.assertEquals(hasReserved, true);
        */
        project = [Select Id, UpdateSequence__c, Status__c from Project__c where Id =: project.Id];
        project.Status__c = 'Booked';
        update project;
        Decimal prevVersion = project.UpdateSequence__c;
        Set<id> projectIds = new Set<id>();
        projectIds.add(project.Id);
        AppUtil.UpdateProjectVersion(projectIds);
        project = [Select Id, UpdateSequence__c, Status__c from Project__c where Id =: project.Id];
        Decimal newVersion = project.UpdateSequence__c;
        
        //system.assertNotEquals(prevVersion, newVersion);
        
        Boolean hasLeadTime = AppUtil.hasProjectLeadTimeByProjectId(project.Id);
        system.assert(hasLeadTime != null);
        
        List<Retailer__c> retailers = AppUtil.getProfileRetailers();
        system.assert(retailers.size() > 0);
        
        
        Integer mcv = AppUtil.GetMaxContactVersion();
        system.assert(mcv != null);
        
        Boolean isloadTime = Apputil.isScheduledWithLoadTime(project.Id);
        system.assert(isloadTime != null);
        
        Boolean isLocked = Apputil.isProjectLocked(project);
        system.assert(isLocked != null);

        
    }

}