src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planning</fullName>
                    <default>true</default>
                    <label>Planning</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Launched</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ended</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <recordTypes>
        <fullName>Booked</fullName>
        <active>true</active>
        <label>Booked</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/ProjectSubmitRequestModelTest.cls
@isTest
private class ProjectSubmitRequestModelTest
{
    @testSetup
    static void setup() {
        TriggerUtil.skipAllTriggers();
        TestDataUtil.init();
        Date startDate = (Datetime.now()).addDays(10).date();
        Date endDate = (Datetime.now()).addDays(20).date();
        TestProject tP = TestProject.create('demo',startDate, endDate)
            .addAllWithoutJobAttempts();
        tP.TestProjectServiceList[0].addAll();
    }
    
	@isTest
	static void itShouldGetProjectWithoutError()
	{
		// Given
        Project__c p = TestProject.getProjects()[0];
        ProjectSubmitRequestModel model = new ProjectSubmitRequestModel();
        Map<String,Object> parameters = new Map<String,Object>();
        parameters.put('projectId', p.Id);

		// When
        test.startTest();
        Map<String,Object> result = (Map<String,Object>) model.get(parameters);
        test.stopTest();

		// Then
        QA.EQ(CONSTANTS.STATUS_WARN, result.get('status'), JSON.serialize(result));
	}

    @isTest
    static void itShouldSubmitProjectWithoutError()
    {
        // Given
        Project__c p = TestProject.getProjects()[0];
        ProjectSubmitRequestModel model = new ProjectSubmitRequestModel();
        Map<String,Object> parameters = new Map<String,Object>();
        parameters.put('projectId', p.Id);

        // When
        test.startTest();
        Map<String,Object> result = (Map<String,Object>) model.modify(parameters);
        test.stopTest();

        // Then
        p = TestProject.getProjects()[0];
        QA.EQ(CONSTANTS.STATUS_WARN, result.get('status'), JSON.serialize(result));
        QA.EQ(CONSTANTS.PROJECT_STATUS_BOOKED, p.Status__c, 'project booked.');
    }
}