src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <fields>
        <fullName>OverrideAccountAndServiceAccess__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Override Account And Service Access</label>
        <type>Checkbox</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ProjectAccount__c.object
<CustomObject>
    <description>Project Account maps an Account to a Project and defines how the Account will be billed. Project Account is related to Project, Account, and Account Address.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please make sure this account&apos;s &apos;Can Request Project&apos; setting is enabled.</errorMessage>
            <filterItems>
                <field>Account.CanRequestProjects__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Project Accounts</relationshipLabel>
        <relationshipName>Project_Accounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Project_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Account</label>
    <nameField>
        <displayFormat>PA-{0000000}</displayFormat>
        <label>Project Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectAccountServiceAccess__c.object
<CustomObject>
    <description>ProjectAccountServiceAccess</description>
    <fields>
        <fullName>Account__c</fullName>
        <formula>CASESAFEID(ProjectAccount__r.Account__r.Id)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProjectAccount__c</fullName>
        <label>Project Account</label>
        <referenceTo>ProjectAccount__c</referenceTo>
        <relationshipLabel>Project Account Service Accesses</relationshipLabel>
        <relationshipName>Project_Account_Service_Accesses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ProjectService__c</fullName>
        <label>Project Service</label>
        <referenceTo>ProjectService__c</referenceTo>
        <relationshipLabel>Project Account Service Accesses</relationshipLabel>
        <relationshipName>Project_Account_Service_Accesses</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Account Service Accesses</relationshipLabel>
        <relationshipName>Project_Account_Service_Accesses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Account Service Access</label>
    <nameField>
        <displayFormat>AA-{00000}</displayFormat>
        <label>ProjectAccountServiceAccess Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Account Service Accesses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectService__c.object
<CustomObject>
    <description>Project Service relates a Service to a Project and is a container used to define the instance of a Service for a specific Project. Project Service is related to Project, Job, Project Service Attribute, Project Service Certification, Project Service Equipment, Project Service Material, Project Service Question, Project Service Target, and Service.</description>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>ProjectServices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <formula>IF( 

OR(ISNULL(ServiceTitle__c), isblank(ServiceTitle__c)),
Service__r.Name, 
ServiceTitle__c &amp;&quot; - &quot;&amp; Service__r.Name  

)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Title</label>
        <type>Text</type>
    </fields>
    <label>Project Service</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/classes/ProjectServiceRequest.cls
public with sharing class ProjectServiceRequest extends LightningRequestBase {
    String AppUsage {get;set;}

    public override Object filter(Object parameters) {
        String projectId = parseProjectId(parameters);
        this.AppUsage = getParamString(parameters, 'usage');

        if(isCommunityRequest() && isSecurityAccessOverride(projectId)){
            return getAccessServices(projectId);
        }

        return getServices(projectId);
    }

    Boolean isCommunityRequest(){
        return (this.AppUsage == 'Community Viewer' || this.AppUsage == 'Retailer')
            ? true: false;
    }

    String getParamString(Object parameters, String key){
        Map<String,object> query = (Map<String,Object>) parameters;
        return LightningRequestHelper.parseString(query.get(key));
    }

    String parseProjectId(Object parameters){
        Map<String,object> query = (Map<String,Object>) parameters;
        String projectId = LightningRequestHelper.parseString(query.get('projectId'));
        
        if(String.isEmpty(projectId)){
            throw new AuraHandledException('The project id is not specified.');
        }

        return projectId;
    }

    List<List<String>> getServices(String projectId){
        List<String> item;
        List<List<String>> result = new List<List<String>>();
        
        for(ProjectService__c ps: [SELECT Id, Title__c FROM ProjectService__c WHERE Project__c=:projectId]){
            item = new List<String>();
            item.add(ps.Id);
            item.add(ps.Title__c);
            result.add(item);
        }
        return result;
    }

    List<List<String>> getAccessServices(String projectId){
        List<String> item;
        List<List<String>> result = new List<List<String>>();
        String accountId = AppUtil.getUserAccountId();

        for(ProjectService__c ps: [SELECT Id, Title__c FROM ProjectService__c WHERE Project__c=:projectId AND Id in (SELECT ProjectService__c FROM ProjectAccountServiceAccess__c WHERE Project__c=:projectId AND ProjectAccount__r.Account__c=:accountId)]){
            item = new List<String>();
            item.add(ps.Id);
            item.add(ps.Title__c);
            result.add(item);
        }
        return result;
    }

    Boolean isSecurityAccessOverride(String projectId){
        Project__c p = [SELECT OverrideAccountAndServiceAccess__c FROM Project__c WHERE Id=:projectId LIMIT 1];
        return (p != null && p.OverrideAccountAndServiceAccess__c == true) ? true : false;
    }
}