src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planning</fullName>
                    <default>true</default>
                    <label>Planning</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Launched</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ended</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/UIConfig__c.object
<CustomObject>
    <description>UIConfig defines how specific fields are rendered within the UI on the Project screens.</description>
    <fields>
        <fullName>Access__c</fullName>
        <label>Access</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Editable</fullName>
                    <color>#FF6600</color>
                    <label>Editable</label>
                </value>
                <value>
                    <fullName>Hidden</fullName>
                    <color>#999999</color>
                    <label>Hidden</label>
                </value>
                <value>
                    <fullName>Visible</fullName>
                </value>
                <value>
                    <fullName>Edit</fullName>
                    <isActive>false</isActive>
                    <label>Edit</label>
                </value>
                <value>
                    <fullName>Read</fullName>
                    <isActive>false</isActive>
                    <label>Read</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Ended</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Launched</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Planning</fullName>
                </value>
                <value>
                    <fullName>Reported</fullName>
                </value>
                <value>
                    <fullName>Started</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UIElement__c</fullName>
        <label>Unique Key</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>UI_Element__c</fullName>
        <label>UI Element</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>UIConfig</label>
    <nameField>
        <displayFormat>UI-{000}</displayFormat>
        <label>UIConfig Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UIConfig</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/UIConfig.cls
public class UIConfig {
    
    public final static Map<String, Boolean> HiddenElements {get;set;}
    static 
    {
    	HiddenElements = getHiddenUIElements();
    }    
    
    public static Map<String, boolean> getHiddenUIElements()
    {
        Map<String, boolean> results = new Map<String, boolean>();
        List<UIConfig__c> uic = [SELECT Id, Status__c, UIElement__c,Access__c  FROM UIConfig__c WHERE Access__c = 'Hidden'];
        for(UIConfig__c c:uic){
            if (String.isNotBlank(c.UIElement__c))
            {
                results.put(c.UIElement__c,true);
            }
        }
        return results;
    }        
    
    public static boolean isEditale(String status, String elementName){
        List<UIConfig__c> uic = [SELECT Id, UI_Element__c,Access__c FROM UIConfig__c WHERE UI_Element__c = :elementName AND Status__c =:status];
        if(status == 'Create' || (uic.size() > 0 && uic[0].Access__c == 'Editable')){
            return true;
        }
        return false;
    }
    
    public static Map<String, boolean> getHiddenElements(String status){
        Map<String, boolean> results = new Map<String, boolean>();
        List<UIConfig__c> uic = [SELECT Id, UI_Element__c,Access__c  FROM UIConfig__c WHERE Access__c = 'Hidden' 
                        AND Status__c =:status];
        for(UIConfig__c c:uic){
            if (String.isNotBlank(c.UI_Element__c))
            {
                results.put(c.UI_Element__c,true);
            }
        }
        return results;
    }    

    public static Boolean checkFieldHidden(String status, String uiElementName){
        string concatElement = uiElementName + '-' + status;
        return HiddenElements.get(concatElement) != null? True : False;
    }
    
    public static Map<String, boolean> getHiddenElements(){
        Map<String, boolean> results = new Map<String, boolean>();
        List<UIConfig__c> uic = [SELECT Id, Status__c, UI_Element__c,Access__c  FROM UIConfig__c WHERE Access__c = 'Hidden'];
        for(UIConfig__c c:uic){
            if (String.isNotBlank(c.UI_Element__c))
            {
                results.put(c.UI_Element__c,true);
            }
        }
        return results;
    }    


    public static Map<String, boolean> getEditableElements(String status){
        List<UIConfig__c> uic = [SELECT Id, UI_Element__c,Access__c  FROM UIConfig__c WHERE Access__c = 'Editable' 
                                 AND Status__c =:status];
        Map<String, boolean> results = new Map<String, boolean>();

        for(UIConfig__c c:uic){
            if (String.isNotBlank(c.UI_Element__c))
            {
                results.put(c.UI_Element__c,true);
            }
        }
        return results;
        
    }


    public static Map<String, boolean> isEditale(String status, Set<String> elementNames){
        List<UIConfig__c> uic = [SELECT Id, UI_Element__c,Access__c  FROM UIConfig__c WHERE UI_Element__c = :elementNames AND Status__c =:status];
        Map<String, boolean> results = new Map<String, boolean>();
        Boolean result = (status == 'Create') ? true : false;
        for(String ename :elementNames){
            results.put(ename,result);
        }
        if(status == 'Create'){
            return results;       
        }
        system.debug('status::::'+status);
        for(UIConfig__c c:uic){
            if(status == 'Create' || (c.Access__c == 'Editable' && results.containsKey(c.UI_Element__c))){
                results.put(c.UI_Element__c,true);
            }
        }
        return results;
    }
    
    public static Map<String, boolean> isHidden(String status, Set<String> elementNames){
        Map<String, boolean> results = new Map<String, boolean>();
        for(String ename :elementNames){
            results.put(ename,false);
        }
        List<UIConfig__c> uic = [SELECT Id, UI_Element__c,Access__c  FROM UIConfig__c WHERE UI_Element__c = :elementNames AND Access__c = 'Hidden' AND Status__c =:status];
        for(UIConfig__c c:uic){
            if(results.containsKey(c.UI_Element__c)){
                results.put(c.UI_Element__c,true);
            }
        }
        return results;
    }
    
    
    public static Map<String, boolean> getProjectEditableFields(String status){
        List<UIConfig__c> uic = [SELECT Id, UI_Element__c,Access__c  FROM UIConfig__c WHERE Status__c =:status AND Access__c = 'Editable' AND UI_Element__c LIKE 'Project__c.%'];
        Map<String, boolean> results = new Map<String, boolean>();
        for(UIConfig__c c:uic){
            results.put(c.UI_Element__c,true);
        }
        if(results.size() == 0){
            return null;    
        }
        return results;
    }
    
    public static boolean isVisible(String status, String elementName){
        List<UIConfig__c> uic = [SELECT Id, UI_Element__c,Access__c FROM UIConfig__c WHERE UI_Element__c = :elementName];
        if(uic.size()>0 && uic[0].Access__c == 'Hidden'){
            return false;
        }
        return true;
    }
    
    public static Map<String, boolean> isVisible(String status, Set<String> elementNames){
        List<UIConfig__c> uic = [SELECT Id, UI_Element__c,Access__c FROM UIConfig__c WHERE UI_Element__c = :elementNames];
        Map<String, boolean> results = new Map<String, boolean>();
        for(String ename :elementNames){
            results.put(ename, true);
        }
        for(UIConfig__c c:uic){
            if(c.Access__c == 'Hidden' && results.containsKey(c.UI_Element__c)){
                results.put(c.UI_Element__c, false);
            }
        }
        return results;
    }

}