src_old/objects/ProjectServiceAttribute__c.object
<CustomObject>
    <description>Relates a Service Attribute to a Project Service and prepopulates default values. Service Attribute is related to Service, Project Service Attribute, and Attribute.</description>
    <fields>
        <fullName>AttachmentURL__c</fullName>
        <label>Attachment URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>AttchFileName__c</fullName>
        <label>AttchFileName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AttributeNumber__c</fullName>
        <formula>ServiceAttribute__r.AttributeNumber__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Attribute Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AttributeOrder__c</fullName>
        <formula>ServiceAttribute__r.AttributeOrder__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Attribute Order</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AttributeTitle__c</fullName>
        <formula>Attribute__r.AttributeTitle__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Attribute Title</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AttributeType__c</fullName>
        <formula>TEXT(Attribute__r.AttributeType__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AttributeType</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AttributeValue__c</fullName>
        <label>Attribute Value</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <formula>Attribute__r.Description__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Description</label>
        <type>Text</type>
    </fields>
    <label>Project Service Attribute</label>
    <nameField>
        <displayFormat>PSA-{00000000}</displayFormat>
        <label>Project Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Service Attributes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/classes/PSAttributeWrapper.cls
public class PSAttributeWrapper {
    @AuraEnabled
    public string RecordID{get; set;}     
    @AuraEnabled
    public string Attributename{get; set;}
    @AuraEnabled
    public string AttributeNumber{get; set;}
    @AuraEnabled
    public decimal AttributeOrder{get; set;}
    @AuraEnabled
    public string AttributeTitle{get; set;}
    @AuraEnabled
    public string AttributeType{get; set;}
    @AuraEnabled
    public string AttributeValue{get; set;}    
    @AuraEnabled
    public string AttachFile{get; set;} 
    @AuraEnabled
    public string AttachFileLink{get; set;} 
    @AuraEnabled
    public String AttachmentURL{get;set;}
  
    
    public PSAttributeWrapper(){        
    }

    public PSAttributeWrapper(ProjectServiceAttribute__c psa)
    {
        RecordID = psa.ID;
        Attributename = psa.description__c;
        AttributeNumber= psa.AttributeNumber__c;
        AttributeOrder = psa.AttributeOrder__c;
        AttributeTitle = psa.AttributeTitle__c;
        AttributeType = psa.AttributeType__c;
        AttributeValue = (psa.AttributeValue__c!=null)?psa.AttributeValue__c:''; 
        AttachFile = psa.AttchFileName__c;
        AttachmentURL = psa.AttachmentURL__c;
 
        if(psa.AttributeValue__c!=null)
            AttachFileLink = '/servlet/servlet.FileDownload?file=' +string.valueOf(psa.AttributeValue__c).substringBefore('=') ;
        else
            AttachFileLink ='';
    }
    
}