src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <fields>
        <fullName>IsJobManualRegenReqd__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The check box will be set when a the Job Manual has to be generated.</description>
        <inlineHelpText>The check box will be set when a the Job Manual has to be generated.</inlineHelpText>
        <label>Regenerate Job Manual</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planning</fullName>
                    <default>true</default>
                    <label>Planning</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Launched</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ended</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ProjectService__c.object
<CustomObject>
    <description>Project Service relates a Service to a Project and is a container used to define the instance of a Service for a specific Project. Project Service is related to Project, Job, Project Service Attribute, Project Service Certification, Project Service Equipment, Project Service Material, Project Service Question, Project Service Target, and Service.</description>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>ProjectServices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Executed</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Variant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Variant</label>
        <referenceTo>Variant__c</referenceTo>
        <relationshipLabel>Project Services</relationshipLabel>
        <relationshipName>Project_Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Service</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectServiceQuestion__c.object
<CustomObject>
    <description>Relates a Question to a Project Service. Questions from Service Question are added by default when a Service is added to a Project Service. Additional Questions can be added. Project Service Question is related to Project Service Question, Question, and Question Variant.</description>
    <fields>
        <fullName>ProjectService__c</fullName>
        <label>Project Service</label>
        <referenceTo>ProjectService__c</referenceTo>
        <relationshipLabel>ProjectServiceQuestions</relationshipLabel>
        <relationshipName>ProjectServiceQuestions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>QuestionNumber__c</fullName>
        <label>Question Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>QuestionText__c</fullName>
        <formula>Question__r.QuestionText__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Question Text</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QuestionType__c</fullName>
        <formula>TEXT(Question__r.QuestionType__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Question Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QuestionVariant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question Variant</label>
        <referenceTo>QuestionVariant__c</referenceTo>
        <relationshipLabel>Project Service Questions</relationshipLabel>
        <relationshipName>Project_Service_Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Question__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>ProjectServiceQuestions</relationshipLabel>
        <relationshipName>ProjectServiceQuestions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ServiceQuestion__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Service Question</label>
        <type>Checkbox</type>
    </fields>
    <label>Project Service Question</label>
    <nameField>
        <displayFormat>PSQ-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Service Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectServiceQuestionDefinedResponse__c.object
<CustomObject>
    <description>Relates a Service Question Defined Response to a Project Service Question. Project Service Question Def Response is related to Project Service Question, Question, Question Defined Response, and Question Defined Repsonse Variant.</description>
    <fields>
        <fullName>DefinedResponseOrder__c</fullName>
        <formula>QuestionDefinedResponse__r.DefinedResponseOrder__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Defined Response Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProjectServiceQuestion__c</fullName>
        <label>Project Service Question</label>
        <referenceTo>ProjectServiceQuestion__c</referenceTo>
        <relationshipName>ProjectServiceQuestionDefResponses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>QuestionDefinedResponse__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question Defined Response</label>
        <referenceTo>QuestionDefinedResponse__c</referenceTo>
        <relationshipName>Project_Service_Question_Def_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <formula>ProjectServiceQuestion__r.Question__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Question</label>
        <type>Text</type>
    </fields>
    <label>Project Service Question Def Response</label>
    <nameField>
        <displayFormat>PSQDR-{00000000}</displayFormat>
        <label>Project Service Question  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Service Question Def Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/Question__c.object
<CustomObject>
    <description>Question stores all of the questions stored in the system and defines the type of question (e.g. Date, Text, Y/N) and if the question is related to targets. Question is related to Question Defined Response, Question Variant.</description>
    <fields>
        <fullName>QuestionText__c</fullName>
        <label>Question Text</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QuestionType__c</fullName>
        <label>Question Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Currency</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Multi-Select List</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Photo</fullName>
                </value>
                <value>
                    <fullName>Signature</fullName>
                </value>
                <value>
                    <fullName>Single-Select List</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                </value>
                <value>
                    <fullName>Time</fullName>
                </value>
                <value>
                    <fullName>Yes/No</fullName>
                </value>
                <value>
                    <fullName>Group</fullName>
                </value>
                <value>
                    <fullName>Barcode</fullName>
                </value>
                <value>
                    <fullName>Multi Select Target</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/objects/QuestionDefinedResponse__c.object
<CustomObject>
    <description>Question Defined Response defines the acceptable responses for a Question. Question Defined Response is related to Question and Question Defined Response Variant.</description>
    <fields>
        <fullName>DefinedResponseOrder__c</fullName>
        <label>Defined Response Order</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Question Defined Response (SurveyQuestionBank)</relationshipLabel>
        <relationshipName>Question_Defined_Response1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Question Defined Response</label>
    <nameField>
        <displayFormat>QBDR-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Defined Response</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/QuestionDefinedResponseVariant__c.object
<CustomObject>
    <description>Question Defined Response Variant defines a variant to a Question Defined Response, such as language. Question Defined Response Variant is related to Question Defined Response and Variant.</description>
    <fields>
        <fullName>QuestionDefinedResponse__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question Defined Response</label>
        <referenceTo>QuestionDefinedResponse__c</referenceTo>
        <relationshipName>Defined_Responses_Variant</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Variant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Variant</label>
        <referenceTo>Variant__c</referenceTo>
        <relationshipName>Defined_Responses_Variant</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Question Defined Response Variant</label>
    <nameField>
        <displayFormat>QDRVAR-{000000000}</displayFormat>
        <label>Defined Response Text Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Defined Responses Variant</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/objects/QuestionVariant__c.object
<CustomObject>
    <description>Question Variant defines a variant to a Question, such as language. Question Variant is related to Question and Variant.</description>
    <fields>
        <fullName>QuestionText__c</fullName>
        <label>Question Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipName>QuestionsVariant</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Variant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Variant</label>
        <referenceTo>Variant__c</referenceTo>
        <relationshipName>QuestionsVariant</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Question Variant</label>
    <nameField>
        <displayFormat>QVAR-{000000000}</displayFormat>
        <label>QuestionVariant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions Variant</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/objects/ServiceQuestion__c.object
<CustomObject>
    <description>Service Question relates one or more Questions to a Service and defines how the questions are rendered when building a Project Service. Service Question is related to Service, Question, and Project Service Question.</description>
    <fields>
        <fullName>QuestionNumber__c</fullName>
        <label>Question Number</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>QuestionText__c</fullName>
        <formula>Question__r.QuestionText__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Question Text</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QuestionType__c</fullName>
        <formula>TEXT(Question__r.QuestionType__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Question Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Service Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Service Question</label>
    <nameField>
        <displayFormat>SQ-{00000000}</displayFormat>
        <label>Service Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/classes/SurveyQuestionProjectServiceController.cls
public with sharing class SurveyQuestionProjectServiceController {

    public string param_surveyQuestionID {get;set;}
    public string project_serviceID {get; set;}
    public List<ProjectServiceQuestion__c> surveyquestions {get; set;}
    public List<question> questions {get; set;}
    public Boolean showAddEditSQButton {get;private set;}
    public Boolean isExternalProject {get;private set;}
    public ProjectServiceQuestion__c newsq {get; set;}
    public ProjectService__c ps {get; set;}    
    public Question__c newsqb {get; set;}
    public Project__c proj {get; set;} 

    public Map<String,Boolean> editableMap {get;set;}

    private void addMessage(ApexPages.Severity severity, String message){
        Apexpages.addMessage(new ApexPages.Message(severity, message));
    }

    public class question
    {
        public Id       id                   {get; set;}
        public String   name                 {get; set;}
        public String   qtext                 {get; set;}        
        public Integer  qno                  {get; set;}
        public String   qt                   {get; set;}
        public Boolean  fq                   {get; set;}    
        public Boolean  lq                   {get; set;}            
        public Boolean  tq                   {get; set;}
        public Id       sqb                  {get; set;}        
                
        public question(ProjectServiceQuestion__c sq)
        {
            id = sq.id;
            name = sq.name;
            qtext = sq.QuestionText__c;
            qno = Integer.valueOf(sq.QuestionNumber__c);
            qt = sq.QuestionType__c;
            fq = false;
            lq = false;
            tq = sq.ServiceQuestion__c;
            sqb = sq.Question__c;
        } 
    }

    public SurveyQuestionProjectServiceController() {
    }


    public SurveyQuestionProjectServiceController(ApexPages.StandardController controller) {
        project_serviceID = ApexPages.currentPage().getParameters().get('id');
        ps = [Select id, name, variant__c, Project__c from projectservice__c where id = :project_serviceID];
        
        System.debug('ps : ' + project_serviceID);
        
        if (project_serviceID == null)
        {
            project_serviceID = 'a0Hj0000004u4Jb';
        }
        
        newsq = new ProjectServiceQuestion__c();
        newsqb = new Question__c();
        
        getSurveyQuestions();
        
        proj = [SELECT Id, Status__c,IsJobManualRegenReqd__c FROM Project__c WHERE Id IN (Select Project__c from ProjectService__c where Id = :project_serviceID ) LIMIT 1];
        
        Set<String> editableFields = new Set<String>{'Project__c.RL_Questions'};
        editableMap = UIConfig.isEditale(proj.Status__c, editableFields);
        showAddEditSQButton = editableMap.get('Project__c.RL_Questions') && Schema.sObjectType.ProjectServiceQuestion__c.isUpdateable();

    }
    
    private void getSurveyQuestions() { 
             surveyquestions = [select id, name, QuestionText__c, QuestionType__c, QuestionNumber__c, ServiceQuestion__c, Question__c from ProjectServiceQuestion__c
                 where ProjectService__c = :project_serviceID 
                 ORDER BY QuestionNumber__c]; 
                 
             questions = new List<question>();
             Integer cnt = 0;    
             
                 
             Boolean oldtq = true;    
             for (ProjectServiceQuestion__c sq : surveyquestions)    
             {
                 question q = new question(sq);
                 if (q.tq == false && oldtq == true)
                 {
                     //first non template question
                     q.fq = true;
                 
                 }
                 oldtq = q.tq;
                 
                 cnt++;
                 
                 if (cnt == surveyquestions.size() && q.tq == false)
                 {
                     q.lq = true;
                 }
                 
                 questions.add(q);
                 
             }
    }
    
    public PageReference RemoveSurveyQuestion() {
        System.debug('BEFORE DELETE --- ' + surveyquestions.size() + ' -- Psq Id -- ' + param_surveyQuestionID);
        
        List<ProjectServiceQuestionDefinedResponse__c> removesurveyquestiondr = [select id, name  from ProjectServiceQuestionDefinedResponse__c where ProjectServiceQuestion__c =:param_surveyQuestionID LIMIT 1];        
        List<ProjectServiceQuestion__c> removesurveyquestions = [select id, name  from ProjectServiceQuestion__c where id =:param_surveyQuestionID LIMIT 1];        
        delete removesurveyquestiondr;
        delete removesurveyquestions;
        //Comment Versioning Code
        //AppUtil.UpdateProjectVersion(ps.Project__c);
        getSurveyQuestions();
        GenerateManual();
        System.debug('AFTER DELETE --- ' + surveyquestions.size());
        return null;
    }    
    
    public PageReference MoveUp() {
        try
        {
            Integer downnumber;
            Integer upnumber;
            
            List<ProjectServiceQuestion__c> upsq = [select id, name, QuestionNumber__c  from ProjectServiceQuestion__c where id =:param_surveyQuestionID LIMIT 1];        
            if (upsq.size()>0)
            {
                upnumber = Integer.ValueOf(upsq[0].QuestionNumber__c);    
            }
    
            List<ProjectServiceQuestion__c> downsq = [select id, name, QuestionText__c, QuestionType__c, QuestionNumber__c, ServiceQuestion__c from ProjectServiceQuestion__c
                where ProjectService__c = :project_serviceID AND QuestionNumber__c < :upnumber and ServiceQuestion__c = false 
                            order by QuestionNumber__c DESC LIMIT 1]; 

            if (downsq.size()>0)
            {
                downnumber = upnumber - 1;
        
                upsq[0].QuestionNumber__c = downnumber;
                update(upsq);
                
                downsq[0].QuestionNumber__c = upnumber;
                update(downsq);    
        
                getSurveyQuestions();        

           }
           else
           {
                addMessage(ApexPages.Severity.ERROR, 'Cannot move up. This is the first question.');
           }
           
           return null;
            
        }
        catch(Exception e)
        {
            addMessage(ApexPages.Severity.ERROR, e.getMessage());
            return null;
        }
    }    

    public PageReference MoveDown() {
    
        try
        {
            Integer downnumber;
            Integer upnumber;
            
            
            List<ProjectServiceQuestion__c> downsq = [select id, name, QuestionNumber__c  from ProjectServiceQuestion__c where id =:param_surveyQuestionID LIMIT 1];        
            if (downsq.size()>0)
            {
                downnumber = Integer.ValueOf(downsq[0].QuestionNumber__c);    
            }
            
            
            List<ProjectServiceQuestion__c> upsq = [select id, name, QuestionText__c, QuestionType__c, QuestionNumber__c, ServiceQuestion__c from ProjectServiceQuestion__c
                where ProjectService__c = :project_serviceID AND QuestionNumber__c > :downnumber AND ServiceQuestion__c=false
                order by QuestionNumber__c LIMIT 1]; 
    
            if (upsq.size() > 0)
            {
                upnumber = Integer.ValueOf(upsq[0].QuestionNumber__c);
                downsq[0].QuestionNumber__c = upnumber;
                update(downsq);
                
                upsq[0].QuestionNumber__c = downnumber;
                update(upsq);    
        
                getSurveyQuestions();        
                    
            }
            else
            {
                addMessage(ApexPages.Severity.ERROR, 'Cannot move down. This is the last question.');
            }
    
        }
        catch(Exception e)
        {
            addMessage(ApexPages.Severity.ERROR, e.getMessage());            
        }
        return null;
    } 
    
    public PageReference populateNewSBQData(){
        if(newsq.Question__c == null)
        {
            return null;
        }
        
        
        newsqb = [Select Id, Name ,QuestionText__c, QuestionType__c from Question__c where Id = :newsq.Question__c LIMIT 1];
        
        System.debug('AFTER CHANGE --- ' + newsqb.QuestionText__c);
        
        return null;
    }              
    
    public PageReference AddSurveyBankQuestion(){
        if(newsq.Question__c == null)
        {
            return null;
        }
        
        Question__c sqb = [Select Id, Name ,QuestionText__c, QuestionType__c from Question__c where Id = :newsq.Question__c LIMIT 1];
        ProjectServiceQuestion__c[] questionNumber = [SELECT QuestionNumber__c FROM ProjectServiceQuestion__c WHERE ProjectService__c =:project_serviceID AND QuestionNumber__c != null ORDER BY  QuestionNumber__c DESC LIMIT 1];
        
        Integer max = 0;
        if(!questionNumber.isEmpty()){
            max = Integer.valueOf(questionNumber[0].QuestionNumber__c);    
        }
        
        //AggregateResult[] ag = [Select MAX(QuestionNumber__c) MaxNumber FROM ProjectServiceQuestion__c where ProjectService__c =:project_serviceID ];
        //Integer max = Integer.valueof(ag[0].get('MaxNumber'));
        //if (max == null)
        //{
          //  max = 0;
        //}
        
        system.debug('~~~~~ ' + newsq.Question__c +'__'+sqb.id+'__'+sqb.name+'__'+sqb.QuestionText__c+'__'+sqb.QuestionType__c  );
          
        try
        {    
            ProjectServiceQuestion__c sqObj = new ProjectServiceQuestion__c();
            sqObj.ProjectService__c = project_serviceID;
            sqObj.Question__c = sqb.Id;
            sqObj.ServiceQuestion__c = false;
            sqObj.QuestionNumber__c = max + 1;
            system.debug('Variant: ' + ps.variant__c);
            if (ps.variant__c != null)
            {
                List<QuestionVariant__c> qvs = [select id, name from questionvariant__c where question__c = :sqb.Id and variant__c =: ps.variant__c];
                if (qvs.size() > 0)
                {
                    sqObj.QuestionVariant__c = qvs[0].Id;
                }
                
            }
            insert sqObj;        
            

            ProjectServiceQuestionDefinedResponse__c psqdefResp;
            List<ProjectServiceQuestionDefinedResponse__c> psqdfrList = new List<ProjectServiceQuestionDefinedResponse__c>();
            
            List<QuestionDefinedResponse__c> qDefResList = [ SELECT Id, Name, DefinedResponseOrder__c, DefinedResponseText__c  FROM QuestionDefinedResponse__c where Question__c = :sqb.Id]  ;
            for(QuestionDefinedResponse__c qdr : qDefResList )
            {
                system.debug('~~~~~ def resp  ' +'__'+qdr.id+'__'+qdr.name+'__'+qdr.DefinedResponseOrder__c+'__'+qdr.DefinedResponseText__c  );
                psqdefResp =  new ProjectServiceQuestionDefinedResponse__c();
                psqdefResp.ProjectServiceQuestion__c = sqObj.id;
                psqdefResp.QuestionDefinedResponse__c = qdr.Id;
                psqdefResp.EndOfQuestions__c = false;
                if (ps.variant__c != null)
                {
                    List<QuestionDefinedResponseVariant__c> qdrvs = [select id, name from QuestionDefinedResponseVariant__c where questiondefinedresponse__c = :qdr.id and variant__c =: ps.variant__c];
                    if (qdrvs.size() > 0)
                    {
                        psqdefResp.QuestionDefinedResponseVariant__c = qdrvs[0].Id;
                    }
                    
                }
                
                psqdfrList.add(psqdefResp);
            } 
            
            insert psqdfrList;
            
            //Comment Versioning Code
            //AppUtil.UpdateProjectVersion(ps.Project__c);
            GenerateManual();
                    
        }
        catch(Exception ex)
        {
            if (ex.getMessage().Contains('duplicate'))
            {
                addMessage(ApexPages.Severity.ERROR, 'Question already added. Please check and try again.');
            }
            else
            {
                addMessage(ApexPages.Severity.ERROR, ex.getMessage());
            }
            return null;

        
        }
        
        newsq = new ProjectServiceQuestion__c();
        newsqb = new Question__c();        
        
        getSurveyQuestions();
        addMessage(ApexPages.Severity.CONFIRM, 'Question(s) added successfully.');  
        return null;
    }          

    
    /*public PageReference assignCP() {
        PageReference assignPage = Page.Add_Locations;
        assignPage.getParameters().put('retURL','/'+project_serviceID );
        return assignPage;
    }*/
    
    public void GenerateManual(){
        if(proj.Status__c == CONSTANTS.PROJECT_STATUS_BOOKED || proj.Status__c == CONSTANTS.PROJECT_STATUS_LAUNCHED || proj.Status__c == CONSTANTS.PROJECT_STATUS_INPROGRESS )
            {            
                TriggerUtil.skipProjectTrigger = true;
                proj.IsJobManualRegenReqd__c = true;
                update proj;
            }
    }
    

}