src_old/objects/ProjectServiceQuestion__c.object
<CustomObject>
    <description>Relates a Question to a Project Service. Questions from Service Question are added by default when a Service is added to a Project Service. Additional Questions can be added. Project Service Question is related to Project Service Question, Question, and Question Variant.</description>
    <fields>
        <fullName>QuestionNumber__c</fullName>
        <label>Question Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Project Service Question</label>
    <nameField>
        <displayFormat>PSQ-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Service Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/ProjectServiceQuestionWrapper.cls
global class ProjectServiceQuestionWrapper implements Comparable {

    public ProjectServiceQuestion__c ProjectServiceQuestion;
    
    // Constructor
    public ProjectServiceQuestionWrapper(ProjectServiceQuestion__c sq) {
        ProjectServiceQuestion = sq;
    }
    
    // Compare opportunities based on the opportunity amount.
    global Integer compareTo(Object compareTo) {
        
        // Cast argument to OpportunityWrapper
        ProjectServiceQuestionWrapper compareToOppy = (ProjectServiceQuestionWrapper)compareTo;
        
        // The return value of 0 indicates that both elements are equal.
        Integer returnValue = 0;
        if (ProjectServiceQuestion.QuestionNumber__c > compareToOppy.ProjectServiceQuestion.QuestionNumber__c) {
            // Set return value to a positive value.
            returnValue = 1;
        } else if (ProjectServiceQuestion.QuestionNumber__c < compareToOppy.ProjectServiceQuestion.QuestionNumber__c) {
            // Set return value to a negative value.
            returnValue = -1;
        }
        
        return returnValue;       
    }
}