src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ProjectServiceAttribute__c.object
<CustomObject>
    <description>Relates a Service Attribute to a Project Service and prepopulates default values. Service Attribute is related to Service, Project Service Attribute, and Attribute.</description>
    <fields>
        <fullName>AttributeValue__c</fullName>
        <label>Attribute Value</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Project Service Attribute</label>
    <nameField>
        <displayFormat>PSA-{00000000}</displayFormat>
        <label>Project Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Service Attributes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/ProjectServiceAttTriggerHandlerTest.cls
@isTest
public class ProjectServiceAttTriggerHandlerTest {
    static testMethod void test_beforeInsert() {
        Project__c project = TestUtil.generateFullTestProject(ProjectType.MD, Date.Today().AddDays(10), Date.Today().AddDays(60)) ;
    }
    
    static testMethod void test_beforeUpdate() {
        Project__c project = TestUtil.generateFullTestProject(ProjectType.MD, Date.Today().AddDays(10), Date.Today().AddDays(60)) ;
        ProjectServiceAttribute__c psca = [select  AttributeValue__c from ProjectServiceAttribute__c LIMIT 1];
        psca.AttributeValue__c = 'Test';
        update psca;
        psca = [select  AttributeValue__c from ProjectServiceAttribute__c LIMIT 1];
        system.assertEquals(psca.AttributeValue__c, 'Test');
    }
    
}