src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <fields>
        <fullName>ProjectType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Type</label>
        <referenceTo>ProjectType__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planning</fullName>
                    <default>true</default>
                    <label>Planning</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Launched</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ended</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ProjectAccount__c.object
<CustomObject>
    <description>Project Account maps an Account to a Project and defines how the Account will be billed. Project Account is related to Project, Account, and Account Address.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please make sure this account&apos;s &apos;Can Request Project&apos; setting is enabled.</errorMessage>
            <filterItems>
                <field>Account.CanRequestProjects__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Project Accounts</relationshipLabel>
        <relationshipName>Project_Accounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Project_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Account</label>
    <nameField>
        <displayFormat>PA-{0000000}</displayFormat>
        <label>Project Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectInvoice__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Project Invoices</relationshipLabel>
        <relationshipName>Project_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CreditApplied__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Credit Applied</description>
        <inlineHelpText>Credit Applied</inlineHelpText>
        <label>Credit Applied</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExternalInvoiceNumber__c</fullName>
        <externalId>true</externalId>
        <label>External Invoice Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LawsonCompanyCode__c</fullName>
        <label>Lawson Company Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1000</fullName>
                </value>
                <value>
                    <fullName>2025</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ProjectAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Account</label>
        <referenceTo>ProjectAccount__c</referenceTo>
        <relationshipLabel>Project Invoices</relationshipLabel>
        <relationshipName>Project_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Invoices</relationshipLabel>
        <relationshipName>Project_Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Invoiced</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Grouped</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>PreBill</fullName>
                    <label>Pre Bill</label>
                </value>
                <value>
                    <fullName>PostExecution</fullName>
                    <label>Post Execution</label>
                </value>
                <value>
                    <fullName>Reconcile</fullName>
                </value>
                <value>
                    <fullName>Unreconciled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project Invoice</label>
    <nameField>
        <displayFormat>INV-{000000000}</displayFormat>
        <label>Project Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectInvoiceLineItem__c.object
<CustomObject>
    <fields>
        <fullName>AccrualAmount__c</fullName>
        <label>Accrual Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LawsonAccount2__c</fullName>
        <label>Lawson Account</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>4500</fullName>
                </value>
                <value>
                    <fullName>2530</fullName>
                </value>
                <value>
                    <fullName>4600</fullName>
                </value>
                <value>
                    <fullName>2590</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LawsonDivision__c</fullName>
        <label>Lawson Division</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>4155</fullName>
                </value>
                <value>
                    <fullName>999</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LawsonSubAccount2__c</fullName>
        <label>Lawson Sub Account</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0000</fullName>
                </value>
                <value>
                    <fullName>7605</fullName>
                </value>
                <value>
                    <fullName>7606</fullName>
                </value>
                <value>
                    <fullName>230</fullName>
                </value>
                <value>
                    <fullName>238</fullName>
                </value>
                <value>
                    <fullName>246</fullName>
                </value>
                <value>
                    <fullName>210</fullName>
                </value>
                <value>
                    <fullName>100</fullName>
                </value>
                <value>
                    <fullName>450</fullName>
                </value>
                <value>
                    <fullName>400</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LawsonUnit2__c</fullName>
        <label>Lawson Unit</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>4155</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Project Invoice Line Items</relationshipLabel>
        <relationshipName>Project_Invoice_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectInvoice__c</fullName>
        <label>Project Invoice</label>
        <referenceTo>ProjectInvoice__c</referenceTo>
        <relationshipLabel>Project Invoice Line Items</relationshipLabel>
        <relationshipName>Project_Invoice_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>QuantityOverride__c</fullName>
        <label>Quantity Override</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ServiceType__c</fullName>
        <label>Service Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Labor</fullName>
                </value>
                <value>
                    <fullName>Product</fullName>
                </value>
                <value>
                    <fullName>SalesTax</fullName>
                </value>
                <value>
                    <fullName>Unreconciled</fullName>
                </value>
                <value>
                    <fullName>PB Applied</fullName>
                </value>
                <value>
                    <fullName>Payment</fullName>
                </value>
                <value>
                    <fullName>Lawson</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Usage</fullName>
                </value>
                <value>
                    <fullName>Lumpsum</fullName>
                </value>
                <value>
                    <fullName>Unreconciled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project Invoice Line Item</label>
    <nameField>
        <displayFormat>INVLI-{000000000}</displayFormat>
        <label>Project Invoice Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectType__c.object
<CustomObject>
    <description>Project Type defines a collection of Services and sets configuration options for a Project. Project Type is related to Project, Project Type Execution Company, Project Type Service, and Location Assignment.</description>
    <fields>
        <fullName>CreateInvoice__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Create Invoice</label>
        <type>Checkbox</type>
    </fields>
    <label>Project Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Types</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/BatchProcessApplyPBCredit.cls
global class BatchProcessApplyPBCredit implements Database.Batchable<sObject>, Database.Stateful {
    boolean hasError = false;        
    List<Object> responses {get; set;}
    ApexJobTracker apexTracker {get; set;}
    String projecttypeid;
    global BatchProcessApplyPBCredit() {
        this.initTrackerAndProjectType();
    }
    
    void initTrackerAndProjectType() {
        this.responses = new List<Object>();        
        
        this.apexTracker = ApexJobTracker.create(projecttypeid, ApexJobTracker.TrackerTarget.ProjectInvoice,
                                                 ApexJobTracker.TrackerOperation.Apply_PB_Credit)
            .save();
    }
    
    String getInvoiceProjectTypeId() {
        List<ProjectType__c> pts = [Select Id FROM ProjectType__c WHERE CreateInvoice__c = true];
        if (pts.size() > 0) {
            return pts[0].Id;
        }
        throw new CustomException('The project type that can create invoice is not defined.');
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        
        if (this.apexTracker.Status != ApexJobTracker.TrackerStatus.In_Progress) {
            this.apexTracker.setStatus(ApexJobTracker.TrackerStatus.In_Progress)
                .save();
        }
        
        // To get Pre Bill invoice for which credit is not applied            
        return Database.getQueryLocator([Select Id, Name, ProjectInvoice__c, ProjectInvoice__r.Name, Type__c, ServiceType__c, Product__c, Amount__c,
                                         Rate__c, AccrualAmount__c, ProjectInvoice__r.ProjectAccount__c,
                                         ProjectInvoice__r.ExternalInvoiceNumber__c, LawsonDivision__c,
                                         LawsonUnit2__c, LawsonAccount2__c, LawsonSubAccount2__c, ProjectInvoice__r.LawsonCompanyCode__c
                                         From ProjectInvoiceLineItem__c
                                         WHERE ProjectInvoice__r.Type__c = :Constants.PROJECT_INVOICE_TYPE_PREBILL
                                         AND ProjectInvoice__r.CreditApplied__c = false 
                                         AND ProjectInvoice__r.Status__c != :Constants.PROJECT_INVOICE_STATUS_CANCELED
                                        ]);
    }
    
    global void execute(Database.BatchableContext BC, List<ProjectInvoiceLineItem__c> scope) {
        
        List<Object> result = new List<Object>();
        try{
            
            List<ProjectInvoiceLineItem__c> newpiliList = new List<ProjectInvoiceLineItem__c>();
            List<ProjectInvoice__c> newpiList = new List<ProjectInvoice__c>();
            Map<string, ProjectInvoiceLineItem__c> preBillMap = new Map<string, ProjectInvoiceLineItem__c>();        
            
            Set<String> projectAccountIds = new Set<String>();
            Set<String> piNeededForprojectAccountIds = new Set<String>();
            List<string> preBillProjectInvoice = new List<string>();
            
            for(ProjectInvoiceLineItem__c Pili : scope){
                preBillMap.put(pili.ProjectInvoice__r.ProjectAccount__c, pili);
                projectAccountIds.add(Pili.ProjectInvoice__r.ProjectAccount__c);
            }
            
            List<ProjectInvoiceLineItem__c> piliList = [SELECT Id, Name,
                                                        ProjectInvoice__c, 
                                                        ProjectInvoice__r.ProjectAccount__c, 
                                                        ProjectInvoice__r.LawsonCompanyCode__c 
                                                        FROM ProjectInvoiceLineItem__c
                                                        WHERE ProjectInvoice__r.ProjectAccount__c IN :projectAccountIds AND
                                                        ProjectInvoice__r.Status__c = :CONSTANTS.PROJECT_INVOICE_STATUS_CREATED AND
                                                        ProjectInvoice__r.Type__c = :CONSTANTS.PROJECT_INVOICE_TYPE_POSTEXECUTION AND
                                                        ProjectInvoice__r.LawsonCompanyCode__c = :CONSTANTS.LAWSON_COMPANY_CODE_US AND
                                                        ServiceType__c = :CONSTANTS.PROJECT_INVOICE_LINEITEM_SERVICETYPE_LABOR];
            
            Set<String> piIds = new Set<String>();
            for(ProjectInvoiceLineItem__c pili : piliList){
                piIds.add(pili.ProjectInvoice__c);
            }
            
            List<ProjectInvoice__c> piList = [SELECT Id, Name, ProjectAccount__c, LawsonCompanyCode__c 
                                              FROM ProjectInvoice__c
                                              WHERE ID IN :piIds];
            
            /*                        
Map<string, ProjectInvoice__c> paProjectInvoiceMap = new Map<string, ProjectInvoice__c>();
for(ProjectInvoice__c pi : piList){
paProjectInvoiceMap.put(pi.ProjectAccount__c, pi);
}                                

for(ProjectInvoiceLineItem__c Pili : scope){                        
if (paProjectInvoiceMap.get(Pili.ProjectInvoice__r.ProjectAccount__c) == null) {
piNeededForprojectAccountIds.add(Pili.ProjectInvoice__r.ProjectAccount__c);                
}
}

List<ProjectAccount__c> projectAccountList = [SELECT Id, Account__c, Project__c
FROM ProjectAccount__c
WHERE
Id in :piNeededForprojectAccountIds];

for(ProjectAccount__c pa : projectAccountList){
newpiList.add(CreateProjectInvoice(pa, CONSTANTS.LAWSON_COMPANY_CODE_US));
}        

result.add(AppUtil.analyzeSaveResultList('insert ProjectInvoice for Credit', Database.Insert(newpiList)));

piList.addAll(newpiList);
*/
            
            for(ProjectInvoice__c newpi : piList){
                
                ProjectInvoiceLineItem__c preBillPiliForPa = preBillMap.get(newpi.ProjectAccount__c);
                
                ProjectInvoiceLineItem__c pili = new ProjectInvoiceLineItem__c();
                pili.ProjectInvoice__c = newpi.Id;
                pili.Type__c = Constants.PROJECT_INVOICE_LINEITEM_TYPE_LUMPSUM;
                pili.ServiceType__c = Constants.PROJECT_INVOICE_LINEITEM_SERVICETYPE_PB_APPLIED;
                pili.Product__c = preBillPiliForPa.Product__c;
                pili.Amount__c = preBillPiliForPa.Amount__c != null ? preBillPiliForPa.Amount__c * -1 : preBillPiliForPa.Amount__c;
                pili.Rate__c = preBillPiliForPa.Rate__c != null ? preBillPiliForPa.Rate__c * -1 : preBillPiliForPa.Rate__c;
                pili.AccrualAmount__c = preBillPiliForPa.AccrualAmount__c;
                pili.QuantityOverride__c = 1;
                pili.Description__c = preBillPiliForPa.ProjectInvoice__r.ExternalInvoiceNumber__c == null ? 'External Invoice Number Not Available' : 
                'Less Pre-bill invoice ' + preBillPiliForPa.ProjectInvoice__r.ExternalInvoiceNumber__c;
                pili.LawsonDivision__c = Constants.LAWSON_DIVISION;
                pili.LawsonUnit2__c = Constants.LAWSON_UNIT;
                pili.LawsonAccount2__c = Constants.LAWSON_ACCOUNT;
                pili.LawsonSubAccount2__c = Constants.LAWSON_SUB_ACCOUNT;
                
                pili.LineItemOrder__c = AppUtil.CreditLineItemOrder;
                newpiliList.add(pili);        
                preBillProjectInvoice.add(preBillPiliForPa.ProjectInvoice__c);
            }
            
            result.add(AppUtil.analyzeSaveResultList('Insert Project Invoice Line Item for Credit', Database.Insert(newpiliList)));
            
            // To set credit applied flag as true for prebill invoice
            List<ProjectInvoice__c> preBillProjectInvoiceToUpdate = [SELECT Id, Name, CreditApplied__c
                                                                     FROM ProjectInvoice__c
                                                                     WHERE Id IN :preBillProjectInvoice];
            
            if (preBillProjectInvoiceToUpdate != null) {
                for (ProjectInvoice__c preBillPi : preBillProjectInvoiceToUpdate) {
                    preBillPi.CreditApplied__c = true;
                }
            }
            
            result.add(AppUtil.analyzeSaveResultList('PreBillProjectInvoice', Database.Update(preBillProjectInvoiceToUpdate)));                
        } catch (Exception ex) {
            result.add(genError(ex));
            this.responses.add(result);
            hasError = true;
        }
    }
    
    
    global void finish(Database.BatchableContext BC) {
        this.apexTracker
            .setStatus(ApexJobTracker.TrackerStatus.Success)
            .setResponse(JSON.serialize(this.responses));
        
        List<AsyncApexJob> aList = [SELECT NumberOfErrors FROM AsyncApexJob WHERE Id = :BC.getJobId()];
        if (!aList.isEmpty() && aList[0].NumberOfErrors > 0 || this.hasError) {
            this.apexTracker.setStatus(ApexJobTracker.TrackerStatus.Failure);
        }
        
        this.apexTracker.save();        
        
        //to clear batch processed
        EndProcess('ProjectInvoice');   
    }
    
    Map<String, Object> genError(Exception ex) {
        Map<String, Object> err = new Map<String, Object>();
        err.put('topic', 'exception');
        err.put('messages', new Object[] {ex.getMessage(), ex.getLineNumber(), ex.getStackTraceString()});
        return err;
    }
    
    public static void EndProcess(String entity){
        
        List<ProcessLastSyncTime__c> plsts = [Select Id, CurrentProcessId__c 
                                              From ProcessLastSyncTime__c 
                                              WHERE ProcessName__c =: entity LIMIT 1];                
        if (!plsts.isEmpty()){
            plsts[0].CurrentProcessId__c = '';            
            update plsts[0];
        }
    }
    
    
    public ProjectInvoice__c CreateProjectInvoice(ProjectAccount__c pa, String lawsonCountryCode) {
        ProjectInvoice__c pi = new ProjectInvoice__c();
        pi.Project__c = pa.Project__c;
        pi.Status__c = Constants.PROJECT_INVOICE_STATUS_CREATED;
        pi.Type__c = Constants.PROJECT_INVOICE_TYPE_POSTEXECUTION;
        pi.LawsonProcessType__c = Constants.LAWSON_PROCESS_TYPE_PE;
        pi.LawsonCompanyCode__c = lawsonCountryCode;
        pi.Account__c = pa.Account__c;
        pi.ProjectAccount__c = pa.Id;
        return pi;
    }
    
}
//Test