src_old/objects/Project__c.object
<CustomObject>
    <description>Project is the primary container that is used to define work within the system. Project is related to Program, Cycle, Job, Project Account, Project Location, Project Service, and Project Type.</description>
    <label>Project</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ProjectService__c.object
<CustomObject>
    <description>Project Service relates a Service to a Project and is a container used to define the instance of a Service for a specific Project. Project Service is related to Project, Job, Project Service Attribute, Project Service Certification, Project Service Equipment, Project Service Material, Project Service Question, Project Service Target, and Service.</description>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>ProjectServices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Service</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ProjectServiceAttribute__c.object
<CustomObject>
    <description>Relates a Service Attribute to a Project Service and prepopulates default values. Service Attribute is related to Service, Project Service Attribute, and Attribute.</description>
    <fields>
        <fullName>ProjectService__c</fullName>
        <label>Project Service</label>
        <referenceTo>ProjectService__c</referenceTo>
        <relationshipLabel>Project Service Attributes</relationshipLabel>
        <relationshipName>Project_Service_Attributes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Service Attribute</label>
    <nameField>
        <displayFormat>PSA-{00000000}</displayFormat>
        <label>Project Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Service Attributes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/GenerateURLTest.cls
@isTest
public class GenerateURLTest {

    public static testMethod void Method_Test(){
        Project__c project = TestUtil.generateFullTestProject(ProjectType.MD, System.today().addDays(60), System.today().addDays(70));    
        projectservice__c ps = [select id from projectservice__c where project__c = : project.id limit 1];
        ProjectServiceAttribute__c psca = [select id from ProjectServiceAttribute__c limit 1];
        //Attachment attmnt = [Select ID, ParentID, body, Name from Attachment limit 1];
        //system.debug('~~~~'+attmnt.id);
        //Test.startTest();
        for(Attachment attmnt : [Select ID, ParentID, body, Name from Attachment])
        {
            GenerateURL.GenerateNewURL(psca.ID, attmnt.id);
            //GenerateURL.UpdateURL('https://api.crossmark.com/ImageService/test', attmnt.id);    
        }
        //Test.stopTest();         
    }  
    public static testMethod void Method_Test2(){
        Project__c project = TestUtil.generateFullTestProject(ProjectType.MD, System.today().addDays(60), System.today().addDays(70));    
        projectservice__c ps = [select id from projectservice__c where project__c = : project.id limit 1];
        ProjectServiceAttribute__c psca = [select id from ProjectServiceAttribute__c limit 1];
        //Attachment attmnt = [Select ID, ParentID, body, Name from Attachment limit 1];
        //system.debug('~~~~'+attmnt.id);
        //Test.startTest();
        for(Attachment attmnt : [Select ID, ParentID, body, Name from Attachment])
        {
            //GenerateURL.GetURL(psca.ID, attmnt.id);
            //GenerateURL.UpdateURL('https://api.crossmark.com/ImageService/test', attmnt.id);    
        }
        //Test.stopTest();         
    }    
    
}