src_old/objects/ProjectType__c.object
<CustomObject>
    <description>Project Type defines a collection of Services and sets configuration options for a Project. Project Type is related to Project, Project Type Execution Company, Project Type Service, and Location Assignment.</description>
    <label>Project Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Types</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src_old/objects/ProjectTypeCustomSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Project Type Configuration Settings</description>
    <fields>
        <fullName>ProjectCompletionStrategyClass__c</fullName>
        <label>Project Completion Strategy Class</label>
        <length>140</length>
        <type>Text</type>
    </fields>
    <label>ProjectTypeCustomSettings</label>
</CustomObject>

src_old/classes/ProjectCompletionStrategyFactory.cls
public with sharing class ProjectCompletionStrategyFactory {
    public static ProjectCompletionStrategy getProjectCompletionStrategy(ID projectTypeID){
        String projectCompletionStrategy = 'BaseProjectCompletionStrategy';
        String projectTypeName = [Select Name From ProjectType__c WHERE ID = :projectTypeID].Name;
        ProjectTypeCustomSettings__c cs = ProjectTypeCustomSettings__c.getValues(projectTypeName);
        if(cs != null && cs.ProjectCompletionStrategyClass__c!=null){
            projectCompletionStrategy = cs.ProjectCompletionStrategyClass__c;
        }
        return (ProjectCompletionStrategy)Type.forName(projectCompletionStrategy).newInstance();
    }
}