src_old/objects/Question__c.object
<CustomObject>
    <description>Question stores all of the questions stored in the system and defines the type of question (e.g. Date, Text, Y/N) and if the question is related to targets. Question is related to Question Defined Response, Question Variant.</description>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/objects/QuestionDefinedResponse__c.object
<CustomObject>
    <description>Question Defined Response defines the acceptable responses for a Question. Question Defined Response is related to Question and Question Defined Response Variant.</description>
    <fields>
        <fullName>DefinedResponseText__c</fullName>
        <label>Defined Response Text</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Question Defined Response (SurveyQuestionBank)</relationshipLabel>
        <relationshipName>Question_Defined_Response1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Question Defined Response</label>
    <nameField>
        <displayFormat>QBDR-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Defined Response</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/objects/ServiceQuestion__c.object
<CustomObject>
    <description>Service Question relates one or more Questions to a Service and defines how the questions are rendered when building a Project Service. Service Question is related to Service, Question, and Project Service Question.</description>
    <fields>
        <fullName>CanRemove__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Can Remove</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Service Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Service Question</label>
    <nameField>
        <displayFormat>SQ-{00000000}</displayFormat>
        <label>Service Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/objects/ServiceQuestionDefinedResponse__c.object
<CustomObject>
    <description>Service Question Defined Response relates a Question Defined Response to a Service Question. Service Question Defined Response is related to Service Question and Project Service Question Defined Response.</description>
    <fields>
        <fullName>CanRemove__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Can Remove</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DefinedResponseText__c</fullName>
        <description>The text that will be shown for this response</description>
        <formula>QuestionDefinedResponse__r.DefinedResponseText__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The text that will be shown for this response</inlineHelpText>
        <label>Defined Response Text</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QuestionDefinedResponse__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Question Defined Response</label>
        <referenceTo>QuestionDefinedResponse__c</referenceTo>
        <relationshipLabel>Service Question Defined Responses</relationshipLabel>
        <relationshipName>Service_Questions_Jump</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ServiceQuestion__c</fullName>
        <label>Service Question</label>
        <referenceTo>ServiceQuestion__c</referenceTo>
        <relationshipLabel>Service Question Defined Responses</relationshipLabel>
        <relationshipName>Service_Questions_Jump</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Service Question Defined Response</label>
    <nameField>
        <displayFormat>SQDR-{00000000}</displayFormat>
        <label>Service Question Defined Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Question Defined Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src_old/classes/QuestionDefinedResponseHandler.cls
public class QuestionDefinedResponseHandler extends TriggerHandler {
    
    public override void afterInsert(){
        if (TriggerUtil.skipQuestionDefinedResponseTrigger) return;
        //TriggerUtil.skipQuestionDefinedResponseTrigger = true; 
        set<Id>sQuestions = New set<Id>();
        Map<Id,List<QuestionDefinedResponse__c>> mapQDR = new Map<Id,list<QuestionDefinedResponse__c >>();
        List<ServiceQuestionDefinedResponse__c>lstSQDR= new  List<ServiceQuestionDefinedResponse__c>();
        for (QuestionDefinedResponse__c qdr: (List<QuestionDefinedResponse__c> ) Trigger.new) {
         sQuestions .add(qdr.Question__c);
            
        }
        
        for(Id question :sQuestions )
        {
            List<QuestionDefinedResponse__c> lstQDR = new List<QuestionDefinedResponse__c >();
            for (QuestionDefinedResponse__c qdr: (List<QuestionDefinedResponse__c> ) Trigger.new) {
                
                if(question == qdr.Question__c)
                {
                    lstQDR.add(qdr);
                    
                }
                
            }
            
            mapQDR.put(question,lstQDR);
        }
        
        List<ServiceQuestion__c> lsq = [Select Id,Question__c from ServiceQuestion__c  where  Question__c  IN :mapQDR.keyset()];
        
        for(  ServiceQuestion__c sq: lsq )
        {
            List<QuestionDefinedResponse__c> lstQuestionDefinedResponse =(List<QuestionDefinedResponse__c>)mapQDR.get(sq.Question__c);
            
            for (QuestionDefinedResponse__c qdr: lstQuestionDefinedResponse )
            {
                
                ServiceQuestionDefinedResponse__c sqdefResp = new ServiceQuestionDefinedResponse__c();
                sqdefResp.ServiceQuestion__c = sq.Id;
                sqdefResp.QuestionDefinedResponse__c =qdr.Id;
                //sqdefResp.DefinedResponseText__c = qdr.DefinedResponseText__c;
                sqdefResp.isActive__c=false;
                sqdefResp.CanRemove__c = false;
                lstSQDR.add(sqdefResp);
                
                
            } 
            
        }
        
        if(lstSQDR.size()>0)
        {
            insert lstSQDR;
        }
        
    }
    
}