src_old/objects/Reservation__c.object
<CustomObject>
    <fields>
        <fullName>ExpirationDate__c</fullName>
        <description>Expiration date defines a date where the Reservation will be moved to the Expired status if it has not move to the reserved state.</description>
        <inlineHelpText>This date defines when the reservation will automatically expire if the reservation doesn&apos;t get approved/reserved.</inlineHelpText>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Isexpirable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Auto-expire will only happen when flag is checked</description>
        <label>Is expirable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>&apos;Draft&apos;</defaultValue>
        <description>Status of the reservation</description>
        <inlineHelpText>Status of the Reservation.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Reserved</fullName>
                    <label>Booked</label>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Reservation</label>
    <nameField>
        <label>Reservation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src_old/classes/ScheduledReservationRequestProcecssor.cls
global class ScheduledReservationRequestProcecssor implements Schedulable {
    public static String CRON_EXP = '0 0 * * * ?';
    
    global static String schedule() {
        ScheduledReservationRequestProcecssor sch = new ScheduledReservationRequestProcecssor ();
        return System.schedule('Reservation Request Processor', CRON_EXP, sch);
    }
    
    global void execute(SchedulableContext sc) {
        system.debug('**ScheduledReservationRequestProcecssor Execute**');
        //First check if any reservation has expired
        //EXPIRED RESERVATIONS
        Date todaysDate = system.Today();
        List<Reservation__c> expiredReservations = [SELECT Id, Name, Status__c
                                                    FROM Reservation__c 
                                                    WHERE ExpirationDate__c < :todaysDate AND 
                                                    Isexpirable__c = true LIMIT 1];
        if (!expiredReservations.isEmpty())
        {
            ReservationHelper.ExpireReservation(expiredReservations[0].Id);
        }
        
        ReservationHelper.notifyReservationExpiration();
    }
}