src_old/objects/Retailer__c.object
<CustomObject>
    <description>Retailer stores the retailers for the system. Retailer is related to Location, Retailer Service, Retailer Service Certification, and Retailer Service Equipment.</description>
    <fields>
        <fullName>FulfillmentLeadTime__c</fullName>
        <label>Fulfillment Lead Time</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LogoHeight__c</fullName>
        <label>Logo Height</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LogoURL__c</fullName>
        <label>Logo URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>OneHubRetailerId__c</fullName>
        <label>One Hub Retailer ID</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ProjectCancelLeadTime__c</fullName>
        <label>Project Cancel Lead Time</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TargetAcquiredDefault__c</fullName>
        <label>Target Acquired Default</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Purchased</fullName>
                </value>
                <value>
                    <fullName>Donated</fullName>
                </value>
                <value>
                    <fullName>Kitted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Retailers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>isMaterialReqd__c</fullName>
        <defaultValue>true</defaultValue>
        <description>To determine if materials are needed for this retailer.</description>
        <label>Is Material Reqd</label>
        <type>Checkbox</type>
    </fields>
    <label>Retailer</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Retailers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/AddEditRetailerExt.cls
public with sharing class AddEditRetailerExt {
    public ApexPages.StandardController controller;
    public Retailer__c Retailer {get;set;}
    public string BODates {get; set;}
    
    public String mode {get; set;} 
        
    public AddEditRetailerExt(ApexPages.StandardController controller) {
    
        try {
            string retlID = ApexPages.currentPage().getParameters().get('id');
            if(retlID != null &&  retlID !=''){
                mode = 'edit';
                Retailer = [select name,user__c,isMaterialReqd__c, LogoURL__c, LogoHeight__c, OneHubRetailerId__c, TargetAcquiredDefault__c, ProjectCancelLeadTime__c, FulfillmentLeadTime__c from retailer__c where ID =: retlID limit 1];            
               
            }
            else{
                mode = 'add';
                Retailer = new retailer__c();  
            }
        }
        catch(Exception ex)
        {
            Apexpages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Unexpected error occurred. Please try later.'));
        }
    }

    public PageReference save() {
        try{
        
            if(mode == 'add'){
                insert Retailer; 
            }
            else{
                upsert retailer;
                           
            }
            Apexpages.addMessage(new ApexPages.Message(ApexPages.Severity.Info, 'Successfully saved.'));
            
            PageReference psPage = new ApexPages.StandardController(Retailer).view();
            psPage.setRedirect(true);
            return psPage;
            
        }    
        catch(Exception ex)
        {
            Apexpages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Unexpected error occurred. Please try later.'));
        }
        return null;
    }
    

}